### ISSUE TITLE
Use proper package names

### ISSUE THREAD

**Issue by durban** [zio/zio#1004]
Since the package names are changing anyway, maybe it's not too late to change them to the reverse domain name (i.e., `dev.zio._`).

**Comment by kaishh** [comment]
Eh, IMHO just `zio` is better. Definitely more concise!

**Comment by iravid** [comment]
Have to agree with @kaishh

**Comment by durban** [comment]
I don't buy it. It's just 4 additional characters (7 total), and in return we don't screw with people who may want to create, e.g., some zio interop packages in their projects (`foo.bar.interop.zio`).

**Comment by ghostdogpr** [comment]
Closing this one as there seems to be consensus for keeping the current package name.
