### ISSUE TITLE
Microsite deployment failure investigation during release deploy

### ISSUE THREAD

**Issue by softinio** [zio/zio#1011]
see https://circleci.com/gh/zio/zio/1315

**Comment by ghostdogpr** [comment]
It fails because the SSH key requires a passphrase, but CircleCI doesn’t support it (https://circleci.com/docs/2.0/add-ssh-key/). 
@Nequissimus can you make one without passphrase?

**Comment by NeQuissimus** [comment]
I did, fingerprint is `b3:9b:af:d5:de:74:32:e7:7a:21:77:77:66:fe:2f:42`

**Comment by ghostdogpr** [comment]
Reopening as the microsite deployment still fails.
Now the error is happens during `Install Yarn`: `ERROR: This command can only be used by root.`

**Comment by ghostdogpr** [comment]
I fixed a number of issues happening during the microsite release but I’m now stuck with that one:
```
[2/4] Fetching packages...
error @babel/core@7.4.5: The engine "node" is incompatible with this module. Expected version ">=6.9.0". Got "6.1.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I did install the latest version of node and npm so I’m not sure why this happens. 
Anyone has an idea? @softinio @iravid @NeQuissimus

**Comment by softinio** [comment]
@ghostdogpr found what the issue was PR ready for you to review #1068
