### ISSUE TITLE
Add `timezone` to DefaultRuntime.Environment

### ISSUE THREAD

**Issue by scurvydoggo** [zio/zio#1012]
We are finding `zio` is a great way to mocking the non-deterministic aspects of our app.

One gap that caught us out though was the absence of a `timezone` field for us to override in any of the default modules, which resulted in different timestamps being generated in our CI environment when the unit tests ran.

To work around this, we've introduced a new `TimeZone` module, which uses `ZoneId.systemDefault` in `TimeZoneLive`, but in our tests we set this explicitly.

It seems a bit overkill to add a whole new module for this though, and `timezone` could instead fit alongside the other fields in `Clock`. Though perhaps then `Clock` needs to be broadened, and given a new name like `Time` in order to accommodate this.

**Comment by spf3000** [comment]
^^ If someone wants to look at the above PR - it's my first attempt at contributing to zio, so you may have to work with me a little - thanks in advance.
