### ISSUE TITLE
Fix tests with Dotty

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1022]
Somehow we are not actually running the tests with Dotty.

When I do, these errors pop up:

```
Exception in thread "specs2-3" java.lang.NoSuchMethodError: org.specs2.specification.create.S2StringContextCreation$specificationInStringContext.s2(Lscala/collection/Seq;)Lorg/specs2/specification/core/Fragments;
	at zio.FunctionIOSpec.is$$anonfun$1(FunctionIOSpec.scala:30)
	at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:26)
	at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:26)
```

**Comment by kaishh** [comment]
https://github.com/zio/zio/issues/1021#issuecomment-504658152

`s2` is a macro, so that method really doesn't exist... We'll have to drop all s2's to support dotty.

**Comment by softinio** [comment]
Related: #1208

**Comment by ghostdogpr** [comment]
The failing test has been migrated to ZIO Test so maybe we could get this unblocked. 

@adamgfraser ever tried ZIO Test on dotty?

**Comment by adamgfraser** [comment]
@ghostdogpr I tried a while back and the issue I ran into is that we depend on ZIO Streams which does not compile on Dotty yet so I think we are blocked on this until #1524 is resolved.

**Comment by ghostdogpr** [comment]
Oh i see, thanks!

**Comment by softinio** [comment]
I thought the issue with running tests with dotty was due to dotty not supporting macros & spec2 tests we have uses macros 🤷🏻‍♂️

**Comment by adamgfraser** [comment]
Right but I think part of the goal for migrating from Specs2 to ZIO Test was that ZIO Test would be completely cross-version and cross-platform so we could run our tests on Dotty. We're just not 100% there yet.

**Comment by adamgfraser** [comment]
This was fixed by migration to ZIO Test and at this point we are running all tests on Scala 3.
