### ISSUE TITLE
Flaky runtime test

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1023]
This test loves to time out

```
[info]   RTS concurrency correctness
[info]     + shallow fork/join identity
[info]     + deep fork/join identity
[info]     + asyncPure creation is interruptible
[info]     + asyncInterrupt runs cancel token on interrupt
[info]     + supervising returns fiber refs
[info]     + supervising in unsupervised returns Nil
[info]     + supervise fibers
[error]     x supervise fibers in supervised
[error]  TIMEOUT: 60 seconds (TestRuntime.scala:18)
```

Last observed with Scala 2.12 and JDK 8

**Comment by jdegoes** [comment]
```scala
  def testSupervised =
    unsafeRun(for {
      pa <- Promise.make[Nothing, Int]
      pb <- Promise.make[Nothing, Int]
      _ <- (for {
            p1 <- Promise.make[Nothing, Unit]
            p2 <- Promise.make[Nothing, Unit]
            _ <- p1
                  .succeed(())
                  .bracket_[Any, Nothing]
                  .apply[Any](pa.succeed(1).unit)(IO.never)
                  .fork //    TODO: Dotty doesn't infer this properly
            _ <- p2.succeed(()).bracket_[Any, Nothing].apply[Any](pb.succeed(2).unit)(IO.never).fork
            _ <- p1.await *> p2.await
          } yield ()).interruptChildren
      r <- pa.await zip pb.await
    } yield r) must_=== (1 -> 2)
```

**Comment by jdegoes** [comment]
This test, as convoluted as it is, looks correct to me. 

Meaning the problem may be in `bracket_` or `interruptChildren` or something lower level.

**Comment by iravid** [comment]
Hmm FWIW ive seen “returns fiber refs” time out as well.

**Comment by ghostdogpr** [comment]
There are several tests that are flaky in RTSSpec, the common point from what I’ve seen is that they all involve supervision. 

With the multiplication of test configurations (jdk11, 2.11, js, etc) it became extremely difficult not to run into it :/

**Comment by wongelz** [comment]
The "returns fiber refs" test sometimes fails with : `'WrappedArray(zio.internal.FiberContext@867d0ad)' doesn't have size 2 but size 1`

**Comment by jdegoes** [comment]
@ghostdogpr @wongelz See [here](https://github.com/zio/zio/pull/1063)

Still more work to do on the fundamental problem `supervise fibers in supervised`

**Comment by wongelz** [comment]
@jdegoes  I'm still seeing the same test failure in "return fiber refs" unfortunately.

But looks like you're on the right track though - if I put `_ <- ZIO.effectTotal(System.gc())` anywhere in "supervise fibers in supervised" it times out every single time.

**Comment by iravid** [comment]
I have some thoughts on the GC eating up the weak set unexpectedly:
- I'd be *really* caught off-guard by this if I wrote something that uses `ZIO.children` and my child fibers were not visible in the returned list (and if we formulated laws for the interaction between `fork` and `children` they'd definitely be violated)
- On the other hand, making this not be a weak set by default would wreak havoc on memory usage for long running fibers using supervision and spawning many fibers. 

Another thought is that allowing a parent fiber to strongly reference (potentially thousands of) child fibers is, many times, an inefficient formulation; embedding the supervision logic into the children themselves can sometimes be much more memory efficient.

**Comment by jdegoes** [comment]
@wongelz 

Hmmm. The hard refs in `return fiber refs` _should_ prevent garbage collection of the fibers. Operative word being _should_.

It could be it's getting removed from the weak set _before_ it's actually garbage collected. 

@iravid I have some thoughts about this, will write them up shortly.

**Comment by LGLO** [comment]
```
[info]   RTS concurrency correctness
[info]     + shallow fork/join identity
[info]     + deep fork/join identity
[info]     + asyncPure creation is interruptible
[info]     + asyncInterrupt runs cancel token on interrupt
[error]     x supervising returns fiber refs
[error]  'Vector(zio.internal.FiberContext@f4ed175)' doesn't have size 2 but size 1 (RTSSpec.scala:1104)
```

**Comment by ghostdogpr** [comment]
Closing since supervision has been completely overhauled.
