### ISSUE TITLE
Add generic 'toManaged' conversion from Resource to Managed

### ISSUE THREAD

**Issue by andreamarcolin** [zio/zio#1028]
Due to 'toManaged' being defined only for `Resource[cats.effect.IO, A]`, it is currently not possible to convert a `Resource[Task, A]` to a `ZManaged`.

A notable example of this limitation include trying to get a Managed from a `Resource[Task, HikariTransactor[Task]]` when using doobie, and also when using Http4s, as reported by several users on gitter.

This problem was already referenced in [the original PR](https://github.com/zio/zio/pull/827#discussion_r281039409) (thanks to @ghostdogpr for the pointer) implementing ZManaged <-> Resource interop, but went probably unnoticed.

**Comment by andreamarcolin** [comment]
I can try to take a stab at this if no one volunteers :)
@jdegoes can you maybe give some advice on how to tackle this problem since you reviewed the above mentioned PR? It would be great help. Thank you

**Comment by jdegoes** [comment]
@andreamarcolin 

First, you'll have to change this:

```scala
final class CatsIOResourceSyntax[A](private val resource: Resource[CIO, A]) extends AnyVal {
```

Instead, accept any `F[_]` for which there is a `ConcurrentEffect`. 

Then you can `mapK` over the `Resource`, translating the `F[_]` into `CIO` (Cats `IO`), and then do what the code is doing now.

This is not the most efficient way but it will get the job done.

/cc @mschuwalow
