### ISSUE TITLE
ZStream#mapAccumM should take a ZIO instead of just IO as parameter

### ISSUE THREAD

**Issue by andreamarcolin** [zio/zio#1029]
ZStream#mapAccumM should be generalized to take a ZIO as a parameter instead of IO, in order to be able to use ZIO's environment in the effect. 

Actual signature: 
```scala 
final def mapAccumM[E1 >: E, S1, B](s1: S1)(f1: (S1, A) => IO[E1, (S1, B)]): ZStream[R, E1, B]
```
Proposed signature: 
```scala 
final def mapAccumM[R1 <: R, E1 >: E, S1, B](s1: S1)(f1: (S1, A) => ZIO[R1, E1, (S1, B)]): ZStream[R1, E1, B]
```

Edit: fixed return type of proposed signature (ZStream env type parameter)

**Comment by andreamarcolin** [comment]
@iravid I can work on this as I told on gitter, but please confirm I am in the right path with the signature :) 
The implementation is quite complex for my actual FP level, but from what I can understand, inner fold already accepts a R1 <: R, so I should be able to just move the type bound to the outer signature and modify it as described above

**Comment by iravid** [comment]
Hi Andrea, the `R1 <: R` is part of the definition of `ZStream`'s interface. You'll need to introduce an `R1` on `mapAccumM`, and use `R2 <: R1` on the constructed stream instance.

**Comment by andreamarcolin** [comment]
Oh, now I see, pretty similar to how it's done for E2. Should have look more carefully. 
I will be back soon with the PR, thank you!
