### ISSUE TITLE
How to management fibers.

### ISSUE THREAD

**Issue by takat0-h0rikosh1** [zio/zio#1034]
I ran this code on my low spec PC.
https://zio.dev/docs/overview/overview_basic_concurrency#forking-effects

Then, the PC generated high fever and died as OOME.

I guess that is probably due to the fact that the number of concurrent fibers can not be managed and resources are exhausted.

Is there any documentation on how to manage concurrent fibers?
https://zio.dev/

**Comment by jdegoes** [comment]
The example should be changed.

`fib(100)` would generate `2^100` fibers, which would crash any machine.
