### ISSUE TITLE
Enable Circle CI Dotty compilation but not tests

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1048]
Tests don't work for Dotty but we should still be compiling Dotty on every build.

/cc @NeQuissimus @softinio

**Comment by softinio** [comment]
Agreed ...... I'll take a look

**Comment by jdegoes** [comment]
@softinio Thank you!

**Comment by NeQuissimus** [comment]
Just run the lint step with Dotty, that will compile the code. (unless the linter does not work xD)
