### ISSUE TITLE
Microsite zio.dev is down too often

### ISSUE THREAD

**Issue by evis** [zio/zio#1065]
For example, it was down for a few minutes right now. Should be problems with web server app, as far as I can guess.

```
$ ping zio.dev
PING zio.dev (167.99.129.42) 56(84) bytes of data.
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=1 ttl=51 time=46.2 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=2 ttl=51 time=46.2 ms
64 bytes from 167.99.129.42 (167.99.129.42): icmp_seq=3 ttl=51 time=47.2 ms
^C
--- zio.dev ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 46.184/46.529/47.212/0.513 ms
$ telnet zio.dev 80
Trying 167.99.129.42...
telnet: Unable to connect to remote host: Connection timed out
```

It's already working right now. But it's definitely not the first and even not the second time I encounter problems with accessing ZIO docs.

Bad microsite availability even became a subject for some jokes in Russian Scala User Group chat. :)

**Comment by ghostdogpr** [comment]
Seems like Netlify (the provider we're using) is being blocked by some russian providers. See https://community.netlify.com/t/netlify-cdn-or-dns-blocked-in-russia/372/3

**Comment by evis** [comment]
I doubt this problem exists due to blocking by providers. I'm able to ping zio.dev when website is down. Also, even if I use VPN, I can't access website anyway.

It's down right now again.

**Comment by ghostdogpr** [comment]
Personally I've never had issues and I access it very often. I'm surprised you have issues even with a VPN. What the link I provided is saying is that some CDNs in Europe are being blocked from Russia, so depending on which CDN you end up with load balancing, results might be different.

If I `dig zio.dev`, I can see I'm pointing to a DigitalOcean CDN located in Singapore (probably the closest to where I live).

Not sure we can do anything except stopping using Netlify altogether. Based on this [pretty recent message](https://community.netlify.com/t/netlify-cdn-or-dns-blocked-in-russia/372/3), they seem to be working on it.

**Comment by ghostdogpr** [comment]
These sites seems to confirm it as well:
https://isitblockedinrussia.com/?host=https%3A%2F%2Fzio.dev
https://www.comparitech.com/privacy-security-tools/blockedinrussia/

I tried a bunch of VPNs from other countries and didn't see any problem. Which VPN have you tried?

**Comment by evis** [comment]
Oops, seems like my VPN tried to connect via Russia too. Sorry for the confusion.

Changed country, actually works ok, thank you.

So, workaround for Russians is simple: just use VPN.

**Comment by ghostdogpr** [comment]
Good to hear, thanks!
