### ISSUE TITLE
Improve `Cause` to disallow Sequential failures being exposed as parallel

### ISSUE THREAD

**Issue by softinio** [zio/zio#1073]
See https://github.com/zio/zio/pull/917#issuecomment-504782408

**Comment by softinio** [comment]
@jdegoes Can I take a bit of your time to understand how Cause currently works in detail to bridge my knowledge and ramp up on the code base so I can tackle this effectively?

**Comment by softinio** [comment]
Going to tackle this

**Comment by jdegoes** [comment]
There should only be one `Fail` in any `Then` (sequence) of failures, and it should always be the first.

It means changing `++` to accept `Cause[Nothing]`, and possibly some other changes.

The intuition here is that if your fiber fails, then as it's unwinding the stack and running finalizers, it may generate more failures, but these will always be defects, not typed failures, and they will always come after the primary typed failure.

Now, the first fiber doesn't have to be a typed failure, it could be an untyped value.

So our possibilities are:

```
E + Throwable + Throwable + ...
```

or:

```
Throwable + Throwable + ...
```

But all other possibilities must be disallowed.

**Comment by vasilmkd** [comment]
Is there any progress on this?

**Comment by softinio** [comment]
@vasilmkd I have been slammed at work to work on this so was going to get back on it this coming week. 

Did you want to work on it today?

**Comment by vasilmkd** [comment]
No worries. Please continue. Just checking if it's still active.

**Comment by softinio** [comment]
👍  Yup still active ty
