### ISSUE TITLE
Implement Schedule.forDuration 

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1078]
Implement:

```scala
object ZSchedule {
  def forDuration(duration: Duration): ZSchedule[Clock, Any, Duration]
}
```

This schedule would repeat until the specified duration elapses (as measure from the time the schedule starts). After the duration elapses, the schedule will terminate.

**Comment by kaishh** [comment]
Don't we have a `ZSchedule.duration`?

**Comment by jdegoes** [comment]
@kaishh 🤦‍♂
