### ISSUE TITLE
Implement firstSuccessOf

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1079]
Using `orElse`, add the following method:

```scala
trait ZIO[R, E, A] {
   def firstSuccessOf(rest: Iterable[ZIO[R, E, A]]): ZIO[R, E, A]
}

object ZIO {
   def firstSuccessOf[R, E, A](first: ZIO[R, E, A], rest: Iterable[ZIO[R, E, A]]): ZIO[R, E, A]
}
```

These methods will use `orElse` to reduce the non-empty iterable of effects into a single effect.

It may make sense to add `firstSuccessOfPar` as a synonym for `raceAll`, and deprecate `raceAll` as the preferred name.

**Comment by peterlopen** [comment]
Should implementation in ZIO object look similar to this?
`rest.foldLeft[ZIO[R, E, A]](first)(_ orElse  _).refailWithTrace`

**Comment by Adriani277** [comment]
Would like to pick this up if no has yet :)
