### ISSUE TITLE
WIP: Improve definition of supervisor (DO NOT IMPLEMENT)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#108]
We now have `Fiber.onComplete`, which looks like this:

```scala
def onComplete(k: ExitResult[E, A] => IO[Nothing, Unit]): IO[Nothing, Unit]
```

This looks like a type of "supervisor", because anyone who calls this method can now see if and how the fiber exits (including all errors).

Currently, when a fiber is forked, an unhandled error handler may be specified, in the form `List[Throwable] => IO[Nothing, Unit]`. If this is not specified, then the uncaught error handler is used from the fiber that forks the fiber (all the way up to the root uncaught error handler).

These two methods of "supervising" a fiber look very similar, and suggest the two notions of "supervising" could be unified in some fashion.

Meanwhile, we have a separate `supervise` combinator:

```scala
IO.supervise {
  for {
    ...
  } ...
}
```

The `supervise` combinator allows collection of forked fibers into a weak set, so that cleanup may be performed upon exit of the specified `IO`. 

This notion is similar to the other in the sense that it's a way of supervising the activity of child fibers.

It's possible all three notions of "supervising" can be unified somehow.

**Comment by jdegoes** [comment]
@regiskuckaertz We can play around with ideas here.

The main problem with the obvious unification:

```scala
def onComplete(k: (Set[Fiber[_, _]], ExitResult[E, A]) => IO[Nothing, Unit]): IO[Nothing, Unit]
```

Is that it would require you collect the child fibers on every fiber. Currently this is a flag turned on / off with the `supervise` combinator, which means you pay the cost only when you need it.

One can view the building of the weak set as being a sort of state update, suggesting a way to generalize the `supervise` combinator. Perhaps if it were generalized, `onComplete` and error handling could be built on top of that.

**Comment by regiskuckaertz** [comment]
Do we want to introduce a `Supervisor` abstract data type to represent the varying degrees of supervision?

- one to deal with unhandled exceptions
- one to deal with the fiber's exit result
- one to deal with the fiber's exit result and children

A user could even "change their mind" for some reason and move from one degree to another.

Also the `IO.supervisor` combinator could be updated likewise. I'm not sure whether it makes sense to keep these in `IO` instead of `Fiber`?

**Comment by jdegoes** [comment]
I think using an sum type for supervisor could be one way to solve the issue. Another thing I thought of: perhaps your supervisor always gets passed `Set[Fiber[_, _]]`, but in some cases it's empty because children are not being observed? In this case, you get a more uniform type signature and more reuse across supervisors.

Finally another thing I thought about:

```scala
trait Supervisor[+A] {
  type State
  def initial: IO[Nothing, State]
  def onFork[E, A](state: State, child: Fiber[E, A]): IO[Nothing, State]
  def onComplete[E, A](result: ExitResult[E, A]): IO[Nothing, State]
  def finish(state: State): IO[Nothing, A]
}
object Supervisor {
  def forks: Supervisor[Set[Fiber[_, _]]] = ???
}
```

Now maybe you could write:

```scala
trait IO[E, A] {
  def superviseWith(s: Supervisor[A])(f: A => IO[Nothing, Unit]) = ???
}
```

And hence:

```scala
io.superviseWith(Supervisor.forks)(Fiber.interruptAll(_))
```

I know this is not well thought out, but more food for thought...

**Comment by regiskuckaertz** [comment]
It looks like the [supervision model in Erlang](http://erlang.org/doc/man/supervisor.html), at least if you squint your eyes 😅

It would be interesting to see how this idea can be reconciled with the declarative API of a ZIO. Perhaps `fork0` can be updated to accept an optional supervision strategy, in which case the fiber would automatically become a supervisor for its descendants.

**Comment by regiskuckaertz** [comment]
Another interesting discussion is how would an event-based API (`onFork`, `onComplete`) weave itself into the current evaluation model? It’s almost as if each action should run into its own fiber and then `State` becomes a piece of shared state, implying some `Ref` around it at least.
