### ISSUE TITLE
zip methods which ignore both effect results

### ISSUE THREAD

**Issue by evis** [zio/zio#1080]
So, we have `zipLeft`, which ignores right effect result, and `zipRight`, which ignores left effect result. We could have another function (`zipNone`? `zipIgnore`?), that ignores both effect results, so returns `ZIO[R1, E1, Unit]`.

Also, the same function could be implemented for `zipPar`.

I'd like to implement it, but want to agree about naming firstly. I suggest such naming:
`*` (as `zipRight` is `*>`, and `zipLeft` is `<*`)
`zipIgnore` as alias to `*`
`&` (same logic)
`zipParIgnore` as alias to `&`

**Comment by iravid** [comment]
Hmm so is this equivalent to `(a <*> b).unit`?

**Comment by evis** [comment]
Yes, it is.

**Comment by iravid** [comment]
Ok. My personal opinion is that it's pretty concise to write, so there'd be no particular advantage to a dedicated combinator.

**Comment by evis** [comment]
It's really concise to write, when we combine just `a` and `b`. But this one isn't so concise, for example:

```scala
(fireMissiles(accuracy) <*> launchSpaceRocket(height) <*> runThreads(count, pause)).unit
```

Compare with:

```scala
fireMissiles(accuracy) * launchSpaceRocket(height) * runThreads(count, pause)
```

Though, we may live without this and just write `unit`, of course.

**Comment by evis** [comment]
I've just realized, that we can write just this:

```scala
fireMissiles(accuracy) *> launchSpaceRocket(height) *> runThreads(count, pause).unit
```

This one is really simple.
