### ISSUE TITLE
Proper error handling with ZIO and http4s when a fiber dies

### ISSUE THREAD

**Issue by don41382** [zio/zio#1082]
I am using ZIO with http4s. Everything works like a charm. The only problem exists when inside ZIO Fiber an unexpected error (Exception) occurs and the Fiber dies. This results in an empty response for the user. This is unsatisfying because we should at least return a 503 :-)

Of course, I could fix this by changing every route to catch the error and prevent (sandbox) the Fiber from dying, but I would love to have this in a generic way and translate "dies" with a proper response for all my routes at once.

Is this possible with http4s?

**Comment by ratoshniuk** [comment]
@don41382 you mean something like `whenDie` ?

**Comment by don41382** [comment]
> @don41382 you mean something like `whenDie` ?
You are talking about `orDie` / `orDieWith`?

To be honest, I am not 100% sure what I am looking for. I just would like to prevent http4s from dying :-) It seems like, it has something to do with the Transactor in Doobie. Currently, I am building my own (step by step) to understand what exactly is happening.

```
  def route: HttpRoutes[AppTask] =
    Router("/" -> HttpRoutes.of[AppTask] {
      case GET -> Root =>
        ZIO.die(throw new Exception("boom"))
    })

  def server: ZIO[AppEnv, Throwable, Unit] =
    ZIO.runtime[AppEnv].flatMap { implicit rts =>
      BlazeServerBuilder[AppTask]
      .bindHttp(8080, "0.0.0.0")
      .withHttpApp(route.orNotFound)
        .withServiceErrorHandler(_ => {
          case ex: Throwable => InternalServerError(ex.getMessage)
        })
      .serve
      .compile[AppTask, AppTask, ExitCode]
      .drain
  }
```

This seems to work and the exception can be caught by `withServiceErrorHandler`.

**Comment by don41382** [comment]
Okay, I found the problem. If I use `ZIO.accessM` to access my environment effect and that crashes, no http4s returns no response to the user.

So, why does

```
def route: HttpRoutes[AppTask] =
    Router("/" -> HttpRoutes.of[AppTask] {
      case GET -> Root / name =>
        ZIO.die(throw new Exception("boom"))
    })
```
behaves differently as crashing environmental effect 
```
def route: HttpRoutes[AppTask] =
    Router("/" -> HttpRoutes.of[AppTask] {
      case GET -> Root / name =>
        ZIO.accessM(_.userPersistence.boom.flatMap(_ => Ok("never returns")))
    })
```
where something like this happens
```
  override val userPersistence: Service[Any] = new Service[Any] {
      ...
      override def boom: UIO[Nothing] =
        ZIO.die(throw new Exception("boom"))
```

Does somebody have an answer to this behavior and how I can streamline both of them?

**Comment by kaishh** [comment]
@don41382
Wrapping your routes with `IO.absorb` should streamline them. As to why there's a difference, this requires investigation... Could you create a runnable snippet with this? That would make it easier to investigate.

**Comment by don41382** [comment]
Thanks for digging this out with me @kaishh

I created a sample project and figured out: it's not the environment effect. Both routes work and the response is processed. So, it must be the `Transactor` of doobie.

**The sample project**
```
object EffectCrash extends scalaz.zio.App {

  type Env = Clock with MyEffect
  type ATask[A] = TaskR[Env, A]

  val dsl: Http4sDsl[ATask] = Http4sDsl[ATask]
  import dsl._

  def route: HttpRoutes[ATask] =
    Router("/" -> HttpRoutes.of[ATask] {
      case GET -> Root / "directEffect" =>
        // this will return a response (503)
        ZIO.effect(throw new Exception("boom"))
      case GET -> Root / "accessEffect" =>
        // this will not return a response (and yes, it does)
        ZIO.accessM(_.myEffect.boom.flatMap(_ => Ok("you'll never see this")))
    })

  def server: ZIO[Env, Throwable, Unit] =
    ZIO.runtime[Env].flatMap { implicit rts =>
      BlazeServerBuilder[ATask]
        .bindHttp(8080, "0.0.0.0")
        .withHttpApp(route.orNotFound)
        .withServiceErrorHandler(_ => {
          case ex: Throwable => InternalServerError(ex.getMessage)
        })
        .serve
        .compile[ATask, ATask, ExitCode]
        .drain
    }

  override def run(args: List[String]): ZIO[Environment, Nothing, Int] =
    server.provideSome[Environment](_ => new Clock.Live with MyEffect.Live {}).foldM(
      _ => ZIO.succeed(1),
      _ => ZIO.succeed(0)
    )
}
```

**Comment by kaishh** [comment]
@don41382 
It's because of `F.suspend` in `HttpRoutes.of`:
```scala
  def of[F[_]](pf: PartialFunction[Request[F], F[Response[F]]])(
      implicit F: Sync[F]): HttpRoutes[F] =
    Kleisli(req => OptionT(F.suspend(pf.lift(req).sequence)))
```
Your `throw` is catched by `suspend`, so it becomes and `IO.fail`, not `IO.die`

Note that behavior becomes consistent if you use `IO.die(new Exception("boom")` in the first route (**NOT** `IO.die(throw new Exception("boom"))` – this is different! It's equivalent to `throw new Exception("boom"); IO.die(???)` – `IO.die` is never called)

Catching/sandboxing/absorbing defects in the routes makes both routes equivalent:

```scala
HttpRoutes.of[ATask]{...}
  .mapF { case OptionT(task) => OptionT(task.absorb) })
```

```
% curl 0.0.0.0:8080/accessEffect  
boom
```

**Comment by don41382** [comment]
Thanks @kaishh. You are right, that was an editing error I made with the `IO.die(throw new Exception(..)` and yes, that would ignore `IO.die`.  I changed both to straight  `throw new Exception("boom")`.

```
  case GET -> Root / "directEffect" =>
        // this will return a response (503)
        throw new Exception("boom")
```
vs 
```
  override def boom: TaskR[Any, Unit] = throw new Exception("boom")
```

Both behave the same way. So, I am still not sure, why is the environment effect behaves differently. Shouldn't both exception result in the same outcome? Would be really nice to understand the difference, if a defect (exception) happens inside an environment effect and inside the https route.

**Comment by kaishh** [comment]
@don41382 
It's because of `F.suspend` in `HttpRoutes.of`:
```scala
  def of[F[_]](pf: PartialFunction[Request[F], F[Response[F]]])(
      implicit F: Sync[F]): HttpRoutes[F] =
    Kleisli(req => OptionT(F.suspend(pf.lift(req).sequence)))
```
Your `throw` is catched by `suspend`, so it becomes and `IO.fail`, not `IO.die`

`suspend` is equivalent to `IO.effect(_).flatten` - `IO.effect` directs exceptions in suspended effect to the error channel

**Comment by kaishh** [comment]
Your two throws happen at 2 different levels of suspension, if you wrap the route throw, or just move it into a .map - `IO.unit.map(_ => throw)` it will no longer be caught by `F.suspend` and will return 503 the same as environment effect

**Comment by don41382** [comment]
You are the man! That makes totally thanks! Thanks for clarifying.

I owe you a beer. Let me know when you are in Germany! :-)

So, the last question: Should the flatten not be a default? I mean, the response should not die, when a defect happens. Wdyt? Is this a ticket more for http4s?

**Comment by kaishh** [comment]
A good question, I proposed for cats-effect instances to always catch defects previously, we may reopen this discussion again in interop-cats. However, naked `throw` outside of `IO.effect` can be seen as a bug and outside of cats-effect laws so it's up to implementation. Right now both zio and http4s are working as intended here.

1. Don't use `throw` outside of imported side-effects
2. Use `.absorb` or `.sandbox` in places where you need 100% failure resistance. My snippet with OptionT absorb above works fine.

**Comment by don41382** [comment]
Your rules make sense. I still think the http4s response should only die if something fatal happens, e.g. (`StackOverflow` / `OutOfMemory`). As you have already been involved in the discussion cats-effect, you might bring it up there again.

I will close this issue because it's not ZIO related. 

And @kaishh, the pizza will be yours! @wi101 also asked to join. So, let me know when you are in Hamburg. It's going to be free pizzas.

**Comment by a14e** [comment]
@neko-kai  can you reopen discussion about `always catch defects`? (i cant find it in interop-cats :-( )

I have full Tagless Final application and I can't recover from unexpected errors within it =(

**Comment by neko-kai** [comment]
@a14e 
I have opened an issue for that https://github.com/zio/interop-cats/issues/277

However, another way to solve your issue would be to migrate form to bifunctor-aware Tagless Final. using bifunctor typeclasses aware of defects you'd be able to catch them. e.g. [BIO](https://izumi.7mind.io/bio/) typeclasses are compatible with cats-effect, so you can migrate pretty easily by adding `import izumi.functional.bio.catz._` to places where you need to convert BIO typeclasses to cats.
