### ISSUE TITLE
`when` sometimes fails to have type parameters inferred

### ISSUE THREAD

**Issue by bbarker** [zio/zio#1084]
In the following code snippet, `when` requires type paramters.

```scala
      _ <- ZIO.effect(%%(aclSeq)(root))
        .logTryMsg(ERR_CMD_RESULT, s"Couldn't set ACLs for $cxtDir")
        .when[CCRSEnv, Nothing](UC.isHostUserType(cmd.meta.containerType))
```

`.when[CCRSEnv, String]` will also work, but not e.g. `.when[CCRSEnv, Int]` (this is taking place in a for loop yielding a value of type `ZIO[CCRSEnv, String, JobId] `.

A relevant signature here is: `def logTryMsg(cVal : A, msg: String): ZIO[CCRSEnv, Nothing, A]`

**Comment by bbarker** [comment]
I'm not sure what happened, but it is working now without specifying type parameters. In fact, it actually fails with the `Nothing` type parameter above now:

```
[error] /home/brandon/workspace/CCRS/web-server/src/main/scala/org/xsede/jobrunner/server/TempJobContextService.scala:58:13: type arguments [org.xsede.jobrunner.model.CCRSEnv,Nothing] do not conform to method when's type parameter bounds [R1,E1 >: String]
[error]       ).when[CCRSEnv, Nothing](UC.isHostUserType(cmd.meta.containerType))
[error]             ^
[error] /home/brandon/workspace/CCRS/web-server/src/main/scala/org/xsede/jobrunner/server/TempJobContextService.scala:52:18: a type was inferred to be `Any`; this may indicate a programming error.
[error]         .mapError(ex => s"Error creating BASE job context dir: ${ex.getMessage}")
[error]                  ^
[error] two errors found
```

Previously I forgot to mention I was using zio "1.0-RC5", and still am. 

I didn't change any relevant dependencies that I can think of; the only things I just did was to add a new dependency with some excludes:

```scala
    , ("eu.timepit" %%% "refined" % "0.9.8")
      .exclude("org.scala-lang.modules", s"scala-xml_$scalaVersionSelectMajor")
```

and add an sbt plugin (`+addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")`).

**Comment by ghostdogpr** [comment]
@bbarker closing this one then, please reopen if you see this again
