### ISSUE TITLE
Suggestions for improvements to documentation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1097]
From a user:

### Having use cases where to use what

- [ ] How to handle interop with java
- [ ] How to handle defects (errors in pure code)
- [ ] How to transform from one variant to another (ie. Task -> UIO, using catchAll, either, fold)

### Best practices when it comes to error

- [ ] what can one do with the polymorphic error channel in ZIO,

### Misc

- [ ] Had issues running a simple service first time I tried ZIO because I had to had to *> IO.never to keep the app alive
- [ ] better understanding for Schedule and the operators around
- [ ] various operators and their purpose should be better documented, with code examples/use cases, small things like these make the difference
- [ ] People want to have something to reproduce in their own projects, a g8 template with a dummy module and akka-http(or/and any other mainstream framework)

**Comment by softinio** [comment]
A Tutorial that takes you step by step to building something useful with exercises and solutions at end to practice using ZIO?

**Comment by ywang412** [comment]
Maybe some simple tutorial comparing java.util.concurrent with zio in terms of how parallelism and queuing are handled would be super helpful. Something to convince Java developers to try zio.

**Comment by sinoz** [comment]
> Maybe some simple tutorial comparing java.util.concurrent with zio in terms of how parallelism and queuing are handled would be super helpful. Something to convince Java developers to try zio.

To add to this, I think it would be useful to have documentation that shows how to use fibers in a CSP-like fashion (think Goroutines & Channels, Akka actors, message passing in general)

**Comment by Tamriel** [comment]
* [ ] The website / documentation should have a search field
* [ ] The streams section could have an example on how to extract the header of a stream with `peel`, and maybe more examples from the talk [Scale By The Bay 2018 - Scalaz Stream: Rebirth](https://youtu.be/mLJYODobz44?t=867)

**Comment by adamgfraser** [comment]
@Tamriel Great suggestions! Thank you!

**Comment by softinio** [comment]
I am working on the search field - coming soon :-)

**Comment by softinio** [comment]
Search added to microsite via: https://github.com/zio/zio/pull/2624

**Comment by adamgfraser** [comment]
I think most of this has been addressed by the work of @khajavi. We can open specific issues for more targeted improvements we want to make.
