### ISSUE TITLE
Add ZStream#partition

### ISSUE THREAD

**Issue by DamianReeves** [zio/zio#1102]
Add the following method to `ZStream`:

``` scala
def partition[B, C, R1 <: R, E1 >: E](p: A => ZIO[R1, E1, Either[B,C]]): ZManaged[R1, E1, (ZStream[R1, E1,B], ZStream[R1, E1, C])]
```

**Comment by spf3000** [comment]
@DamianReeves wouldn't split accept a function of `p: A => Boolean` ? Similar to for example ZStream#filter:   `def filter(pred: A => Boolean): ZStream[R, E, A]`  - and then the signature you mentioned could be splitM similar to ZStream#filterM `  final def filterM[R1 <: R, E1 >: E](pred: A => ZIO[R1, E1, Boolean]): ZStream[R1, E1, A]`?

**Comment by didierd** [comment]
What about the more general 

`def split[B, C, R1 <: R, E1 >: E](p: A => ZIO[R1, E1, Either[B,C]]): ZManaged[R1, E1, (ZStream[R1, E1,B], ZStream[R1, E1, C])]` ?

**Comment by iravid** [comment]
@didierd I missed this comment - that's a good generalization! We should do that.

**Comment by vasilmkd** [comment]
Is anyone working on this actively?
