### ISSUE TITLE
Fix Flaky zio.stm.STMSpec test for Scala 2.11

### ISSUE THREAD

**Issue by softinio** [zio/zio#1105]
In circleci when running tests for Scala `2.11` the STMSpec test fails frequently with error: 

```
[error] Failed: Total 626, Failed 1, Errors 0, Passed 625
[error] Failed tests:
[error] 	zio.stm.STMSpec
[error] (coreJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 127 s, completed Jun 29, 2019 3:05:07 PM
Exited with code 1
```
Be good to investigate and make this test reliable. 

Sample Circle fail: 

https://circleci.com/gh/zio/zio/3876

**Comment by ghostdogpr** [comment]
@heraklos this is due to the fix in https://github.com/zio/zio/pull/1090 
I guess we should increase the number of concurrent fibers to make sure the condition always applies?

**Comment by heraklos** [comment]
@ghostdogpr 
Thanks for the suggestion. 
You're right and we should increase the number of concurrent fibers.
But in my local environment, even 2 concurrent fibers make the test pass, although 10 concurrent fibers make the test fail in Circle CI. 
So I can't be sure how many fibers are enough to make the test fail.

As I looked through the description of the test case, I notice it was intended to assert the test case with 100 concurrent fibers in the first place.
https://github.com/zio/zio/blob/5f35f8a646e3444100022c01763cdc4c3ca5677a/core/jvm/src/test/scala/zio/stm/STMSpec.scala#L35
So I'm going to increase the number of concurrent fibers from 10 to 100 for the time being and check the result.

**Comment by ghostdogpr** [comment]
Sounds good!

**Comment by softinio** [comment]
Note that when ever I have seen this test fail it has always been using scala 2.11 !
