### ISSUE TITLE
SystemSpec test case fails on Windows platform

### ISSUE THREAD

**Issue by ywang412** [zio/zio#1108]
When running test cases, I found one test case in SystemSpec is not friendly to Windows native developer. 
  def env1 = {
    val io = unsafeRun(system.env("PATH"))
    io must beSome
    io.get must contain("/bin")
  }

The "/bin" will fail windows platform and "\bin" will work. This test case is platform dependent. If this is recognized as an issue, I'd like to fix it. 

Thanks!

**Comment by ghostdogpr** [comment]
Yep it’s legitimate, you can submit a fix 👍

**Comment by ywang412** [comment]
#1109
