### ISSUE TITLE
Move Exit.Cause to top-level

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1113]
`Cause` appears as a nested class inside the `Exit` companion object, but its importance and visibility has grown, and it makes sense to divorce it from the `Exit` type, by moving it to the top-level `zio` package.

We could introduce temporary `type Cause[+E] = zio.Cause[E]` and `val Cause = zio.Cause` synonyms inside `Exit` to maintain backward compatibility, but mark them `@deprecated`.

**Comment by hamednourhani** [comment]
Hi @jdegoes can I start from here

**Comment by dorsev** [comment]
hey @hamednourhani, sorry about this. 
This is my first PR in zio and did not think to write here that I started it.

**Comment by iravid** [comment]
Closed by #1117
