### ISSUE TITLE
Enhance ZStream#spaced to emit the schedule's output into the stream as well

### ISSUE THREAD

**Issue by iravid** [zio/zio#1120]
Currently, `spaced` doesn't emit the schedule's output into the stream; it is ignored. To align the combinator more closely with `ZIO#repeat`, we should emit the schedule's output into the stream when the schedule finishes. 

The signatures for the new combinators should be:

```scala
def spacedEither[R1 <: R, B](schedule: ZSchedule[R1, A, B]): ZStream[R1 with Clock, E, Either[B, A]]
def spaced[R1 <: R, A1 >: A](schedule: ZSchedule[R1, A, A1]): ZStream[R1 with Clock, E, A1] = 
  spacedEither(schedule).map(_.merge)
```

**Comment by dag2ww** [comment]
Hi,
if no one has started this one yet, I would like to take it as my first contribution.

**Comment by iravid** [comment]
Hi @dag2ww, go ahead! I updated the description as the previous spec was not aligned with how `ZSchedule` works.

**Comment by dag2ww** [comment]
OK, great! 
Thank you.

**Comment by dag2ww** [comment]
Hi @iravid ,
Having the change implemented, I'm about to update test for `spaced` and would like to confirm the expected output/behaviour. 
What would you expect for `Stream(1, 2, 3).spaced(Schedule.recurs(1))` with Schedule's output emitted each time it finishes? 
Without Schedule's output emitted it was: 1, 1, 2, 2, 3, 3. 

Looking forward your comment on this. Thanks!

**Comment by iravid** [comment]
@dag2ww Yes, every time it finishes.
