### ISSUE TITLE
Add SoftwareMill as sponsor to website and README.md 

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1125]
Displayed attractively and prominently on both the README.md inside this repository, and on the ZIO website, we should add [SoftwareMill](https://softwaremill.com) as a ZIO sponsor, with both the tagline and a link to their home page.

 - [SoftwareMill Logo](https://softwaremill.com/images/header-main-logo.3449d6a3.svg)
 - Tagline: "Custom software by true engineers"
 - Link: <https://softwaremill.com>

**Comment by kaishh** [comment]
What was their donation amount? 🤔

**Comment by jdegoes** [comment]
@kaishh CircleCI build coverage for 1 year starting from July. Probably going to be $2.4k assuming $200 / month.

**Comment by NeQuissimus** [comment]
Thank you @softwaremill

**Comment by kaishh** [comment]
@jdegoes 
Can we get into the sponsors list too?
