### ISSUE TITLE
Release interop projects simultaneously

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#1146]
Trying to release multiple interop modules at the same time causes all of them to fail due to multiple staging repositories...

https://circleci.com/gh/zio/interop-future/84
```
[error] Multiple repositories are found:
[error] [devzio-1113] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1114] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1115] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1116] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1117] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1118] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1119] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] [devzio-1120] status:open, profile:dev.zio(ad33947a4dfa37) description: Implicitly created (auto staging).
[error] Specify one of the repository ids in the command line
```

I guess we should open a staging repository explicitly and use its ID in `sonatypeRelease`. Can anyone with sbt-foo help out? @softinio @NeQuissimus g-guys?

Also if someone could `sonatypeDrop` again, I could proceed with releasing them one-by-one 🙏

**Comment by NeQuissimus** [comment]
I dropped them all, may take a minute or two.
This problem has been bugging us for a while. I did not know you could pass an ID to `sonatypeRelease`.

**Comment by kaishh** [comment]
Thanks!

**Comment by kaishh** [comment]
Getting  a strange failure in `interop-twitter` release:
```
Failed: signature-staging, failureMessage:No public key: Key with id: (30c86b8e6313b52d) was not able to be located on <a href="http://keys.gnupg.net:11371/">http://keys.gnupg.net:11371/</a>. Upload your public key and try the operation again.
```
https://circleci.com/gh/zio/interop-twitter/95

**Comment by NeQuissimus** [comment]
The GPG key infrastructure is currently under attack. Should be intermittent.

**Comment by kaishh** [comment]
Another conflict. Could you please give me creds so that I could drop manually?

**Comment by ghostdogpr** [comment]
Actually you can do it, the credentials are on the team discussions in this org. You can login to nexus with it.

**Comment by kaishh** [comment]
👍 Done
