### ISSUE TITLE
Enhance support for Option and Either

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1160]
# Getter Helpers

Sometimes we have values like `UIO[Option[A]]`, and we wish the option to be non-empty; if the option is empty, we wish to fail the effect. Similarly for structures like `Task[Either[A, B]]`.

## Option Getter Helpers

Add these methods to `ZIO` trait:

```scala
trait ZIO[-R, +E, +A] {
  def someOrFailWith[B, E1 >: E](f: Throwable => E1)(implicit ev: A <:< Option[B]): ZIO[R, E1, B] = ???
  
  def someOrFail[B, E1 >: NoSuchElementException](implicit ev: A <:< Option[B], ev2: E <:< E1): ZIO[R, E1, B] = ???
}
```
### Usage 

Add a variety of tests for `someOrFail` and `someOrFailWith`.

```scala
val task: Task[Int] = UIO(Some(42)).someOrFail
```

## Either Getter Helpers
Add these methods to `ZIO` trait:

```scala
trait ZIO[-R, +E, +A] {
  def leftOrFailWith[B, C, E1 >: E](f: Throwable => E1)(implicit ev: A <:< Either[B, C]): ZIO[R, E1, B] = ???
  
  def leftOrFail[B, E1 >: NoSuchElementException](implicit ev: A <:< Either[B, C], ev2: E <:< E1): ZIO[R, E1, B] = ???

  def rightOrFailWith[B, C, E1 >: E](f: Throwable => E1)(implicit ev: A <:< Either[B, C]): ZIO[R, E1, C] = ???
  
  def rightOrFail[B, E1 >: NoSuchElementException](implicit ev: A <:< Either[B, C], ev2: E <:< E1): ZIO[R, E1, C] = ???
}
```
### Usage 

Add a variety of tests for `leftOrFail`, `leftOrFailWith`, `rightOrFail`, and `rightOrFailWith`.

```scala
val task: Task[Int] = UIO(Right(42)).rightOrFail
```

# Constructor Helpers

It would be nice to construct things like `UIO[Option[Int]]` directly rather than using repeated function application. To do this, some helpers can be added into `ZIO` companion object, and other companion objects:

```scala
def some[A](a: A): UIO[Option[A]] = ???
val none: UIO[Option[Nothing]] = ???

def left[A](a: A): UIO[Either[A, Nothing]] = ???
def right[B](b: B): UIO[Either[Nothing, B]] = ???
```

With corresponding tests in `RTSSpec.scala`.

**Comment by dorsev** [comment]
I Would love to take this.

**Comment by jdegoes** [comment]
@dorsev Please do!

**Comment by kaishh** [comment]
These are called `fromOption` and `fromEither` in BIO - https://github.com/7mind/izumi/blob/develop/fundamentals/fundamentals-bio/src/main/scala/com/github/pshirshov/izumi/functional/bio/BIOSyntax.scala#L114
Specifying error on None, like in `timeoutFail`, has been extremely useful to me, I think it would be nice to have besides a hardcoded `NoSuchElementException`

**Comment by jdegoes** [comment]
@kaishh @dorsev 

How about this revision:

```scala
trait ZIO[-R, +E, +A] {
  def someOrFail[B, E1 >: E](f: E1)(implicit ev: A <:< Option[B]): ZIO[R, E1, B] = ???
  
  def someOrFailException[B, E1 >: NoSuchElementException](implicit ev: A <:< Option[B], ev2: E <:< E1): ZIO[R, E1, B] = ???

  def leftOrFail[B, C, E1 >: E](f: E1)(implicit ev: A <:< Either[B, C]): ZIO[R, E1, B] = ???
  
  def leftOrFailException[B, E1 >: NoSuchElementException](implicit ev: A <:< Either[B, C], ev2: E <:< E1): ZIO[R, E1, B] = ???

  def rightOrFail[B, C, E1 >: E](f: E1)(implicit ev: A <:< Either[B, C]): ZIO[R, E1, C] = ???
  
  def rightOrFailException[B, E1 >: NoSuchElementException](implicit ev: A <:< Either[B, C], ev2: E <:< E1): ZIO[R, E1, C] = ???
}
```

This way you can do a custom error, or the "default" error (`NoSuchElementException`).
