### ISSUE TITLE
Describe type parameters in zio.stream.ZStream#Fold

### ISSUE THREAD

**Issue by dag2ww** [zio/zio#1173]
As of now, for new comers, it requires extra work to figure out the meaning of zio.stream.ZStream#Fold type parameters used.

Would be good to add few sentences with semantics of each type param in here:
`type Fold[R, E, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, E, S]) => ZManaged[R, E, S]]`

**Comment by iravid** [comment]
Good idea. `Fold` is not intended to be the main way to consume the results of a stream (`run` and `foreach` are), but scaladoc would be greatly appreciated.

**Comment by ghostdogpr** [comment]
Closed by #1272
