### ISSUE TITLE
Implement `TMap`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1178]
Implement `zio.stm.TMap`:

```scala
class TMap[K, V] private (hashmap: TRef[TArray[List[(K, V)]]) { ... }
```

with methods similar to `Map` inside it, allowing access and updating by key, as well as folding and other types of functionality compatible with STM.

**Comment by mijicd** [comment]
I'll take this one.

**Comment by jdegoes** [comment]
@mijicd Awesome!

If up for a challenge, see [Michael Schröder's thesis](http://hackage.haskell.org/package/ttrie).

**Comment by iravid** [comment]
About time we get finalisers and ZManaged for STM! ;-)

**Comment by mijicd** [comment]
@jdegoes nice, I'll check it out!
