### ISSUE TITLE
Restart publishing for dotty

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#1180]
We've stopped publishing for dotty after switching orgs. I think we can resume doing that, though!

**Comment by softinio** [comment]
interops will probably need to be done first

**Comment by softinio** [comment]
Also we still have macros in the code base especially the specs2 tests like `s2` which will not work with dotty

**Comment by kaishh** [comment]
@softinio Core doesn't depend on interops though and we don't have (and can't) build mdocs for dotty. We can also keep blissfully ignoring tests for dotty for now and just release after successful compile.

**Comment by softinio** [comment]
related to this conversation : #1208

**Comment by gzoller** [comment]
Bump!  Scala 3 is right around the corner... time to clean up any Scala 2 dependencies and publish Dotty builds, please.

**Comment by ghostdogpr** [comment]
We are already publishing for dotty: https://repo1.maven.org/maven2/dev/zio/zio_0.23/ (it's not the latest dotty version, there is a blocker for upgrading but it might be solved soon, see https://github.com/zio/izumi-reflect/issues/38)
