### ISSUE TITLE
Optimize parallel methods

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1182]
The parallel methods of ZIO require optimization:

 - [ ] `foreachPar` & variants
 - [ ] `collectAllPar` & variants
 - [x] `raceAll` & variants
 - [ ] `forkAll` & variants
 - [ ] `reduceAllPar` & variants
 - [ ] `mergeAllPar` & variants

Right now, these methods are implemented via _binary composition_. 

This creates deeply nested and lop-sided trees:

```
   /\
  /  \
 *    \
      /\
    /   \
   *    /\
       /  \
      *    \
           /\
          /  \
         *    *
```

All the intermediate propagation of results takes a long time and generates heap.

The ideal way to optimize many of these parallel methods is to use an `Array` (a flat data structure) and coordinate results through a `Ref` and maybe a `Promise`.

If someone wants to take on this ticket but needs more details, let me know and we can pair on one of them (maybe `forkAll`) to see an example of how to apply performance optimization in this fashion.

**Comment by galosa** [comment]
I would love to take it

**Comment by galosa** [comment]
I will start from forkAll :)

**Comment by hepin1989** [comment]
if the size is 2, then use binary operation, otherwise, use array.

**Comment by galosa** [comment]
Hey @jdegoes,
This is my first OSS contribution, I tried this and I'm struggling with the implementation for `forkAll`.
I would love to pair up and do this together.

**Comment by jdegoes** [comment]
@galosa Let's do it! What time zone are you in?

**Comment by galosa** [comment]
@jdegoes Thank you, my timezone is GMT+3.

**Comment by vasilmkd** [comment]
Any progress on this? Not necessarily looking to directly contribute, just interested.

**Comment by galosa** [comment]
Not yet, we didn't manage to sit on this yet. Since it taking so long feel free to take it.

**Comment by simpadjo** [comment]
@jdegoes Let me try to do it.
I have a question though. 
The size of the result is not known beforehand so we can't just preallocate an array of the right size. We need a growable structure that supports `add(idx: Int, value: B)` operation. `java.util.ArrayList` is a perfect candidate but it's not js-friendly.
I really wouldn't like to reimplement it.

I'm going to collect results together with task indices and into scala.mutable.ArrayBuffer[(Int, B)]` then convert it into `Array[B]` (linear complexity) and then to list.

What do you think? Maybe there are existing data structures to reuse?

**Comment by simpadjo** [comment]
I've made a draft implementation: https://github.com/simpadjo/zio/blob/foreachpar/core/shared/src/main/scala/zio/internal/ParOps.scala 

Unfortunately it doesn't work properly if one task doesn't terminate (e.g. `IO.never`) and another task fails or crashes. It must kill non-terminating tasks but it doesn't. I tried different variations of `onTermination`, `onError` and `interrupt` but failed to make it work.

**Comment by hanny24** [comment]
Hi, can I do this as a part of Warsaw Hackathon ?

**Comment by regiskuckaertz** [comment]
@hanny24 by all means 🙏

**Comment by YuvalItzchakov** [comment]
I'm going to start work on this if there are no objections

**Comment by evis** [comment]
@jdegoes I think, we are ready to close this issue. There are no more methods which create large inefficient trees with zipPar.

**Comment by evis** [comment]
> I think, we are ready to close this issue. There are no more methods which create large inefficient trees with zipPar.

@iravid @adamgfraser

**Comment by jdegoes** [comment]
@evis Thank you!!!
