### ISSUE TITLE
better repl inspection

### ISSUE THREAD

**Issue by contrun** [zio/zio#1193]
I was trying to play zio with ammonite.
```
import $ivy.`dev.zio::zio:1.0.0-RC10-1`, zio._
ZIO.succeed(1)
Fiber.succeed(1)
```

I understand that all I did was creating new effects. But this is in an `repl`, so I expected to see information more relevant than `res3: UIO[Int] = zio.ZIO$Succeed@6afced93` and `res6: Fiber[Nothing, Int] = zio.Fiber$$anon$5@6414eb98`. It should be just like `ghci`.

Is it possible that we differentiate the behavior of those ZIO in an `repl` from those in normal code, so that the output of `repl` can be more useful?

**Comment by kitlangton** [comment]
While this doesn't fully match `ghci`'s behavior, `.unsafeRun` is added implicitly to all effects within a ZIO repo session:
```scala
  // Keep this consistent with the version in .core-tests/shared/src/test/scala/REPLSpec.scala
  val replSettings = makeReplSettings {
    """|import zio._
       |import zio.console._
       |import zio.duration._
       |import zio.Runtime.default._
       |implicit class RunSyntax[A](io: ZIO[ZEnv, Any, A]){ def unsafeRun: A = Runtime.default.unsafeRun(io.provideLayer(ZEnv.live)) }
    """.stripMargin
  }
```
