### ISSUE TITLE
ZStream#effectAsync should provide a way for the caller to signal stream end

### ISSUE THREAD

**Issue by iravid** [zio/zio#1200]
We can perhaps add an overload that uses `Option[A]` as the value for the ZIO, but that would unfortunately incur an allocation on each element.

@jdegoes any ideas? Maybe `Option[E]` on the error channel?

**Comment by jdegoes** [comment]
Yes, `Option[E]` would pay the price only on failure.

**Comment by iravid** [comment]
We can probably get rid of `Take` in the same way!

**Comment by jdegoes** [comment]
@iravid That would be awesome, since it's used so pervasively now.

**Comment by vasilmkd** [comment]
What is the scope of this issue? Implement `Option[E]` as a signal for stream end and evaluate the solution as a replacement for `Take`, but defer the actual replacement of the code for later?

**Comment by iravid** [comment]
Yeah. For this ticket, let's focus on `effectAsync`.

I prototyped replacing `Take` with signalling through the error channel entirely, and it wasn't trivial due to the separation of consumer/producer errors in Stream. We might need to wait for the error overhaul on ZStream for this.

**Comment by vasilmkd** [comment]
I'll be working on this.
