### ISSUE TITLE
Add ZStream#flatMapParSwitch

### ISSUE THREAD

**Issue by iravid** [zio/zio#1203]
Comparing to Rx*, we've got `concatMap` (which is `ZStream#flatMap`) and `mergeMap` (which is `ZStream#flatMapPar`). We're only missing `switchMap`, with semantics as described here: https://www.learnrxjs.io/operators/transformation/switchmap.html.

We could generalize `switchMap` to a combinator called `flatMapParSwitch`:
```scala
trait ZStream[R, E, A] {
  def flatMapParSwitch[R1 <: R, E1 >: E, B](maxOpen: Int)(f: A => ZStream[R1, E1, B]): ZStream[R1, E1, B]
}
```

This operator maps every `A` to a new stream, and merges the output of up to `n` streams in parallel. So far, identical to `flatMapPar`. The difference is that whenever a new `A` is emitted, the oldest* stream of `B` to be opened is cancelled.

\* the strategy of choosing which stream to cancel can also be generalized, but that can be left for a follow-up

**Comment by vasilmkd** [comment]
I'd like to take this. I'm interested to learn more about Rx.

**Comment by iravid** [comment]
@vasilmkd go for it! :-) Please have a look at the implementation for `flatMapPar` before you start. It should be fairly similar in structure. It's pretty well commented so you can follow the nuances.

**Comment by vasilmkd** [comment]
Initial implementation is ready for review. Will we also be implementing a synchronous switchMap (only one active stream at a time)?

I'm also interested to hear ideas about the generalized way to select the stream to be closed.

I'm very grateful for the comments and clear implementation of flatMapPar, and the comprehensive test suite. I really learned a lot and had a lot of fun implementing this code.
