### ISSUE TITLE
Add ZStream#zipWithLatest

### ISSUE THREAD

**Issue by iravid** [zio/zio#1204]
Like `ZStream#zipWith`, but holds onto the last item emitted on each side so there's always an element to combine with.

**Comment by contrun** [comment]
I'd like to contribute. Do you mean a function like combineLatest in RxJava https://github.com/ReactiveX/RxJava/blob/3.x/docs/Combining-Observables.md#combineLatest  ?

**Comment by iravid** [comment]
Yup!
