### ISSUE TITLE
Add Executor#toJava: java.util.concurrent.Executor

### ISSUE THREAD

**Issue by tabdulradi** [zio/zio#1212]
I've been using the following simple converter recently:
```scala
private def asJava(executor: Executor): java.util.concurrent.Executor = 
  command =>    
    if (executor.submit(command)) ()
    else throw new java.util.concurrent.RejectedExecutionException
```

Does this interest more people? shall I PR it as a method on `Executor`?

**Comment by jdegoes** [comment]
@tabdulradi Great idea! We should investigate Scala.js compatibility to know where to put it...
