### ISSUE TITLE
Add prameterless ZIO#toManaged to lift an effect into ZManaged

### ISSUE THREAD

**Issue by tabdulradi** [zio/zio#1213]
Currently, there is `ZIO.toManaged` that takes `release` parameter. How about adding a parameterless overload that just calls `ZManaged.fromEffect`?

**Comment by iravid** [comment]
That's `ZIO#toManaged_` :-)

**Comment by tabdulradi** [comment]
Oh it's still on master, amazing! Thanks a lot.
