### ISSUE TITLE
Enhance combinators for working with sum types (Option, Either, etc.)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1217]
A few operators can allow digging into terms of sum types, pushing error states onto the error channel; and a couple more can allow "popping" error states off the error channel.

```scala
trait ZIO[R, E, A] {
  def left[B, C](implicit ev: A <:< Either[B, C]): ZIO[R, Option[E], B] = ???
  def right[B, C](implicit ev: A <:< Either[B, C]): ZIO[R, Option[E], C] = ???
  def some[B](implicit ev: A <:< Option[B]): ZIO[R, Option[E], B] = ???
  def none[B](implicit ev: A <:< Option[B]): ZIO[R, Option[E], Unit] = ???
  def head[B](implicit ev: A <:< List[B]): ZIO[R, Option[E], B] = ???
  
  def fuseError[E1, E2 <: E1](default: E2)(implicit ev: E <: Option[E1]): ZIO[R, E1, B] = ???

  def peelError[E1, A1 >: A](default: A1)(implicit ev: E <: Option[E1]): ZIO[R, E1, A1] = ???
}
```

/cc @jczuchnowski who was thinking about these issues.

**Comment by adamgfraser** [comment]
I'm happy to take this if no one else is.

**Comment by jdegoes** [comment]
@adamgfraser 🙏

**Comment by adamgfraser** [comment]
I’m on it.

**Comment by jczuchnowski** [comment]
So just not to double the work, I'll post a PR with what I was working on.

**Comment by jczuchnowski** [comment]
So here it is.
@adamgfraser I suggest I finish the work on Option (I have `some` and `peelError`) and you could take Either. What do you think?
@jdegoes we talked about different names before. I believe I have a kind of `peelError` but with a different signature, right?

**Comment by adamgfraser** [comment]
@jczuchnowski That sounds great. I'll take `left`, `right`, and `head` and leave `some`, `none`, `fuseError`, and `peelError` to you. I just did implementations of `none` and `fuseError` so I will add them as a comment to your PR in case it is helpful to you.

**Comment by jczuchnowski** [comment]
@adamgfraser yes, it'll be helpful, thanks!

**Comment by jdegoes** [comment]
@jczuchnowski Yes, I am not really sure on good names here.

**Comment by ghostdogpr** [comment]
Closing this, both PRs are merged.
