### ISSUE TITLE
Add convenience methods to Schedule

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1219]
We should add two methods to `ZSchedule`, which will recur while / until the input to the schedule equals the specified reference value.

```scala
def doWhileEquals[A](a: A): Schedule[A, A]
def doUntilEquals[A](a: A): Schedule[A, A]
```

This will simplify a lot of code that currently does things like `Schedule.doWhile(_ == true)`.

**Comment by CloudZou** [comment]
@jdegoes can is pick up it?

**Comment by CloudZou** [comment]
`final def doWhileEquals[A](a1: A): Schedule[A, A] =
    identity[A].check((a, _) => IO.succeed(a == a1))`

@jdegoes  is it like this?

**Comment by HurmuzacheCiprian** [comment]
sorry, is this still outstanding? also I can see that there are no tests for the ZSchedule class?

**Comment by ghostdogpr** [comment]
@HurmuzacheCiprian yep. Tests are in RetrySpec and RepeatSpec but we’d like to move them to a ZScheduleSpec as per https://github.com/zio/zio/issues/1345

**Comment by HurmuzacheCiprian** [comment]
oh ok, cheers. @CloudZou are you still working on this? sorry to jump in like this but maybe I can help if it's ok?

**Comment by jozi-k** [comment]
I believe this issue can be closed now.
