### ISSUE TITLE
Specialize forkAll, parAll, raceAll

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#122]
Currently, recursively using `forkAll`, `parAll`, or `raceAll` on large lists will lead to a lot of unnecessary overhead.

Each of these will generate a tree like this:

```
       /\
      /  \
     A   /\
        /  \
       B   /\
          /  \
         C    D
```

So, in the case of `D`, it's actual work will be deferred through 3 separate bounces to the thread pool.

There are three possible ways to deal with this problem:

1. Improve the logic of forking to peek down and pass intermediates to do less work.
2. Specialize `forkAll`, `parAll`, and `raceAll` by introducing 3 new primitive operations that are specialized to work on lists or list-like structures. These can use lots of tricks because they are more specialized than the fully general purpose combinators.
3. Implement `forkAll`, `parAll`, and `raceAll` directly in terms of the `fork` / `join` (low-level) framework.

This ticket describes (3), because it is easiest and does not involve any changes to the runtime system.

**Comment by vitaliihonta** [comment]
@jdegoes can I take it?)
