### ISSUE TITLE
Pull out all core tests into separate `core-tests` project

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1225]
We will use _ZIO Test_ for all tests. In order to avoid circular dependencies, we should pull out all `core` tests into a new project: `core-tests`. This will depend both on `testkit` and on `core` and will contain all tests currently in `core`.

Some basic level of familiarity with `sbt` is required for this ticket.

**Comment by mgibowski** [comment]
I volunteer to take this.

**Comment by jdegoes** [comment]
@mgibowski Thank you! 🙏

**Comment by ghostdogpr** [comment]
Closed by #1248

**Comment by jdegoes** [comment]
@ghostdogpr Thank you for all the cleanup! I should remind people to use `Fixes #xyz` syntax in pull requests...
