### ISSUE TITLE
Rename `testkit` to `test`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1226]
`testkit` should be renamed to `test`, since it's evolving to become _ZIO Test_, and `testkit` will just be a test environment that is part of _ZIO Test_.

This involves updating the directory and miscellaneous stuff in the `sbt` build file.

**Comment by vasilmkd** [comment]
I'd like to take this.

**Comment by jdegoes** [comment]
@vasilmkd Thank you!

**Comment by vasilmkd** [comment]
No problem. Glad I could help on short notice.

**Comment by vasilmkd** [comment]
I guess this issue can be closed? @jdegoes
