### ISSUE TITLE
ZIO.collectSuccesses

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1233]
I'd love to have a method `ZIO.collectSuccesses[R, E, A](in: Iterable[ZIO[R, E, A]]): ZIO[R, Nothing, List[A]]` (and an equivalent `collectSuccessesPar`), which - unlike `ZIO.collectAll` - Cannot fail but rather just returns all the results that have succeeded.

I find myself writing something like `ZIO.collectAll(zios.map(_ <&> x))` and filtering `x` back out.

**Comment by mtsokol** [comment]
I would like to try to do it.

**Comment by jdegoes** [comment]
We can make this more orthogonal by adding a method to `Exit`:

```scala
Exit.successes(it: Iterable[Exit[E, A]]): List[A]
```

Then `ZIO.foreach(list)(_.run).map(Exit.successes)` gives us what you want.

Similarly for `Exit.failures`, etc.

Another factoring would be: `ZIO.collectWith(list.map(_.run)) { case Success(a) => a }`.

Actually I quite like `collectWith`.

Once the foundation is done a combinator could be written on top, but for compositionality, it's important to have a nice foundation.

**Comment by NeQuissimus** [comment]
`collectWith` would be great, I like that. It would allow to do something similar using `list.map(_.either)` if one prefers that.

**Comment by ghostdogpr** [comment]
Closed by #1237
