### ISSUE TITLE
Add "setter" / "update" methods to mock services

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1240]
The following mock services (located in the `test` project, in the `shared` source directory) are powered by a `Ref` that contains test data:

 - [ ] TestClock
 - [ ] TestConsole
 - [ ] TestSystem
 - [ ] TestRandom

These mock services provide test implementations of the corresponding ZIO interfaces (Clock, Console, System, Random).

We need to add setter / update functions to these, so users can update the test data _without interacting with the `Ref`_. 

 - Clock: setTime, setTimeZone, etc.
 - Console: feedLine
 - System: putEnv, etc. 
 - Random: feedInt, etc.

Once this ticket is complete, a user could interact with `TestConsole`, and programmatically push text into the buffer, for example; and do the same with other mocks.

This will allow us to hide the `Ref` implementation and make it easier to setup test scenarios.

**Comment by vasilmkd** [comment]
I'll take TestClock, since I have already used it in previous tests.

**Comment by adamgfraser** [comment]
I can do the other ones.

**Comment by jdegoes** [comment]
🙏

**Comment by ghostdogpr** [comment]
Closed by #1252
