### ISSUE TITLE
Rename TestClock, TestScheduler, TestSystem, TestConsole, TestRandom, TestEnvironment

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1257]
Now that we have moved the mock services into `zio.test.mock`, it makes sense to rename the `Test` prefix to `Mock`, e.g. `MockConsole`, `MockEnvironment`, etc.

**Comment by dkarlinsky** [comment]
I'll take this

**Comment by jdegoes** [comment]
@dkarlinsky Thanks!

**Comment by ghostdogpr** [comment]
Closed by #1260
