### ISSUE TITLE
Add ZManaged#memoize

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1263]
Constructs an inner `ZManaged` that will lazily acquire the resource, but only a single time; releasing in the outer scope only.

```scala
trait ZManaged[R, E, A] {
  def memoize: ZManaged[R, E, ZManaged[R, E, A]] = ???
}
```

/cc @iravid

**Comment by jdegoes** [comment]
This could also be called `duplicate`.

**Comment by jdegoes** [comment]
It could also be called `shared`.

**Comment by mtsokol** [comment]
I would like to try to do it.

**Comment by jdegoes** [comment]
@mtsokol Awesome, thank you! 🙏

**Comment by fsvehla** [comment]
Is this actually taken for the hackathon?

**Comment by mtsokol** [comment]
@fsvehla I've started it here https://github.com/zio/zio/pull/1276 and came up with idea in PR last comment according to given tip and it still waits for feedback. I'm not sure about it so feel free to look at it and give you opinion on that snippet.

**Comment by fsvehla** [comment]
@mtsokol are you still around? When will you leave tomorrow?

**Comment by mtsokol** [comment]
Yeah I'm I our conference room available until 22:00. Tomorrow I'm leaving 15:00, also available whole day 🙂

**Comment by fsvehla** [comment]
Aah too bad we miss ourselves then, we have left for a pub and I will need to leave at 09:00 tomorrow.
