### ISSUE TITLE
Blocking as default `effect` import?

### ISSUE THREAD

**Issue by fanf** [zio/zio#1275]
Following these discussion in twitter (https://twitter.com/fanf42/status/1155734715346935808 and https://twitter.com/fanf42/status/1155781700246523905°, and on the advice of @kaichaosun I'm opening that issue to discuss about what should/could be done to make importing bloking IO more well known and/or the default effect strategy. 

The problem with `Blocking` by default is that it would lead to really inefficient runtime as discussed in previous issues in the subject like https://github.com/zio/zio/issues/248. 
The problem with `non Blocking` by default, and especially for people news to  `ZIO` or without prior big knowledge of (jvm) execution context, is that they will not know that there is an issue here (why to do it?), how exactly to do it? (use `effectBlocking` is not default, how to use it for composition), what are the consequences (should I use it always? As little as possible), and that they most likely won't know when (what is actually a `blocking` ?). If someone don't use `Blocking` when he should, it can lead to real big problem, up to deadlock (https://github.com/zio/zio/issues/241).

So, for all these reasons, the story around `Blocking` should be rethought, either by having a default `Blocking` effect (sufficiently efficient to be usable as a default), or by making the use of `effectBlocking` sufficiently obvious for everyone, especially new comers without prior-knowledge of thread pools and execution context, easy.

**Comment by jdegoes** [comment]
I think we can solve this problem once and for all, will just require a little time post 1.0.

**Comment by AshishPrasad** [comment]
@jdegoes, @fanf do we have a future where an end user doesn't have to care about which variant (blocking/non-blocking) of ZIO API to invoke?

**Comment by fanf** [comment]
Update: in Rudder, we tried to make the default import of an effect runs on `Blocking` (ie: our `IOResult.effect` adds a `Blocking`).
The performances are catastrophic, up to x10 longer compared to the previous version without ZIO. 

As our application is rather big and a port from existing, non pure FP, code we seems to be left with the following option:

- remove ZIO and ack the experiment as a failure (not what we would like to do);
- do not make effect runs on blocking but get random deadlocks, hard to debug (and a no-go for an app going to prod on customer infra),
- check all the 100kloc for what the code does in each case to use the correct blocking/async strategy (obviously the correct choice, and it was the long-term plan, but it clearly defeat the possibility to add ZIO per piece in an existing application, and I'm not sure how much resources we will need to spend on that).

**Comment by jdegoes** [comment]
@fanf The problem stems from the context switching, most likely (popping off the blocking pool after every primitive op). Though I need to benchmark to be sure.

To solve it now: simply switch your runtime to use fork/join thread pool. I can write that up if you like. This'll instantly solve 100% of your problems.

Longer term, the user won't have to care. Probably 2 months out, though.

@ashishprasad Yes, the distinction will go away

**Comment by fanf** [comment]
@jdegoes you mean the `Blocking` threadpool? IE something like: 
```
    val myRuntime = new DefaultRuntime() {
      object ForkJoinBlockin extends Blocking {
        val blocking: Blocking.Service[Any] = new Blocking.Service[Any] {
          val blockingExecutor: UIO[Executor] = {
            val pool = new ForkJoinPool(4)
            object executor extends Executor {
              override def yieldOpCount: Int = 10000
              override def metrics: Option[ExecutionMetrics] = None
              override def submit(runnable: Runnable): Boolean =
                try {
                  pool.execute(runnable)
                  true
                } catch {
                  case _: RejectedExecutionException => false
                }
              override def here: Boolean = false
            }
            executor.succeed
          }
        }
      }
      override val Environment: Environment = new Clock.Live with Console.Live with ZSystem.Live with Random.Live with Blocking.Live
    }
```

**Comment by fanf** [comment]
That make performance better only marginally (10% better than previous case, so still an order of magnitude worse than without ZIO).
 
Should I try to:
- also change the threadpool for non blocking effects to ForkJoin ? Change only some parameter of the existing (like number of thread = nb core/2 in place of x2 ?)
- change number of thread for ForkJoin (4 here is nb core /2) ?
- change yieldOpCount to Int.maxInt ?

**Comment by jdegoes** [comment]
Create it from Scala's global execution context, or wire up your own fork/join pool 👍

**Comment by fanf** [comment]
With the following code, we are at ~x5 worst performance in our big generation process (mixing I/O (files, postgres, LDAP), cpu intensive, sequential and parallel tasks). Still very bad, but better than the x10 (or even failure) from before.

```
new DefaultRuntime() {
      object ForkJoinBlockin extends Blocking {
        val blocking: Blocking.Service[Any] = new Blocking.Service[Any] {
          val blockingExecutor: UIO[Executor] = Executor.fromExecutionContext(Int.MaxValue)(scala.concurrent.ExecutionContext.global).succeed
        }
      }

      override val Platform: Platform = PlatformLive.fromExecutionContext(scala.concurrent.ExecutionContext.global)
      override val Environment: Environment = new Clock.Live with Console.Live with ZSystem.Live with Random.Live with Blocking.Live
    }
```

**Comment by jdegoes** [comment]
@fanf Be sure to turn off tracing, too, as this can negatively affect performance.

Finally, I do want to let you know that after we have 1.0 out, I'll turn my attention to this issue and make sure you can have high performance without manual specification of blocking effects.

**Comment by fanf** [comment]
Some more info: some parts of the code with ZIO are as fast as, or even faster than previous code. So it seems that it's not directly a contingency of ZIO runtime or as a whole, but usage patterns. 
We suspect that the problems happen on paradigm bounds. Most likely, we have some part that make assumption/requirement on the code, which is reasonable in imperative land (synchronized block?) and is not at all in ZIO.
So: I think we need to split appart that issue (ie: make effect blocking by default) and our perf problem, which is likely not linked to that, or not directly. 
I will keep posting our findings.

**Comment by fanf** [comment]
As promised, some news on the perf part: our measurement tends to confirm that the performance issue is not the fault of `ZIO` per se, but the context switching between  `ZIO` world and effectful world. 
We successfully fully ported one of the performance problematic point to full `ZIO` and we are now back to the perf region where we were before the switch (> one order of magnitude better, in a path called millions of times). 

So, this is good, but I don't really understand why the performance where so bad before. My hypothesis is that the JVM wasn't able to optimize code before the switch, and so we were remaining in non-optimized region (currently, we see a dramatic perf optimization after a couple of loops, when we didn't had it before). I'm not sure what to conclude about that. Good perf seem trickier to achieve in a mixed ZIO/historical app than in pure ZIO or pure imperative. Scala call by name seems costly, especially when you do thousands of it, and even more since you can't have an `implicit class Foo[A](val a: => A) extends AnyVal`. 

For reference, this is the code we use to switch from `liftweb Box[A]` to `ZIO[Any, RudderError, A]`. I tried to remove all the cats/fold part to only keep: 
```
  implicit class SimpleBoxToIO[E <: RudderError, A](res: => Box[A]) {
    def toIO: IOResult[A] = IOResult.effect(res).flatMap { //IOResult is just a IO.effect(...) + mapError to RudderError 
      case Full(res)   => res.succeed
      case eb:EmptyBox => Unexpected((eb ?~! "Error: ").messageChain).fail
    }
  }
```
But it didn't changed anything significative performance wise. (

**Comment by neko-kai** [comment]
@fanf minor correction: You can have an AnyVal implicit class for by-name with AnyVal for Function0 + implicit def - see ZIOSyntax [implicit def](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/syntax/package.scala#L25) & [class](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/syntax/ZIOSyntax.scala#L28). This works because by-name is just sugar over Function0, they're the same in runtime and converting between them is free.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fanf** [comment]
Oh cool! I didn't know about that. A bit sad scalac doesn't do the trick by
itself. Thanks!

**Comment by domsj** [comment]
> I think we can solve this problem once and for all, will just require a little time post 1.0.

I'm curious: what solution is this hinting at?

---

Fwiw https://github.com/reactor/BlockHound seems like a useful tool (you do need to mark relevant threads with `NonBlocking` interface from Reactor's lib, which surely isn't the case for zio right now) to help users in situations like this.

**Comment by fanf** [comment]
@domjs: AFAIK (derived from a two minutes chat with @jdegoes so I can be mostly wrong), the idea is to create all fibers in a default pool and have the underlying zio virtual machine observe if they make progress from one tick to the other. After some threshold of non progression, a fiber would be migrated automatically to a blocking thread pool.
The idea is *very* neat and again shows how important and powerful the design of zio (operations interpreted on a specifically tailored runtime) is.
getting to think about it, that design would likely have avoided #2373 (or perhaps just hidden a fiber count explosion? Could the interpreter also check if fibers are piling up at the same point, which is likely a synptom of something bad (lock or need for a circuit breaker) and should be reported to an user, at least in debug mode?)

**Comment by fanf** [comment]
Rust seems to have the same problem as us, and chose a solution which seems near to what @jdegoes proposed (AFAIU): 

https://async.rs/blog/stop-worrying-about-blocking-the-new-async-std-runtime/

Of course, that does not mean that you can write blocking code everywhere: https://www.reddit.com/r/rust/comments/ebpzqx/do_not_stop_worrying_about_blocking_in_async/

Really looking forward for that, because it will likely be a MASSIVE performance boost for non pure-zio application.

**Comment by fanf** [comment]
Some more information on the performance problem. 

We did quite a lot of tests with our set-up, and there is a substantial performance change if you use 1/ only one thread pool and 2/ (this part is very important, else perf are almost unchanged) you remove all the explicit pool thread pinning, 3/ you don't use `effectBlocking` which also add logic about interruptability of underlying thread.  

AFAIU, 2/ is important because for now, ZIO don't check if it is already on the correct thread pool before starting lock logic, and so there is an important cost paid upfront (fiber pause, logic to switch even if the final pool is the same, etc). 

Regarding thread pool used in the executor: we tried JDK 8 ForkJoinPool, JDK 11 ForkJoinPool,  and a version of `ZIO` blocking pool with slightly different parameters. 

- JDK 11 FJP is the most efficient and does not seems to lead to deadlock, but we can't use it because our customers still use JDK8 most of the time (*sight*)
- JDK 8 FJP leads to deadlocks. The problems seems to often happen when an other thread pool start a computation that at some point need to switch to `ZIO` pool (that happens a lot in our case, because we can't change our web framework pool for ex)
- the blocking thread pool leads to a git worse performances, but no deadlocks (and still much better perf than with two pools). Here, "a bit worse" is around 5% of JDK8 FJP, and much better is around 15~20%. 

The exact config used for now is the following, with some comments on parameter values after:
```
  def blockingExecutor = Executor.fromThreadPoolExecutor(_ => 5000) {
    val corePoolSize  = Math.max(5, Runtime.getRuntime.availableProcessors()/2)
    val maxPoolSize   = 500 // if we exhauste 500 thread, Rudder is most likely dead, no need to take the server with it
    val keepAliveTime = 30*1000L // default is 1000
    val timeUnit      = TimeUnit.MILLISECONDS
    val workQueue     = new SynchronousQueue[Runnable]()
    val threadFactory = new NamedThreadFactory("zio-rudder-mix", true)

    val threadPool = new ThreadPoolExecutor(
        corePoolSize
      , maxPoolSize
      , keepAliveTime
      , timeUnit
      , workQueue
      , threadFactory
    )

    threadPool
  }
```

- the yield cound was tested at `Int.MAX_VALUE`, `100`, `500`, `1000`, `5000`. `Int.MAX_VALUE` was avoided because we saw cases where, in a CPU bounded task, only one thread was ever used in place of the awaited count. We are not sure why, but we assume that in that case, the CPU bounded fiber doesn't even yield to fiber in charge of parallelism/the interpreter. 
`100` lead to a noticeable overhead, which was almost not noticeable for `500` and not at all for any of the other values. We landed to `5000` but there's not hard number in our use case to favor it compared to `1000`, so we settle in a bit more locality. 
- `corePoolSize` need to be a bit big especially in hardware configuration with 1 or 2 cores. `5` has no justification better than "with 2, we were spending our life recreating core pool thread, and with 10 threads are sitting there all the time without real justification". 
- `maxPoolSize` is big. Pragmatically in our use case, `500` is equivalent to threads stacking one over the others - we don't have a highly concurrent app, with (for ex) hundreds of requests to precess in parallel. So in our use case, we would prefer to crash the scala app that the host machine (because of other more critical services on it). 
- `keepAliveTime` lifted to `30s`. It need more tailoring, but toward a bigger number. The default `1s` is dramatically to low in our use case. 

We didn't tested impact of changing the queue implementation in that set-up for now. Previous tests seem to show that the impact was negligible (but not the same condition, so need to be assessed again). 

Hope it helps,

**Comment by jdegoes** [comment]
@fanf Super useful writeup! Thanks for all your work on this.

**Comment by iravid** [comment]
Thank you for documenting your findings @fanf.

**Comment by adamgfraser** [comment]
@fanf Yes thank you and I think encouraging! We added logic to check if we are already on a thread pool and if so not shift there, so that should address your second point, and we changed the default `effectBlocking` to not add in interruptibility logic to your third point. So I think the "out of the box" behavior should be much better now. We just started doing nightly releases. I don't know if it is possible to try that with your other dependencies, but would be interesting to see the impact those changes have for you.

**Comment by fanf** [comment]
@jdegoes @iravid @adamgfraser sorry I forgot one hyper-important thing: we were locked to `RC16` until now, because of #2373 and so, most of what I say may be less relevant now. 
I will try the niglties ASAP to see (likely tomorrow, I need to split cleanly the different part). 

Also: in hotspot, `tracing` is a performance killer, and it seems that marking an effect `untraced` does not propagate to effects composing it. At least, I observed that adding more `untraced` lead to more perf, even when added at different step of a big for. I don't have the least idea if it's the desired behavior or not, and if it's the desired behavior, it would be extremelly handy to be able to only mark a top-level effect as untraced (else in case of refactoring - especially factoring out some logic, you loose perf without remembering why)

**Comment by adamgfraser** [comment]
@fanf Regarding tracing, can you say a little more about what you are seeing? It should be compositional, so making an effect untraced  doesn't impact other effects composed after that one but does impact any sub-effects composed into it. For example:

```scala
val zio1 = for {
  _ <- doSomething.untraced
  - <- doSomethingElse // this effect will still be traced
} yield ()

val zio2 = zio1.untraced // now entire effect will be untraced
```

So you should be able to just call `untraced` at the top of your application or use `Runtime.withTracing(Tracing.disabled)` to disable it entirely.

**Comment by fanf** [comment]
@adamgfraser ok, what you describe is what I expected to happen, but it's not what I saw. Does that hold if there is `fork`, or pool switch (ie `effect/effectBlocking`)? 
And my observation can be just an artefact of the load system, I didn't investigated much.

**Comment by neko-kai** [comment]
@fanf Yes, tracing status should also be inherited by a fork (I think we have a test for that). The surest way to disable tracing completely is at `Platform` level - `platform.withTracing(Tracing.disabled)`

**Comment by fanf** [comment]
@neko-kai : I would prefer to not do that. I want tracing everywhere, safe in some hotspot (where is an error happen, I have other way to know). Tracing by default is the correct default. 
I will investigate that, most likely everything works as expecting and I moved several things at once somehow.

**Comment by fanf** [comment]
I tested RC18 nightlies (`1.0.0-RC17+281-0351fa8d-SNAPSHOT`). After a bit of frustration with all the changes for a RC (no more `.succeed/.fail`, no more `.traverse`/`.sequence`, big change in services which disproportionnaly impact users like me with a lot of `unsafeRun`, my own `Runtime` implementation, my own `Blocking` services... - but I can hear that I'm in an extrem minority, and that it's better to do these change now than to live with them - still, frustration and some edge to polish - living in the edge ;) )

The performances improvement are massive: around 20%. With that nightly, I'm almost as the same level of performance than what I got after tweeking thread pools in RC16 (as shown in https://github.com/Normation/rudder/pull/2743). RC16 version is still 3~5% better (with very raw and fluctuating measure, so extremelly scientific measure). 
One thing thought: the keepalive for threads in `default-async` seem very short. My application is alterning CPU bounded task and I/O, most done on parallel fibers. With a keep-alive of 1s, I experience a pattern of:
```
create 2 x nb_core threads on default async
use them for a couple seconds
kills them
a couple seconds latter: create 2 x nb_core threads on default async
etc
```
After 30 min of app running, the thread pool count was above 5000 thread created. 
This lead to a bit of overhead, but less than what I thought (a couple percent ?). 
In my case, switching to a keep alive of 30 s allowed to have the same 20 threads after 24h. 

So: this is going in the good direction! We still have a slowdown of +100% in some part of the app (not I/O bounded) that we need to investigate, but the main problems of the `blocking` threadpool seems to be now under control.

**Comment by adamgfraser** [comment]
@fanf That's great! I just pushed a PR suggested by @jdegoes to increase the default `keepAlive` time which should help with part of that. I'm also working on bringing back a version of the `defaultRuntime` which I should have later today. Let us know what you find regarding the remaining slowdowns and we can iterate on those as well.

**Comment by fanf** [comment]
Hello people, I'm digging up old threads. I saw I lot of work in ZIO 2.0 regarding thread pool management and ergonomics. 
I'm linking them here because it's likely relevant to people interested in that ticket, even if the core issue is still not adressed (if I understood correctly, but now most of the preliminary work to do it is in place):

- blocking thead pool switch deforestation & merge, see performance here: https://github.com/zio/zio/releases/tag/v2.0.0-M1
- Advances in the ZIO 2.0 Scheduler https://ziverge.com/blog/advances-in-the-zio-2-scheduler

**Comment by fanf** [comment]
It looks like there will be some changes in ZIO 2.0: https://twitter.com/jdegoes/status/1466346352955342850
