### ISSUE TITLE
Add combinators that accumulate errors on `zip`

### ISSUE THREAD

**Issue by catostrophe** [zio/zio#1280]
`Cause[E]` allows collecting failures via `&&` operator, but it's barely used in ZIO's combinators.
Many of those using `zip` internally may alternatively be implemented with an eager, error-accumulating semantic similarly to cats' `Validated`. Such combinators may be useful for validation problems.

Below is the suggested list of combinators to be extended with their error-accumulating versions.
ZIO:
- zipWith
- zip
- zipLeft
- zipRight
- zipWithPar
- zipPar
- zipParLeft
- zipParRight
- foreach/traverse
- foreachPar/traversePar
- foreachParN/traverseParN
- foreach_/traverse_
- foreachPar_/traversePar_
- foreachParN_/traverseParN_
- collectAll/sequence
- collectAllPar/sequencePar
- collectAllParN/sequenceParN
- forkAll
- forkAll_
- mergeAll
- mergeAllPar
- reduceAll
- reduceAllPar

Similar changes are proposed for `ZManaged`.

The open questions are:
- do we need all these extra combinators?
- how to name them to reflect their semantic?
- which symbolic operators to choose for aliases?
- how to reduce the amount of copypasta for implementing combinators derived from zip/zipWith?

A draft implementation that demonstrates the difference in semantics with the default `zip`:
```scala
/**
 * Sequentially zips this effect with the specified effect using the
 * specified combiner function. Eagerly performs both effects and accumulates
 * failures, if any.
 */
final def zipWithEager[R1 <: R, E1 >: E, B, C](that: ZIO[R1, E1, B])(f: (A, B) => C): ZIO[R1, E1, C] =
  (self.run zipWith that.run)((e1, e2) => (e1 zipWith e2)(f, _ && _)).unrun

/**
 * The inverse operation to `run`. Submerges the full result of execution.
 */
final def unrun[R1 <: R, E1 >: E, A1](implicit ev1: ZIO[R, E, A] <:< ZIO[R1, E1, Exit[E1, A1]]): ZIO[R1, E1, A1] =
  ev1(self).flatMap(_.foldM[R, E, A](ZIO.halt, ZIO.succeed))
```

**Comment by saraiva132** [comment]
@catostrophe I have implemented combinators that I believe might close this issue. 

Partition, validate and validateFirst and their parallel counterparts. 

What do you think might be missing? They are all done in terms of foreach which is the same as traverse, as it stands. I might take a closer look at this in some time and re-think what can be improved.

**Comment by jdegoes** [comment]
@saraiva132 Thank you for your work on this ticket!
