### ISSUE TITLE
ZIO Test: Cleanup type parameter orderings

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1281]
Sometimes `T` comes first; other times, `L`, and then `T`. The ordering should be consistent across all data types. 

See:

 - `SuiteCase`
 - `TestCase`
 - `ZTest`
 - `ZSpec`
 - etc.

In directory: `/test/src/**`

Possibly the correct ordering is `L` followed by `T`, because every node has `L`, but only some have `T`.

**Comment by adamgfraser** [comment]
I’ll take this.

**Comment by jdegoes** [comment]
@adamgfraser Thank you... yet again. 😄
