### ISSUE TITLE
ZIO Test: Remove dependency on Specs 2

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1283]
ZIO Test currently depends on Specs 2. The test suite should be refactored to use ordinary Scala `assert` in a main function, to avoid having any external dependencies.

**Comment by mtsokol** [comment]
I would like to give it a shot.

**Comment by mtsokol** [comment]
@jdegoes But how about all the quick-check-like tests? I've started rewriting `StackBoolSpec` and it's based on `scalacheck`. So maybe remove `spec2` but keep `scalacheck` dependency? Or write these contract/specification based tests from scratch?

**Comment by adamgfraser** [comment]
I'll take this.

**Comment by jdegoes** [comment]
@adamgfraser Thank you!
