### ISSUE TITLE
Should ZIO#foreachParN and related combinators take an Int instead of a Long?

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1288]
Right now `ZIO.foreachParN` and related combinators take a `Long` parameter to limit the degree of parallelism. Should this be changed to an `Int`? I have a hard time seeing when using an `n` value greater than `Int.MaxValue` would make sense. And the existing signature can lead to warnings about implicit numeric widening if an `Int` is passed that create unnecessary friction for users.

Happy to open a PR for this if there is agreement but wanted to check first since I am relatively new here and I know there has been a tremendous amount of prior work that has gone into this.

**Comment by iravid** [comment]
`Int` makes more sense to me. `ZStream` uses an `Int` for combinators with parallelism.

**Comment by adamgfraser** [comment]
Okay, I will submit a PR on this.

**Comment by vasilmkd** [comment]
@adamgfraser @iravid Please also double check `ZStream` combinators. Some of them are definitely using `n: Long`.

**Comment by adamgfraser** [comment]
Okay. Should we change `Semaphore` too?

**Comment by iravid** [comment]
Right! Good catch @vasilmkd.
