### ISSUE TITLE
Add a version of `Semaphore#withPermit/withPermits` that returns a Managed

### ISSUE THREAD

**Issue by iravid** [zio/zio#1289]
This would be more composable compared to `withPermit(task)`, and safer compared to bare usage of `acquire/release`.

In the implementation, it's important to put the `prepare` step in the uncancelable reservation step, and `awaitAcquire` in the cancelable step.

**Comment by iravid** [comment]
cc @vasilmkd

**Comment by vasilmkd** [comment]
Can I take it?

**Comment by iravid** [comment]
By all means

**Comment by vasilmkd** [comment]
As naming is one of the hardest things to get right, do I make overloads that have `Managed` return type or name them `withPermitManaged`?

**Comment by iravid** [comment]
I'm good with `withPermitManaged`
