### ISSUE TITLE
ZIO Test: Pull stream tests into new `stream-tests` top-level project

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1294]
As part of preparation to make ZIO Test depend on Streams tests need to be pulled out into their own top-level project, following `core` / `core-tests`.

**Comment by adamgfraser** [comment]
Mind if I take this? I will think we will need to do this to fully remove the Specs2 dependency from ZIO Test since right now the tests in streams depend on the test runtime in Test.

**Comment by jdegoes** [comment]
@adamgfraser That would be awesome!

**Comment by jdegoes** [comment]
@adamgfraser Any ETA on this? 

Trying to introduce Stream into ZIO Test but due to circular dependencies, can't be done until this one is closed. Wondering whether to grab this or pray your evening isn't booked. 😂

**Comment by adamgfraser** [comment]
@jdegoes Sorry didn't see this early. Just submitted a PR.

**Comment by iravid** [comment]
Done in #1296
