### ISSUE TITLE
Update contributors guide

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1298]
The contributors guide is a bit out of date, especially with respect to testing (now that the tests have been moved into standalone projects); and should be updated.

**Comment by jdegoes** [comment]
### Sorting Contents of Traits / Classes / Objects

Convention for sorting methods / vals / types / operators inside a class / object:

 - abstract types (alphabetically in this category)
 - abstract operators (alphabetically in this category)
 - abstract named defs / vals  (alphabetically in this category)
 - concrete types (alphabetically in this category)
 - concrete operators (alphabetically in this category)
 - concrete named methods (alphabetically in this category)

### Companion Objects for Aliases

 - Effect types: `Task`, `UIO`, `RIO`, `IO`
 - Etc.

**Comment by adamgfraser** [comment]
I will take this.

**Comment by adamgfraser** [comment]
I think this has been addressed by some of the improvements made to the contributors guide by @saraiva132 and others.
