### ISSUE TITLE
Add ZIO#eventually

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1299]
```scala
trait ZIO[R, E, A] { self =>
  def eventually: ZIO[R, Nothing, A] = self orElse eventually
}
```

/cc @LGLO

**Comment by vasilmkd** [comment]
Anything more to this? I'll take it.

**Comment by LGLO** [comment]
I wasn't clear enough. I meant adding `eventually` to assertions :D but this one looks good!
`repeat(Forever)` is almost same (but requires `Clock`).

**Comment by vasilmkd** [comment]
@LGLO Can you please point me to the test you mentioned?

**Comment by vasilmkd** [comment]
All this time, I was searching for ZIOSpec or similar...
