### ISSUE TITLE
ZIO Test: Refactor MockRandom to use pseudo-random number generator (PRNG)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1301]
MockRandom (in `test` project) currently has simple lists, defined by users, of "random" data. This is useful sometimes, but is not a very good default mock implementation.

We should power the methods of MockRandom with a pseudo-random number generator (which can be kept track of in the `MockRandom.Data` structure that is currently fed into `MockRandom`), and implement all methods in terms of this.

There are [many](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/Random.java) sources of inspiration, [this one](https://github.com/NICTA/rng), perhaps, the closest.

**ZIO Test won't be useful for property checking until this ticket is completed.**

**Comment by adamgfraser** [comment]
I’ll take it.

**Comment by jdegoes** [comment]
Awesome! Btw you in Philly?

**Comment by adamgfraser** [comment]
@jdegoes Yes.
