### ISSUE TITLE
ZIO Test: Add Gen combinators

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1308]
We need combinators for ZIO Test Gen. One can find examples in QuickCheck, SmallCheck, ScalaCheck, and Hedgehog (this one may be the closest fit).

Examples:

 - `Gen.oneOf`
 - `Gen.listOf`
 - `Gen.vectorOf`
 - `Gen.string`

Etc.

**Comment by adamgfraser** [comment]
I would love to take this.

**Comment by jdegoes** [comment]
@adamgfraser It's all yours! Thank you. 🙏

**Comment by jdegoes** [comment]
@adamgfraser Btw I will be in Philadelphia on Sunday on my way out of the country for a vacation. If you don't mind a crowd (my family), let's meetup!

**Comment by adamgfraser** [comment]
@jdegoes Would love to!

**Comment by ghostdogpr** [comment]
Closed by #1356
