### ISSUE TITLE
Add a Sink for grouping elements into n-sized lists, sets, maps

### ISSUE THREAD

**Issue by iravid** [zio/zio#1309]
Signatures (happy to hear alternatives to naming):
```scala
def collectAllN(n: Int): ZSink[Any, Nothing, A, A, List[A]]
def collectAllToSet[A]: ZSink[Any, Nothing, Nothing, A, Set[A]]
def collectAllToSetN[A](n: Int): ZSink[Any, Nothing, A, A, Set[A]]
def collectAllToMap[K, A](key: A => K): ZSink[Any, Nothing, Nothing, A, Map[K, A]]
def collectAllToMapN[K, A](n: Int)(key: A => K): ZSink[Any, Nothing, A, A, Map[K, A]]
```

`collectAllN` can be a special-cased version of `Sink.foldUntil`. The latter 4 compute the stopping condition as a function of the state, not the elements, so they can't use `foldUntil`.

**Comment by PawelGizka** [comment]
I can take this.

**Comment by PawelGizka** [comment]
@iravid so should I create functions in `Sink` which produce for example: `ZSink[Any, Nothing, A, A, List[List[S]]]` ? Or do you mean something else?

**Comment by iravid** [comment]
@PawelGizka thank you! Added the signatures to the description. Let me know if they don't add up.
