### ISSUE TITLE
ZIO Test: Add Common Predicates

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1314]
Following the existing code in Predicate.scala, inside the `/test/...` directory (_ZIO Test_), this ticket is to add common predicates.

A predicate is basically a function from some value (like a string) to a test result, either success or failure (with a message). Mostly, existing similar predicates can be copy / pasted / modified, so there is no need to engineer complex code.

A good place to find predicates is boolean-returning methods on Scala collections, the String type in Java / Scala, and so forth.

These would include:

 - `startsWith`
 - `endsWith`
 - `matches` (Regex)
 - Etc.

Note that each predicate must be a _verb_; so, for example, `initial` is not a good name for a predicate, but `startsWith` is a good name.

**Comment by jaliss** [comment]
I'd like to take this.

**Comment by jdegoes** [comment]
@jaliss Awesome, thank you!

**Comment by adamgfraser** [comment]
It would be nice to have a predicate for numerical equality within some tolerance that we could use with types like `Double`.

**Comment by jdegoes** [comment]
`approximatelyEquals`, perhaps?

**Comment by ghostdogpr** [comment]
+ `sameElements`

**Comment by adamgfraser** [comment]
`isEmpty` and `nonEmpty`

**Comment by jdegoes** [comment]
@jaliss You still working on this one? (No rush, just wondering.)

**Comment by jaliss** [comment]
yes @jdegoes.  I'll spend more time on it this week.

**Comment by adamgfraser** [comment]
@jaliss We may want to have people at the Warsaw Hackathon next weekend work on adding more assertions as well. Can we try to get the ones you have done merged this week so others can build on them? We can always open up a follow-up PR if there are other assertions you want to add that you haven't had a chance to implement yet.

Just a heads up we added a `containsString` assertion as part of #1668 so no need to worry about that one.

**Comment by jaliss** [comment]
@adamgfraser sounds good.   I'll put up a PR this monday/tuesday.  Ok, I'll remove `containsString` from my changes then :)

**Comment by jaliss** [comment]
@adamgfraser I just created a PR with the changes I had so far.  If it looks good we can merge and create new issues to add more assertions.

**Comment by adamgfraser** [comment]
@jaliss Awesome! Will take a look today.
