### ISSUE TITLE
Implement Cause#untraced

### ISSUE THREAD

**Issue by kaishh** [zio/zio#1317]
Motivation: sometimes errors are propagated to callers in situations where a stacktrace might reveal sensitive information such as the structure of proprietary application's source code – or it might simply be too noisy, therefore sometimes we may want to filter a Cause before returning it. Also, some users expect that calling `ZIO.untraced` will completely remove debugging information – this is not the case as debugging information outside of the untraced region is still preserved; it may still be useful to provide a mechanism for removing it.

Implement a function in `Cause` with signature:

```scala
def untraced: Cause[E]
```

that would remove all tracing information from a Cause (by unwrapping `Cause.Traced` nodes)

It can then be used e.g. with `mapErrorCause`: `io.mapErrorCause(_.untraced).untraced` to stop sampling and remove all debug output for all errors in a region.

**Comment by shankarshastri** [comment]
@kaishh, I can take up this, if you can provide me a few pointers on where I can start on.

**Comment by kaishh** [comment]
@shankarshastri 
Sure! Take a look existing functions in `Cause`, especially those that use `Cause.fold` – once you get how to use `fold` you'd probably know how to use it to implement `untraced`!
DM me on gitter if you want to talk more!

**Comment by shankarshastri** [comment]
Sure @kaishh

**Comment by kaishh** [comment]
Closed in https://github.com/zio/zio/pull/1354
