### ISSUE TITLE
Clock is not compatible with Scala.js

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1325]
`Clock` uses `java.time`, which is not part of the Scala.js Java library. We get around this in the tests by depending on `scalajs-java-time` but this does not implement `OffsetDateTime` or `ZoneId` (see [implementation of Instant](https://github.com/scala-js/scala-js-java-time/blob/master/src/main/scala/java/time/Instant.scala)). I think this didn't come up because you don't see the error until runtime and almost all of our tests are on the JVM right now. But for example if I try to run the program below on Scala.js I get an error "Referring to non-existent class java.time.ZoneId", even with a dependency  on `scalajs-java-time`.

```scala
object TestMain  {

  def main(args: Array[String]): Unit = {

    println(java.time.LocalDate.now)      
    // 2019-08-02

    val runtime = new zio.DefaultRuntime {}
    val clock = zio.clock.Clock.Live
    println(runtime.unsafeRun(clock.clock.currentDateTime))
    // [error] Referring to non-existent class java.time.ZoneId
  }
}
```

Am I missing something here?

**Comment by regiskuckaertz** [comment]
I know ZIO is dependency free, but then, JavaScript. Browsers are getting stronger in their support of i18n-related APIs, but still far from java time. Meanwhile, there's https://github.com/zoepepper/scalajs-jsjoda

**Comment by jdegoes** [comment]
Perhaps we should depend on `scalajs_jsjoda` in tests, and document this thoroughly?

OTOH 2 years since last commit is mildly concerning, although same can be said of many other Scala.js libraries.

The alternative is depending less on `java.time` and relying more on "simple" structures to represent the very few time-related concepts we use.

Agreed it needs to be handled and as part of 1.0 since it may affect the API.

**Comment by kaishh** [comment]
We use `scala-java-time` in LogStage.js, could be an option (last commit 21 days ago) https://github.com/cquiroz/scala-java-time

**Comment by jdegoes** [comment]
@kaishh That looks much better maintained!

**Comment by adamgfraser** [comment]
It looks like using `scala-java-time` is working in ZIO Test. Do we want to do the same thing in the core tests and mark this as resolved or still consider more broadly the time structures we are using?

**Comment by ritschwumm** [comment]
does Zio actually need more than Instant and Duration? and if so, for what?

**Comment by jdegoes** [comment]
> It looks like using scala-java-time is working in ZIO Test. Do we want to do the same thing in the core tests and mark this as resolved or still consider more broadly the time structures we are using?

I think doing the same thing in core tests makes sense, and then thoroughly documenting the dependency no the shim in the Scala.js interop section on the website.

**Comment by jdegoes** [comment]
> does Zio actually need more than Instant and Duration? and if so, for what?

It uses time zone, for example.

**Comment by adamgfraser** [comment]
@jdegoes Okay, I will submit a PR on that.

**Comment by jdegoes** [comment]
@adamgfraser Thank you!

**Comment by ritschwumm** [comment]
@jdegoes i see that - but is it really necessary to do so, or can you get away without "calendar-based" dates completely?

in my experience, dealing with calendars is a huge and difficult topic, and seldomly got right. if you can stay away from calendars - do so, you're doing yourself and your users a favor.

**Comment by adamgfraser** [comment]
@ritschwumm It is a good question. Searching through the current code base `OffsetDateTime` doesn't appear anywhere except in `Clock` implementations. I think the question is whether we want to be able to support scheduling events at a certain point in time in the future (e.g. send this report every Monday morning at 9 AM). I know there is some ongoing work on that and if we want to be able to support that use case then we need a concept of calendar based time. Otherwise I would tend to agree we could get away with just having a concept of duration.

**Comment by ritschwumm** [comment]
@adamgfraser i guess if i'd wanted to implement something like a cron-like scheduler, i'd put that in a a separate module and depend on something that can deal with calendars there, keeping the core clean and simple.

**Comment by jdegoes** [comment]
@ritschwumm It was not in the original design... worth checking to see if we really need it.
