### ISSUE TITLE
Test suite ignored when using ExecutionStrategy.ParallelN

### ISSUE THREAD

**Issue by edvmorango** [zio/zio#1331]
The reference for snippet and the discussion can be found at #1284

**Comment by ghostdogpr** [comment]
How do you run it? I've tried the code from your PR and they don't get ignored, whether I use Sequential or Parallel. I just do `test:run` in sbt. Using the run button in IntelliJ also works.

**Comment by edvmorango** [comment]
Initially, I followed the contributor's guide, `test:compile` followed by `test`, I didn't receive feedback from the Spec so I tried to execute using the IDE and got success for `tests` and no response for `suites`, after changing the execution strategy of executor to `Sequential` I started to receive the expected response for `suites`  when running using the IDE.  When I executed using `test:run` worked perfectly. I think maybe I can update the contributor guide with `test:run` but I'm not sure about the IDE behavior for `suites`.

**Comment by ghostdogpr** [comment]
That’s because we’re missing #1259. Sbt doesn’t know how to run those ZIO Test tests yet, so we have to use `run` instead of `test` for now. No need to change contributor guide since we will be able to use `test` (and that’s the way to run existing tests).
