### ISSUE TITLE
More flaky tests

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#1337]
Got few flaky tests trying to build the project. These tests haven't been reported yet.

revision: 222999eaacb43630bf373d6e0225a3d444bd4ab0
java: openjdk version "11.0.4" 2019-07-16

1) 
> [error]     x bracket release called on interrupt
> [error]  42 != 0 (RTSSpec.scala:698)

reproduced two times in a row during initial build

2) 

> [info]   Stream merging
> [error]     x merge
> [error]  TIMEOUT: 60 seconds (TestRuntime.scala:18)

reproduced once

3) this one looks scary

> [info] ExitSpec
> [info]     Cause
> [info]       + `Cause#died` and `Cause#stripFailures` are consistent
> [info]       + `Cause.equals` is symmetric
> [info]       + `Cause.equals` and `Cause.hashCode` satisfy the contract
> [info]     Then 
> [info]       + `Then.equals` satisfies associativity
> [info]       + `Then.equals` satisfies distributivity
> [info]     Both
> [info]       + `Both.equals` satisfies associativity
> [info]       + `Both.equals` satisfies commutativity
> [info] Total for specification ExitSpec
> [info] Finished in 4 seconds, 998 ms
> [info] 7 examples, 610 expectations, 0 failure, 0 error
> 
> 
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:361)
> 	at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
> 	at scala.collection.immutable.HashMap.updated(HashMap.scala:39)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$Constants.put(AkkaLineNumbers.scala:95)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$Constants.readOne(AkkaLineNumbers.scala:103)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.getConstants(AkkaLineNumbers.scala:228)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.getInfo(AkkaLineNumbers.scala:155)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.apply(AkkaLineNumbers.scala:64)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbersTracer.traceLocation(AkkaLineNumbersTracer.scala:30)
> 	at zio.internal.stacktracer.Tracer$$anon$1.traceLocation(Tracer.scala:35)
> 	at zio.internal.FiberContext.traceLocation(FiberContext.scala:105)
> 	at zio.internal.FiberContext.pushContinuation(FiberContext.scala:112)
> 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:323)
> 	at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:593)
> 	at zio.internal.FiberContext$$Lambda$36718/0x00000008456be440.run(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:361)
> 	at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:359)
> 	at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
> 	at scala.collection.immutable.HashMap.updated(HashMap.scala:39)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$Constants.put(AkkaLineNumbers.scala:95)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$Constants.readOne(AkkaLineNumbers.scala:103)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.getConstants(AkkaLineNumbers.scala:228)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.getInfo(AkkaLineNumbers.scala:155)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbers$.apply(AkkaLineNumbers.scala:64)
> 	at zio.internal.stacktracer.impl.AkkaLineNumbersTracer.traceLocation(AkkaLineNumbersTracer.scala:30)
> 	at zio.internal.stacktracer.Tracer$$anon$1.traceLocation(Tracer.scala:35)
> 	at zio.internal.FiberContext.traceLocation(FiberContext.scala:105)
> 	at zio.internal.FiberContext.pushContinuation(FiberContext.scala:112)
> 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:323)
> 	at zio.Runtime.unsafeRunAsync(Runtime.scala:93)
> 	at zio.Runtime.unsafeRunAsync$(Runtime.scala:79)
> 	at zio.BaseCrossPlatformSpec.unsafeRunAsync(BaseCrossPlatformSpec.scala:19)
> 	at zio.Runtime.unsafeRunSync(Runtime.scala:68)
> 	at zio.Runtime.unsafeRunSync$(Runtime.scala:65)
> 	at zio.BaseCrossPlatformSpec.unsafeRunSync(BaseCrossPlatformSpec.scala:19)
> 	at zio.Runtime.unsafeRun(Runtime.scala:57)
> 	at zio.Runtime.unsafeRun$(Runtime.scala:56)
> 	at zio.BaseCrossPlatformSpec.unsafeRun(BaseCrossPlatformSpec.scala:19)
> 	at zio.RTSSpec.$anonfun$testSyncEvalLoopEffectThrow$6(RTSSpec.scala:240)
> 	at zio.RTSSpec$$Lambda$42345/0x00000008461f4840.apply(Unknown Source)
> 	at org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:21)
> 	at org.specs2.matcher.Expectable.value(Expectable.scala:21)
> 	at org.specs2.matcher.EqualityMatcher.apply(EqualityMatcher.scala:25)
> 	at org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:51)
> 	at org.specs2.matcher.MustExpectable.must_$eq$eq$eq(MustExpectable.scala:20)
> 	at zio.RTSSpec.testSyncEvalLoopEffectThrow(RTSSpec.scala:240)
> 	at zio.RTSSpec.$anonfun$is$11(RTSSpec.scala:29)
> [info] shutting down server
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> Hello
> [info] MutableConcurrentQueueSpec
> [info]     Make a bounded MutableConcurrentQueue
> [info]      + of capacity 1 returns a queue of capacity 1.
> [info]      + of capacity 2 returns a queue of capacity 2.
> [info]      + of capacity 3 returns a queue of capacity 3.
> [info]     With a RingBuffer of capacity 2
> [info]      + `offer` of 2 items succeeds, further offers fail.
> [info]      + `poll` of 2 items from full queue succeeds, further `poll`s return default value.
> [info] Total for specification MutableConcurrentQueueSpec
> [info] Finished in 58 ms
> [info] 5 examples, 0 failure, 0 error

**Comment by saraiva132** [comment]
Either tag tests as flaky on a PR or close this please.
