### ISSUE TITLE
Add ZIO#doWhile

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1339]
In working with some code where I needed to use effects within an algorithm I found myself wanting the following method:

```scala
def doWhile[R, E, A](zio: ZIO[R, E, A])(f: A => Boolean): ZIO[R, E, A] =
  zio.flatMap(a => if (f(a)) doWhile(zio)(f) else ZIO.succeed(a))
```

Is that something that would be worth adding as a method on the `ZIO` companion object?

One issue is whether we can implement it in terms of `Schedule`. We could do:

```scala
def doWhile[R, E, A](zio: ZIO[R, E, A])(f: A => Boolean): ZIO[R with Clock, E, A] =
  zio.repeat(ZSchedule.doWhile(f))
```

But then we are introducing an unnecessary `Clock` dependency since every decision in the `Schedule` we are using has a zero delay. Is there a way to refactor `Schedule` so that schedules with non-zero delay require a `Clock` environment and do their own sleeps, while schedules with zero delay do not require that environment? Then methods like `repeat` and `retry` could just propagate the environment required by the underlying schedule.

**Comment by jdegoes** [comment]
> Is there a way to refactor Schedule so that schedules with non-zero delay require a Clock environment and do their own sleeps, while schedules with zero delay do not require that environment?

To do this, we have to push the sleeps into the `Schedule`. Right now, the driver (`repeat` / `retry`) is responsible for sleeping, but if we push the sleeping into `Schedule` (an early version did this), then `Clock` would only be needed for schedules that actually sleep.

I think this could be a good move and cleanup code as well as answer some unresolved questions about Schedule

I will try to open a new ticket to investigate this.
