### ISSUE TITLE
Deprecate all succeedLazy

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1346]
Too many people are confused about `succeedLazy`. Given a pure FP market, it could survive, but given the target audience of ZIO, I don't think it's a good fit.

We should deprecate all `succeedLazy` methods and prepare to delete them for 1.0.

**Comment by kaishh** [comment]
Big :+1: on this, I've never seen `succeedLazy` NOT being misused in our codebase 😆 
I only ever used it once, but I don't think a strict `succeed` would change anything in that place.

**Comment by denisgarci** [comment]
What should the message be? Use `succeed`?
