### ISSUE TITLE
Limited memoize

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1359]
We have `final def memoize: ZIO[R, Nothing, IO[E, A]]`, which will effectively cache the result of an IO.

I would like to have a limited `memoize` that "times out".
Using the environment's `Clock`, it should be possible to basically build a mini-cache with an attached TTL.

Here is my use-case:
I have a REST API I need to auth with. I know that the JWT expires after 1 hour, so I would like to prevent running to the token endpoint for at least 45 minutes and hitting the other endpoints with said token over and over.
Upon expiry of the memoization, my IO chain should then grab a new JWT and memoize that for 45 minutes... etc.

**Comment by adamgfraser** [comment]
I can take this.

**Comment by ghostdogpr** [comment]
Closed by #1361
