### ISSUE TITLE
ZStream.mapMPar(1) may process stream element out of order

### ISSUE THREAD

**Issue by rtimush** [zio/zio#1367]
Code to reproduce:
```scala
for {
  queue  <- Queue.unbounded[Int]
  _      <- Stream.range(0, 9).mapMPar(1)(queue.offer).runDrain
  result <- queue.takeAll
  _      <- if (result == result.sorted) putStrLn("Ok")
            else putStrLn(s"Out of order: ${result}")
} yield ()
```
With relatively high probability it prints something like:
```
Out of order: List(0, 1, 2, 3, 4, 5, 6, 7, 9, 8)
```
It doesn't violate any of the guarantees scaladocs give, but may be surprising.

**Comment by vasilmkd** [comment]
Did work like this for `flatMapPar`. Can we enumerate all the parallel methods so that I can check them? Do they all end in `Par`?

**Comment by iravid** [comment]
Hi @vasilmkd - the solution is probably very similar. For stream they all end with `Par`, yes.

**Comment by vasilmkd** [comment]
Yes, we should have checked last time. Better late than never I guess.

**Comment by vasilmkd** [comment]
Is it possible that in this particular code example, the queue is actually responsible for the nondeterminism (i.e. it wakes up fibers out of order). Not sure how unbounded queue is implemented, will take a look.

**Comment by vasilmkd** [comment]
Actually, I used @rtimush 's code as a test. Because we fixed the ordering in `flatMapPar` now `mapMParUnordered` actually passes the ordering test, and mapMPar does not, which I find extremely funny. :smile:
Opening a PR where we can discuss what to do.

**Comment by vasilmkd** [comment]
This is the main source of non-determinism: https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1041, namely, `permits.withPermit(...)` which executes the effect produced by the mapping function with a permit.

Technically, if we `runCollect` on the stream and compare the produced `List`, we will get the "expected" ordering of 10 `Boolean` values (or if we preserve the original values, 0..9).

@iravid I would even go as far as to relabel this issue as expected behavior.

I will edit the PR as a test that shows that `mapMPar` indeed preserves the ordering against `mapM`.

**Comment by rtimush** [comment]
@vasilmkd you're right, the resulting stream is always correctly ordered, it's just about the processing order. Nevertheless, I would still say this behavior can be surprising. One more thing that came into my mind is that for the same reason, `mapPar(1)(f).take(n)` can run `f` more than `n` times:

```scala
for {
  queue     <- Queue.unbounded[Int]
  _         <- Stream.range(0, 10).mapMPar(1)(queue.offer).take(1).runDrain
  // can be `List(0)` but can also be `List(1, 0)`
  processed <- queue.takeAll
} yield () 
```

**Comment by vasilmkd** [comment]
I definitely agree that the behavior is surprising at times.

This is a very interesting demonstration. This probably shows a bug in the short circuiting of the combinator.

@iravid Should we pursue an implementation more in line with `ZStream#flatMapPar`?

**Comment by iravid** [comment]
I think it's possible to slightly modify the current implementation to achieve the right ordering:
- the permit should be acquired not in the forked fiber, but in the `foreachManaged` function
- a latch should be added that prevents `foreachManaged` from progressing before the fiber starts

That should do the trick no @vasilmkd ?

**Comment by ghostdogpr** [comment]
The test is flaky btw, not sure it's related: https://circleci.com/gh/zio/zio/18307
