### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1368]
This may be interesting for us:
https://github.com/features/actions

**Comment by softinio** [comment]
I was at the launch event and I was impressed with offering. First thing I thought was if we have an interest to do it all again :-) 

It goes GA November 13th.

I should have my beta access in next 24 hours apparently so if that enables me to try with ZIO we can have a play with it in parallel to circle to see what its like at some point.

**Comment by iravid** [comment]
I'm pretty happy with CircleCI now so unless this offers massive benefits I'd prefer we leave the CI alone for a year ;-)

**Comment by iravid** [comment]
Also, SoftwareMill already paid for the CircleCI plan. Not sure if that's a monthly/annual payment.
