### ISSUE TITLE
Provide convenient way to create companion objects for specialized ZIO aliases

### ISSUE THREAD

**Issue by rnd4222** [zio/zio#1370]
Imagine that I want to use specific environment and error types in my application, so I've created an alias for ZIO:
`type MyIO[A] = ZIO[MyEnv, MyError, A]`
Now, it would be quite useful to also have a companion object for `MyIO` as it's done for `Task`/`IO` types:
```
object MyIO extends ZIOFunctions {
  type UpperE = MyError
  type LowerR = MyEnv
}
```
Unfortunately, it isn't possible because `ZIOFunctions` is package private.

**Comment by jdegoes** [comment]
The new `ZIO` uses a different approach that does not involve `ZIOFunctions`: now everything delegates manually to ZIO. This is more boilerplate for library authors but greatly improves error messages and type inference (fewer / more specific type parameters).
