### ISSUE TITLE
Better documentation for ZIO.Succeed and ZIO#succeed

### ISSUE THREAD

**Issue by azolotko** [zio/zio#1371]
Apparently, `ZIO.Succeed` has a special treatment from ZIO, which needs additional coverage in documentation. 

Consider the following code:

```scala
{
  for {
    _ <- zioAction1
    _ <- zioAction2
    _ <- zioAction3
  } yield ()
}.succeed(())
```

While not being pretty or idiomatic, it is an interesting learning curve step. The intent here was to discard any error that might have appeared during execution of the actions above. In reality though, only `zioAction1` is going to be executed, and `zioAction2` and `zioAction3` are discarded, even when `zioAction1` succeeds.

The reason for this is the following code which looks ahead and discards nested flatMaps if it encounters `ZIO.Succeed` as a next action: https://github.com/zio/zio/blob/v1.0.0-RC11/core/shared/src/main/scala/zio/internal/FiberContext.scala#L273

It turns out that, to correctly achieve the original goal, the code above should be written like this:

```scala
{
  for {
    _ <- zioAction1
    _ <- zioAction2
    _ <- zioAction3
  } yield ()
} catchAll (_ => ZIO.unit)
```

Taking myself and a small group of people whom I showed the above example, the behaviour is not obvious from beginner's point of view, and needs additional coverage in documentation.

**Comment by dreverri** [comment]
It doesn't seem like `zioAction1` is executed either:
https://scastie.scala-lang.org/WZM9BmHtSJS5yWt0bsv6Rw

I wonder what the use case is for `succeed` on the trait?

**Comment by dreverri** [comment]
Looks like the trait method discards the current ZIO value and just returns a new ZIO:
https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZIO.scala#L1045

**Comment by azolotko** [comment]
Yes, you are correct. I incorrectly stripped down a larger example that I had, misunderstanding its meaning. I think the issue is invalid then.

**Comment by dreverri** [comment]
Maybe succeed should be removed from the trait?
