### ISSUE TITLE
Make `fromFuture` methods translate exceptions on Future creation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1375]
Currently, `ZIO.fromFuture(_ => throw e).either` will kill the fiber. This should be changed so that `ZIO.fromFuture(_ => throw e).either` is `Left(e)`.

We should have a test in `RTSSpec` to demonstrate the behavior.

Possibly, we should also look at `Fiber.fromFuture` and other `fromFuture` methods to see if any can be improved in a similar way.

**Comment by vilu** [comment]
I'll give this one a go.

**Comment by vilu** [comment]
https://github.com/zio/zio/pull/1376

If no feedback is given and this PR is considered OK I'll look into Fiber.fromFuture and any other fromFuture I can find in a subsequent PR.
