### ISSUE TITLE
Guava (ListenableFuture) interop library

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio#1381]
https://github.com/sideeffffect/interop-guava

this library adds interop for Guava's `ListenableFuture` (used e.g. in gRPC)

please add this repository to ZIO organization

**Comment by sideeffffect** [comment]
@jdegoes I believe `interop-guava` already uses CircleCI (it's copied from `interop-java`)
I'd be happy to maintain it
do you think you (or anybody else) could arrange the move under the ZIO organization umbrella?

**Comment by sideeffffect** [comment]
somebody should add interop-guava to CircleCI -- the config files are ready in the git repo, it just needs to be turned on the CircleCI side

https://circleci.com/gh/zio/interop-guava/tree/master

**Comment by ghostdogpr** [comment]
I’ll have a look!

**Comment by ghostdogpr** [comment]
Done! Here's the first build of master: https://circleci.com/workflow-run/07cf1401-d177-4b79-a078-c7dc36680b1a
I also enabled builds on PRs, for the existing PR it will probably get trigger next time you push something.

**Comment by sideeffffect** [comment]
cool! could you also make me and admin of the repo?

**Comment by ghostdogpr** [comment]
Done!

**Comment by ghostdogpr** [comment]
Closing this one then.
Once it's ready (and it looks like it's already ready), you could make a PR to add it here: https://github.com/zio/zio/blob/master/docs/ecosystem/ecosystem.md
