### ISSUE TITLE
Expose Executor as ExecutorService

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio#1414]
Needed for ZIO NIO https://github.com/zio/zio-nio/issues/29 .
Add method on Executor analogous to `asEC` but returning an ExecutionCotextExecutorService.

**Comment by PawelGizka** [comment]
I take this

**Comment by dzajkowski** [comment]
@jczuchnowski looks like a basic implementation is straight forward: https://gist.github.com/viktorklang/5245161

**Comment by jczuchnowski** [comment]
Damn, this actually looks very promising!
