### ISSUE TITLE
ZIO Test: Add composition operators to Assertion

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1433]
Currently in ZIO Test (`test` project / directory), it is quite inconvenient to make multiple assertions on different values. A pattern seen in `ZQueueSpec.scala` in `core-tests` is as follows:

```scala
assert((v1, v2, o1, o2), Predicate.equals((10, 20, true, true)))
```

This does not scale in general (although it works for `Predicate.equals`, specifically), and leads to overly verbose error messages in the event of failure.

While we can (and probably should) define `Predicate.tuple2` (etc.) predicates, a better solution for assertion composition is simply to define operators on `Assertion`.

In particular, we can define the following operators on the `Assertion` trait:

 - `&&` — This will compose two `Assertion` into one, requiring that both succeed for the result to succeed.
 - `||` — This will compose two `Assertion` into one, requiring that one or the other succeed for the result to succeed.

For now, we can simply choose one failure ("first failure") if both fail. Later, we may want to expand `Assertion` into a free semiring to collect all failures. 

The type signatures requiring implementation:

```scala
trait Assertion[+E] {
  def && [E1 >: E](that: Assertion[E1]): Assertion[E1] = ???
  def || [E1 >: E](that: Assertion[E1]): Assertion[E1] = ???
}
```

In addition, we should define two tests in the `test` package for ZIO Test; and finally, we should refactor `ZQueueSpec.scala` to use the new assertion operators, as proof the "mission" of this ticket has been successfully accomplished.

**Comment by adamgfraser** [comment]
I can take this.

**Comment by jdegoes** [comment]
@adamgfraser Awesome, thank you!
