### ISSUE TITLE
ZIO Test: Add traversal methods for Assertion

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1437]
We need sequence / traverse on `Assertion` (in the `test` project / top-level directory):

```scala
Assertion.foreach[A, E](as: Iterable[A])(f: A => Assertion[E]): Assertion[List[E]]
Assertion.collectAll[E](as: Iterable[Assertion[E]]): Assertion[List[E]]
```

with corresponding unit tests.

**Comment by adamgfraser** [comment]
I’m already working on adding methods and tests for Assertion so I can take this as well.
