### ISSUE TITLE
Question: Why is syntax for IO

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1445]
Question that may turn into an easy ticket :)

Why are the implicit conversions in https://github.com/zio/zio/blob/v1.0.0-RC11/core/shared/src/main/scala/zio/syntax/syntax.scala only for `IO[E, A]` and not `ZIO[R, E, A]`?
Historical reasons (from before the introduction of `ZIO`)?

Can we fix those up?

**Comment by ghostdogpr** [comment]
Yeah I think they were just never updated after ZIO environment was introduced. There's a PR for the tuple support: https://github.com/zio/zio/pull/1444
