### ISSUE TITLE
Flaky test in ZStreamSpec

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1449]
```
[info]   Stream.broadcast
[info]     + Values
[info]     + Errors
[info]     + BackPressure
[error]     x Unsubscribe
```
I've seen that `Unsubcribe` test fail in several builds.
Examples:
https://circleci.com/gh/zio/zio/18107
https://circleci.com/gh/zio/zio/18094

cc @mschuwalow @iravid

**Comment by mschuwalow** [comment]
Hm. I'm having trouble reproducing it locally and I don't see any obvious candidates where this could be coming from. I'll mark this one as flaky and continue investigating, ok?

**Comment by adamgfraser** [comment]
Sometimes using `unflaky` in situations like that can be helpful in reproducing failures locally. Sorry if you already did that.

**Comment by mschuwalow** [comment]
The underlying cause is actually #1467
