### ISSUE TITLE
Find another name for ZStream.InputStream

### ISSUE THREAD

**Issue by iravid** [zio/zio#1461]
Too easy to conflate with `java.io.InputStream`.

cc @jdegoes @vasilmkd @mschuwalow and all other naming experts :-)

**Comment by iravid** [comment]
My suggestion: `Pull`

**Comment by vasilmkd** [comment]
I think it must go because we plan on making `java.io.InputStream` one of the main highlights for `StreamEffect`.

**Comment by jdegoes** [comment]
`Pull` is good.

**Comment by vasilmkd** [comment]
Working on this. Can I use this opportunity to also change `ZStream` to be a class?

**Comment by iravid** [comment]
Yes, good idea!
