### ISSUE TITLE
A new encoding for ZSink

### ISSUE THREAD

**Issue by iravid** [zio/zio#1470]
Opening this issue for posterity because I don't think it's the right way forward...

I experimented with the following encoding for `ZSink` today:
```scala
trait ZSink[-R, +E, +A0, -A, +B] { self =>
  def run[R1 <: R, E1 >: E, A1 <: A](pull: ZStream.InputStream[R1, E1, A1]): ZIO[R1, E1, (Chunk[A0], B)]
}
```

First, you may ask yourself why can't we just use a `case class` with `run: InputStream => ZIO`? The problem is the variance. For the sink to be contravariant in `R` and covariant in `E`, we have to use a subtype and supertype in `run`. So the defining function has to be polymorphic.

Moving on, several combinators become very simple. For example:
```scala
  def mapM[R1 <: R, E1 >: E, C](f: B => ZIO[R1, E1, C]): ZSink2[R1, E1, A0, A, C] =
    new ZSink2[R1, E1, A0, A, C] {
      override def run[R2 <: R1, E2 >: E1, A1 <: A](
        pull: ZStream.InputStream[R2, E2, A1]
      ): ZIO[R2, E2, (Chunk[A0], C)] =
        self.run(pull).flatMap {
          case (a0, b) => f(b).map((a0, _))
        }
    }

  def ? : ZSink2[R, Nothing, A0, A, Option[B]] =
    new ZSink2[R, Nothing, A0, A, Option[B]] {
      override def run[R1 <: R, E1, A1 <: A](pull: ZStream.InputStream[R1,E1,A1]): ZIO[R1,E1,(Chunk[A0], Option[B])] =
        self.run(pull).foldM(
          _ => UIO.succeed(Chunk.empty -> None),
          v => UIO.succeed(v._1 -> Some(v._2))
        )
    }

  def chunked: ZSink2[R, E, A0, Chunk[A], B] =
    new ZSink2[R, E, A0, Chunk[A], B] {
      override def run[R1 <: R, E1 >: E, A1 <: Chunk[A]](
        pull: ZStream.InputStream[R1, E1, A1]
      ): ZIO[R1, E1, (Chunk[A0], B)] =
        ZStream.fromInputStream(pull).flatMap(ZStream.fromChunk(_)).process.use(self.run)
    }
```

That's nice. The problem, however, arises when we want to transform `E` and `R`. Here's `mapError`:
```scala
  def mapError[E1](f: E => E1): ZSink2[R, E1, A0, A, B] =
    new ZSink2[R, E1, A0, A, B] {
      override def run[R1 <: R, E2 >: E1](pull: ZStream.InputStream[R1, E2, A]): ZIO[R1, E2, (Chunk[A0], B)] =
        // InputStream[R1, E2, A] - we can't mapError on that
        // self.run(pull) - this doesn't typecheck
        // stuck!
    }
```

That's highly reminiscent of the trouble we had with `ZStream`. In fact, it's the same problem; we made `E` covariant but it's actually used on both sides of a function. So it's really invariant. We can split `E` and `R` to two type parameters, but... 7 type parameters on ZSink... unattractive.

Another problem I realize is that by moving the responsibility of pulling on the stream to the sink, we make our lives hard in combinators that rely on feeding sinks step-by-step- `aggregate` and `aggregateWithin`.

So I conclude this experiment as evidence that we should stay with the current encoding - we just need to get rid of `Step` :-)

cc @jdegoes @vasilmkd

**Comment by jdegoes** [comment]
@iravid 

I think the problem with `E` is just telling us that sinks should _not_ be able to handle errors from streams; it violates inversion of control, anyway.

It can be solved by encoding a sink as `Pull[R, Nothing, A] => ZIO[R, E, (Chunk[A0], B)]`. This means that any code which "runs" a stream with a sink, e.g. `ZStream#run`, will have to catch and handle its own errors; bypassing the sink when an error arises.

I'd argue this makes sense and is easy to do. So I don't find the `E` argument that compelling.

There are some other reasons to consider the encoding:

  - It is obvious how to make resource-safe sinks. We just change to `Pull[R, Nothing, A] => ZManaged[R, E, (Chunk[A0], B)]`. Now sinks can be databases, files, sockets, etc., anything that has resources and needs to be shutdown appropriately. Right now, sinks cannot make any guarantees about resource cleanup. (Note: I think we can add the functionality separately; I don't know exactly what it would look like, but it is probably possible, so we shouldn't consider this argument definitive.)
 - `ZSinkEffect`. The power of `(() => A) => (Chunk[A0], B)` is drool-worthy. We'd still have to find a way to make this work in some maintainable fashion that doesn't require every sink combinator have two implementations. But interesting nonetheless.

The difficulties of `aggregate` and `aggregateWithin` are more compelling. Right now the sinks very clearly need a "driver", and are just state machines; giving them the `Pull` makes them different beasts and could limit some options on the other side. OTOH it may just be the whole pull/push duality, that is, half the combinators become easier, half become harder (we saw something similar with `ZStream`, e.g. `flatMap`).

**Comment by iravid** [comment]
Yes, leaving off error handling is a fair compromise; I don't think it's important for Sink.

However, I'm not convinced. Here's why:
* `aggregate` and `aggregateWithin` of combinators that want to step the sink manually. Moreover, they want to be able to run a partial extract. That will not be possible with the new encoding, because `Pull => ZIO` is an "all or nothing" thing. In fact, I'm not sure how to formulate their behavior at all with this encoding 🧐
* Resource safety for sinks is a good point (in fact the simplicity of how everything is formulated in terms of `Pull => ZIO` is a big advantage). So far we've solved this by constructing the sink inside `Managed` and tying that to the Stream's scope. I think that generally solves the issue? E.g.:

```scala
trait DB {
  def connection: Managed[Throwable, Connection]
}

trait Connection {
  def write(items: List[Item]): Task[Unit]
}

def databaseSink =
  db.connection.map { conn =>
    ZSink.collectAllN[Item](5000)
      .mapM(items => conn.write(items).const(items))
  }

val consumer = Stream(itemsFromFile)
  .transduceManaged(databaseSink) 
```

* Fusing `StreamEffect` and `SinkEffect` - yes, that is really awesome. But what prevents us from attaining that today? We have a specialized implementation of `run` in `StreamEffect`; when it is given a `SinkPure`, it doesn't go through IO. The only difference between that and `(() => A) => (Chunk[A0], B)` is who's driving - the stream or the sink.

**Comment by jdegoes** [comment]
I think I'm mostly convinced now.

Albeit for (2), the main point is that stream "baked in" the safety, so you can have resource combinators on stream directly; but perhaps we can find a way to do that too.

> We have a specialized implementation of run in StreamEffect; when it is given a SinkPure, it doesn't go through IO. 

Awesome. 👍 

I think the only remaining argument is that "pull some elements from a stream and return a value" is easier to teach than state machines, but few people will write them manually, so I think it's not convincing enough to change the representation given the drawbacks.

**Comment by iravid** [comment]
@jdegoes 👍🏻

Ok, so closing this issue for now. If anyone has further comments or insights feel free to reopen.
