### ISSUE TITLE
ZIO Test: Support Generators for Functions

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1472]
I would like to add generators for functions to our property based testing framework so we could have generators of type `Gen[R, A => B]`. I think that, while there are definitely more combinators we could add, this is the last major feature to bring ourselves to parity with existing libraries like ScalaCheck in this area. Right now I'm struggling to do this.

The general approach used by ScalaCheck and QuickCheck is to use the `A` to perturb the random number generator in some way. Typically you have a `Cogen` type that basically represents a "hashing" function that converts an `A` to a `Long` and then you use `^` or some operator to combine that with the existing random number seed to get a new random number generator, and use that along with a `Gen[B]` to generate `B` values. This generally works well but in every implementation I have seen requires running the `Gen[B]`. Basically the problem is we have a `Gen[R, A => Gen[R, B]]` and at least I haven't found a way to convert this to a `Gen[R, A => B]` without unsafely running it. For other testing frameworks this is less of an issue because their effect type is generally a `State` monad that doesn't support other effects, so running it to eliminate the local effect is less of an issue.

@jdegoes Do you have any thoughts on how we might approach this?

**Comment by jdegoes** [comment]
We can convert any total side-effecting method `f : A => B` into a pure function by doing the following:

1. Create a mutable map (a concurrent hash map, probably; at least on JVM, Scala.js has no such thing);
2. Create a memoizing wrapper around `f` that will invoke `f` at most once for a given `A`, storing the result inside the mutable map.

As long as edge conditions are properly handled (i.e. no race conditions), the function, let's call it `f'`, will now be referentially transparent and safe for exposing to user-land code.

So given a `Gen[R, B]`, we should be able to produce a `Gen[R, A => B]`, by building the `A => Gen[R, B]` (which will, for every unique `A`, generate a `B` effectfully); then using `ZIO.runtime` (for `unsafeRun`) and a memo table, we can safely convert the `A => Gen[R, B]` into an effect containing `A => B`.

The main challenge, perhaps, will be the distinction between "discrete" and "continuous" random variables: for the discrete case, the `Gen` stream for `B` will contain all values, deterministically specified; for the continuous case, the stream will contain a single effectful value that samples the state space randomly and non-deterministically. Perhaps you can unify them by doing `.forever` on the stream and then converting it to a `Queue`, which you can then use as a fresh source of `B`'s, one for every unique `A`.

There is also a limitation on this approach: Scala.js does not support blocking, so `A => B` cannot be created from any asynchronous effect; arguably that's a misuse of `Gen` (you shouldn't be doing IO or sleeping or anything to generate a value in a property-based test), but we cannot enforce it at the type-level.

The alternative would be to say we generate functions `A => UIO[B]` only, so when you call them, you are in an effect and have to stay there for the rest of your test. Then you can handle asynchronous generators on both platforms with ease, and never have to unsafe run anything, even "safely". The drawback to this is that such functions are more painful to work with for pure property-based tests, and most property-based tests will be pure, focusing on operations applied to objects in a domain.
