### ISSUE TITLE
ZIO Test: Minor renames to prepare for initial release

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1475]
- `zio.test.Predicate` => `zio.test.Assertion`. _Predicate_ is a technical term, that many developers may not be familiar with, but _assertion_ is more common, and we are already using _assert_. One _asserts_ an _assertion_, so it fits with existing jargon better. Example: `assert(42, Assertion.isEqualTo(42))`.
 - `zio.test.Assertion` => `zio.test.AssertResult`. `Result` is already very common (too common?), whereas `AssertResult` is clearly the result of an assert. 
 - `zio.test.FailureDetails` => `zio.test.TestFailure`. Shorter and ties the failure to a test.

**Comment by adamgfraser** [comment]
Can I take this? I'm already all over this part of the code base with my work on #1438 so will be easy to fold in and avoid merge conflicts.

**Comment by jdegoes** [comment]
@adamgfraser Done! Thank you. 🙏
