### ISSUE TITLE
Add java.nio.Buffer-backed Chunk subtypes

### ISSUE THREAD

**Issue by iravid** [zio/zio#1479]
To support reading buffers without copying them into arrays.

Minimally, support ByteBuffer.
Ideally, support all java.nio.Buffer subtypes. (maybe using specialization?)

**Comment by jdegoes** [comment]
👍 👍 👍

**Comment by pshemass** [comment]
@iravid do you want to have this in core or maybe we could implement this in zio-nio?

**Comment by iravid** [comment]
@pshemass Chunk is sealed, so this would have to be in core.

**Comment by pshemass** [comment]
@iravid what about moving ```Chunk``` to ```zio-nio```?

**Comment by iravid** [comment]
@pshemass that’d force a zio-nio dependency on the zio-streams module, and any library using Chunk (which is all libraries that would use zio-streams). So that’s probably a no-go.

**Comment by quelgar** [comment]
It may make sense to move zio-nio's buffer wrappers into core. I had planned to bring up the chunk ↔︎ buffer relationship at some point, because as things stand today zio-nio usually must copy when using chunks.

**Comment by vasilmkd** [comment]
I'm curious to work on this. Has anyone picked this up yet?

**Comment by vasilmkd** [comment]
Better late than never?
