### ISSUE TITLE
Improve default handling of timeouts in ZIO Test

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1489]
Currently a flaky ZIO Test that doesn't have a timeout will cause the tests to hang forever with no output. The only option is to kill the tests and it won't tell you which test was hanging.

We could:
- add some message that tells you which test is causing the problem e.g. `In Suite "Integers", test "addition" has taken more than X minutes to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics.`

- have a large enough default timeout so that CI jobs don't hang forever? CircleCI has a 10min timeout in case there is no output, but if we add the message above, it may keep it running forever.

cc @adamgfraser @jdegoes

**Comment by jdegoes** [comment]
I think (1) would be awesome, and (2) would be OK at the level of test runners, i.e. some sort of global default (overridable) timeout. Both in combination may be maximally useful.

**Comment by adamgfraser** [comment]
I will work on this.
