### ISSUE TITLE
Add more shorthands for running streams

### ISSUE THREAD

**Issue by iravid** [zio/zio#1491]
```scala
class ZStream[R, E, A] {
  def head: ZIO[R, E, Option[A]]
  def last: ZIO[R, E, Option[A]]
}
```

**Comment by vasilmkd** [comment]
Does this originate from gitter?

**Comment by NeQuissimus** [comment]
Is `head` what is usually referred to as `peek`? Or is it different?
How would you get a `last` from a stream? I don't see how you can know what the last element is...

**Comment by iravid** [comment]
@NeQuissimus 

Not sure what `peek` is :-) `head` should just result in the first element.

`last` can be formulated in terms of a `Pull` that "remembers" (using a `Ref`) the last element that it pulled from upstream, and when upstream fails with `ZIO.fail(None)`, it recovers to that element.

An open question here is whether `head` should run all of the stream's effects, or not. I.e. is it equivalent to `take(1)`? Or does it run through all of the stream and just remembers the first element?

**Comment by alexvanolst** [comment]
I'll be working on this
