### ISSUE TITLE
Add combinator to tick elements of a ZStream at regular interval

### ISSUE THREAD

**Issue by nicolasdasriaux** [zio/zio#1492]
The goal would be to emit the elements of a stream at regular intervals such as in this example.

```scala
val ticks = Stream.repeatEffectWith(IO.succeed(Tick), Schedule.spaced(1.second))
val numbers = Stream.fromIterable(1 to 10)

val tickedNumbers = numbers.zip(ticks).map(_._1)
```

`numbers` could be anything more complex than just emitting numbers for 1 to 10.

It could be having a `ZStream#ticking` combinator

```
trait ZStream[-R, +E, +A] {
  def ticking(initialDelay: Duration, interval: Duration): ZStream[R with Clock, E, A] = ???
}
```

And doing

```
val tickedNumbers = Stream.fromIterable(1 to 10).ticking(3.seconds, 1.second)
```

Or having simpler, more orthogonal methods, such as:

```
object ZStream {
  def tick[A](initialDelay: Duration, interval: Duration, a: A): Stream[Clock, Nothing, A] = ???
}
```

And doing

```scala
val tickedNumbers = Stream.fromIterable(1 to 10).zip(Stream.tick(3.seconds, 1.second, Tick)).map(_._1)
```

Also, having `<&>`, `<&`, `&>` combinators (backed by `zip`combinator for example) might be interesting, but it is questionable in 2 ways:
* `zip` combinator takes 2 queue sizes as additional parameters,
* this might not be the place to discuss those operators in this issue.

It would nevertheless allow to write:

```scala
val tickedNumbers = Stream.fromIterable(1 to 10) <& Stream.tick(3.seconds, 1.second, Tick)
```

**Comment by vasilmkd** [comment]
@nicolasdasriaux Do you need the first element to be delayed as well?

If not, there is currently a shorter implementation than your solution:
`numbers.throttleShape(1, 1.second)(_ => 1)`.

**Comment by nicolasdasriaux** [comment]
Yes, initial delay behavior is desirable.
I'll update initial comment to account for this.

**Comment by iravid** [comment]
@nicolasdasriaux The `<&>` variants make perfect sense as they correspond to the `zipWith` combinator. Could you open a seperate issue for those?

The difference, I think, between the `ticking` combinator you describe here and `throttleShape` is that `ticking` intersperses the elements of  the stream with constant delays, regardless of how fast elements arrive. In other words, `throttleShape` regulates the flow of elements while `ticking` just causes the stream to "dumbly" pull every `duration` seconds.

**Comment by nicolasdasriaux** [comment]
Yes, and it's been upgraded a bit by taking an `initialDelay` and an `interval`. I feel a preference .

**Comment by nicolasdasriaux** [comment]
Added #1496. Using `<*>`, `<*` and `*>` rather than `<&>`, `<&` and `&>`.

**Comment by iravid** [comment]
Let's use this ticket to discuss the variants of scheduling we would like to offer on streams (cc @vasilmkd @regiskuckaertz @jdegoes):
* `ZStream#schedule` - Intersperses the individual elements with with delays and repetitions. Produces a stream that looks like this:
`A1 |--delay determined by A1--| A2 |--delay determined by A2--| ...`
Optionally, every element may also be repeated. This combinator will supersede the existing `ZStream#spaced`.
* `ZStream#repeatWith` - Delays and repeats the entire stream, without affecting the individual elements. Should look like this:
`A1 A2 A3 |--delay--| A1 A2 A3`
* `ZStream#throttleShape` - doesn't work with schedule; regulates the flow of elements. Makes sure that only `n` elements pass in every time period.
`|--A1--|A2----|-A3---|

Are there any others?

**Comment by iravid** [comment]
@nicolasdasriaux For the initial delay, it's probably easiest to prepend a stream; e.g. `ZStream.fromEffect(clock.sleep(500.millis)) ++ yourStream`.

**Comment by jdegoes** [comment]
IMO `throttleShape` should use `Schedule` too. I'd just call it `throttle`. 

Throttling can be viewed as `n` elements per `time period`. Schedule just lets you vary the time period or keep it fixed, as you like. `stream.throttle(100, Schedule.spaced(1.second))` for "classic" throttling.

**Comment by vasilmkd** [comment]
True, @iravid and I wanted to look into using Schedule for throttling but got busy with other things. I have a question though, what about schedules that aren't time based?

**Comment by jdegoes** [comment]
Same thing as `throttle(100, 0.millis)`
