### ISSUE TITLE
Retry requires clock

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1494]
Right now, `retry` and friends all need a `Clock` because of https://github.com/zio/zio/blob/8322b5c08640bec4c09855a5f60871185e093f03/core/shared/src/main/scala/zio/ZIO.scala#L1016

If I want to just do `zio.retry(Schedule.recurs(10000))`, I should not need a clock; my `zio` should just retry immediately for up to 10000 times. No clock needed.

**Comment by ghostdogpr** [comment]
This is a duplicate of this no? https://github.com/zio/zio/issues/1348

**Comment by NeQuissimus** [comment]
Oh yes, you're right!
