### ISSUE TITLE
Add `zipLeft`, `zipRight` methods (as addition to `zip` method) to `ZStream` and equivalent operators

### ISSUE THREAD

**Issue by nicolasdasriaux** [zio/zio#1496]
On `ZStream`:

* Add `crossWith(f: (A, B) => C)`, equivalent to `ls.flatMap(l => rs.map(f)`
* Add `cross` / `<*>`, equivalent to `crossWith((_, _))`
* Add `<*`, equivalent to `(l <*> r).map(_._1)`
* Add `*>`, equivalent to `(l <*> r).map(_._2)`
* Add  `<&>`, an alias for `zip`
* Add `zipLeft` and `<&`, equivalent to `(l <&> r).map(_._1)`
* Add `zipRight` and `&>`, equivalent to `(l <&> r).map(_._2)`

**Comment by iravid** [comment]
For consistency, the `<*>` variants should be based on `flatMap`, while the `<&>` should be based on `zipWith`.

If we were ultra-consistent, `zipWith` itself would have another name. But that's already been decided by other streaming libraries.

Also, I don't think we neeed `&&&`.

I'll update the description.

**Comment by jdegoes** [comment]
@iravid Don't we need `zipWith` and `zipWithPar`, and their variants (left/right)?

**Comment by nicolasdasriaux** [comment]
On `ZStream`:

**Renaming**

* Rename current `zipWith` to `zipParWith` 
* Rename current `zip` to `zipPar`

**`zipParWith` family**

* Add  `<&>`, an alias for `zipPar`
* Add `zipParLeft` and `<&`, equivalent to `(l <&> r).map(_._1)`
* Add `zipParRight` and `&>`, equivalent to `(l <&> r).map(_._2)`

**`zipWith` familly**

* Add `zipWith`, equivalent to `ls.flatMap(l => rs.map((l, _)))`
* Add  `zip` and `<*>` and, equivalent to `l.zipWith(r, (_, _)) 
* Add `zipLeft` and `<*`, equivalent to `(l <*> r).map(_._1)`
* Add `zipRight` and `*>`, equivalent to `(l <*> r).map(_._2)`

**Comment by iravid** [comment]
@jdegoes 

We have `ZStream#zipWith` currently, which runs two streams in parallel. We don't have a named operator for `ls.flatMap(l => rs.map(r => (l, r)))`.

@jdegoes @nicolasdasriaux 

As I mentioned above, renaming the current `zipWith` to imply parallel semantics would be the most consistent. But keep in mind that this is inconsistent with the Scala collections library. Beyond that, most people I've worked with automatically reach for `zipWith` as the operator with the current semantics, and not `zipParWith`.

**Comment by jdegoes** [comment]
@iravid OK, it bothers me a bit but in cases where we only have one variant, we do omit the `Par` prefix. Of course we could flip it in this case, `zipWithSeq` for the other one, although `crossWith` would be better.

**Comment by iravid** [comment]
`cross` is a great idea. I will update the description.

**Comment by ghostdogpr** [comment]
Closed by #1510
