### ISSUE TITLE
Add Semaphore#permits

### ISSUE THREAD

**Issue by amelnikov-mylivn** [zio/zio#1511]
It would be useful to have a method in Semaphore to get the maximum number of permits available. We have Semaphore#available but it returns only free permits. Semaphore#permits or Semaphore#permitsTotal should return capacity of the Semaphore.

P.S. Use case is a read write lock on top of semaphore where you acquire all permits to have an exclusive access.

**Comment by jdegoes** [comment]
Should be done with `TSemaphore`, too, and same name for both.

**Comment by adamgfraser** [comment]
I can take this.

**Comment by vasilmkd** [comment]
Looking at [Semaphore.java](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Semaphore.html), even the Java semaphore does not have a `permitsTotal` equivalent. Not saying that this is not a valid use case, I just think it merits a discussion first.

**Comment by iravid** [comment]
@adamgfraser @amelnikov-mylivn The semantics of Semaphore today allow `release` to increase the available permits beyond the initial permits.

I'm not sure if it's correct to bake this into Semaphore itself.

**Comment by adamgfraser** [comment]
@iravid I thought I saw something weird about that when I was scrolling through the test suite last night! Would your conclusion be (a) the current behavior of `release` is correct and thus the concept of a "maximum" number of permits doesn't make sense or (b)  the current behavior of `release` is wrong and should be adjusted?

I'm definitely not an expert on this but I always thought the concept of a Semaphore was that there were a fixed number of permits and a user could "borrow" them to perform actions so it seems strange that the user could create new permits and could potentially lead to violations of the goal of ensuring that only a certain number of users can access a resource at the same time. But maybe there are other use cases for this that I am not understanding.

**Comment by iravid** [comment]
The only semaphores I've used did not enforce releasing more than taken. They've all (incl. Java's Semaphore) relied on application convention to always release just what was taken. E.g. see this line in the Java Semaphore API:
```
There is no requirement that a thread that releases a permit must have acquired that permit by calling acquire. Correct usage of a semaphore is established by programming convention in the application.
```

By extension, this says that you're responsible for not releasing more than needed.

So, *by convention*, our Semaphore should not bake this in. There's nothing preventing us from deviating though. 

Personally, I have not come by a usecase yet where the initial `n` is not available to my code when acquiring all permits for exclusive access (e.g. https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L900, https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1273, and more in private code).

**Comment by adamgfraser** [comment]
Yeah, I was just looking at the Java and Cats Effect implementations and they both allow `release` to increase the number of permits. Seems strange to me, but agree we need a good reason to deviate from the implementation of an existing structure. I could update my PR to track "maximum number of currently available permits" but not sure how useful that is if you don't have a guarantee someone won't just increase it.

@jdegoes Do you have a point of view on this?

@amelnikov-mylivn Can you shed a little more light on your use case. If you are creating the Semaphore wouldn't you know the initial number of permits?

**Comment by regiskuckaertz** [comment]
> The semantics of Semaphore today allow release to increase the available permits beyond the initial permits.

😨 does that mean this would work:
```scala
semaphore.available.flatMap {
  case 0 => (semaphore.release(1) *> semaphore.acquire(1)).uninterruptible *> doSomething
  case _ => doSomething
}
```

**Comment by amelnikov-mylivn** [comment]
> Can you shed a little more light on your use case. If you are creating the Semaphore wouldn't you know the initial number of permits?

I use it like this right now, passing number of permits alongside with Semaphore. I thought it would be useful to have such method. But also I can encapsulate Semaphore and max number of permits inside my own class (like ReadWriteLock). 

Feel free to close this ticket if you think that this method may break Semaphore contracts.

**Comment by adamgfraser** [comment]
@regiskuckaertz Yes. It is a little scary but it is consistent with Java and Cats Effect. Thinking about it more I think there are two potential directions we can go here depending on our aspirations.

**Option 1: Semaphore as ZIO Implementation of Java Semaphore**
This is what we are doing today. We’re providing similar functionality as exists on Java Semaphore in a ZIO non-clocking / reverentially transparent way. If this is what we are trying to do then I am coming around to the @vasilmkd view that this is something we may not want to support. I think maintaining a concept of “total permits” would require a significant reworking of the internals, because when `release` is called we need to know whether the release is a return of outstanding permits that a process has borrowed or just an increase in permits, which I think would in some way require tracking which processes have acquired permits. This could add significant overhead, as @iravid pointed out the creator of the Semaphore should have access to its initial number of permits, and it is not a feature provided by other Semaphore implementations.

**Option 2: ZIO “Safe” Semaphore**
Just for the sake of discussion, we could think about instead having a “safe” semaphore. `acquire` and `release` are arguably inherently unsafe outside the context of `withPermit` and friends because they represent acquisition and release of resources not in the context of `bracket`. So say we make both `acquire` and `release` private and only expose `withPermit` and friends. Then we can guarantee that actions will never cause the number of permits to exceed the initial number, as well as that the Semaphore will never leak permits. It is worth noting here that in my search of our code base every use of a semaphore in actual production code (not testing or benchmarking) uses a variant of `withPermit` and not `acquire` and `release`. The potential disadvantage of this is that it might limit the ability to build other structures on top of this but it would be completely workable with all our existing code and would be much safer.

**Comment by regiskuckaertz** [comment]
I don't know what the Java people were thinking but it does sound like Tony Hoare the day he thought about `null`: "Well of course they're going to check!" 😄

**Comment by adamgfraser** [comment]
It is worth noting here that Rust's Semaphore only has the equivalent of `withPermits`, so it isn't completely crazy.

https://docs.rs/semaphore/0.4.0/semaphore/struct.Semaphore.html

**Comment by iravid** [comment]
I could think of some (fairly rare) cases where I'd want to acquire and release manually, but those cases can be answered by `withPermitsManaged`, which allows the acquire/release actions to be decomposed by a sufficiently willing user.

**Comment by adamgfraser** [comment]
So do we have a new direction on this? If the power user could still get what they want in some way I think this would be way safer for the average user. What do you think @jdegoes?

**Comment by amelnikov-mylivn** [comment]
Just FYI.
For my own use case (read write lock) - I created my own class which does not break any semaphore semantics. Maybe it will be useful to someone.

```
import zio.{Reservation, Semaphore, UIO, ZIO, ZManaged}

class ReadWriteLock private (semaphore: Semaphore, capacity: Int) {
  def withReadLock[R, E, A](task: ZIO[R, E, A]): ZIO[R, E, A] =
    ZIO.bracket(semaphore.acquire)(_ => semaphore.release)(_ => task)

  def withWriteLock[R, E, A](task: ZIO[R, E, A]): ZIO[R, E, A] =
    ZIO.bracket(semaphore.acquireN(capacity))(_ => semaphore.releaseN(capacity))(_ => task)

  def withReadLockManaged[R, E]: ZManaged[R, E, Unit] =
    ZManaged.reserve(Reservation(semaphore.acquire, _ => semaphore.release))

  def withWriteLockManaged[R, E]: ZManaged[R, E, Unit] =
    ZManaged.reserve(Reservation(semaphore.acquireN(capacity), _ => semaphore.releaseN(capacity)))
}

object ReadWriteLock {
  def make: UIO[ReadWriteLock] = make(Int.MaxValue)
  def make(maxReaders: Int): UIO[ReadWriteLock] =
    if (maxReaders < 1)
      ZIO.die(new IllegalArgumentException("read write lock requires maximum number of readers to be more than 0"))
    else
      Semaphore.make(maxReaders).map(s => new ReadWriteLock(s, maxReaders))
}
```

**Comment by vasilmkd** [comment]
@amelnikov-mylivn The discussion has shifted as to whether dropping the `acquire` and `release` API makes sense. Could you modify your code by making use of the `withPermit` and `withPermitManaged` API instead? Thanks.

**Comment by amelnikov-mylivn** [comment]
> @amelnikov-mylivn The discussion has shifted as to whether dropping the `acquire` and `release` API makes sense. Could you modify your code by making use of the `withPermit` and `withPermitManaged` API instead? Thanks.

Sure

```
import zio.{Semaphore, UIO, ZIO, ZManaged}

class ReadWriteLock private (semaphore: Semaphore, capacity: Int) {
  def withReadLock[R, E, A](task: ZIO[R, E, A]): ZIO[R, E, A] =
    semaphore.withPermit(task)

  def withWriteLock[R, E, A](task: ZIO[R, E, A]): ZIO[R, E, A] =
    semaphore.withPermits(capacity)(task)

  def withReadLockManaged[R, E]: ZManaged[R, E, Unit] =
    semaphore.withPermitManaged

  def withWriteLockManaged[R, E]: ZManaged[R, E, Unit] =
    semaphore.withPermitsManaged(capacity)
}

object ReadWriteLock {
  def make: UIO[ReadWriteLock] = make(Int.MaxValue)
  def make(maxReaders: Int): UIO[ReadWriteLock] =
    if (maxReaders < 1)
      ZIO.die(new IllegalArgumentException("read write lock requires maximum number of readers to be more than 0"))
    else
      Semaphore.make(maxReaders).map(s => new ReadWriteLock(s, maxReaders))
}
```

**Comment by jdegoes** [comment]
I have seen code that uses the behavior of `release` to increase permits, and it's the behavior of the other async effect implementations. I'm not sure if that makes it correct. It could hide bugs in code, compared with a separate method to increase total available permits.

I think `FiberSemaphore` could be useful, which would tie the permits to a particular semaphore, and require release on that; basically it's a more generalized version of `ReentrantLock`, but using a `FiberId` and not a `ThreadId`.

Semaphore is trivial to do as `TRef[Int]` so we don't need to get too fancy; STM makes this so simple that infinite variations can be created. Although we need to document that better.

Perhaps `withPermitsManaged` is enough for the safety issue (making sure to pair acquire with release, making sure not to release things not acquired, etc.).

Any other thoughts?

**Comment by jdegoes** [comment]
^^^ One could make the argument that `acquire(n) === release(-n)` and other nice algebraic properties should hold.

**Comment by vasilmkd** [comment]
Any way to revive this discussion?

**Comment by adamgfraser** [comment]
Yes, I think we should. I just pushed a commit to #1523 to show what it would look like if we took out `acquire` and `release`. Let's discuss how we push this forward there.
