### ISSUE TITLE
ZIO Stream: Compile Against Dotty

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1524]
Currently we only compile ZIO Core against Dotty. This ticket is to get ZIO Stream to compile against Dotty as well. This would involve identifying what issues cause ZIO Stream to fail to compile with Dotty today and resolving those issues. It may also be helpful to look at the settings in `build.sbt` and in particular `dottySettings` to see if those same settings can be applied to ZIO Stream or if other settings are needed.

Getting ZIO Stream to compile against Dotty is a blocking item for other downstream ZIO libraries, including ZIO Test, to do so as well. As the Scala ecosystem transitions from Scala 2 to Scala 3 over the next couple of years there is a big opportunity for ZIO to be nimble and add value for users with its zero dependency approach if we can provide a true cross-platform, cross-version solution.

cc @iravid

**Comment by emanb29** [comment]
Not sure if this is of any use, but I tried to get streams building on `0.19.1-bin-20190904-beba63a-NIGHTLY` and it seems like there's some differences between the Scala 2 and 3 type inference.

Adding an explicit type annotation (`[R1, Nothing, Nothing, Take[E1, B], (Take[E1, C], Loser)]` on the line beginning `left.raceWith` in ZStream.scala) on the aforementioned method actually causes the dotty compiler to crash. Even running the compiler with `-language:Scala2` does not work, causing the same type inference errors.

**Comment by iravid** [comment]
Hey @emanb29, this is helpful! Would be great if you could submit a draft PR. We can then work on  a minimization of the compile failures and submit that to the Dotty team, I'm sure they'd be able to squash that out!

**Comment by adamgfraser** [comment]
@iravid Any update on this? I know we removed the `specialized` annotations on `Chunk` that I think were one of the main issues here. Is it worth trying to compile on Dotty again?

**Comment by iravid** [comment]
Yes!
