### ISSUE TITLE
Remove specialization from Chunk in favor of distinct subtypes of Chunk.Arr

### ISSUE THREAD

**Issue by iravid** [zio/zio#1526]
Today, `Chunk` is specialized on `A`. There are several reasons to reconsider this:
1. It is probably sufficient to specialize just the `Arr` constructor, as only arrays benefit from specialization. 
2. The future of specialization is unclear in Dotty. I only found this presentation from Dmitry Petrashko: https://d-d.me/talks/flatmap2016, but nothing concrete in the Dotty site. Maybe @smarter can shed some light on this?

**Comment by iravid** [comment]
This is necessary for #1524.

**Comment by smarter** [comment]
> The future of specialization is unclear in Dotty. I only found this presentation from Dmitry Petrashko: https://d-d.me/talks/flatmap2016, but nothing concrete in the Dotty site. Maybe @smarter can shed some light on this?

Plans for automatic specialization have been shelved. Right now there's zero specialization support in Dotty, adding method specialization should be easy and useful and will probably happen soon-ish, but class/trait specialization is a much bigger can of worms which we might decide to completely avoid (especially considering that anything we do might get obsoleted by Valhalla).

**Comment by iravid** [comment]
Well, that settles it. Thanks @smarter.
