### ISSUE TITLE
ZIO Test: Add OverLoaded Check Methods for Multiple Generators

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1528]
As suggested by @iravid it would be nice if we could write `check` statements for property based testing with multiple generators. This can already be done today by using `<*>` to tuple the generators but this requires the user to do the tupling and then write a match expression for every property they want to test. We can write some overloaded methods to do this automatically and provide a more pleasant experience for the user.

I will take the ticket.

**Comment by iravid** [comment]
🙏🏻

**Comment by jdegoes** [comment]
I'd suggest we do this in a trait `CheckVariants` that requires only the base cases, then we can inherit that trait in the package object. Just to avoid massive boilerplate clutter in the package object.

**Comment by adamgfraser** [comment]
Good idea.
