### ISSUE TITLE
Fix compilation error DefaultTestRunner

### ISSUE THREAD

**Issue by Vilkina** [zio/zio#1537]
After 'git pull upstream':
<img width="1278" alt="Screen Shot 2019-08-31 at 3 01 27 PM" src="https://user-images.githubusercontent.com/3358827/64063720-bcbbc780-cc00-11e9-95ab-92edeed27b7b.png">

**Comment by ghostdogpr** [comment]
I got that too, `;clean;compile` on the root project fixed it for me.

**Comment by adamgfraser** [comment]
@Vilkina Thanks for the report! If you do `;clean;compile` in SBT it should fix that. I also renamed one of the instanced to lower case `defaultTestRunner` in one of the PRs we merged last night so if you update to the latest version of `master` that should resolve it too. Would you let me know if those suggestions resolve the problem for you?

**Comment by Vilkina** [comment]
@adamgfraser resolved, tnx

**Comment by adamgfraser** [comment]
@Vilkina Awesome! Thanks for reporting!
