### ISSUE TITLE
ZIO Test: Add structure to `Assertion` display

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1542]
Currently, `Assertion` has a `render` method that converts the assertion into a string. This is useful but a string has no structure at all, and with more structure comes greater potential (nicely formatted output, different renderings for different types, etc.).

This ticket is to change the `Assertion` type so that `Assertion#render` becomes a function that returns this more structured representation, while `Assertion#toString` becomes a function from this more structured representation, to the current string representation.

For the more structured representation, we can place an ADT similar to the following inside the `Assertion` companion object:

```scala
final case class Render(name: String, paramsLists: List[List[RenderParam]])
sealed trait RenderParam
object RenderParam {
  final case class Assertion[A](assertion: Assertion[A]) extends RenderArg
  final case class Value(value: Any) extends RenderArg
}
```

The main goals of this ADT are to capture both the name of an assertion, as it will be rendered to strings and as it exists in Scala, as well as the parameters to the assertion combinator (there may be multiple parameter lists, due to curried syntax!), both assertion parameters, and catch-all value parameters (later this could be improved, but for now, "catch all" is fine).

Then the various `Assertion.assertion*` methods can be modified, and the combinators adjusted, to produce the structured form, using helpers to simplify construction. 

We currently define assertions like this:

```scala
Assertion.assertion("hasField(\"" + name + "\"" + s", _.${name}, ${assertion})") { ... }
```

After the change, it will be something like:

```scala
Assertion.assertion("hasField")(param(name), param(assertion)) { ... }
```

The latter representation captures a LOT more structure, including enough for pretty-printing the output (wrapping / tree-like rendering), and treating string values specially (quoting them so they render as valid Scala strings; since currently `String#toString` will provide a rendering that is not valid Scala code).

**Comment by adamgfraser** [comment]
I can take this.

**Comment by szimano** [comment]
Hey guys, I think my issue might be connected to this Issue.

I am trying to make an integration of github.com/softwaremill/diffx library into ZIO Test - the library purpose is to pretty print diffs between two given case classes

ie.

`
sealed trait Parent
  case class Bar(s: String, i: Int) extends Parent
  case class Foo(bar: Bar, b: List[Int], parent: Option[Parent]) extends Parent

  val right: Foo = Foo(
    Bar("asdf", 5),
    List(123, 1234),
    Some(Bar("asdf", 5))
  )
  val left: Foo = Foo(
    Bar("asdf", 66),
    List(1234),
    Some(right)
  )
`

the diff printed is

![image](https://user-images.githubusercontent.com/289588/64256003-6c06e000-cf1a-11e9-82fe-bb0204f02d28.png)

(colours and stuff :) )

Now I see that what is reported back to the user is the passed `renderer` String, but this is given upfront, before the actual evaluation of assertion, so cannot really be generated basing on the actual comparison.

Is there any way to provide something like your own reporter that would be generated during evaluation? Thanks for the pointers!
