### ISSUE TITLE
Reduce build times and costs

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1545]
Our overall CI build times have become pretty large, and with the sustained activity on ZIO from many contributors (which is great! 🎉), the costs are getting important too.

Each individual build is not that long, but we have 12 combinations of Scala versions (2.11, 2.12, 2.13), JDK (8, 11) and platforms (JVM, JS). We expect to add Dotty (#1022) and Scala Native (#639) soon, which is going to increase the number of combinations exponentially. The question is: do we really need all combinations?

I had a look at a number of open-source Scala projects and most of them only build and test with jdk8. In the rare cases where they do it with jdk11, they only do for a single version (usually Scala 2.12 with JVM). Examples [here](https://travis-ci.org/scalaz/scalaz) and [there](https://travis-ci.org/http4s/http4s).

How about testing JDK11 only with Scala 2.12 + JVM? We would go from:
```
- test_211_jdk8_jvm:
- test_212_jdk8_jvm:
- test_213_jdk8_jvm:
- test_211_jdk11_jvm:
- test_212_jdk11_jvm:
- test_213_jdk11_jvm:
- test_211_jdk8_js:
- test_212_jdk8_js:
- test_213_jdk8_js:
- test_211_jdk11_js:
- test_212_jdk11_js:
- test_213_jdk11_js:
```
to
```
- test_211_jdk8_jvm:
- test_212_jdk8_jvm:
- test_213_jdk8_jvm:
- test_212_jdk11_jvm:
- test_211_jdk8_js:
- test_212_jdk8_js:
- test_213_jdk8_js:
```

Any other ideas?

**Comment by softinio** [comment]
We could just run against jdk8 as a routine and build against jdk11 on a schedule and on master only though we risk a broken build? 

Jdk11 daily or weekly ?

**Comment by ioleo** [comment]
@ghostdogpr How about switching the build system from SBT to [bazel](https://bazel.build/)? With low-granurality targets (eg. 1 per package) bazel would really shine here and recompile/retest only whats absolutely necessary.

**Comment by ghostdogpr** [comment]
@ioleo I would rather stick to something widespread so that most people can contribute easily. With sbt at least everyone knows how to get the project running. It might be better (I have no idea), but would require some learning and configuring from everyone. I prefer to spend this time building cool ZIO things! 😄

**Comment by NeQuissimus** [comment]
I'd support having JDK11 with only a "sanity-build". How many parallel workers do we currently have?

**Comment by ghostdogpr** [comment]
We have up to 43x parallelism but the problem is more the total build-minutes we spend by executing all those.
