### ISSUE TITLE
Stop publishing core-tests and streams-tests

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1561]
We want to stop publishing our tests, but we can't because they are currently used by the interop libraries.

## Step 1:
Stop depending on core-tests in interop libraries. If it was actually used, replace it with ZIO Test.
- [x] [Interop Twitter](https://github.com/zio/interop-twitter)
- [x] [Interop Scalaz](https://github.com/zio/interop-scalaz)
- [x] [Interop Monix](https://github.com/zio/interop-monix)
- [x] [Interop Java](https://github.com/zio/interop-java)
- [x] [Interop Guava](https://github.com/zio/interop-guava)

(cats and reactive-streams are already not using it)

Example of using ZIO Test here: https://zio.dev/docs/usecases/usecases_testing

## Step 2:
Stop publishing core-tests and streams-tests

**Comment by vilu** [comment]
I would like to tackle this one.

**Comment by ghostdogpr** [comment]
@vilu Thanks! Let us know if you need any help.

**Comment by ghostdogpr** [comment]
@vilu which interop are you tackling first? I ask in case other contributors want to share the work.

**Comment by vilu** [comment]
I work from the top to the bottom. I'll post a PR to the Twitter one this weekend to get a confirmation that I'm addressing it in the right way.

I can keep updating this PR when I pick a new one. So, just to re-iterate I'm currently working on the Twitter one. Any other one would be ok for anyone to pick up without us stepping on each others toes.

**Comment by ghostdogpr** [comment]
@vilu sounds good 👌

**Comment by mijicd** [comment]
@vilu just link this issue in your PRs and feel free to reach out if you need any help.

**Comment by vilu** [comment]
I actually ran into some issues: https://github.com/zio/interop-twitter/pull/29

**Comment by ghostdogpr** [comment]
Working on interop-java

**Comment by ghostdogpr** [comment]
Monix and Java done

**Comment by sideeffffect** [comment]
will do guava

**Comment by sideeffffect** [comment]
guava done https://github.com/zio/interop-guava/pull/3

**Comment by ghostdogpr** [comment]
Step 1 completed
