### ISSUE TITLE
ZIO Test: Type Inference Issue with Assertion#equalTo

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1562]
@regiskuckaertz raises the good point that code like the following does not compile:

```scala
assert(List(1, 2, 3).filter(_ => false), equalTo(List.empty))
// found: Assertion[List[Nothing]]
// required: Assertion[List[Int]]
```

Where:

```scala
class Assertion[-A]
final def assert[A](value: => A, assertion: Assertion[A])
final def equalTo[A](expected: A): Assertion[A]
```

It does work with an explicit type annotation on `assert`:

```scala
assert[List[Int]](List(1, 2, 3).filter(_ => false), equalTo(List.empty))
```

The problem is that the compiler is not zeroing in on the expected type being `List[Int]` early enough and so is not widening `List.empty` from `List[Nothing]` to `List[Int]`. We could potentially address this by adding a curried version of `assert`, perhaps:

```scala
final def assert_[A](value: => A)(assertion: Assertion[A])
```

However, this fractures our API and this method loses all type safety because the contravariant assertion type will get widened arbitrarily, so for example this would compile:

```scala
assert_("Adam")(equalTo(1))
```

If we were going to do that we almost might as well make `equalTo` return an `Assertion[Any]`.

Right now my inclination is that adding the explicit type parameter is the best option but that isn't entirely satisfactory so putting it out there to see if anyone else has better ideas.

**Comment by regiskuckaertz** [comment]
I'm happy with the signature and don't think we should curry, though I was a bit surprised by the behaviour. This would not compile:
```scala
Some(5).fold(Nil)(_ => List(1))
```
even with the currying. But this would
```
Some(5).fold(List(1))(_ => Nil)
```
I thought `assert` would behave similarly, i.e. the second parameter can be a subtype of the first. That said, adding the type signature is really not asking too much 😅

**Comment by ghostdogpr** [comment]
Instead of the type parameter on `assert`, you can add it to `List.empty` so it's a bit shorter:
```
assert(List(1, 2, 3).filter(_ => false), equalTo(List.empty[Int]))
```
That's usually how I deal with `fold` and friends.
I also don't think we should curry.

**Comment by adamgfraser** [comment]
@jdegoes Do you have any other ideas here? Otherwise I am going to close.

**Comment by regiskuckaertz** [comment]
I have several other example in the streams tests. For simple types like `List[Int]` it's ok, but for anything else like tuples of eithers of options etc, it gets quickly hard to read.

**Comment by adamgfraser** [comment]
Okay, that is good feedback. Then I will definitely not close and will think more about this.

**Comment by jdegoes** [comment]
@adamgfraser 

How about this:

```scala
class Assertion[-A]

final def assert[A](value: => A, assertion: Assertion[A]): Unit = ???
final def equalTo[A](expected: Any): Assertion[A] = ???

assert(List(1, 2, 3).filter(_ => false), equalTo(List.empty))
```

**Comment by jdegoes** [comment]
The other thing that can be done with `equalTo`:

```scala
final def equalTo(expected: AnyRef): Assertion[AnyRef] = ???
```

This is actually legitimate given that `equals` / `hashCode` is defined on `AnyRef`, and that is how `equalTo` is implemented.

**Comment by jdegoes** [comment]
It's very important to fix type inference issues like these.

**Comment by adamgfraser** [comment]
I'm on it. My concern had been that these solutions are less type safe in that you could call `equalTo` with a right hand side that could not possibly be equal to the left hand side. But as you say that is inherent in the definition of `equals` and the worst case is just that you write a test that doesn't make sense and so the test fails versus the current situation which causes pain for all users. I will push a fix for this today.
