### ISSUE TITLE
ZIO Test: Explore Alternatives for Bringing Back Old MockRandom Functionality

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1566]
Originally `MockRandom` had a very simple implementation along the lines of `MockConsole` where you would “feed” data into `MockRandom` and then when you called methods that relied on `Random` you would just get back the data you fed in. As we built out ZIO Test we upgraded `MockRandom` to a full blown purely functional pseudo-random number generator which is much more powerful but actually doesn’t support the very simple use case of “feed a few numbers, verify that your program returns the expected result” as well.

I see a few options here:

1. **Add an additional MockRandom implementation** - Maybe for namespacing we create package `mockVariants` in `mock` and then `SimpleMockRandom` within that. It provides a solution and doesn’t require changing anything else but I worry a bit about providing different ways of doing similar things and it also doesn’t integrate as nicely with `MockEnvironment` since the user has to provide this separately and make sure they don’t override the normal `MockRandom` for applications like property based testing.
2. **Make Current MockRandom replace Random.Live** - `Random` is unique among the core ZIO environment types in that it doesn’t have to involve any interaction with the outside world. To print to the live console we actually have to access some system resource that exists outside ZIO. But `scala.util.Random` is just a pseudo-random number generator itself, just unfortunately one that mutates internal state. Our existing `MockRandom` implementation already generates the same random outputs as `scala.util.Random` for any given seed, and we could make sure it was seeded with the system time initially in the same way when the environment is created. This would be the first time our environmental effects didn’t just delegate to standard library methods, so it may be a hard no. But if we did this we could then make `MockRandom` implement the old behavior. One disadvantage would be all our property based testing methods would have to reference `Live` which would be a pain, but maybe we could use a type alias to get around it.
3. **Do Nothing** - `MockRandom` is deterministic so you could always set the seed to a certain value, see what outputs you get for that seed (you can do in REPL with `scala.util.Random` since it provides same outputs) and then check against those. But that is definitely not as convenient as it used to be.

There may be variants of these or other alternatives I’m not thinking of so would appreciate any other ideas or thoughts on how important the old `MockRandom` use case is for supporting. As a user would you expect the default `MockRandom` to give you the “feed data” behavior or the “purely functional RNG” behavior?

**Comment by ghostdogpr** [comment]
As discussed in Gitter I think the default `MockRandom` provided in `MockEnvironment` should provide easy ways for ZIO Test users to control the output, just like `MockClock` does for time. As I was implementing tests at work, I was surprised it didn’t allow that and I had to write my own. So I prefer your option 2. 

I’d be curious to know what others are thinking, maybe there are other use cases.

**Comment by ghostdogpr** [comment]
@jdegoes what do you think about this one?

**Comment by jdegoes** [comment]
@adamgfraser @ghostdogpr How about some hybrid:

You can "push" fake randoms, and when the buffer is empty, it goes onto use the pseudo-random-number-generator.

So by default you don't have to push anything, if you don't want. Would that be reasonable?

**Comment by adamgfraser** [comment]
@jdegoes Yes. I thought about that and was a little concerned about it from a separation of concerns perspective, but it may be better for us to get a little dirtier on our end to make things better for our users.

**Comment by ghostdogpr** [comment]
@jdegoes @adamgfraser 👍

**Comment by jdegoes** [comment]
@adamgfraser 

> Make Current MockRandom replace Random.Live

This is an interesting idea. What do you think are the pros / cons?

> Yes. I thought about that and was a little concerned about it from a separation of concerns perspective, but it may be better for us to get a little dirtier on our end to make things better for our users.

I suppose we have to ask: what is the best default if the user doesn't feed `MockRandom` with any data or when it runs out (with too little)? Just a constant? Wrap around the test data? Or switch over into PRNG mode? All could be useful, I can imagine many tests that just _happen_ to use randomness and they don't necessarily care about which randoms they get.

**Comment by adamgfraser** [comment]
Pros:
- We could implement methods on `Random` including `setSeed` and `perturb` that could be useful for some of our users. I had thought this might be important for us to be able to support randomly generated functions but it seems like that is not necessary.
- We could maintain a cleaner interface where `Random` does pseudorandom number generation and `MockRandom` is fed data versus having to mix the two interfaces.

Cons:
- Methods in ZIO Test that relied on random number generation would have to rely on `Live[Random]` instead of `Random`. I think we could limit this to the `check` variants.
- Added complexity in explaining why all the other ZIO environment types delegate to Scala standard library methods but this one does not.

We would also have to compare performance. I recall when I was diagnosing some of the issues with long test times on ScalaJS that `Random` and `MockRandom` seemed roughly comparable but we would have to do that more scientifically.
