### ISSUE TITLE
Rename ZIO.aggregateWithin to ZIO.aggregateWithinEither and add a simpler aggregateWithin

### ISSUE THREAD

**Issue by iravid** [zio/zio#1567]
The current version of `aggregateWithin` emits the schedule's output into the stream, resulting in a stream of `Either[ScheduleOutput, Batch]`. This variant should be named `aggrgateWithinEither`, and `ZStream#aggregateWithin` should be defined as:
```scala
def aggregateWithin = aggregateWithinEither.collect {
  case Right(v) => v
}
```

**Comment by saeltz** [comment]
@iravid , I'll give this one a try.

**Comment by iravid** [comment]
Thanks @saeltz!

**Comment by saeltz** [comment]
@iravid , does this look good?
https://github.com/zio/zio/compare/master...saeltz:master

**Comment by iravid** [comment]
@saeltz thanks for picking this up! Could you open a PR?
