### ISSUE TITLE
ZIO Test: Improve Reporting of Property Based Testing Result

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1585]
This ticket is to improve reporting of property based testing results. A completed ticket will make two or possibly three improvements to existing test reporting:

- [ ] Report the shrunk random variables that caused the test to fail in addition to the failing test result. This will involve modifying the `checkStream` method in `CheckVariants.scala` so instead of just mapping the test over the random sample we keep a tuple of the sample and the test result and shrink those.
- [ ] Show the number of tests that passed before the failing test. This can also be done within the `checkStream` function, probably by using something like `zipWithIndex`.

A nice to have would be:
- [ ] Show the random seed for failing property based tests. This will be a little tricky because property based tests don't necessarily need to use a "random" variable (all the check methods are generic in `R` and could be done with an exhaustive sample). So we would need a way to at compile time identify which ones do and then access the `Random` to get the seed.

**Comment by ghostdogpr** [comment]
Working on this
