### ISSUE TITLE
Switch to bundle publishing

### ISSUE THREAD

**Issue by pshirshov** [zio/zio#1589]
Right now we publish all our projects with `sbt-sonatype` plugin. 

After most recent update of the plugin it become possible to publish faster and with lot higher correctness. More details here: https://github.com/xerial/sbt-sonatype/issues/89

We should switch to the shiny new `sonatypeBundleUpload` command

Supersedes: #1442 

The essense:

```scala
publishTo in ThisBuild := (if (!isSnapshot.value) {
  sonatypePublishToBundle.value
} else {
  Some(Opts.resolver.sonatypeSnapshots)
})
```

and then:

```bash
sbt +clean +sonatypeBundleClean +publishSigned +sonatypeBundleRelease
```

**Comment by jdegoes** [comment]
<xerial/sbt-sonatype#89>
