### ISSUE TITLE
ZIO Test: testM question

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#1593]
Why is `testM` requiring the error type to be `Nothing`?
I may be missing something but when I write a test like 

```scala
for {
  _ <- startSomething // ZIO[Any, Throwable, Unit]
  res <- readSomething // ZIO[Any, Nothing, String]
} yield assert(res, equalTo("bla"))
```

it introduces a bit of overhead to get rid of that `Throwable`.

Can we have something like 

```scala
  final def testM[R, L, T, E](label: L)(assertion: ZIO[R, E, TestResult]): ZSpec[R, Nothing, L, Unit] =
    Spec.test(
      label,
      assertion.either.flatMap { result =>
        result match {
          case Right(r) => r.failures match {
            case None           => ZIO.succeed(TestSuccess.Succeeded(AssertResult.unit))
            case Some(failures) => ZIO.fail(TestFailure.Assertion(failures))
          }
          case Left(err) => ZIO.fail(TestFailure.Assertion(null)) // I really don't know what to put here?
        }
      }
    )
```

Or is there an intended way of doing this without adding too much overhead to tests?

**Comment by adamgfraser** [comment]
Yes, I think we should be able to do something here. We have a `TestFailure.Runtime` subtype to cover that. I think our thinking had been that the default behavior would be people would write tests that didn't have expected failures and the `E` type parameter was more flexibility for alternative implementations in the future, but I think we can generalize relatively easily. Let me work something up.

**Comment by neko-kai** [comment]
@adamgfraser 
> I think our thinking had been that the default behavior would be people would write tests that didn't have expected failures

Well, we use wildcard `_` as error type in [izumi](https://github.com/7mind/izumi/blob/baea35e54dd482e54cd2d075e774cfd26806897a/distage/distage-testkit/src/main/scala/izumi/distage/testkit/services/DISyntaxBIOBase.scala#L15) so that code with arbitrary error types can be mixed within a test and just fail the test if necessary. But we predominantly write integration tests and assertions, not equalities.
