### ISSUE TITLE
ZIO Test: Implement TestRuntime and TestApp

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1600]
This ticket is to implement `TestRuntime` and `TestApp` within package `test.mock` within ZIO Test.

Currently users who want to try the functionality that `MockEnvironment` offers for testing effects like `Console` have to either write a ZIO Test test suite or provide the mock environment themselves using methods like `ZIO.provide`. We can make it even easier for people to use this functionality by creating a `TestRuntime` analogous to the `DefaultRuntime` in `zio/core` except that the environment is the `MockEnvironment`. Then we can create a `TestApp` like the existing `App` trait that extends the `TestRuntime`. That way a user will be able to extend `App`, implement their program in the `run` method, and use the mocking capabilities without any further effort.

**Comment by Vilkina** [comment]
I can try

**Comment by adamgfraser** [comment]
Going to close this as I think it is addressed by the existing tools we have built out for controlling use the live versus test environment.
