### ISSUE TITLE
Rename `sync` to `effect` in ZIOSyntax.LazyCreationSyntax

### ISSUE THREAD

**Issue by markosski** [zio/zio#1606]
I'm new to the code base but it looks like some left-over from refactoring?

https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/syntax/ZIOSyntax.scala#L30

rename 

`def sync[R]: ZIO[R, Throwable, A]   = ZIO.effect(a())`

to 

`def effect[R]: ZIO[R, Throwable, A]   = ZIO.effect(a())`

**Comment by ghostdogpr** [comment]
That’s right! We should probably have both and deprecate `sync` for a smooth transition. 

Would you like to make a PR for this?

**Comment by markosski** [comment]
Yes, happy to contribute.

**Comment by ghostdogpr** [comment]
Closed by #1618
