### ISSUE TITLE
sbt output is missing in CircleCI

### ISSUE THREAD

**Issue by LGLO** [zio/zio#1622]
In many cases there is no output from `sbt` command in CircleCI.
![Screenshot from 2019-09-08 14-58-23](https://user-images.githubusercontent.com/2694353/64488521-2cf1cb00-d249-11e9-8390-eceb3b3b74f6.png)

I suspect super shell in sbt 1.3.0

**Comment by LGLO** [comment]
This looks like CircleCI issue indeed.
For example I have opened https://circleci.com/gh/zio/zio/22666 in two tabs and one time I can see output and other time not.
![Screenshot from 2019-09-08 15-39-19](https://user-images.githubusercontent.com/2694353/64489071-2ebe8d00-d24f-11e9-9722-a7b0dbce09c4.png)
![Screenshot from 2019-09-08 15-39-36](https://user-images.githubusercontent.com/2694353/64489072-2f572380-d24f-11e9-9e5e-6ba16d769f8a.png)

**Comment by ghostdogpr** [comment]
Found a couple tweets indicating the issue in on CircleCI side:
https://twitter.com/y_ury_/status/1170711468922347521
https://twitter.com/cobot_1/status/1170670922778304512

**Comment by softinio** [comment]
Yeah I verified over weekend that this totally is a circleci glitch. As we have a paid account will raise a support ticket with them about. Glad we have it documented here.

**Comment by ghostdogpr** [comment]
Seems like they fixed it: https://status.circleci.com/incidents/qfhr81gjzkb0
Closing this ticket
