### ISSUE TITLE
Proposal: CancelableFuture

### ISSUE THREAD

**Issue by fsvehla** [zio/zio#1627]
Proposal: Adding a `CancelableFuture`, which extends `Future` with a `cancel` operation that triggers interruption of the underlying `IO`.

### Use case

> We've started introducing zio at the edges of our system. This results in having multiple `unsafeRunToFutures` running in different actors. I'm looking for advice on terminating these from outside of zio (e.g. when the parent actor is shutting down).

(reported by @dpennell)

### API

1. Introduce a `CancelableFuture`

```scala
trait CancelableFuture[A] extends scala.concurrent.Future {
  def cancel(): Unit
}
```

or (see https://github.com/zio/zio/issues/1627#issuecomment-529606773)

---

```scala
trait CancelableFuture[E, A] extends scala.concurrent.Future {
  def cancel: `UIO[Exit[E, A]]`
}
```

2. Return `CancelableFuture` in `ZIO` and the RTS

```diff
-- final def toFuture(implicit ev2: E <:< Throwable): ZIO[R, Nothing, scala.concurrent.Future[A]]
++ final def toFuture(implicit ev2: E <:< Throwable): ZIO[R, Nothing, zio.CancelableFutureA]]
```

### Implementation

* AFAICT all `Future` methods must be reimplemented, most will most likely simply delegate
* Interop code with Cats-Effect will most likely have code of very similar shape (for `ConcurrentEffect` `runCancelable`)

**Comment by fsvehla** [comment]
I’d like to work on this.

**Comment by iravid** [comment]
I would suggest, alternatively, that *only* `unsafeRunToFuture` would return that trait. The trait could essentially be a wrapper over the `FiberContext` itself.

**Comment by iravid** [comment]
Oh, sorry, I can see why this would be useful in `toFuture`. Returning `CancelableFuture` there makes sense!

**Comment by fsvehla** [comment]
About naming - is it a `Cancelable`, `Cancellable`, `Interruptable` or `Interruptible` `Future`? :D

**Comment by fsvehla** [comment]
I propose that `cancel`, instead of returning `Unit` should return `UIO[Exit[E, A]]` and that we including the `IO`’s error channel as a type parameter: `CancelableFuture[E, A] extends Future[A]`

The obvious downside is that the a `Runtime` must be around to cancel the action, but it will be around anyway in places were we need a Future… @dpennell would this make your use case harder?

**Comment by dpennell** [comment]
@fsvehla I'm using a shared, long-lived Runtime, so this should be fine.

**Comment by dpennell** [comment]
@fsvehla Thanks for taking this on!

**Comment by vasilmkd** [comment]
> About naming - is it a `Cancelable`, `Cancellable`, `Interruptable` or `Interruptible` `Future`? :D

It's `Cancelable` and `Interruptible`.
