### ISSUE TITLE
ZIO Test: Benchmark and Explore Optimization Opportunities for Random Generators

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1630]
As more people start using property based testing in ZIO Test we should benchmark how long it takes to generate common random data types with ZIO Test versus other property based testing frameworks and natively using `scala.util.Random`. Once we understand where we are, we can explore opportunities for optimization. For example, right now every random number we generate is wrapped in a `ZIO` which is itself modifying the `Ref` that underlies `MockRandom`. We could potentially generate data in batches in certain cases (e.g. if we know we need a list with 100 integers generate all of them in one effect). This would be somewhat less composition but could be worth it if we got a significant speedup.

A completed ticket would:

- [ ] Create a new `GenBenchmarks.scala` file in the `benchmarks` project set up the same way as existing benchmarks.
- [ ] Define and benchmark a few common random variable generation tasks (e.g. generate a random double, generate a list of random integers of a certain size, generate a random string of a certain size) using both the combinators and defined in ZIO Test and native methods on `sclala.util.Random`.
- [ ] Benchmark the same tasks using other Scala property based testing frameworks in Scala, in particular ScalaCheck and Hedgehog.

**Comment by neko-kai** [comment]
> Benchmark the same tasks using other Scala property based testing frameworks in Scala, in particular ScalaCheck and Hedgehog.

Also [nyaya](https://github.com/japgolly/nyaya/) which purports to be way faster than scalacheck :+1:

**Comment by jaliss** [comment]
I'd like to take this.

**Comment by adamgfraser** [comment]
Awesome!

**Comment by jaliss** [comment]
@adamgfraser I did not get to work on this and I'll be out for a couple of weeks.  If someone else wants to take this go ahead otherwise I'll work on it once I am back.

**Comment by adamgfraser** [comment]
@jaliss No worries! Thanks for the heads up. I really appreciate it.

**Comment by pk044** [comment]
mind if I take this one? sounds like a good opportunity to learn something useful :)

**Comment by adamgfraser** [comment]
Please do!
