### ISSUE TITLE
Proposal Cause.Stackless or Cause.Meta

### ISSUE THREAD

**Issue by ioleo** [zio/zio#1646]
Following the discussion on #1610 in some cases we would like to:
* ignore traces in cause (both execution and stack)

```scala
final case class Stackless[E](cause: Cause[E]) extends Cause[E]
```

* we'd like to avoid adding "special cases" for each new idea/feature that arises
* thence the proposal to add ability to enrich the cause structure with arbitrary metadata

```scala
final case class Meta[A, E](cause: Cause[E], meta: A) extends Cause[E]
```

**Comment by adamgfraser** [comment]
Closed by #1706.
