### ISSUE TITLE
Migrate all tests to ZIO Test

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1647]
Here's the list of tests to migrate to ZIO Test. Look at `ZQueueSpec` or `ZManagedSpec` for examples.
If you want to contribute this ticket, please comment to say which spec you're tackling.

- [x] CauseSpec
- [x] FiberLocalSpec
- [x] FiberRefSpec
- [x] FiberSpec
- [x] FunctionIOSpec
- [x] PromiseSpec
- [x] RefMSpec
- [x] RefSpec
- [x] ZIOSpec
- [x] ZManagedSpec
- [x] ZQueueSpec
- [x] ZScheduleSpec
- [x] DurationSpec
- [x] ExecutorSpec
- [x] StackBoolSpec
- [x] STMSpec
- [x] PlatformSpec
- [x] RTSSpec
- [x] SemaphoreSpec
- [x] SerializableSpec
- [x] ZIOSpecJvm
- [x] BlockingSpec
- [x] MutableConcurrentQueueSpec
- [x] OneShotSpec
- [x] TArraySpec
- [x] SystemSpec
- [x] js/MutableConcurrentQueueSpec
- [x] js/OneShotSpec
- [x] jvm/2.12/StacktracesSpec

When all are done, we can remove the dependency to specs2 as well as some common code.

**Comment by LGLO** [comment]
I'll try with STMSpec and merge StmIssue1587Spec to it.

**Comment by zezutom** [comment]
I'd like to take Duration and Serializable specs.

**Comment by adamgfraser** [comment]
I'm doing CauseSpec as part of #1706.

**Comment by lemastero** [comment]
I am attacking `FiberSpec`

**Comment by kapke** [comment]
I'll try to migrate JS specific ones.

**Comment by wojtek-tg** [comment]
I'd like to take a stab at `DurationSpec`

**Comment by XLPI** [comment]
Ok, I'll try pick easy one. Which one can you advice? @ghostdogpr

**Comment by XLPI** [comment]
I picked ExecutorSpec

**Comment by kapke** [comment]
`MutableConcurrentQueueSpec`and `OneShotSpec` are migrated too.

**Comment by kapke** [comment]
I'm starting migration for `FunctionIOSpec` now

**Comment by adamgfraser** [comment]
You're on fire! 🔥

**Comment by mijicd** [comment]
I'll start with `RTSSpec` now.

**Comment by smart-ass** [comment]
I'm taking `StackBoolSpec`

**Comment by ghostdogpr** [comment]
@mijicd brave! 💪

**Comment by dzajkowski** [comment]
will tackle `SemaphoreSpec`

**Comment by smart-ass** [comment]
Taking `ZScheduleSpec`

**Comment by zezutom** [comment]
I take FiberLocalSpec

**Comment by chlin501** [comment]
I would like to take `ZIOSpecJvm`

**Comment by LGLO** [comment]
@chlin501 :muscle: Good luck, it's big one!
There is ZIOSpec.scala already with few test.
I'll sync with you because I've already migrated `foreachPar_` and `foreachParN` when helping @hanny24 with reimplementing these.

**Comment by XLPI** [comment]
I take PlatformSpec

**Comment by dkarlinsky** [comment]
I'll take `SerializableSpec`

**Comment by dzajkowski** [comment]
@lemastero I didn't notice that you already took `FiberSpec`. sorry!

**Comment by XLPI** [comment]
jvm/2.12/StacktracesSpec  - picked

**Comment by chlin501** [comment]
@LGLO A few question, are there any similar migrated ZIO Test cases that also extends  `GenIO` or similar that can be referred to? And which ZIO test cases use `foreachPar_` and `foreachParN` that can be checked that I can use it as a start point? 

Thanks for your help!

**Comment by LGLO** [comment]
@chlin501
These test are not in master yet, however I'll open PR just for that 5 cases - tomorrow.
Can you see it here: https://github.com/LGLO/scalaz-zio/blob/issue-1499-tests/core-tests/shared/src/test/scala/zio/ZIOParCombinatorsSpec.scala ? Note: ZIOSpec is place for ZIO combinators.

Regarding `GenIO`, I didn't migrate any of them, but can you please take a look at `ZManagedSpec`? There is use of `zio.test.Gen`

**Comment by ghostdogpr** [comment]
Only 4 left! Amazing work everyone.

**Comment by zezutom** [comment]
I take ZIOSpecJvm

**Comment by LGLO** [comment]
@zezutom as far as I know @chlin501 declared for it, can't see it here, maybe it was on gitter.
Could you please get in touch and agree who's doing that?

**Comment by zezutom** [comment]
will do, thanks

**Comment by chlin501** [comment]
> will do, thanks

Feel free to take it. I am fine with that.

**Comment by zezutom** [comment]
@chlin501 Thank you, I'll try to do it at the end of this week. It's fine if you change your mind and take it by then.

**Comment by sideeffffect** [comment]
Probably there are [`BaseCrossPlatformSpec`](https://github.com/zio/zio/blob/master/core-tests/shared/src/test/scala/zio/BaseCrossPlatformSpec.scala) and [`TestRuntime`](https://github.com/zio/zio/blob/master/core-tests/jvm/src/test/scala/zio/TestRuntime.scala) missing on that list

**Comment by adamgfraser** [comment]
Those both just contain helper methods so once the last two test suites are migrated we can delete those. But you're right we would also want to move those to a platform specific directory.

**Comment by adamgfraser** [comment]
@zezutom Just checking in on migrating `ZIOSpecJVM`. Are you still working on this? Do you need any help to finish it?

**Comment by dkarlinsky** [comment]
Working on `ZIOSpecJvm`

**Comment by zezutom** [comment]
Apologies for my late response @adamgfraser , I did not start work on it. Thanks @dkarlinsky for taking over.

**Comment by serragnoli** [comment]
I'll work on `jvm/2.12/StacktracesSpec`

**Comment by adamgfraser** [comment]
Thanks to everyone who contributed to getting these tests migrated, included @zezutom, @dzajkowski, @kapke, @ghostdogpr, @LGLO, @mschuwalow, @smart-ass, @wojtek-tg, @XLPI, @mijicd, @fagossa, @denisgarci, to @dkarlinsky and @serragnoli for getting the last tricky tests over the finish line, and to @regiskuckaertz for single-handedly migrating the stream tests! Our efforts are already paying off in clearing the way for Scala Native support for ZIO!

**Comment by regiskuckaertz** [comment]
Amazing work everyone! 🎉
