### ISSUE TITLE
Add more tests for ZSink combinators that concatenate leftovers

### ISSUE THREAD

**Issue by iravid** [zio/zio#1648]
Some combinators on ZSink concatenate leftovers. We should add regression tests that verify that the leftovers are concatenated in correct order.

**Comment by msosnicki** [comment]
Hi @iravid , can I take this one? 
Leftovers in this context mean something like in `collectAllN` (so using leftovers within one element for downstream) or a Sink that would carry on state between the subsequent downstream elements (something like `movingAverage`, I haven't found anything like that so far in the existing API).
Thanks! :)

**Comment by iravid** [comment]
Hey @msosnicki, feel free to pick this up!

The point of leftovers is to represent the fact that a sink might not have consumed all the elements fed into it, and that they should be re-processed.

For example, consider a sink that processes a stream of chunks into chunks of no more than `n` elements. If you feed it a chunk of elements larger than `n`, it'd need to slice that chunk up and return the excess elements as leftovers.

**Comment by kitlangton** [comment]
Looks like these got added :)
