### ISSUE TITLE
Checklist: Ensure methods are sorted alphabetically

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1658]

**Comment by LukaszByczynski** [comment]
I will take it

**Comment by wi101** [comment]
@LukaszByczynski Nice I will assign you

**Comment by LukaszByczynski** [comment]
I'm going to push one PR per file. I have hope this should minimize the conflicts between PR's.

**Comment by adamgfraser** [comment]
Going to close this as it is pretty old at this point. I think our files are generally organized this way. If anyone sees something out of place feel free to open a PR.
