### ISSUE TITLE
Checklist: Ensure ZIO.* methods are replicated to Task.*, IO.*, RIO.*, etc.

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1660]

**Comment by Twizty** [comment]
Hi, I'd like to take on this issue. Is it still available or is it already taken for the hackathon?

**Comment by adamgfraser** [comment]
We don't have any companion object for `URIO` right now. Do we want to add that?

**Comment by jakubjanecek** [comment]
I'd like to take this task as part of the hackathon.

**Comment by jakubjanecek** [comment]
I did my best to synchronize all the companion objects, PR is ready to be reviewed: https://github.com/zio/zio/pull/1746
