### ISSUE TITLE
Chunk.drop results in NegativeArraySizeException

### ISSUE THREAD

**Issue by MI3Guy** [zio/zio#1663]
When calling Chunk.drop with a value greater than the length, a java.lang.NegativeArraySizeException is thrown.

For instance:

    Chunk(1, 2, 5).drop(10) // throws

This issue does not occur if I create an AnyRef Chunk instead of Int.

    Chunk[AnyRef](new AnyRef()).drop(10) // does not throw

I'm running 1.0.0-RC12-1.

**Comment by vasilmkd** [comment]
I ran into this bug when implementing #1572. 

This has already been fixed, but hasn't made a release yet.
https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Chunk.scala#L55

**Comment by MI3Guy** [comment]
Great. Thanks.
