### ISSUE TITLE
Sink.foldWeighted can get stuck on a single element larger than max

### ISSUE THREAD

**Issue by iravid** [zio/zio#1671]
The following snippet will hang:

```scala
    Stream(5)
      .transduce(
        Sink
          .foldWeighted(List[Int]())((i: Int) => i.toLong, 4) { (acc, el) =>
            el :: acc
          }
          .map(_.reverse)
      )
      .runCollect
```

The reason is that `foldWeighted` (and `foldWeightedM`) will refuse to process an element that brings the weight over `max`, so transduce is perpetually stuck with a leftover.

Should we allow `foldWeighted` to create a single element batch with weight > max? I think this makes sense.

### Sidenote:

This is actually bigger than `foldWeighted`, and will happen whenever a sink refuses to process an element, and rejects it by signalling completion with the element in the leftover.

The sink operators (`transduce`, `aggregate`, `aggregateWithin`) will all "hang" today when a sink refuses to process a single element. I think this is the only reasonable alternative, as all other choices lead to dropping an element. That should probably be an explicit user choice.

**Comment by iravid** [comment]
@vasilmkd @jdegoes @regiskuckaertz @adamgfraser What do you think?

**Comment by vasilmkd** [comment]
Agreed, dropping should only ever be user choice.

**Comment by regiskuckaertz** [comment]
Same here, either dropping or returning should be decided at the call site imo.

**Comment by iravid** [comment]
@vasilmkd @regiskuckaertz 

Ok, so that's agreed. What do you think about the behavior of `foldWeighted`? I'm going back and forth on this, because I have a use case that would break if a single element batch larger than `max` would be created.

Maybe we should allow a function to be passed in that replaces the element? The user can then decide how to handle this case. That function would default to `identity`.

**Comment by regiskuckaertz** [comment]
I like the function, that’s a great idea. What if it allowed the user to break down into smaller ones? Because if the default is identity, then isn’t the only alternative to drop some information? In your example say it would be to take the min between the element and the max, instead of returning `4 :: 1 :: Nil` or some such.

**Comment by iravid** [comment]
Oh yeah, that's cool. So we can do `A => Chunk[A]` (or `A => ZIO[Chunk[A]]` for `foldWeightedM`). And the resulting chunk is treated as a leftover, so its elements would be processed normally (and can be further decomposed). Big 👍
