### ISSUE TITLE
Add Meta term to Cause enumeration

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1684]
A new `Meta` tag can be attached to `Cause` to allow attachment of metadata.

There are three obvious options here.

One is supporting only _boolean metadata_. For example:

 - Should this stack trace be printed?
 - Is this a primary failure?
 - Did this failure come from a finalizer? 
 - Etc.

```scala
final case class Meta[E](cause: Cause[E], contains: AnyRef => Boolean) extends Cause[E]
...
case object Stackless
def stackless[E](cause: Cause[E]): Cause[E] = Meta(cause, _ eq Stackless)
```

This is very easy to use but only supports boolean metadata. 

The second option is to allow typed information to be attached to a `Cause`. This is more powerful but much more cumbersome to use:

```scala
final case class Meta[M, E](cause: Cause[E], meta: M) extends Cause[M, E]
...
def meta[M, E](meta: M, cause: Cause[M, E]): Cause[M, E] = Meta(cause, meta)
```

A third option involves fixing the metadata type: to a sum type, created and maintained by ZIO. It offers an intermediate option between the other two options.

/cc @adamgfraser @neko-kai

**Comment by neko-kai** [comment]
Related: https://github.com/zio/zio/issues/1646 - there I propose a private product type in ZIO

**Comment by adamgfraser** [comment]
Is anyone working on this? Otherwise I can take it.
