### ISSUE TITLE
Add ZStream#paginate

### ISSUE THREAD

**Issue by iravid** [zio/zio#1704]
At the workshop on ZStream in Scala World, I wanted to demonstrate how to use ZStream to scroll through an S3 bucket listing.

The way S3's API works is like so:
- You query the `ListBucket` method and get back (simplified) `(List[Key], Option[ContToken])`.
- If the continuation token is defined, you need to query `ListBucket` again, and this time pass in the continuation token.

You'd think that this would easily work with `ZStream#unfoldM`, but that doesn't have the right shape: `unfoldM` is `unfold(s: S)(S => Option[(A, S)])`, but this says that the last fetch we'll make needs to return `None`; that's not how the API works. So you have to do an awkward dance and of course I couldn't figure it out during the workshop :-P

So extrapolating on the above signature from S3, we need something like `def paginate[R1 <: R, E1 >: E, A, S](s: S)(f: S => ZIO[R1, E1, (A, Option[S]))]` on `ZStream`. Then we could do:
```scala
def fetch: Task[(List[Key], Option[ContToken])]
def fetchNext(token: ContToken): Task[(List[Key], Option[ContToken])]

Stream.fromEffect(fetch).flatMap {
  case (keys, None) => Stream.fromIterable(keys)
  case (keys, Some(token)) => 
    Stream.fromIterable(keys) ++
    Stream.paginate(token)(fetchNext).mapConcat(Chunk.fromIterable)
}
```

**Comment by regiskuckaertz** [comment]
I'm on it.
