### ISSUE TITLE
Adding more doctests to data types and introps

### ISSUE THREAD

**Issue by hamednourhani** [zio/zio#1710]
This issue has been opened for new contributers on ZIO to be involved in the project and get deeper in zio api. Also doctest are testable scaladocs that will help the project users understand api usages and functionallities.
@jdegoes would you please add more guid for new comers.

**Comment by jdegoes** [comment]
@hamednourhani 

We are using `mdoc` to write code that is checked at build time. You can find more information [here](https://scalameta.org/mdoc/):

<https://scalameta.org/mdoc/>

To begin, I think you should first look at the [ZIO Website](https://zio.dev):

<https://zio.dev>

Then you should look at areas which are weak and choose something to work on. I can then help you get started adding more checked, compilable examples.

Sound good?

**Comment by hamednourhani** [comment]
@jdegoes it's a pleasure to working on zio. I will check the project and will come back with PR
