### ISSUE TITLE
Add ZStream.retry

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1711]
Retries on a failed pull according to the retry strategy..

This didn't make sense in the old encoding, but does in the new one.

/cc @iravid

**Comment by iravid** [comment]
This requires that we go over all the combinators and constructors and make sure they can be safely retried. Some of them aren't.

**Comment by jdegoes** [comment]
@iravid Isn't this also true of ordinary effects? `ZIO` provides `retry` method but it's hopeless to retry some things (e.g. loading a class).

**Comment by iravid** [comment]
@jdegoes Yeah, but most of the `Pull`s keep some internal state in refs that could get corrupted if errors occur. We have been assuming so far (through the contract of `Pull`) that if `Pull` gets interrupted or fails, it will not be called again (without recreating it through the `ZManaged` scope).

**Comment by wojtek-tg** [comment]
I'd like to try this but I have no idea if I won't go down some odd rabbit holes, I don't mind if anyone else picks it up in parallel.

**Comment by wojtek-tg** [comment]
I added some of my work above but ran into a problem that I can't really debug. If anyone wants to pick it up go ahead.

**Comment by lemastero** [comment]
Maybe a silly question, but can we now achieve with `ZSchedule`:
1) add a small random delay between retries (jitter)
2) perform retry up to N times (I would probably like to be able to log every retry)
3) add an exponential increase in delays (exponential backoff)

From my experience, it is very useful in some situations, to be able 
4) to distinguish between failures that should be retried and the one  not meant to trigger retry (this is an error we know about and we know if it happens there is no reason to retry

Retry with exponential backoff with jitter with custom non-recoverable error detection is the holy grail of retry world :)

**Comment by adamgfraser** [comment]
Closed by #4409.
