### ISSUE TITLE
Add ZStream.fromIterator

### ISSUE THREAD

**Issue by iravid** [zio/zio#1729]

**Comment by sideeffffect** [comment]
I'll do it :)

**Comment by kamilkloch** [comment]
Will this work? ;)
```scala
def fromIterator[R, A](it: Iterator[A]): ZStream[R, Nothing, A] = {
      ZStream.unfold(it)(it => if (it.hasNext) Some((it.next(), it)) else None)
    }
```

**Comment by sideeffffect** [comment]
has to be
```scala
final def fromIterator[A](iterator: ZIO[Any, Nothing, Iterator[A]]): StreamEffect[Nothing, A]
```
or maybe even 
```scala
final def fromIterator[A](iterator: ZManaged[Any, Nothing, Iterator[A]]): StreamEffect[Nothing, A]
```

the reason is that `Iterator` is impure, mutable by nature and thus the stream will not be re-runnable

**Comment by vasilmkd** [comment]
How is this different from `fromIterable`, geniunely curious?

**Comment by sideeffffect** [comment]
@vasilmkd `Iterable.iterator` always creates a fresh iterator (pointing to the first element). `Iterator` itself is a non-functional structure, which mutates on `.next()`
