### ISSUE TITLE
Add a method for converting ZStream[Byte] to a ZManaged[java.io.InputStream]

### ISSUE THREAD

**Issue by iravid** [zio/zio#1730]

**Comment by sideeffffect** [comment]
I'll do it :)

**Comment by Cereopsis** [comment]
@iravid Any requirements on the completeness  the InputStream implementation i.e should `markSupported()` return `true`?

**Comment by Cereopsis** [comment]
Lol, answering my own question, I think no is the answer as it would seem problematic and anyway the default implementation is `false`. I guess the user (developer!) should be aware of the IOException thrown by `reset()`

**Comment by sideeffffect** [comment]
still free to take? if yes, I will try to tackle this

**Comment by Cereopsis** [comment]
@sideeffffect Please feel free, I’m a little light on ZStream knowledge so although I think the end solution won’t be that complex, there’ll be a good bit of back and forth to get there 🤪. Not to sway your own style but I had a brief chat with @iravid yesterday and he mentioned that ZStreamEffectChunk might be useful?

**Comment by Cereopsis** [comment]
@sideeffffect ...you at the hackathon, by the way?

**Comment by sideeffffect** [comment]
not anymore :D (at the airport now, but proudly attended :muscle: )
