### ISSUE TITLE
Remove existential types from the ZIO codebase

### ISSUE THREAD

**Issue by vasilmkd** [zio/zio#1759]
Existential types are going away in Scala 3.

E.g. `ZStream#tap`.

**Comment by LGLO** [comment]
@vasilmkd could you point me to some article about existential types removal?

**Comment by vasilmkd** [comment]
https://dotty.epfl.ch/docs/reference/dropped-features/existential-types.html

**Comment by LGLO** [comment]
`Existential types using forSome have been dropped.`
`Existential types that can be expressed using only wildcards (but not forSome) are still supported, but are treated as refined types.`
I think we are safe using `_` and don't have to change to `Any` - do you see any benefit of having `Any` instead of `_`?

**Comment by LGLO** [comment]
I mean, there is no `forSome` in ZIO codebase.

**Comment by vasilmkd** [comment]
#1743.

I opened this issue because of a remark by @jdegoes. I just like to see consistency in the codebase. I'm ok with both solutions I suppose. :-)

**Comment by adamgfraser** [comment]
Are there any situations where `[_]` and `[Any]` would be semantically different?

**Comment by vasilmkd** [comment]
I'm guessing it depends on the variance of the type parameter? So for a contravariant parameter, it probably needs to be `Nothing`.

**Comment by LGLO** [comment]
I cannot contribute to the discussion about difference of `[_]` and `[Any]` I'd just hold on making massive changes without justification. Maybe someone has strong arguments in this discussion.

**Comment by vasilmkd** [comment]
I don't have strong feelings on this subject. I opened the issue for documentation purposes mainly.

**Comment by LGLO** [comment]
:+1: Good, I hope I'll learn something here!

**Comment by neko-kai** [comment]
wrt difference between Any and _ - this has been discussed before in

https://github.com/zio/zio/issues/381
https://github.com/zio/zio/pull/414

**Comment by adamgfraser** [comment]
Can we close this? Or maybe we should wrap it into #1298 regarding updating the contributor's guide with clear guidance for this and other areas. I definitely don't feel as qualified as some others to do #1298 but I'm happy to take a stab at it and people can tell me where I am wrong.

**Comment by neko-kai** [comment]
Hmm, there's a Scala bug with an example where scala fails to unify types – https://github.com/scala/bug/issues/11769, I thought it would be a good example for where `_` is better than `Any` – but surprisingly in this case `Any` works well, while both `_` and a type parameter fail!

```scala
// scala 2.12 only
object example {
  val mapBuilder = Map.newBuilder[String, String]
  val setBuilder = Set.newBuilder[String]

  def foreachParam[U](i: Iterable[Any])(f: Any => U): Unit = i.foreach(f)
  def foreachWildcard(i: Iterable[Any])(f: Any => _): Unit = i.foreach(f)
  def foreachAny(i: Iterable[Any])(f: Any => Any): Unit = i.foreach(f)

  // type arguments [String,Iterable[java.io.Serializable] with String => Any with scala.collection.generic.Subtractable[String,Equals]] do not conform to trait Subtractable's type parameter bounds [A,+Repr <: scala.collection.generic.Subtractable[A,Repr]]
  foreachParam(List(Option(""))) {
    case Some(_) => mapBuilder += "" -> ""
    case None => setBuilder += ""
  }

  // The argument types of an anonymous function must be fully known. (SLS 8.5)
  foreachWildcard(List(Option(""))) {
    case Some(_) => mapBuilder += "" -> ""
    case None => setBuilder += ""
  }

  // OK!
  foreachAny(List(Option(""))) {
    case Some(_) => mapBuilder += "" -> ""
    case None => setBuilder += ""
  }
}
```

Perhaps I was completely wrong about that and we should be using `Any` instead... The example shows there certainly IS a difference, but the difference in this example doesn't hold when extended to covariant data types, like ZIO:

```scala
def foreachWildcard(i: Iterable[Any])(f: Any => Option[_]): Unit = i.foreach(f)
def foreachAny(i: Iterable[Any])(f: Any => Option[Any]): Unit = i.foreach(f)

// OK!
foreachWildcard(List(Option(""))) {
  case Some(_) => Some(mapBuilder += "" -> "")
  case None => Some(setBuilder += "")
}

// OK!
foreachAny(List(Option(""))) {
  case Some(_) => Some(mapBuilder += "" -> "")
  case None => Some(setBuilder += "")
}
```

**Comment by jdegoes** [comment]
Existential types are being deleted in Scala 3.x.

**Comment by jdegoes** [comment]
My 2 cents `Any` is the way to go here, because (1) there will be no choice in Scala 3, and (2) it infers well and is safe under Scalazzi, exactly as safe as an existential type.

**Comment by neko-kai** [comment]
@jdegoes 
See https://github.com/zio/zio/issues/1759#issuecomment-533883673 / https://dotty.epfl.ch/docs/reference/dropped-features/existential-types.html, only `forSome` syntax is dropped, wildcards remain. (It wouldn't be possible to drop wildcards due to Java interop even if there was demand for that, aside)

**Comment by jdegoes** [comment]
@neko-kai Ah, interesting. What about `_` being co-opted for partial type application in 3.1 (ish)? Or is that no longer on the table?

**Comment by neko-kai** [comment]
@jdegoes There will be a switcheroo where `?` and `_` will swap meaning in ~3.1.

**Comment by adamgfraser** [comment]
I think if there is not a disadvantage there is some value to contributors in having one way to do something and to users in not wondering if there is some significant to the use of `_` in one place and `Any` somewhere else. It would also let us sidestep any issues between `?` and `_` since I assume at some point we will want to support both versions. Shall we open a PR to replace instances of wildcard types and see if it creates any issues?

**Comment by neko-kai** [comment]
@adamgfraser That would be educational :+1:

**Comment by adamgfraser** [comment]
Okay, will do.
