### ISSUE TITLE
Microsite publishing issue: unknown links

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1776]
@softinio https://circleci.com/gh/zio/zio/26796 there was some problem with links in the About page

**Comment by ghostdogpr** [comment]
@softinio I think there's still an issue: the page `Contributing` is not visible on the website: https://zio.dev/docs/about/about_index
If you click "Next", you get a 404.

**Comment by softinio** [comment]
@ghostdogpr My changes aren't like yet are they? we haven't done a release since I fixed? Once we do a new release that issue will go away. Issue from before I fixed.

**Comment by ghostdogpr** [comment]
Ah so because there was some link errors, the whole page is missing? I thought you only fixed the links, which was not the same as the whole page being missing. Never mind then 😅

**Comment by softinio** [comment]
@ghostdogpr yeah those link issues caused docusaurus to skip publishing that all together.

**Comment by ghostdogpr** [comment]
@softinio there's still one warning in mdoc step:
```
warning: about/contributing.md:12:17: Unknown link 'about/contributing.md#ZIO-Contributor-License-Agreement'.
Please read the [Contributor License Agreement](#ZIO-Contributor-License-Agreement) before continuing below.
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
