### ISSUE TITLE
A new TestAspect "only" to run single test in a Suite

### ISSUE THREAD

**Issue by dkarlinsky** [zio/zio#1790]
@adamgfraser It would be nice to have an aspect, called something like `only`, which when added to a single test in a suite, would case all other tests to be ignored. (Similar to `it.only' in mocha).
This could be very convenient during development, especially when debugging.

I think two aspects will be needed to pull this off. One on the outer suite that will do the filtering (ideally added to default aspects) and the `only` aspect that will mark the selected test somehow. 
The only way I see to mark a test in the `only` aspect,  is to add some magic mark to the label. (Unless we decide to add a notion of "tags" to `TestCase`)

What do you think @adamgfraser?
I would like to work on this, if this makes sense to you.

**Comment by adamgfraser** [comment]
I think this would be a great feature to add. The challenge is how to implement it. Let me think about it, you can do the same, and we can use this issue to discuss ideas or feel free to open a PR if you have something you would like to use as a starting point. Would be great to work with you on this!

**Comment by reibitto** [comment]
I was looking for this feature just now and I stumbled upon this issue. I like this idea.

I've been using the name matching approach up until now. The `-z` option in ScalaTest, and `-ex` in specs2:
https://etorreborre.github.io/specs2/guide/SPECS2-3.5/org.specs2.guide.Selection.html

These two approaches are ergonomically different, though I guess these features overlap enough that both don't need to be implemented?

**Comment by adamgfraser** [comment]
@reibitto I actually think these are both good features that would be nice to have. They have similarities but also support slightly different styles / use cases. `@@ only` seems like it would be slightly more useful if, say, you knew you wanted to only run these tests for the next few hours. Whereas the command line option could be more useful if you did a patch change and just want to run one or two tests once to make sure they still work okay before submitting your PR.

The SBT Test Runner already supports running only a certain suite like `testOnly zio.ZManagedSpec` but doesn't support only running certain tests within a suite. If you were interested, a PR to add that feature would be very welcome.

@dkarlinsky wrote the SBT test runner and I believe there was some discussion of supporting more command line options at the time. Anything you would add here from your experience?

**Comment by reibitto** [comment]
@adamgfraser Alright, thanks. I think I'll take a look at that then.

**Comment by adamgfraser** [comment]
@reibitto Awesome!

**Comment by dkarlinsky** [comment]
@adamgfraser I don't recall if there was actual discussion about adding a label filter command line argument. Maybe the possibility was just mentioned as "we may support this in the future"

**Comment by adamgfraser** [comment]
@dkarlinsky Yeah, I think it was definitely at that level of detail. Didn't know if you had gotten a chance to look into it at all.

**Comment by adamgfraser** [comment]
@reibitto Another thing to look at here would be implementing support for the `testQuick` command to only rerun failed tests.

**Comment by adamgfraser** [comment]
Closed by #1838 .
