### ISSUE TITLE
Add Cause#flatMap

### ISSUE THREAD

**Issue by iravid** [zio/zio#1806]
Can we do this? Did anyone ever look into this?

This can lead to `Cause#flatten`, which can be useful when sandboxing and unsandboxing. Currently unsandbox is formulated in terms of `catchAll`, but it's probably more accurate to formulate it in terms of `catchAllCause`, which would require that we flatten a `Cause[Cause[E]]` to `Cause[E]`.

**Comment by adamgfraser** [comment]
I think it should be possible. The only case of `Cause` that actually has an `E` value in it is a `Fail` "leaf" in the `Cause` "tree", so I think we should just be able to replace every `Fail` leaf in the original tree with the new tree produced by the `f` in `flatMap`. I'm already in these files so let me see if I can add this.

**Comment by iravid** [comment]
@adamgfraser You're everywhere!! 👑

**Comment by ghostdogpr** [comment]
Closed by #1706
