### ISSUE TITLE
Timeout on ChunkGen Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1807]
It looks like the third monad law test for `ChunkGen` is occasionally timing out, causing flakiness. @regiskuckaertz Could you take a look?

https://circleci.com/gh/zio/zio/27859?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by regiskuckaertz** [comment]
Ok, will do as soon as I get the opportunity either later today, or tomorrow as today this guy arrives in the family 😍 

![IMG_1590](https://user-images.githubusercontent.com/629976/65504503-70923900-dec7-11e9-849c-9353a61220e1.jpeg)

**Comment by ghostdogpr** [comment]
@regiskuckaertz I was gonna ask you a picture 😄 Enjoy!

**Comment by iravid** [comment]
😍

**Comment by adamgfraser** [comment]
Whoa! Awesome!

**Comment by adamgfraser** [comment]
This is quite old and I have not observed any flakiness in this test so going to close.
