### ISSUE TITLE
Fix ZIO#unsandbox

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1808]
`ZIO#unsandbox` should use `catchAllCause` and flatten it with `ZIO.halt` to avoid losing information on error. We should add a test to demonstrate that no information is lost during error composition.

**Comment by iravid** [comment]
#1706 has a principled `Cause#flatMap` (and `Cause#flatten`), so this ticket should be based on that branch (or after it is merged).

**Comment by adamgfraser** [comment]
This should be easy to implement in terms of `Cause.flatten` so I can just take care of it there.

**Comment by ghostdogpr** [comment]
Closed by #1706
