### ISSUE TITLE
Be less lossy about error composition in `orElse` and variants

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1809]
Currently `orElse` and variants are implemented in terms of `tryOrElse`, which will discard failure information on the left hand side, even if the right hand side fails. If the right hand side fails, it would be nice to have access to information on the failure of the left hand side, as well.

While discarding some information is inevitable — mainly because the left and right may have entirely different error types — holding onto some information may be useful.

In particular, we could wrap the `Cause` from the left hand side in `FiberFailure`, and make it a defect that is exposed chronologically prior to the errors of the right hand side. Or possibly, we could strip the `E1`s from the left hand side, leaving a `Cause[Nothing]`, which could precede the `Cause[E2]` of the right hand side.

```scala
  private[this] final def tryOrElse[R1 <: R, E2, B](
    that: => ZIO[R1, E2, B],
    succ: A => ZIO[R1, E2, B]
  ): ZIO[R1, E2, B] =
    new ZIO.Fold[R1, E, E2, A, B](
      self,
      ZIOFn(() => that)(_.stripFailures match {
        case None    => that
        case Some(c) => ZIO.halt(c)
      }),
      succ
```

**Comment by Twizty** [comment]
Hi, I'd like to implement that.

**Comment by vasilmkd** [comment]
The `ZSink#orElse` combinator closely follows these semantics as well. It would be nice if it continued to do so.

@jdegoes We used `Cause.Both` in other `ZSink` combinators. Would that make sense here?

**Comment by Twizty** [comment]
@jdegoes Hi, I'd like to clarify, does this issue require to fix `orElse`, or to fix `tryOrElse` in general? To fix just `orElse` I came up with something like this:
```
  final def orElse[R1 <: R, E2, A1 >: A](that: => ZIO[R1, E2, A1]): ZIO[R1, E2, A1] =
    self.foldCauseM(cause => cause.stripFailures match {
      case None    => that.catchAllCause(cause2 => ZIO.halt(Cause.die(FiberFailure(Cause.Both(cause, cause2)))))
      case Some(c) => ZIO.halt(c)
    }, _ => that)
```

Is it something you were looking for?

**Comment by neko-kai** [comment]
Done in https://github.com/zio/zio/pull/1828
