### ISSUE TITLE
`Promise.await` should be renamed `Promise.join`

### ISSUE THREAD

**Issue by cloudmark** [zio/zio#1827]
Fibres have a `join` and `await` which have different semantics.  Await simply peeks at a result while commits the life of the fibre with the result of the joined fibre. 

It would make sense to have the same semantics for Promise so rename await to join.

**Comment by cloudmark** [comment]
I can have a look at this if there is common consensus.

**Comment by cloudmark** [comment]
Should we allow both in the short term and mark `await` as deprecated?

**Comment by adamgfraser** [comment]
I'm 👎 on this. I understand that both of these involve semantically blocking but I don't think that blocking on every data type needs to have the same name (for example `take` on a `Queue` semantically blocks until there is an element in the `Queue`). A `Promise` isn't a thing like a `Fiber` that one would normally think you could `join`. Also `await` is very idiomatic among other functional and non-functional `Promise` implementations. This feels like creating a bunch of works for ourselves and our users for something that is actually less clear.

**Comment by iravid** [comment]
Yeah, this is a pretty established name by now, so 👎 on this as well.

**Comment by neko-kai** [comment]
Well, I like the idea for one 👍

**Comment by jdegoes** [comment]
I like the idea too but am happy to go with consensus. I irrationally expect await = Exit.

**Comment by adamgfraser** [comment]
I think the ship has sailed on this one.
