### ISSUE TITLE
Duration render for sub 1ms durations

### ISSUE THREAD

**Issue by LGLO** [zio/zio#1832]
`999999.nanoseconds.render` is `"0 ms"`.
What do you think about rendering it as `"999999 ns"` when to `toMillis < 1`?
@ghostdogpr

**Comment by adamgfraser** [comment]
Yes.

**Comment by ghostdogpr** [comment]
Sure, why not. Did you want to do it or shall I?

**Comment by adamgfraser** [comment]
Closed by #1839.
