### ISSUE TITLE
Add a function to implement simple loops

### ISSUE THREAD

**Issue by schernichkin** [zio/zio#1834]
Cats has `tailRecM` which supposed to be used to write TCO loops, however it useful when I need to perform some action untill condition met. With ZIO I use explicit recursion. Something like:
```scala
// loop until got non-empty set of values
def takeSome: Task[Set[A]] = queue.take.flatMap { values => if (values.isEmpty) takeSome else Task.succeed(values) }
takeSome
```
Implementing loops with recursive function requres type annotations I think it will be useful to have special function for such cases.

**Comment by adamgfraser** [comment]
Have you looked at the `Schedule` combinators? I think you could do what you are talking about with something like `queue.take.repeat(Schedule.doWhile(_.isEmpty))`.

**Comment by schernichkin** [comment]
Oh, thanks, did not know about it. Looks good, is it possible to get rid of Clock?

**Comment by adamgfraser** [comment]
Yes! We have two open PRs to remove the `Clock` dependency so should be coming very soon. Once we have that in we will probably also add some convenience methods on `ZIO` to make this even easier (e.g. `zio.doWhile(p)`). In the meantime you can use `ZIO.provide(Clock.Live)` to get rid of it.

**Comment by schernichkin** [comment]
Thanks. I will use it as you suggest and will update my library as soon as `zio.doWhile` will become available. Closing the issue.
