### ISSUE TITLE
ZIO.race performance problem

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#1844]
According to `IOEmptyRaceBenchmark` in `benchmarks`, `ZIO.race` is currently noticeably slower than Monix and Cats Effect IO Race's. On my machine:
```
[info] Benchmark                                (size)   Mode  Cnt    Score     Error  Units
[info] IOEmptyRaceBenchmark.catsEmptyRace         1000  thrpt   10  315.196 ± 398.678  ops/s
[info] IOEmptyRaceBenchmark.monixEmptyRace        1000  thrpt   10  192.894 ±   7.672  ops/s
[info] IOEmptyRaceBenchmark.zioEmptyRace          1000  thrpt   10   33.152 ±   0.572  ops/s
[info] IOEmptyRaceBenchmark.zioTracedEmptyRace    1000  thrpt   10   25.166 ±   1.548  ops/s
```

Sampled via `sbt 'benchmarks / jmh:run zio.IOEmptyRaceBenchmark'`

This makes a difference in workloads with a huge amount of `race`'s, such as `fs2.Stream.parJoin` – https://github.com/zio/zio/issues/1441

**Comment by YuvalItzchakov** [comment]
This sounds interesting, I'd like to work on it.

**Comment by jdegoes** [comment]
`raceWith` has gotten progressively more complex and is using quite a lot of machinery now. It has strong guarantees but it desperately needs a performance-sensitive rewrite.
