### ISSUE TITLE
Improve ZStream/ZStreamChunk composition

### ISSUE THREAD

**Issue by iravid** [zio/zio#1845]
Currently, mixing ZStream and ZStreamChunk can be a bit clunky.

For example, this doesn't work:
```scala
Stream.fromEffect(someEffect) *> aStreamOfChunks
```

It's possible that adding a few overloads of the sequencing operators will solve this. Happy to hear other thoughts!

**Comment by vasilmkd** [comment]
Just off the top of my head, would an implicit syntax class that exposes the inner stream of chunks work?

**Comment by Twizty** [comment]
Hi, I'd like to implement it.

**Comment by vasilmkd** [comment]
Go for it!

**Comment by vasilmkd** [comment]
@iravid Here's an idea. Can we make `ZStreamChunk` be a syntax class over a stream of chunks?

**Comment by vasilmkd** [comment]
@iravid Maybe not the most popular idea, but worth a discussion: https://docs.oracle.com/javase/8/docs/api/java/util/stream/BaseStream.html.

**Comment by iravid** [comment]
Closing as this is not the right approach to the problem.
