### ISSUE TITLE
Allow custom behavior on inheritFiberRefs?

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio#1847]
It might be interesting to allow custom behavior for FiberRefs when joining a fiber.
For example one could instrument sleeps very nicely with a fiberref that tracks how long a fiber has slept and on join the maximum of both values is used.

The default case should be to just use the value of the joined fibers, as is currently done.

Looking at FiberContext I believe I understand how this could be implemented.

**Comment by adamgfraser** [comment]
This sounds very interesting. Would the behavior be determined when creating the `FiberRef` or when joining it?

**Comment by mschuwalow** [comment]
I believe that having to specify the behavior during creation of the fiberref would lead to fewer surprises and have an easier usage, but I have no strong opinions either way

**Comment by adamgfraser** [comment]
I think being able to specify the behavior when the `FiberRef` is created could be much more interesting, because then if you created the `FiberRef` with some behavior you could guarantee that it would be executed in combinators like `race` where you might not be able to specify your own behavior at the time of joining.

**Comment by jdegoes** [comment]
So I've thought about this for a while now... great ideas.

Basically, any monoid over the ref value has well-defined properties under fork/join.

So we should modify `FiberRef.make` to something like:

```scala
def make[A](zero: A, combine: (A, A) => A = (_, last) => last): FiberRef[A} = ...
```

Then always use the `combine` operator on them.

Now we can support all monoids easily, and the current behavior is merely the "last" monoid as a convenient default.

Any takers? Pretty straightforward and should be backward compatibble.
```

**Comment by adamgfraser** [comment]
@mschuwalow If you want to take this it is all yours. Otherwise I will.

**Comment by mschuwalow** [comment]
I would like to take a shot it, if you don't mind

**Comment by adamgfraser** [comment]
Go for it!
