### ISSUE TITLE
Tracing/stack correction support?

### ISSUE THREAD

**Issue by pshirshov** [zio/zio#185]
At the moment it may be hard to restore the full execution path which lead to an exception because zio doesn't perform any stack manipulaitons nor trace execution path.

It may be kinda expensive but at the same time it may be extremely valuable for debugging/etc.

I would propose to implement additional debug runtime with tracing or stack correction support.

**Comment by jdegoes** [comment]
I was thinking about this the other day. Whatever the solution, it should have no impact on performance when disabled.

**Comment by kaishh** [comment]
Done in #849 :tada:
