### ISSUE TITLE
Alternative to Gitter

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#1884]
With the latest iOS, the Gitter app (which was already poor) became barely usable because of scrolling issues. It hasn’t been updated in 2 years so I’m not confident there’ll be a fix anytime soon. 

How about moving to something else that is actually working and maintained? Slack? Discord? Share your thoughts 🙏

**Comment by adamgfraser** [comment]
Those were the two I was going to suggest.

**Comment by NeQuissimus** [comment]
Vote for Slack

**Comment by neko-kai** [comment]
Gitter is clearly the most discoverable and has relevant features such as infinite addressable history. Slack workspaces are closed, so you can't link to a message publicly and free workspaces have perishable history

**Comment by ghostdogpr** [comment]
The Gitter apps are actually being deprecated and will be removed from the stores: https://gitlab.com/gitlab-org/gitter/webapp/issues/2281

@neko-kai valid points, especially the ability to view a room without joining. The search UX is so bad that keeping the whole history isn’t that useful unless you have direct links. But then those useful chats should be turned into FAQs or blog posts, ideally.

**Comment by softinio** [comment]
@ghostdogpr I am super glad you brought this up as I have struggled with gitter for a while also and is frustrating. 

I must admit I am not too keen on slack as the alternative though it works well the free version does not keep history and the reasons @neko-kai mentioned are all valid. We should avoid slack for sure in my opinion. 

I haven't used discord enough to know if it overcomes the limitations of Slack but certainly Its apps work, easy to join by just sharing a link, there are already some great functional programming servers that have moved to discord. So between the two I would vote for discord. 

I haven't look into it but github bought this company few months ago don't know its an option as never looked at it: https://spectrum.chat/

**Comment by softinio** [comment]
Rust lang community use Discord too. Here is sample if anyone has never tried it a functional programming one with an active scala channel: 

https://discordapp.com/invite/SKaXYj

**Comment by regiskuckaertz** [comment]
One would hope MS Teams would soon get integrated with Github.

**Comment by ioleo** [comment]
:+1: for discord
:-1: for slack
:-1: on spectrum

**Comment by softinio** [comment]
Ok so I took the initiative and setup a discord server for ZIO thereby reserving the ZIO name for the server on discord. Whether we decide to replace gitter with discord or not I thought there is some value in having this server in addition as it is genuinely a far superior service to gitter and what better way to decide than trying it. Happy to close it if we decide against it but at least server name reserved whilst we evaluate.

Here is the link to the invitation to join: https://discord.gg/2ccFBr4

I propose initially members of the zio steering committee be the founding admins and moderators of this discord server with their agreement of course.

So @jdegoes  @ghostdogpr @iravid @neko-kai  @pshirshov @wi101 would you like to be admin/moderator of this?

**Comment by iravid** [comment]
Sure. I just joined.

In terms of alternatives, Discord seems like the only viable one.

**Comment by iravid** [comment]
As I noted on Discord, we can't expect to get rid of Gitter any time soon, so I suggest just putting up @softinio's invite link on the ZIO/Core topic. I'll do so for zio-kafka.

**Comment by iravid** [comment]
@zio/core Is anyone against encouraging the participants in the Gitter chatroom to join the Discord server?

**Comment by adamgfraser** [comment]
I’m in favor of it.

**Comment by jdegoes** [comment]
I'd surely like to be a mod / admin!

My only concern with this is that due to its accessibility, we will "always" have to support Gitter, so Discord won't really reduce number of places we have to be, just fragment the community.

Moving away from Gitter would require:

 - Github/etc. based self-signup to chat (super easy / low friction sign in to chat)
 - Web interface

Maybe Discord supports these as well as Gitter and it's viable to slowly push everyone to Discord???

**Comment by ghostdogpr** [comment]
@iravid also in favor

@jdegoes Discord has a nice web interface. If you join the room we can make you admin: https://discord.gg/tS3ePv I don't think you can signup with github, however they don't force you to signup, if you join the server while logged out it creates an account automatically and you can attach it to your email later on.

**Comment by softinio** [comment]
@jdegoes Can you join so I can make you admin sir: https://discord.gg/2ccFBr4

I think everyone will move away from gitter eventually the way it has deteriorated over the last year. In the near term I think we will see regulars for sure enjoy using discord and new people wanting to interract with us will start in gitter and then move to discord when they decide to stick around and see the benefits. 

Signing up to discord is pretty low friction especially if you have had an account for another community anyway. 

Gitter is really unsable in my opinion nice to have this to be more productive.
