### ISSUE TITLE
Rename ZStream#transduce, ZStream#aggregate, ZStream#aggregateWithin

### ISSUE THREAD

**Issue by iravid** [zio/zio#1886]
These operations use sinks to aggregate elements and emit the results into the stream. The latter two operate asynchronously, and the last also uses timeouts from a schedule.

I noticed that `transduce` is not easily found; people usually gravitate towards `aggregate` for synchronous operations. I suggest doing the following renames:
* `transduce` => `aggregate`
* `aggregate` => `aggregateAsync`
* `aggregateWithin` => `aggregateAsyncWithin`

Would love to get some opinions before doing this.

**Comment by vasilmkd** [comment]
I agree with this change. I also had discoverability problems when I started contributing to ZIO streams. My throttling implementation uses transduce.

**Comment by mschuwalow** [comment]
Maybe it makes sense to keep transduce around as an alias.

**Comment by vasilmkd** [comment]
How about `through`?

**Comment by simpadjo** [comment]
Seems that no one is on it. Taking.
