### ISSUE TITLE
ZIO test: multiple parameters function generators

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#1889]
Right now it is easy to write generators for functions of one argument, but not more. This result in having to write tests as follows:
```scala
check(Gen.function[R, (A1, A2), B]) { f =>
  (??? zipWith ???)(Function.untupled(f))
}
```

Perhaps we need to add `Gen.function[2|3|4|5]`.

**Comment by adamgfraser** [comment]
Great idea. My top priority right now is getting the mocking framework and shared resources PRs in before the next release but I should be able to take care of this later today.
