### ISSUE TITLE
Add `ZEnv`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1891]
Currently, we lack a type alias to describe the set of all environmental effects that "ship" with ZIO.

Ideally, we would have this inside the `zio` package object:

```scala
type ZEnv = Clock with Console with System with Random with Scheduler with Blocking
```

It's not possible to do this naively, because Scala.js does not support `Blocking`. However, one could extract out a package-private `ZIOTopLevel` (or `AbstractZIOPackage`?) from the existing `package.scala` inside the `zio` package, and then extend from this class in both the Scala.js directory, and the JVM directory.

Then each extension could specify its own `type ZEnv`, as appropriate for the underlying platform.

Finally, existing code that uses, e.g. `DefaultEnvironment#Environment` or similar could be refactored to use the much simpler `ZEnv` type alias.

**Comment by mschuwalow** [comment]
I'll take this one.
