### ISSUE TITLE
ZIO Test: Migrate ZIO Test Internal Test Suite to ZIO Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1898]
ZIO Test has reached a point of maturity where it makes sense to migrate the internal test suite to use ZIO Test itself rather than the minimal test framework we are currently using. This will make it easier for contributors in the future because they will be able to use one testing framework across all ZIO projects and take advantage of all the features in ZIO Test to write and run tests.

This is a great issue for people who are looking to learn more about writing tests in ZIO Test and some of how it works and is also a good first issue for new contributors since there are a lot of different specs of varying size and complexity so you can pick what works for you. If you are interested in working on this please respond here with which spec you would like to work on so we don't duplicate efforts, submit a PR for that spec, and then we will check it off here.

- [x] AssertionSpec
- [x] BoolAlgebraSpec
- [x] CheckSpec
- [x] ClockSpec
- [x] ConsoleSpec
- [x] DefaultTestReporterSpec
- [x] ExpectationSpec
- [x] EnvironmentSpec
- [x] FunSpec
- [x] GenSpec
- [x] GenZIOSpec
- [x] LiveSpec
- [x] ManagedSpec
- [x] RandomSpec
- [x] SampleSpec
- [x] SchedulerSpec
- [x] SummaryBuilderSpec
- [x] SystemSpec
- [x] TestAspectSpec
- [x] TestSpec
- [x] TimeVariantsSpec

**Comment by unclebob418** [comment]
I'd like to help out with a few of these but may need some guidance (new to ZIO and I've never worked on a team before so the PR process is a bit unfamiliar). I'll start with TestSpec since that seems the simplest.

**Comment by adamgfraser** [comment]
Great! Please feel free to reach out here or on Discord if you have questions or need help as you are working on it.

**Comment by unclebob418** [comment]
I'll see if I can tackle the rest of these - the first one seemed easy enough and taking the time to understand the tests should help my understanding of how it all works

**Comment by adamgfraser** [comment]
Sounds good. Do however many you want. They vary a lot in size so whenever you reach a stopping point let me know and we can merge what you have done. Feel free to reach out any time if you have questions as you are working on them.

**Comment by unclebob418** [comment]
Working TestAspectSpec at the moment (understanding that will help with the doco). This one is... mch harder :) getting there slowly

**Comment by unclebob418** [comment]
@adamgfraser can you please tick off the tests migrated under #1959?
TestSpec
ConsoleSpec
EnvironmentSpec
SystemSpec

**Comment by adamgfraser** [comment]
@unclebob418 Good catch! Done now. `MockSpecSpec` is being taken care of as part of #2000 so will mark that off when it is merged but no need to do that one.

**Comment by TapanVaishnav** [comment]
@adamgfraser Hi Adam, I'd like to take on the following tasks(if that's okay)
```
CheckSpec
DefaultTestReporterSpec
GenSpec
MockSpecSpec
```

**Comment by TapanVaishnav** [comment]
> @TapanVaishnav thanks for volunteering! Is it ok if I do `GenSpec`? I have to rewrite `RandomSpec` to use `Gen` (see #2037) and was going to use the `GenSpec` migration to learn how to use `Gen` in support

Ok, no worries, go ahead. I will do the following ones then.
```
CheckSpec
DefaultTestReporterSpec
MockSpecSpec
SampleSpec
SummaryBuilderSpec
TestAspectSpec
```

**Comment by unclebob418** [comment]
Thanks @TapanVaishnav. Let me know if you have any questions - If it's something I can help with it'd be good to offload @adamgfraser a bit

**Comment by adamgfraser** [comment]
@TapanVaishnav Awesome! Thanks for contributing! `TestAspectSpec` was actually done in #1959 and `MockSpecSpec` was renamed to `ExpectationSpec` and done in #2000. Sorry, I just updated the checklist to reflect that. The others definitely look good though! What I would suggest is you pick one you want to work on initially and then when you are ready for another you can just post here with that one. That way other contributors can migrate tests you aren't working on.

**Comment by TapanVaishnav** [comment]
> What I would suggest is you pick one you want to work on initially and then when you are ready for another you can just post here with that one. That way other contributors can migrate tests you aren't working on.
Seems good. I will have a look at all the remaining ones and post a new comment.

**Comment by TapanVaishnav** [comment]
I'll take the `CheckSpec` one.

**Comment by adamgfraser** [comment]
Great!

**Comment by TapanVaishnav** [comment]
@unclebob418 I tried moving `checkspec` to `test` dir and now I'm getting the following error.
```Implementation restriction: access of method check in trait CheckVariants from <$anon: Function0>, would require illegal premature access to the unconstructed `this` of trait CheckVariants in package test```
which shouldn't happen because `CheckVariants` class is also being called from other classes like StreamSpec but there it's working with any problem. 
It's not ZIO related(I guess) but would be really thankful if someone can help.

**Comment by unclebob418** [comment]
@TapanVaishnav can you please create a PR so I can see your code? just use WIP in the title

**Comment by TapanVaishnav** [comment]
@adamgfraser @unclebob418 Created new PR, Please have a look and Sincere apologies for all the hustle.

**Comment by TapanVaishnav** [comment]
Now that the `CheckSpec` is done, I'd like to proceed with the next available `DefaultTestReporterSpec` if that's ok?

**Comment by adamgfraser** [comment]
Great!

**Comment by TapanVaishnav** [comment]
Hi Adam, as always thank you so much for your time and review(you are the best).
Now that `DefaultTestReporterSpec ` is done, I'd like to proceed with the next available one (which I believe is `GenSpec`) if you don't mind. 

Also sincere apologies for the trouble but can you update the checkbox list in the PR description.
Thanks in advance

**Comment by adamgfraser** [comment]
@TapanVaishnav Thanks for your work on this and for the reminder! I updated the checklist. I think @unclebob418 may be working on GenSpec so can you please coordinate on that one? We’re almost there!

**Comment by unclebob418** [comment]
Yes @TapanVaishnav I'm slogging it out with GenSpec. Sorry for the slow progress on this one. Perhaps give SampleSpec a go?

**Comment by TapanVaishnav** [comment]
Ok got it, then I can start working on `SampleSpec` but I'm going on a BizTrip from this weekend and might not be able to work full-on at this, so meanwhile, if someone wants to try `SampleSpec` then they are free to go

**Comment by unclebob418** [comment]
Looks like next up for me is `SummaryBuilderSpec`

**Comment by adamgfraser** [comment]
Great! For that one I think there is significant duplicated functionality between that and `DefaultTestReporterSpec` so I would suggest seeing if you can factor some of that out.

**Comment by unclebob418** [comment]
Should I just merge the specs into `DefaultTestReporterSpec`?

**Comment by adamgfraser** [comment]
I think ideally we would keep them separate but just factor out the common code, maybe into the existing `ReportingTestUtils.scala` file.

**Comment by unclebob418** [comment]
I'll take `TimeVariantsSpec`

**Comment by adamgfraser** [comment]
@unclebob418 I think that one should be pretty straightforward. Can you take a look at `GenUtils.scala` as part of that and see what needs to be moved to the `test` directory and what can be deleted? We're almost there!

**Comment by unclebob418** [comment]
@adamgfraser yeah this one is easy - actually almost done already :). I've deleted GenUtils - it's no longer used anywhere, but I'll break the helper functions from GenSpec out into a new GenUtils file I think. In `TimeVariantsSpec` I'm only using `checkShrink` & `checkSample` which I've imported from `GenSpec` at this stage.

**Comment by unclebob418** [comment]
@adamgfraser I'm actually wondering if this whole thing shouldn't move into `GenSpec` (either that or break other broad groupings out of `GenSpec` (e.g. numeric/text) to make it a bit more manageable?

**Comment by adamgfraser** [comment]
@unclebob418 I think moving it into `GenSpec` makes sense.

**Comment by unclebob418** [comment]
@TapanVaishnav did you make any progress with `SampleSpec` or are you happy for me to give it a go?

**Comment by TapanVaishnav** [comment]
> @TapanVaishnav did you make any progress with `SampleSpec` or are you happy for me to give it a go?

Please go ahead, I am caught up in my company's work. (and won't be able to touch it for a while)

**Comment by adamgfraser** [comment]
Closed thanks to fantastic work from @unclebob418 with help from @TapanVaishnav!

**Comment by unclebob418** [comment]
And @darl :)

**Comment by adamgfraser** [comment]
Yes! Fixed above.
