### ISSUE TITLE
raceAll doesn't correctly inherit FiberRefs

### ISSUE THREAD

**Issue by mlangc** [zio/zio#1900]
The new `raceAll` implementation, that isn't backed by `raceWith` anymore, does not correctly inherit `FiberRef`s. To reproduce add the following tests to `FiberRefSpec`:

```scala
testM("its value is inherited in a trivial race") {
  for {
    fiberRef <- FiberRef.make(initial)
    _ <- fiberRef.set(update).raceAll(Iterable.empty)
    value <- fiberRef.get
  } yield assert(value, equalTo(update))
},
testM("the value of the winner is inherited when racing two ZIOs with raceAll") {
  for {
    fiberRef <- FiberRef.make(initial)
    latch <- Promise.make[Nothing, Unit]
    winner = latch.complete(fiberRef.set(update1))
    looser1 = latch.await *> fiberRef.set(update2) *> looseTimeAndCpu
    looser2 = fiberRef.set(update2) *> ZIO.fail(":-O")
    _ <- looser1.raceAll(List(winner))
    value1 <- fiberRef.get <* fiberRef.set(initial)
    _ <- looser2.raceAll(List(winner))
    value2 <- fiberRef.get <* fiberRef.set(initial)
  } yield assert((update1, update2), equalTo((value1, value2)))
}
```

cc @chikei

**Comment by chikei** [comment]
Just to make sure, so in `raceAll` the last successful looser does not get inherited like what happened in [this test](https://github.com/mlangc/zio/blob/71ac6a77f8c6a3807377bcb5fa52e47677960ae9/core-tests/shared/src/test/scala/zio/FiberRefSpec.scala#L157)?

**Comment by mlangc** [comment]
The intended behavior is to do it like `ZIO.race` (see [these tests](https://github.com/mlangc/zio/blob/71ac6a77f8c6a3807377bcb5fa52e47677960ae9/core-tests/shared/src/test/scala/zio/FiberRefSpec.scala#L132)): Only the `FiberRef`s from the winner get inherited. If all participants in the race fail, nothing gets inherited.
