### ISSUE TITLE
Schedule's `||` considers delay even when decision is "no"

### ISSUE THREAD

**Issue by reibitto** [zio/zio#1909]
I ran into unexpected behavior when using Schedule's `||`. We discussed this a bit on Gitter and I was asked to create an issue for it since Schedule might have a couple of refactorings coming up which this may affect.

Basically the issue is that `||` currently considers the delay of a Schedule even if the decision to continue is false.

If a more concrete example is helpful, this is the exact example I ran into (copy/pasting from Gitter):

So I'm migrating our retry policies to use ZSchedule and I was able to model everything except one. Basically it's a policy that uses a different policy based on the error that was returned. Like "if it's a rate-limited error try every 2 seconds, otherwise every 100 ms". I tried with a combination of Schedule.doWhile and ||, but this didn't work because || chooses the minimum delay regardless if the decision to continue is true or not.

I created a custom combinator for this and it seems to do what I want, but I'm not sure if there's a way to do this with the existing functions. If one doesn't exist, I guess I can create an issue and subsequent PR, but I wanted to check here first what people think. Because I have no idea if what I created is even "sound". What I have is this:

```scala
final def <||[R1 <: R, A1 <: A, C](that: ZSchedule[R1, A1, C]): ZSchedule[R1, A1, (B, C)] =
  new ZSchedule[R1, A1, (B, C)] {
    type State = (self.State, that.State)
    val initial = self.initial.zip(that.initial)
    val update  = (a: A1, s: State) => self.update(a, s._1).zipWith(that.update(a, s._2)) { (d1, d2) =>
      ZSchedule.Decision(
        d1.cont || d2.cont,
        if(d1.cont) d1.delay else d2.delay,
        (d1.state, d2.state),
        () => (d1.finish(), d2.finish())
      )
    }
  }
```

And I'm using it like:

```scala
val normalPolicy = Schedule.spaced(2.seconds) && Schedule.doWhile[String](_ != "rate-limit-error")
val rateLimitPolicy = Schedule.spaced(100.millis) && Schedule.doWhile[String](_ == "rate-limit-error")

val combinedPolicy = (normalPolicy <|| rateLimitPolicy) && Schedule.recurs(10)
//val combinedPolicy = (normalPolicy || rateLimitPolicy) && Schedule.recurs(10) // Won't work
```

**Comment by mschuwalow** [comment]
This will be fixed as part of #1798 once it lands.

**Comment by mschuwalow** [comment]
This should be resolved now
@reibitto can you confirm and close this?

**Comment by reibitto** [comment]
Thanks for the Schedule rework @mschuwalow! I can confirm RC16 fixed this issue. Closing.
