### ISSUE TITLE
Website integrated discord chat

### ISSUE THREAD

**Issue by ioleo** [zio/zio#1941]
@softinio We should replace `open chat` (gitter integration) on website to discord.

I've found [TitanEmbeds/Titan](https://github.com/TitanEmbeds/Titan) project, but to enable it you need discord server admin rights. Could you look into it?

**Comment by ghostdogpr** [comment]
I think it was done already in https://github.com/zio/zio/pull/1914 (it wasn't deployed yet)

**Comment by softinio** [comment]
Yup already done. Will go out next deploy.
