### ISSUE TITLE
Introduce ZEnv decorators for different ZIO modules

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1953]
Introducing a `ZEnv.scala` file, which will house a companion object for the type alias `ZEnv` (defined in `zio` package object, through `ZEnvDefinition`), we can place a number of case classes that can offer decorating behavior.

```scala
object ZEnv {
  def clockDecorator(f: Clock.Service[Any] => Clock.Service[Any]): ZEnv => ZEnv = ???
  def systemDecorator(f: System.Service[Any] => System.Service[Any]): ZEnv => ZEnv = ???
  ...
}
```

With this functionality in place, it will become possible to write:

```scala
effect.provideSome(ZEnv.clockDecorator(...))
```

for example, to "weave" an aspect into `Clock`.

**Comment by mschuwalow** [comment]
I'll take this one
