### ISSUE TITLE
ZIO Test: Add ifEnv TestAspect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1960]
It would be useful to have a test aspect that runs a test only if an environment variable satisfies a provided assertion.

```scala
object TestAspect {
  ...
  def ifEnv(env: String, assertion: Assertion[String]): TestAspect[...] = ...
  ...
}
```

To be used as:

```scala
testM("A test of something") {
  ...
} @@ ifEnv("TRAVIS_CI", equalTo("true"))
```

Marks the test as ignored if the environment variable does not exist or is not set to the specified environment variable. Will need to use the live environment.

**Comment by jdegoes** [comment]
Can also imagine the property version of this, e.g. `ifProp`, which uses Java properties.

**Comment by adamgfraser** [comment]
I’ll take this.
