### ISSUE TITLE
ZSink.splitDelimiter

### ISSUE THREAD

**Issue by loicdescotte** [zio/zio#1965]
It would be nice to have a `splitDelimiter` operation on ZSink, to be able to do something close to Akka Streams `Framing.delimiter`, i.e, change the way elements are separated in a ZStream by merging and re-splitting them.

Akka Streams `Framing.delimiter` usage example : 

```scala
source.via(Framing.delimiter(ByteString("\n"), maximumFrameLength = 256)
```

It could be something like : 

 ```scala
stream.transduce(ZSink.splitDelimiter("\n", maximumFrameLength = 256))
```
Note : `maximumFrameLength` should have a default (unbounded ?) value.

Thanks

**Comment by iravid** [comment]
This would be a very nice generalization of `ZSink.splitLines`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by regiskuckaertz** [comment]
I'd like to take this one. So:
```scala
object ZSink {
  def splitDelimiter(delimiter: String): ZSink[Any, Nothing, String, String, String]
  val splitLines = splitDelimiter("\n")
}
```
? Also, can we try to find a better name? `splitAt`?

**Comment by iravid** [comment]
`splitOn` would be good! To be fully compatible with the current splitLines, we need to handle both `\n` and `\r\n`. So I guess we need a list of delimiters in the signature.

Would be interesting to see how this can be handled efficiently in general. I guess we need a prefix search tree.

**Comment by regiskuckaertz** [comment]
We could probably store the platform-specific line separators somewhere.

**Comment by iravid** [comment]
Sure I don't mind making it configurable, but the default should handle both delimiters and not require a decision.

We can also keep `splitLines` separately implemented for now if that complicates things.

**Comment by regiskuckaertz** [comment]
I think yes. I struggle to find another example where this would be useful but also it seems this opens up a box of weird edge cases 🤔
