### ISSUE TITLE
ZIO Test: Simplify Test Result Types

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1971]
Issue to track simplification of ZIO Test test results. Will work on this more once #1951 is merged. Things I am thinking about:

- Add an `Ignore` case to `BoolAlgebra` - This would let us have a `zero` for various combinators to combine assertions and I think could potentially allow us to unify some of our different types for test results.
- Unify `TestSuccess` and `TestFailure` into one algebraic data type - Right now `ZSpec` and `ExecutedSpec` has type `Either[TestFailure[E], TestSuccess[S]]` where `TestFailure` and `TestSuccess` themselves have subtypes. If we got rid of the `Either` and made this one hierarchy we could cut down on some boilerplate and provide some nice convenience methods for working with these types.
- Potentially remove `TestFailure.Runtime` case from unexecuted specs. Now that all specs are effectual I think we want all failures to go in the `E` parameters of the effect and only capture failures as test results once we have executed the specs.
- For executed specs, potentially build the test annotation map into the result type.

**Comment by jdegoes** [comment]
@adamgfraser Is this still relevant?

**Comment by adamgfraser** [comment]
@jdegoes No.
