### ISSUE TITLE
Flaky CancelableFuture Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1977]
```scala
[info] - CancelableFutureSpec
[info]   + interrupts the underlying task on cancel
[info]   - cancel returns the exit reason
[info]     false did not satisfy isTrue()
```

https://circleci.com/gh/zio/zio/33544?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mlangc** [comment]
I can't reproduce this with d5d1f7ab2516f6163970443425a27df8f3d3cdbb and `nonFlaky(10000)`.

**Comment by adamgfraser** [comment]
Okay let's close.
