### ISSUE TITLE
Cause#failureOrCause can stackoverflow but should use 

### ISSUE THREAD

**Issue by LGLO** [zio/zio#1984]
`Cause#failureOrCause` stack-overflows when it's made of many nested `Both`s.
`failures` would overflow as well in this case but case for `failureOrCause` is that is requires only first `Fail`.
Basically there is problem with `foldLeft`.

I stumped on it when I created 10000 failing effects and tried to `foreachPar` them and they completed before being interrupted, so each had time to fail before interruption.

**Comment by adamgfraser** [comment]
I can work on this.
