### ISSUE TITLE
Flaky ZIO test

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#1987]
[check this out](https://app.circleci.com/jobs/github/zio/zio/33869):
```
ZIO Test
[info] - ZIO
[info]   - raceAll
[info]     - returns last failure
[info]       25 did not satisfy equalTo(24)
```

**Comment by LGLO** [comment]
I was thinking a lot about this test some time ago. My only conclusion was that we can increase delay only.
This is because thread can be paused after passing some barrier/latch/whatever we add in test and before registering itself as a looser.

**Comment by regiskuckaertz** [comment]
Also done.
