### ISSUE TITLE
Interruptible regions in finalizers cause finalizers to not run after fiber is interrupted

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#2005]
Example: 
```scala
import zio.console.putStrLn
import zio.duration._
import zio.{URIO, ZIO}

object ZioIncoherentInterruptibleRegionsInFinalizers extends zio.App {
  override def run(args: List[String]): URIO[zio.ZEnv, Int] = {
    ZIO.never.ensuring {
      ZIO.sleep(1.second) *>
      ZIO.unit.interruptible *> // removing this causes print to happen
      putStrLn("Waited 1s") // never printed because interruptible causes immediate interrupt
    }.fork.flatMap {
      ZIO.sleep(1.second) *> _.interrupt
    }.as(0)
  }
}
```

Expected:

Line `Waited 1s` in the console

Actual:

Nothing is printed because interruptible op `ZIO.unit.interruptible` causes the finalizer to be interrupted AGAIN for good by its own `interrupted` status.

/cc @jdegoes @darl

**Comment by devesh-shetty** [comment]
Hi @neko-kai ,
Could I take this up? Thanks!

**Comment by neko-kai** [comment]
@devesh-shetty 
Sure, feel free to!

**Comment by jdegoes** [comment]
@neko-kai Damn, nice find. There mist be a story behind that! 😆

**Comment by jdegoes** [comment]
Hmm, actually isn't this correct behavior? What would you expect to happen? A finalizer is not special, so it is like any ordinary interruptible hole inside an uninterruptible region.

**Comment by neko-kai** [comment]
@jdegoes 
Well, let's see what haskell does 😅 https://repl.it/repls/WhichIrresponsibleCharacterencoding
```
Started
Finalizer: Waiting 1s
Waited 1s
```
The finalizer is not interrupted again – but then that has to do with interruption being an exception –  a one-time event. I would (intuitively) expect the finalizer to become interruptible by _another_ outside signal, but not by the _past_ interruption that caused it to execute.

**Comment by jdegoes** [comment]
@neko-kai To get the behavior you want, you could write:

```scala
ZIO.never.ensuring {
      ZIO.sleep(1.second) *>
      ZIO.unit.interruptible.run *>
      putStrLn("Waited 1s") // never printed because interruptible causes immediate interrupt
    }.fork.flatMap {
      ZIO.sleep(1.second) *> _.interrupt
    }.as(0)
```

You have to handle the interrupt signal otherwise it will terminate the finalizer. It's the same thing as doing, e.g. `uninterruptibleMask { restore => restore(foo).run *> otherStuff }`

If you want an uninterruptible section to _not_ be interrupted, then you need to make sure you `run` any potentially interruptible regions passed into your code; in the same way you need to make sure you handle their errors, because errors will break out of the finalizer in the same way that interruption will (indeed, they are both `Halt`).

**Comment by jdegoes** [comment]
I think this is just part of ZIO semantics, which allow you to punch interruptible holes in uninterruptible regions. You should always `run` untrusted effects (i.e. effects passed into your code, which you are sequencing into your own). Or not use `interruptible` (it must be used carefully, e.g. see `raceWith`) and just use `uninterruptibleMask`.
