### ISSUE TITLE
Fiber composition should be parallel

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2033]
Fiber composition operators should _always_ compose in parallel.

The reason is that if in a composite fiber, one fiber fails on some operation like `join` or `await`, then all must fail; rather than waiting for the other members of the composite to complete, it makes more sense to terminate them immediately like other parallel operators.

Mostly, this will be a matter of replacing `zipWith` in `Fiber.scala` with `zipWithPar`.

The following code:

```scala
  def shard[R, E, A](queue: Queue[A], n: Int, worker: A => ZIO[R, E, Unit]): ZIO[R, E, Nothing] = {
    val worker1 = queue.take.flatMap(a => worker(a).uninterruptible).forever

    ZIO.forkAll(List.fill(n)(worker1)).flatMap(_.join) *> ZIO.never
  }
```

should exhibit improved behavior: namely, if one worker fails, then the others will be terminated, rather than running until they fail.

We should put this or other simpler examples in a test to demonstrate correctness of fiber composition.

**Comment by adamgfraser** [comment]
I can work on this.
