### ISSUE TITLE
ZIO Test: Add assertCompletes

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2034]
ZIO Test could use a `val assertCompletes = assert(true, isTrue)` for tests that merely assert the completion of something. This would be added along side `assert` and `assertM` in the ZIO test package object.

**Comment by adamgfraser** [comment]
I can add this.

**Comment by jdegoes** [comment]
🙏

**Comment by hikouki-gumo** [comment]
Hi @adamgfraser, at the moment, with smart assertion (assertTrue), is it still recommended to use assertCompletes to assert the completion of something without error? Or is it possible to assertTrue?
