### ISSUE TITLE
Rename ZSchedule logInput / logOutput

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2036]
Rename to Rename `tapInput` / `tapOutput` for consistency with other tap methods. 

In addition, we could _consider_ renaming `tapOutput` to `tap` (or maybe not, since we have `whileOutput`, etc.).

We should deprecate the old versions until `1.0.0` by adding the deprecation annotation.

**Comment by mschuwalow** [comment]
Ioll take this after https://github.com/zio/zio/pull/1798 lands
