### ISSUE TITLE
Add ZStream#collectM, collectWhileM

### ISSUE THREAD

**Issue by iravid** [zio/zio#2055]
Like `ZStream#collect` and `collectWhile`, but evaluate an effect returned by the PF.

Signatures:
```
final def collectM[R1 <: R, E1 >: E, B](f: PartialFunction[A, ZIO[R1, E1, B]]): ZStream[R1, E1, B]
final def collectWhileM[R1 <: R, E1 >: E, B](f: PartialFunction[A, ZIO[R1, E1, B]]): ZStream[R1, E1, B]
```

**Comment by vasilmkd** [comment]
It would be nice to add these combinators to `ZStreamChunk` and `Chunk` as well.

**Comment by likeanowl** [comment]
I would like to help with this!

**Comment by iravid** [comment]
@likeanowl All yours!
