### ISSUE TITLE
ZIO Stream: Enable Tests on ScalaJS

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2069]
Currently all tests for the ZIO Streams project are in the `streams-tests/jvm` folder and thus only being run on the JVM. This ticket is to move all of those tests to the `shared` folder so that they run on both the JVM and ScalaJS and resolve any compilation or test failures that result from running them.

**Comment by urmaul** [comment]
Some tests won't succeed because they depend on unsupported features (example" https://github.com/zio/zio/blob/6bcd9042d17b83a736964fe36aed308fcb9fb2d3/core/js/src/main/scala/zio/internal/OneShot.scala#L44). Does it make sense to move only passing tests?

**Comment by adamgfraser** [comment]
@urmaul Yes but we should catalog the ones we don't move and make sure that they are for reasons intrinsic to ScalaJS and the corresponding methods have documentation that they don't make sense on ScalaJS.

**Comment by adamgfraser** [comment]
Closing as this functionality is already in place.
