### ISSUE TITLE
Run ZIO Core Test Suite on Dotty

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2070]
Currently ZIO Core is being compiled against Dotty but we are not running the test suite on Dotty. This ticket is to enable that by changing the `testDottyJVM` command alias in `build.sbt`, get the test suite to compile on Dotty, and resolve any issues that result.

**Comment by tenzki** [comment]
I will take this one.

**Comment by StelaLeon** [comment]
I would like to take a look at this, @tenzki are you still on it or shall i pick it up?
