### ISSUE TITLE
Move the docs to a seperate project with its own release cycle

### ISSUE THREAD

**Issue by ioleo** [zio/zio#2071]
Currently the documentation is versioned/released together with ZIO, which is troublesome in some scenarions, like when ZIO Mock framework was updated, but some of the examples relied on ZIO Macros (which were not yet updated at the time).

The solution is to move the docs to a seperate project `zio-docs` which will have its own release / versioning lifecycle independent of ZIO core.

**Comment by adamgfraser** [comment]
This is done now based on the work of @atooni.
