### ISSUE TITLE
Flaky STM Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2073]
We are seeing some flakiness in the "read only STM shouldn't return partial state of concurrent read-write STM" test in `STMSpec.scala`. This ticket is to identify the underlying issue causing the flakiness and resolve it. We have had several issues with flakiness of tests related to STM functionality before so that we thought we had resolved so there is probably a subtle issue here. This ticket needs someone with significant experience with the STM functionality in ZIO.

**Comment by mijicd** [comment]
Closed in #2134
