### ISSUE TITLE
Flaky RTS Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2074]
We are seeing flakiness in the test "cancellation is guaranteed" in `RTSSpec.scala`. This ticket requires someone with experience with main ZIO run loop.

**Comment by regiskuckaertz** [comment]
Is this still relevant?

**Comment by mlangc** [comment]
I can't reproduce this with d5d1f7ab2516f6163970443425a27df8f3d3cdbb and `nonFlaky(10000)`.

**Comment by adamgfraser** [comment]
Okay, let's close and we can reopen if it gets reported again. No point in having these sitting out there if we can't reproduce.

**Comment by mlangc** [comment]
@adamgfraser shouldn't we remove the `@@ flaky` though? Otherwise the bug is guaranteed to not show up again....

**Comment by adamgfraser** [comment]
You're totally right. Just opened a PR to remove it.
