### ISSUE TITLE
Make parts of ZManaged private

### ISSUE THREAD

**Issue by iravid** [zio/zio#2076]
This is necessary to evolve ZManaged's API in a backwards compatible way.

The following bits need to be changed:
- `ZManaged` itself needs to be a plain `final class` (and not a `case class`)
- The constructor needs to be hidden (`case class ZManaged[R, E, A] private ...`)
- An `apply(reservation: ZIO[R, E, Reservation[R, E, A]])` method should be provided on the companion object
- The `reserve: Reservation` constructor parameter should be made private (though I think that's the default once it's a plain class)
- A method `reserve: ZIO[R, E, Reservation[R, E, A]]` should be provided on the class

**Comment by mijicd** [comment]
cc @stkeky
