### ISSUE TITLE
Port combinators from ZIO to ZManaged

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio#2077]
ZManageds public API still lacks behind ZIOs API and we should explore how many of the combinators on ZIO can also be defined on ZManaged. The first part of this issue would be to collect all functions that are currently missing and in a second step investigate each one of them.

**Comment by saraiva132** [comment]
Methods that I identified are part of ZIO and not ZManaged. I am pretty sure I missed some or I just ignored them because it just does not even make sense to mention them here. I guess we can identify the ones that make more sense and create tickets for those and I can work on these straight away :)

- absorb
- absorbWith
- asError
- Bracket related
- cached
- catchAllCause
- catchSomeCause
- collect
- eventually
- filter related
- forever
- forkOn
- flattenErrorOption
- handleChildrenWith
- left/right leftOrFail/rightOrFail
- race related methods
- reject / rejectM
- repeat/ repeatOrElse / repeatOrElseEither
- retryOrElse / retryOrElseEither
- some / someOrFail
- summarized
- supervised
- tapBoth/ tapError
- timedWith
- timeoutFail / timeoutFork / timeoutTo
- to
- traced / tracingStatus / untraced
- uninterruptible
- void

**Comment by mijicd** [comment]
I propose to open this ticket for multiple contributors. Each one of them would be able to tackle a single combinator. WDYT?

@mschuwalow @saraiva132 ^

**Comment by saraiva132** [comment]
There is still work left to actually identify which ones make sense to implement in ZManaged. Are you suggesting that each separate ticket for each specific combinator would just be closed if it does not make sense or should that be discussed in the context of this issue?

**Comment by mijicd** [comment]
No, just keep the task list in this issue, perhaps in you comment. People could refer to this issue (e.g. part of ...) in their PRs.

**Comment by mijicd** [comment]
@iravid could you take a look at the list above?

**Comment by mijicd** [comment]
Guys, please raise your hand to the combinator you're taking and refer to this issue in the PR, otherwise there'll be duplicated work :).

**Comment by saraiva132** [comment]
@mijicd Guilty. yesterday I was not paying attention and did the same one. Should I update my issue up there with which ones are already done / being done ? Also at some point probably discard the ones that make no sense to port but I am unsure exactly which ones.

**Comment by mijicd** [comment]
That would be great, just convert the list to checklist.

**Comment by saraiva132** [comment]
@mijicd  done. If someone at some point can come up and tell which ones do not make sense to port so I check them it would be great.

**Comment by mijicd** [comment]
@saraiva132 perfect, thanks!

**Comment by mschuwalow** [comment]
My two cents on the ones remaining:

- bracket*: These will probably start having unintuitive semantics when defined on top of zmanaged. We started exploring this for Sync instances in interop cats https://github.com/zio/interop-cats/pull/39, but that discussion kind of died down. Maybe @neko-kai can provide input.

- forever: I believe does not really make sense on managed
- handleChildrenWith: probably useless considering that we have release here
- race*: I think will be tricky, but potentially quite interesting
- repeat*: probably doesn't make sense
- retry*: probably doesn't make sense
- summarized: there might be use for a version with three points of measurement: before reserve, after acquire, after release
- supervised: probably doesn't make sense
- uninterruptible: probably doesn't make sense

There are also a few more in ZIOs companion that might be interesting such as foldLeft.

**Comment by 3link** [comment]
I will implement `summarized `.

**Comment by zach-albia** [comment]
Can I try `tapBoth`/`tapError`?

**Comment by adamgfraser** [comment]
@zach-albia Please do!

**Comment by vpavkin** [comment]
I'll take reject/rejectM if noone started those yet :)

**Comment by adamgfraser** [comment]
@vpavkin Great!

**Comment by saraiva132** [comment]
@adamgfraser can you take a look at the list above and see what combinators still might make sense to add? Not a lot left but a lot of time has passed. Thanks!

**Comment by adamgfraser** [comment]
Closing in light of the introduction of scopes.
