### ISSUE TITLE
Remove for comprehensions from TArray

### ISSUE THREAD

**Issue by mijicd** [zio/zio#2078]
All for-comprehensions used internally should be de-sugared.

**Comment by fsvehla** [comment]
Why?

**Comment by mijicd** [comment]
Minor win in getting rid of tail map.

**Comment by YuvalItzchakov** [comment]
How about using https://github.com/oleg-py/better-monadic-for ?

**Comment by mijicd** [comment]
@YuvalItzchakov there's sort of a "silent" agreement not to use it inside the libraries in the organization. It's a great choice generally speaking though.

**Comment by AlexWerff** [comment]
Is anyone doing that? If not I will do so.

**Comment by mijicd** [comment]
It's yours.
