### ISSUE TITLE
Remove for-comprehensions from TQueue

### ISSUE THREAD

**Issue by mijicd** [zio/zio#2081]
All for-comprehensions used internally should be de-sugared.

**Comment by mijicd** [comment]
Closed by #2100

**Comment by env0der** [comment]
Sorry for the noob question, but may I ask what's the motivation for desugaring? some performance benefits?

**Comment by mijicd** [comment]
As I said in one of the related issue, it's a minor win of saving one frame by eliminating the tail map imposed by for comprehensions.

**Comment by env0der** [comment]
I see, thanks for the explanation!
