### ISSUE TITLE
Ensure all factories return STM

### ISSUE THREAD

**Issue by mijicd** [zio/zio#2084]
Make sure all structures are created in STM, e.g. in `TSet`:

```scala
object TSet {
  final def apply[A](data: A*): STM[Nothing, TSet[A]] = ...

  // other methods
}
```

Implementers should prefer `apply` to `make` and provide additional factories where applicable (as in `TMap` and `TSat`). The issue can be split among multiple persons, in which case the following checklist apply:

- [ ] `TArray`
- [x] `TPromise`
- [x] `TQueue`
- [x] `TRef`
- [x] `TSemaphore`

To avoid duplicate work, please state what you intend to pick in the comments.

**Comment by smart-ass** [comment]
I take TArray

**Comment by vitaly-pushkar** [comment]
I take TRef

**Comment by env0der** [comment]
I take TQueue

**Comment by vitaly-pushkar** [comment]
@mijicd `TRef` seems to already have a `make` that returns `STM`. Is it relevant?

**Comment by mijicd** [comment]
@vitaly-pushkar let's just rename it to `apply`. I'd leave `makeCommit` as it is.

**Comment by env0der** [comment]
@mijicd here is `TQueue` part: https://github.com/zio/zio/pull/2103

**Comment by env0der** [comment]
@mijicd and same for `TSemaphore` and `TPromise`: https://github.com/zio/zio/pull/2104
