### ISSUE TITLE
Use URIO in type signatures where possible

### ISSUE THREAD

**Issue by joroKr21** [zio/zio#2088]
E.g. `access`, finalizers, etc.

Would that make sense?

One reason to do this is type inference: see zio/interop-cats#104
I don't see a reason not to do it (it would also simplify a bit type signatures).

**Comment by joroKr21** [comment]
Hmm, actually it doesn't with RIO I forgot that RIO is fixed to Throwable. Is there a type alias that fixea the error to Nothing?

**Comment by ghostdogpr** [comment]
@joroKr21 URIO
