### ISSUE TITLE
Add ZStreamChunk#chunkN

### ISSUE THREAD

**Issue by saraiva132** [zio/zio#2109]
`  def chunkN(chunkSize: Int): ZStreamChunk[R, E, A]`

There is no guarantee that chunk have a uniform size and chunkN should constraint the chunk sizes to a parametrized value.

**Comment by TapanVaishnav** [comment]
Isn't `def buffer(capacity: Int): ZStreamChunk[R, E, A]` somewhat similar to above described `chunkN` ?

**Comment by saraiva132** [comment]
Following docs buffer aims to allows a faster producer to progress independently of a slower consumer by buffering up to `capacity` chunks in a queue. 

chunkN aims to break down chunks of arbitrary size to chunks of size N by slicing and re-arranging them

**Comment by saraiva132** [comment]
@TapanVaishnav are you picking this up?

**Comment by TapanVaishnav** [comment]
@saraiva132 I see, so in `chunkN` we only keep the elements till size N and removes all after that?

**Comment by TapanVaishnav** [comment]
> @TapanVaishnav are you picking this up?

Sure, I can pick up this.

**Comment by TapanVaishnav** [comment]
> chunkN aims to break down chunks of arbitrary size to chunks of size N by slicing and re-arranging them

@saraiva132 I started working on this and wanted to confirm one thing.
As per the above explanation, `chunkN` takes the first n elements and discards after that and returns a new `ZStreamChunk[R, E, A]` ?

**Comment by TapanVaishnav** [comment]
@saraiva132 Please have a look when you get time
https://github.com/zio/zio/pull/2171

**Comment by saraiva132** [comment]
@TapanVaishnav Taking a flight I will take a look as I get time. Good work!
