### ISSUE TITLE
Document the STM

### ISSUE THREAD

**Issue by mijicd** [zio/zio#2122]
STM documentation is missing from microsite. The issue can be split to the following subsections:

- [x] STM
- [x] TArray
- [x] TMap
- [x] TPromise
- [x] TQueue
- [x] TRef
- [x] TSemaphore
- [x] TSet
- [x] TReentrantLock

Note that this issue has been extracted from #417, and the parent will be updated once we're done with the changes.

Raise your hand for specific subsection you'd like to work on.

**Comment by felipehaack** [comment]
Hi,
I'm new here, but I would like to work on a few items from the list `TArray, TMap, TPromise and TQueue`. 
I'm just not sure if these items are already on the website (I didn't find there actually). Or, would you point me the place where these items should be placed?

**Comment by mijicd** [comment]
Hi @felipehaack, thanks for stepping up!

None of these are currently documented, and we really need them. They should be listed with other data types. Reach out if you need any help!

**Comment by felipehaack** [comment]
Thanks, I will come up with the documentation for these items and on the way there I will definitely reach you out. (I'm taking this pull request as example #1013)

**Comment by drmarjanovic** [comment]
Hi, I would like to take`TSet`.

Also, @felipehaack I can help you with `TArray`, `TMap` and `TQueue` if you agree.

**Comment by mijicd** [comment]
@drmarjanovic `TSet` is yours.

**Comment by felipehaack** [comment]
@drmarjanovic, please, thank you.

**Comment by felipehaack** [comment]
Hi @mijicd,
I would like to take the `TSemaphore` this time. Is it ok?

**Comment by mijicd** [comment]
@felipehaack sure thing, go for it!

**Comment by calvinlfer** [comment]
hello @mijicd, @francisToth and myself would like to pick up whatever is remaining 😸

**Comment by adamgfraser** [comment]
@calvinlfer Awesome!

**Comment by mijicd** [comment]
@calvinlfer amazing, thanks!
