### ISSUE TITLE
Ignore should not recover from unchecked exceptions

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#2142]
Recently in [this issue](https://github.com/zio/zio/issues/1868) we fixed `ZIO#option` to make it NOT handle unchecked exceptions. The point was that it should be explicit using something like `sandbox`.

I think the same reasoning applies to `ZIO#ignore`. What do you think?

**Comment by alexvanolst** [comment]
I agree, I would be surprised by the current behaviour of ignore. Have opened a PR.
