### ISSUE TITLE
ZIO Test: Add "not" variants of test aspects

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2144]
We have things like `jvmOnly`, `dottyOnly`, etc., that can run a test on only the JVM/Dotty/etc., but it would be nice to have their inverses: e.g. run a test everywhere except on the JVM/Dotty/etc. Maybe `exceptJvm`, `exceptJs`, `exceptDotty`, etc.

**Comment by adamgfraser** [comment]
Good idea. I will add.

**Comment by jdegoes** [comment]
You're up early! 😆
