### ISSUE TITLE
Provide a simple method to run a program to completion without explicitly folding

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#2153]
In most examples, the program is run at the entry point like `program.fold(_ => 1, _ => 0)`. This gets repetitive, and also provides a source of confusion for Scala developers not familiar/comfortable with folding.

Perhaps a simpler method, like `execute`, that would fold the program with 1 and 0 as defaults? Perhaps even a `execute(errorCode: Int, exitCode: Int)` overload?

**Comment by alexvanolst** [comment]
I like the idea of this helper to make ZIO examples simpler, but I think the name `execute` could lead to some confusion since it is just a conversion to an infallible effect with the standard exit codes and nothing is being executed.

How about `exit` or `exitCode`?

**Comment by hmemcpy** [comment]
@alexvanolst you might be right that `execute` implies something is actually *happening*, but I also think it should be a verb of some sort that implies "running" the effect. Naming is hard :)

**Comment by luis3m** [comment]
I suggest having a more descriptive type:
```scala
case class ExitCode(code: Int) extends AnyVal

object ExitCode {
  val Success = ExitCode(0)
  val Failure = ExitCode(1)
}
```
I'm also in favor of naming the new function `exitCode` which would be consistent with `.either`. Entry function would look like this:
```scala
def run(args: List[String]): URIO[ZEnv, ExitCode] =
  console.putStrLn("Hello GitHub").exitCode
```

An integer may be intuitive enough for a Java or C programmer but probably not for someone who's starting to code and perhaps many programmers who have never used exit codes before.

**Comment by jdegoes** [comment]
In #3561, I proposed something like:

```scala
sealed trait ZIO[-R, +E, +A] {
  ...
  def asExitCode: ZIO[R, Nothing, Int] = 
    self.foldCauseM(cause => UIO(println(cause.prettyPrint)) as 1, _ => 0)
}
```

**Comment by luis3m** [comment]
@jdegoes that's definitely better than the status quo IMO. I'm wondering if in your experience teaching ZIO the `Int` part has been intuitive enough. Probably seeing `asExitCode` in the documentation and samples will be enough. I lean towards having an `ExitCode` datatype.

**Comment by jdegoes** [comment]
@luis3m It would be better to have `ExitCode` as a separate wrapper type around an `Int`, although given it would break backward compatibility, the benefit is perhaps not quite worth it (I think it's open for debate though).

**Comment by adamgfraser** [comment]
We could write a Scalafix migration rule for this.

**Comment by jdegoes** [comment]
@adamgfraser I'm on board with that. 👍

**Comment by hmemcpy** [comment]
Great, I can see this was fixed by @luis3m! Closing. Thank you all!
