### ISSUE TITLE
Duration.Infinity has incorrect asJava

### ISSUE THREAD

**Issue by TimPigden** [zio/zio#2166]
Code is
```
    override def asJava: JavaDuration = JavaDuration.ofSeconds(Long.MaxValue)
```
The problem is that doing .toMillis on the result will attempt to muliply Long.MaxValue by 1000 causing an overflow.
It should be JavaDuration.ofMIllis(Long.MaxValue)

**Comment by TapanVaishnav** [comment]
@TimPigden Thanks for the detailed explanation, if you don't mind then I'd like to fix this one.

**Comment by TimPigden** [comment]
Hi, sure. But I thought of something namely the reverse operation, but I'm
m not in a position to look at code at the moment. Can you hold on for a
couple of hours?

**Comment by TapanVaishnav** [comment]
> Can you hold on for a couple of hours?

Sure, I also read the code and having concerns if is this really a bug. As, if someone wants to get `Long.MaxValue` of millis for `Infinity` object, then isn't it better to just call the `toMillis` instead of `asJava`?

**Comment by TimPigden** [comment]
Hi. No Inifinity.toJava.toMillis needs to work not cause a crash.
I spotted the bug because I used zio kafka. That allows setting of a default value of Inifinity. It then calls a java api that wants a java.time.Duration and that +subsequently calls toMillis on the java object - so the conversion happens against the bogus infinity value and zio kafka gets an exception.
looking at this code
```
  final def fromJava(duration: JavaDuration): Duration =
    if (duration.isNegative) Zero
    else if (duration.compareTo(JavaDuration.ofNanos(Long.MaxValue)) >= 0) Infinity
    else fromNanos(duration.toNanos)
```
the fromJava treats anything greater or equal to 
```
JavaDuration.ofNanos(Long.MaxValue)
```
as infinity. So the logical thing to do would be to convert Infinity to that value (not ofMillis as I originally suggested).

**Comment by TimPigden** [comment]
Hi @TapanVaishnav did you do something about this? It's urgent for me and I'll need tofix in a local copy. So if you've not done anything, I'll create a one-liner PR fix

**Comment by TapanVaishnav** [comment]
> Hi @TapanVaishnav did you do something about this? It's urgent for me and I'll need tofix in a local copy. So if you've not done anything, I'll create a one-liner PR fix

Sorry for the delay, I've created the PR and just waiting for someone to review it.

**Comment by adamgfraser** [comment]
@TimPigden @TapanVaishnav Merged.

**Comment by TapanVaishnav** [comment]
> @TimPigden @TapanVaishnav Merged.

Thank you 🙇
