### ISSUE TITLE
Interop Java Futures

### ISSUE THREAD

**Issue by ratoshniuk** [zio/zio#2177]
Hi there!

Can we provide and interoperation for Java Futures? 
They occurs very frequently in AWS, for example and it's kinda annoying to wrap them. 

What do you think about this approach?

```scala
object TaskUtils {
      def fromJavaFuture[T](f: CompletableFuture[T]): Task[T] = {
        Task.effectAsync[T] {
          cb => 
            f.handle((out, err) => {
              cb {
                err match {
                  case null => Task.apply(out)
                  case e => Task.fail(e)
                }
              }
            })
        }
      }
    }

```

it was `thieved` from zio-sqs , but i think it could be potentially useful in production where there are so much follow problems 😞

**Comment by regiskuckaertz** [comment]
Check out the [interop-java](https://github.com/zio/interop-java) project 😉

**Comment by ratoshniuk** [comment]
Thank you!
