### ISSUE TITLE
ZIO Test: Unify order of type parameters

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2178]
We did this once before, but unfortunately it looks like there is some divergence, e.g.:

```scala
TestRunner[R, L, T, E, S]
ZSpec[R, E, L, T]
```

We should look at all types and see if there is an ordering we could standardize on that would be familiar to those who know `R, E, A` in ZIO.

**Comment by adamgfraser** [comment]
I agree. How about we try to standardize everything around `[R, E, L, T, S]`? `R` and `E` stay at the front in normal order to be consistent with rest of ecosystem. The others are a bit more subjective but conceptually label comes before the test, and type of the test comes before the type of the successful result.

**Comment by jdegoes** [comment]
@adamgfraser I think that makes sense. The consistency helps a lot with learnability.

**Comment by adamgfraser** [comment]
@jdegoes Totally agree. I will do tonight.
