### ISSUE TITLE
Fold interop-java back into this project

### ISSUE THREAD

**Issue by iravid** [zio/zio#2187]
We moved the conversion methods for CompletionStage and friends out to a separate project, but that seems pointless as the Java platform is always there.

The methods there can be added to a platform-specific file in this project.

Anyone know of a reason why we shouldn’t do this?

**Comment by regiskuckaertz** [comment]
True 🤔

**Comment by jdegoes** [comment]
Makes sense to me, as long as they are isolated to JVM.
