### ISSUE TITLE
[error] Referring to non-existent class java.time.ZoneId$

### ISSUE THREAD

**Issue by serragnoli** [zio/zio#2208]
First time I'm running ZIO's `test` from `master` and I'm getting: [sbt-test-logs.txt](https://github.com/zio/zio/files/3828812/sbt-test-logs.txt)

I did a little digging and found a closed issue https://github.com/zio/zio/issues/1934 with a PR to fix it.
Are the errors I'm seeing due to something wrong with my env or an actual issue?

**Comment by softinio** [comment]
Can you put the contents of your log in a gist or just paste in this issue?

**Comment by serragnoli** [comment]
@softinio
Thanks for replying.
Here is the [GIST](https://gist.github.com/serragnoli/920cd860720d31ba0303b39ab93994c7l) with more details.

**Comment by adamgfraser** [comment]
@serragnoli Are you using ZIO Test on ScalaJS? If so you need to add a dependency that provides the `java.time` package. You can use [scala-java-time](https://github.com/cquiroz/scala-java-time) for this.

**Comment by serragnoli** [comment]
@adamgfraser 
I followed this [section](https://github.com/zio/zio/blob/master/docs/about/contributing.md#prepare-your-code) of the contributor's guide.
The [dependency you mentioned](https://github.com/zio/zio/blob/master/build.sbt#L123) exists in `master` plus the [plugin](https://github.com/zio/zio/blob/master/project/plugins.sbt#L5).

What am I missing please?

**Comment by adamgfraser** [comment]
@serragnoli Sorry, I should have looked at the logs more closely. It looks like you are trying to run the tests for ZIO streams on ScalaJS, is that right? Those tests haven't been enabled on ScalaJS yet and I believe `streamsTests` doesn't have that dependency currently.

**Comment by serragnoli** [comment]
@adamgfraser 
I am planning to start working on one of the open issues and I followed the contributors guide to verify whether my environment is OK. Therefore, I started SBT from the root of the project and did a  `clean; compile; test:compile; test` and noticed the errors in the GIST.

At the minute I'm under the impression the documentation may need some tweaking on how to avoid/ignore those errors to help newcomers (like me) but I'm not too sure what kind of tweak.

**Comment by serragnoli** [comment]
I'll clock out for a couple of hours now, but I'll be back afterwards.

**Comment by adamgfraser** [comment]
Sounds good. I will see if I can reproduce locally and come up with a recommendation. I will also be on Discord and can help there when you are back.

**Comment by adamgfraser** [comment]
@serragnoli I don't doubt the issue but I am not able to replicate locally. I think it has something to do with the `java-time` dependency and would try adding that to the `streamsTestsJS` project, but it is a little hard for me to give more definitive guidance than that since I can't reproduce it. Feel free to reach out on Discord to troubleshoot.

**Comment by simpadjo** [comment]
Had the same problem. Had to disable js modules from the build for local development.

**Comment by adamgfraser** [comment]
Could you try updating [this](https://github.com/zio/zio/blob/5d533f1f8c66d36d468d15e81f1cc5b882545bb1/build.sbt#L151) line by adding the following at the end?

```scala
  .settings(
    libraryDependencies += "io.github.cquiroz" %%% "scala-java-time" % "2.0.0-RC3" % Test
  )
```

**Comment by serragnoli** [comment]
OK. I was looking at this issue right now. I'll try your suggestion.

**Comment by serragnoli** [comment]
@adamgfraser The dependency has fixed the issue, thanks 👍 . I added it to a couple of places as you'll be able to see in the PR please.

**Comment by serragnoli** [comment]
> Had the same problem. Had to disable js modules from the build for local development.

Hi @simpadjo 
Could you re-enable the JS modules and try them against the latest from`master` please?

All the tests are now passing on my local env. It would be an extra layer of confidence before closing the ticket if the tests also work in your local env.

**Comment by simpadjo** [comment]
Works now, thank you!
