### ISSUE TITLE
ZIO Test: Remove or minimize creation of new runtimes

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2212]
A number of places right now where ZIO Test makes a new runtime: 

```scala
new DefaultRuntime {}
```

We should push this up higher and higher and ideally avoid or at least minimize creation of new runtimes, since each one has its own thread pool, unhandled error reporter, etc., and the user has no control over these things when a runtime is created and used internally.

**Comment by adamgfraser** [comment]
I am working on this.
