### ISSUE TITLE
Gen.alphaNumeric* not alphanumeric

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#2231]
All the alphanumeric methods in `zio.test.Gen` are based around `Gen.alphaNumericChar`

This generator pulls in too many characters:

```scala
@ ((48 to 57) ++ (65 to 122)).map(_.toChar).filterNot(_.isLetterOrDigit)
res2: IndexedSeq[Char] = Vector('[', '\\', ']', '^', '_', '`')
```

ASCII 91-96 need to be removed
This will also fix the weight on the gen of 52 :)

**Comment by adamgfraser** [comment]
Thanks for reporting! I will fix this now.

**Comment by NeQuissimus** [comment]
@adamgfraser @jdegoes Any chance I could get an RC17 with this? :)
