### ISSUE TITLE
ZStream scope error handling

### ISSUE THREAD

**Issue by vasilmkd** [zio/zio#2234]
Currently, `ZStream` is defined in terms of the `val process: ZManaged[R, E, Pull[R, E, A]]` method, which defines most streams as scoped effectful iterators.

There are some constructors that accept scoped resources, immediately try to enter the scope and build a stream inside it (`ZStream.unwrapManaged`, `ZStream.fromIteratorManaged`). Passing a `ZManaged.fail` to these constructors fails with an unhandled checked error.

There are also other constructors that don't assume anything and guard against failures that occur when entering the scope (`ZStream.fromEffect`, `ZStream.managed`). These constructors are safer, but currently produce a stream that will throw the scope entering failure when pulled. Honestly, I feel that this behavior is wrong, because the stream should not output the error, but rather, the stream should not even be constructed, because this error conceptually occurs before the stream even exists.

In that sense, the constructors that I mentioned first in this description are more correct, they don't allow the stream to be constructed.

Therefore, I would like to suggest the following. We should force the user to handle the scope errors before constructing the Stream, by requiring that any managed effect passed to a stream constructor has all checked errors handled (error type Nothing).

Further, this should be visible in the type signature of `val process: ZManaged[R, Nothing, Pull[R, E, A]]` and should be visible in the `managed`, `fromEffect`, `unwrapManaged` and other constructors as needed.

One caveat. This would probably change the signature of `bracket` to accept a non-failing `acquire` effect.

On the other hand, if this is not the direction that we wish to continue in, we should use this opportunity to define exactly how to unify these constructors and other stream combinators that accept a scoped pull somewhere in their implementation. This is very important for #1765.

@iravid

**Comment by vasilmkd** [comment]
After sleeping on this for a week... I have come to the following conclusion.

There is no need to force the user to handle all errors before creating a stream from an effect and here is why. In the end, streams are translated into `ZIO` values by `run`ning them. At that point, the user will be forced by the `ZIO` runtime to handle all checked errors, which is good enough in this case.

With that said, I still think that we need to keep the consistency of not allowing stream scope entering errors to be served by the stream itself, but rather fail its creation. I will illustrate this with a code example.

```scala
Stream.fromEffect(IO.fail("Ouch")).run(Sink.drain)
```

should fail before the `run` method even has a chance to `pull` the stream.

I will keep this issue open for a bit longer and I will hopefully close it later with a PR.

**Comment by vasilmkd** [comment]
But what if the error is not served as part of the pull, and the produced stream whose scope cannot be entered is combined with another stream and potentially retried. There would be no way to handle the error and it would continually fail, which forces the scope error to be served on the pull...

@iravid

**Comment by iravid** [comment]
Sorry for the delay here, terribly busy with work the last few weeks. Promise to come back to this next week or this weekend if time permits.

**Comment by vasilmkd** [comment]
There is no rush. I added the comment because I was "triggered" by the other issue. :smile: I'm sure we'll find a way to solve this properly.

**Comment by vasilmkd** [comment]
Have you had the chance to think about this? @iravid
