### ISSUE TITLE
Add access / accessM to ZStream

### ISSUE THREAD

**Issue by pjoneswork** [zio/zio#2238]
Looking for the best way to access the environment of a `ZStream`.

We can currently do 

```scala
trait FooZIO {
    def fooZio: ZIO[Any, Nothing, Unit]
}

object FooZIO {
    def bar: ZIO[FooZIO, Nothing, Unit] = ZIO.accessM[FooZIO](_.fooZio)
}
```

But, it doesn't appear that we have the equivalent ability on `ZStream`. E.g.

```scala
trait FooZStream {
    def fooZStream: ZIO[Any, Nothing, Unit]
}

object FooZStream {
    def bar: ZStream[FooZStream, Nothing, Unit] = ???
}
```

I propose adding `access` and `accessM` to `ZStream`. but I'm open to other suggestions.

**Comment by iravid** [comment]
@pjoneswork would be a good addition! You can work around this for now by doing `ZStream.fromEffect(ZIO.accessM(...))`

**Comment by pk044** [comment]
@pjoneswork are you planning to add it yourself? I'm up for implementing this in case it's free to take :)

**Comment by pjoneswork** [comment]
@pk044 : Go for it! I won't have time to tackle this in the near future. Thank you!
