### ISSUE TITLE
testOnly happily runs things that do not exist

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#2245]
This is more a UX thing than anything.
When using `testOnly` in SBT, our test runner seems to just report a happy status if the intended test suite does not exist.
I don't think it should be this way and a "missing test suite" error should be returned.

```
sbt:Kafka Commons> testOnly Bla
[info] ScalaTest
[info] Run completed in 15 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] ZIO Test
[info] Done
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for Test / testOnly
[success] Total time: 0 s, completed Nov 15, 2019 11:10:06 AM
```

**Comment by adamgfraser** [comment]
@reibitto Do you want to take a look at this? We should probably align `Spec#only` with whatever we do here.

**Comment by reibitto** [comment]
Sure, I'll take a look at this.
