### ISSUE TITLE
Run CI builds after merging into master

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio#2255]
Currently it is easy to silently break master as builds are only run on the pr branches.
The idea would be to merge the pr branch into master manually before running the build.

WDYT?

/cc @iravid @mijicd

**Comment by mijicd** [comment]
Master would still be broken though. Can anyone recall what's the reason for disabling strict builds (i.e. `Require branches to be up-to-date before merging`)?

**Comment by softinio** [comment]
I vote re-enabling strict builds

**Comment by guizmaii** [comment]
@mschuwalow Is this fixed? Can we close this issue?
