### ISSUE TITLE
Remove all code deprecated for 1.0.0

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#2257]
To get ready for the 1.0.0 release, delete all code marked as `deprecated` for 1.0.0.

**Comment by adamgfraser** [comment]
We should also identify any areas where we can make other improvements to the code related to deleting the deprecated methods. Like I know in `Semaphore` we can do things slightly better now that we don't have to support the deprecated methods. I am happy to take that one in particular but we should think about whether there are any other cases like that.

**Comment by ghostdogpr** [comment]
@adamgfraser good point!

**Comment by adamgfraser** [comment]
I'll knock this out tonight.
