### ISSUE TITLE
Single random element

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#2270]
Would it make sense to add this method?

```scala
  final def genValue[R, A](gen: Gen[R, A]): ZIO[R, Unit, A] =
    gen.sample.map(_.value).forever.take(1).runCollect.flatMap(l => ZIO.fromOption(l.headOption))
```

Sometimes I just want a single random element from a `Gen` rather than a full-blown `checkM` test.

**Comment by adamgfraser** [comment]
Yes I think so. I will work on adding something like that.
