### ISSUE TITLE
Assertion.forall expects a list

### ISSUE THREAD

**Issue by freskog** [zio/zio#2281]
The current implementation of Assertion.forall seems to expect that the underlying iterable is a list. 

```scala
val dummy: ZSpec[Any, Nothing, String, Unit] =
    test("forall works with a sorted set")(
      assert(SortedSet(1,2,3),Assertion.forall(Assertion.isGreaterThan(0)))
    )
```
This fails with

>       scala.MatchError: TreeSet(1, 2, 3) (of class scala.collection.immutable.TreeSet)
>     	at zio.test.Assertion$.$anonfun$forall$1(Assertion.scala:321)
>     	at zio.test.Assertion$.$anonfun$assertionRec$1(Assertion.scala:209)

If I try it with a list, it works as expected.

```scala
val dummy: ZSpec[Any, Nothing, String, Unit] =
    test("forall works with a list")(
      assert(List(1,2,3),Assertion.forall(Assertion.isGreaterThan(0)))
    )
```

The issue seems to be in the implementation of forall, where there's a hardcoded assumption on a list.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will fix this morning!
