### ISSUE TITLE
Provide a more helpful hint in the CanFail message

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#2285]
I just upgraded to RC17, and my scratch program stopped compiling with the following error:
```
This operation only makes sense for effects that can fail.
[error]     program.fold(_ => 1, _ => 0)
[error]                 ^
```
This is due to #2049, but I feel the failure message can be more helpful. I didn't know what to do until someone suggested mapping the result to a success value. 
This suggestion could be reflected in the error message.

**Comment by adamgfraser** [comment]
The challenge here is that we are doing this through creating these ambiguous implicit instances and we need to provide one error message for all instances in which an effect can't fail. So ideally we would like to provide a nice customized error message here like "use map" but that would not be accurate advice for a variety of other cases where you are using a combinator that doesn't make sense.

So I think there are a couple of things we can do here.

1. If there is another message that we think would be more helpful in general we can change it accordingly. This is very easy. If you have a message that you think would be more helpful or if anyone else has suggestions we can incorporate that very quickly.
2. In #2049 I put together a table of value preserving rewrites for combinators that don't make sense. We could potentially move that to a page on the ZIO website and include a link to that with more information on why these combinators don't make sense and how the user can rewrite them. Requires a little more work for us and the user would need to have an internet connection but could be nice.

Open to any other suggestions on the best way to do this.

**Comment by jdegoes** [comment]
It would be nice if we could make this a warning and not an error, that way the user can fail on it if necessary (I don't know a way to do that though; maybe through @deprecated?). I agree including a link to @adamgfraser's great table would be superb. And maybe a slight tweak to the wording, something like:

```
This error handling operation assumes your effect can fail. However, your effect has Nothing for the error type, which means it cannot fail, so there is no need to handle the failure. To find out which method you can use instead of this operation, please see the reference chart at:

  <link>
```

**Comment by adamgfraser** [comment]
Okay let me work on this.

**Comment by Tamriel** [comment]
I just got this nice error message, but the linked page does not exist yet. It's [https://zio.dev/docs/canfail](https://zio.dev/docs/canfail)

**Comment by hmemcpy** [comment]
Yeah, should be https://zio.dev/docs/can_fail

**Comment by adamgfraser** [comment]
Will fix.

**Comment by hmemcpy** [comment]
I think it's already fixed, maybe @Tamriel is on an older version?

**Comment by adamgfraser** [comment]
@hmemcpy Yes you're right.
