### ISSUE TITLE
Pretty render of `Duration` should not be limited to seconds

### ISSUE THREAD

**Issue by fanf** [zio/zio#2287]
We use duraction for human-scale tasks too, like daily/weekly cron job, and it would be nice if duration can be rendered natively (ie without relying to JodaTime or Java etc) to human readable numbers (up to days perhaps, even if "day" becomes complicated - but it can be ignored for duraction, it's complicated for dates).

**Comment by mijicd** [comment]
cc @bblagojevic94

**Comment by kolov** [comment]
I can pick this up

**Comment by mijicd** [comment]
I believe @bblagojevic94 is already on it, but perhaps the two of you can sync about it to avoid duplicated effort?

**Comment by bblagojevic94** [comment]
@mijicd, you are right, I'm already on it. But, if @kolov wants to join we can try to split the task into smaller units.

**Comment by fanf** [comment]
For your information, there is an ISO standard for period (https://en.wikipedia.org/wiki/ISO_8601#Durations). It's not nice for humans, but very handy for serialisation when you don't want to just have a number of millisec (typically in semi-human readable exchange format). 
It's more "for information", because I believe it's not a format well known/used, and I believe we step in the "hard" part of date/time, so in no way as important as having a one-call away method to pretty print durations in logs.

**Comment by kolov** [comment]
This task looks quite small to be worth splitting and synchronising the work.  After deciding what to render, probably there will not be much implementation code. ISO-8601 may be worth supporting, next to a one-call pretty print to produce something like `365d 6h 9m 9.76s`.

**Comment by bblagojevic94** [comment]
@fanf, just to sum up, we need a human-readable format for `Duration` (up to days) and for now, we won't support ISO-8601?

**Comment by fanf** [comment]
Yes, but that's *my* need and understanding of how things could be
priorized. I'm nobody in the project lead, so it's up to you to decide :)

Le jeu. 21 nov. 2019 à 18:27, Bojan Blagojević <notifications@github.com> a
écrit :
