### ISSUE TITLE
WIP: The 'jittered' problem

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2296]
Sometimes we want to tweak the environment. Ordinarily this requires deconstructing and reconstructing it, which cannot be done in a generic fashion in the current environmental convention—the shape of the environment needs to be known. This is leading to environmental widening and user-pain in methods like `ZSchedule#jittered`.

It occurred to me that reconstruction is not really necessary. All we need is the ability to tweak an environment in a scoped fashion.

The unscoped variant is pretty easy:

```scala
object experiment {
  trait ZService[S] {
    def decorate(f: S => S): UIO[Unit]
  }
  trait Logger {
    val logger: Logger.Service 
  }
  object Logger {
    trait Service extends ZService[Record] {
      def log(line: String): UIO[Unit]
    }
    object Service {
      def apply(record: Record): Service = new Service {
        @volatile private var record: Record = Record(line => UIO(println(line)))

        def log(line: String): UIO[Unit] = record.log(line)

        def decorate(f: Record => Record): UIO[Unit] = UIO { record = f(record) }
      }
    }
    final case class Record(log: String => UIO[Unit])
  }

  def decorate[R]: DecoratePartiallyApplied[R] = new DecoratePartiallyApplied[R]

  class DecoratePartiallyApplied[R] {
    def apply[S](proj: R => ZService[S])(f: S => S): URIO[R, Unit] = ZIO.environment[R].flatMap(r => proj(r).decorate(f))
  }

  decorate[Logger](_.logger)(record => record.copy(log = line => record.log(line)))
}
```

To tweak within a scope would require maintaining a list / stack of records and pushing / popping before & after decoration.

This is obviously WIP but may be worth spending a bit of time on.

**Comment by mvv** [comment]
I've used `FiberRef`s for that [here](https://github.com/mvv/zilog/blob/master/src/main/scala/com/github/mvv/zilog/ImplicitArgsLogger.scala)

**Comment by adamgfraser** [comment]
Superseded by #2594.
