### ISSUE TITLE
Rename provideSome to mapEnvironment / contramapEnvironment / contramap

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio#2316]
Feels like clearer naming and frees up the name for macros :D
WDYT?

/cc @iravid @ioleo

**Comment by regiskuckaertz** [comment]
That would be contramap as `R` is contravariant.

**Comment by mschuwalow** [comment]
> That would be contramap as `R` is contravariant.

Good point, I would say that mapEnvironment has better discoverability than contramap though, but I think either would be an improvement over provideSome naming

**Comment by jdegoes** [comment]
`provideSome` describes what it does, in fact, the name came from someone asking me, "is there a way to provide some of an environment?"
