### ISSUE TITLE
ZIO Test: Improve rendering when test selection is used

### ISSUE THREAD

**Issue by reibitto** [zio/zio#2325]
If a suite has additional suites underneath it, I don't think it makes sense to render the parent suite label if no tests were run underneath it. For example:

```
sbt:core-tests> testOnly *.ZIOSpec -- -t "test that doesn't exist"
[info] + ZIO
[info]   + someOrFailException
[info] Ran 0 tests in 501 ms: 0 succeeded, 0 ignored, 0 failed
[info] ZIO Test
[info] No tests were executed
```

I don't think "someOrFailException" should be printed out in this case. Probably neither should "ZIO" be (though it _might_ make sense to make an exception for the root node... not sure).

**Comment by adamgfraser** [comment]
I agree. Do you want to take the ticket?

**Comment by reibitto** [comment]
I'm not sure how I'm going to fix this just yet, but I can take a look.
