### ISSUE TITLE
Create a giter8 template for starting a new zio project

### ISSUE THREAD

**Issue by softinio** [zio/zio#2328]
Create a giter8 template for starting a new zio project. Perhaps base it on zio-actors as a small project. 

This template is to be used by maintainers of ZIO GitHub Organization to start new projects, it should have: 

- A Valid Circleci configuration
- A Valid build.sbt that includes configuration for releasing
- Common set of `project/plugins.sbt` 
- makes use of `project/BuildHelper.scala` as used in other `ZIO` projects

**Comment by jchoffmann** [comment]
I created something here: https://github.com/jchoffmann/zio-seed.g8  as a potential starting point for contributing something.

I kept it simple by depending just on `zio` and `zio-test` plus some plugins I find useful. In my opinion a simple bootstrap or seed giter8 shouldn't depend on more specific libraries like `zio-actors`. Additional templates can handle these.

What do you think?

**Comment by softinio** [comment]
There are no plans to depend on another library like `zio-actors`. 

`base it on zio-actors` is essential as we want a certain minimum set of requirements to be included in all repos similar to what `zio-actors` have such a configured `circleci` configuration that is included as part of the giter8 template same as for example `zio-actors` but with this name replaced with the new repo names.

**Comment by softinio** [comment]
oh @jchoffmann I think there is a misunderstanding on the scope of this issue! I think you are referring to a giter8 template for starting an external app using zio. The giter8 template I had in mind for this ticket is one we use within the `ZIO` org for new projects. Will update to make that clear. 

For the seed sample you have created feel free to add it to our docs here for people to use: https://github.com/zio/zio/blob/master/docs/resources/resources.md

**Comment by jchoffmann** [comment]
My bad, I completely misunderstood this. I will create a PR for `resources.md` which might at least help people new to ZIO.
 
As for the original scope, I could help here too but would need to become familiar with the way you ZIOnistas set up your projects (using `zio-actors` as starting point). It will take little while so maybe someone else is a better candidate for this.

**Comment by jchoffmann** [comment]
Hi @softinio , I've created something that is hopefully closer to what you need: https://github.com/jchoffmann/zio-project-seed.g8

It is based on setting a `title` (including capitalization and whitespaces) from which `name`, `package` and a few more properties can be derived.

Example:
```
$ g8 jchoffmann/zio-project-seed.g8
... [SLF4J spam omitted] ...
title [ZIO Project]: ZIO Template Test
name [zio-template-test]:
package [zio.template.test]:
docs_directory [zio-template-test-docs]:
circleci_cache_key [sbt-zio-template-test-cache-v2]: sbt-template-test-cache-v2
discord_link [https://discord.gg/UNKNOWN]:

Template applied in /Users/jh/Development/./zio-template-test
```

You can see the example output here: https://github.com/jchoffmann/zio-template-test
(this compiles)

**Comment by mijicd** [comment]
@jchoffmann the template seems to be working really nice. We might polish it a bit, fo example, I'd remove everything but name.

@softinio wdyt?

**Comment by jchoffmann** [comment]
Thanks for your comment, happy to change and polish it as you like. Would you like to see something like this then?
```
$ g8 jchoffmann/zio-project-seed.g8
... [SLF4J spam omitted] ...
name [ZIO Project]: ZIO Template Test

Template applied in /Users/jh/Development/./zio-template-test
```
and derive all other keys from the name? (e.g. doc, circleci)

How about the discord link, just leave it as hardcoded UNKNOWN in the template?

**Comment by mijicd** [comment]
I'm not sure how frequently will the invite expire. However, we can probably use the current one as the default.

**Comment by mijicd** [comment]
One more thing, we should remove `zio-nio` from dependencies, as it might not be needed by everything. ZIO and ZIO Test should be there for sure.

**Comment by jchoffmann** [comment]
@mijicd I've changed the template according to your comments: https://github.com/jchoffmann/zio-project-seed.g8

[x] simplify template by deriving everything from the single property `name`
[x] scala-steward config
[x] use current discord links
[x] remove `zio-nio` and `scala-reflect` dependencies

The workflow looks like this now:
```
$ g8 jchoffmann/zio-project-seed.g8
... [SLF4J spam omitted] ...
name [ZIO Project]: ZIO Template Test

Template applied in /Users/jh/Development/./zio-template-test
```

You can see the example output [here](https://github.com/jchoffmann/zio-template-test)

**Comment by mijicd** [comment]
@jchoffmann this looks quite good! Let's see if @softinio has some additional suggestions, but as far as I'm concerned, this can be the new library seed.

**Comment by softinio** [comment]
@jchoffmann overall looks good to me thank you so much for doing this. 

Did you want to contribute your project and move it to the ZIO org or do you prefer to keep it where it is?

**Comment by jchoffmann** [comment]
@softinio happy to move it to the ZIO org, that makes most sense. You can just copy it from my repo, change the template license, remove my name from it etc, according to how you want to keep your projects. It's not a complicated thing, hope it helps saving a bit of time :-)

**Comment by softinio** [comment]
@jchoffmann thanks so much you are awesome! Will do it later today. Bedtime for me now :-)

**Comment by softinio** [comment]
Thank you @jchoffmann we now have https://github.com/zio/zio-project-seed.g8
