### ISSUE TITLE
Consider making stepChunk not final on ZSink.

### ISSUE THREAD

**Issue by sir-wabbit** [zio/zio#2343]
```scala
  /**
   * Steps through a chunk of iterations of the sink
   */
  final def stepChunk[A00 >: A0, A1 <: A](state: State, as: Chunk[A1])(
    implicit ev: A1 =:= A00
  ): ZIO[R, E, (State, Chunk[A00])] = {
    val _   = ev
    val len = as.length

    def loop(state: State, i: Int): ZIO[R, E, (State, Chunk[A00])] =
      if (i >= len) UIO.succeed(state -> Chunk.empty)
      else if (self.cont(state)) self.step(state, as(i)).flatMap(loop(_, i + 1))
      else UIO.succeed(state -> as.asInstanceOf[Chunk[A00]].splitAt(i)._2)

    loop(state, 0)
  }
```
could be optimized for some `ZSink`s if it is not declared `final`.

EDIT: I am not even sure HotSpot uses `final` modifiers. I know that Scalac is supposed to be able to use those, but I don't trust Scalac at all :) I would argue that `final` is an anti-pattern except in very low-level highly optimized code.

**Comment by vasilmkd** [comment]
@jdegoes might have some strong feelings on the scalac/jvm comment. I know the ZIO codebase strives for using the `final` modifier anywhere where it is possible to do so. Of course, a PR with these optimizations would be very welcome and I'd be very happy to take a look at.

**Comment by iravid** [comment]
PRs welcome for dropping `final` from stepChunk!

**Comment by guizmaii** [comment]
Closing as the `stepChunk` method doesn't seem to exist anymore
