### ISSUE TITLE
DefaultRuntime: Do not log pure interruptions

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2352]
We should add a method on `Cause` to check to see if the cause is a "pure interruption". A pure interruption is a `Cause` formed solely through nodes that are neither `Die` nor `Fail` (although it may have any combination of `Both`, `Then`, `Trace`, `Meta`, and `Interrupt`).

A cause that is a pure interruption (even a complex one) should not, by default, be logged to standard error, in the `DefaultRuntime`.

Currently, while simple interruptions are not logged, more complex interruptions are logged.

`Cause` is defined in `Cause.scala` in `core`, and `DefaultRuntime` is defined in `DefaultRuntime.scala` in `core`.

**Comment by adamgfraser** [comment]
Great idea! This will eliminate a wide class of spurious fiber failure warnings. I am working on this now.
