### ISSUE TITLE
Cause: Add extractors for terms of Cause

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2353]
We could use some custom extractors (`unapply` methods in companion objects) for `Die`, `Fail`, `Both`, `Then`, and `Interrupt`). These custom extractors should strip `Meta` information from the nodes, and possibly `Trace` information as well (todo: discuss).

These would help people interact more naturally with the terms of the `Cause` subtype.

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by vasilmkd** [comment]
@adamgfraser Name based extractors might be something that we could benefit from, in terms of saving allocations (not completely sure about the performance requirements of this issue). Just sharing this for visibility and education purposes.
https://hseeberger.wordpress.com/2013/10/04/name-based-extractors-in-scala-2-11/
