### ISSUE TITLE
ZIO Syntax: Refactor map2, map3, ..., to mapN

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2356]
The zio.syntax package defines `map2`, `map3` syntax, etc., on tuples, which utilize sequential zip. It is not convenient for refactoring to have to change the method name from, e.g., `map2` to `map3` because one added another element in the tuple. So instead, we should call this method `mapN` so no matter how many elements the tuple has, the user calls the same method name.

**Comment by adamgfraser** [comment]
@jdegoes What do you think about moving this to the `ZIO` companion object so that users do not have to rely on implicit syntax? Related to #2241.
