### ISSUE TITLE
Test: Colouring broken for multi-line strings

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#2362]
The blue colouring the test result formatter outputs fails for multi-line strings (such as stack traces):

Note: I had to remove some non-public info :)

![Screenshot from 2019-11-28 11-54-30](https://user-images.githubusercontent.com/628342/69823435-da380780-11d6-11ea-84f2-5ee22d905085.png)

**Comment by ghostdogpr** [comment]
Fixed by #2389
