### ISSUE TITLE
STM: Enhance TArray

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2368]
`zio.stm.TArray` is missing many useful methods:

 - `find` to find an element
 - `indexOf` to get the index of a matching element
 - etc.

Probably 10 or so helpful utility methods could be added to `TArray` to make summarizing and retrieving information from the array more useful.

I would look on methods of `Array` / `Vector` in Scala and see which ones would be a good fit for `TArray`.

**Comment by horned-sphere** [comment]
I'd like to have a go at this one. I've made a start but need to add in some tests yet.

**Comment by horned-sphere** [comment]
I've made a [PR for this](https://github.com/zio/zio/pull/2446). Hopefully I haven't gone too far with adding methods.

**Comment by mijicd** [comment]
Closed by #2446.
