### ISSUE TITLE
ZIO Test: typeCheck fails for interpolated string

### ISSUE THREAD

**Issue by ioleo** [zio/zio#2369]
Can we possibly allow for interpolated strings in `typeCheck`?

**This works**
```scala
assertM(
  typeCheck(
    """
    val a: Int = 1
    """
  ),
  isRight(isUnit)
)
```

**This does not**
```scala
val code =
  """
  val a: Int = 1
  """

assertM(
  typeCheck(s"$code"),
  // typeCheck(code),  <-- this also does not work
  isRight(isUnit)
)
```

The result is failed fiber with:
```
An unchecked error was produced.
      java.lang.RuntimeException: Compilation failed
```

**Why would it be useful?**
I'm my case I have a fairly large test suite and in each test I need to repeat imports:

```
import zio._
import zio.hset._

// here actual code
```

It would be nice if I could define my own helper method to remove that boilerplate.
/cc @adamgfraser

**Comment by adamgfraser** [comment]
We can definitely consider that. A couple of things to think about:

1. Names in the enclosing scope are already visible in the macro that implements `typeCheck`. So you actually don't need to do the imports in each of your tests as long as you have already imported in an enclosing scope, such as at the top of your file. That doesn't change the value of being able to do interpolation in other use cases but in this particular one you may already be okay.
2. The reason I haven't done that to date is that it can be relatively brittle. Right now the macro implementation just evaluates an `Expr[String]` so as long as it evaluates to a string and is a fixed reference that is available at compile time it will work. To support interpolation we would have to pattern match on a certain tree of expressions which I believe would mean that if there were slight variations in the pattern (e.g. single quotes versus triple quotes) the macro could not work at all. Maybe we can try to cover the common variations and it is worth it but that is the issue to think about.

**Comment by ioleo** [comment]
@adamgfraser Interesting, did the macro implementation change since `assertCompiles` version? I remember trying to add imports on top of my file with an earlier version, but it didn't work, thence I did not try it now. I'll try it out.

**Comment by adamgfraser** [comment]
@ioleo I'm not sure. I recall it being that way the last time I looked at it but it may have changed in an earlier version. I am testing it with an example like:

```scala
    testM("typeCheck must include names in enclosing scope") {
      final case class Box[+A](value: A)
      val result = typeCheck {
        """
        val a1 = 1
        val box = Box(a1)
        val a2 = box.value
        a1 == a2
        """
      }
      assertM(result, isRight(anything))
    }
```
