### ISSUE TITLE
ZIO Stream: Consider adding `.via` operator

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#2370]
Other streaming libraries has the concept of a `Flow`, that allows you to map one stream to the other in a single chain, like:
```
source.via(flow).to(sink)
```

It would be nice to have `.via` operator in ZIO Streams that allows mapping `ZStream[A] => ZStream[B]`.

Without that, the flow of operations looks not so nice:
```
mapStream(
  stream
    .map(...)
    .flatMap(...)
).aggregateAsyncWithin(...)
```
but it could be something like:
```
stream
  .map(...)
  .flatMap(...)
  .via(mapStream)
  .aggregateAsyncWithin(...)
```

**Comment by vasilmkd** [comment]
Working on it.
