### ISSUE TITLE
Deadlock in 1.0.0-RC17 - maybe due to infinite fiber shutdown

### ISSUE THREAD

**Issue by fanf** [zio/zio#2373]
After upgrading Rudder (https://github.com/Normation/rudder) from ZIO `1.0.0-RC16` to `1.0.0-RC17`, I encounter deadlock which manifests when only one CPU is provided to the application. 
In that case, thread dump show that every ZIO related thread are waiting in `OneShot`, and in particular the the maximum number of `zio-default-async` (2) is reached (both waiting). 

The application is a migration from an old code base and relies to a lot of `unsafeRunSync` (at each point of interaction between the nice zio world and the old reality). 

After a lot of discussion in `zio` chan, it was brought to the discussion by @jdegoes that the root cause may be the management of infinite fibers introduced in `RC17` which are now killed when parent die. And we do use such fiber for application-livespan action (like cron-like, etc - and now I know we should use `.daemon` for that. 

Reverting to `RC16` remove the dead lock.

**Comment by vasilmkd** [comment]
Same symptoms as #2226.

**Comment by jdegoes** [comment]
`eff.fork.daemon` will do what you want, but please wait until RC18 before trying again, as I think we need to discuss reasonable defaults.

**Comment by adamgfraser** [comment]
Closed as this was resolved with the implementation of the fiber supervision model.
