### ISSUE TITLE
Add Algebra for sending metrics to prometheus

### ISSUE THREAD

**Issue by softinio** [zio/zio#2381]
# Overview

Create Algebra needed to represent:

- the request to prometheus
- the response received from prometheus
- will need a method to transform from redis protocol message received to the new request algebra that will be used by the client

# Notes
- <https://prometheus.io/> 
- <https://prometheus.io/docs/instrumenting/writing_clientlibs/>
- Note that I have implemented a custom version of the redis protocol as the protocol for sending between client and server. This has already been implemented and can be used for both JVM and JS.

**Comment by dkarlinsky** [comment]
I will take this
