### ISSUE TITLE
Implement client for sending metrics to prometheus 

### ISSUE THREAD

**Issue by softinio** [zio/zio#2382]
# Overview

Implement client for sending metrics to prometheus

## Notes

- if its via http use <https://github.com/softwaremill/sttp> for client
- https://prometheus.io/
- <https://prometheus.io/docs/instrumenting/writing_clientlibs/>

**Comment by dkarlinsky** [comment]
I will take this

**Comment by darl** [comment]
afaik prometheus pulls metrics from application, not the application pushes them.
there are push-gateway for pushing, but its not common pattern to use prometheus

**Comment by toxicafunk** [comment]
FYI, I have just added [documentation for zio-metrics](https://zio.github.io/zio-metrics/docs/essentials/essentials_files#exporters) which supports most common Prometheus exporters including an Http Server for scraping as well as a PushGateway (https://github.com/zio/zio-metrics/blob/master/prometheus/src/main/scala/zio/metrics/prometheus/PrometheusExporters.scala).
