### ISSUE TITLE
Allow to call Fiber.dump from an external signal

### ISSUE THREAD

**Issue by fanf** [zio/zio#2390]
Fiber dump is a fabulous feature which by itself gives zio a huge value proposition. But a big part of that value is voided by the fact that currently, you can't use it when you really need, ie in an unforseen lock in production, especially if the lock happens in a condition set hard to diagnose and reproduce.

So, it would be a major win to be able to call fiber dump from an external signal/tools, like it's possible to do with `jstack` (or it was possible to do through kill -3, but I think it was removed).

Moreover, the listener for that signal might need to live in its own thread/fiber pool so that we can analyse even situation where `zio-default-async` is exhausted like in #2373.

**Comment by ghostdogpr** [comment]
@fanf I think #2263 covers this, doesn't it?

**Comment by fanf** [comment]
Totally, and I searched before posting (b/c I was almost sure to have discussed this before) and could not find it back :)

So, sorry for the noise! I'm closing this one and will comment on #2263 if needed.
