### ISSUE TITLE
Upgrade scala.js to 1.0.0-RC1

### ISSUE THREAD

**Issue by softinio** [zio/zio#2392]

**Comment by lvitaly** [comment]
@softinio I've prepared a pull request for this issue (https://github.com/zio/zio/pull/2479). `testJS` works fine locally but fails in CI tests on `testTestsJS/run`. It looks like replaced `java.lang.System.exit` method affects it (https://github.com/scala-js/scala-js/issues/3504). Latest Scala.js doesn't support this method (https://github.com/scala-js/scala-js/blob/7acc1ca8e5a43df6813a3dfa06555436510376a5/javalanglib/src/main/scala/java/lang/System.scala#L375) and I replaced it with Unit in `src/main/scala/zio/test/ExitUtils.scala`. I will try to figure it out.

**Comment by adamgfraser** [comment]
Closing as this is done.
