### ISSUE TITLE
Should We Remove Remaining Implicit Syntax?

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2400]
At this point the only implicit syntax remaining in `ZIOSyntax.scala` is:

- `fail`
- `require`
- `succeed`
- `effect`
- `effectTotal`

Are these worth having implicit syntax for? These all have corresponding methods on the `ZIO` companion object that seem as concise and straightforward.

**Comment by ghostdogpr** [comment]
I've never used any of these so I'm in favor of removing it. Maybe we can do a quick poll in the Discord to see if there are some users and why they prefer it.
