### ISSUE TITLE
Rename `paginate` method to `paginateM` and add new `paginate` method on `ZStream` and `Stream`

### ISSUE THREAD

**Issue by nicolasdasriaux** [zio/zio#2404]
There are 3 methods that allow to unfold on `ZStream`:
* `ZStream.unfold`,
* `ZStream.unfoldM` (with a parameter taking a function returning a `ZIO`)
* `ZStream.paginate` which could be named more consistently as `paginateM` as its function parameter returns a `ZIO`.

`paginate` would then be missing to match `unfold` (as opposed to `unfoldM`).

Changes would be:
* Rename current `paginate` method to `paginateM`
  `def paginateM[R, E, A, S](s: S)(f: S => ZIO[R, E, (A, Option[S])]): ZStream[R, E, A]`
* Add a new `paginate` method \
  `def paginate[R, E, A, S](s: S)(f: S => (A, Option[S])): ZStream[R, E, A]`

**Comment by vasilmkd** [comment]
Will you work on this or can I take it? @nicolasdasriaux

**Comment by nicolasdasriaux** [comment]
You can take it.

**Comment by vasilmkd** [comment]
On it.
