### ISSUE TITLE
Type Safety Issue with ZIO#withFilter

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2413]
I noticed that one of our tests for type safety of `ZIO#withFilter` is disabled on Dotty and confirmed that there is an issue here. Minimized example on Dotty is below.

I've tried the usual tricks such as an implicit syntax class and haven't been able to resolve this. I think this may indicate a more fundamental soundness issue here. The problem is that we are trying to constrain this to only be available when `E` is a supertype of `NoSuchElementException`. But `E` is naturally covariant so it is always a legal move for the compiler to widen `E` to a type such as `Any` that satisfies this constraint.

Copying @wi101.

```scala
object Example extends App {
  
  trait ZIO[-R, +E, +A] { self =>
    def withFilter[E1 >: E](f: A => Boolean)(implicit ev: NoSuchElementException <:< E1): ZIO[R, E1, A] =
      ???
  }

  def a: ZIO[Any, String, Int] = ???
  def b = a.withFilter(_ == 1) // compiles and inferred type of E is Object with Serializable
}

**Comment by jdegoes** [comment]
It should be any type that is a subtype of `NoSuchElementException`...

**Comment by adamgfraser** [comment]
We can definitely do that. I think the downside is that it will make the use case quite narrow. You wouldn't be able to use `withFilter` with `Task[A]` for example.

**Comment by jdegoes** [comment]
Hmm, actually, we need proof that we can embed `NoSuchElementException` into `E`, i.e. that `E` is a supertype of `NoSuchElementException`. 

But I think the issue is that we can't require that proof using a type bound, we have to use evidence, which is invariant, which forces a new type parameter.

Maybe it'd be simpler to add this method as syntax in companion object?

**Comment by adamgfraser** [comment]
I tried that and wasn't able to get it to work in a way where unsound examples didn't compile. I will post an example in a minute.

**Comment by adamgfraser** [comment]
```scala
object Example extends App {

  trait ZIO[-R, +E, +A]

  implicit class WithFilter1[R, E >: NoSuchElementException, A](private val self: ZIO[R, E, A]) {
    def withFilter1(f: A => Boolean): ZIO[R, E, A] = ???
  }
  
  implicit class WithFilter2[R, E, A](private val self: ZIO[R, E, A]) {
    def withFilter2(f: A => Boolean)(implicit ev: NoSuchElementException <:< E): ZIO[R, E, A] = ???
  }
  
  def io1: ZIO[Any, String, Int] = ???
  def io2: ZIO[Any, Nothing, Int] = ???
  lazy val result1 = io1.withFilter1(_ == 0)
  lazy val result2 = io2.withFilter2(_ == 0)
  println("Uh, oh!")
}
```

**Comment by adamgfraser** [comment]
The second attempt seems a little more promising. Part of the issue is that `NoSuchElementException` is a subtype of `Nothing` so we can widen a `UIO[A]` to an `IO[NoSuchElementException, A]` by calling `withFilter`. Though now that I think about it maybe that is okay. We have a test right now to check that can't happen but maybe that test is overly restrictive.

**Comment by regiskuckaertz** [comment]
If you add a `CanFail` evidence, it should work.

**Comment by jdegoes** [comment]
We can widen `UIO[A]` to any error type. It's ok. You can treat an effect that cannot fail as if it were an effect that can fail. You just can't do the reverse.

**Comment by adamgfraser** [comment]
Good point. I will push a fix for this in a minute.

**Comment by jdegoes** [comment]
I am not sure there is a type soundness issue here.

What's happening is that error type is widening to `Any` when the errors are unrelated to `NoSuchElementException`. I think that's expected. We could probably engineer it to "stop" widening up to, say, `Throwable`. Although in a lot of places errors will auto-widen to `Any` if they are unrelated (e.g. `flatMap`).

**Comment by adamgfraser** [comment]
@jdegoes That's fair. It doesn't result in code that is unsound in that something isn't of the right type, it can just lead to lack of any type information about the error type if they are unrelated. I've got a fix ready right now that requires `E >:> NoSuchElementException`. Do we want to go with that or are we over-engineering this and we should just allow arbitrary types?
