### ISSUE TITLE
Add ZIO.fromFutureInterrupt

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2419]
Add a method `ZIO.fromFutureInterrupt((ec: ExecutionContext) => ... : Future[A])`, which passes it a specially crafted `ExecutionContext`, which will disable `submit` when the parent ZIO effect has been interrupted. This will allow interruption of running `Future`, albeit without any guarantee of resource cleanup, and without any interruption between async boundaries.

**Comment by iravid** [comment]
Very clever @jdegoes!!

**Comment by regiskuckaertz** [comment]
wow 🙌

**Comment by adamgfraser** [comment]
I will work on this.
