### ISSUE TITLE
Add ZIO.tapBoth variant that accepts one parameter via an Either[E, A]

### ISSUE THREAD

**Issue by kusamakura** [zio/zio#2427]
I usually find that I write a lot of `ZIO.tapBoth(e => log(e), a => log(a))` when testing or debugging. To remedy the duplication, I wrote an extension method:
```scala
def tapBoth_[R1 <: R, E1 >: E](f: Either[E, A] => ZIO[R1, E1, Any]): ZIO[R1, E1, A] = {
  self.tapBoth(e => f(Left(e)), a => f(Right(a)))
}
```

If anybody thinks this is useful enough, I would be happy to open a PR with this addition.
With regards to naming, an alternative could be `tapBothEither`, which I think is much clearer.

**Comment by adamgfraser** [comment]
This has been implemented now.
