### ISSUE TITLE
Verify the correctness of Stream.halt and Stream.catchAll

### ISSUE THREAD

**Issue by vasilmkd** [zio/zio#2429]
Running the following code:
```scala
testM("Stream.halt is safe to pull again") {
  Stream
    .halt(Cause.fail("Ouch"))
    .catchAll(_ => Stream.succeed(5))
    .process
    .use(nPulls(_, 3))
    .map(assert(_, equalTo(List(Left(Some("Ouch")), Left(None), Left(None)))))
}
```

results in this output:
```
[info] - StreamPullSafetySpec
[info]   - Stream.halt is safe to pull again
[info]     List(Right(5), Left(None), Left(None)) did not satisfy equalTo(List(Left(Some(Ouch)), Left(None), 
Left(None)))
```

Notice that I'm using `catchAll` and not `catchAllCause`.

This seems off to me. @iravid Wdyt?

Edit:
This also happens with this code, so it might be desired, it just feels a bit counter intuitive to me, but I may be wrong.

```scala
ZIO.halt(Cause.fail("Ouch")).catchAll(str => UIO.effectTotal(println(str)))
```

Feel free to close this issue if this is the intended behavior.

**Comment by iravid** [comment]
ZIO.halt(Cause.fail(a)) is equivalent to ZIO.fail(a) (check the definitions)
