### ISSUE TITLE
Fibers' `onTermination` effects are only run on sbt `exit`

### ISSUE THREAD

**Issue by mtsokol** [zio/zio#2436]
@adamgfraser So here's the code snippet with sbt output, thanks once again for looking at this together 🙂 

For such program:
```scala
import zio._
import zio.console.Console.Live.console

object Example extends App {

  def run(args: List[String]): ZIO[ZEnv, Nothing, Int] =
    myAppLogic.as(0)

  val myAppLogic =
    for {
      fib <- IO.never.onTermination(_ => console.putStrLn("First")).fork
      _   <- fib.interrupt
      _   <- IO.never.onTermination(_ => console.putStrLn("Second")).fork
    } yield ()
}
```
The output is:
```
[info] Running Main
First
[success] Total time: 1 s, completed Dec 7, 2019 12:12:28 AM
```
So after completing the run the second `onTermination` is not executed?

And the rest is completed after sbt `exit` (here accumulated after few runs):
```
sbt:zio-workspace> exit
[info] shutting down server
Second
Second
Second
Second
```
[EDIT] Also after trying few times the output sometimes is with hanging sbt:
```
sbt:zio-workspace> run
[info] Compiling 1 Scala source to /Users/mateusz/IdeaProjects/play-json-workspace/target/scala-2.12/classes ...
[info] running Example
First
[success] Total time: 2 s, completed Dec 7, 2019 12:36:16 AM
sbt:zio-workspace> exit
[info] shutting down sbt server
[warn] Thread[Thread-4,5,run-main-group-0] loading zio/App$$anon$1.class after test or run has completed. This is a likely resource leak
```

**Comment by jdegoes** [comment]
You aren't interrupting the 2nd one, which means it is only being run when the JVM is shutdown, via the shutdown hook installed by `zio.App`. SBT controls when that JVM is terminated.

Maybe we could add a method `zio.App.forceShutdown` to do the same thing that's happening right now when the JVM is shutdown. That'd probably be a good ticket!
