### ISSUE TITLE
Use immutable collections in api descriptions

### ISSUE THREAD

**Issue by t3hnar** [zio/zio#2451]
`scala.collection.Iterable` & `scala.collection.Seq` are used in many places in ZIO api Which are interfaces for both mutable and immutable collections. This allows developers to pass mutable collection, there after mutation of passed collection may lead to undesired and hard-to-trace behaviours.

**Comment by t3hnar** [comment]
this addresses this issue https://github.com/zio/zio/pull/2441

**Comment by guizmaii** [comment]
@t3hnar Is this still an issue in ZIO2? Can we close this ticket?
