### ISSUE TITLE
ZIO Core: Make all effect constructors lazy in all parameters

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2462]
All effect constructors (`succeed`, etc.), including those in modules like `Console`, should utilize by-name parameters. The rationale is that people accidentally put side-effects into parameters, and it's better to attempt to make these side-effects lazy than result in confusing behavior.

For pure code, it makes no difference anyway.

```scala
for {
  _ <- blocking(putStrLn(Thread.currentThread().getName))
} yield ()
```

An effect constructor is any method appearing in any companion object that takes simple parameters and returns an effect (`ZIO`, `ZStream`, `ZSink`, `STM`, etc.).

**Comment by saraiva132** [comment]
I can do this

**Comment by adamgfraser** [comment]
Awesome!

**Comment by saraiva132** [comment]
Should a parameter of type `Iterable[ZIO[R1, E, A]]` also be by-name ?

**Comment by saraiva132** [comment]
Effects that get by-name parameters:

- [ ] IO
- [ ] ZIO
- [ ] UIO
- [ ] RIO
- [ ] URIO
- [ ] TASK
- [ ] ZManaged
- [ ] Managed
- [ ] ZStream
- [ ] ZStreamChunk
- [ ] ZSink
- [ ] Pull (ZIO alias)

Methods (Not all effects have all of these methods):

- succeed
- fail
- die/ dieMessage
- effect/effectTotal  
- left/right/some
- fromTry/fromEither/fromOption/ fromFiber.
- halt
- done
- interruptAs
- sleep

Eager variant will add the sufix `Now`. Example `succeedNow`

## Service Modules

-  **Clock**: currentTime and sleep
-  **Console**: putStr and putStrLn
-  **Random**: nextBytes, nextInt, nextLong and nextString
-  **System**: env and property

**Comment by adamgfraser** [comment]
I think this generally seems like a solid plan. A couple of thoughts:

1. We probably don't need `now` variants of all of these methods but only ones that are used in internal combinators with some regularity.
2. I think there are some other combinators that we need to make lazy. `when` in particular has generated several questions.

I would suggest we open a PR with initially a relatively narrow focus, say just `ZIO.scala` as we did with the previous work on `final` methods to see what this looks like in practice and then once we have alignment we can move on to the rest of the codebase.

**Comment by saraiva132** [comment]
@adamgfraser I was starting to work on a PR just for ZIO. But was interrupted by a lot of things. Which methods would you say do not require an eager variant ? We can also do it step by step and add as things make sense.

**Comment by adamgfraser** [comment]
My initial hypothesis would be that methods that directly construct a subtype of `ZIO` or construct a `ZIO` from one of our internal types (e.g. `succeed`, `fail`, `halt`) should have eager variants and the other ones don't need it. We might approach it by initially changing everything to be lazy and then seeing which non-lazy methods we need so we're not unnecessarily calling lazy versions all the time in internal combinators.

**Comment by saraiva132** [comment]
@adamgfraser @jdegoes 

[This](https://github.com/databricks/scala-style-guide#call_by_name) is worrying me a bit. 

I believe we do not suffer from this since our data types that hold computations express the laziness with () => Input instead of just typical by-name. And I am sure this was taken into consideration. But wanted to make sure.

**Comment by adamgfraser** [comment]
@saraiva132 Just wanted to check in on this since it is one of the gating items for the 1.0 release. Let me know if you want to work together on anything here.

**Comment by saraiva132** [comment]
@adamgfraser This week was quite busy at work so I had no space to work on this. I will work on this this weekend. I will have the time. I suppose we will be able to cooperate in the next two days. Tonight I am afraid I will use it to rest as well.

**Comment by adamgfraser** [comment]
@saraiva132 No worries at all. Sounds great!

**Comment by adamgfraser** [comment]
Discussed this with @saraiva132 and I will pick this up.
