### ISSUE TITLE
Incomplete Scaladoc on effectAsync methods

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#2471]
The description for parameter `blockingOn` is not documented for `ZIO.effectAsync`, `ZIO.effectAsyncInterrupt` and `ZIO.effectAsyncMaybe`.

**Comment by ajaychandran** [comment]
@jdegoes Hi, could you provide a description for the parameter? What does this mean for the async effect if the fiber fails?

**Comment by jdegoes** [comment]
The parameter is a hint as to which fibers may ultimately complete the async callback.

**Comment by ajaychandran** [comment]
Thanks for the info.
