### ISSUE TITLE
Adding ZStream combinator that keeps pulling elements while ignoring state

### ISSUE THREAD

**Issue by saraiva132** [zio/zio#2481]
A while back I saw someone interested in having a combinator in ZStream that would not require you to handle state but keep pulling elements of the stream, so using `unfold` or `paginate` would be awkward. 

@adamgfraser suggested a potential combinator with the name `fromPullRepeat` like:

`def fromPullRepeat[R, E, A](pull: ZIO[R, Option[E], A]): ZStream[R, E, A]`

I guess this would be a nice addition. cc @iravid

**Comment by iravid** [comment]
This is exactly `ZStream.fromPull` :-) Perhaps we should rename it to `ZStream.repeatPull`?

**Comment by adamgfraser** [comment]
Ah, sorry about that. I thought `fromPull` just lifted a single effect into a `ZStream`. Yes, I think we could use something to clarify here because even looking at the implementation it can be a little confusing with the overloading of `ZStream.apply`, or at least it was for me. `repeatPull` would be shorter and more consistent with existing combinators like `repeatEffect`.

**Comment by saraiva132** [comment]
And I am on it :D `fromPull` also mislead me to believe the same so I guess `repeatPull` will make it more clear that you will keep pulling from the stream using provided `ZIO[R,Option[E],A]`

**Comment by saraiva132** [comment]
Actually, there is a distinction between `ZStream.fromEffect` and `ZStream.repeatEffect`. We could perhaps change current `ZStream.fromPull` to `ZStream.repeatPull` and add a `ZStream.fromPull` that creates a single element stream from a pull. Might not make sense though since there is `ZStream.fromEffect` already.

**Comment by adamgfraser** [comment]
Yes, I think we rename the existing `ZStream.fromPull` to `ZStream.repeatPull` and then I suppose for consistency we could add a `ZStream.fromPull` that optionally emits a single element.

**Comment by iravid** [comment]
Cool, just make sure to migrate all existing usages of fromPull
