### ISSUE TITLE
Fix Broken Links in Documentation and Enable CI

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2485]
I noticed that we have a decent amount of our Scaladoc that is not linking correctly. See [here](https://circleci.com/gh/zio/zio/46387?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for an example. This ticket is to fix all of these so that no more warning are generated and change CI settings so that a warning fails the build to prevent future regressions.

**Comment by laurynasl-wix** [comment]
I've opened a pr for this: #2513

**Comment by adamgfraser** [comment]
Great! Will take a look.

**Comment by laurynasl-wix** [comment]
@adamgfraser The pr was merged, is there something more to do here?

**Comment by adamgfraser** [comment]
@laurynasl-wix No, sorry. Closing now.

**Comment by adamgfraser** [comment]
Closed by #2513.
