### ISSUE TITLE
Site: More user-friendly layout wanted for mobile devices

### ISSUE THREAD

**Issue by plokhotnyuk** [zio/zio#2491]
Here is how it looks now:
![image](https://user-images.githubusercontent.com/890289/71110973-a98d3180-21c8-11ea-850b-ea5a130a6e14.png)

**Comment by ghostdogpr** [comment]
You're right! There's already an issue for it though: #1621 so I'll close this one as a duplicate.
Always hard to get this done as most of us are better with Scala and backend stuff than CSS and frontend.
