### ISSUE TITLE
ZIO Test: Create test annotation for "ignored" tests

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2498]
Users would like to know which tests were ignored in a given run. So we could keep track of those ignores and render them something like `ignored: 1` (or `ignored: 24` for a suite-level rendering).

To add a test annotation and renderer, the following process must be followed:

1. Add a new TestAnnotation, one which counts ignored tests
2. Access the test annotation from within the `ignore` `TestAspect`
3. Define a new renderer for the TestAnnotation
4. Compose the new renderer with the default test annotation renderer

Am I missing anything, @adamgfraser?

**Comment by adamgfraser** [comment]
@jdegoes I'm on it!
