### ISSUE TITLE
ZIO Test: Create new test annotation for retried tests

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2499]
Users would like to know how many times a test had to be retried before it succeeded (with, e.g. `flaky` combinator). So we could keep track of those retries and render them something like `retried: 1` (or `retried: 24` for a suite-level rendering).

To add a test annotation and renderer, the following process must be followed:

1. Add a new TestAnnotation, one which counts retried tests
2. Access the test annotation from within the `flaky` `TestAspect`
3. Define a new renderer for the TestAnnotation
4. Compose the new renderer with the default test annotation renderer

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by adamgfraser** [comment]
Closed by #2502.
