### ISSUE TITLE
ZIO Test: Create new test annotation for repeated tests

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2500]
Users would like to know how many times a test was repeated (with, e.g. `nonFlaky` combinator). So we could keep track of those repetitions and render them something like `repeated: 1` (or `repeated: 24` for a suite-level rendering).

To add a test annotation and renderer, the following process must be followed:

1. Add a new TestAnnotation, one which counts repeated tests
2. Access the test annotation from within the `nonFlaky` `TestAspect`
3. Define a new renderer for the TestAnnotation
4. Compose the new renderer with the default test annotation renderer

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by adamgfraser** [comment]
Closed by #2502.
