### ISSUE TITLE
ZIO When evaluate always the condition.

### ISSUE THREAD

**Issue by politrons** [zio/zio#2506]
Hi all, we detect that having a `ZIO.when` condition in our for comprehension, even when the condition is false is evaluating the ZIO.fail. Any idea what's happening here?   I  notice that ZIO.success is not lazy, and I guess with fail happen the same, but the weird part is that condition is always evaluated.

`           _ <- ZIO.when(!isValidAccessToken(accessToken))(ZIO.fail(unauthorizedErrorRoute))
`

Regarda.

**Comment by adamgfraser** [comment]
@politrons I'm not sure I understand the issue. The snippet below seems to be working correctly for me. Are you saying you are using side effecting code within `fail`?

```scala
import zio.test._
import zio.ZIO

object ExampleSpec extends DefaultRunnableSpec {

  def spec = suite("Example")(
    testM("when") {
      for {
        _ <- ZIO.when(false)(ZIO.fail("fail"))
      } yield assertCompletes
    }
  )
}
```

**Comment by politrons** [comment]
if I run this basic code

```
  @Test
  def zioErrorWhen(): Unit = {
    main.unsafeRun((for {
      _ <- ZIO.when(false)(ZIO.fail {
        println("Why this happens?")
        new IllegalArgumentException()
      })
      _ <- ZIO.effect(println(s"${Thread.currentThread().getName} ZIO"))
    } yield ()).catchAll(_ => ZIO.succeed(println("Control async effects"))))
  }
```

This is printed

```
Why this happens?
main ZIO
```

I dont know why the         `println("Why this happens?")` but not the throwable.

If I change the false by true, then the throwable is propagated with the ZIO.fail and the output of the program is


```
Why this happens?
Control async effects
```

**Comment by saraiva132** [comment]
@politrons `succeed`, `fail`, etc are methods that should lift pure values and thus are eagerly evaluated. We are working towards making this more clear potentially providing and eager and lazy approach. **You should not have side-effectful code when calling these methods.**

**Comment by politrons** [comment]
ok with that, but even if they are not lazy, why if the condition is false, the code is still evaluated?

**Comment by adamgfraser** [comment]
@politrons To follow up on what @saraiva132 said, the issue here is that `fail` is meant for creating a failure from a value that doesn't have any side effects. To get the behavior you want you can do something like:

```scala
import zio.test._
import zio.ZIO

object ExampleSpec extends DefaultRunnableSpec {

  def spec = suite("Example")(
    testM("when") {
      for {
        _ <- ZIO.when(false) {
          for {
            _ <- ZIO.effectTotal(println("Why this happens?"))
            _ <- ZIO.fail(new IllegalArgumentException)
          } yield ()
        }
      } yield assertCompletes
    }
  )
}
```

**Comment by politrons** [comment]
Thanks for the solution
