### ISSUE TITLE
Two Bad Things about the repo

### ISSUE THREAD

**Issue by duobei** [zio/zio#2507]
1. So large size.
After cloned the repo,  it's weird that assets path takes 118M , total size is 185M.

2. Messy code paths.
Under the repo root, there are 5 paths related test:
core-tests
streams-tests
test
test-sbt
test-tests

Zio is great, but it could be better.

**Comment by adamgfraser** [comment]
@duobei Thanks for the feedback!

On the size, I think that is being driven by some of the media assets. Not sure if we could host those somewhere else and link to them.

On the organization, we have an entire testing library in ZIO Test and an SBT integration module for that, so two of the "test related" paths are user facing projects. The other three are test modules for the three main projects (ZIO Core, ZIO Streams, and ZIO Test). We find it helpful to have separate projects for tests and for each of the three projects.

**Comment by jdegoes** [comment]
I think we could have `zio-media` and move all the media assets there. That's the bulk of the size right there. To do it properly we would purge the binaries from the history...
