### ISSUE TITLE
ZIO Test: Improve Usability with Ammonite

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2510]
Following up on discussion on Discord, the experience running ZIO Test specs from Ammonite is not great because although the specs can be run using their main methods, on completion the spec will exit the interactive session. This doesn't occur in in SBT because SBT traps that exit and throws a `SecurityException` which we then catch [here](https://github.com/zio/zio/blob/2aca6773ad471af04b986f73bff19100caea31b2/test/shared/src/main/scala/zio/test/RunnableSpec.scala#L58).

I haven't worked with Ammonite much so very open to suggestions here. The constraint is that I think we need to maintain the default behavior as exiting with a failure exit code so that we signal to tools like CI that tests have failed. One idea would be to take a command line argument like `-i` for interactive sessions that prevents the exit behavior. Another would be to see if there is some kind of environment variable we can access to indicate we are in an Ammonite session.

**Comment by psilospore** [comment]
>Another would be to see if there is some kind of environment variable we can access to indicate we are in an Ammonite session.

Would this help
```
amm --code "println(sys.env.filter(_.toString.contains(\"amm\")))"
Compiling /Users/syedajafri/dev/rules_scala/scripts/(console)
Map(JAVA_MAIN_CLASS_19131 -> ammonite.Main)
```

**Comment by adamgfraser** [comment]
Yes, it looks like that could give us what we need!
