### ISSUE TITLE
Better Organization for ZIO Test Documentation

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2518]
As ZIO Test grows we need to continue to upgrade the quality of our documentation. One issue we have right now is that existing documentation is split between two locations on the website ("Use Cases - Testing" and "How To - Test Effects") and neither of these are necessarily particularly obvious. What do people think about creating new categories on the main navigation bar at the top of the page for ZIO Stream and ZIO Test and then we can move all documentation for those projects below that?

**Comment by ghostdogpr** [comment]
I agree, I think they even deserve their own microsite but a dedicated category is good too. One thing to check is whether it looks okay if there so many categories and they don’t fit in one line.

**Comment by DanielBlanco** [comment]
This happened to me today because the documentation is not 100% clear and easy to follow.

I was creating my test suite like this:
```
  def spec =
      suite("SampleSpec")(tests: _*)
        .provideCustomLayerShared(ExpensiveLayer.live)
        .mapError(TestFailure.fail) @@
        before(zio.console.putStrLn("suite-before")) @@
        after(zio.console.putStrLn("suite-after")) @@
        sequential
```
getting:
```
A-before
A
A-after
B-before
B
B-after
suite-before
suite-after
suite-before
suite-after
```
instead of:
```
  def spec =
    (
      suite("SampleSpec")(tests: _*) @@
        before(zio.console.putStrLn("suite-before")) @@
        after(zio.console.putStrLn("suite-after")) @@
        sequential
    ).provideCustomLayerShared(ExpensiveLayer.live).mapError(TestFailure.fail)
```
that gets what I wanted:
```
suite-before
A-before
A
A-after
suite-after
suite-before
B-before
B
B-after
suite-after
```
And there is still things that I need to learn by reading the zio-test code.

Having said that, I want to help on improving the site but I'm not sure where to start.

**Comment by adamgfraser** [comment]
That would be great! I think first step is getting everything in one place and more organized. I have a branch I have been working on for that. Let me clean it up and push something and then would be great to get your help!

**Comment by khajavi** [comment]
This issue seems to have been resolved. If it is still valid, please open it.
