### ISSUE TITLE
Interrupt Fiber as ZManaged release 

### ISSUE THREAD

**Issue by 7robertodantas** [zio/zio#2537]
Hi,

I have a scenario where I'd like to keep a fiber in background sending ttl check to a consul registration every second. Since I'm using `ManagedApp` instance I was trying to wrap this fiber into a ZManaged, thus calling the Fiber's interrupt method as the release method. 

Turns out that the fiber is not being interrupted / cancelled. Is this a bug or am I missing something?

The following is a minimal reproducible example (ammonite):

```scala
import $ivy.`dev.zio::zio:1.0.0-RC17`

import zio._
import zio.console._
import scala.concurrent.duration._
import zio.duration.Duration

val repeateble = putStrLn("ttl") repeat Schedule.fixed(Duration.fromScala(1.second)).unit
val managed = ZManaged.make(repeateble.fork)(_.interrupt)
val io = managed.use(_ => putStrLn("Use"))

val rts = new DefaultRuntime {}
rts.unsafeRun(io)
````

The output is the following:

```
Use
ttl
ttl
...
ttl
ttl
```

**Comment by iravid** [comment]
This is an (unfortunately) common pitfall. Fibers inherit the interruptibility status of the region from which they are forked. In your example, you're forking the fiber from an uninterruptible region (in ZManaged's acquire). Thus, the fiber is running in an uninterruptible state and cannot be interrupted.

There's a much shorter pattern you can use:
```
val managed = repeatable.toManaged_.fork
```

This will fork the `repeatable` IO in an interruptible state and interrupt it on release.
