### ISSUE TITLE
Update contributing guidelines with coding rules and recommendations.

### ISSUE THREAD

**Issue by saraiva132** [zio/zio#2549]
Triggered by #2509 and #2463

Closes  #190, #335, #2462, #2512 

## Possible formats

- https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
- https://docs.scala-lang.org/style/
- https://github.com/databricks/scala-style-guide

## Scalafix project inspiration

- https://github.com/scalaz/scalazzi
- https://github.com/alejandrohdezma/sensitive-strings
- https://github.com/scalatest/autofix
- https://github.com/pdalpra/scalalint

## Solution

Some rules will be able to be automated and others will remain as general guidelines

- Documentation with expectations about how things should look.

- Scalafix CI and plugin automation to make sure the rules are followed by existing and future code.

### Extensions:

1. value classes must be final and extend AnyVal.
2. method extension classes must be final and extend AnyVal
3. Sealed traits that are ADTs should extend from Product with Serializable.
4. Regular traits and sealed trait that do not form ADTS should extend from Serializable but not from Product.
5. Multiple parameter classes that are ADT should be case class and not extend AnyVal
6. Traits should always extends serializable

### Final definitions

1. All methods on classes / traits declared final, by default
2. No methods on objects declared final
3. No methods on final classes declared final
4. All classes inside objects should be defined final
5. All final classes have private constructors & constructor parameters
6. All vals declared final, either in objects or final classes, if they are constant expressions and without type annotations.
7. Private methods/vals not declared final since they are already final
8. Package-private vals/methods declared final

### Refactor

1. If a class has all final members, class declared final & final member annotations removed
2. use least powerful type alias

### Naming of parameters

1. partial function are called `pf`
2. evidences are called `ev`
3. promise are called `p` (unless in its own class methods, in that case it is called `that`)
4. functions are called `fn`, `fn1`, unless they bear specific meaning: `use`, `release`, ..
4. consider _ method having more meaningful names
5. iterable are called `in`
6. when a parameter type equals own (in a method of a trait) call it `that`
7. please, PLEASE, only use  by name parameters if it makes sense. mind the Function[0] extra allocation and loss of clean syntax
8. folds initial value are called `zero`

### Misc

1. GADTS should have type annotation.
2. Type alias should have type annotation.
3. Methods that lift pure values to effects are dangerous. Dangerous in the sense that they can potentially have dangerous side-effects. Such methods should have a default lazy variant and an eager variant for advanced users that are aware they absolutely do not have side-effects in their code, having slight gains in performance. The lazy variant should have a normal name (succeed, fail, lift, potato) and the eager variant should have a now suffix (succeedNow, liftNow, potatoNow) which makes it clear of its eager behaviour.      

### Code structure

1. Method alphabetization - add lazy vals to fix forward references.
2. Sorting of imports

**Comment by iravid** [comment]
Appreciate the work that went into compiling this list! Any ideas on how are we going to enforce these over time? As a reviewer I have no ability to keep all these in mind.

**Comment by saraiva132** [comment]
For now. I am enforcing all of this in the existing codebase in incremental PRS. I took my time to learn the entire codebase, how things look in one part and on the other. What are the differences. We want users to have expectations about how things look like. Things to be predictable.

Regarding how to enforce this? I am afraid there are only two possibilities:

1.  Refer people to the coding guidelines. This implies the rules need to be segmented in a way that its easy to quickly find what you need. We do not want to scare new contributors with too many rules.
2. Maintainers have this in mind. I think @adamgfraser is someone who is capable of that. I believe I am as well. But that is because this things are important to me, I admit.

**Comment by adamgfraser** [comment]
Thanks for working on this! I think it is great to be focusing on code quality as we grow and something like this can reflect our collective wisdom.

A couple of suggestions.

First, I think it could be good to distinguish objective technical rules we want to enforce from more subjective recommendations or suggestions. Going down your list it seems like there is a rough continuum from top to bottom with very objective things like usage of `final` modifier at the top and then more subjective things like naming of certain kinds of parameters that are more for consistency and then just things to think about at the bottom. It is great to have all of those but distinguishing them could help reviews and contributors focus on a smaller set of "must haves".

Second, I think if you are going to spend time on this it could be good to look into using Scalafix to automate some of these rules. Checking them could then be included in our CI process. This might both give you more leverage, since you can implement the rule once and then apply it across the entire code base, force us to think through the rules more, and provide a more scalable way for us to maintain some of them.

**Comment by saraiva132** [comment]
The idea to use scalafix to automate as much as possible is gold. For now, this exploration was important because it allowed me to learn, understand, and identify what should stay and what should go.

**Comment by softinio** [comment]
Another thought I had was to fork and enhance this plugin to include in our projects: 

https://github.com/scalaz/scalaz-plugin

**Comment by saraiva132** [comment]
Sounds like a project I would love to do! This recommendations are amazing.
