### ISSUE TITLE
Add support for non-empty list with ZIO.foreach (or ZIO.collectAll and similar operations)

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio#2554]
As of now, passing a nonEmptyList (which can be `scala.collection.immutable.::[A]`) to `ZIO.foreach` (or `ZIO.collectAll` and similar operations if any) returns a `List` which would mean it could be empty. However, in practice, passing a non-empty list to such operations can never yield an empty list. 

Hence, it is a good idea if ZIO could support a `collectAll` or `foreach` operation that can operate on `::` and returns a `::`

**Comment by afsalthaj** [comment]
If we are happy with this issue, I can take it up myself.

**Comment by adamgfraser** [comment]
To a certain extent this is raising the issue again of us not having a `Traverse` type class or another way to abstract over various collection methods. We already have another PR to add variants of these for `Option`, we want to add variants for `Chunk`, and potentially over time we will want the same thing for other methods that operate on collections like `partitionM`.

In the short term I agree the straightforward solution is just to add variants for this but may be worthwhile to think about if there is something else we can do here.

**Comment by saraiva132** [comment]
@afsalthaj @adamgfraser Indeed. I think there needs to be some careful thinking on our APIs that have iterables as input can be improved. For instance #2451 

I am unsure what is the direction to go but, just the fact we are accepting mutable data structures as input is enough to raise a red flag.

**Comment by afsalthaj** [comment]
@adamgfraser 
One of the thoughts that I have at this point is why would we even want to call certain zio functions (`zio.foreach`, `zio.collectAll`) with a empty collection at all, while we know its difficult to impose non-emptiness with the collection hierarchy. Correct me if I am wrong, that, let's make some functions support only non-emptiness?

From a user's perspective, it is difficult to form a non-empty version of the iterable to form, however, it will still be acceptable, given the fact we are trying to avoid computations that are invalid with the help of types.

Your view on `Traversable` type class is very interesting.  Having variants of `::` and `Chunk` could be abstracted out as single functions.

However, `Option` gets into the same question of why `foreach` on `None`. `ZIO.fromOption(opt).flatMap(ZIO.effect(...))` could be an alternate ?

**Comment by adamgfraser** [comment]
@afsalthaj I think the issue with that is that a lot of times we don't know if the list is empty or not. We just have a `List[A]` that could be empty or not, just like we have an `IO[E, A]` that could fail or not. Unless we know at compile time that the list is empty, which I think is pretty rare, I think we want to support operations on it. Otherwise we are forcing the caller to deal immediately with the possibility of the list being empty when often they will want to defer that to a higher level of the application.

**Comment by afsalthaj** [comment]
@adamgfraser Agree. Makes sense. 
Seems like a hard requirement for many users and and more code handling simple usecases.
That said, personally I prefer using `NonEmptyList` whenever I can. The `NonEmptyList` in core functional libraries have been a great help in getting rid of bugs (by early handling of them) . 

`::` is kind of tricky, as it doesn't have useful functions such as 
```scala
NonEmptyList.fromList(List())
// res6: Option[cats.data.NonEmptyList[Nothing]] = None

NonEmptyList.fromList(List(1,2,3))
// res7: Option[cats.data.NonEmptyList[Int]] = Some(NonEmptyList(1, 2, 3))

```

**Comment by regiskuckaertz** [comment]
All the combinators receiving `NonEmpty*` would sit well in the interop-cats project, imho.

**Comment by adamgfraser** [comment]
@afsalthaj One thing we could think about is having some helper methods for that. For example:

```scala
object NonEmptyList {
  def fromList[A](as: List[A]): Option[::[A]] = ???
```

This wouldn't require a type class or anything like that and would just be normal functions. I'm not sure it is worth it just for ZIO Core / Stream / Test but could be make sense if other ZIO libraries are using nonempty lists significantly more.

**Comment by afsalthaj** [comment]
@adamgfraser  I missed out the conversation, though I learned this is taken up through discord channels. Thanks a lot again !

**Comment by adamgfraser** [comment]
This has been implemented now.
