### ISSUE TITLE
Add debounce support

### ISSUE THREAD

**Issue by reibitto** [zio/zio#2565]
I brought this up on Discord, but there are more design decisions to be made than I initially expected so having an issue to sort everything out for organization's sake is probably a good idea.

So basically what I was initially was looking for is debounce on ZIO itself. Something like:

```scala
def debounce(waitTime: Duration): URIO[Clock, ZIO[R, E, Option[A]]]
```

But then it seems like you'd also want versions on the ZIO companion object too:

```scala
def debounce1[R, E, A, T](f: T => ZIO[R, E, A], waitTime: Duration): URIO[Clock, T => ZIO[R, E, Option[A]]]
```

and `debounce2`, `debounce3`, etc... which is kind of awkward. Plus a ZIO returning another ZIO isn't very ergonomic in the first place.

Maybe it's better to forget that route and focus just on the ZIO Streams case? Adding debounce on streams generalizes better I think.

There is one additional issue where there are multiple interpretations of what `debounce` should do. For example, lodash and a few other libraries have a "leading" and "trailing" option. I found some diagrams which might be helpful visualizing this:
https://medium.com/@ellenaua/throttle-debounce-behavior-lodash-6bcae1494e03

Do we want to support all these? If not, which one should be the default implementation?

Any other ideas or things to think about?

**Comment by gchudnov** [comment]
It looks like a  variant of `throttleEnforce` in zio. Am I correct?

**Comment by reibitto** [comment]
@iravid Can you re-open this since that PR got reverted?

An update from me:

I solved my particular problem defining a non-streams debounce like so:

```scala
def debounced[R, E, A](waitTime: Duration): UIO[ZIO[R, E, A] => ZIO[R with Clock, Nothing, Fiber[E, A]]] =
  Ref.make(Option.empty[Fiber[E, A]]).map { previousRef => (f: ZIO[R, E, A]) =>
    for {
      _ <- ZIO.whenCaseM(previousRef.get) {
            case Some(previous) => previous.interrupt
          }
      fiber <- f.delay(waitTime).fork
      _     <- previousRef.set(Some(fiber))
    } yield fiber
  }
```

This is working for me. If there is interest, I'd be willing to make a PR for it. But I'm not sure there is much demand for a non-streams version like this. It's not as ergonomic as a streams version would be.

It's possible to re-use this to implement the streams version, but I imagine a more elegant solution exists.

If somebody needs a streams `debounce` more urgently than I do, feel free to take this issue before me.

**Comment by reibitto** [comment]
There's a related PR by @luis3m  #3574

**Comment by reibitto** [comment]
There is also a race condition to consider. Here's what I did to address that:

```scala
def debounced[R, E, A](waitTime: Duration): UIO[ZIO[R, E, A] => URIO[R with Clock, Fiber[E, A]]] = {
  RefM.make(Option.empty[Fiber[E, A]]).map { previousRef => (f: ZIO[R, E, A]) =>
    previousRef.modify {
      case Some(previous) => previous.interrupt *> f.delay(waitTime).fork.map(a => (a, Some(a)))
      case None           => f.delay(waitTime).fork.map(a => (a, Some(a)))
    }
  }
}
```

**Comment by luis3m** [comment]
Just submitted https://github.com/zio/zio/pull/3580

**Comment by adamgfraser** [comment]
This has been implemented now.
