### ISSUE TITLE
Should We Have ZIO Test Magnolia Project for Deriving Generators?

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2570]
I have gotten a couple of requests for support for automatically deriving generators for algebraic data types and I believe @ghostdogpr has implemented a version of this in one of his projects, so I think we should discuss whether it makes sense to have a subproject to provide this functionality to users who want it.

We are already using Magnolia to do derivation for ZIO Config and it would be a separate module so we wouldn't be forcing a dependency on anyone. The main downside I see is that I believe when deriving a generator for an algebraic data type we would need to use some "canonical" generator for types such as `Int`, `String`, `List`, and so on, which to a certain extent goes against the ZIO Test design philosophy of explicit generators and that there is not a "one size fits all" generator for a type. At the same time, this would all be opt in and users could always fall back to the existing combinators in ZIO Test if they wanted more fine grained control of their generators.

What do others think?

**Comment by ghostdogpr** [comment]
How about ZIO Test being moved to its own repo? That way adding modules like this one wouldn’t affect the size of the zio project.

**Comment by neko-kai** [comment]
@ghostdogpr I think we couldn't do this because of circular dependency between zio tests & zio-test?

**Comment by adamgfraser** [comment]
@neko-kai I think it would be okay because `test` depends on `core` and `streams` and then `coreTests` and `streamTests` depends on `test` so I don't think there is any circularity unless I am missing something.

@ghostdogpr I think that is definitely an idea worth thinking about but there is also some value in being able to make changes across the projects without waiting for a release. For example, I just made a change to the representation of the `TestEnvironment` that motivated a change to the encoding of services in `core` and then allowed an improved implementation of the `TestEnvironment`. We couldn't iterate that quickly if they were in separate libraries.

If we want to keep the ZIO project small we could also just have ZIO Test Magnolia be a separate project along the line of the existing `interop` projects. Or maybe we decide that keeping the repo small is not the highest priority at this point.

**Comment by neko-kai** [comment]
@adamgfraser 
> I think it would be okay because test depends on core and streams and then coreTests and streamTests depends on test so I don't think there is any circularity unless I am missing something.

Well, but that IS a circularity. if zio & zio test are separate, then for each release of ZIO it must use a previous version of ZIO Test for tests - so previous zio-test must be binary compatible with next zio-core & vice-versa. That would make binary-breaking changes pretty hard to perform, unless tests are moved too

**Comment by adamgfraser** [comment]
@neko-kai Ah, that is a great point.

**Comment by ghostdogpr** [comment]
Here's a gist with my initial implementation: https://gist.github.com/ghostdogpr/2c268f576db1c0274ee6a3d4791b081a

You can see it's quite minimal.

**Comment by adamgfraser** [comment]
@ghostdogpr Awesome! Thank you! Will work on this.
