### ISSUE TITLE
Optimize effectAsync methods on ZStream?

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#2571]
In the `ZStream.effectAsync*` methods, the current implementation requires an extra `.unit` operation when the callback is invoked. This can be avoided either by returning `Unit` after `runtime.unsafeRun` or by changing the return type of the callback function to `Any`.

@iravid @adamgfraser What do you think?

**Comment by iravid** [comment]
Sure, that'd be a good change.

**Comment by ajaychandran** [comment]
Thanks.
To minimize impact, I am gonna go with the first option.
