### ISSUE TITLE
ZIO Test: Generator for bounded strings

### ISSUE THREAD

**Issue by octavz** [zio/zio#2578]
Lots of time is necessary to generate bounded texts, there are already few solutions:

```
Gen.int(N, M).flatMap(Gen.stringN(_)(Gen.alphaNumericChar))
```
Quite long and unfriendly for beginners

Or using `Sized` which is even more unfriendly since needs fiddling with `provideSome` afte `flatMapping` on `Sized.makeService`

Or by `Gen.anyString.map(_.take(M))` which is not great either

I think it would be useful to have something like `Gen.boundedString(N,M)` that will generate strings of min N,max M size, with a a default for char generator.

**Comment by adamgfraser** [comment]
There is a little bit of a balance here between providing something that makes this specific case easier but also something that is composable. For example, what if you want to do the same thing with a `List` or a `Vector`, which also indicates that the user needs to be able to specify the generator?

One option would be to just have something like `listBounded`, `vectorBounded`, `stringBounded` and then `alphaNumericStringBounded`, with the first three taking a range and a generator as a parameter and the last one taking just a range.

Another would be to create a `bounded` combinator that takes a generator and returns a version that generates values in a range. Possibly this could be uses to implement the convenience methods above.

Anyway I will work on this and come back with something.
