### ISSUE TITLE
alias operators with Reactor/RxJava/Akka-Stream

### ISSUE THREAD

**Issue by hepin1989** [zio/zio#2584]
refs:https://github.com/zio/zio/issues/2405
As we are going to release 1.0; Hope the operators will not missing than other toolkits.

**Comment by hepin1989** [comment]
Like `switchIfEmpty`; Akka has `orElse` but the `orElse` of ZIO Stream has different behavior.

**Comment by iravid** [comment]
Hello, please clarify the purpose of the ticket to concrete action items so others can express opinions about the necessity.

**Comment by hepin1989** [comment]
Collect what ZIO stream is missing and then we could audit it and add it in zio.

**Comment by iravid** [comment]
Ok, that's pretty broad. Do you intend to compile the list yourself? Otherwise I suggest closing the ticket and opening more specific tickets for missing combinators.

**Comment by hepin1989** [comment]
@iravid I think I could make use of this one as a magnet one:)

**Comment by adamgfraser** [comment]
@hepin1989 Isn't `switchIfEmpty` just `++`?

**Comment by hepin1989** [comment]
@adamgfraser No, it only switch to the other Stream if the current one complete with empty,not contacting.

**Comment by iravid** [comment]
Closing this - if there's an operator missing, please open a specific issue.
