### ISSUE TITLE
ZIO Test: Interop with Scalacheck?

### ISSUE THREAD

**Issue by kusamakura** [zio/zio#2585]
Is there any demand for `org.scalacheck.Gen` => `zio.test.Gen` interop?
I've been using this successfully for the time being, but maybe I can publish it if needed.
I'm not sure how to go about the shrinker, though. I'd appreciate it if somebody can guide me into the right direction.

```scala
package zio.interop

import org.scalacheck.rng.Seed
import org.scalacheck.{Arbitrary, Gen => SCGen}
import zio.random.Random
import zio.stream.ZStream
import zio.test.{Gen, Sample}
import zio.{Task, ZIO}

object scalacheckz {

  def fromGen[A](gen: SCGen[A]): Gen[Random, A] = {
    Gen {
      for {
        seed <- ZStream.fromEffect(ZIO.accessM[Random](_.random.nextLong))
        result <- ZStream
                   .fromEffect(ZIO.effectSuspend[Random, A] {
                     Task(gen.pureApply(SCGen.Parameters.default, Seed(seed)))
                   })
                   .orElse(ZStream.empty)
      } yield Sample(result, ZStream.empty)
    }
  }

  def fromArbitrary[A](arb: Arbitrary[A]): Gen[Random, A] = {
    fromGen[A](arb.arbitrary)
  }

  implicit class ArbitraryOps[A](private val arb: Arbitrary[A]) extends AnyVal {
    def toZioGen: Gen[Random, A] = fromArbitrary(arb)
  }

}
```

**Comment by adamgfraser** [comment]
I think that could be good. My main focus has been on adding more built in generators to ZIO Test and in most cases it should be a straightforward process to switch from ScalaCheck combinators to their ZIO Test equivalents. But the reality is if you have a large legacy code base and have written complex custom generators it would be nice to be able to use those at least for a transition period.

Let me come back to you with more detailed thoughts on this tomorrow.

**Comment by kusamakura** [comment]
@adamgfraser Right, that's what I was thinking too. The main motivation for me to write this was when I was converting some `circe` JSON scalacheck specs to `zio-test`, since the provided JSON Gen instances weren't trivial.
