### ISSUE TITLE
Unexpected CanFail for for comprehension with pattern match

### ISSUE THREAD

**Issue by francisdb** [zio/zio#2591]
ZIO 1.0.0-RC17

```scala
def runMyThing(): ZIO[Clock, Nothing, (Queue[M], Queue[E])] = ...
def foo =
    for {
      (a, b) <- runMyThing()
    } yield (a -> b)
```

fails to compile with `This operation only makes sense for effects that can fail.`

translating the for comprehension into a flatMap or map works

discord log:
> reibittoToday at 12:32 PM
Oh hmm, that one is a tricky case I think. The pattern match on the left side seems to be the issue. I forgot, internally that uses **withFilter** I believe?

related to #2049

**Comment by adamgfraser** [comment]
@francisdb This was resolved in #2420 and will be available in the next release candidate.

**Comment by francisdb** [comment]
Aha, that explains that strange NoSuchElementException in the signature in Intellij.

**Comment by adamgfraser** [comment]
You want to close this?
