### ISSUE TITLE
add a TQueue.empty constructor

### ISSUE THREAD

**Issue by sken77** [zio/zio#2601]
I found myself needing this. I notice that `TMap` has an empty constructor but `TQueue` doesn't. is there a reason for this? If not, i would gladly add it

**Comment by adamgfraser** [comment]
I believe the issue is that queues are parameterized on a size. Were you looking for a queue with no maximum size? I think that could definitely be a good addition.

**Comment by sken77** [comment]
whats the reason for requiring a capacity? the underlying queue doesnt seem to need one

```
object TQueue {
  final def make[A](capacity: Int): STM[Nothing, TQueue[A]] =
    TRef.make(ScalaQueue.empty[A]).map(ref => new TQueue(capacity, ref))
}
```

**Comment by adamgfraser** [comment]
I think we want to support queues that are both bounded and unbounded. Queues are control flow structures where offering to a queue that doesn’t have capacity suspends so users may want queues with specific sizes, whereas for something like a Map that consideration doesn’t really apply.

**Comment by sken77** [comment]
Also, would be great to add `front/peek`, `back` and `swap`

**Comment by sken77** [comment]
I see. what do you think about the above methods? You think we still want an unbounded Queue? these are 2 separate issues now. but wanted to mention it now that i have your attention

**Comment by adamgfraser** [comment]
Yes, I think we want to support both bounded and unbounded queues. We should be able to do that with one class similar to the standard queue, either by having a unbounded queue just have a size of `Int.MaxValue` or slightly expanding the internal state that is maintains. Also think we want to add more combinators like the one you mentioned.

@mijicd Does that make sense?

**Comment by mijicd** [comment]
@adamgfraser absolutely. @sken77 feel free to tackle both of the issues (constructors and missing methods), and let me know if you need any help.

**Comment by sken77** [comment]
excellent ill get to it

**Comment by sken77** [comment]
this is done
