### ISSUE TITLE
zio-test Gen should exercise 'boundary' values

### ISSUE THREAD

**Issue by leigh-perry** [zio/zio#2613]
The following sample test should fail for `Int.MinValue`. 
```
testM("Sample property test") {
  check(Gen.anyInt) {
    i =>
      assert(Math.abs({println(i);i}), isGreaterThanEqualTo(0))
  }
}
```

However, because of `Gen`'s reliance on `Random`, in practice, this value does not get tested. Ideally, `Gen` would test all significant boundary cases to find issues like this.

At the moment, I explicitly add the boundary values via `TestRandom.feedXxx`, eg:
```
testM("Sample property test") {
  TestRandom.feedInts(0, 1, -1, Int.MaxValue, Int.MaxValue - 1, Int.MinValue, Int.MinValue + 1) *>
    check(Gen.anyInt) {
```

but it would be nice to bake these into anyInt et al.

I am happy to help implement if there is agreement.

**Comment by adamgfraser** [comment]
I tend to think this makes sense. It probably shouldn't be limited to just "boundary" values but some concept of "special" values (e.g. 0 would I think be one of these, arguably +1 and -1, etc...). Unfortunately there is no objective definition of what these "special" values are or how frequently they should be generated but I think it probably does make sense to try fo figure out some sensible approach for the "default" generators like `anyInt`.

**Comment by leigh-perry** [comment]
I normally use `TestRandom.feedInts(0, 1, -1, Int.MaxValue, Int.MaxValue - 1, Int.MinValue, Int.MinValue + 1) *>` as a good starting point.

**Comment by adamgfraser** [comment]
That makes sense to me. We should also think about doing the same thing for "default" generators for other types for consistency, not that we necessarily need to do everything in one PR.

If anyone else has thoughts about this please chime in.

**Comment by leigh-perry** [comment]
Yes, agreed... all the `anyXxxx` generators would benefit.

**Comment by regiskuckaertz** [comment]
It seems like adding support for weighted distributions, for skewing the probabilities, akin to the `frequency` function in QC and Hedgehog, is a logical generalisation for that feature?

**Comment by adamgfraser** [comment]
We have `Gen.weighted` for that so I think it is more a matter of using that in the implementation of these generators.

**Comment by regiskuckaertz** [comment]
ah, didn't see it. Yeah that makes sense 👍

**Comment by leigh-perry** [comment]
@adamgfraser Is there any progress on this? I have run into another boundary case where the `Gen.anyInt` didn't find a bug that Scalacheck did because.

I may have some spare time in a week or so to help out, if you like.
