### ISSUE TITLE
ZIO Test: Odd behaviour of equalTo(anything)

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#2616]
I am not sure whether we will want to change this or not but I just encountered something I found to be weird.

So, I understand why this is but I find the following behaviour counter-intuitive:

```scala
val test = testM("Some test") {
  for {
    foo: Foo <- loadFoo()
  } yield assert(foo, equalTo(anything))
} // Foo(bar) did not satisfy equalTo(anything())
```

The implementation of `equalTo` will compare my `foo` to `anything`.
Instead, we need to do the following:

```scala
val test = testM("Some test") {
  for {
    foo: Foo <- loadFoo()
  } yield assert(foo, anything)
}
```

**Comment by adamgfraser** [comment]
I think this is another case where our move to type checked `equalTo` is helping us out. On master:

```scala
package zio.test

import zio.test.Assertion._

object ExampleSpec extends DefaultRunnableSpec {

  def spec = test("try to do something that doesn't make sense") {
    // Does not compile
    // Found: Assertion[Assertion[Any]]
    // Required: Assertion[Int]
    assert(1)(equalTo(anything))
  }
}
```

Note that `assertCompletes` can also be helpful for these situations where you don't want to assert a specific thing but just that you have gotten to a certain point in the program execution.

**Comment by adamgfraser** [comment]
Yeah, I did a Scalafix rule to automatically rewrite all the assertions in the ZIO codebase and am going to be publishing it so that others can use as well.

**Comment by NeQuissimus** [comment]
The inheritance-based `DefaultRunnableSpec` is going to mess up way more than that for me. We have  a custom subclass of it currently, which means I'll have to rebuild that. But oh well :D

**Comment by adamgfraser** [comment]
I think it should be fairly straightforward to subclass the new `DefaultRunnableSpec`, but that is without me knowing much about what you are doing. If there is anything I can do to help let me know.

**Comment by adamgfraser** [comment]
Shall we close this?
