### ISSUE TITLE
STM.when/whenM with retry

### ISSUE THREAD

**Issue by sken77** [zio/zio#2619]
I just saw that `STM.when` and `whenM` were merged. i was wondering if we could also need `STM.whenRetry` so instead of returning `STM.unit` on the else it returns `STM.retry` that seems to be also a very common use case

**Comment by adamgfraser** [comment]
Sure. I think this could be implemented pretty straightforwardly in terms of the existing `check` combinator. How about `filterOrRetry` and `filterOrRetryM`?

**Comment by jdegoes** [comment]
How would this be different than `check`?

**Comment by adamgfraser** [comment]
I think it would just be an infix version of `check`, maybe it should just be called that:

```scala
final class ZSTM[-R, +E, +A] { self
  def check(p: Boolean): ZSTM[R, E, A] =
    if (p) self else STM.retry
```

We could also have an effectual variant.

**Comment by jdegoes** [comment]
The bad thing about this is the ordering in `a.check(b)` is actually `b` and then `a`, whereas, with `STM.check(b) *> a`, it is `b` and then `a`.

Overall I am not sure if the savings in typing is worth the added overhead of a new operator?

**Comment by adamgfraser** [comment]
That's fair. I agree it is very marginal.

**Comment by adamgfraser** [comment]
Shall we close this?
