### ISSUE TITLE
ZStream#groupedWithin Test is Flaky

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2629]
@mschuwalow Can you take a look?

```
[info] ZIO Test
[info] - StreamSpec
[info]   - Stream.groupedWithin
[info]     - group before chunk size is reached due to time window
[info]       List(List(1, 2), List(3), List(4, 5)) did not satisfy equalTo(List(List(1, 2), List(3, 4), List(5)))
```

https://circleci.com/gh/zio/zio/50278?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by mschuwalow** [comment]
I'll take a look, sorry

**Comment by adamgfraser** [comment]
No problem. It is a tricky one. Can you approve my PR marking the test as flaky so we can resolve the build failure on master?

**Comment by mschuwalow** [comment]
done, I'll push a fixed version in a bit

**Comment by adamgfraser** [comment]
Thanks!

**Comment by mschuwalow** [comment]
@adamgfraser can we close this?

**Comment by adamgfraser** [comment]
Yes.
