### ISSUE TITLE
Follow Up On New Environment Encoding

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2633]
Issue to track follow up items from #2594:

- [x] **Dotty** - ~~CI for Dotty has been temporarily disabled until lampepfl/dotty#7965 is resolved. It appears that there is a PR that will fix this lampepfl/dotty#7992. As soon as this is merged we should move to the latest nightly version of Dotty and try to resolve any outstanding issues so that we can reenable CI for Dotty.~~ Dotty support has been restored. @adamgfraser to reach out to Dotty team to resolve remaining type inference issues. lampepfl/dotty#8031
- [x] **Scala 2.13** - ~~Tests are currently not being run for Scala 2.13 because of a strange bug where platform specific source files in the `jvm` folder were not being compiled on Scala 2.13 that @jdegoes and I were unable to resolve. @softinio and @mijicd, any help in fixing this and cleaning up our build would be hugely valuable.~~
- [x] **Izumi Light Type Tag** - Replace `TypeTag` with `LightTypeTag` to address issues identified by @neko-kai.
- [ ] **Documentation** - Update documentation to reflect new environment encoding and to describe new best practices for composing modules
- [ ] **General Review and Polishing** - @jdegoes will be submitting a follow up PR to do some general polishing. Contributors should probably review changes to parts of the code base they are most familiar with to see if there is anything else that needs to be cleaned up. We should also think about if there are any areas in the code base where we can use the additional power we have to do things better.
- [ ] **Performance and test timeouts** - To address Scala 2.11 compatibility issues we had to move the implementations of services into the same object as the definition of the service and accessors. This appears to be having a negative performance impact in some cases that we do not currently understand. We need to diagnose and address this. As part of this we set the timeout for tests to be very long. We need to bring this back to 60 seconds once this issue is addressed and even now can probably shorten it.

**Comment by vasilmkd** [comment]
I manually reverted the PR that moved implementations of services in the package objects, reproducing the compilation issues on Scala 2.11, but this did not solve the test timeout issues.
