### ISSUE TITLE
Add details of twitter account to microsite & README

### ISSUE THREAD

**Issue by softinio** [zio/zio#2639]
Our twitter handle is `zioscala`

Be good to have a twitter logo with above handle that redirects to our handle on twitter for users to follow us. 

As a suggestion add this to footer near the discord logo.

Some resources: 

- https://fontawesome.com/v4.7.0/icon/twitter
- https://fontawesome.com/v4.7.0/icon/twitter

As a bonus be nice to add the same to all other ZIO repos 😄

**Comment by lvitaly** [comment]
@softinio hi, I've created the pull request for this issue. Please review 😃

**Comment by softinio** [comment]
@lvitaly Thank you!
