### ISSUE TITLE
Add a version of ZIO#ensure that can tell if the effect succeeded, failed or interrupted

### ISSUE THREAD

**Issue by thesamet** [zio/zio#2669]
Currently, there is no easy way to add a finalizer that can behave differently based on whether the effect completed successfully, interrupted or failed. I am currently achieving this with:

```
ZIO.unit.bracketExit(
  release={ (_, exit: Exit[Throwable, Unit]) => exit.untraced match {
    csae Exit.Success(_) => ...
    case Exit.Failure(Cause.Interrupt(_)) => ...
    case Exit.Failure(Cause.Fail(_)) => ...
    case Exit.Failure(_) => ...
  }},
  use={_ =>theEffect})
```

While the above seems to work, it would be nice to have a simplified API.

**Comment by adamgfraser** [comment]
I will take this.

**Comment by regiskuckaertz** [comment]
`onInterrupt`, `onError`, etc?

**Comment by adamgfraser** [comment]
I was thinking just `ensuringExit` but could also have more specialized combinators.

**Comment by regiskuckaertz** [comment]
They exist already. Perhaps should be called `ensuringOnInterrupt` instead

**Comment by adamgfraser** [comment]
Good point. Personally I think the existing names are pretty clear so we could just add `ensuringExit` if people want to specify all finalization logic in one place.

**Comment by regiskuckaertz** [comment]
I agree they make sense and ensuringExit is great; I think they will be more discoverable if we prefix them all similarly, then the intent will be crystal clear. What do you think?

**Comment by adamgfraser** [comment]
I'm neutral. Definitely has some nice symmetry but also longer and maybe an unnecessary change for marginal benefit at this point?

**Comment by thesamet** [comment]
There's another nuance for the original request for a simplified API that I'd like to clarify. It looks like there's a lot going on inside the `Cause[E]` - it is extended by cases named `Meta`, `Then`, `Both`, `Traced`, `Empty` which are unclear what they imply if they came back under the `Failure` branch of the `Exit`. From a user perspective, my natural tendency was to try to pattern-match on the `Cause`, but that doesn't seem like the way it was intended to be used given the tree structure. I then found `interrupted: Boolean`, `died: Boolean`, `failed: Boolean` that can let me know what I need. I wonder if there's an opportunity to provide a simpler data structure, or alternatively better document how `Cause` works.

**Comment by adamgfraser** [comment]
Good point. I think `interrupted`, `died`, and `failed` are the preferred approach for this case. Agreed about the need for improved documentation.

**Comment by regiskuckaertz** [comment]
I'm not sure. I'm used to `on*` because that's the convention in the javascript world, but you don't find it very often in Scala. I can only think of `future.onComplete`. The fact that @thesamet didn't see `onInterrupt` or `onTermination` is quite telling. Besides, `ensuringExit` will subsume them all.

**Comment by vasilmkd** [comment]
We have a slight inconsistency now. I believe in `ZManaged` this is called `onExit`. Also, `ZStream` would benefit from this combinator as well.

**Comment by adamgfraser** [comment]
That is a great point. I will do a follow up to rename it to `onExit` and to add to `ZStream`.

**Comment by vasilmkd** [comment]
We should decide if we want to stick with ensuring or onExit. I'm not sure what I prefer.

**Comment by adamgfraser** [comment]
I kind of like `onExit` but you are right. We should also consider that we already have `onExit` and `onExitFirst` in the wild, so if we are neutral between then using that would be the alternative that does not cause breakage for users.

**Comment by adamgfraser** [comment]
Just pushed a PR for the renaming. I left adding `onExit` to stream out of that one because it seems to have some complexities in terms of the scope of the managed versus the pull that needed more thought.
