### ISSUE TITLE
ZIO Test: no equivalence between `*>` and `flatMap` from Expectation

### ISSUE THREAD

**Issue by arjun-1** [zio/zio#2671]
While using ZIO Test, I found some peculiarity which I cannot wrap my head around :sweat_smile:. Using the `*>` operator on Expecation, I created the following working mock:
```
val mockMomaClient: Expectation[MomaClient, Nothing, Position] = 
  (MockMomaClient.getNodeUrl(equalTo(sessionId)) returns value(
    uri"localhost"
  )) *>
  (MockMomaClient.getFrameCount(anything) returns value(1)) *>
  (MockMomaClient.getPosition(anything) returns value(position))
```
Looking at the definition of `*>` :
```
final def *>[M1 <: M, E1 >: E, B](that: Expectation[M1, E1, B]): Expectation[M1, E1, B] = flatMap(_ => that)
```
This should be equivalent to:
```
val mockMomaClient: Expectation[MomaClient, Nothing, Position] =
  (MockMomaClient.getNodeUrl(equalTo(sessionId)) returns value(
    uri"localhost"
  ))
  .flatMap(_ => MockMomaClient.getFrameCount(anything) returns value(1))
  .flatMap(_ =>
    MockMomaClient.getPosition(anything) returns value(position)
  )
```
In my case however, it is not. A test that previously succeeds, now fails with the error:
```
info] - A main server route
[info]   - returns positions
[info]     Fiber failed.
[info]     ╥
[info]     ╠─An unchecked error was produced.
[info]     ║ java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class sttp.model.Uri (scala.runtime.BoxedUnit is in unnamed module of loader sbt.internal.classpath.ClassLoaderCache$Key$CachedClassLoader @171f9268; sttp.model.Uri is in unnamed module of loader sbt.internal.LayeredClassLoader @97a3b59)
[info]     ║    at zio.test.mock.Expectation.$anonfun$managedEnv$9(Expectation.scala:96)
[info]     ║    at zio.internal.FiberContext.evaluateNow(FiberContext.scala:340)
[info]     ║    at zio.internal.FiberContext.$anonfun$fork$2(FiberContext.scala:655)
[info]     ║    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
```

**Comment by jdegoes** [comment]
These should be the same. Actually I'm surprised you can do `flatMap` on Expectation.

Thanks for reporting!

**Comment by ioleo** [comment]
@jdegoes We use `flatMap` to combine expectations in orderly manner. This one slipped under the radar becouse I always used the shorthand syntax. The fix adds appropriate regression suite.

**Comment by adamgfraser** [comment]
@ioleo Do we use the power of `flatMap` anywhere? That is do we ever use the result of one expectation to dynamically create the next expectation? In every case I have seen we have sequential ordering of expectations but we aren't creating them dynamically (e.g. all combinations of expectations could be written using `*>`). If so we could remove `flatMap` and implement everything in terms of `zipWith`. This could allow us to know more about expectations statically, for example we could could the number of calls expected without running them.

**Comment by ioleo** [comment]
@adamgfraser @jdegoes yes, we do need `flatMap` to support `for-comprehension`

for small suites `*>` is perfectly fine, but for larger suites this may be preferable:

```scala
import MockConsole._

val mock =
  for {
    _ <- putStrLn(equalTo("foo")) returns unit
    _ <- putStrLn(equalTo("bar")) returns unit
    _ <- putStrLn(equalTo("baz")) returns unit
    _ <- getStrLn returns value("acme")
    _ <- putStrLn(equalTo("foo2")) returns unit
    _ <- putStrLn(equalTo("bar2")) returns unit
    _ <- putStrLn(equalTo("baz2")) returns unit
    _ <- getStrLn returns value("acme2")
  } yield () // NOTE: we never use the values, we only need sequantial composition and syntax
```

**Comment by ioleo** [comment]
Arguably, the same can be achieved with

```scala
import MockConsole._

val mock =
    (putStrLn(equalTo("foo")) returns unit) *>
    (putStrLn(equalTo("bar")) returns unit) *>
    (putStrLn(equalTo("baz")) returns unit) *>
    (getStrLn returns value("acme")) *>
    (putStrLn(equalTo("foo2")) returns unit) *>
    (putStrLn(equalTo("bar2")) returns unit) *>
    (putStrLn(equalTo("baz2")) returns unit) *>
    (getStrLn returns value("acme2"))
```

**Comment by adamgfraser** [comment]
Okay, we may want to consider whether the syntax is worth providing the "unnecessary"  power of a monad versus an applicative and the resulting lack of ability to do static analysis.

What happens if a user does try to capture the result of one expectation and feed it to another?

**Comment by jdegoes** [comment]
👍 on deleting
