### ISSUE TITLE
Why new instance of TQueue created many times in this example test? 

### ISSUE THREAD

**Issue by danieljsun** [zio/zio#2679]
```
import zio.IO
import zio.stm.TQueue
import zio.test._
import zio.test.Assertion._

object StmSpike {
  val itemsIO: IO[Nothing, TQueue[String]] = {
    TQueue.make[String](Int.MaxValue) // Note: literally the `unbounded` version in next release
  }.commit
}

object StmSpikeSpec extends DefaultRunnableSpec(
  suite("StmSpikeSpec")(
    testM("one STM") {
      val l1 = List("foo")
      (for {
        items1 <- StmSpike.itemsIO
        _ <- items1.offerAll(l1).commit
        items2 <- StmSpike.itemsIO
        l <- items2.takeAll.commit
      } yield l)
        .map(l => assert(l, hasSize(equalTo(l1.size))))
    }
  )
)
```

It may looks strange that `flatMap` the `itemsIO` twice, but the above test is a simplified version of scenario where I have a Service (following the Module pattern) with a few APIs. Those APIs all use a private field of `UIO[TQueue]` which I hope to achieve atomicity of the Queue access (e.g. offer/take/etc).
Please do let me know if I have approached it wrong and a proper ZIO way to do my scenario.

**Comment by adamgfraser** [comment]
`itemsIO` is an effect that creates a `TQueue`, so you are creating two separate queues and offering an element to one queue and then taking all elements from a different queue. You can just create the queue once and the offers and takes will still be transactional.

**Comment by danieljsun** [comment]
Thanks @adamgfraser
