### ISSUE TITLE
ZIO Mock: mocking composed environments

### ISSUE THREAD

**Issue by ioleo** [zio/zio#2692]
Given a program that depends on more modules, eg:

```scala
val app =
  for {
    n <- random.nextInt
    _ <- console.putStrLn(s"$n")
    m <- random.nextLong
    s <- console.getStrLn
  } yield s"$s : ${n + m.toInt}"
```

We can construct individual mocks for `Console` and `Random` expecting each to be called twice, then convert them to mock implementations and provide to the program. 

```scala
import MockConsole._
import MockRandom._

val mockRandom = (nextInt._1 returns value(1)) *> (nextLong._0 returns value(2L))
val mockConsole = (putStrLn(equalTo("1") returns unit) *> (getStrLn returns value("foo"))

val combinedMock: ZLayer.NoDeps[Nothing, Console with Random] =
  mockRandom ++ mockConsole
```

However the relative order in which the metods were called will only be checked within each service's scope.

So the mocks will check that `nextLong` was called after `nextInt`, and that `getStrLn` was called after `putStrLn`, but will not check if `nextLong` was called after or before `putStrLn`.

So the following program would also pass the test:

```scala
val app =
  for {
    n <- random.nextInt
    m <- random.nextLong
    _ <- console.putStrLn(s"$n")
    s <- console.getStrLn
  } yield s"$s : ${n + m.toInt}"
```

Sometimes that is OK, and we don't care about the total order of calls, as long as the relative order is kept, but sometimes it might be relevant (especially when testing business processes) to make sure some calls happen before others in the "larger" environment.

The construction of such expectations would be straightforward and is already possible:

```scala
import MockConsole._
import MockRandom._

val largerEnvMock = (
  (nextInt._1 returns value(1)) *>
  (putStrLn(equalTo("1") returns unit) *>
  (nextLong._0 returns value(2L)) *>
  (getStrLn returns value("foo"))
)  
```

What we're missing is a way to auto-derrive `Mockable[A with B]` given `Mockable[A]` and `Mockable[B]`. Now a mockable is simply a single function `Mock => Has[A]`.

```scala
implicit def compose[A, B]()(implicit m1: Mockable[A], m2: Mockable[B], Tagged[Has[B]]): Mockable[A with B] =
  (mock: Mock) => {
    val env1: Has[A] = m1.environment(mock)
    val env2: Has[B] = m2.environment(mock)
    val env3: Has[A] with Has[B] = env1 union env2

    // this does not compile
    // it gets `Has[A] with Has[B]` but expects `Has[Has[A] with Has[B]]`
    env3
  }
```

I suspect if we changed the `Mockable` a little we could actually get that auto-derrivation working and have this super nice feature in ZIO Mock.

Both approaches could be composed, eg given a program that depends on 3 modules `A`, `B` and `C`, we could create a mock for `A with B` and seperately a mock for `C` and combine them using `++` just like we did in the first example, which would give us a mocked environment for `Has[A] with Has[B] with Has[C]` where relative order of calls on `A` and `B` is checked, while on `C` we just check that the expected calls happened, not careing when (in relation to A and B calls).

@jdegoes @adamgfraser I'm putting this out as I'm not sure when I'll have the time to follow this up, so if anyone has time, feel free to take this.

**Comment by jdegoes** [comment]
Definitely worth thinking about this post-`Has` to see if we can enrich composition properties of the mockable data types.

**Comment by ioleo** [comment]
Also this can be extended to `Spyable` @adamgfraser

**Comment by adamgfraser** [comment]
Very interesting. We should definitely come back to this.

**Comment by ioleo** [comment]
@adamgfraser @jdegoes FYI: started working on this. Looks promising so far. Will post PR when its complete.

**Comment by jdegoes** [comment]
@ioleo Awesome, keep us posted! 🙏

**Comment by ioleo** [comment]
Its progressing slowly, due to little time, but I will do my best to deliver this within next few days (I hope to have it merged before the next release).

**Comment by ioleo** [comment]
@jdegoes @adamgfraser Got it working. Just need to do some cleanup + update docs / examples and I will be opening the PR today or tomorrow. I think you will like it :)
