### ISSUE TITLE
Add "any" layers for all services in ZEnv

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2694]
Right now, every service has a `*.live` layer, e.g. `Clock.live`, which is a `ZLayer[In, Error, Out]`.

This is useful to wire together production implementations of services. However, sometimes, in wiring or providing part of an environment, a service needs something, and it doesn't matter if it's live or test or whatever.

To make this just a bit simpler, we can define the following layers inside the companion objects of services:

```scala
object Clock {
  val any: ZLayer[Clock, Nothing, Clock] = ZLayer.environment[Clock]
  ...
}
```

This way, in wiring, people can use `Clock.any ++ System.live ++ ...` (to be read as, _I am building a layer that uses any clock service and the live system service..._), without having to manually use `ZLayer.environment` to construct a "passthrough" layer.

The `*.any` layers can be added to all existing services, including test services; and possibly, searching for `ZLayer.environment` or `ZLayer.identity` will reveal places where this simplification can be utilized.

**Comment by adamgfraser** [comment]
I will add this now.

**Comment by mschuwalow** [comment]
This will be super useful. That pattern came up a lot while migrating the codebase
