### ISSUE TITLE
Queue.sliding `offer` clarification

### ISSUE THREAD

**Issue by vasilmkd** [zio/zio#2699]
I have been slightly bitten by the `def offer(a: A): UIO[Boolean]` method on the _sliding_ `Queue[A]`. My expectation is that there should _always_ be a place for a new element in the queue, at the expense of the oldest one (first one at the front) being dropped (a reasonable choice IMO), and therefore the return value of the method should _always_ be a `true`. But it seems that is not always the case, by checking the implementation.

I'd like to get an explanation why this is the case, and can anything be done about it. (I have no objections to the model, just curious).

**Comment by ghostdogpr** [comment]
The reason it’s not hardcoded to `true` is that `offer` is implemented using `offerAll`, and if you `offerAll` a number of items higher than the queue size, some items will be discarded. So in practice I don’t think you will ever receive false if you use `offer`.

**Comment by vasilmkd** [comment]
Except that I do, in this PR, unless I am mistaken, but I don't see some of the elements being dequeued. The issue is, when there is an error from a stream pull, I block on the last enqueued promise, until it is taken out of the queue (and it shouldn't ever be dropped, because I don't enqueue anything after it), yet the program hangs. #2666. @ghostdogpr

**Comment by vasilmkd** [comment]
I'd really love an explanation of the following. It seems that the decision comes from this line:
https://github.com/zio/zio/blob/9294751fb10beb959499bb8b8ec4769f5b501a0f/core/shared/src/main/scala/zio/ZQueue.scala#L394.
Why is this line executed at the creation of the effect, not for example at the effect execution time? It seems counter-intuitive to me. Thanks.

**Comment by ghostdogpr** [comment]
Indeed this line seems problematic. If a concurrent operation adds or removes items while we’re sliding the queue, that Boolean will be wrong.
It seems the only way to get it right would be to collect the items we pull from the queue (instead of just dropping them like now) and check if one of them belong to the input list. If yes, return false (we dropped an item we offered), otherwise true. WDYT?

**Comment by vasilmkd** [comment]
Something needs to be done here definitely. Your proposal seems very reasonable.

Let me see if I'm understanding this correctly. Let's say we have a queue with capacity 2, already filled with 2 elements, and we are trying to offer 5 elements to the queue. Given no other concurrent offers or takers, we should end up with the last 2 of the 5 elements into the queue, the first 3 elements of the list dropped, the 2 elements before the offer also dropped and a signal Boolean value `false`. Is that correct?

**Comment by ghostdogpr** [comment]
@vasilmkd yeah that’s correct. You want to try fixing it? Otherwise I can work on a fix tomorrow (today is new year celebration where I live 😅).

**Comment by vasilmkd** [comment]
Happy new year then! Honestly, I have worked around the limitation for the moment, so there's no rush. It seems that it is safe to assume that each 1 element offer implicitly returns `true`. So if you don't mind, since it's your idea and you seem to know the code quite well, I am going to leave this one to you. 😄

**Comment by ghostdogpr** [comment]
Sure, makes sense!

**Comment by ghostdogpr** [comment]
This is more complicated than I thought. To have the exact information whether any input items has been dropped, we would need to compare the dropped items with the input items, but we can't do that because they might be values and not references (e.g. if `A` = `Int`).

Instead, we could return `false` if _any_ item was dropped (not just from the input list). What do you think? Any better idea?

**Comment by regiskuckaertz** [comment]
It feels counter-intuitive to return `false` in my opinion. The contract of sliding/dropping is that they _will_ drop elements on the floor but that has nothing to do with the success of the enqueue operation. In fact they guarantee the operation will be successful, right? (barring the queue has been shut down)

**Comment by vasilmkd** [comment]
After thinking for a few weeks about this, I tend to agree with you @regiskuckaertz.

**Comment by ghostdogpr** [comment]
Okay, it makes sense. I'll return `true` then.
