### ISSUE TITLE
Unexpected behavior: zio.map assumes the function succeeds

### ISSUE THREAD

**Issue by scofirat** [zio/zio#2701]
zio.map assumes the function succeeds, making codes such as the following throw exceptions:

zio.map(unsafeFunctionThatThrowsException).orElse(default())

**Comment by adamgfraser** [comment]
`map` applies a pure function, meaning one that doesn't throw exceptions, to the result of a computation. If your function can throw exceptions you can use `task.(a => ZIO.effect(f(a))).orElse(default)` to safely capture the throwable in a `ZIO` value an recover from it.

**Comment by iravid** [comment]
Closing as ZIO does not catch when evaluating functions that are assumed to be pure.
