### ISSUE TITLE
Port ZSink constructors and combinators to the new encoding

### ISSUE THREAD

**Issue by iravid** [zio/zio#2719]
See current design in https://github.com/zio/zio/issues/2551#issuecomment-578415241.

Submit PRs to `feature/zconduit`. Reply below to claim an item.

Constructors:    
- [ ] ~await~ ported as `ZSink.head`
- [x] collectAll 
- [x] collectAllN - port as transducer
- [x] collectAllToMap 
- [x] collectAllToSet 
- [x] collectAllToMapN - port as transducer
- [x] collectAllToSetN - port as transducer
- [x] collectAllWhile - port as transducer
- [x] collectAllWhileM - port as transducer
- [x] die 
- [x] dieMessage 
- [x] drain 
- [x] fail
- [x] fold
- [x] foldLeft 
- [x] foldLeftM 
- [x] foldM
- [x] foldUntil - port as transducer
- [x] foldUntilM - port as transducer
- [x] foldWeighted - port as transducer
- [x] foldWeightedDecompose - port as transducer
- [x] foldWeightedDecomposeM - port as transducer
- [x] foldWeightedM - port as transducer 
- [x] fromEffect
- [x] fromFunction - will need a different signature (`A => Either[Z, Unit]`)
- [x] fromFunctionM - will need a different signature (`A => ZIO[R, Either[E, Z], Unit]`)
- [x] halt
- [x] head 
- [ ] ~identity~ - ported as `head`
- [x] ignoreWhile - port as transducer
- [x] ignoreWhileM - port as transducer
- [x] last 
- [ ] ~pull1~ requires leftovers to operate properly, don't port
- [ ] ~read1~ requires leftovers to operate properly, don't port
- [ ] splitOn - port as transducer
- [x] succeed
- [x] splitLines - port as transducer
- [ ] ~splitLinesChunk~ chunks are built-in so this will be ported as `splitLines`
- [x] utf8DecodeChunk - port as transducer

Combinators:
- [x] &> 
- [x] *> 
- [x] <& 
- [x] <&> 
- [x] <* 
- [x] <*> 
- [ ] <| 
- [x] as 
- [ ] asError 
- [x] contramap
- [x] contramapM
- [x] dimap
- [x] flatMap
- [x] map
- [x] mapError
- [x] mapM
- [ ] orElse
- [ ] provideSome
- [x] race 
- [x] raceBoth
- [ ] tapInput 
- [ ] tapOutput 
- [ ] timed
- [ ] unit 
- [x] zip 
- [x] zipLeft 
- [x] zipPar 
- [x] zipParLeft 
- [x] zipParRight 
- [x] zipRight 
- [x] zipWith 
- [x] zipWithPar
- [ ] ?
- [ ] chunked
- [ ] collectAll
- [ ] collectAllN
- [ ] collectAllWhile
- [x] collectAllWhileWith (signature changed to `Z => Boolean`
- [ ] collectAllWith
- [ ] optional
- [ ] takeWhile
- [x] untilOutput
- [ ] drop
- [ ] dropWhile
- [ ] filter
- [ ] filterM
- [ ] filterNot
- [ ] filterNotM
- [ ] keyed

**Comment by iravid** [comment]
Doing `ZSink.drain`

**Comment by simpadjo** [comment]
@iravid I'd take some but don't see the branch. Is there anything done at the moment?

**Comment by iravid** [comment]
@simpadjo Hey - the branch is `feature/zconduit`.

**Comment by simpadjo** [comment]
@iravid thanks for updating the status.
Picking `race` and `zipPar` families.

**Comment by iravid** [comment]
Doing `collectAllTo{Map,Set}` and `collectAllTo{Map,Set}N`
