### ISSUE TITLE
Upgrade mdoc Resolve mdoc upgrade issues

### ISSUE THREAD

**Issue by softinio** [zio/zio#2721]
- upgrade mdoc to latest version
- update code snippets in code to resolve these issues: 
https://app.circleci.com/jobs/github/zio/zio/52156

**Comment by peterlopen** [comment]
I will have a look.

**Comment by softinio** [comment]
@peterlopen thank you!

**Comment by peterlopen** [comment]
@softinio 
wrt:
`reference to App is ambiguous;
it is both defined in object Session and imported subsequently by 
import zio.App
object MyApp extends App {
`
I can think of 3 ways how to fix this (however I do not like any of them):
1. removing `import zio.App` from code snippet
2. aliasing zio.App to ZApp in import and using that one in code snippet
3. removing import, and using zio.App in code snippet

Which of those would be better in your opinion?

Best would be to have issue you have created for mdoc fixed (https://github.com/scalameta/mdoc/issues/204). Neither reset-object/nest does not help in this case.

thanks.

**Comment by peterlopen** [comment]
@softinio 
`error: /home/plopen/projects/zio/docs/howto/mock_services.md:236:49: not found: value accountObserverLive
      val result = app.provideLayer(mockEnv >>> accountObserverLive)
`
this one is weird too - mockEnv from previous mdoc block is available, however accountObserverLive is not (even in the block following directly after its definition).

My idea would be to merge those blocks together. WDYT? 
thanks.

**Comment by softinio** [comment]
@peterlopen 

Sorry for late reply (I need to fix my github email filtering :-) )

Agree with merging block. 

Ultimate solution is to get it fixed in mdoc via the issue I created. Failing that guess choose from the 3 options the one that provides the most clarity in the docs. Maybe 3? Which is the one you hate the least :-) ?

**Comment by adamgfraser** [comment]
@peterlopen You still working on this? Anything you need to push it forward?

**Comment by peterlopen** [comment]
@adamgfraser created PR, sorry for not pushing it earlier.

**Comment by adamgfraser** [comment]
@peterlopen No problem! We all have a lot going on, especially these days. Will take a look today.
