### ISSUE TITLE
Should we move our docs from Docusaurus to Paradox

### ISSUE THREAD

**Issue by softinio** [zio/zio#2722]
# Paradox

https://github.com/lightbend/paradox
https://developer.lightbend.com/docs/paradox/current/

# Summary

I really like Docusaurus but I feel its adding a level of complexity to our project and build.

### Some benefits of Paradox

- Zero dependency on anything other than scala and sbt. This means no dependency on JS, yarn etc. All of this can be removed from our build process, local dev requirements etc

- scalafiddle of code inclusion in docs: https://developer.lightbend.com/docs/paradox/current/directives/fiddles.html

- snippets: https://developer.lightbend.com/docs/paradox/current/directives/snippets.html
- useful grouping feature: https://developer.lightbend.com/docs/paradox/current/groups.html
- css friendly and theme able

Thought I ask the questions and see everyones view on it. 

Thanks.

**Comment by jdegoes** [comment]
Lightbend has little incentive to maintain their own doc builder... looks relatively inactive. Also we'd have to migrate all ZIO projects to the new one. 

That doesn't mean we shouldn't do it, just consider carefully. While Docusaurus is "messy" in terms of dependencies, it isn't causing any real pains so far. Also with Docusaurus having a 2.0, we can benefit from many nice new features like search.

**Comment by softinio** [comment]
@jdegoes I agree with your points so will close this. 

Also FYI I did add search to the zio site you will see it next release :-)

**Comment by jdegoes** [comment]
@softinio Search is coming? Awesome! Thank you! 🙏
