### ISSUE TITLE
Improvements to build process to include snapshot releases

### ISSUE THREAD

**Issue by softinio** [zio/zio#2724]
# Goals

- Would like to have regular snapshot releases so new features can be used and tested before release

# Plan

- [x] Add circlci Support to <https://github.com/olafurpg/sbt-ci-release> - done via <https://github.com/olafurpg/sbt-ci-release/pull/93> and this change is included in the latest release

- [x] Generate new PGP for release to Sonatype
- [x] Update circleci context with new PGP key 
- [x] In project: Upgrade version of `sbt-pgp` to latest 2.x version and remove this package being ignored by scala stewart in `.scala-steward.conf` (this file we can remove if only item)
- [x] in project: Add `addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.0")` and amend `circleci` config to use it
- [x] Update README: new link to snapshot release in the bar and any other update necessary

# Expected Outcome

- Current `release` process via generating a new release version tag continues to work as it does now (with the new upgraded `sbt-pgp`)
- on merge to master new snapshot version released

# Testing and Roll out

- Going to make the above changes to `zio-actors` first and make sure it all works as expected
- Upon success with `zio-actors` will add changes (of course via a PR) to ZIO
- Roll out to other `zio` projects. Thinking I will create an issue with steps to follow for each repo  and maybe others can help me so we can get them all done fast
- @mijicd has promised to bring a priest

# Finally

- Drink 🍷to celebrate 

# Future Work

- Post this effort I would like to have a staging website for https://zio.dev maybe https://snapshot.zio.dev that on merge to master it gets updated so we are able to see what our site looks like before doing a release and have docs for the snapshots :-) 

- Also be good to consider this as it will result in a less complex build and local dev environment, plus faster builds which means circleci bill reduced (by how much or worth doing no idea :-) ): https://github.com/zio/zio/issues/2722

**Comment by mijicd** [comment]
Assuming everything goes as expected, we should create a follow-up to sync all of the other repositories, as well as the giter8 template.

**Comment by softinio** [comment]
@mijicd @jdegoes @adamgfraser Above ZIO PR outlines the changes that needs to be make to our other repos to enable snapshots if needed. 

For the seed best to base it on the `zio-actors` changes. 

Success 🍷:

<https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_2.12/>
<https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-actors_2.12/>

😀

**Comment by softinio** [comment]
cc @iravid  ^^
