### ISSUE TITLE
ZIO Mock: support methods that accept streams and/or produce streams

### ISSUE THREAD

**Issue by thesamet** [zio/zio#2734]
Currently ZIO Mock supports methods that gets parameters and return an effect that produces a single value. The ask is to provide support for methods that produce/consume streams.

**Comment by ioleo** [comment]
@thesamet Thanks for raising the issue. It's on my roadmap, now that we've got Mock for complex environments (#3000) I'll see what we can do for polymorphic methods and ZStream support.
