### ISSUE TITLE
Add ZStream.fromIterableEffect

### ISSUE THREAD

**Issue by iravid** [zio/zio#2735]
Signature:
```scala
object ZStream {
  def fromIterableEffect[R, E, A](zio: ZIO[R, E, Iterable[A]]): ZStream[R, E, A]
}
```

**Comment by peterlopen** [comment]
I would like to take this one.

**Comment by adrianfilip** [comment]
@peterlopen sorry, saw your comment after I started looking into it.

**Comment by peterlopen** [comment]
ok, np. just for reference, I was thinking about this solution:
`  def fromIterableEffect[R, E, A](fa: ZIO[R, E, Iterable[A]]): ZStream[R, E, A] =
    fromEffect(fa).flatMap(Stream.fromIterable)
`

**Comment by adrianfilip** [comment]
@peterlopen That looks better. You should make a pr.

**Comment by peterlopen** [comment]
thanks. will do.

**Comment by adrianfilip** [comment]
great. I closed my pr.

**Comment by peterlopen** [comment]
@iravid should name be just `fromIterable` ? based on other methods, i.e.: `def fromIterator[R, E, A](iterator: ZIO[R, E, Iterator[A]]): ZStream[R, E, A] = ...`

**Comment by peterlopen** [comment]
@iravid nvm, Effect in name makes sense as Stream.fromIterable already exists.
