### ISSUE TITLE
Add ZSink.sum

### ISSUE THREAD

**Issue by iravid** [zio/zio#2737]
Signature:
```scala
object ZSink {
  val sum: Sink[Any, Nothing, Nothing, Long, Long]
}
```

Or possibly use `scala.math.Numeric` for defining the input type.

**Comment by kolemannix** [comment]
I would like to tackle this.

In addition, what about a `count` sink as well that simply counts the elements it receives and emits a `Long`?

**Comment by iravid** [comment]
All yours @kolemannix!

**Comment by kolemannix** [comment]
Trying with this signature
```scala
def sum[A](implicit ev: Numeric[A]): ZSink[Any, Nothing, Nothing, A, A]
```

There are some inconveniences to the caller
```scala
Stream.fromIterable(1 to 10).run(ZSink.sum)
```
yields the unfriendly
```
[error] /zio/streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala:1248:60: ambiguous implicit values:
[error]  both object BigIntIsIntegral in object Numeric of type scala.math.Numeric.BigIntIsIntegral.type
[error]  and object ShortIsIntegral in object Numeric of type scala.math.Numeric.ShortIsIntegral.type
[error]  match expected type Numeric[A]
[error]               assertM(Stream.fromIterable(range).run(ZSink.sum))(equalTo(range.sum))
[error]                                                            ^
```
In my experience this happens whenever one tries to be generic over Numeric. Is this satisfactory? It is resolved by specifying `ZSink.sum[Int]`. I don't believe overloading is the answer here, but hardcoding to `Long -> Long` seems a bit narrow.

Being generic also means using a `def`, which means we're instantiating a new `PureSink` on each call, which may or may not matter for performance.

Thoughts?

**Comment by vasilmkd** [comment]
I wouldn't worry about the `def`. It's also ok for the type to be needed to be specified.

**Comment by iravid** [comment]
We can add a shortcut on ZStream that will ease this issue:
```scala
def runSum(implicit A: Numeric[A]): ZIO[R, E, A] = run(Sink.sum[A])
```

**Comment by regiskuckaertz** [comment]
Looks like this is done.
