### ISSUE TITLE
fromJavaFuture interop

### ISSUE THREAD

**Issue by cheatmenot** [zio/zio#2755]
currently, I need to convert the javaFuture to scalaFuture first before I can use Task.fromFuture (which is an overhead of converting one future to another and there is no "proper" way). Most of the libraries I used is Java based, so if possible can we add support for javaFuture interoperability, like Task.fromJavaFuture(). Thanks!

**Comment by adamgfraser** [comment]
Have you looked at [zio/interop-java](https://github.com/zio/interop-java)?

**Comment by cheatmenot** [comment]
sorry, I will check on that, I have only view on the docs - https://zio.dev/docs/interop/interop_java which says coming soon. Maybe we need also to update that one, if I have time I will do some docs stuff. Thanks!

**Comment by mijicd** [comment]
@cheatmenot That'd be great. We have some helpers in both `interop-java` and `interop-guava`, feel free to take a look and suggest any changes you find necessary.

@adamgfraser I am closing this issue, but we should once again reconsider pulling the Java interop back into the core lib itself. We had some issues about that.
