### ISSUE TITLE
Add ZIO.any

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#2762]
Proposal to add `ZIO.any`.
```scala
final def any: UIO[Any] = ZIO.unit
```
This can help with type inference / eliminating `.unit` operations.
```scala
def submit(o: Option[Int], q: Queue[Int]): UIO[Any] = 
  o.fold(ZIO.any)(q.offer)
// o.fold[UIO[Any]](ZIO.unit)(q.offer) - with type inference
// o.fold(ZIO.unit)(q.offer(_).unit) - with extra operation
```
@jdegoes @adamgfraser Thoughts?

**Comment by adamgfraser** [comment]
I'm not a big fan of this. I think in your example the right signature for submit is `UIO[Unit]` (assuming you want to discard the information about whether there was any value and whether there was capacity in the queue). Having `Any` in types that are not contravariant leads to the risk of types being widened inadvertently. In your case, I would use the last way of writing this and take it as an indication that perhaps a convenience method on `Queue` that lets you offer a value and returns `UIO[Unit]` would be helpful.

**Comment by ajaychandran** [comment]
@adamgfraser 
I agree with your main argument but I don't care for the return value in my usecase.
On second glance, I don't care if the value is enqueued either. :blush:

The initial motivation was to simplify usecases that involved `Option.fold`. But perhaps this is not justification enough to add `ZIO.any`.

If we were to add a convenience method on `Queue`, is this what you had in mind?
```scala
def offer1(a: A): UIO[Unit] = offer(a).doUntil(identity).unit
```
On a related note, `offer1` could return `UIO[Boolean]` (or `UIO[Any]`, since the expected boolean value is always true) and we could save 1 `.unit` operation. What is your preference in this case?

**Comment by adamgfraser** [comment]
@ajaychandran I think you would need to think through a bit what behavior you would want when the queue was at capacity (e.g. in your first example you were happy to make "best efforts" to offer and move on regardless versus in this case you are retrying until there is capacity) and how the method would behave for different queue implementations (I believe this implementation could lead to continuously trying to offer elements in a tight loop in certain situations like with a dropping queue).

Then if you have something you are happy with and feel is sufficiently general to be applicable to other users you can open an issue or PR or discuss it on the Discord channel to get more input.

**Comment by ajaychandran** [comment]
@adamgfraser Thank you for the inputs. Will pick this up in a different thread.
