### ISSUE TITLE
STM.tap

### ISSUE THREAD

**Issue by fsvehla** [zio/zio#2776]
```scala
trait STM[E, A] {
  def tap(f: A => STM[E, Unit]): STM[E, A]
}
```

**Comment by adamgfraser** [comment]
You want to take the ticket?

**Comment by fsvehla** [comment]
@adamgfraser Yep!

**Comment by adamgfraser** [comment]
@fsvehla Great! Can you add `tapError` and `tapBoth` too?

**Comment by fsvehla** [comment]
Sure thing

**Comment by fsvehla** [comment]
Seems like @mijicd started on this independently in #2777 so I I’m not working on this anymore.

**Comment by mijicd** [comment]
@fsvehla feel free to continue with `tapError` / `tapBoth`, although they might be a bit quirky.

**Comment by fsvehla** [comment]
Taking `tapError` / `tapBoth`

**Comment by mijicd** [comment]
These two might be quirky from a semantic point of view. Let's say you have the following signature:

```scala
def tapError[R1 <: R, E1 >: E](f: E => ZSTM[R1, E1, Any]): ZSTM[R1, E1, A]
```

Failure we got from running `self` would prevent `f` to be committed as well.

cc @jdegoes to verify this

**Comment by adamgfraser** [comment]
Another transactional effect would have to subsequently recover from the error within the transaction for the tap effect to be committed. So for example this test passes:

```scala
for {
  refA <- TRef.make(10).commit
  refB <- TRef.make(0).commit
  _    <- (refA.get *> ZSTM.fail("fail")).tapError(_ => refB.set(1)).ignore.commit
  b    <- refB.get.commit
} yield assert(b)(equalTo(1))
```

But if the transaction fails and we recover outside of the transaction, for example by committing after the tap effect and then ignoring the resulting ZIO error the tap effect would never be committed. I think this is just the nature of STM and the combinator still makes sense but it is a good point.

**Comment by mijicd** [comment]
That would certainly suffice for test purposes, however, it forces breaking of transactional boundary which is unfortunate.

**Comment by adamgfraser** [comment]
You're right. You could do something like:

```scala
val tx =
  for {
    refA <- TRef.make(10)
    refB <- TRef.make(0)
    a <- (refA.get *> ZSTM.fail("fail"))
          .tapError(_ => refB.set(1))
          .foldM(_ => refB.get, _ => refB.get)
  } yield a
```

**Comment by mijicd** [comment]
This is definitely better, however, note that:

```scala
tx.tapError(_ => refB.set(1)).foldM(_ => refB.get, _ => refB.get)
```

is equivalent to:

```scala
tx.foldM(_ => refB.modify(_ => (1, 1)), _ => refB.get)
```

In essence, for `tapError` to be used, we'll need to follow it with a more powerful combinator to prevent its result from being rollbacked.

**Comment by adamgfraser** [comment]
Yes, in my example it is definitely kind of trivial but the `tapError` effect could be separate from the error handler by a lot of other logic that assumes success. I kind of think about it like how with `ZIO` we use `tapError` but our applications almost always don't fail at the top level, we catch and recover from the error somewhere. `STM` just lets us created different isolated "programs" that we can compose together but ultimately have to handle their own errors if they are going to have any effects that are not rolled back.

**Comment by fsvehla** [comment]
Do we have consensus if `tapBoth|Error` make sense?

**Comment by adamgfraser** [comment]
My perspective would be that they do.

@mijicd What do you think?

**Comment by mijicd** [comment]
I am a bit worried about use scenarios mentioned above, but they're definitely implementable and can be useful in certain scenarios. If we go with them, this behavior needs to be clearly stated.

Summoning @jdegoes as tie-breaker :).

**Comment by jdegoes** [comment]
I think it makes sense to have them. Obviously if the error is not recovered from, then the transaction will have no effect. But much code cannot know if the transaction will be recovered from (at a higher-level) and could therefore call `tapError` to effect changes in the transaction on an error state.
