### ISSUE TITLE
How Should We Support Chunk In Effect Combinators?

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2781]
We just merged #2380 providing overloaded versions of `foreach` for `Option` and `Chunk`.

For `Option` this could just be regarded as a convenience method for making working with optional values slightly more ergonomic in some cases. `Option` has at most one value so a lot of variants of "collection" operations aren't meaningful.

But `Chunk` is our own collection type so theoretically I would think we would want it to be first class, which would mean all operations that were supported on Scala collections in ZIO would also be supported on chunks. Unfortunately this is quite a few operations, not only the `foreach` and `collectAll` variants but `foldLeft`, `foldRight`, `filter`, `validate`, `partition`, etc... and their various aliases on all the companion objects.

The alternatives I see are:

1. Just implement the methods. It would be a great source of first issues but I worry a bit about increasing the maintenance burden of adding new variants where essentially when we add a new method we often need `ZIO`, `ZManaged`, and `ZSTM` variants as well as `Iterable` and `Chunk` variants and forwarders for various companion objects.
2. Implement some kind of minimal collection type class.
3. Say that because of its lazy nature only some subset of operations make sense on chunks and delineate what those are.

Right now we seem to be going down the first route but I want to be sure we really think that is the road to go down before we start adding a bunch of additional methods for `Chunk`.

**Comment by jdegoes** [comment]
Maybe `Chunk` becomes first class, with first-class support everywhere, and the rest are just derivative. Maybe all the methods are shifted over to work, if not with `Chunk`, then anything that is `ChunkLike`, e.g.:

```scala
trait ChunkLike[Collection[_]] {
  def toChunk[A](ca: Collection[A]): Chunk[A]
  def fromChunk[A](chunk: Chunk[A]): Collection[A]
}
object ChunkLike { /* implicits for everything in Scala std lib */ }
```

One could also imagine `NonEmptyChunk` being a subtype of `Chunk` (a kind of marker interface that guarantees at least one element). Mainly so you could do `foreach` over non-empty things and get back something that's non-empty.

It's kind of the most minimal thing I can think of that could possibly be justified on grounds that "chunk is primary" and not reinventing what can be obtained elsewhere.

**Comment by adamgfraser** [comment]
Yes, you could definitely do that. You might not even need `fromChunk` (which non-linear structures like trees couldn't implement). We already have all of our methods return `List` as the output type so they could just go to returning `Chunk`. Then we would just need a way of converting an arbitrary collection to a `Chunk`. I do feel like this brings us away from the standard library though in a way that is less than ideal.

**Comment by regiskuckaertz** [comment]
Do you think `Chunk` is here to stay? I'm asking because the effort is not trivial and it may be that [the upcoming implementation of `Vector`](https://github.com/scala/scala/pull/8534) obliterates the need for it—IIRC the reason it was added in the first place is good append and random access.

**Comment by jdegoes** [comment]
Yes, Chunk is here to stay. Vector boxes primitives, Chunk does not.

@adamgfraser I forgot about this ticket. I was more imagining that methods like `ZIO.foreach` would be polymorphic in the collection type. They would support returning anything that can be created from a chunk. So you'd do, e.g. `ZIO.foreach[Vector](...)` to get back a `Vector`. 

I think that can be done in a lower-kinded (inferrable) way with some `CanBuildFrom` type machinery... question is do we wanna go there or not.

**Comment by jdegoes** [comment]
After thinking about this for quite some time, here's what I think we should do:

1. Support Chunk input, chunk output
2. Support Iterable input, List output
3. Where it makes sense, support Option input, Option output
4. Delegate everything else to a third-party library (e.g. ZIO Prelude)

**Comment by adamgfraser** [comment]
That sounds good. I will add these.

**Comment by adamgfraser** [comment]
Looking at this there are quite a few combinators that we would want `Chunk` variants for.

- [ ] firstSuccessOf
- [ ] raceAll
- [ ] collectAll
- [ ] CollectAllPar
- [ ] collectAllParN
- [ ] collectAllSuccesses
- [ ] collectAllSuccessesPar
- [ ] collectAllSuccessesParN
- [ ] collectAllWith
- [ ] collectAllWithPar
- [ ] collectAlWithParN
- [ ] filter
- [ ] firstSuccessOf
- [ ] foldLeft
- [ ] foldRight
- [ ] foreach*
- [ ] foreach_*
- [ ] foreachPar*
- [ ] foreachPar_*
- [ ] foreachParN
- [ ] foreachParN_
- [ ] forkAll
- [ ] forkAll_
- [ ] mergeAll
- [ ] mergeAllPar
- [ ] partition
- [ ] partitionPar
- [ ] partitionParN
- [ ] raceAll
- [ ] reduceAll
- [ ] reduceAllPar
- [ ] replicate
- [ ] validate
- [ ] validatePar
- [ ] validateFirst
- [ ] validateFirstPar

Methods with an asterisk have already been implemented.

I don't know if there is any good way to cut this list down. Otherwise this could be a source of good first issues. Fortunately I think these could be added after 1.0.0 in a binary compatible way.
