### ISSUE TITLE
ZIO Core: Add more control flow combinators to avoid the need for explicit recursion

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2786]
The following combinators might be useful to add to `ZIO`, together with the companion objects for the ZIO type aliases (`Task`, `UIO`, `URIO`, `RIO`, `IO`).

```scala
def loop[R, E, A, S](initial: S, cont: S => Boolean, inc: S => S)(body: S => ZIO[R, E, A]): ZIO[R, E, List[A]] = ???

def loop_[R, E, S](initial: S, cont: S => Boolean, inc: S => S)(body: S => ZIO[R, E, Any]): ZIO[R, E, Unit] = ???
```

A more powerful version would be:

```scala
def iterateM[R, E, S](initial: S, cont: S => Boolean)(body: S => ZIO[R, E, S]): ZIO[R, E, S] = ???
```

#### Example Usage

```scala
ZIO.loop(0, _ < 10, _ + 1) { index =>
  putStrLn(s"Currently at index ${index}")
}
```

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by jdegoes** [comment]
Hmm, should probably be called `iterate` rather than `iterateM` because there is no useful version of the base `iterate`, similar to `ZIO.foreach`, etc.

**Comment by adamgfraser** [comment]
Yes. I also think we should curry `initial` for better type inference on `cont` and `inc`.
