### ISSUE TITLE
ZIO Test: Add verify TestAspect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2792]
It would be useful to have a `TestAspect` that allows verification of "post conditions" after tests are run.

```scala
def verify[R, E, A](condition: ZIO[R, E, TestResult]): TestAspect[...]
```

**Example**

```scala
myTest(...) {
} @@ verify(databaseIsReset)
```

**Comment by adamgfraser** [comment]
I will add this.

**Comment by pshirshov** [comment]
Out of curiosity: are you going to verify them after ALL the tests finish or immediately after each test?

**Comment by adamgfraser** [comment]
I was thinking after each test.

**Comment by jdegoes** [comment]
We could consider making that configurable too, e.g. verifyEach vs verifyAll.

**Comment by adamgfraser** [comment]
Yes. We would have to think a bit about what we do with the failure in `verifyAll`. Right now we have the concept that suites either fail with an error pr produce a collection of tests. Presumably we want to keep the test results even if the verification condition fails so we can't just fail at the suite level. Maybe we append the failure to each of the tests?

**Comment by pshirshov** [comment]
> I was thinking after each test.

Whie this idea looks nice it's gonna be one more hell in real life. You don't need postconditions for pure code and you are creating another great opportunity for impure code have interference.

**Comment by jdegoes** [comment]
> to keep the test results even if the verification condition fails so we can't just fail at the suite level. Maybe we append the failure to each of the tests?

Exactly, so they all fail for the same reason, i.e. failed post-condition. It would be odd to have all the tests "pass" but the suite "fail" so I think that's more intuitive.

> Whie this idea looks nice it's gonna be one more hell in real life. You don't need postconditions for pure code 

I think it's useful for verifying appropriate cleanup is done after a suite, in an integration or systems test. Whether or not it's a good idea to write such code, well, let's leave that for the user to decide. 😉

**Comment by jdegoes** [comment]
(Guess with this semantic we would not need 2 versions of verify, just one...)

**Comment by adamgfraser** [comment]
Unless you wanted to be able to call it on a suite and have verification done after each test.

**Comment by jdegoes** [comment]
@adamgfraser Ah right, I suppose that makes sense.
