### ISSUE TITLE
Port Combinators from ZIO to STM

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2802]
There are a variety of combinators on ZIO that don't exist on STM right now. Many of these methods don't make sense for STM (e.g. methods dealing with fibers, interruption, importing side effecting code into ZIO, etc...). But there are many others that would make sense and would be helpful to have (e.g. `flatMapError`).

The first part of this issue is to go through the methods in ZIO and identify which of them would make sense to implement for STM. Then we can use this issue as a master tracker and people can take different methods they want to implement. In general it should be possible to implement these methods in terms of existing STM combinators, so this is a great opportunity to learn more about STM and add some new methods to the public API.

Copying @mijicd.

**Comment by mijicd** [comment]
I will go through this tonight and update the issue with implementable combinators.

**Comment by adamgfraser** [comment]
Awesome!

**Comment by mijicd** [comment]
I've collected all combinators that can be added to (Z)STM. Obviously, we could add more by committing and invoking the respective operation on ZIO, but I'd prefer not to do that now as it would clutter the interface.

Please take a look at the lists, suggest combinators that we could add/remove, and enjoy hacking :).

### ZSTM

- [ ] absolve
- [ ] andThen (with aliases)
- [ ] bimap
- [ ] catchAll
- [ ] catchSome
- [ ] filterOrDie
- [ ] filterOrDieMessage
- [ ] filterOrElse
- [ ] filterOrElse_
- [ ] filterOrFail
- [ ] flatMapError
- [ ] flip
- [ ] flipWith
- [ ] flattenErrorOption
- [ ] get
- [ ] head
- [ ] merge
- [ ] none
- [ ] onFirst
- [ ] onLeft
- [ ] onRight
- [ ] onSecond
- [ ] optional
- [ ] orDie
- [ ] orDieWith
- [ ] left
- [ ] leftOrFail
- [ ] leftOrFailException
- [ ] refineOrDie
- [ ] refineOrDieWith
- [ ] right
- [ ] rightOrFail
- [ ] rightOrFailException
- [ ] reject
- [ ] reject
- [ ] rejectM
- [ ] some
- [ ] someOrFail
- [ ] someOrFailException

### ZSTM companion

- [ ] absolve
- [ ] foldLeft
- [ ] foldRight
- [ ] fromFunction
- [ ] fromFunctionM
- [ ] fromOption
- [ ] left
- [ ] mapN
- [ ] mergeAll
- [ ] none
- [ ] reduceAll
- [ ] right
- [ ] some
- [ ] swap
- [ ] _1
- [ ] _2

**Comment by adamgfraser** [comment]
How about:

**Trait**
- [ ] compose
- [ ] doUntil*
- [ ] doWhile*
- [ ] eventually
- [ ] forever
- [ ] summarized

**Companion object:**
- [ ] filter
- [ ] partition
- [ ] replicate
- [ ] require
- [ ] validate
- [ ] validateFirst
- [ ] whenCase
- [ ] whenCaseM

* Would need to be implemented directly rather than in terms of schedule

**Comment by mijicd** [comment]
Thanks for adding them! I agree with most, and have 2 remarks:

- I'm not sure whether `forever` is needed.
- We already have `filter` on trait, and it operates with different semantics. That being said, we should either omit `filter` here, or think about some renaming.

**Comment by adamgfraser** [comment]
Yes, `forever` has somewhat different semantics here since you wouldn't use it to like run a server forever. It is more "keep running this until it fails" like `eventually` is "keep running this until it succeeds". And yes you're right that `filter` has a somewhat different semantic here than in ZIO with the way it is implemented in terms of `collect`. Maybe it becomes `filterM`?

**Comment by mijicd** [comment]
We can actually rename `filter` to `retryUntil`?

**Comment by adamgfraser** [comment]
Yes and maybe add a `retryWhile` variant.

**Comment by mijicd** [comment]
I'll add those 2 separately and remove filter. With that in place, we can add `filter` to the companion easily.

**Comment by mijicd** [comment]
After merging #2812, here's the final list of combinators to be added:

#### Class

- [ ] absolve
- [ ] andThen (with aliases)
- [ ] bimap
- [ ] catchAll
- [ ] catchSome
- [ ] compose
- [ ] doUntil
- [ ] doWhile
- [ ] eventually
- [ ] filterOrDie
- [ ] filterOrDieMessage
- [ ] filterOrElse
- [ ] filterOrElse_
- [ ] filterOrFail
- [ ] flatMapError
- [ ] flip
- [ ] flipWith
- [ ] flattenErrorOption
- [ ] forever
- [ ] get
- [ ] head
- [ ] merge
- [ ] none
- [ ] onFirst
- [ ] onLeft
- [ ] onRight
- [ ] onSecond
- [ ] optional
- [ ] orDie
- [ ] orDieWith
- [ ] left
- [ ] leftOrFail
- [ ] leftOrFailException
- [ ] refineOrDie
- [ ] refineOrDieWith
- [ ] right
- [ ] rightOrFail
- [ ] rightOrFailException
- [ ] reject
- [ ] reject
- [ ] rejectM
- [ ] some
- [ ] someOrFail
- [ ] someOrFailException
- [ ] summarized

### Companion

- [ ] absolve
- [ ] filter
- [ ] foldLeft
- [ ] foldRight
- [ ] fromFunction
- [ ] fromFunctionM
- [ ] fromOption
- [ ] left
- [ ] mapN
- [ ] mergeAll
- [ ] none
- [ ] partition
- [ ] reduceAll
- [ ] replicate
- [ ] require
- [ ] right
- [ ] some
- [ ] swap
- [ ] validate
- [ ] validateFirst
- [ ] whenCase
- [ ] whenCaseM
- [ ] _1
- [ ] _2

**Comment by sken77** [comment]
I'll do

absolve
either
doWhile
doUntil
bimap

**Comment by sken77** [comment]
ill do

andThen >>>
compose <<<
catchAll
eventually
flatMapError
flipWith
flattenErrorOption

btw flip is already there

**Comment by mijicd** [comment]
Please split them up in logical groups though (:heart: for smaller PRs :)).

**Comment by sken77** [comment]
orDie
orDieWith

**Comment by sken77** [comment]
doing
```
left
leftOrFail
leftOrFailException
right
rightOrFail
rightOrFailException

```

**Comment by mijicd** [comment]
Tackling factories (`fromOption`, `fromFunction` and `fromFunctionM`).

**Comment by sken77** [comment]
adding
```
some
someOrFail
someOrFailException
```

**Comment by sken77** [comment]
doing sumarized

**Comment by mijicd** [comment]
Taking care of `left`, `right`, `orLeft`, `orRight`.

**Comment by sken77** [comment]
Doing `onFirst`, `onSecond`

**Comment by sken77** [comment]
Ill add all the `option` related ones

```
get
head
optional
none
```

**Comment by sken77** [comment]
doing `forever` `merge`

**Comment by mijicd** [comment]
Tackled some/none on companion.

**Comment by mijicd** [comment]
Tackled partition.

**Comment by sken77** [comment]
doing 

```
filterOrDie
filterOrDieMessage
filterOrElse
filterOrElse_
filterOrFail
```

**Comment by mijicd** [comment]
Tackled `filter`.

**Comment by sken77** [comment]
doing reject/rejectM

**Comment by mijicd** [comment]
Doing `flatten`, `_1`, _2`

**Comment by sken77** [comment]
Doing `mergeAll` from the companion

**Comment by sken77** [comment]
Doing `reduceAll` from the companion

**Comment by mijicd** [comment]
Tackled `mapN`.

**Comment by mijicd** [comment]
Tackled `replicate`.

**Comment by sken77** [comment]
add

`whenCase`
`whenCaseM`

**Comment by sken77** [comment]
add
`validate`
`validateFirst`

**Comment by mijicd** [comment]
Porting `refineOrDie` and `refineOrDieWith`.

**Comment by sken77** [comment]
so the ones left are `caughtSome` requires `Cause` in ZIO how would that translate in ZSTM? any further discussio for `forever`?

**Comment by adamgfraser** [comment]
We should be able to implement `catchSome` without `Cause`. We can just use `catch` and recover with the partial function if it matters or else retail. I guess `forever` is up for debate but I think it is a well defined combinator. It is certainly easy to implement.

**Comment by sken77** [comment]
ok. doing `catchSome` and `forever

**Comment by mijicd** [comment]
With the last 2 being completed, I'm closing the issue. @sken77, @adamgfraser thanks for collaborating on this one!
