### ISSUE TITLE
In ZLayer.fromServicesM, R should not have type bounds

### ISSUE THREAD

**Issue by thesamet** [zio/zio#2816]
In `ZLayer.fromServiceM` functions, `R` has a type bound of `<: Has[_]`. I think that this requirement is unnecessary, as in the definition of `ZLayer[RIn, E, ROut]` - `RIn` is unbounded. This creates a problem when the effect provided fromServiceM is an `IO`, as in that case `R` is `Any`, and is not a sub-type of `Has[_]`.

Let me know if this is unintentional and I can put together a PR.

**Comment by adamgfraser** [comment]
Yes I believe this is correct.

**Comment by adamgfraser** [comment]
PR would be much appreciated. 🙏
