### ISSUE TITLE
Make Sure We Are Ready to Publish for Next Release Candidate

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2844]
We've had a lot of changes since the last release candidate so as we come up on RC18 it would be good to make sure we are all set to publish our various projects without any hiccups. Things that come to mind are:

- [ ] **Scala Native** - we added Scala Native support but not sure if we need to do anything else to publish for that
- [x] **ZIO Test Magnolia and JUnit Test Runner** - We added ZIO Test Magnolia and JUnit test runner projects that will be published for the first time. I tried to set these up in a reasonable way but would love another set of eyes from the experts
- [x] **Dotty** - We've dramatically expanded test coverage for Dotty and addressed compatibility issues since last time. I know Scala 2 versions are compatible but anything more we should be doing to publish for Dotty?

Copying @softinio and @mijicd.

**Comment by mijicd** [comment]
I don't think there's anything special require for Dotty and native, but we'll double-check it.

**Comment by adamgfraser** [comment]
Thank you! 🙏

**Comment by softinio** [comment]
Verified dotty we are 100% good and ready here it is it being published successfully for snapshot: 
https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_0.22/

But I don't see any scala native jars being published so we may have a problem there. Will dig more and if issue will work on fixing it asap.

**Comment by softinio** [comment]
I believe we will need to add this plugin to be able to do scala native releases:

https://github.com/portable-scala/sbt-crossproject/

There seems to be a potential problem with the latest release of this plugin though that I am looking into that I want to make sure no issue before proceed with it.

**Comment by softinio** [comment]
All good with using https://github.com/portable-scala/sbt-crossproject/ we need to add this to be able to release native.

Be good to see it work with snapshots before next release.

**Comment by mijicd** [comment]
@softinio can you make a PR with this one? We should be able to verify the outcome immediately :).

**Comment by softinio** [comment]
@mijicd yeah I was planning on doing that to `actors` first to verify before `zio`, but I don't think I have bandwidth to get to it done for one to two weeks, do you have time to tackle it and tag me to review by any chance before then? Else I will of course.

**Comment by mijicd** [comment]
@softinio I'll play with it today.

**Comment by mijicd** [comment]
@softinio this plugin is already part of the project, I'm investigating the issue further.

**Comment by ghostdogpr** [comment]
- Dotty was released well: https://repo1.maven.org/maven2/dev/zio/zio_0.22/1.0.0-RC18-1/
- The JUnit Runner too: https://repo1.maven.org/maven2/dev/zio/zio-test-junit_2.13/1.0.0-RC18-1/
- I don't see ZIO Test Magnolia. And indeed it's missing in the big `aggregate(...)` in build.sbt
- Scala Native is still TODO as mentioned above
