### ISSUE TITLE
ZIO Test: Make it Easier to Configure Number of Property Based Tests

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2851]
Currently we can configure the size of generators using the `Sized` service but we can't configure the number of times to run a property based test without changing our code to use `checkN` instead of `check`. It could be nice to be able to continue to write tests with `check` but have those tests access some parameter with the number of times to run property based tests. This could be used, for example, to run all property based tests fewer times on Scala JS versus the JVM if tests are already taking longer on Scala JS.

We could potentially all do this through the `size` parameter but it seems like we have distinct concepts here (we might want our generator to still be the current size but to run all tests half as many times).

Conceptually we could do this either by adding additional parameters  to `Sized` or by adding additional services similar to `Sized`. The advantage of doing everything through one service is we avoid a proliferation of services but we also lose some specificity in our ability to see what dependencies an effect uses (e.g. a sized generator needs to be able to access the generator size but doesn't need to know anything about the test count). The alternative is adding another service.

One other thing we may want to think about in a similar vein is whether it is worth making the number of times to repeat a test with `nonFlaky` configurable in the same way.

@jdegoes What do you think?

**Comment by jdegoes** [comment]
I think the tradeoffs are exactly as you list them.

I think I'd prefer a single `TestConfig` or something trait that exposes 3-6 pieces of data that are used during the test, things like:

 - default number of retries
 - default number of repetitions
 - default number of samples
 - default size of generated values
 - etc.

Basically "ZIO Test Default Settings". These settings don't have to be effectful, this could just be a case class with static settings (with the new environment encoding).

**Comment by adamgfraser** [comment]
Yes I think that is more scalable if we are going to have more than just one more piece of data. I will work on this.
