### ISSUE TITLE
ZIO Core: Add temporary DefaultRuntime to assist with migration

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2873]
I think we should bring back a backward-compatible `DefaultRuntime` for RC18 and ship it `@deprecated` so that people will know it's going away in 1.0. This will assist with the migration. Also in the docs we can point people to the more official way to do things: with the bootstrap runtime and `provideLayer`.

To implement this ticket:

 - Dig back into RC17 code and look at `DefaultRuntime`
 - Implement new `DefaultRuntime` with the same methods; it will use `Runtime.unsafeFromLayer` in order to create the `ZEnv` environment that is used by all the `unsafeRun` methods
 - Add Scaladoc to describe the new preferred way, which is to use `Runtime.global` and provide layers directly via `ZIO#provideLayer`; explaining that, in general, layers are managed resources and require allocation and deallocation and therefore that scoping their resources is highly recommended as a best practice, but pointing to `Runtime.unsafeFromLayer` as a fallback that can be used when the 'best practice' is too inconvenient

**Comment by adamgfraser** [comment]
I’ll take this.
