### ISSUE TITLE
ZIO.cached doesn't work for ttl = Duration.Infinity

### ISSUE THREAD

**Issue by HansBrende** [zio/zio#2876]
```
println(unsafeRun(for {
    ref <- Ref.make(0)
    getAndIncrement = ref.modify(curr => (curr, curr + 1))
    cached <- getAndIncrement.cached(Duration.Infinity)
    a <- cached
    b <- cached
    c <- cached
} yield (a, b, c)))
```
prints:
```
(0, 1, 2)
```
expected output:
```
(0, 0, 0)
```

Also, please note the javadoc on `System.nanoTime()`:

> To compare two nanoTime values
> 
>  long t0 = System.nanoTime();
>  ...
>  long t1 = System.nanoTime();
> one should use t1 - t0 < 0, not t1 < t0, because of the possibility of numerical overflow.

https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.
