### ISSUE TITLE
Rationalize Redundant Methods

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2900]
I noticed that with some of our recent additions we have a couple of methods that do the same thing:

```scala
  /**
   * Maps the error value of this effect to the specified constant value.
   */
  final def asError[E1](e1: => E1)(implicit ev: CanFail[E]): ZIO[R, E1, A] =
    mapError(new ZIO.ConstFn(() => e1))

  /**
   * Executes this effect and returns its value, if it succeeds, but
   * otherwise fails with the specified error.
   */
  final def orElseFail[E1](e1: => E1)(implicit ev: CanFail[E]): ZIO[R, E1, A] =
    orElse(ZIO.failNow(e1))
```

```scala
  /**
   * Executes this effect and returns its value, if it succeeds, but otherwise
   * returns the specified value.
   */
  final def fallback[A1 >: A](a: => A1)(implicit ev: CanFail[E]): ZIO[R, Nothing, A1] =
    fold(_ => a, identity)

  /**
   * Executes this effect and returns its value, if it succeeds, but
   * otherwise suceeds with the specified value.
   */
  final def orElseSucceed[A1 >: A](a1: => A1)(implicit ev: CanFail[E]): URIO[R, A1] =
    orElse(ZIO.succeedNow(a1))
```

Does anyone have a preference for which versions we should keep?

**Comment by jdegoes** [comment]
I like the `orElse` variants because they are at least part of the same family, with consistent naming.

OTOH `asError` mirrors `as` and there is precedent for that pattern across the combinators.

🤷‍♂

**Comment by marktoujiline** [comment]
What advantage does `asError` or `orElseFail` provide over `mapError`? 
```
effect.asError(new Exception("err"))
effect.orElseFail(new Exception("err"))
effect.mapError(_ => new Exception("err"))
```

**Comment by adamgfraser** [comment]
@marktoujiline Just ergonomics. saves you from having to write a function that ignores its input when you just want to map the error to a constant value.

**Comment by marktoujiline** [comment]
Reason I'm asking is ZIO has so many ways to handle errors it can be overwhelming, especially for someone starting out (like me). I'd prefer having just `mapError` and `flatMapError` if possible. The smaller the surface area of ZIO, the easier it is to learn.

**Comment by adamgfraser** [comment]
I hear you. I think the ship has kind of sailed on that because there is another set of people who want the more specific combinator for their use case. My advice for a beginner would be that essentially every error handling combinator is implemented in terms of `foldM` so if you use that you will never be wrong and then there is probably a more specific variant for your use case.

**Comment by HansBrende** [comment]
I personally like the `orElse` variants better, because they seem less ambiguous.

If `as` is mapping a success to a success, `asError` sounds like you are mapping a success to an error, when it is really mapping an error to an error.

**Comment by HansBrende** [comment]
@adamgfraser does my above comment seem reasonable to you?

**Comment by adamgfraser** [comment]
@HansBrende Yes. I don't have a strong opinion on which ones to keep so was leaving this open but you and @jdegoes both expressed some preference for the `orElse` variants. I think that makes sense and no one has spoken up for the alternative so will go ahead and implement that.

I agree that a combinator that just fails something with a value could make sense. You can already do it easily with `zio *> fail(e)` but obviously that hasn't stopped us from writing these other combinators so not opposed to it. Agree that `asError` could conceptually make sense but we definitely can't do that without first having a version with it removed because of the current version with a very different meaning. `failWith` came to me off the top of my head.

Also not sure we need to be in a rush to add this. No one seems to be beating down the door for it and we do have a lot of methods on ZIO already.
