### ISSUE TITLE
Create provideCustomLayer

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2907]
In many user-cases, `provideSomeLayer` will be utilized:

 - to provide the non-ZEnv part of the environment
 - to provide the non-(ZEnv + test) part of the environment (ZIO Test)

We could have helpers, `provideCustomLayer`, affixed to the data types, which simply call `provideSomeLayer`, and which fix the remainder to be ZEnv (in ZIO Core) and ZEnv + TestEnvironment (in ZIO Test).

Then a lot of user-land tests could be simplified to `spec.provideCustomLayer(myCustomLayer)`, and a lot of `App` run functions could switch to using `provideSomeLayer`.

**Comment by adamgfraser** [comment]
I will take this.
