### ISSUE TITLE
Provide a RTS object implementation for direct use of unsafeRun

### ISSUE THREAD

**Issue by fanf** [zio/zio#291]
AFAIK, there is no object in ZIO that can be called directly for `unsafeRun`, something like `object JvmRunner extends RTS`. That raises a number of questions, especially for new commers. Perhaps there is some rationals for it, but I didn't found them, and questions on gitter/twitter didn't pointed to a clear answer. 

I know that there is the `App` trait, I know that you can just `new RTS{}.unsafeRun`, but these options are not very satisfactory at least in the following cases:

- because they raise question like "why do I need to do that each time? What am I missing? If nothing, why the lib doesn't just provide it?"
- when you want to test something in the REPL,
- its variatiation: when you want to test a `IO` in isolation, 
- when you want to integrate a little bit of ZIO in an impure app and you need to locally run one `IO[E,T]` that you successfully integrated in stealth mode in the project,

So, following the request here (https://gitter.im/scalaz/scalaz-zio?at=5bbceeb06e5a401c2d4205bc), I'm opening that ticket to discuss the subject.

**Comment by jdegoes** [comment]
It's possible. The question is what kind of thread pool to create to make such an operation sane (probably unbounded, which quickly retires unused threads).

Also if it exists people will use it, which may lead to troubles common to using global thread pools. 😄

**Comment by karolchmist** [comment]
Inside the package object zio:

```scala
package object zio {
  // the default rts which uses scala default thread pools:
  private val defaultRts =  new RTS { /* overrides go here */ }

  // all unsafe run methods
 def unsafeRun...
}
```

Delegate the thread pools to existing globals in Scala (e.g. global execution context).

This may in some cases require adapters from `ExecutionContext` etc to whatever ZIO uses.

TODO: Is there something like a default scheduled executor sitting around in Scala, or must the actor system be used for the scheduled executor that ZIO requires???

**Comment by fanf** [comment]
For reference, there is a default implementation provided since I-don't-remember-what-1.0-RC:

```
zio.Runtime.default.unsafeRun()
```

**Comment by adamgfraser** [comment]
@fanf Thank you! 🙏
