### ISSUE TITLE
Update "How to > Use Module Pattern" docs in view of ZLayer

### ISSUE THREAD

**Issue by zach-albia** [zio/zio#2938]
Now that we have `ZLayer`, an update on structuring large ZIO programs would be a great help to newcomers along with a separate page for `ZLayer`.

**Comment by adamgfraser** [comment]
Yes, updating the documentation on the website is one of the last gating items for `ZLayer` being ready for RC18.

**Comment by adamgfraser** [comment]
I also think as part of this we should move away from using `>` as part of the module pattern. See further discussion at https://github.com/zio/zio-macros/issues/101.

**Comment by zach-albia** [comment]
> Yes, updating the documentation on the website is one of the last gating items for ZLayer being ready for RC18.

Is someone already working on this? If not, would like to lend a hand here.

**Comment by pierangeloc** [comment]
I am rewriting this how to with `ZLayer` should open a PR in a few hours. Maybe you could take care of documenting the mocking updates?

**Comment by zach-albia** [comment]
> Maybe you could take care of documenting the mocking updates?
@pierangeloc I'll take it.

**Comment by zach-albia** [comment]
I think zio/zio-macros#101 needs to be resolved before the mocking updates page can be updated. Of course, I can always write on the assumption we're moving away from the `>` syntax. Please advise?

**Comment by softinio** [comment]
@zach-albia @pierangeloc Can this issue be closed as we have: 

https://zio.dev/docs/howto/howto_use_layers

and 

https://docs.google.com/document/d/1P0mx1gSNU2UTi-9PXUeY8O74v5gyK-UETznM1SbkQjA/edit#heading=h.tsittnt9c96t

**Comment by zach-albia** [comment]
@softinio Yes, I'll close it then.
