### ISSUE TITLE
ZIO Test: provideManagedShared starts managed 2 times

### ISSUE THREAD

**Issue by gstraymond** [zio/zio#2939]
This simple test with an environment runs `Managed.succeed(println("managed acquired"))` 2 times although I use `provideManagedShared`.

```scala
import zio.test.Assertion._
import zio.test._
import zio.Managed
import zio.ZIO

object FooSpec
    extends DefaultRunnableSpec(
      suite("foo suite")(
        FooTests.test
      ).provideManagedShared {
        Managed.succeed(println("managed acquired"))
      }
    )

object FooTests {
  val test = testM("foo test")(
    for {
      _ <- ZIO.access[Unit](identity)
    } yield assert(true, equalTo(true))
  )
}
```

Output:

```
managed acquired
managed acquired
[info] + foo suite
[info]   + foo test
[info] Ran 1 test in 691 ms: 1 succeeded, 0 ignored, 0 failed
[info] Done
```

This behavior is producing errors when used with integrations tests where Managed objects are starting servers.

ZIO version: `1.0.0-RC17`

**Comment by adamgfraser** [comment]
@gstraymond I am not able to reproduce your issue on `master` or on `RC17` (see https://scastie.scala-lang.org/hlGVUv8BTeOd8fl1xcRJEQ). What test runner are you using?

**Comment by gstraymond** [comment]
I run the tests from sbt test runner using the configuration here https://zio.dev/docs/usecases/usecases_testing

**Comment by adamgfraser** [comment]
I was able to replicate your issue on RC17 using the SBT test runner. It looks like it has to do with handling of suspending side effects between the test runner and the test framework. In your example, if I do `Managed.effectTotal(println("managed acquired"))` the line is only printed once. So for now I would check that side effects such as starting servers are properly suspended in effect constructors in your `Managed` and in RC18 the test framework will do the right thing regardless.

**Comment by adamgfraser** [comment]
@gstraymond Did this work for you? If so do you want to close?

**Comment by gstraymond** [comment]
Works flawlessly using `effectTotal`, thanks !
