### ISSUE TITLE
ZIO Core: Type Inference Issue with ZLayer.fromServices

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2949]
@mtsokol Identified a type inference issue with `ZLayer.fromServices`:

```scala
type ServiceHas = Has[Service]
trait Service

type ServiceHas2 = Has[Service2]
trait Service2

type ServiceHas3 = Has[Service3]
trait Service3

val live: ZLayer[ServiceHas2 with ServiceHas3, Nothing, ServiceHas] =
  ZLayer.fromServices[Service2, Service3, ServiceHas] { (storage, cache) =>
    Has(new Service {})
  }
// Okay

val liveFailing: ZLayer[ServiceHas2 with ServiceHas3, Nothing, ServiceHas] =
  ZLayer.fromServices { (storage: Service2, cache: Service3) =>
    Has(new Service {})
  }
// found:    (Example.Service2, Example.Service3) => zio.Has[Example.Service]
// required: (Example.Service2, Example.Service2) => zio.Has[Example.Service]
```

It appears that the Scala compiler is trying to infer the types for `fromServices` from the specified return type for `liveFailing` and is inappropriately taking just the left hand side of the `&` instead of both types, maybe because it is not a true intersection type. Assigned to an intermediate `val` and then returning that also works

I can resolve by adding an additional type parameter to `fromServices`:

```scala
  def fromServices1[A0: Tagged, A1: Tagged, A <: Has[A0] with Has[A1], B <: Has[_]](f: (A0, A1) => B): ZLayer[A, Nothing, B] =
    ZLayer(ZManaged.fromEffect {
      for {
        a0 <- ZIO.environment[Has[A0]].map(_.get[A0])
        a1 <- ZIO.environment[Has[A1]].map(_.get[A1])
      } yield f(a0, a1)
    })
```

However, people may need to specify the type parameters since they are contravariant parameters so I think adding another type parameter has a significant cost.

Right now I am somewhat inclined to say at least this solution is not a net improvement and that we should open an issue with the Scala team (the issue appears on Dotty as well) but wanted to put it out there for discussion.

**Comment by mtsokol** [comment]
@adamgfraser Sure, I also think that we can elevate it to Scala team via an issue to check with their evaluation on this.

**Comment by adamgfraser** [comment]
@mtsokol I will open issues.

**Comment by adamgfraser** [comment]
Issues opened at https://github.com/scala/bug/issues/11898 and https://github.com/lampepfl/dotty/issues/8378.

**Comment by adamgfraser** [comment]
Following up on responses from Scala / Dotty teams it sounds like this is a limitation of the compiler.  There was an interesting idea from @smarter that if we do something like this it will work:

```scala
trait Has[A]

trait A
trait B
trait C

trait ZLayer[-RIn, +E, +ROut]

object ZLayer {
  type ZLayer2[-RIn1, -RIn2, +E, +ROut] = ZLayer[RIn1 with RIn2, E, ROut]
  def fromServices[A0, A1, B](f: (A0, A1) => B): ZLayer2[A0, A1, Nothing, Has[B]] =
    ???
}

object Test {
  val live: ZLayer.ZLayer2[A, B, Nothing, Has[C]] =
    ZLayer.fromServices { (a: A, b: B) =>
      new C {}
    }
}
```

This requires introducing this `ZLayer2` type alias and users using that. I tend to think that specifying the type parameters in `fromServices` is not much harder than specifying the argument types of the anonymous function and introducing a bunch of new type aliases is not worth it to solve this problem but open to other perspectives.

**Comment by mtsokol** [comment]
@adamgfraser Sure, it would be an exaggeration to introduce type aliases for that. Let's stay with specifying type params (maybe we can add a mention about it in `fromServices` scaladoc for users encountering it in the future?). Thank you once again for help! 🙂

**Comment by gaelrenoux** [comment]
Potentially linked to this, I've had a compilation error in this. Method something1 is fine, but the compiler fails in something2 on the line `r1 ++ r2`
```scala
import $ivy.`dev.zio::zio:1.0.0-RC18`

import zio.{Has, Tagged, ZIO}

def get[R]: R = ???

def something1[R1 <: Has[_], R2 <: Has[_] : Tagged, E, A](z: ZIO[R1 with R2, E, A]): ZIO[R1, E, A] = {
  val r2 = get[R2]
  z.provideSome[R1] { r1 =>
    val env = r1 ++ r2
    env
  }
}


def something2[R1 <: Has[_], R2 <: Has[_] : Tagged, E, A](z: ZIO[R1 with R2, E, A]): ZIO[R1, E, A] = {
  val r2 = get[R2]
  z.provideSome[R1] { r1 =>
    r1 ++ r2
  }
}
```
Error is: 
```
[error]  found   : r2.type (with underlying type R2)
[error]  required: Nothing
[error]       r1 ++ r2
```

**Comment by adamgfraser** [comment]
I think we can close this as our understanding is that this will not be addressed at the Scala compiler level and we have addressed by deprecating these constructors in ZIO 2.
