### ISSUE TITLE
ZIO Test: Add `diagnose` TestAspect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#2955]
A hypothetical `diagnose` `TestAspect` would be designed to do the following:

 - isolate the test
 - run the test
 - do a localized (not global!) fiber dump at the end of the test (if failed/timed out/etc)
 - detect and print out which fibers are still running and what they're waiting on and where they are

**Comment by adamgfraser** [comment]
I will take this.

**Comment by jdegoes** [comment]
@adamgfraser You're a machine! ❤️🤖😂

**Comment by adamgfraser** [comment]
Closed by #2965.
