### ISSUE TITLE
Mockable - unable to mock methods with type parameters

### ISSUE THREAD

**Issue by thobson** [zio/zio#2978]
Assuming we have a method on a module similar to this:

`def put(key: String, value: String): UIO[Unit]`

we can easily create a capability tag and mockable implementation:

`object put extends Method[Any, (String, String), Unit]`

However this doesn't work if we change the method to:

`def putK[K: Show](key: K, value: String): UIO[Unit]`

I was able to create a capability tag using a class:

`class putK[K: Show] extends Method[Any, (K, String), Unit]`

However I then always get an expectation failure

Please see the attached test case. Is there a workaround for this? Did I misunderstand something?
[zio-testcase.zip](https://github.com/zio/zio/files/4266470/zio-testcase.zip)

**Comment by jdegoes** [comment]
I think `Method` itself will not work for polymorphic methods.

I think that would require `MethodPoly1`, e.g. 

```scala
trait MethodPoly1[In[_], Out[_]] {
  def apply[A]: Method[In[A], Out[A]]
}
```

Maybe there's another way (I am not sure), but in any case, requires some new support in ZIO Test.

**Comment by ioleo** [comment]
@thobson It's not currently supported, but thank you for raising this. I will look into it.
