### ISSUE TITLE
ZIO Core: Improve Rendering of Fiber Dumps

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2981]
There is a lot of great information in fiber dumps about what fibers currently exist, who their parents are, and what they are doing to help diagnose deadlocks or other concurrency issues. However, right now the visualize presentation is not as good as it could be in clearly showing which fibers are parents of another fiber versus siblings. This ticket is to improve the `Fiber.prettyPrintM` to print more useful and easily understandable fiber dumps.

**Comment by simpadjo** [comment]
@adamgfraser what about modifying `Fiber.dumpStr`instead? 
So it first prints the fibers hierarchy tree with minimal inline information and then individual fiber stacktraces via `prettyPrintM` as before?

**Comment by adamgfraser** [comment]
@simpadjo That sounds like a great idea!

**Comment by simpadjo** [comment]
Ok, picking this one then.

**Comment by bogdanmanate** [comment]
Hi @adamgfraser, 
I will give it a try.

**Comment by adamgfraser** [comment]
@simpadjo @bogdanmanate Can you please coordinate?

**Comment by bogdanmanate** [comment]
@simpadjo are you also on the zio discord channel ?
