### ISSUE TITLE
Zlayer docs missing from microsite due to misconfiguration 

### ISSUE THREAD

**Issue by softinio** [zio/zio#3008]
New pages added to docs need to be added to the side bar config here: 

https://github.com/zio/zio/blob/master/website/sidebars.json#L68

Noticed this page was not:

https://github.com/zio/zio/blob/master/docs/howto/use_modules_and_layers.md

Be good to do an audit of the docs to make sure nothing else missing.

**Comment by softinio** [comment]
cc @pierangeloc fyi

**Comment by adamgfraser** [comment]
@softinio Thanks for reporting and sorry about that! Will fix now.
