### ISSUE TITLE
Option[Bug] when running tests from IntelliJ in RC18

### ISSUE THREAD

**Issue by FloWi** [zio/zio#3014]
In RC17 I was able to run the tests from within IntelliJ. I think in RC18 s.th. broke.

I get this error from the ZTestRunner. 
```
Exception in thread "main" java.lang.NoSuchMethodError: zio.test.TestRunner.unsafeRun$default$2()Lzio/test/TestLogger;
	at zio.intellij.testsupport.runner.ZTestRunner$.run(ZTestRunner.scala:37)
	at zio.intellij.testsupport.runner.ZTestRunnerHost.main(ZTestRunnerHost.java:5)
```

Don't know if it's a bug in ZIO Test or something is wrong with IDEA.

**Comment by adamgfraser** [comment]
@FloWi That functionality is powered by [ZIO Intellij](https://github.com/zio/zio-intellij). There is a known issue that it is not providing this functionality right now after the update to RC18 and work is ongoing to update. I would suggest that we close and open an issue there to track progress as I do not believe there is anything we can do from the ZIO Test end at this point.

Copying @hmemcpy.

**Comment by FloWi** [comment]
Good to know, thanks. I'm happy to close it here. I'll open an issue at the ZIO Intellij project.
