### ISSUE TITLE
Add a Docusaurus blog to website

### ISSUE THREAD

**Issue by softinio** [zio/zio#3020]
Docusaurus has blog functionality. So my idea is we add it and use it similar to: 

<https://scalameta.org/mdoc/blog/>

Content we should add to the blog:

- Copy of releases notes
- Newsletter content: Maybe actually have the newsletter content here and email sent is a copy or a link to our blog as an idea
- Write blogs related to new functionality 
- Invite outside contributors to add new blogs via PR

**Comment by jdegoes** [comment]
Would be amazing.

**Comment by radutoev** [comment]
I can look into this one if it's ok.

**Comment by jdegoes** [comment]
@radutoev That would be awesome, thank you!

**Comment by radutoev** [comment]
Any suggestions about a first blog post that I could add? 

Maybe something is already written that would be a good first post.

**Comment by softinio** [comment]
@radutoev What would be great is if you can start off with:

1) Create a blog for each release we did including the release notes and dating the blog the date of the release:

<https://github.com/zio/zio/releases>

2) Create a blog for each newsletter we have published and date the blog the same date as the newsletter was published: 

<https://www.getrevue.co/profile/zio>

3) Write a new blog introducing our blog and welcoming people to contribute blogs to it via PR as a suggestion? Happy with any other ideas you have just thought of this as one idea.

4) Be good to have at the footer of each blog a creative commons license and reminding people to link back to our blog for attribution ... see the footer of my blog for example: 

<https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/>

**Comment by Abhijeetmishr** [comment]
@jdegoes @softinio How about jekyll ?

**Comment by adamgfraser** [comment]
Copying @khajavi.

**Comment by khajavi** [comment]
@Abhijeetmishr The docusaurus has built-in blog support, so we can enable it with minimum effort.

**Comment by jdegoes** [comment]
@khajavi Let's get it turned on and tidied up!

**Comment by khajavi** [comment]
This has been resolved in the #7940 pull request.
