### ISSUE TITLE
Folding on Option[A] with ZIO values no longer compiles

### ISSUE THREAD

**Issue by MaT1g3R** [zio/zio#3026]
This code block below used to compile fine on RC17, but it no longer compiles on RC 18

```scala
case class MyError()
val option: Option[String] = Some("")
val getNewString: IO[MyError, String] = IO.succeed("")
val getString: IO[MyError, String] = option.fold(getNewString)(IO.succeed)
```

**Comment by adamgfraser** [comment]
@MaT1g3R The signature of `succeed` was changed to be by name to provide greater safety in capturing potential unintended side effects so they can be managed by the ZIO Runtime. The Scala compiler does not unify by name and by value functions in your context. You can fix by changing `IO.succeed` to `IO.succeed(_)` in your example.

**Comment by MaT1g3R** [comment]
Thank you, that worked
