### ISSUE TITLE
Add tags to tests / suites to make it easier to run related tests together

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3029]
Currently ZIO Test lets us attach tags to tests and suites, but we're not using that feature.

It would be useful to add tags that allow us to group related tests. For example, all tests of interruption could utilize the tag "interruption", whether they are testing ZIO, ZStream, ZManaged, etc. Similarly, error handling tests could utilize the tag "errors". And so forth.

**Comment by adamgfraser** [comment]
This would be great. I think one thing we could do to build on this would be define a common set of tags, possibly in `ZIOBaseSpec`, so we don't have issues with inconsistent tags (e.g. "interrupt" versus "interruption"). For example:

```scala
trait ZIOBaseSpec {

  object Tags  {
    val interop = "interop"
    val interruption = "interruption"
  }
}
```

We could possibly define our own internal `tag` test aspect that only accepts a `ZIOTag` which is a sealed trait to enforce this further at the type level but that might be overkill.

**Comment by jorge-vasquez-2301** [comment]
@jdegoes @adamgfraser I can work on this 😃

**Comment by adamgfraser** [comment]
@jorge-vasquez-2301 Awesome!
