### ISSUE TITLE
ZIO Core: ZLayer.fromServices should support more than 5

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3037]
It is very common to have more than 5 services being supplied to a module.

Ideally this would be auto-generated so we can have a much larger limit. 
But would be happy if in the short term it could be extended to at least 10.

**Comment by adamgfraser** [comment]
Agreed this is a quick win. I will add this tomorrow.

**Comment by adamgfraser** [comment]
Closed by #3054.
