### ISSUE TITLE
ZIO Core: ZLayer fails to infer types

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3039]
The following will not be represented as ZLayer[A with B, Nothing, C]:

```
  val live = ZLayer.fromServices { (a: A.Service, b: B.Service) => new C.Service {
    val x = 10
    def c: Task[String] = Task("c")
  }}
```

And instead needs to be written as such to be usable:

```
  val live = ZLayer.fromServices[A, B, C] { (a, b) => new C.Service {
    val x = 10
    def c: Task[String] = Task("c")
  }}
```
Likewise for ZLayer.succeed etc.

It would be great if the types could be inferred somehow (can we cast to C?).  Otherwise the [documentation](https://zio.dev/docs/howto/howto_use_layers) should be updated so that every example has the types specified e.g.
```
val layer = ZLayer.succeed[MyService](new Service
```

It is confusing that when adding a simple field to a Service the whole layer becomes unusable. Alternatively, document that all fields should be private:

```
  val live = ZLayer.fromServices[A, B, C] { (a, b) => new C.Service {
    private val x = 10
    def c: Task[String] = Task("c")
  }}
```

**Comment by adamgfraser** [comment]
Yes, I think this is an unfortunate consequence of structural typing and `Has` being invariant. Solutions are:

1. Specify the type parameters to `fromServices` (e.g. `fromServices[A, B, C]`)
2. define any values in the service defintion that do not just implement the service as `private` (e.g. `private val x = 10`)
3. Define a constructor that returns the correct type (e.g `object Service { def apply(x: Int): Service = ??? }`).
4. Specify the return type of your layer (e.g. `val live: ZLayer[A with B, Nothing, C] = ZLayer.fromServices(???)`)

Will think about how we can document this more and I think there are a variety of ergonomic solutions but unfortunately I don't think we can eliminate this entirely.

**Comment by adamgfraser** [comment]
This is addressed by `ZEnvironment` being covariant in ZIO 2.
