### ISSUE TITLE
ZIO Test: Add double implication

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3046]
`(l <==> r) = (l ==> r) && (r ==> l)`

**Comment by WesselVS** [comment]
Seems like a good first issue, I'd like to pick this up

**Comment by adamgfraser** [comment]
Great!

**Comment by WesselVS** [comment]
Here
https://github.com/zio/zio/pull/3049 (not sure how to link that pull request to this issue)

**Comment by adamgfraser** [comment]
@WesselVS Thanks! You can just say "resolves" and the issue number in your PR to link them. Will take a look.
