### ISSUE TITLE
Determine how App exit and ExitStatus should behave

### ISSUE THREAD

**Issue by RaasAhsan** [zio/zio#305]
Since both the default RTS fiber pool and timer pool spawn daemon threads now, the JVM immediately exits when the main thread completes. Unless the pools are intentionally overriden to be non-daemon, it seems like two of the inhabitants of the `ExitStatus` ADT don't serve much purpose anymore: `ExitWhenDone` and `DoNotExit`.

My proposal is to remove the `ExitWhenDone` and `DoNotExit` constructors and instead require the user to program their own termination logic, whether it be to wait on a promise, never complete or exit normally. This is in line with the original intention to daemonize the RTS pool.

**Comment by jdegoes** [comment]
Maybe in combination with an `awaitPending: IO[Nothing, Unit]` method that will resume when no threads are in use?

**Comment by RaasAhsan** [comment]
I'd be interested in hearing how that would work. But if that `IO` is running on the same `RTS` as the one it is shutting down, could possibly run into some issues if we rely on `shutdown` and `awaitTermination`:
- If `Async` is used somehow, the continuation would never be restarted because task submission would be rejected
- Non-terminating `Runnable`s would prevent the pool from shutting down.
- Combining both of the above, attempting to timeout on `awaitPending` wouldn't work in a predictable manner when a non-terminating `Runnable` is still executing: the continuation from `Sleep` would never be invoked because it submits its `Async` computation back to the pool shutting down

**Comment by jdegoes** [comment]
I think #315 demonstrates that the main method being explicit about what to do when the main fiber terminates is a good thing and will minimize user confusion.

**Comment by RaasAhsan** [comment]
There are other factors in #315 that should at least be identified and considered. Regardless of which direction we go, users should understand `App` when they use it. It was difficult in this case, because as OP pointed out:
1. Functionality changed between versions.
2. The consequences of the change weren't properly documented anywhere.

I won't try to fight this anymore, but I can make according changes in #307. I had changed the thread pool to be a `ExecutionContext` from a `ExecutorService` since several users had requested it, so that needs to be reverted if we want to keep the `ExitWhenDone` constructor. We'll also need to introduce some sort of indefinite blocking mechanism for `DoNotExit`.
