### ISSUE TITLE
ZIO Clock: Failure to reflect exception in type

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3052]
Generated by `clock.currentDateTime`, which can apparently throw:

```
java.time.zone.ZoneRulesException: Unknown time-zone ID: America/New_York
```

The fix is to reflect the possibility of failure in the return type. I am not sure if `ZoneRulesException` is the only exception, or if there are others that can be thrown, but they should be reflected in the type and captured via `Task(...).refineOrDie { ... }`.

**Comment by jorge-vasquez-2301** [comment]
@jdegoes I can work on this one 😃

**Comment by adamgfraser** [comment]
@jorge-vasquez-2301 As part of this can we understand when this exception can occur?

**Comment by jdegoes** [comment]
<https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#systemDefault-->

```
DateTimeException - if the converted zone ID has an invalid format
ZoneRulesException - if the converted zone region ID cannot be found
```

The methods we are calling in `package.scala` for `Clock` should be audited for the exceptions they throw, and those exceptions properly reflected in the types.

I know for sure `ZoneId.systemDefault` throws because it did so on my machine and I was totally surprised by it! This is used indirectly in the `currentDateTime` method.

**Comment by adamgfraser** [comment]
Yeah. I wonder if we should have some kind of algebraic data type of valid values so it is impossible for those failures occur. But maybe too much work that is outside our area of focus.
