### ISSUE TITLE
in Java 9 newInstance is deprecated

### ISSUE THREAD

**Issue by octavz** [zio/zio#3060]
Starting with Java 9 `newInstance` is deprecated and the build will throw a warning:

```
zio/test-junit/jvm/src/main/scala/zio/test/junit/ZTestJUnitRunner.scala:31:8: method newInstance in class Class is deprecated: see corresponding Javadoc for more information.
[error]       .newInstance()
[error]        ^
[error] No warnings can be incurred under -Xfatal-warnings.
[error] two errors found
[error] (testJunitRunnerJVM / Compile / compileIncremental) Compilation failed
```

I can make a PR.

**Comment by adamgfraser** [comment]
Please do!

**Comment by contrun** [comment]
I just found the same issue. @octavz  do you mind I make a pr?

**Comment by adamgfraser** [comment]
@octavz Just wanted to check in on this. If you got pulled in other directions sounds like @contrun is able to work on it. Would be good to get this resolved.

**Comment by LeeTibbert** [comment]
I have other fish to fry, but if neither @octavz nor @contrun have time to fix this, let me know and I can take a run at it.

**Comment by LeeTibbert** [comment]
And, of course, as I just discovered, the fix is not as simple as the straight forward textual
substitution described in the Java 9 [doc](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html) for the `newInstance` method.  

I believe that Zio wants to support Java 8 and above.  Different text is needed on J8 vs J9+.

**Comment by LeeTibbert** [comment]
Ah! I see now.  Java * has the getDeclaredConstructor() method, so the obvious substitution
works. Pretty clever deprecation evolution on the part of the Java devos.

@contrun, as a user, thank you for the PR.
