### ISSUE TITLE
ZIO always waits for timeout expiration in acquire/release of bracket

### ISSUE THREAD

**Issue by gaelrenoux** [zio/zio#3065]
Using ZIO 1.0.0-RC18
Effects which are configured with a timeout always wait for the timeout to expire (even when we've had a successful result before that time), when within the acquire or release portion of a bracket.

Here's a piece of code reproducing the issue:
```scala
import zio.duration._
import zio._

object TimeoutTest extends zio.App {

  override def run(args: List[String]): ZIO[ZEnv, Nothing, Int] = {

    def logTime(text: String) =
      clock.currentDateTime
        .map(time => s"$text\t$time")
        .flatMap(console.putStrLn(_))

    def effect(name: String) =
      logTime(s"$name effect: ")
        .timeout(5.seconds)
        .tap(_ => logTime(s"$name timeout:"))

    effect("open ").bracket(_ => effect("close")) { _ =>
      effect("work ")
    }.as(0)

  }
}
```

Prints:
```
open  effect: 	2020-03-08T17:43:28.117+01:00
open  timeout:	2020-03-08T17:43:33.114+01:00 // here we've waited until the end of the timeout
work  effect: 	2020-03-08T17:43:33.115+01:00
work  timeout:	2020-03-08T17:43:33.147+01:00 // but not here
close effect: 	2020-03-08T17:43:33.148+01:00
close timeout:	2020-03-08T17:43:38.148+01:00 // here we've waited again
```

**Comment by neko-kai** [comment]
This is linked to a change in RC18:

> **Safer race**
> Race no longer forces either side to be interruptible. Users may have to perform left.interruptible.race(right.interruptible) to acquire the old behavior (which punched holes in uninterruptible regions); or possibly, left.disconnect.race(right.disconnect) (if they want the effects to be keep running when interrupted, but in the background).

Before, `timeout` would work correctly here, because both sides would be forced interruptible, now neither is, so a `timeout` in bracket can't finish early.

```scala
  final class TimeoutTo[R, E, A, B](self: ZIO[R, E, A], b: B) {
    def apply[B1 >: B](f: A => B1)(duration: Duration): ZIO[R with Clock, E, B1] =
      (self map f) raceFirst (ZIO.sleep(duration) as b) // TODO: Make right-hand side interruptible?
  }
```
