### ISSUE TITLE
Aliases for ZLayer

### ISSUE THREAD

**Issue by octavz** [zio/zio#3066]
@jdegoes, @adamgfraser  

As discussed on Discord, would be very useful to have some extra aliases.
`type Layer[+E, +A] = ZLayer[Any, E, A]`
`type ULayer[A] = Layer[Nothing, A]`

I think ULayer is extra useful in tests, I found myself using it everywhere, `provideLayre(layer)` `layer` is `ULayer` given the fact that `Has` is invariant and we are required to use signature everywhere we have subtypes please consider adding both above and deprecate `NoDeps`.

Thank You

**Comment by adamgfraser** [comment]
@octavz https://github.com/zio/zio/pull/3064.

**Comment by adamgfraser** [comment]
Closed by #3064.
