### ISSUE TITLE
Trick used to support implicit search negation cannot be used with Dotty

### ISSUE THREAD

**Issue by smarter** [zio/zio#3068]
https://github.com/zio/zio/tree/master/core/shared/src/main/scala-2.12%2B/zio contains a bunch of definitions all following the same pattern:
```scala
implicit def neq[A, B]: A =!= B = new =!=[A, B] {}

@implicitAmbiguous("Cannot prove that ${A} =!= ${A}")
implicit def neqAmbig1[A]: A =!= A = unexpected
implicit def neqAmbig2[A]: A =!= A = unexpected
```

This trick is intentionally not supported by dotty, see part 4 of http://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html, instead one should use [`scala.implicits.Not`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/implicits/Not.scala).

While the code as-is will compile with dotty, it will not have the desired behavior and in fact might lead to blowing up compile times as experienced in https://github.com/lampepfl/dotty/issues/8463

**Comment by adamgfraser** [comment]
@smarter Thanks for following up on this! I am working on adding a version specific file that uses the `Not` combinator to address this.
