### ISSUE TITLE
Add "ZLayer#andWith" combinator doing both of `++` and `>>>`

### ISSUE THREAD

**Issue by Baccata** [zio/zio#3084]
I found the `layer0 ++ (layer0 >>> layer1)` pattern to be repeated on several occasions in my project, and made a custom operator for it:  

```scala
  import zio._ 
  implicit class ZLayerOps[RIn, E, ROut <: Has[_]](zlayer: ZLayer[RIn, E, ROut]) {

    def andWith[E1 >: E, ROut2 <: Has[_] : Tagged](other: ZLayer[ROut, E1, ROut2]): ZLayer[RIn, E1, ROut with ROut2] =
      zlayer ++ (zlayer >>> other)

  }
```

Not certain it's something you guys would like to add, but I figure it doesn't hurt to suggest.

**Comment by adamgfraser** [comment]
Yes I think we could potentially use some sort of `passthrough` operator that turns a layer that "hides" its inputs into one that exposes its inputs downstream. Let me work on this.

**Comment by neko-kai** [comment]
Sorry for harsh words, but I believe such an operator should be primary and MemoMap should be phased out in its favor – it's solving the wrong problem by silently caching "private" dependencies, and thereby encourages "private" dependencies, and it breaks referential transparency to do it which it makes it even harder to reason about.

**Comment by adamgfraser** [comment]
@neko-kai Feedback always welcome! I think that gets to a larger design discussion of whether to hide or pass through dependencies. Great to have that here but I am going to continue to proceed with incremental improvements based on existing design pending resolution of that discussion.
