### ISSUE TITLE
ZIO Core: catchSomeDefect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3085]
A hypothetical `catchSomeDefect` would allow responding to a subset of defects:

```scala
sealed trait ZIO[-R, +E, +A] {
  def catchSomeDefect[R1 <: R, E1 >: E, A1 >: A](f: PartialFunction[Throwable, ZIO[R1, E1, A1]]): ZIO[R1, E1, A1]
}
```

/cc @gabro

**Comment by adamgfraser** [comment]
I am working on this.

**Comment by hepin1989** [comment]
Just catchDefect，it accept a partial function,so no need the some word

**Comment by gabro** [comment]
That's perfect, thanks @jdegoes and @adamgfraser

**Comment by adamgfraser** [comment]
@hepin1989 `catchDefect` would imply that it catches all defects, which is not the case. For consistency with other combinators `catchSome` and `catchSomeCause` we definitely need the current name. We could potentially add `catchAllDefect` that would catch all defects.

**Comment by hepin1989** [comment]
@adamgfraser more practical
