### ISSUE TITLE
Uninterruptible race should auto-disconnect children

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#3100]
There was a proposal before to make `race` auto-disconnect to avoid a deadlock caused by interruption inheritance in `x.race(ZIO.never).uninterruptible` ([link](https://github.com/zio/zio/pull/2317#issuecomment-559926500))

> ### Alternate Proposal
> 
> Here's what I want to do: change `race` to _not_ make both sides interruptible; rather, it will use the parent region's interruptibility status to decide what to do:
> 
> 1. If the parent region is NOT interruptible, then we will not interrupt either left or right sides; rather, we will allow the loser of the race to continue operating in the background without affecting the execution of either side.
> 2. If the parent region IS interruptible, this is the user specifying that it is OK to interrupt, so we will make both left and right sides interruptible and interrupt the loser of the race.
> 
> In this fashion, we defer the decision of interruptibility to the call-site, which gives much more flexibility and leads to less surprising behavior:
> 
 > * If I want to make a race uninterruptible, then I can do so, and I can have the guarantee that I get the "fastest success", but it will not interfere with the loser's lifecycle.
>  * If I want to make a race interruptible, or if I don't care (the default is interruptibility), then loser will be interrupted as per current semantics.
> 
> Separately we need to see if `race` is the only problematic combinator. I think any combinator which "forces" interruption without considering the parent region's status is likely to have confusing edge cases like this. So a code audit may identify other areas of potential improvement.

However, the most recent supervision overhaul does not implement this proposal - this leaves `race` unsafe to use in uninterruptible sections, as evidenced by recent bug report https://github.com/zio/zio/issues/3065 - where while the timeout fiber would still leak with the above proposal when uninterruptible; if it was auto-disconnected, it would at least not cause a time leak for the full length of timeout.

Can we / should we go back to the above proposal?

**Comment by jdegoes** [comment]
It's an easy change and may lead to fewer surprises. 👍

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/zio/pull/3125
