### ISSUE TITLE
ZIO Mock: expect no calls

### ISSUE THREAD

**Issue by ioleo** [zio/zio#3115]
Previous ZIO Mock encoding had the `Expectation.nothing` helper which allowed to create mocked services which should not be called. As a follow-up to discussion on discord, there are a few ideas how to support that in the new encoding:

* create empty layers which don't call a Proxy, but immidietly die with MockException
```scala
val empty: ULayer[Has[Service]] = ZLayer.succeed(new Service {
    override def repositoryExists(name: Name): IO[PagerError, Name] = ZIO.die(UnexpectedCallExpection(RepositoryExists, name))
    override def releases(name: Name): IO[PagerError, List[GitHubRelease]] = ZIO.die(UnexpectedCallExpection(Releases, name))
  })
```
* intercept all calls to `A` service at `Has` level, dieing with MockException at `_.get[A]` invocation
* extend the `Expectation` with another case allowing to disallow certain calls (or all calls in extreme case), an equivalent of logical `Not` and use that to handle this case

Ideally the solution should require as little typeing from the developer as possible.

**Comment by ragb** [comment]
any updates on this or any suggested workaround?

**Comment by ex0ns** [comment]
Hello,
I would love to continue the work done on #3641. I re-implemented the changes on the latest version of master and I think it's more or less working but I'm no expert with zio-mocks and I would love to have some feedbacks and pointers about the implementations.

First of all I'm not sure what I should do in the `prettify` method of the Debug object.
I started by creating an object (like it was done before) that looks like:

```scala
  private[test] case class NoCalls[R <: Has[_]: Tag](mock: Mock[R]) extends Expectation[R] {
    override private[test] val invocations: List[Int] = Nil
    override private[test] val state: ExpectationState = Satisfied
  }
```

Should I open a pull requests with the changes I adapted from #3641 so we can discuss about them ?

**Comment by adamgfraser** [comment]
@ex0ns That would be fantastic!

**Comment by pettermachado** [comment]
@ragb I worked around this by creating an optional "fake" expectation without parameters.

```scala
object MockedService extends Mock[Api] {
  private object empty extends Effect[Unit, Nothing, Unit]

  val Empty = empty().optional

  // object SayHello extends Effect[String, Throwable, String]
  // val compose: ...
```

Setting up my testing environment can then be done like
```scala
object ServiceTest extends DefaultRunnableSpec {

  def spec = {
    suite("ServiceTest")(
      testM("get returns a playlist") {
        val testEnv = MockedService.Empty ++ live
        val app = sayHello("...").provideCustomLayer(testEnv)
```

Calling anything on the mocked service will result in an error.

**Comment by ex0ns** [comment]
> @ragb I worked around this by creating an optional "fake" expectation without parameters.
> 
> ```scala
> object MockedService extends Mock[Api] {
>   private object empty extends Effect[Unit, Nothing, Unit]
> 
>   val Empty = empty().optional
> 
>   // object SayHello extends Effect[String, Throwable, String]
>   // val compose: ...
> ```
> 
> Setting up my testing environment can then be done like
> 
> ```scala
> object ServiceTest extends DefaultRunnableSpec {
> 
>   def spec = {
>     suite("ServiceTest")(
>       testM("says hello") {
>         val testEnv = MockedService.Empty ++ live
>         val app = sayHello("...").provideCustomLayer(testEnv)
> ```
> 
> Calling anything on the mocked service will result in an error.
> 
> Edit: typo.

This is actually a pretty nice approach to this issue, and it does not require any changes in ZIO.
@adamgfraser what do you think of this solution ?

**Comment by esthomw** [comment]
@ex0ns @pettermachado It would be great to document it in ZIO `Mock services` section. I think this could also be provided in `Mock` instances.

**Comment by poslegm** [comment]
Hello! Do you need some help here? I really need this feature too and I can make an effort to release it.
