### ISSUE TITLE
Scala.js scala-java-time dependency

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3139]
I brought this up on Discord, but seeing as this might need long-form discussion, thought I'd create an issue.

Basically, it seems like ZIO Scala.js projects require a dependency on `scala-java-time` starting with RC18. When I upgraded one of my Scala projects from RC17 to RC18-2, I started getting errors like:

```
Referring to non-existent class java.time.DateTimeException
  called from zio.clock.package$Clock$Service$$anon$1.currentDateTime()zio.ZIO
...
Referring to non-existent class java.time.ZoneId
  called from zio.clock.package$Clock$Service$$anon$1.$$anonfun$currentDateTime$1(scala.Long)zio.ZIO
...
Referring to non-existent method java.time.Instant$.ofEpochMilli(scala.Long)java.time.Instant
  called from zio.clock.package$Clock$Service$$anon$1.$$anonfun$currentDateTime$4(scala.Long)java.time.Instant
...
```

It seems like the moment you refer to `Runtime.default` you start getting these errors. This wasn't the case with RC17 for reasons I'm not yet sure about...

The easy fix was to add a dependency on `"io.github.cquiroz" %%% "scala-java-time" % "2.0.0-RC5"`, but is there a nicer way of handling this?

These are 2 that I can see:
1. If `scala-java-time` is a hard dependency from here on out, then maybe it should be a transitive dependency from the get-go? Rather than requiring people to manually add the `scala-java-time` dependency themselves after running into these kind of errors.
2. Make the Clock service more lazy somehow, where `scala-java-time` is only needed if you use the parts that require `java.time`. Not sure how doable this is though.

Option 1 is straightforward, but is there a concern about making the generated js files bigger? Or actually maybe that's not an issue if the unused parts get pruned out during optimization anyway.

**Comment by adamgfraser** [comment]
Yes. I think it relates to the slightly different encoding for the default services in RC18-2. Let me see if I can make them lazier.

**Comment by mgenereu** [comment]
Spun my wheels on this until figured out the linking issue had to do with Java Time.  That led me to this mill addition:
`ivy"org.scala-js::scalajs-java-time::1.0.0"`
Didn't solve the issue either.  More spinning and I found this ticket.  This mill addition (as referenced above) solved it:
`ivy"io.github.cquiroz::scala-java-time::2.0.0-RC5"`

**Comment by mgenereu** [comment]
How are the ZIO JS tests running without this?

**Comment by adamgfraser** [comment]
I don't know if there is some specific issue with Mill but in general all you have to do is add a `java-time` dependency.

**Comment by reibitto** [comment]
I just checked and can confirm what @mgenereu is seeing. `scalajs-java-time` doesn't work (getting those non-existent class errors). `scala-java-time` works fine though and it's what I've been using without issue since when I first created this issue.

**Comment by adamgfraser** [comment]
Yes the issue is that `scalars-java-time` doesn't implement all the methods of `java-time`. That's why we switched.

**Comment by mgenereu** [comment]
To clarify two points:

- It's no longer optional and since I wasn't using Clock, I ignored the suggestion on https://zio.dev/docs/interop/interop_javascript . Other research on the linking error I was getting led me to the ScalaJS java-time dependency instead.
- The ScalaJS java-time dependency doesn't work. I don't know why.

Here's the code that failed without Clock.
```scala
import zio._
import zio.console._

object Main extends App {
  def run(args: List[String]) = {
    for {
        _ <- putStrLn("Hello world!!!")
    } yield ExitCode.success
  }
}
```

Nothing to do with mill.

**Comment by mgenereu** [comment]
Heh... didn't see your comments until after I hit submit.  Would you like me to update the docs now that it's not optional or do you think that's going to change back?

**Comment by reibitto** [comment]
Also to answer your question @mgenereu, the reason why the tests work is because of this line:
https://github.com/zio/zio/blob/deb11439336658dd4a4e4aa7819dd83a3e2be3ef/project/BuildHelper.scala#L331

However, this is a Test dependency. Since `scala-java-time` is effectively a requirement currently (wasn't the case before), I'm not sure it should be marked as Test anymore. Unless Clock can be made more lazy which was one idea I mentioned in the original post.

**Comment by adamgfraser** [comment]
I think documentation update would definitely be good. I wonder if we should just add it as a dependency in ZIO on Scala.js. The idea of the current setup is that we are zero dependency and the user just has to bring their own `java-time` dependency. But to my knowledge there is only one dependency that actually fully implements the interface and you need to have some dependency so I wonder if we are really gaining anything here since practically everyone is going to need to add this dependency and we're just creating friction in people needing to do this / not knowing they need to do this / adding the wrong dependency.

**Comment by mgenereu** [comment]
It's not a typical dependency in the library sense.  It's part of fixing ScalaJS to get it to work.  These dependencies are already there to make everything work:

```
├─ dev.zio:zio_sjs1_2.13:1.0.0-RC21-2
│  ├─ dev.zio:izumi-reflect_sjs1_2.13:1.0.0-M2
│  │  ├─ dev.zio:izumi-reflect-thirdparty-boopickle-shaded_sjs1_2.13:1.0.0-M2
│  │  │  ├─ org.scala-js:scalajs-library_2.13:1.0.1 -> 1.1.0 (possible incompatibility)
│  │  │  │  └─ org.scala-lang:scala-library:2.13.3
│  │  │  └─ org.scala-lang:scala-library:2.13.3
│  │  ├─ org.scala-js:scalajs-library_2.13:1.0.1 -> 1.1.0 (possible incompatibility)
│  │  │  └─ org.scala-lang:scala-library:2.13.3
│  │  └─ org.scala-lang:scala-library:2.13.3
│  ├─ dev.zio:zio-stacktracer_sjs1_2.13:1.0.0-RC21-2
│  │  ├─ org.scala-js:scalajs-library_2.13:1.1.0
│  │  │  └─ org.scala-lang:scala-library:2.13.3
│  │  └─ org.scala-lang:scala-library:2.13.3
│  ├─ org.scala-js:scalajs-library_2.13:1.1.0
│  │  └─ org.scala-lang:scala-library:2.13.3
│  └─ org.scala-lang:scala-library:2.13.3
```

**Comment by adamgfraser** [comment]
Yes. I think that is a fair argument.

**Comment by mgenereu** [comment]
Want a PR for this or is it easy, peasy for you?
