### ISSUE TITLE
Random range functions

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3146]
I feel Random might benefit from range variants for generating random numbers, like `nextInt(low, high)` (or `nextIntRange(low, high)` if you'd rather not use overloading).

Reason being for convenience considering that it's a very common operation. And to avoid mistakes like https://github.com/zio/zio/issues/3141. At a glance it's not easy to tell there's a bug there.

**Comment by adamgfraser** [comment]
Yes I think so too. Also the Scala standard library added `between` variants to `scala.util.Random`  for that so I think we need to add to maintain parity with that functionality. I was running into the same thing in fixing #3141 so can fold into that. We should largely be able to pull existing functionality from the generators for those ranges up into `Random`.

**Comment by reibitto** [comment]
Oh nice, I didn't realize they added that in Scala 2.13 (still stuck on 2.12 on some of my projects). Then yeah, I agree that it makes sense to match the naming. Least amount of surprise that way.
