### ISSUE TITLE
ZIO Test: include source location traces for all test executions

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#3152]
To improve the usability of ZIO Tests when running with external runners (such as IntelliJ), it would be very helpful to have the exact source information (preferably, `filename:line_number`) of the executing tests. This would allow adding features such as navigation to the exact test, or, in case of failures, going to the exact line that failed.

Perhaps traces could be added with annotations?

**Comment by hmemcpy** [comment]
For what it's worth, I've been experimenting with Li Haoyi's [sourcecode](https://github.com/lihaoyi/sourcecode) library, and it seems to work!
![image](https://user-images.githubusercontent.com/601206/80281471-0ae38500-8714-11ea-8a41-33d3e50ccd6b.png)

This was done by adding two implicits to `test`/`testM` and storing them as annotations:
```
def testM[R, E](label: String)(assertion: => ZIO[R, E, TestResult])
                 (implicit file: sourcecode.File, line: sourcecode.Line): ZSpec[R, E] =
   ...
```
No further changes to user code were required.

**Comment by davidpdrsn** [comment]
This would be really useful when running tests on the command line as well. Currently getting a failure like `true did not satisfy equalTo(false)` isn't very helpful when you have several assertions chained with `&&`. A line number would be very nice.

**Comment by hmemcpy** [comment]
I'd like to work on this during the hackathon!

**Comment by hmemcpy** [comment]
@davidpdrsn sorry for the delay, but your request,

>This would be really useful when running tests on the command line as well. Currently getting a failure like true did not satisfy equalTo(false) isn't very helpful when you have several assertions chained with &&. A line number would be very nice.

Is addressed by @dkarlinsky's work on #4427, which is also the basis of my own PR for the file/line numbers.

Hopefully coming soon :)

**Comment by davidpdrsn** [comment]
I'm sorry but I can't answer that. I have moved jobs and don't work with Scala anymore. Feel free to ignore that I wrote earlier.

**Comment by hmemcpy** [comment]
Oh, well if you return to Scala there will be nice helpful error messages waiting for you :)
