### ISSUE TITLE
ZIO.fromServices causes IntelliJ to run out of memory in v1.0.0-RC18-2

### ISSUE THREAD

**Issue by HansBrende** [zio/zio#3156]
I had something like 

```
val live: ZLayer[A with B with C with D, Nothing, R] = 
    ZLayer.fromServices[A.Service, B.Service, C.Service, D.Service, R.Service](makeService)
```

which worked fine in  v1.0.0-RC18-1, but caused IntelliJ to run out of memory and freeze every time I had that source code file open when I updated to v1.0.0-RC18-2.

In v1.0.0-RC18-2, when I replaced it with
```
val live: ZLayer[A with B with C with D, Nothing, R] = {
    val _ = makeService(???, ???, ???, ???)
    ???
}
```
memory was normal.

This is probably an IntelliJ bug or a Scala plugin bug, but I thought I should bring it to your attention anyway.

Tested on IntelliJ IDEA Ultimate 2020.1 EAP and 2019.3.3, with the latest scala plugin versions for those two IntelliJ versions. My IntelliJ max heap size was 4096M.

**Comment by adamgfraser** [comment]
Thanks for reporting!

This issue has been discussed on Discord as well. Our current understanding is that the new environment encoding created the issue in RC18-1 as well but that these issues were exacerbated by the addition of higher arity variants of layer constructors in #3054. Some users like you have reported that things worked fine in the RC18-1 though others report experiencing the issues there as well. So our current belief is that the issue existed in both versions but is more salient for some users given system specific details.

There is an open issue with Intellij [here](https://youtrack.jetbrains.com/issue/SCL-17210) that I would encourage you to voice your support for. Beyond that we could potentially remove the higher arity variants temporarily though a fix on the Intellij side really seems like the right answer given that this would be removing functionality to satisfy a certain IDE and does not even seem to fully resolve the issue.

**Comment by mikail-khan** [comment]
@adamgfraser I did an experiment by commenting out all the arities beyond 5 parameters and the memory issue still occurs. Adding this information here for completeness.

**Comment by adamgfraser** [comment]
@mikail-khan Thank you! From the latest reports we are getting and the status of [this](https://youtrack.jetbrains.com/issue/SCL-17221) issue it appears that the problem has been resolved. Are you able to try the latest nightly and see if that fixes it for you?

**Comment by HansBrende** [comment]
@adamgfraser I have tried the latest nightly build, can confirm that it fixed the issue for me.

**Comment by adamgfraser** [comment]
@HansBrende That's fantastic! Shall we close this issue then?

**Comment by mikail-khan** [comment]
@HansBrende please could you feedback on that JetBrains ticket so their developer knows. He was asking for feedback on his fix. Thank you

**Comment by HansBrende** [comment]
@adamgfraser @mikail-khan sure.
