### ISSUE TITLE
Packages are pushed to `staging`, not `snapshot`

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio#316]
follow-up on https://github.com/scalaz/scalaz-zio/pull/261

---

Apparently we now don't publish to snapshot artefacts [`snapshots`](https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/) but to [`staging`](https://oss.sonatype.org/content/repositories/staging/org/scalaz/scalaz-zio_2.12/)

@NeQuissimus suspects that it's an issue with Sonatype, opened https://issues.sonatype.org/browse/OSSRH-42907

**Comment by NeQuissimus** [comment]
Oh, I forgot about this! I will provide them with a new Gist

**Comment by ghostdogpr** [comment]
Closing this since we are properly releasing snapshots now
