### ISSUE TITLE
Race Sink not working as I expect

### ISSUE THREAD

**Issue by politrons** [zio/zio#3166]
Hi all, 
I'm following documentation of ZStream and ZSink. I'm trying to use the race operator since I consider it could be pretty useful, but somehow I cannot make it works as I expect.

Just like the documentation  said, the sink that process the input and generate the output faster win.
Well having this example

 ```
 @Test
  def sinkRace(): Unit = {
    val sink1 = Sink.fromFunction[String, String](_ => {
      Thread.sleep(1000)
      "First sink win"
    })
    val sink2 = Sink.fromFunction[String, String](_ => {
      Thread.sleep(1)
      "Second sink win"
    })
    val raceSink= sink1.race(sink2)
    val program =
      ZStream("Ladies and Gentleman, start your engines")
        .run(raceSink)
    println(unsafeRun(program))
  }
```

Where obviously the second sink should always win since he is delaying just 1 ms against the 1000 of the first, I see that the stream wait for a second, and then the first Sink always win.

I'm doing something wrong here?

Regards

**Comment by vasilmkd** [comment]
`Sink.fromFunction` expects a pure function, which is not what you have provided, given the `Thread.sleep`. I suggest evaluating an effect with `Sink.fromEffect`, in which you will use `Clock` to `sleep` for a given duration, and you should see the correct behavior.

**Comment by vasilmkd** [comment]
I'll write a snippet, just give me a moment.

**Comment by vasilmkd** [comment]
I guess there is an issue after all, looking into it.

**Comment by vasilmkd** [comment]
@iravid We have implemented `ZSink#race` to mean the first sink to successfully finish (i.e. produce a value) wins, however we do not race effects inside the implementation (in fact we use `zipPar` which waits for both effects to finish. Technically, we are not racing the effects that these sinks execute, but rather the sinks as a whole, which are state machines, and we allow them to progress until they report an error (even though this technically means that we don't care about the individual effects that they execute, as in the code above). Is this unintuitive? I don't have a strong opinion on this, to be honest.

**Comment by iravid** [comment]
Sure, racing the effects in Sink#race would be an improvement over waiting for both sides in every step. Though it may complicate the code considerably, because on subsequent steps, you have to wait for the other side to finish. The benefit would only be apparent when stepping and then immediately extracting, like in the example.

**Comment by simpadjo** [comment]
@iravid @vasilmkd this one works now. Let's close it
