### ISSUE TITLE
Don't overload methods with completely different signatures and the same arguments

### ISSUE THREAD

**Issue by alexknvl** [zio/zio#3172]
In `StreamEffect`:
```scala
def fail[E](e: => E): StreamEffect[Any, E, Nothing]
def fail[E, A](e: E): A = throw Failure(e)
```
I am surprised that anything in that code works with these overloads, considering that the second method is *polymorphic in its return value* and both are polymorphic in their arguments!

**Comment by adamgfraser** [comment]
I will fix this.
