### ISSUE TITLE
ZIO Core: Add option

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3178]
It is very common when wrapping APIs to see the following style of method:
```
getObject: Task[Object]
```
i.e. where it either returns the object or throws an exception.

We have Task.either which allows you to convert this to an either. But it would be nice as well to have Task.option as sometimes I don't care about why it failed.

**Comment by ghostdogpr** [comment]
It's already there no? https://javadoc.io/doc/dev.zio/zio_2.12/latest/zio/ZIO.html#option(implicitev:zio.CanFail[E]):zio.URIO[R,Option[A]]

**Comment by adamgfraser** [comment]
The other combinator you may want to look at is `Task#getOrFail` if you want to lift an optional value into a `Task`.

**Comment by nadenf** [comment]
Really not sure how I missed that. Closing !
