### ISSUE TITLE
ZStream, merge multiple effectful streams provokes unknown Fiber interrupt

### ISSUE THREAD

**Issue by fcabouat** [zio/zio#3200]
Hi,

I think I might have found a bug when merging 3 streams ? Am I doing something wrong here ?

```scala
import zio._
import zio.clock._
import zio.duration._
import zio.random._
import zio.stream._
import zio.console._

object Main extends scala.App {

  val eff = {
    val s1 = ZStream
      .fromEffect(for {
        i <- nextInt(100)
      } yield i)
      .repeat(Schedule.fixed(100.millis))
    val s2 = ZStream
      .fromEffect(for {
        i <- nextInt(100)
      } yield i + 1000)
      .repeat(Schedule.fixed(100.millis))
    val s3 = ZStream
      .fromEffect(for {
        i <- nextInt(100)
      } yield i + 2000)
      .repeat(Schedule.fixed(100.millis))

    val s = s1.merge(s2).merge(s3)

    for {
      _ <- s.foreach(i => putStrLn(i.toString))
    } yield ()
  }

  Runtime.default.unsafeRun(eff.provideLayer(ZEnv.live))
}
```

INFO  2020
INFO  35
INFO  1040
ERROR Exception in thread "main" zio.FiberFailure: Fiber failed.
ERROR An interrupt was produced by #8.
ERROR No ZIO Trace available.

https://scastie.scala-lang.org/ERbRyMh0QOCyXcENPHXi8w

Regards,

**Comment by iravid** [comment]
Hi @fcabouat, which ZIO version is this?

**Comment by tylerprete** [comment]
@iravid I can reproduce on 1.0.0-RC18-2

**Comment by fcabouat** [comment]
Same version for me, 1.0.0-RC18-2 and 1.0.0-RC18 in the Scastie :)

**Comment by iravid** [comment]
Thanks for the info @fcabouat and @tylerprete. This appears to be the same problem we had with `ZManaged#zipWithPar`. A workaround fro now is `ZStream.mergeAll(3)(s1, s2, s3)` - that works correctly in the scastie you attached.

**Comment by fcabouat** [comment]
Thanks, the workaround also works on my real case and even looks cleaner !

**Comment by guizmaii** [comment]
@fcabouat Is it still an issue with ZIO2? Closing, feel free to ask for re-opening if you still have the issue in ZIO 2
