### ISSUE TITLE
ZIO Macros: add optional wrapper for accessors

### ISSUE THREAD

**Issue by ioleo** [zio/zio#3203]
As pointed out by DmytroOrlov on discord:
> I'm not very happy with removing `>` so `HttpClientCfg.>.config` will be just `HttpClientCfg.config`
> now in intellij idea navigation by `Cmd+B` jumps to Helper Object instead of needed
> `HttpClientCfg.Service.config` method (it's regression for me :frowning: )

To resolve this we should add an optional argument to `@accessible` macro, eg `@accessible(">")` that if defined, will be the name of wrapping object.

Examples: 

```scala
@accessible
object HttpClientCfg {
  trait Service { ... }
  // accessors generated directly here
}
// use HttpClientCfg.foo
```

```scala
@accessible(">")
object HttpClientCfg {
  trait Service { ... }
  object > { /* accessors generated in wrapping object */ }
}
// use HttpClientCfg.>.foo
```

```scala
@accessible("Service")
object HttpClientCfg {
  trait Service { ... }
  object Service { /* accessors generated in wrapping object */ }
}
// use HttpClientCfg.Service.foo
```

**Comment by neko-kai** [comment]
The accessor object should inherit from `Service` for the method to be resolved to the `Service` method in IDE - otherwise it will still be the object's method. I think @DmytroOrlov means the version of module pattern with type parameter specifically:

```scala
@accessible(">")
object HttpClientCfg {
  trait Service[-R] { ... }
  object > extends Service[Any] { /* accessors generated in wrapping object */ }
}
```

**Comment by jjkv** [comment]
hi, is this still up for grabs? i've been motivated to get involved with contributing to zio and this seems like a good first issue for me

**Comment by neko-kai** [comment]
@jjkv By all means, go ahead 👍

**Comment by guizmaii** [comment]
Accessor pattern as been deprecated. Closing
