### ISSUE TITLE
Missing API for `ZSchedule` which takes a list of durations

### ISSUE THREAD

**Issue by fanf** [zio/zio#3205]
Sometime, we want to exexcute a given action after specific (user provided) intervals of time, and it would be handy to have a pair of API for that: one matching `fixed` semantic, and one matching `spaced` one. 

I imagine a combinator taking a list of durations for parameter, and building the corresponding schedule so that: 
```
// start action for each of the provided times: 
val s1 = ZSchedule.startAt(0 second :: 2 minutes :: 5 minutes :: Nil)

// start action at 0s, then 2min after end of first action, then 5 minutes after end of second action
val s2 = ZSchedule.startSpacedBy(0 second :: 2 minutes :: 5 minutes :: Nil)
```
(I will let you choose better names

**Comment by adamgfraser** [comment]
`Schedule.fromIterable`?

**Comment by adamgfraser** [comment]
@jeremyrsmith You still working on this?

**Comment by jeremyrsmith** [comment]
@adamgfraser I think it will be easy for someone more familiar with `Schedule`... I realized I don't actually grok it that well.

**Comment by adamgfraser** [comment]
@jeremyrsmith Okay. I will take it.
