### ISSUE TITLE
Stream randomly does not completes

### ISSUE THREAD

**Issue by fillson-shady** [zio/zio#3213]
Hello!

I use zio together with [zio-grpc](https://github.com/scalapb/zio-grpc) and have strange behaviour in case of bidirectional streaming. I run same test multiple times and it randomly fails or passes.  

The problem is in stream closing on the client side. Client code looks like:
```scala
_ <- GrpcClient.transmitRetry(Stream.fromQueue(sendQueue), Schedule.fixed(30.seconds)) { response =>
  for {
    head <- dataQueue.take
    tail <- dataQueue.takeUpTo(response.demand - 1)
    data <- ZIO.collectAll((head +: tail).collect {
      case Take.Value(value) => ZIO.some(value)
      case Take.Fail(cause)  => log.error("Failed to send some data", cause) *> ZIO.none
      case Take.End          =>
        val waitComplete =
          resultsQueue.take.doUntilM(cnt => sentCount.get.map(_ == cnt)) *>
          sendQueue.shutdown
        log.info("Data stream completed") *>
        waitComplete.fork *>
        ZIO.none
    }).map(_.flatten)
    _    <- sendQueue.offerAll(data)
    _    <- sentCount.update(_ + data.size)
  } yield ZIO.unit
}
```
where `GrpcClient.transmitRetry` is auto-generated gRPC stub with zio retry logic.   

Internally bidirectional call looks very simple:
```scala
Stream
      .bracketExit[Status, StreamingClientCallListener[Res]](
        StreamingClientCallListener.make[Res](call)
      )(anyExitHandler(call))
      .flatMap { listener: StreamingClientCallListener[Res] =>
        val init = Stream
          .fromEffect(
            call.start(listener, headers) *>
              call.request(1)
          )
          .drain
        val sendRequestStream = (init ++ req.tap(call.sendMessage) ++ Stream
          .fromEffect(call.halfClose())).drain
        sendRequestStream.merge(listener.stream)
      }
```

As I assume 2 streams must be closed to finish call - first is `sendRequestStream` which corresponds to client requests, second - `listener.stream` are responses from server.  

Client requests stream is correctly closing from the code in first listing by calling `sendQueue.shutdown`.  

Server responses stream is also always correctly closing from the `StreamingClientCallListener`:  
```scala
class StreamingClientCallListener[Res] {

override def onClose(status: Status, trailers: Metadata): Unit =
    runtime.unsafeRun(queue.offer(Left((status, trailers))).unit)

  def stream: ZStream[Any, Status, Res] =
    ZStream
      .fromQueue(queue)
      .tap {
        case Left((status, trailers)) =>
          queue.shutdown *> IO.when(!status.isOk)(IO.fail(status))
        case _ => IO.unit
      }
  ...
}
```

The problem is that `onClose` is always called correctly. However `queue.shutdown` is called occasionally - it looks like a race in some internal zio core which leads to such undefined behaviour.  I also have looked on zio traces for both fail and succeed cases - and it looks exactly like that. 

Have tried on both stable (1.0.0-RC18-2) and snapshot (1.0.0-RC18-2+57-41473c47-SNAPSHOT) versions. 

I'm so sorry but I can't reproduce this bug in simpler example, at least for now.   

Regards.

**Comment by fillson-shady** [comment]
It seems, that race was in my code - between a fiber that completes client and a locking operation `dataQueue.take`. It is always hard to debug such async and interpreted (like in zio) code.
I'm sorry for disturbing and closing this task. 
Anyway thank you so much for great library which is now changes the game in Scala world!

**Comment by iravid** [comment]
> It seems, that race was in my code - between a fiber that completes client and a locking operation `dataQueue.take`. It is always hard to debug such async and interpreted (like in zio) code.
> 
> I'm sorry for disturbing and closing this task. 
> 
> Anyway thank you so much for great library which is now changes the game in Scala world!

No worries and thank you for taking the time to open the issue! To debug these issues, you can use the `TestAspect.diagnose` aspect in ZIO Test. That will give you a fiber dump that shows which fiber is hanging on what.
