### ISSUE TITLE
Create BitChunk

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3234]
A BitChunk is a chunk of bits, whose length method returns the number of bits in the chunk, and whose apply / get / etc. methods all operate on the bits.

A `Chunk[X]` should have a `toBitChunk` method, for all `X` such that `X` can be easily viewed as a sequence of bits—most notably, `Chunk[Byte]`.

The methods on `BitChunk` should be similar to the methods on `Chunk`, but of course, specialized to bits. Any attempt to "map" a `BitChunk` should return an ordinary chunk—if we even have map-like functions.

**Comment by vilu** [comment]
I would be up for working on this one.

**Comment by vilu** [comment]
I'm still up for working on it but all of a sudden I had less spare time than I thought. If someone wants to give it a go instead of me please go ahead.

**Comment by jdegoes** [comment]
@adamgfraser Awesome, happy to pair on this too, especially for the performance bits!

**Comment by adamgfraser** [comment]
@jdegoes That would be great. Let me put together an initial version and then would love to do that!
