### ISSUE TITLE
ZIO Core: Clarity over ZIO.when/if

### ISSUE THREAD

**Issue by nadenf** [zio/zio#3236]
Given the following code .. (2) and (3) compile and (1) and (4) don't.
This is confusing as it is perfectly normal to have an if statement without the else.

```scala
for {
  _ <- ZIO.ifM(hasChanges)(doSomething)  ... (1)
  _ <- ZIO.ifM(hasChanges)(doSomething)(doSomethingElse) ... (2)
  _ <- ZIO.whenM(hasChanges)(doSomething) ... (3)
  _ <- ZIO.whenM(hasChanges)(doSomething)(doSomethingElse) ... (4)
}
```
One way of reconciling this is to only support "when" at the end e.g. doSomething.when(..) and add support for (1) to "if". Or just make "if" a synonym for "when".

**Comment by adamgfraser** [comment]
Going to close this as I think with the `when` and `unless` variants we now have all the use cases covered.
