### ISSUE TITLE
Optimize Chunk#++

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3238]
`zio.Chunk`

Currently, chunk concatenation is lazy, but does not utilize a balanced tree. Balancing is necessary to achieve efficient performance in the presence of operations on the concatenated tree.

See [here](https://en.wikipedia.org/wiki/Rope_(data_structure))

**Comment by ahoy-jon** [comment]
after #3241
I could help someone do it.

**Comment by ahoy-jon** [comment]
I take it ( #3311 )

**Comment by adamgfraser** [comment]
Awesome!

**Comment by ahoy-jon** [comment]
Current implementation on master is not working for a large chunk:
```scala
val chunk = (1 to 32768).foldLeft(Chunk(0))(_ + _)
chunk.map(_ + 1)
```
Is raising a stackoverflow.
