### ISSUE TITLE
Give TRef the polymorphic treatment

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3260]
Given that `ZRef` is only used to update immutable data, and given that much immutable data that is accessed concurrently is ideally stored in `TRef` structures inside the environment, it can make a lot of sense to port the polymorphism of `ZRef` into `TRef`.

Of course, we could have `ZTRef` and `TRef`, where `TRef` would be the less polymorphic version, similar to the relationship between `ZRef` and `Ref`. So the polymorphism would be opt-in.

This ticket will involve creating a version of `TRef` (proposed name: `ZTRef`) that is nearly API identical to `ZRef`, and then making a type / companion object alias for `TRef`.

**Comment by vasilmkd** [comment]
I'd like to work on this.

**Comment by adamgfraser** [comment]
Awesome!
