### ISSUE TITLE
ZManaged is not finalized

### ISSUE THREAD

**Issue by serrufSe** [zio/zio#3271]
Hello. I found that ZManaged can be not finalized after interruption in this small example
```scala
import zio.{App, Managed, UIO, ZIO}
import zio.duration._

object Main extends App {
  val someValuableResource: Managed[Nothing, Unit] = Managed.fromEffect(UIO(println("valuable resource are here")))

  val application: ZIO[Any, Nothing, Unit] = for {
    _ <- someValuableResource.ensuring(UIO(println("resource release"))).useForever.fork
    _ <- ZIO.unit.forever
  } yield ()

  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] = for {
    appFiber <- application.fork
    _ <- ZIO.sleep(5.seconds)
    _ <- appFiber.interrupt
    _ <- UIO(println("app interrupted"))
  } yield 0
}
```
in output only
```
valuable resource are here
app interrupted
```
Is this is expected behavior ? It is look like vary common case, when in application level we start use some resource (like server) for forever in separate fiber and immediately start do some background work and late try to restart whole application.

Sorry for my english. 
btw ZIO is awesome!

**Comment by serrufSe** [comment]
ZIO version 1.0.0-RC18-2

**Comment by adamgfraser** [comment]
@serrufSe Thanks for reporting! If you replace `ZIO.unit.forever` with `ZIO.never` or even `UIO(println("forever"))` it looks like it works as expected. So it seems like there is something with `ZIO.unit.forever` in particular, which is creating a very tight infinite loop with a constant value. Investigating further, but hopefully that at least gets your immediate issue resolved.

**Comment by adamgfraser** [comment]
Ah, interesting. If I replace `useForever` with `use(_ => ZIO.infinity)` it works correctly. So it looks like the forked fiber is being garbage collected before the finalizer is run.

**Comment by serrufSe** [comment]
Thanks for quick reply. Look like `use(_ => ZIO.infinity)` is fitted for my case.
