### ISSUE TITLE
ZIO web doc should explain Platform differences prior to Zio 1.0.0

### ISSUE THREAD

**Issue by LeeTibbert** [zio/zio#3277]
### Overview
Zio is incredibly open and welcoming in its documentation & support.  In that spirit...

From my recent work with the three platforms (JVM, JS, & Native) in the Zio GitHub directory,
I have come to believe that the web [documentation](https://zio.dev/docs), perhaps in or
below the `Overview` section, would benefit from a _small_ section explaining two topics 
below.

I believe making this change before Zio 1.0.0 is worthwhile.  If given the go-ahead and
some suggestions for where the concepts can go, I am willing to take a run at a PR, the wording
of which could be improved by review.

#### Platforms

ZIO currently is supported on two platforms, JVM & JS.  It also contains Zio development-only
code for Scala Native.  The provided documentation accurately describes the JVM platform.
 
The JS platform differs slightly. For example, it allows concurrent and asynchronous but not
parallel execution.  It currently can also have problems in some situation with synchronous execution
(I am filing an issue here later. The doc I am suggesting may not want to get into that. It makes brains ache!)

Differences in the Scala Native support will be documented as that support matures. (For the curious, when I tried that support a few days ago on the supplied hello-world example, I got
a link error with missing OffsetDateTime.  Easy enough for me to work around, but not something which people new to Zio should have to bear without having to cross a yellow-tape line.)

#### Zero dependencies

I also suggest that the Zio docs describe what is meant by "zero dependencies".  I suspect
 the term is well defined in some communities but has a different meaning in the larger world.

I think that what is meant here is "zero beyond what is required by an ordinary non-Zio program for that Platform".  The latter part of that could be in a footnote (i.e. "See PlatformSpecific link for
slight differences").

 Probably anyone would know that the JVM Platform required a Scala & a JVM. On a moments reflection, a person could realize that the JS Platform required ScalaJS.
  It is possible to use some phases of the latter without
 Node.js installed but most people would consider Node.js to be at least a soft dependency. 
(I think there is another at least soft dependency there also. I would have to try on a clean
system.) 

It looks like Scala Native support will break that description as it matures. That could go into
the  PlatformSpecific section suggested above.

**Comment by adamgfraser** [comment]
Great suggestions! I will work on this.

**Comment by LeeTibbert** [comment]
Thanks Adam,  I did not mean to generate first level work for you...

A related related to the "zero dependencies", I think. Is that I have not yet stumbled
across a place which describes minimal required versions. Perhaps because 
ZIO has been evolving so quickly that any such documentation would be overwhelmed
by events.

I suspect from a recently accepted PR about jsPromise that Zio requires an scalaJs which supports ECMAscript 6 (javascript 2015) and a node.js or browser which does also.

The JVM Platform probably has a minimal required Java version, probably java 8. I have not
tried it with the current Java 14.  I do not know what the current Continuous Integration matrix is.

Unfortunately, these dependencies creep in.  By the Gell-Mann "If it is not forbidden, it must occur" principle, somebody is _bound_ to hit them (and take up support time).

**Comment by LeeTibbert** [comment]
Reporting as I find/remember them.

scala/zio/blocking & variants are not available with scalaJs.

**Comment by LeeTibbert** [comment]
core/shared/src/main/scala/zio/Runtime.scala methods unsafeRun() & unsafeRunSync() are preceded by the  comment:  I believe these routines are foundational and is called by code a 
```
/**                                                                           
   * Executes the effect synchronously, failing                                 
   * with [[zio.FiberFailure]] if there are any errors. May fail on             
   * Scala.js if the effect cannot be entirely run synchronously.               
   *                                                                            
   * This method is effectful and should only be done at the edges of your program.                                                                            
   */
```
I believe these routines are foundational: unsafeRun is called in the example
at https://zio.dev/docs/overview/overview_running_effects:
`runtime.unsafeRun(ZIO(println("Hello World!")))`.  That example
works, but I have been able to provoke the failure on both the JS & Native
platforms.

The "May fail on Scala.js" portion should probably be in a PlatformSpecific 
section of the documentation.  The description is currently also true for Scala Native
but probably now need to document that, as it is subject to change.

**Comment by LeeTibbert** [comment]
Doc issues being identified and rising to the top is, IMHO, a sign of maturity for ZIO.

Please consider making the "hello-world" example more prominent.  It exists, but is hard to find.
I suspect that a lot of new people start by looking for a "hello-world" example. 

Different people have different learning styles.  It is impossible for doc, even hyperlinked doc,
to address all of them, but some major cases can be handled/

 Perhaps a section for the impatient with
a link to (running effects)[https://zio.dev/docs/overview/overview_running_effects] and
a statement that to really understand it, one should start at "Creating Effects" and work through
the sections.
