### ISSUE TITLE
Improve error messages with Has

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3317]
Due to use of implicit syntax, some operators will not appear on a `ZLayer` unless `ROut <: Has[_]`. This can decrease discoverability. It would be nicer if the user could always try the operator, and just get a custom error message if `ROut` has the wrong shape.

Similarly, some binary operators cannot be used unless the right hand side also has an `ROut2 <: Has[_]`. If it fails to have this bound, a generic message is produced. It would be nice to produce a custom error message.

We can use a combination of implicit evidence, rather than type bounds (to defer the failure to the last possible moment), and `@implicitNotFound` to achieve this.

```
The ZLayer operator you are trying to use needs to combine multiple services. While services cannot directly be combined, they can be combined if first wrapped in the Has data type. Before you use this operator, you must ensure the service produced by your layer is wrapped in Has.

Currently, your ZLayer produces Clock.Service, but to use this operator, you must produce Has[Clock.Service]. You can either map over your layer, and wrap it with the Has(_) constructor, or you can directly wrap your service in Has at the point where it is currently being constructed.
```

**Comment by adamgfraser** [comment]
Good idea. I will add this.
