### ISSUE TITLE
Unify ChunkSpec

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3324]
Currently tests for Chunk are split up between two different `ChukSpec.scala` files in the `coreTests` and `streamTests` projects. We should unify all chunk tests in the file in `coreTests` and also move the chunk generators in `ChunkUtils.scala`, which explicitly generate all the different subtypes of chunks, to that file.

Then we should update the chunk generators used in all the stream tests to use the new chunk generators implemented in ZIO Test.

**Comment by vasilmkd** [comment]
I'll take this now.
