### ISSUE TITLE
Ensure all methods that can be final are final

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#335]
We have some methods, e.g. `schedule.run`, which are declared like so:

```scala
def run(as: Iterable[A]) = ...
```

We should change all methods that are not designed to be overridden to be `final`:

```scala
final def run(as: Iterable[A]) = ...
```

As far as I know, the only methods that should remain non-final are the public fields and methods of `RTS.scala` in the `jvm` directory of the `core` project.

**Comment by saucam** [comment]
I'll take this one

**Comment by sideeffffect** [comment]
can we have a Scalafix rule for that?

**Comment by Jeremy-Laier** [comment]
Can we close?  [#480](https://github.com/zio/zio/pull/480) is merged
