### ISSUE TITLE
Leak in Scala.js + ZIO 1.0.0-RC18-2

### ISSUE THREAD

**Issue by erdavila** [zio/zio#3355]
After upgrading my Scala.js app from 1.0.0-RC17 to 1.0.0-RC18-2, an ever increasing memory consumption was noticed.
During upgrade, the only code changes were:
* replacing `zio.internal.PlatformLive.Default` with `zio.internal.Platform.default` in a custom `Runtime` object
* replace calls for `(new zio.clock.Clock.Live {})._someMethod_(...)` with `zio.clock._someMethod_(...).provideLayer(zio.clock.Clock.live)`

The app is a Google Chrome extension which runs a task every 5 minutes. I did a profiling with _DevTools >> Memory >> Allocation instrumentation on timeline_ during a task run. The resulting files for the app with ZIO 1.0.0-RC17 and 1.0.0-RC18-2 are available in https://gist.github.com/erdavila/65257ae51c27001eea8de7ec113a3637/raw/292a18f4497e4cbcd03e07864b4e79cba734aa33/heaps.zip. (The dump for RC17 has 8MB while the one for RC18-2 has 214MB!)
They can be loaded in DevTools, but I'm not sure what to look at.

**Comment by jdegoes** [comment]
It is possible but not certain that this is related to automatic supervision (parent fibers now track child fibers). We should make sure that when fibers end life, they are cleaned up. However, this will not take care of situations where fibers run forever, or at least, never terminate (e.g. `IO.never.fork`)

**Comment by erdavila** [comment]
I tracked the problem down to one of the changes made during the upgrade :flushed:. The line
```scala
// with ZIO 1.0.0-RC17
(new zio.clock.Clock.Live {}).currentTime(TimeUnit.MILLISECONDS)
```
was replaced with
```scala
// with ZIO 1.0.0-RC18-2
zio.clock.currentTime(TimeUnit.MILLISECONDS).provideLayer(zio.clock.Clock.live)
```
. This line is in a service that was not migrated to the `ZLayer` approach. During execution of the task that runs every 5 minutes, this code is executed around 500 times, which adds to the leak.

If it is instead replaced with
```scala
// with ZIO 1.0.0-RC18-2
zio.clock.Clock.Service.live.currentTime(TimeUnit.MILLISECONDS)
```
the leak is not observed.

---
Using the alternative replacement would solve the problem for me by now until the service is migrated to `ZLayer`.
But still there is something to be solved in the layer handling by ZIO, right? :thinking:

**Comment by adamgfraser** [comment]
@erdavila Thanks for the detailed information. That is super helpful in tracking down the problem.

**Comment by guizmaii** [comment]
@erdavila Is it still an issue with ZIO2? Closing as ZIO1 isn't maintained anymore

**Comment by erdavila** [comment]
> @erdavila Is it still an issue with ZIO2? Closing as ZIO1 isn't maintained anymore

The application was migrated to a different architecture/platform, so we are not using Scala+ZIO anymore.
