### ISSUE TITLE
Improve Support for NonEmptyChunk

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3357]
While overall `Chunk` took a step forward with extending `IndexedSeq`, our support for the `NonEmptyChunk` concept took a step back with that since method names we would like to use are now already defined by `IndexedSeq` so right now we have the somewhat awkward `mapNonEmpty`, `flatMapNonEmpty`, and `concatNonEmpty` to preserve the information that a `Chunk` is nonempty.

I wonder if we should consider an alternative encoding:

```scala
final class private NonEmptyChunk[+A](private val chunk: Chunk[A]) {

  // methods that are guaranteed to return a nonempty chunk or are only safe on a nonempty chunk implemented here
}

object NonEmptyChunk {

  // smart constructors preserve guarantee that chunk is initially nonempty

  // can always "throw away" information and widen to chunk that may or may not be empty
  implicit def asChunk[A](nonEmpty: NonEmptyChunk[A]): Chunk[A] =
    nonEmpty.chunk
}
```

This would require a little more code on our part but I think it could have two advantages:

1. Improve ergonomics of `NonEmptyChunk` -We would be able to have methods like `map`, `flatMap`, and `++` that would do exactly what we would expect
2. Simplify `Chunk` implementation - If we did this we would not have to preserve the static type information of empty versus nonempty within `Chunk` combinators, which I think could simplify some things given we already have a lot of complexity we are dealing with.

**Comment by jdegoes** [comment]
I think I like it. 👍

**Comment by ahoy-jon** [comment]
`NonEmptyChunk` could be removed totally from `Chunk` to that point and be moved elsewhere, even to /dev/null.
I just tried to use it and couldn't without casting.

**Comment by adamgfraser** [comment]
Can you say more about the issues you ran into?

**Comment by ahoy-jon** [comment]
Sorry, I was doing some `++` and `apply` on a `foldLeft`. (doing benchmarks)

**Comment by adamgfraser** [comment]
Well `++` is definitely not going to preserve the nonempty status at this point. If you use `concatNonEmpty` it should work unless there is something else going wrong that I'm not understanding.

**Comment by iravid** [comment]
Agreed on making `NonEmptyChunk` a separate type with appropriate forwarders.

**Comment by adamgfraser** [comment]
On it.
