### ISSUE TITLE
Explore Unifying ZIO Collection Combinators

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3369]
Right now we have a lot of collection combinators like `foreach` and `collectAll` that have `Iterable`, `Chunk`, and in some case `Option` variants. We also have a variety of other combinators that could probably use `Chunk` variants (see #2781 for a relatively comprehensive list).

It would be nice if we could unify these different variants. I think there are a couple of options that we could pursue:

**Use Existing Mechanics from Scala Collection Librabry**

Now that `Chunk` extends `Iterable` we could do something like:

```scala
  def foreach0[CC[x] <: Iterable[x], R, E, A, B, That](
    in: CC[A]
  )(f: A => ZIO[R, E, B])(implicit bf: ZIOBuildFrom[CC[A], B, That]): ZIO[R, E, That] =
    ???
```

Here `ZIOBuildFrom` would just be a wrapper around `CanBuildFrom` on Scala 2.12 and `BuildFrom` on Scala 2.12 to avoid having version specific files anywhere else.

Advantages:
-  All collection operations would return the same type of collection (a Chunk would return a Chunk, a List would return a List, etc...) which would improve the user experience and let us get rid of a bunch of variants
- Minimal existing abstractions beyond those that already exist elsewhere

Disadvantages:
- Signatures of these methods get more complicated and less readable
- Internal combinators now need to work with an `Iterable` instead of a `List` which means internal code will often need to be written in a less functional style
- I haven't figured out a way to write the signature above in a way that abstracts over the kind of the collection (e.g. a `Map` versus a `List`). It seems that we want to say `CC <: Iterable[A]` instead of `CC[x] <: Iterable[x]` but so far I have not been able to make this work.

**Implement some kind of `ChunkLike` trait**

`ChunkLike` witnesses an isomorphism between some other collection type and a Chunk. All collection combinators internally translate things other than Chunks to Chunks, perform operations on them, and convert back.

Advantages:
- Type signatures somewhat simpler than in the case above

Disadvantages:
- Need new `ChunkLike` abstraction
- Need to define instances for all common collection types. New user defined collection types don't work out of the box (maybe we can widen to Iterable?).
- Need to rewrite combinators in terms of `Chunk`
- Less performant for collection types other than `Chunk` because of need to convert to and from

**Comment by jdegoes** [comment]
I really like the first approach. I think we can ignore Maps and anything else that doesn't have kind `* => *`.

**Comment by adamgfraser** [comment]
Sounds great!
