### ISSUE TITLE
Discrepancy between comments and implementations of `zio.internal.Stack.pop()`

### ISSUE THREAD

**Issue by sergei-shabanau** [zio/zio#3372]
Comment for `.pop()` says

> Pops an item off the stack, or returns `null` if the stack is empty.

however implementation is optimistic and throws `ArrayIndexOutOfBoundsException`

The same happens for `.peek()`

**Comment by jdegoes** [comment]
Since `A <: AnyRef`, it would be ok to return null here instead of throwing, and faster anyway.
