### ISSUE TITLE
FiberRefs do not propagate into RefM.modify

### ISSUE THREAD

**Issue by alexknvl** [zio/zio#3373]
`RefM.make` spawns a fiber during construction, so `FiberRef`s do not correctly propagate inside of `RefM.modify(...)`:

```scala
for {
  ref1 <- FiberRef.make(0)
  ref2 <- RefM.make(())
  _ <- ref1.set(1)
  _ <- ref2.modify { _ =>
    ref1.get.flatMap(x => putStrLn(x.toString))
  }
} yield ()
```

I expected it to print `1`, but it actually prints `0`. I don't know what the correct behavior should be, but I think this is a bit counter-intuitive.

**Comment by alexknvl** [comment]
The following implementation does not suffer from the same problem, has the same semantics w.r.t. `modify` operations being serialized, and is presumably much faster.
```scala
final class RefS[A] private (semaphore: Semaphore, ref: Ref[A]) {
  def get: UIO[A] = 
    ref.get
  
  def modify[R, E, B](f: A => ZIO[R, E, (B, A)]): ZIO[R, E, B] =
    semaphore.withPermit(for {
      oldV <- ref.get
      (result, newV) <- f(oldV)
      _ <- ref.set(newV)
    } yield result)
}
object RefS {
  def make[A](value: A): UIO[RefS[A]] = for {
    s <- Semaphore.make(1)
    r <- Ref.make(value)
  } yield new RefS(s, r)
}
```

`RefM.set` seems to be bogus as well, since it can run at the same time as `modify`, leading to race conditions...

**Comment by jdegoes** [comment]
I think we can replace it with a `Semaphore`. It'd be nice to see a benchmark, because in essence we're trading a fast queue for the "queue" inside Semaphore. But I don't think `RefM` should be used for performance sensitive work so it's probably just fine.

The other way to solve it would be to call `Fiber#inheritFiberRefs` to grab the fiber refs from the child fiber.

**Comment by adamgfraser** [comment]
I can work on this.

**Comment by iravid** [comment]
RefM also does not propagate interruption to the execution of the bundles.

I agree that Ref+Semaphore is equivalent; I switched to that from RefM after getting deadlocked by the above in some ZStream combinators 😅

**Comment by adamgfraser** [comment]
Coming soon!

**Comment by alexknvl** [comment]
I think there might be some very subtle differences semantics-wise. I believe I got a deadlock in one of our job dispatching component after I switched from `RefM` to `RefS`, but the fact it propagates `FiberRef`s was important enough for me that I just simplified the job dispatching algorithm to make it work 😅
