### ISSUE TITLE
Add bitwise operations to Chunk.BitChunk

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3388]
BItChunks, being backed by arrays of bytes, can support efficient bitwise operations, such as bitwise and, bitwise or, bitwise xor, and bitwise negation.

These methods should be added to `Chunk.BitChunk`. For ease of use, they should also be accessible on the parent `Chunk` when there is proof the element type is a `Boolean`. This means they need a generic implementation that works even when the chunk is not backed by a `BitChunk`, but is in fact backed by, for example, an array of booleans.

```scala
sealed trait Chunk[+A] {
  def & (that: Chunk[Boolean])(implicit ev: A <:< Boolean): BitChunk = ...
  ...
}
object Chunk {
  class BitChunk extends Chunk[Boolean] {
    override def & (that: Chunk[Boolean])(implicit ev: A <:< Boolean): BitChunk = ...
    ...
  }
}
```

**Comment by adamgfraser** [comment]
I'll do this.

**Comment by michalwarecki** [comment]
@adamgfraser are you working on that? If not, I can take it

**Comment by adamgfraser** [comment]
@michalwarecki Go for it!

**Comment by faradaym** [comment]
I would like to work on this if @michalwarecki is not!

**Comment by adamgfraser** [comment]
@faradaym Great!

**Comment by faradaym** [comment]
Tests in BitChunkSpec use a function that generates a `Chunk[Byte]` , but for my test I would specifically need either `Chunk[Boolean]` or `BitChunk` . I was going to make a function to do this, but `Gen` does not seem to have the ability to generate booleans. 

I tried to write a bitwise method on `Chunk`, utilizing a `ChunkBuilder` and returning `Chunk[Boolean]`; this appears to work. However, I don't see a builder for BitChunk. Advice on how to proceed would be appreciated! 

Here is a test
```scala
testM("bitwise and"){
  check(genByteChunk, genByteChunk){ (byteChunkOne, byteChunkTwo) =>
    //temporary in absence of a generate BitChunk or Chunk[Boolean}
    val chunkOne: Chunk[Boolean] = Chunk(true, false, true, true, false)
    val chunkTwo: Chunk[Boolean] = Chunk(false, true, false, true, false, false, false, true, true)
    val actual = chunkOne & chunkTwo

    val expected: Chunk[Boolean] = Chunk(false, false, false, true, false, false, false, false, false)
    assert(actual)(equalTo(expected))
  }
}
```

my attempt at bitwise & on Chunk:
```scala

      def & (that: Chunk[Boolean])(implicit ev: A <:< Boolean): Chunk[Boolean] = {
        val shorter = math.min(self.length, that.length)
        val longer = math.max(self.length, that.length)
        val difference = longer - shorter
        val builder = ChunkBuilder.make[Boolean]()
        builder.sizeHint(longer)
        var i = 0

        while(i < shorter){
          builder += (self(i) & that(i))
          i+= 1
        }
        for( j <- 1 to difference) builder += false;

        builder.result()
      }
```

BitChunk:
```scala

    override def &[A >: Boolean](that: Chunk[Boolean]): BitChunk = {
       //???
    }
```

**Comment by adamgfraser** [comment]
@faradaym You can generate booleans using `Gen.anyBoolean`. So you could do something like:

```scala
val genBooleanChunk: Gen[Random with Sized, Chunk[Boolean]] =
  Gen.chunkOf(Gen.anyBoolean)

val genByteChunk: Gen[Random with Sized, Chunk[Boolean]] =
  ???

val genChunk: Gen[Random with Sized, Chunk[Boolean]] =
  Gen.oneOf(genBooleanChunk, genByteChunk)
```

**Comment by jdegoes** [comment]
@adamgfraser Was this completed?
