### ISSUE TITLE
Migrate all lazy array creation code in Chunk to use ChunkBuilder instead

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3393]
Currently, many `Chunk` operations like `map` allocate arrays, lazily creating them until they know what their correct element type should be.

This creates a lot of obfuscation in the code base and makes it difficult to create type-specific behavior around chunk creation. 

Since we have `ChunkBuilder` now, it could be a good idea to migrate this manual lazy creation of arrays to use `ChunkBuilder` instead, which has the same logic inside it.

To do this efficiently, each operation like `map` should create a new chunk builder, and then call `sizeHint` to set the size of the expected output chunk. Then it can add the elements into the chunk builder, and finally convert to the return chunk type.

**Comment by mschuwalow** [comment]
I'll take this one
