### ISSUE TITLE
Enhance ChunkBuilder with type-specific variants

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3394]
`ChunkBuilder` is generic in the type of chunk it builds (`A`). However, this leads to boxing all elements passed to `ChunkBuilder#add`. 

In order to avoid boxing, it will be necessary to create sub traits (such as `ChunkBuilder.Int`) that are designed to work with a specific primitive type. These sub traits would expose a new method, e.g. `add(i: Int)`, which would not involve boxing the element type, and which would store it directly in a specialized array created directly with the class tag for the primitive type.

This ticket is to implement these type-specific variants of `ChunkBuilder` in the companion object of `ChunkBuilder`. 

 - `ChunkBuilder.Byte`.  Uses an `Array[Byte]`, with a specialized `add` method accepting an unboxed `Byte`.
 - `ChunkBuilder.Short`.  Uses an `Array[Short]`, with a specialized `add` method accepting an unboxed `Short`.
 - `ChunkBuilder.Int`.  Uses an `Array[Int]`, with a specialized `add` method accepting an unboxed `Int`.
 - `ChunkBuilder.Long`.  Uses an `Array[Long]`, with a specialized `add` method accepting an unboxed `Long`.
 - `ChunkBuilder.Float`.  Uses an `Array[Float]`, with a specialized `add` method accepting an unboxed `Float`.
 - `ChunkBuilder.Double`.  Uses an `Array[Double]`, with a specialized `add` method accepting an unboxed `Double`.
 - `ChunkBuilder.Boolean`. This chunk builder will utilize the machinery developed in #3383 so that it may efficiently build bit chunks.
 - `ChunkBuilder.Char`. Uses an `Array[Char]`, with a specialized `add` method accepting an unboxed `Char`.

When this ticket is done, these primitive-specialized chunk builders will exist and have rudimentary tests. But there is no need to use these chunk builders as part of this ticket.

**Comment by adamgfraser** [comment]
The `ArrayBuilder` that backs `ChunkBuilder` already has specialized variants for primitive types so it should be straightforward to add these.

**Comment by jdegoes** [comment]
@adamgfraser Awesome. 👍

**Comment by adamgfraser** [comment]
I'll add this.
