### ISSUE TITLE
Safer map alternative

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3402]
Using methods that can throw exceptions inside of `map` such as `foo.map(_.unsafeOpThatThrows)` will result in a defect. This often bites new users.

Currently there is `foo.flatMap(x => Task(x.unsafeOpThatThrows))` or `foo.map(_.unsafeOpThatThrows).absorb` (the latter isn't _quite_ equivalent because it casts too wide of a net). The idea is to have an alternate like `mapSafe` (or `mapAbsorb` or whatever a good name for it would be).

Just the fact that it would come up in autocomplete as you type map could remind you, "Wait, is my map call safe?"

This safe map would need evidence `E =:= Throwable`.

**Comment by adamgfraser** [comment]
I will add.

**Comment by jdegoes** [comment]
@reibitto @adamgfraser I'd suggest `mapEffect` based on our naming conventions.

**Comment by adamgfraser** [comment]
@jdegoes Sounds good.

**Comment by reibitto** [comment]
I wonder, could `E <:< Throwable` work here?

**Comment by adamgfraser** [comment]
Yes that is what I am doing. But we need to return a value of type `Throwable`, since the effect could fail due to some type of other `Throwable`.
