### ISSUE TITLE
ZIO Test: support custom equality

### ISSUE THREAD

**Issue by ioleo** [zio/zio#3405]
We should have the equivalent of ScalaTest's `Equality` to allow overriding how equality is defined for `equalTo` assertion.

**Comment by adamgfraser** [comment]
ZIO Prelude is going to have this and include tight integration with ZIO Test for it.

**Comment by adamgfraser** [comment]
Going to close this just because I don't think there is an action item in this repository at this point.

**Comment by jypma** [comment]
Is there a more specific link on how to achieve this with ZIO Prelude?

**Comment by adamgfraser** [comment]
Use `zio.prelude.Assertions.equalTo`, which uses an `Equal` instance defined for your type to determine whether two types are equal, then define an `Equal` instance` reflecting your notion of equality.
