### ISSUE TITLE
Flaky FiberSpec Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3441]
```scala
[info] - FiberSpec
[info]   - track blockingOn
[info]     - in race
[info] Timeout of 1 m exceeded.
```

https://app.circleci.com/pipelines/github/zio/zio/7033/workflows/b0b4d01d-ba5c-4055-a3b0-2328c3316bed/jobs/71954

Copying @runtologist.

**Comment by runtologist** [comment]
I'll take a look.
