### ISSUE TITLE
Make Chunk implicitly convert to, but not extend, IndexedSeq

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3447]
Given that IndexedSeq creates mandatory boxing on `apply`, can't support reasonably sized bit chunks, and forces weird signatures for some methods, I think it makes sense re-investigating the decision to make Chunk extend IndexedSeq. 

Instead, we can offer an IndexedSeq "view" of a Chunk through an implicit in the companion object, which allows smooth interop but without the other drawbacks; and possibly also add an `asIndexedSeq` method for cases where the implicit is insufficient.

**Comment by adamgfraser** [comment]
#3426 addresses this. I will clean it up and get it ready to merge.
