### ISSUE TITLE
Add Java class that can access nth element of each primitive type of array

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3448]
It appears Scala's `Array#apply` method is merely `IndexedSeq#apply`, which will always box. To avoid the necessity of having this boxing overhead, we need a Java helper class inside package `zio.internal`, something like:

```java
public class ArrayHelper {
  public static byte getByte(byte[] array, int i);
  public static char getChar(char[] array, int i);
  ...
}
```

The helper class will contain accessors for each primitive type. An accessor for `Object[]` is not needed since that is available natively in Scala.

Once implemented, this functionality can be used by #3387 for improved performance for the specialized accessor methods already added by #3386.

**Comment by aleksandarskrbic** [comment]
@jdegoes I would like to take this one.

**Comment by adamgfraser** [comment]
@aleksandarskrbic Great!

**Comment by neko-kai** [comment]
@jdegoes @aleksandarskrbic 
> It appears Scala's Array#apply method is merely IndexedSeq#apply, which will always box.

This does not reproduce for me, decompiling the following code with Intellij reveals direct access to array, no boxing and not IndexedSeq#apply.

```scala
package example

object example {
  locally {
    val array  = Array(1, 2, 3)
    val i: Int = array(2)
  }
}
```
->
```java
//decompiled from example$.class
package example;

import scala.Predef.;
import scala.runtime.BoxedUnit;

public final class example$ {
   public static final example$ MODULE$ = new example$();

   static {
      int[] array = new int[]{1, 2, 3};
      int i = array[2];
      .MODULE$.locally(BoxedUnit.UNIT);
   }

   private example$() {
   }
}

        //decompiled from example.class
package example;

import scala.reflect.ScalaSignature;

@ScalaSignature(
   bytes = "\u0006\u0005I9Qa\u0001\u0003\t\u0002\u00191Q\u0001\u0003\u0003\t\u0002%AQ\u0001E\u0001\u0005\u0002E\tq!\u001a=b[BdWMC\u0001\u0004\u0007\u0001\u0001\"aB\u0001\u000e\u0003\u0011\u0011q!\u001a=b[BdWm\u0005\u0002\u0002\u0015A\u00111BD\u0007\u0002\u0019)\tQ\"A\u0003tG\u0006d\u0017-\u0003\u0002\u0010\u0019\t1\u0011I\\=SK\u001a\fa\u0001P5oSRtD#\u0001\u0004"
)
public final class example {
}
```

**Comment by aleksandarskrbic** [comment]
@neko-kai you are right, just tried it.

**Comment by jdegoes** [comment]
@neko-kai @aleksandarskrbic Well, that's a huge relief! Maybe in @vasilmkd's reproduction, it was somehow accessed through IndexedSeq?

**Comment by vasilmkd** [comment]
Java indeed is the assembly of the JVM.

**Comment by vasilmkd** [comment]
> @jdegoes @aleksandarskrbic
> 
> > It appears Scala's Array#apply method is merely IndexedSeq#apply, which will always box.
> 
> This does not reproduce for me, decompiling the following code with Intellij reveals direct access to array, no boxing and not IndexedSeq#apply.
> 
> ```scala
> package example
> 
> object example {
>   locally {
>     val array  = Array(1, 2, 3)
>     val i: Int = array(2)
>   }
> }
> ```
> 
> ->
> 
> ```java
> //decompiled from example$.class
> package example;
> 
> import scala.Predef.;
> import scala.runtime.BoxedUnit;
> 
> public final class example$ {
>    public static final example$ MODULE$ = new example$();
> 
>    static {
>       int[] array = new int[]{1, 2, 3};
>       int i = array[2];
>       .MODULE$.locally(BoxedUnit.UNIT);
>    }
> 
>    private example$() {
>    }
> }
> 
>         //decompiled from example.class
> package example;
> 
> import scala.reflect.ScalaSignature;
> 
> @ScalaSignature(
>    bytes = "\u0006\u0005I9Qa\u0001\u0003\t\u0002\u00191Q\u0001\u0003\u0003\t\u0002%AQ\u0001E\u0001\u0005\u0002E\tq!\u001a=b[BdWMC\u0001\u0004\u0007\u0001\u0001\"aB\u0001\u000e\u0003\u0011\u0011q!\u001a=b[BdWm\u0005\u0002\u0002\u0015A\u00111BD\u0007\u0002\u0019)\tQ\"A\u0003tG\u0006d\u0017-\u0003\u0002\u0010\u0019\t1\u0011I\\=SK\u001a\fa\u0001P5oSRtD#\u0001\u0004"
> )
> public final class example {
> }
> ```

Here Scala knows statically that you are dealing with an `Int` array. Try to work over an `Array[A]` where you receive this array as a function argument, for example, is where this falls apart.

**Comment by neko-kai** [comment]
@vasilmkd 
Yes, I see, polymorphic array access resorts to calling methods of `ScalaRunTime` and will return a boxed object, however, constraining the variable to `_ <: AnyRef` is enough to return direct access:

```scala
package example

object example {
  locally {
    def xa[A](array: Array[A]): Unit = {
      val i: A = array(2)
    }
    def ofAnyRef[A <: AnyRef](array: Array[A]): Unit = {
      val i: A = array(2)
    }
  }
}
```
->
```java
public final class example$ {
   public static final example$ MODULE$ = new example$();

   static {
      .MODULE$.locally(BoxedUnit.UNIT);
   }

   private static final void xa$1(final Object array) {
      Object var1 = scala.runtime.ScalaRunTime..MODULE$.array_apply(array, 2);
   }

   private static final void ofAnyRef$1(final Object[] array) {
      Object var1 = array[2];
   }

   private example$() {
   }
}
```

**Comment by aleksandarskrbic** [comment]
@vasilmkd  So should I implement java class or approach proposed by @neko-kai can be used instead?

**Comment by iravid** [comment]
@jdegoes We've seen in #3576 that this isn't necessary to avoid boxing in the chunk subtypes. Ok to close?

**Comment by jdegoes** [comment]
👍 Would be nice to document our learning somewhere.
