### ISSUE TITLE
Consider Aligning Order of Type Parameters in ZQueue and ZRefM

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3461]
Right now the signatures are:

```scala
trait ZQueue[-RA, +EA, -RB, +EB, -A, +B]
trait ZRefM[-RA, -RB, +EA, +EB, -A, +B]
```

For consistency it would be nice if the parameters were in the same order. I think the `ZRefM` ordering is slightly more idiomatic (all environment parameters first, then all error parameters), though the `ZQueue` signature has been around longer.

**Comment by iravid** [comment]
👍🏻 to using the ZRefM order.
