### ISSUE TITLE
Simulate a Schedule

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3468]
I think it would be helpful to be able to take any arbitrary Schedule and "simulate" it to get its output. For example, say I have:

```scala
val retryPolicy = Schedule.exponential(1.second) <* Schedule.recurs(5)
```

I'm imagining a function that you could use to answer questions like, "What would the output of this schedule be given this input?" Another important thing this function would do is give you the answer without actually sleeping (I think you might need a Clock like zio-test's TestClock to do this).

A function like this would open up possibilities to use `Schedule` in more situations than you can now (such as in distributed systems).

To give one real-world example:

I have multiple message queue consumers that processeses messages and will retry them later if they fail (possibly on a completely different consumer node next time). Each time the message comes through again, there's a `ReceiveCount` header. If the `ReceiveCount` is 4, I want to know the 4th value in the retryPolicy Schedule so that I can tell the message queue "pop it back in the queue to show up after X time has passed".

It would be cool to leverage ZIO's Schedule to create any kind of schedule that I can imagine rather than write my own schedule implementation just for this specific purpose.

**Comment by adamgfraser** [comment]
Yes this is a little bit of the tradeoff with schedules actually doing sleeps at each step versus being descriptions. We thought this would support more uses of chronic job like scheduling but it does make use cases like this more difficult. Do you need any interaction with real time for this? If not I think the easiest thing to do would be to remap the `Clock` implementation to one that just immediately runs everything that it is given, though note if there are other arbitrary effects included in the step of a schedule there is no way to run the schedule without triggering those effects as well.

**Comment by reibitto** [comment]
A `Clock` that immediately runs everything sounds perfect.

But hmm, yeah, the arbitrary effect part is tricky. I'm not doing arbitrary effects, and can't imagine ever needing that... but I see your point. If someone needs that and they don't want to actually run them while simulating, I suppose they would have to put that in `R` and simulate those parts themselves too by providing a custom layer for it? I imagine it's a rare case, but could be worth adding a usage note about it.

**Comment by adamgfraser** [comment]
I think the bigger issue is that you could do effect that aren’t embodied in the environment at all, like you place a tap on the output of a schedule that prints all the outputs to the console. If you do effects in your schedule that aren’t modeled in your environment type there is no way for us not to run those when executing the schedule. But I agree that would not be very common.

**Comment by simpadjo** [comment]
Here is another case where unification of `sleep` with other capabilities appears to be problematic: https://github.com/zio/zio/issues/2957
