### ISSUE TITLE
window and watermark function in ZIO Streams

### ISSUE THREAD

**Issue by michalwarecki** [zio/zio#3482]
Hi guys,

Recently I've been dealing with ZIO Streams and in my use case I found two missing functionalities in ZIO Streams:
- watermark - removing incoming events older than provided duration,
- window - grouping events by sliding time window.

I have some time to implement such contribution but I need your input/review.
The first thing is answer to question: are such functions even needed in ZIO Streams?
The second is to review design of both functions:

`def window(windowDuration: Duration, tick: Duration, timestamp: A => Instant, buffer: Int = 16): ZStream[R with Clock, E, List[A]]`

- `windowDuration` - sliding window duration,
- `tick` - how frequent consumer will receive grouped events,
- `timestamp` - time in UTC representing each event (question: should we use Instant or Long as a timestamp?),
- `buffer` - event buffer

`def watermark(delayThreshold: Duration, timestamp: A => Instant): ZStream[R with Clock, E, A]`

- `delayThreshold` - watermark duration (events older than `currentTime - delayThreshold` will be dropped),
- `timestamp` - time representing each event

**Comment by simpadjo** [comment]
Hey,
I think having something like this would be great.
Couple of comments: 
1) A major pull request with a complete redesign zio-streams is about to be merged. Makes sense to wait a bit with coding.
2) Would be useful be able to use current time as an event timestamp as well

**Comment by michalwarecki** [comment]
Thanks for the comment @simpadjo !

1. I see the changes are already merged so I'll start prototyping today.
2. Do you mean that by default it should be current time?

**Comment by simpadjo** [comment]
Hard to say how final API would look like. I'm talking about usecases:
1) extract time from a stream element
2) use a "natural" timestamp

There could be few ways to achieve this including:
a) changing timestamp timestamp type to  `A => ZIO[R, E, Instant]`
b) asking a caller to zip the stream with the current time themself

**Comment by iravid** [comment]
Hello @michalwarecki, sorry I did not chime in yet. I admit I find it hard to see a family of combinators around watermarks directly in `ZStream` as that is a fairly domain-specific usecase, whereas most ZStream combinators are very generic.

For example, #3542 is a monomorphic version of `filterM`.

But I am open to being convinced. Pinging other contributors for some more opinions: @vasilmkd @regiskuckaertz @mschuwalow

As a side-note, we will be picking up the development of https://github.com/zio/zio-analytics soon(tm). That will include full-fledged support for watermarked streams.

**Comment by vasilmkd** [comment]
I'm with @iravid on this one, I think these features are better suited for a library.

**Comment by michalwarecki** [comment]
Hi, I believe it's a generic functionality for time-based streaming and it's different, much more powerful version of already existing `groupedWithin`.

Please, take a look at examples and documantation from different popular streaming systems:

https://ci.apache.org/projects/flink/flink-docs-stable/dev/stream/operators/windows.html

https://databricks.com/blog/2017/05/08/event-time-aggregation-watermarking-apache-sparks-structured-streaming.html

I can also see it in `zio-analitics` but I feel that it better suits in core streams because of it's generic nature.

**Comment by regiskuckaertz** [comment]
Both combinators are clearly domain-specific, even down to their names 😆 I would be very surprised if they weren't in zio-analytics.

**Comment by iravid** [comment]
Perhaps we should have stated the purpose of ZIO Streams more clearly in its documentation. As I see it, ZIO Streams is a library for declarative concurrency and control flow; watermarking and windowing are operators for streaming analytics.

The other problem with including this functionality in ZIO Streams is that watermarking is the tip of the iceberg. For proper windowing support, we would need to implement a complete set of windowing strategies (hopping/tumbling/session); eviction strategies; watermarking strategies (exact/lagging); persistence strategies (otherwise your windows are lost on restart); etc. This is clearly out of scope for ZIO itself.

**Comment by michalwarecki** [comment]
Thanks for the clear comment on that! I agree now. I'll put it on hold and pick up when `zio-analytics` will be started.

**Comment by iravid** [comment]
Thank you @michalwarecki for investing your time and thoughts into this! Contributions on zio-analytics would be very welcome :-)

Closing for now.

**Comment by jamesward** [comment]
What ever happened with zio-analytics?

**Comment by adamgfraser** [comment]
Still coming but focused on ZIO 2.0 for now!
