### ISSUE TITLE
Push `ZStream#mapError` and `ZTransducer#mapError` to `ZConduit`

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3485]
I stumbled upon the issue https://github.com/zio/zio/issues/2431 
It raises some concerns about of zio-streams that are mostly resolved.
But the one problem is still there: 

> Even though the current type signatures of the aggregate combinators say that the error types of the stream and the sink must unify together, I will argue that these are actually unrelated, and cannot both be handled by a single future combinator.

If a stream fails can fail with `E1` and a sink can fail with `E2` then we could plug them together by lifting errors into `Either[E1, E2]`. 
There is `ZStream#mapError` function. We need to add `ZSink#mapError` as well.
But looks like `mapError` could be just declared in `ZConduit` instead. 

If I'm not missing something - will be happy to make a PR.
If not - let's simply add `ZSink#mapError`.

**Comment by iravid** [comment]
Let’s avoid unifying the errors to an Either in the aggregate combinators. I’d like to explore alternative solutions first.

Adding mapError to ZSink would be a great addition! We should do ZTrandducer too.

**Comment by simpadjo** [comment]
I'm not going to change any signatures. I mean that if both Stream an Sink have `mapError` method, a user have enough tools to unify errors by themself (if really wants).
