### ISSUE TITLE
ZStream.fromQueue creates a singleton chunk stream

### ISSUE THREAD

**Issue by iravid** [zio/zio#3489]
Follow-up to #3079.

`ZStream.fromQueue` creates a stream of singleton chunks because we have no way of taking multiple elements from a queue and blocking until at least some of the takes are satisfied. Using `takeAll.repeatWhile(_.size == 0)` would create a busy-waiting loop.

We would need to implement `takeBetween(min: Int, max: Int)` methods on Queue which block until at least `min` elements and at most `max` elements can be satisfied. ZStream.fromQueue can use that to grab everything the queue can offer at every pull.

cc @mijicd

**Comment by mijicd** [comment]
I'm working on something similar, as discussed over chat. Tomorrow's the day off, so I'll be back on this.

**Comment by iravid** [comment]
Thanks for putting in the time to do this @mijicd! Just to clarify, this isn’t urgent as it is a performance optimization.
