### ISSUE TITLE
Implement additional variants for ZStream#timeout

### ISSUE THREAD

**Issue by iravid** [zio/zio#3493]
The only variant implemented currently fails the stream with an interruption. This is arguably unexpected because we could have just ended the stream.

We should implement variants of timeout that mirror the ones on ZIO:
- `timeout(Duration)` should end the stream when a pull times out
- `timeoutErr(e: E)` should fail the stream with `E` when a pull times out
- `timeoutTo(ZStream)` should switch over to another stream when a pull times out

**Comment by simpadjo** [comment]
@iravid close?

**Comment by iravid** [comment]
Closed in #3562
