### ISSUE TITLE
Home for derived concurrency types

### ISSUE THREAD

**Issue by RaasAhsan** [zio/zio#350]
I haven't seen one yet, but is there a home where derived types for concurrency should go? ZIO provides a powerful set of primitives (`Ref`, `Queue`, `RefM`, `Semaphore`) in which many other concurrent data structures (latches, barriers, locks, maps) can be defined in terms of. They would provide immense value to users, but perhaps this library isn't the best home for them?

- same package
- separate submodule
- separate repository
- users should define as needed (not in favor of this one)

**Comment by adamgfraser** [comment]
I think we said these could live in `zio-concurrent` now.
