### ISSUE TITLE
Auto-composition of ZIO Layers

### ISSUE THREAD

**Issue by vitaliis** [zio/zio#3531]
Not sure if that is possible, but I want to propose an idea.
It would be really nice if one could provide a bunch of required layers and zio would automatically figure out how to wire them coherently together.

Right now you have to provide all the required layers to other layers using `>>>`. You do this for layers that depend on other layers that depend on other layers, until at most there is ZEnv left. So you can provide a list of "resolved" layers to the app.

Maybe it is possible through the marcos or in some other way to build that graph of dependencies and satisfy dependencies automatically step by step.
I can imaging having a map of lazy values (keys are resulting layer types and values are layers themselves). Then traversing this map multiple times until all the dependencies are satisfied and we can build a coherent environment. Starting from services that don't have requirements, building them first. And then feeding them where they are required.
Having it in this "dynamic way" can enable us building more precise error messeges where exactly which dependencies are missing. Instead of unwinding a big error message. For which I built a tool because error can become really huge and incomprehensible. But that is a different topic.

**Comment by neko-kai** [comment]
@vitaliis You may want to look at distage's `fromHas` which does exactly what you describe https://izumi.7mind.io/latest/release/doc/distage/basics.html#zio-has-bindings

**Comment by vitaliis** [comment]
Thank you for this option. That is already a step forward. The disadvantage of this approach is that it relies on an external framework therefore requiring an additional dependency. And you still have to define "bindings" (from Service to Layer) manually. Don't get me wrong, it is a fully valid approach, which is already available and useful, but not exactly what I meant above.

What I imagined is providing to an app a set of layers and let the library figure out itself how compose layers based on provided Layers. Layers definitions and types already contain a resulting and required services, so these "bindings" could be automatically derived from given layers, without having to specify it explicitly. You still may combine them manually if needed, but in many cases that would become unnecessary anymore.

**Comment by neko-kai** [comment]
@vitaliis 
> Layers definitions and types already contain a resulting and required services, so these "bindings" could be automatically derived from given layers, 

That's already what `distage` does. I believe writing `make[T].from(layer)` is better long-term than writing `wire(layer)` without specifying the type, because then you can search for occurences of `make[T]` and figure out how that type was created.

However, if you just want to not specify the return type, it's very easy to let Scala infer it:

```scala
val zenvModule = new ModuleDef {
  wire(Clock.live)
  wire(Console.live)
  wire(System.live)
  wire(Random.live)
  wire(Blocking.live)
  
  def wire[R: HasConstructor, A: Tag](layer: RLayer[R, A]) = make[A].fromHas(layer)
}
```

Or indeed derive the bindings from a Set of layers automatically:

```scala
composeLayers(
  Clock.live,
  Console.live,
  System.live,
  Random.live,
  Blocking.live
)

def composeLayers(layers: LayerBinding*): Module = layers.foldLeft(Module.empty)(_ ++ _.layerModule)

final case class LayerBinding(layerModule: Module)
object LayerBinding {
  implicit def fromLayer[R: HasConstructor, A: Tag: zio.Tagged](layer: RLayer[R, Has[A]]): LayerBinding = LayerBinding(new ModuleDef {
    make[A].fromHas(layer = layer)
  })
}
```

**Comment by adamgfraser** [comment]
Going to close this as I think this use case is already covered by `distage` and out of scope for ZIO itself.
