### ISSUE TITLE
Defect in zio.Has

### ISSUE THREAD

**Issue by fillson-shady** [zio/zio#3558]
Hello!

It seems, that I meet a bug in DI (Layers) system. I assume, that all dependencies have to be checked at compile time. But here is example of code which compiles successfully, but throws Error at runtime.

```scala
import izumi.reflect.Tags.Tag
import zio._
import zio.console._

object ServiceA {
  type HasServiceA = Has[Service]
  trait Service {
    def print: ZIO[Console, Nothing, Unit]
  }
  val live: Service = new Service {
    def print: ZIO[Console, Nothing, Unit] = putStrLn("Access A")
  }
  def print: URIO[HasServiceA with Console, Unit] =
    ZIO.accessM(_.get.print)
}

object ServiceB {
  type HasServiceB = Has[Service]
  trait Service
  val live: Service = new Service {}
}

abstract class Base[R <: Has[_]: Tag] extends App {

  def init(): ZLayer[ServiceA.HasServiceA, Nothing, R]

  def run(args: List[String]): ZIO[ZEnv, Nothing, Int] = {
    val app = for {
      _ <- putStrLn("Line one")
      _ <- ServiceA.print
      _ <- putStrLn("Line two")
    } yield ()
    val baseLayer = ZLayer.succeed(ServiceA.live) ++ Console.live
    val layer     = baseLayer ++ (baseLayer >>> init())
    app
      .provideCustomLayer(layer)
      .as(0)
  }
}

object Test extends Base[ServiceB.HasServiceB] {
  def init(): ZLayer[ServiceA.HasServiceA, Nothing, ServiceB.HasServiceB] = ZLayer.succeed(ServiceB.live)
}
```

This code doesn't work on both `1.0.0-RC18-2` and `1.0.0-RC18-2+247-a7dd2990-SNAPSHOT` (to run on SNAPSHOT you have to replace `import izumi.reflect.Tags.Tag` with `import izumi.reflect.Tag`).

Errors for a slightly different. Error for `1.0.0-RC18-2`:
```
java.lang.Error: Defect in zio.Has: Could not find ServiceA::Service inside Map(package::Console::Service -> zio.console.package$Console$Service$$anon$1@7fc7a800,
package::Blocking::Service -> zio.blocking.package$Blocking$Service$$anon$1@73968dd3,
package::Clock::Service -> zio.clock.package$Clock$Service$$anon$1@dff5a21,
package::System::Service -> zio.system.package$System$Service$$anon$1@7780697c,
package::Random::Service -> zio.random.package$Random$Service$$anon$1@35c54824,
ServiceB::Service -> net.degoes.zio.ServiceB$$anon$2@727ab35a)
```

Error for `1.0.0-RC18-2+247-a7dd2990-SNAPSHOT`:
```
java.lang.Error: Defect in zio.Has: Set({Has[=ServiceA::Service] & Has[=package::Console::Service]}) statically known to be contained within the environment are missing
```

It seems that it is a problem in interaction with a Tag. Necessary dependencies are erased in `Has.scala`:
```scala
def union[B <: Has[_]](that: B)(implicit tagged: Tagged[B]): Self with B =
  self.unionAll[B](that.prune)
```
Because at some point of execution `tagged` contains only `ServiceB::Service`, `that.prune` erases `ServiceA::Service` from dependencies.

Am I doing something wrong or it is a bug?

Thank you!

**Comment by adamgfraser** [comment]
@fillson-shady Thanks for reporting! Will take a look.

**Comment by neko-kai** [comment]
@fillson-shady
If you add `implicit tag: Tag[ServiceA.HasServiceA with zio.console.Console with R]` the problem disappears. The corruption happens in `provideCustomService`, the issue may be in `LightTypeTag.refinedType` function.

/cc @pshirshov

**Comment by pshirshov** [comment]
Seems like something is wrong with `Tag` macro, not the type info extraction logic, the macro  shouldn't allow an invalid tag to be constructed.

**Comment by fillson-shady** [comment]
@neko-kai 
Thank you so much for workaround!
Indeed, changing the signature of `class Base` solves the issue:
```scala
abstract class Base[R <: Has[_]: Tag](implicit tag: Tag[ServiceA.HasServiceA with zio.console.Console with R]) extends App
```

**Comment by neko-kai** [comment]
@fillson-shady Fixed upstream, do you need a release asap or is workaround good enough for now?

**Comment by fillson-shady** [comment]
@neko-kai 
The workaround is definitely good enough for me! Thanks again for the very quick fix!

**Comment by dkarlinsky** [comment]
@neko-kai was your fix ever merged into ZIO? 
I'm getting a similar error (in ZIO 1.0.4): 
```
java.lang.Error: Defect in zio.Has: Set(<refinement>) statically known to be contained within the environment are missing
```
When doing something like:
```scala 
def provide[R <: Has[_]: Tag, E, A](env: R,  zio: ZIO[R with Blocking, E, A]): ZIO[Blocking, E, A] = {
   zio.provideSome[Blocking](_.union[R](env))
}
```

**Comment by neko-kai** [comment]
@dkarlinsky 
Can't reproduce (https://scastie.scala-lang.org/ct3TJwbuSgGa2rQJcllWuw), do you have an example?
btw I think it's better to open a brand new issue in https://github.com/zio/izumi-reflect for this, it's unlikely that this new error is connected to the error in this issue.

**Comment by dkarlinsky** [comment]
Yeah, I think my code was too simple to reproduce. 
I will try to come up with minimal reproducing code, and will open an issue if I do.
Thanks.
