### ISSUE TITLE
ZIO.tupled

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3564]
Mentioned this in the Discord, but I think it might be nice to have `ZIO.tupled` (or whatever it should be called) for cases where you're doing more than 1 zip but you want a flat tuple.

This is basically an extension off of ZIO.mapN. Right now you have to do:

```scala
ZIO.mapN(UIO(1), UIO("s"), UIO(true)) { case tuple => tuple }
```

Note that the pattern match is needed here (`map(identity)` won't work... though it might be possible in Dotty?)

The proposed addition would look like:

```scala
ZIO.tupled(UIO(1), UIO("s"), UIO(true))
```

**Comment by adamgfraser** [comment]
Closed by #3565.
