### ISSUE TITLE
Consider Renaming MapN Variants

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#3567]
Currently we have `ZIO.mapN` for combing multiple effects with a function and `ZIO.tupled` for combining more than two effects into a tuple. Conceptually these are both just higher arity variants of `zip`. We may want to rename to `zipWithN`, `zipN`, `zipWithParN`, and `zipParN`. Whatever we do we should align across various ZIO effect types.

**Comment by adamgfraser** [comment]
Closing in light of compositional zips.

**Comment by caeus** [comment]
Compositional zips?

**Comment by adamgfraser** [comment]
```scala
val zio1: ZIO[Any, Nothing, Int] =
  ZIO.succeed(42)

val zio2: ZIO[Any, Nothing, String] =
  ZIO.succeed("foo")

val zio3: ZIO[Any, Nothing, Double] =
  ZIO.succeed(0.5)

val zipped: ZIO[Any, Nothing, (Int, String, Double)] =
  zio1 <&> zio2 <&> zio3
```
