### ISSUE TITLE
Why does collectAll use List?

### ISSUE THREAD

**Issue by borissmidt** [zio/zio#3575]
I was looking into the code and i i found it a bit weird to find out that a collectAll on a stream collects everything into a List and then reverts it (which looks really inefficient for large streams). I understand that you want to be 100% immutable but a list buffer wouldn't have leaked its state and might have been more efficient?

```
  def collectAll[A]: ZSink[Any, Nothing, Nothing, A, List[A]] =
    foldLeft[A, List[A]](List.empty[A])((as, a) => a :: as).map(_.reverse)
```
Also don't you return a Seq and then you are still able to change the collection to something else if it gives higher performance and make binary compatibility easier?

**Comment by borissmidt** [comment]
Maybe an offtopic question,
Why is there no `collect` that allows me to just do a filter and map like Monix/scalaZ stream? its just unexpected that it throws when a match doesn't match. I use a collect often to 'flatmap' a stream with options to remove the None values.

**Comment by jdegoes** [comment]
We want to switch to using `Chunk` as the default data type. 

Any interest in doing a PR? 😉

**Comment by borissmidt** [comment]
Yea why not i'll have a try.

**Comment by iravid** [comment]
Replacing the list with Chunk and ChunkBuilder there would be great 👍🏻

**Comment by borissmidt** [comment]
I also see a simular collect all in the scheduler class, i assume that it is best to replace any place where there is a `foldleft` with a list in it?

**Comment by mijicd** [comment]
@borissmidt bonus points if you propagate this change throughout the lib :). Do we want to replace the list-based methods or expose additional chunk-based methods? We can swap their implementation to use the chunk-based ones, and perhaps mark them as deprecated.

**Comment by borissmidt** [comment]
Yes i will do it but on a part by part basis otherwise the PR becomes really big. I had a different branch where i started with most list parts. But then the scope became too big.
I was even hitting the engine itself.

**Comment by borissmidt** [comment]
> @borissmidt bonus points if you propagate this change throughout the lib :).
> 
> Do we want to replace the list-based methods or expose additional chunk-based methods? We can swap their implementation to use the chunk-based ones, and perhaps mark them as deprecated.

In my opinion the default methods should give you the highest performance. 
i.e. if chunk is faster than List than vanilla collectAll should return that.
Then you could add the collectAllList. So it is a more verbose to use. 

Or better yet add a collectAllSeq then it is compatible with most existing scala code unless chunk already is a Seq?

It's also the last time you can break binary compatibility and api before you go to version `1.0.0`.

**Comment by jdegoes** [comment]
@borissmidt Yes, Chunk is faster than List, and can be converted to List easily with `toList`. So it makes sense to use Chunk as the default data type, I think.

**Comment by adamgfraser** [comment]
Closing as this operator uses `Chunk` now.
