### ISSUE TITLE
Augment FiberRef constructor with "fork" operator

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3579]
Currently, to construct a fiber ref, one must supply:

```scala
initial: A
join: (A, A) => A = (_, r) => r
```

To be fully general, we should support an additional operation, "fork", which will be called when the value of the fiber ref is "forked" into a child:

```scala
initial: A
fork: A => A = identity(_)
join: (A, A) => A = (_, r) => r
```

The default, of course, is just the identity function.

**Comment by adamgfraser** [comment]
I will do this.
