### ISSUE TITLE
ZStream#repeatEffectWith: allow schedule to rely on the effect value

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3598]
[Good first issue]

Current signature of the method is 

`def repeatEffectWith[R, E, A](fa: ZIO[R, E, A], schedule: Schedule[R, Any, _]): ZStream[R, E, A]`.

It could be 
`def repeatEffectWith[R, E, A](fa: ZIO[R, E, A], schedule: Schedule[R, A, _]): ZStream[R, E, A]`
instead.

For example, this would allow to ask an external source for data, check whether returned data is empty and if it is - add a delay before the next try.

Could be achieved by rewriting this method in terms of `ZStream.unfoldM`.

**Comment by iravid** [comment]
This would be really nice. There are a bunch of other operators on ZStream that take schedules with an `Any` input. We should re-examine those too.
