### ISSUE TITLE
ZStream.debounce emit at end of stream

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3602]
I expect the following to result in `List(3)`, but right now it's an empty list:

```scala
ZStream(1, 2, 3).fixed[Any](500.millis).debounce(1.second).runCollect
```

I think the end-of-stream case isn't being handled. @luis3m Do you know if that's the case?

**Comment by luis3m** [comment]
@reibitto I will check this out in a few hours

**Comment by iravid** [comment]
Thank you @luis3m!

**Comment by luis3m** [comment]
@iravid @reibitto by just adding `if (chunk.isEmpty) Pull.empty else previous.interrupt *> store(chunk)` when the current fiber beats the previous one it works. I'm not sure why it's getting empty chunks though
