### ISSUE TITLE
Revert ZStream#runHead to pre-RC19 behavior?

### ISSUE THREAD

**Issue by iravid** [zio/zio#3634]
`ZStream#runHead` used to evaluate as little as possible of the stream to emit one element. We accidentally (or maybe not accidentally, can't remember 😅) changed it to evaluate everything but emit just one element.

What's the right behavior here? Would love to get inputs. @regiskuckaertz @simpadjo @adamgfraser

**Comment by simpadjo** [comment]
I'm afraid that this is `won't fix`. 
Short-circuiting operations could mitigate the problem by sprinkling `.either`s (and optionally `chunkN(1)`). But
1) it will not work for `Sink`s (they are unable to wrap the stream in `.either`)
2) it will not work for streams being transformed (via `flatMap`, `transduce`, etc.)
3) anyway, such sinks violate "Always consume entire chunks" rule. 
I never understood what this rule exactly means, but seems that this is the case :smile:

**Comment by iravid** [comment]
Yes, 3 is very true; such a sink would be lossy and not friendly to sink composition.

**Comment by simpadjo** [comment]
This thing actually could work, if counduits operated on `(Chunk[O], Option[E])`objects.
But the zio-streams need a break.

**Comment by paulpdaniels** [comment]
This is sort of counter-intuitive behavior for a stream, if you do `runHead` you'd expect it to do the least processing and just get the first value. Could we rename it to `runHeadFully` or something then make `runHead` an alias for `take(1).runHeadFully`?

**Comment by regiskuckaertz** [comment]
Isn't the eager version `stream.head` and `stream.tail`? I think the `run` prefix is a good indicator that the whole stream will be consumed.

**Comment by simpadjo** [comment]
Hm, true. `runHead` does what it supposed to do. 
But even 'lazy' `stream.run(ZSink.head)` will evaluate at least one entire chunk.

**Comment by simpadjo** [comment]
I vote for removing it after megring leftovers PR.
This would be just `.run(ZSink.head *> ZSink.drain)`

**Comment by iravid** [comment]
The confused user reports convinced me the previous behavior was right. Thank you for your inputs everyone
