### ISSUE TITLE
Add boolean algebra

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#3635]
Boolean operators can be lifted into a ZIO in two ways:

- avoid evaluating the second effect when the first yields the answer (i.e. false for `&&`, true for `||`, true for `==>`)
- race two boolean effects when both may take a long time and apply the same rule as above

Now for naming these combinators 😆 

wdyt?

**Comment by simpadjo** [comment]
`ZBool` :smile: 

```
sealed trait ZBool[R, E]{
  def evalLazy: ZIO[R, E, Boolean] = ???
  def evalPar: ZIO[R, E, Boolean] = ???
}
class Lift[R, E](v: ZIO[R, E, Boolean]) extends ZBool[R, E]
class ZOR[R, E](b1: ZBool[R, E], b2: ZBool[R, E]) extends ZBool[R, E]
class ZAND[R, E](b1: ZBool[R, E], b2: ZBool[R, E]) extends ZBool[R, E]
```

But what is the usecase?

**Comment by regiskuckaertz** [comment]
I was more thinking along the lines of:
```scala
trait ZIO[R, E, A] { self =>
  def && [R1 <: R, E1 >: E](that: => ZIO[R1, E1, Boolean])(implicit ev: A <:< Boolean): ZIO[R1, E1, Boolean] =
    self >>= (if (_) that else succeedNow(false))

  def || [R1 <: R, E1 >: E](that: => ZIO[R1, E1, Boolean])(implicit ev: A <:< Boolean): ZIO[R1, E1, Boolean] =
    self >>= (if (_) succeedNow(true) else that)
  ...
}
```
Just an optimisation for long chains of boolean operations that may cost a lot in space/time.
