### ISSUE TITLE
Could ZIO with zio-akka-cluster be an alternative to Apache Spark?

### ISSUE THREAD

**Issue by samthebest** [zio/zio#3642]
I've never used ZIO, so total noob, and I have a very general question (or a long list of specific questions).  Not sure this is the best place for it, apologies in advance if it isn't!

So the general version of the question is: Could ZIO with zio-akka-cluster be an alternative to Apache Spark?

https://github.com/zio/zio-akka-cluster

The specific questions:

1. Can one easily read/write data to S3?
2. Can one easily read/write data in Parquet format?
3. Does ZIO have shuffle operations, like join and groupby?
4. Do you have fine grained control over parallelism & partitioning, e.g. can I do `.repartition(100)`? Set number of executors? Set executor cores etc?
5. Would be nice to have some code (using AWS Java SDK) to spin up the Akka Cluster with all the necessary firewall rules and stuff, like EMR, does this exist?
6. Would ZIO only be for small/medium data (GBs), or could it handle Big Data (TBs)? (This question really boils down to how good the shuffle ops are mentioned in Q3)

If some of the answers are "no", but "maybe in the future", that would also be interesting.  Would be good to get a sense of timescale.

Regarding the WHY, well, Spark has some drawbacks:

 - Dataframes ruined the APIs, they should have continued iterating on RDD.
 - Stuck on Java 8
 - Stuck on Scala 2.12
 - In spite of it's maturity still has some weird exceptions

BTW, I'd be happy to contribute a library for 5, since I've written a lot of code using the AWS Java SDK.

**Comment by simpadjo** [comment]
I'd say no (without actually writing the second Spark).
Spark consist basically from
1) user-faced api for manipulating RDDs
2) resource allocation via YARN
3) communication between nodes
4) ecosystem of connectors and libraries

Zio could make (1) nicer
Akka-cluster could provide building blocks for (3) but communication protocols would have to be rewritten

Spark (if you restrict yourself to using only sane subset of features) is actually not that bad and MUCH more FP-friendly than akka.

**Comment by simpadjo** [comment]
Sane subset of Spark features is basically foldMap-as-a-service.

**Comment by samthebest** [comment]
> using only sane subset of features

🤣  Love this.  So like 10%, so like basically RDD.

**Comment by vasilmkd** [comment]
If I'm not mistaken, this falls under the scope of [zio-analytics](https://github.com/zio/zio-analytics)?

/cc @iravid

**Comment by iravid** [comment]
Closing as this is out of scope for this issue tracker. Feel free to continue the conversation on Discord!
