### ISSUE TITLE
Add ZSink.managed

### ISSUE THREAD

**Issue by iravid** [zio/zio#3651]
```scala
def managed[R, E, I, A, Z](m: R, E, A)(push: Chunk[I] => ZIO[R, E, Unit])
```

**Comment by simpadjo** [comment]
and make use of it in `ZSink.fromOutputStream` (which is in fact `ZSink.toOutputStream`)

**Comment by vasilmkd** [comment]
Has this naming been discussed anywhere? Merits of `from` vs `to`?

**Comment by iravid** [comment]
Hmm no. I don't think we should switch to `to`.

**Comment by simpadjo** [comment]
If we prefer to think in terms of how sinks are constructed rather than how the data flows, we should rename `ZSink.drain` to `ZSink.fromNowhere` :)

**Comment by iravid** [comment]
🤣

That's a fair point but I'm thinking of the constructors as:
- actions (foldLeft, drain, collectAll, ...)
- wrapping some sort of other abstraction into a sink (fromFile, fromOutputStream)

**Comment by regis-leray** [comment]
@iravid can you give some hints about, should i look into ZStream ?

```scala
def managed[R, E, I, A, Z](m: ZManaged[R, E, A])(push: Chunk[I] => ZIO[R, E, Unit]): ZSink[R,E, I,Z]
```

**Comment by regis-leray** [comment]
@iravid i think the signature should be more like this 

`push: (A, Chunk[I]) => ZIO[R, E, Unit]`

```scala
def managed[R, E, I, A, Z](m: ZManaged[R, E, A])(push: (A, Chunk[I]) => ZIO[R, E, Unit]): ZSink[R,E, I,Z]
```

am i correct ?

**Comment by simpadjo** [comment]
@regis-leray yes, the signature will be more like this.

I'm not 100% sure but seems that you can get away with `ZSink(m.flatmap(a => ...))`.

**Comment by regis-leray** [comment]
@simpadjo good this is exactly what i wanted to try 😎. I was puzzle by the `push` definition.
