### ISSUE TITLE
Make ZStream.Take easier to use

### ISSUE THREAD

**Issue by iravid** [zio/zio#3653]
`Take` is a type alias for `Exit[Option[E], Chunk[A]]`. This represents a step in a stream:
* `Exit.succeed(Chunk)` is an emission of a chunk;
* `Exit.fail(Some(E))` is a stream failure;
* `Exit.fail(None)` is an end-of-stream;
* `Exit.halt(Die/Interrupt)` are defects as usual.

In this ticket, we will convert it to the following form:
```scala
case class Take[E, A](exit: Exit[Option[E], Chunk[A]]) extends AnyVal
```

And provide the following facilities:
- An object with common constructors that forward to `Exit` constructors with adapations to the error/value types:
  - `Take.succeed(A)`
  - `Take.succeed(Chunk[A])`
  - `Take.fail(E)`
  - `Take.halt(Cause[E])`
  - `Take.end`
  - `Take.die(Throwable)`
  - `Take.dieMessage(String)`
  - `Take.done(Exit[E, A])`
- Folds for deconstructing `Take` values:
```scala
def fold[R, E, Z](end: => Z, error: Cause[E] => Z, value: Chunk[A] => Z): Z
def foldM[R, E1, Z](end: => ZIO[R, E1, Z], error: Cause[E] => ZIO[R, E1, Z], value: Chunk[A] => ZIO[R, E1, Z]): ZIO[R, E1, Z]
```
- The minimal subset of combinators required to port ZStream from using `Exit` directly to using `Take`

**Comment by luis3m** [comment]
@iravid what is fold supposed to do in case of `Cause.die` for instance?

**Comment by vasilmkd** [comment]
@luis3m Forward to, i.e. keep the semantics of, `Exit#fold`.

**Comment by luis3m** [comment]
@vasilmkd so make it to be:
```scala
def fold[R, E, Z](end: => Z, error: Cause[Option[E]] => Z, value: Chunk[A] => Z): Z
```
Or this one to avoid using `sequenceCauseOption` everywhere:
```scala
def fold[R, E, Z](end: => Z, error: Option[Cause[E]] => Z, value: Chunk[A] => Z): Z
```

**Comment by luis3m** [comment]
Actually, just
```scala
def fold[R, E, Z](end: => Z, error: Cause[E] => Z, value: Chunk[A] => Z): Z
```
As it should use `end` in case of `None`

**Comment by vasilmkd** [comment]
Yes, however that is the type signature for `foldCause`.

**Comment by iravid** [comment]
Ah this is true. `fold` should indeed be defined
```scala
def fold[R, E, Z](end: => Z, error: Cause[E] => Z, value: Chunk[A] => Z): Z
```

Will fix the description.

**Comment by vasilmkd** [comment]
Now I see that there are no `Cause` variants on `Exit`. I was misled by `foldCauseM` in the description. @iravid Is there a possibility to discriminate between these cases (`fold` and `foldCause`, and `M` variants)?

**Comment by iravid** [comment]
I think the fold has to account for the `Cause[E]` case, so it's either `Cause[E] => Z` or `E => Z, Cause[Nothing] => Z`.

Interestingly `=> Z, Cause[E] => Z, Chunk[A] => Z` is basically the previous encoding for `Take`.

**Comment by vasilmkd** [comment]
No, I don't consider splitting the `Cause` into `E` and `Cause[Nothing]` to be a good API. I meant more as `fold` being a weaker `foldCause` which cannot recover from defects.

**Comment by iravid** [comment]
Right but there's no aspect of recovery in the pure variants. You have to return a `Z`.

**Comment by luis3m** [comment]
@iravid is the idea here to introduce `Take` and then gradually change the combinators to use it instead of `Exit[Option[E], Chunk[O]]`?

**Comment by iravid** [comment]
I think I'd prefer one big PR but open to that too.

**Comment by luis3m** [comment]
I guess I can open a draft PR then

**Comment by simpadjo** [comment]
I'm a bit suspicious about overloading `.succeed` for chunks and single values.

**Comment by iravid** [comment]
Right. Good point. Let's go with `Take.single`, `Take.chunk`?
