### ISSUE TITLE
ZStream#tap causes data loss

### ISSUE THREAD

**Issue by thesamet** [zio/zio#3660]
In RC19-2, failures in the effect executed by `tap` cause the stream to drop elements that were produced prior to the failure, but possibly weren't consumed yet:

```
val myAppLogic =
    Stream(1,2,3)
    .tap {
      x => IO.when(x==3)(IO.fail("error"))
    }
    .either
    .runCollect.flatMap { x => putStrLn(x.toString) }
```

in RC19-2:
```
List(Left(error))
```

in RC18-2:
```
List(Right(1), Right(2), Left(error))
```

**Comment by iravid** [comment]
@thesamet Thanks for reporting. Fix incoming.
