### ISSUE TITLE
Please release zio-test-junit

### ISSUE THREAD

**Issue by dkarlinsky** [zio/zio#3662]
Junit support was merged in #2533, but `zio-test-junit` module apparently was never released to maven central.
@adamgfraser

**Comment by adamgfraser** [comment]
@dkarlinsky Thanks for raising!

@softinio @mijicd Any idea why this isn't being published? It looks like it is included in the root project.

**Comment by mijicd** [comment]
It seems that it is there : https://search.maven.org/artifact/dev.zio/zio-test-junit_2.13/1.0.0-RC19-2/jar

Am I missing something?

**Comment by adamgfraser** [comment]
@mijicd You're totally right. It is here as well: https://mvnrepository.com/artifact/dev.zio/zio-test-junit_0.23.

I didn't find it when I looked before but I think it is just pretty far down in the search results when you search for ZIO Test and when you throw JUnit in there you get a ton of things that are unrelated.

@dkarlinsky At least you have an artifact that you can use!

**Comment by dkarlinsky** [comment]
Great, Thanks!
Sorry for the confusion.
