### ISSUE TITLE
Rename Chunk#mapM_ to Chunk#tap

### ISSUE THREAD

**Issue by iravid** [zio/zio#3667]

**Comment by vasilmkd** [comment]
Picking this up.

**Comment by adamgfraser** [comment]
Is the `tap` name somewhat strange because it discards the chunk instead of returning it unchanged? Normally I think of tap as doing some side effect with a value without changing the underlying value.

**Comment by vasilmkd** [comment]
I'm with @iravid on this one. I think `mapM_` is a misnomer. The type signature `def mapM_[R, E](f: A => ZIO[R, E, Any]): ZIO[R, E, Unit]` is adequate for renaming to `tap`.

Checking the current implementation reveals that the effects don't change the chunk in any way, so `map` is definitely misleading. Opening a PR.

**Comment by adamgfraser** [comment]
I'm not defending the current naming, I just wonder if we should return the original chunk if we are going to call it `tap` or come up with a name that is more clear about the fact that it is discarding the chunk.

**Comment by vasilmkd** [comment]
Sorry, it's getting late. I get what you are saying. We are basically dealing with `foreach` with this type signature, right?

**Comment by adamgfraser** [comment]
Yeah, I was actually thinking it is very similar to the `foreach` signature on `ZStream` but unfortunately since `ZIO.foreach` collects the results of the effects I think it would be super confusing to use that.

**Comment by vasilmkd** [comment]
Alright, deferring this until tomorrow.

**Comment by guizmaii** [comment]
Closing as it's ZIO 1 issue and ZIO 1 isn't maintained anymore
