### ISSUE TITLE
Replace the implementation of ZStream#merge with one that doesn't race effects

### ISSUE THREAD

**Issue by iravid** [zio/zio#3682]
We're currently avoiding interruption of pulls in ZStream because most operators aren't interruption safe. While this is obviously bad and we should fix it at some point, our alternative strategy of using `raceWith` and keeping around the losing fiber can cause memory leaks over time (see e.g. #3679 and scalapb/zio-grpc#63 which I suspect are about this).

For this ticket, we need to replace the implementation of `merge` which currently races two pulls and emits the one that succeeded, with an implementation that runs both streams in the background and pipes them into a queue. The front of the stream is then a fiber that pulls from that queue.

This is pretty similar to `ZStream.mergeAll(left, right)` but we need a separate implementation to maintain the termination strategies.

**Comment by iravid** [comment]
cc @luis3m if you're interested!

**Comment by luis3m** [comment]
@iravid cool, I will take this one
