### ISSUE TITLE
Go all in on java.time?

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3685]
In particular, [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) could be used instead of our own type. Unlike Scala's Duration, its operators are total, with the exception of overflow (which could be regarded as a defect).

**Comment by simpadjo** [comment]
Similar thread on scala-contributors:
https://contributors.scala-lang.org/t/make-duration-and-finiteduration-general/4270

tldr: `java.time` is not supported by ScalaJs

**Comment by neko-kai** [comment]
@simpadjo ZIO already pulls `scala-java-time` for Scala.js, so I think that's covered.

**Comment by iravid** [comment]
I would sorely miss the 10.seconds syntax but that can stay in zio.duration._.

👍🏻 otherwise

**Comment by adamgfraser** [comment]
Would make interoperating with other libraries easier and we have gotten bitten by corner cases involving duration concepts a couple times.

**Comment by mijicd** [comment]
Adjusting the syntax and nuking it would be ideal, as Itamar said :).

**Comment by aappddeevv** [comment]
Going all in on java.time would make java.time required on the js platform. Front-end works is sensitive to dependencies. I've not checked, but if scala.time (as it is currently pulled in on JS for zio) increases bundle size significantly, that's a concern. I'll try to poke around a bit and see what the size impact is especially if the front-end also has to pull in other time libs that are already dependencies.

**Comment by fsvehla** [comment]
@aappddeevv Zio already depends on `scala-java-time`

**Comment by adrianfilip** [comment]
I will take a crack at this next week if no one else is working on it.

**Comment by plokhotnyuk** [comment]
Why not just write own `zio.time.Duration`? 

It can be less than 300 lines of Scala code including efficient parsing and serialization that could be borrowed from the jsoniter-scala library.

**Comment by adrianfilip** [comment]
I see no other comments. I am starting to work on this one.

**Comment by adrianfilip** [comment]
@jdegoes @adamgfraser @iravid 
What behaviour do you want when someone passes a negative Duration in operators where that doesn't make sense? Let's say a negative duration is used in ZIO.sleep. Should it fail, should it use the abs(value) or should it use the zero value (meaning it won't sleep at all)?

**Comment by adrianfilip** [comment]
I am making the (executive :D) decision to treat negative java.time durations as Duration(0).
This will also impact zio operations with Durations. 
Ex. Adding 2 durations where one is negative and one is positive will result in ignoring the negative one. Basically the moment negative durations are passed to any operator they get converted to Duration(0) or are ignored. Also if any operation will result in a negative duration that will also be converted to Duration(0).

I will continue based on this premise.

**Comment by adrianfilip** [comment]
Made a PR for this: https://github.com/zio/zio/pull/4026
