### ISSUE TITLE
zio-test: Parallel checkM

### ISSUE THREAD

**Issue by octavz** [zio/zio#3688]
Would be useful to have some kind of parallel  `checkM`, given some generators would execute in parallel instead of sequential.

**Comment by adamgfraser** [comment]
Yes. We are limited by the parallelism of the stream underlying the generator as far as producing elements, but we could definitely check multiple samples in parallel. I think we just need to implement a variant of `checkStream` like so:

```scala
def checkStreamPar[R, R1 <: R, E, A](stream: ZStream[R, Nothing, Sample[R, A]], maxShrinks: Int = 1000)(
  test: A => ZIO[R1, E, TestResult]
): ZIO[R1, E, TestResult] =
  stream.zipWithIndex
    // use mapMPar instead of mapM to perform test effects in parallel
    .mapMPar(???) { 
      case (initial, index) =>
        initial.foreach { input =>
          test(input).traced
            .map(_.map(_.copy(gen = Some(GenFailureDetails(initial.value, input, index)))))
            .either
        // convert test failures to failures to terminate parallel tests on first failure
        }.flatMap(sample => sample.value.fold(_ => ZIO.fail(sample), _ => ZIO.succeed(sample)))
    }
    // move failures back into success channel for shrinking logic
    .catchAll(sample => ZStream.succeed(sample))
    // shrinking logic unchanged and could be factored out into a separate combinator
```

I think the biggest challenge here is just method names for all these variants. We probably want to allow the user to control the degree of parallelism here and we are already using the `N` suffix to denote the number of samples to check. 😂

**Comment by lightning95** [comment]
I'd like to implement this.
