### ISSUE TITLE
Bugs with forking fibers

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3692]
Version 1.0.0-RC19-2
I'm currently tracking down a bug in production.

At some point my application fails with an error that zio executor rejected the task:

> 
> ay 20 05:22:57 imph04 java[1200]: ╠─An unchecked error was produced.
> May 20 05:22:57 imph04 java[1200]: ║ java.util.concurrent.RejectedExecutionException: Unable to run zio.internal.FiberContext$$Lambda$58
> May 20 05:22:57 imph04 java[1200]: ║         at zio.internal.FiberContext.evaluateLater(FiberContext.scala:712)
> May 20 05:22:57 imph04 java[1200]: ║         at zio.internal.FiberContext.evaluateNow(FiberContext.scala:528)
> May 20 05:22:57 imph04 java[1200]: ║         at zio.internal.FiberContext.$anonfun$fork$3(FiberContext.scala:706)
> May 20 05:22:57 imph04 java[1200]: ║         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> May 20 05:22:57 imph04 java[1200]: ║         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> May 20 05:22:57 imph04 java[1200]: ║         at java.lang.Thread.run(Thread.java:748)
> May 20 05:22:57 imph04 java[1200]: ║
> May 20 05:22:57 imph04 java[1200]: ║ Fiber:Id(1589952096236,268293529) was supposed to continue to:

This is not good itself, but even worse, application doesn't properly crash but rather hangs (Perhaps this is my fault).

As of now, I haven't found the bug but found something else instead:
1)

```
object Test {

  def main(args: Array[String]): Unit = {
    val runtime = zio.Runtime.default

    println("Start")

    val cached = Executors.newCachedThreadPool()
    val ec = ExecutionContext.fromExecutor(cached)

    val neverEndingTasks: Seq[Task[Int]] = (1 to 10000).map(i => Task.fromFuture(_ => Future {
      if (i % 1000 == 0) {
        println(s"Start $i")
      }
      while (true) {
        Thread.sleep(100000)
      }
      i
    }(ec)))

    val res = runtime.unsafeRun(ZIO.forkAll(neverEndingTasks).flatMap(_.join))
    println(s"DONE: $res")
    cached.shutdown()
    println("cleaned")
  }
}
```

- overflows: 

> java.lang.StackOverflowError
> 	at java.lang.invoke.Invokers.checkGenericType(Invokers.java:321)
> 	at scala.runtime.Statics.releaseFence(Statics.java:148)
> 	at scala.collection.immutable.$colon$colon.<init>(List.scala:623)
> 	at scala.collection.immutable.List.$colon$colon(List.scala:97)
> 	at zio.internal.FiberContext.await(FiberContext.scala:735)
> 	at zio.Fiber$$anon$4.await(Fiber.scala:392)
> 	at zio.Fiber$$anon$4.await(Fiber.scala:392)
> 	at zio.Fiber$$anon$4.await(Fiber.scala:392)
> 	at zio.Fiber$$anon$4.await(Fiber.scala:392)
> 	at zio.Fiber$$anon$4.await(Fiber.scala:392)

2) if I replace `val res = runtime.unsafeRun(ZIO.forkAll(neverEndingTasks).flatMap(_.join))` with 
`val res = runtime.unsafeRun(ZIO.forkAll_(neverEndingTasks))`

the task is considered completed ("Done" is printed) and the app hangs.

Send help.

**Comment by politrons** [comment]
@simpadjo  Hi I'm playing with your test and maybe I dont get it, but what you expect is that your program finish, print the Done and finally clean up all the Threads form the pool. But instead is getting stuck as is happening to me with your code right?.

What I see here, is since you have an endless loop for each thread, because you wrote a `while(true)` and you `join` in the `flatMap` your program can never end since it's imposible that the `fibers` that you `fork` can `join` back to the main thread, before it ends their process so your program got stuck waiting for that to happen.

Do you have in your production code something that can hang forever?, if that's the case I guess is logical your main thread got stuck waiting for that `join` to happen, and you should never try to bring back that fiber into the main Thread.

**Comment by simpadjo** [comment]
@politrons Hi, I expect this program to run forever w/o any exceptions. 
The runtime has been reworked since I reported this issue, so if you can't reproduce it - just close it.

**Comment by politrons** [comment]
I cannot with version 1.0 it just hang forever, so yep I think you can close it 😉
