### ISSUE TITLE
Spurious interrupt when using `ZStream#interruptWhen` together with `ZSream#mapMPar`

### ISSUE THREAD

**Issue by felher** [zio/zio#3693]
Version RC18-2 and RC19-2

When having some code like:

```scala
ZStream
  .fromIterable(List.fill(100)(0))
  .interruptWhen(ZIO.never)
  .mapMPar(8)(_ => sleepRandom)
  .runDrain
```

the last few instances of sleepRandom  (sleeps a random number ob milliseconds) together with the whole `.runDrain` sometimes get interrupted. Both the `interruptWhen` and `mapMPar` are necessary for the interruption to manifest. Leaving out `interruptWhen` or changing `mapMPar` to `mapM` removes the interruption.

Here is a small reproduction which starts a number of those streams and reports which ones have been interrupted and which ones run to completion:

https://scastie.scala-lang.org/GgbF9wGaRsehnoYX5aw5yQ

**Comment by luis3m** [comment]
It's worth mentioning this bug isn't exclusive to `interruptWhen` + `mapMPar`. You can also recreate this bug with:

- `timeout` + `mapMPar`
- `debounce` + `mapMPar`

It seems to be `mapMPar` specific as I couldn't recreate this issue with `flatMapPar` which has some similarities in the implementation.

**Comment by iravid** [comment]
Interesting. Thanks for noting that @luis3m. I haven't gotten to the bottom of this yet. Will continue digging later this week.

**Comment by luis3m** [comment]
@iravid I just submitted a PR, I understand why that change works but I'm not so sure why `ZIO.awaitAllChildren` does not.
