### ISSUE TITLE
Nevertheless return leftovers to ZSink

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3711]
This topic has been discussed few times already but there is no centralized place where one could read all pros and cons. Even if we don't get to agreement, let this place at least be a wiki.

Before the Great Stream Redesign sinks we allowed to emit a leftover together with a value. Moreover, the type of the lefover was not fixed to the type of the stream.
Now sinks are not allowed to emit leftovers at all.

**Motivation**: handling leftovers is hard.

**Counetrpoint**:
Now result of the sink composition depends on how the stream is chunked. See a recent complain:
https://discord.com/channels/629491597070827530/630498701860929559/714819824190095452

To mitigate this problem, we consider a proper sink only a sink that 

> Always consume entire chunks.

This requirement sounds quite vague to me. Also it quite easy to accidentally break it.
Moreover, we have a standard sink in the code that breaks this rule: `ZSink.head`.
This is debatable whether this sink breaks the rule or not (since it is vague), but FWIW, it gives surprising results (see the discord link).

Also using `flatMap` as a name for sink composition becomes more misleading: people expect that methods named after FP concepts don't do strange things.

Usecase from the link looks quite legit and no one provided a workaround for it.

**Proposal**
Bring back a share of the power that Sink used to have.

`type Push[-R, +E, -I, +Z] = Option[Chunk[I]] => ZIO[R, Either[E, (Z, Chunk[I])], Unit]`

Compared to the previous design, here the sink can't emit arbitrary leftover. The type must be the same as the input.
This would enable support of useful and intuitive `flatMap`s.

Requirement "Always consume entire chunks" translates to "Always consume entire value" which can be formalized:

If a stream `str` doesn't emit errors, `str.run(sink) === str.chunkN(1).run(sink)`

Consequences of this law: 
1) If `str1` and `str2` don't fail and have the same content, `str1.run(sink) === str2.run(sink)`
2) If `sink(Some(input))` emitted  `(value, leftover)`, then ~~`input.endsWith(leftover)`~~
`input.endsWith(leftover)` of `leftover.endsWith(input)`

I do believe that there have been reasons to remove leftovers but it would be great to have a list of problematic cases written explicitly. So one could test the prototype against them.

E.g. would successful migration of existing ZSink constructors, combinators and tests be enough to prove that leftovers are viable? 

cc @iravid @jdegoes

**Comment by simpadjo** [comment]
One problem I can see:
Sink is no longer contravariant on `I`.
There should be a method to convert it explicitly.

**Comment by iravid** [comment]
The number of complaints on the Discord channel has swayed me as well. However, `Option[Chunk[I]] => ZIO[R, Either[E, (Z, Chunk[I])], Unit]` is not the signature I want for this. I am convinced there is a way to encode this as `Option[Chunk[I]] => ZIO[(R, Ref[Chunk[I]]), Either[E, Z], Unit]`, similar to how `StateT[ZIO[R, E, ?], S, A]` can be encoded as `ZIO[(R, Ref[S]), E, A]`.

I will try to come up with a prototype next week.

**Comment by simpadjo** [comment]
What are the advantages?

**Comment by simpadjo** [comment]
Ah, at least it solves the issue with contravariance.

**Comment by iravid** [comment]
@simpadjo Feel free to experiment with that and put something together if you have the time!

**Comment by simpadjo** [comment]
After 10 minutes already have to remove `contramap` operations. Bad start!

**Comment by iravid** [comment]
Yes it's entirely plausible they have to go. This was the reason we had `A0` on the previous encoding.

**Comment by simpadjo** [comment]
@iravid 
The biggest problem so far: can't implement `Transducer >>> Sink`.
`Transducer[A, B] >>> Sink[B, C]` should result in `Sink[A, C]`. But the type of the leftover is `B` and I can't untransduce it back to `A`.

**Comment by iravid** [comment]
Resolved by #3722
