### ISSUE TITLE
ZStream#intersperse breaks with usage of Stream.repeatEffect

### ISSUE THREAD

**Issue by svranesevic** [zio/zio#3729]
`ZStream#intersperse` breaks with usage of `Stream.repeatEffect`.

Test case:
```scala
testM("intersperse several from repeat effect") {
  Stream
    .repeatEffect(ZIO.succeed(42))
    .map(_.toString)
    .intersperse("@")
    .take(4)
    .runCollect
    .map(result => assert(result)(equalTo(Chunk("42", "@", "42", "@"))))
}
```
Failure: `Chunk(42,42,42,42) did not satisfy equalTo(Chunk(42,@,42,@))`

Note: Moving `ZStream#take` beforehand `ZStream#intersperse` yields the same failure.

_Edit:_ Correct failure message

**Comment by svranesevic** [comment]
Two more test cases that might be interesting, with `ZStream.repeatEffectChunk` though.


1. **Passing** test case:
```scala
testM("intersperse several from repeat effect chunk") {
  Stream
    .repeatEffectChunk(ZIO.succeed(Chunk(42, 42, 42, 42)))
    .map(_.toString)
    .intersperse("@")
    .take(4)
    .runCollect
    .map(result => assert(result)(equalTo(Chunk("42", "@", "42", "@"))))
}
```

2. **Failing** test case:
```scala
testM("intersperse several from repeat effect chunk single element") {
  Stream
    .repeatEffectChunk(ZIO.succeed(Chunk(42)))
    .map(_.toString)
    .intersperse("@")
    .take(4)
    .runCollect
    .map(result => assert(result)(equalTo(Chunk("42", "@", "42", "@"))))
}
```
Failure:`Chunk(42,42,42,42) did not satisfy equalTo(Chunk(42,@,42,@))`

**Comment by iravid** [comment]
Thanks for reporting @svranesevic. Looks like just a bug in the intersperse implementation. Will have a fix soon.

**Comment by iravid** [comment]
@svranesevic You can copy the fixed implementation to your project until we have a new release out. Thanks again for reporting!

**Comment by svranesevic** [comment]
@iravid Thank you for the quick turnaround!
