### ISSUE TITLE
Fiber failure with ZStream.aggregateAsyncWithin and ZStream.interruptWhen

### ISSUE THREAD

**Issue by svroonland** [zio/zio#3740]
In this infinite stream, `interruptWhen(ZIO.never)` is used, yet the stream fails with an interruption error. This appears to be present in RC19-2 and RC20 (https://scastie.scala-lang.org/ywITkPfqR3e627YCKEC9uA and https://scastie.scala-lang.org/0fDYgZ5jSBO3gT84LQiwYA)

**Comment by svroonland** [comment]
I tried to change `interruptWhen` to use `raceAll` instead of `raceFirst`. That gives even stranger behavior, with the stream appearing to be stuck. See example here, no more "aggregate async done" messages are being printed after a short while.

https://scastie.scala-lang.org/5WAVeooJTfeT5kxfMrNNdA

**Comment by luis3m** [comment]
@svroonland it's the same issue. The thing is, `raceAll` interrupts the other fibers as soon as it gets its first success. `as` is being interrupted therefore it waits for the promise to succeed and that's why it hangs.

```scala
as.tapCause(c => UIO(println(c.prettyPrint)))
```
Add this to `myInterruptWhen` and you'll get an interruption error.

**Comment by iravid** [comment]
Hey @luis3m. Do you have any insight as to what's going on here?

**Comment by luis3m** [comment]
@iravid sort of, I'm still trying to understand why it's happening, I will give an update tomorrow. It's very likely I will need help understanding the issue but can tell that disowning `producerWaiting` solves the issue.

**Comment by luis3m** [comment]
Thinking a bit deeper I realized that this should also happen with other combinators such as debounce as it also stores a fiber to await later and I was right, `debounce` does not work with `interruptWhen` (or any other combinator racing fibers I guess):

https://scastie.scala-lang.org/hjcUbjl5QfSTHKkC5MTIzw

**Comment by luis3m** [comment]
I feel I'm missing something basic here but my understanding is that it's not working because parent fibers terminate children which is why these fibers saved for later are being interrupted but I fail to understand why `interruptWhen` is needed to recreate the issue.

**Comment by svroonland** [comment]
I played around with this and I think I also understand now, thanks to @luis3m. 

The forked fiber for `waitForProducer` created by `updateSchedule.raceWith(waitForProducer)` is a child fiber of the `runIO.join.raceFirst(as)` in `interruptWhen`, which also forks `as`. So there's:
main fiber -> interruptWhen's `as` fiber -> waitForProducer fiber. 

`interruptWhen` will, as part of `raceFirst`, call `join` on the `as` fiber, which interrupts its child fibers: in this case the `waitForProducer` fiber. 

So this issue would only show up when the fiber running `aggregateAsyncWithinEither` (loosely speaking) is joined, such as by `interruptWhen`.

So as a rule of thumb: if you fork fibers that you don't join or interrupt yourself, like in `aggregateAsyncWithin`, you have to disown them?

**Comment by luis3m** [comment]
@svroonland very well put, yes.

**Comment by svroonland** [comment]
I made a PR with the fix you suggested @luis3m. Also made an attempt to clean up the disowned fiber on stream shutdown. I have the feeling that I haven't considered all edge cases. I'm wondering if there's an alternative way to implement aggregateAsyncWithinEither that has more inherent resource cleanup guarantees somehow?

I also plan to think of some test case(s) for this.

**Comment by luis3m** [comment]
@svroonland I had the following test case locally:
```scala
assertM(
  ZStream
    .fromSchedule(Schedule.fixed(100.millis))
    .tap(_ => TestClock.adjust(100.millis))
    .aggregateAsyncWithin(ZTransducer.last, Schedule.fixed(500.millis))
    .interruptWhen(ZIO.never)
    .take(5)
    .someOrFail(None)
    .runCollect
)(equalTo(Chunk(3, 8, 13, 18, 23)))
```
I peeked at your draft and I don't think you need to join the fiber. I think you just need to interrupt it in case the stream gets interrupted or fails. (cc @iravid)

**Comment by svroonland** [comment]
@luis3m You're right, interruption makes more sense. In fact joining will not work because the producer may not produce anything anymore.

I added your test case and marked the PR ready for review.
