### ISSUE TITLE
Chunk.toArray StackOverflow, ZIO-RC19

### ISSUE THREAD

**Issue by KadekM** [zio/zio#3753]
```
Java.lang.StackOverflowError at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at zio.Chunk$Concat.toArray(Chunk.scala:1128) at 
zio.Chunk$Concat.toArray(Chunk.scala:1128) at
```
and so on

**Comment by adamgfraser** [comment]
@KadekM Thanks for reporting! Will take a look.

**Comment by KadekM** [comment]
@adamgfraser would it be possible to do release after this is merged? It's rather problem for us

**Comment by adamgfraser** [comment]
@KadekM A snapshot is released on every commit and then we are also planning on doing another release candidate tomorrow so will have this in soon.

**Comment by KadekM** [comment]
@adamgfraser is there something I can do to help with this?

**Comment by adamgfraser** [comment]
@KadekM Sorry for the delay. Was going to get this in along with the fiber supervision changes and do the next release candidate but we’re still working through a couple of issues with fiber supervision so just merged this. Snapshot should be available shortly.

**Comment by KadekM** [comment]
@adamgfraser thanks :+1:

**Comment by coderfromhere** [comment]
this (or a similar exception) is still happening. Whenever I run a ZIO effect in my main app and expect this to work (`CLI` implements arguments parsing, and for the sake of the example is irrelevant because it never gets reached if `.toList` or `.toArray` is used on `args`):
```
    override def run =
        val program =
            for
                args <- getArgs
                opts <- CLI.execCLI(args = args.toList)
            yield opts match
                ...
```

the application terminates abruptly without any error propagation. If I replace `args.toList` to `args.toString.splt(" ")` it does work and produces expected CLI arguments mismatch error.

**Comment by adamgfraser** [comment]
@coderfromhere Do you have a reproducer?

**Comment by coderfromhere** [comment]
@adamgfraser no sorry, I tried to extract it into a self-contained sbt build target and it was working there, perhaps I was too eager to google search for a similar issue before investigating deeper on my side.
