### ISSUE TITLE
ZStream.repeatEffect runs effect more times than should

### ISSUE THREAD

**Issue by bosyi** [zio/zio#3762]
On RC18-2 i have following code(count, println added):
https://scastie.scala-lang.org/bosyi/9SaEnmIjRqyY25xKSBUmJw/6
```
var count = 0
Stream.repeatEffect(IO.effect{println(count); count = count + 1; z.getNextEntry}).
  takeWhile(_ != null).
  filter(_.getName == "version").
  runHead.
  flatMap(_ => IO.succeed(println(s"ok. $count")))
```
which produces
0
ok. 1
that is absolutely right as for test i am using zip archive with one file inside with name version
but after updating to RC20 i have NPE
```
Fiber failed.
An unchecked error was produced.
java.lang.NullPointerException
        at zio.Chunk$Tags$.fromValue(Chunk.scala:1375)
        at zio.Chunk$Singleton.<init>(Chunk.scala:1219)
        at zio.Chunk$.single(Chunk.scala:919)
        at zio.stream.ZStream$.$anonfun$repeatEffectOption$1(ZStream.scala:3598)
```
so i try to rewrite code to repeatEffectOption
https://scastie.scala-lang.org/bosyi/9SaEnmIjRqyY25xKSBUmJw/7
```
var count = 0
Stream.repeatEffectOption(IO.effect(Option({println(count); count = count + 1; z.getNextEntry})).some).
  filter(_.getName == "version").
  runHead.
  flatMap(_ => IO.succeed(println(s"ok. $count")))
```
which now produce this for same input file:
0
1
2
ok. 3
Also problem remains also for repeatEffect. Same results. Just Fiber failed in the end

**Comment by luis3m** [comment]
@bosyi I cannot recreate this issue with `repeatEffectOption`: https://scastie.scala-lang.org/05uAIDQ6RzqrdVw5zw7UrA

**Comment by bosyi** [comment]
@luis3m my bad, i had RC18-2 before.
Example with RC18-2 https://scastie.scala-lang.org/bosyi/9SaEnmIjRqyY25xKSBUmJw/6
Example with RC20 https://scastie.scala-lang.org/bosyi/9SaEnmIjRqyY25xKSBUmJw/7

**Comment by luis3m** [comment]
@bosyi the behavior of `repeatEffectOption` is actually the same. The confusion here is `runHead` (see #3634)

Try `runCollect` (or `run(ZSink.head)`) instead and you should get the same result on both of those examples. As for `repeatEffect`, what do you think @iravid? `Tags.fromValue` is causing this. I guess this is something that we want to fix even though it's null right?

**Comment by iravid** [comment]
I don't think we can safely support nulls. This will probably result in a class cast exception: `(Chunk(1, 2) ++ Chunk(null)).toArray`.

As for the `runHead` trouble, I think we have enough evidence that the pre-RC19 behavior was correct.

Thank you for reporting @bosyi. Feel free to ask any follow up questions or close if you're good.
