### ISSUE TITLE
ZStream.buffer buffers chunks instead of single values

### ISSUE THREAD

**Issue by svroonland** [zio/zio#3766]
For example, `someZStream.buffer(100)` will buffer up to 100 chunks instead of 100 elements.

**Comment by luis3m** [comment]
I'll take this one

**Comment by iravid** [comment]
@luis3m If possible - could you rename the chunk versions as `bufferChunks`? After the performance issues in zio-kafka due to destroying the chunking structure, I think these variants could prove useful.

**Comment by luis3m** [comment]
@iravid sure

**Comment by ghostdogpr** [comment]
Fixed in https://github.com/zio/zio/pull/4967
