### ISSUE TITLE
ZIO-Test: Support for architecture test

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#3767]
Archunit works really well with Java and Kotlin but lacks solid support for Scala. It would be great if `zio-test` could start with some basic support to write unit tests for architecture.

I am not sure if this is within the scope of ZIO Test but I think it would be a great feature to add.

**Comment by adamgfraser** [comment]
@tusharmath I think that would be great. I think given that at least as I understand it this would add an additional dependency I think this would make sense as a separate project (e.g. `zio-test-archunit`) that would live in its own repository. I don't have the knowledge of it or capacity to do myself but if you or anyone else is interested I think it would be fantastic and will help in any way I can. If it is alright with you I think we should probably close this issue as I don't think there is an actionable item in this repository. Maybe we can follow up on Discord to see if anyone else would be interested in working on this?

**Comment by adamgfraser** [comment]
Going to close this as while I think this would be a great addition I don't think there are concrete action items for us to take within this repository. If you are interested in exploring this and there is anything I can do to help please let me know.
