### ISSUE TITLE
ZIO's java facade.

### ISSUE THREAD

**Issue by He-Pin** [zio/zio#378]
It makes a lot of sense to provide a Java facade to make ZIO easy to use from Java:).Could be a separate module.

**Comment by jdegoes** [comment]
Would love this (in a separate module)! Could set the Java world on fire. 😉

**Comment by LukaszByczynski** [comment]
I think this will be good task for upcoming hackaton.

**Comment by guizmaii** [comment]
Closing as it'll probably never happen
