### ISSUE TITLE
Add ZStream#retry to retry the stream

### ISSUE THREAD

**Issue by svroonland** [zio/zio#3785]
There is `ZIO#retry`, we should have an equivalent for `ZStream`. 

TBD: semantics, retry the entire stream or just the last pull?

**Comment by svroonland** [comment]
cc @adamgfraser about the semantics: pull or whole stream

**Comment by svroonland** [comment]
Just noticed that #1711 is also about retrying, but just the latest pull.

**Comment by adamgfraser** [comment]
Closed by #4409.
