### ISSUE TITLE
ZLayer.mapValue and ZLayer.unit

### ISSUE THREAD

**Issue by Fristi** [zio/zio#3802]
```scala
    def mapValue[B: Tag](f: A => B): ZLayer[R, E, Has[B]] = layer.map(a => Has(f(a)))
    def unit: ZLayer[R, E, Has[Unit]]                     = layer.mapValue(_ => ())
```

`mapValue` is 'valuable' when you want to select a value from a configuration dependency:

```scala
  val appConfig      = config.layers.load[AppConfig]
  val dbConfig       = appConfig.mapValue(_.get.db)
```

`unit` is valuable when you have top level dependencies which model a long running process which returns something else then `Unit`

```scala
  val app            = consumer ++ producer ++ internalServer.unit ++ externalServer.unit

  def bootstrap: ZManaged[ZEnv, Throwable, Unit] =
    app.build.unit
```

**Comment by adamgfraser** [comment]
What are the types of `consumer` and `producer` in your example? Why do you need to call `unit` there if you are already calling `unit` on the `Managed` you are building from the layer?

**Comment by Fristi** [comment]
Good point, I think that would be an easy way to fix it.

What do you think of adding `mapValue` (or maybe call it something else) or does there already exist such a thing? :)

**Comment by Fristi** [comment]
I see `ZLayer#project` has been implemented, closing this
