### ISSUE TITLE
Defect in Has error and different compile behaviour with dotty

### ISSUE THREAD

**Issue by tgroehl** [zio/zio#3816]
I'm currently playing around with Dotty (0.23.0-RC1) and ZIO (1.0.0-RC20) and I'm getting a runtime error when running a small piece of code, which works fine under Scala 2.13.2.

Another thing I noticed is a different compile behavior between dotty and 2.13.2. The first time when I tried to compile the code with 2.13.2 the compiler (rightfully) complained about the missing implicit `Tag`s for `A` and `D`. I used dotty before 2.13.2 and didn't notice that they were missing. The dotty-compiler did not complain and is able to compile the same code without the necessary implicits. So this might be a dotty bug, but I'm not sure.

Here is the piece of code I'm talking about. To get the different results during compile time simply remove all `: Tag` occurrences.
```scala
import zio._
object Test extends zio.App{

    class Container[A](val a : A) 
    type ContainerProvider[A, D <: Container[A]] = Has[ContainerProvider.Service[A,D]]

    object ContainerProvider{

        trait Service[A, D <: Container[A]]{
            def provide: IO[Throwable, D]
        }

        def layer[A: Tag, D <: Container[A] : Tag](container: D): Layer[Nothing, ContainerProvider[A,D]] = 
            ZLayer.succeed{
                new Service[A,D]{
                    def provide: IO[Throwable, D] = IO.succeed(container)
                }
            }
     
        def provide[A: Tag, D <: Container[A] : Tag]: ZIO[ContainerProvider[A, D], Throwable, D] =
            ZIO.accessM{_.get.provide}    
    }
    
    def run(args: List[String]): zio.ZIO[zio.ZEnv, Nothing, zio.ExitCode] = 

        program.provideCustomLayer(ContainerProvider.layer[Int, Container[Int]](new Container(10)))
           .map(x => println(x))
           .either
           .map(x => zio.ExitCode(0))

    def program:ZIO[ContainerProvider[Int, Container[Int]], Throwable, Container[Int]] = 
        ZIO.accessM{ x => 
            ContainerProvider.provide
        }
}
```

And here is the stack-trace of the runtime error:
```
[error] java.lang.Error: Defect in zio.Has: Set(Test$::ContainerProvider$::Service[=Int,=Test$::Container[=Int]]) statically known to be contained within the environment are missing
[error]         at zio.Has$HasSyntax$.prune$extension(Has.scala:136)
[error]         at zio.Has$HasSyntax$.union$extension(Has.scala:148)
[error]         at zio.Has$$anon$2.union(Has.scala:92)
[error]         at zio.Has$$anon$2.union(Has.scala:91)
[error]         at zio.ZLayer.$plus$plus$$anonfun$1(ZLayer.scala:53)
[error]         at zio.ZManaged.zipWith$$anonfun$2$$anonfun$1(ZManaged.scala:1087)
[error]         at zio.ZManaged.map$$anonfun$1(ZManaged.scala:443)
[error]         at zio.ZIO$MapFn.apply(ZIO.scala:3790)
[error]         at zio.ZIO$MapFn.apply(ZIO.scala:3789)
[error]         at zio.internal.FiberContext.nextInstr(FiberContext.scala:844)
[error]         at zio.internal.FiberContext.evaluateNow(FiberContext.scala:392)
[error]         at zio.internal.FiberContext.fork$$anonfun$3(FiberContext.scala:706)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:74
```

**Comment by jdegoes** [comment]
This is most likely in Izumi reflect, but good to track here too! 🙏

**Comment by neko-kai** [comment]
@tgroehl 
>  I used dotty before 2.13.2 and didn't notice that they were missing. The dotty-compiler did not complain and is able to compile the same code without the necessary implicits.

There's a fairly involved piece of logic, `TagMacro`, in izumi-reflect that takes care of combining available `: Tag` evidences into types at runtime, by recursively doing implicit lookups for type parameters encountered in the type structure.

This `TagMacro` simply does not exist for the dotty version, so until it's added the tag evidences will not be combined in Dotty. (Also dotty version allows invalid/unresolved types, such as those with type parameters to slip through without errors, that's related but separate)

For the case in your example this can actually be worked around by requesting a "preassembled" tag (this will also improve performance in general):

```scala

        def layer[A, D <: Container[A]](container: D)(implicit t: Tag[ContainerProvider[A, D]]): Layer[Nothing, ContainerProvider[A,D]] = 
            ZLayer.succeed{
                new Service[A,D]{
                    def provide: IO[Throwable, D] = IO.succeed(container)
                }
            }
```

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/issues/103
