### ISSUE TITLE
ZStream.grouped can return empty Lists

### ISSUE THREAD

**Issue by reibitto** [zio/zio#3818]
This behavior changed after the ZTransducer changes:

```scala
ZStream.fromIterable(List.empty[Int]).grouped(5).mapM { x =>
  // This block will run with `x` being an empty list
  ...
}
```

I found this a bit surprising. Prior to RC19, that block would not run since the stream is empty and there is nothing to map.

**Comment by simpadjo** [comment]
Yes, looks like a bug, I'll fix it
