### ISSUE TITLE
Incorporate support for Gitpod?

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#3820]
<https://www.gitpod.io>

**Comment by mgenereu** [comment]
I'm using Zio while developing in Gitpod.  Works fine.  What would you expect?

**Comment by mgenereu** [comment]
I'm assuming by support you meant make the project easily editable in Gitpod. Hope that's what you meant and feel free to clarify.

**Comment by mgenereu** [comment]
Please note: The template from Gitpod is based on their really heavy Docker image. I can see this being a good first working version but using a lighter base image and optimization might take a few iterations. I'm on a Chromebook and Gitpod doesn't have a strong Dockerfile iteration process that doesn't require a commit to the repository each time.

**Comment by jdegoes** [comment]
@mgenereu Yes, I was hoping we could make it as easy to contribute to ZIO as clicking a button. 😄
