### ISSUE TITLE
`ZStream#fromIterator(Managed)` should have an optional `chunkSize` parameter

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3841]
[Good first issue]
`ZStream#fromIterator` creates a task for pulling each individual element. This makes it infeasible for low-level tasks.

It can be worked around by calling `ZStream.fromIterator(it.grouped(1000))`.
Explicitly adding `chunkSize` parameter would save users from accidentally hitting this problem.

**Comment by simpadjo** [comment]
How to undo an accidental thumbsup on my own issue?  :rofl:

**Comment by lvitaly** [comment]
@simpadjo @iravid hey, can I take it?

**Comment by simpadjo** [comment]
Sure!

**Comment by ogresto** [comment]
'This job has been blocked because resource-class:large is not available on your plan. Please upgrade to continue building.' 

 could you please upgrade ci plan ?

**Comment by emilhotkowski** [comment]
@adamgfraser Looks fixed
