### ISSUE TITLE
Schedule lags between occurs 1 and 2

### ISSUE THREAD

**Issue by kubukoz** [zio/zio#3850]
I'm sorry if the description is too specific, but I haven't dived into why this happens yet.

Given such a program, which prints the amounts of milliseconds since it started, on a schedule:

```scala

import zio._
import zio.console._
import zio.clock._
import zio.duration._
import java.util.concurrent.TimeUnit

object ZIOMain extends zio.App {
  def run(args: List[String]): URIO[ZEnv, ExitCode] = program.as(ExitCode.success)

  val program = clock.nanoTime.flatMap { startTime =>
    val newTime = clock.nanoTime.map(_ - startTime).map(_ / 1000000).map(_.toString)

    newTime.flatMap(a => ZIO.effectTotal(println(a))).repeat(Schedule.spaced(100.millis))
  }
}
```

On my machine it results in output like:

```
191
481
583
684
785
886
987
1089
1191
1293
1394
1495
...
```

While most numbers are greater than the previous ones by roughly 100, the difference between 191 and 481 is 290, so about 190ms of extra delay. I've been getting consistent results on this, and the difference is even more visible if the spacing (100ms) is decreased, or removed altogether (`Schedule.recurs`):

```
83
164
164
164
165
165
```

It doesn't happen when I repeat with manual recursion, or in `forever` (which doesn't use `repeat` but recurses as well).

Could it be just some overhead from initially constructing the schedule, which benefits from caching on later attempts? It feels a bit too repeatable, but maybe there are some optimizations there.

I'm running RC21 on graalvm CE 20.0.0.

**Comment by jdegoes** [comment]
Thanks for reporting, will look into this soon!

Did you try `Schedule.fixed`?

**Comment by kubukoz** [comment]
I just did, same thing:

```
80
236
236
242
251
261
272
282
292
301
311
322
332
341
351
361
371
381
392
401
412
421
432
```

(`Schedule.fixed(10.millis)`)

**Comment by kubukoz** [comment]
Also, `Schedule.forever.addDelay(_ => 10.millis)` (which I guess is fewer combinators on top of the primitive implementation).

**Comment by heaven-born** [comment]
From what I could find, the issue is most likely inside `ZIO#repeatOrElseEither`. It produces the original effect without any delay, and only after that starts using `schedule.driver` for scheduling. 

    self.foldM(   // <- problem is here
            e => ...
            a => loop(a) // <-- here scheduling begins
    )

I'm not vert good at the internals of ZIO, so I'm not sure now to fix it. It will probably require changing signature of Driver#next in order to make to works with `ZIO[,,In]` instead of just `In`.

**Comment by heaven-born** [comment]
I modified @kubukoz 's program a bit in order to see the difference between calls:

    val program = for {
       startTime <- clock.nanoTime
       prev <- Ref.make(-1L)
        _ <- (
            for {
              newTime <-clock.nanoTime.map(_ - startTime).map(_ / 1000000)
              diff <- prev.get.map(p =>  if (p == -1L) 0 else newTime - p)
             _ <- putStrLn(newTime.toString + " ms; diff between curr and prev= " + diff )
             _ <- prev.set(newTime)
             } yield ()

         ).repeat(Schedule.spaced(100.millis) *> Schedule.recurs(4))
    } yield ()

So now it prints the following:

    117 ms; diff between curr and prev= 0
    560 ms; diff between curr and prev= 443
    668 ms; diff between curr and prev= 108
    769 ms; diff between curr and prev= 101
    872 ms; diff between curr and prev= 103

With this implementation on my laptop an average difference between lines 1 and 2 is about 440 ms.

Following change decreases the average value from  440 ms to 340 ms

     val program2 = clock.currentDateTime.orDie *> program

Which is an evidence for an issue related to `Schedule#Driver#next` first call, because`Schedule#Driver#next` is created inside `Schedule#driver` which in its turn uses `clock.currentDateTime` in `val next`.  So at least part of the delay seems to be an initialization issue. 

The rest of extra delay remains unclear for me, but it can be anything including `step` function used in `val next`.

**Comment by heaven-born** [comment]
This is even more straightforward demonstration of the issue:

    val lightProgram = for {
      driver <- Schedule.spaced(100.millis).driver
      startTime <- clock.nanoTime
      _ <- driver.next(0).catchAll(_=>putStrLn("never happen"))
      midTime <- clock.nanoTime
      _ <- driver.next(0).catchAll(_=>putStrLn("never happen"))
      endTime <- clock.nanoTime
      diff1 = (midTime - startTime)
      diff2 = (endTime - midTime )
      _ <- putStrLn("diff1 ="+ diff1)
      _ <- putStrLn("diff2 ="+ diff2)
    } yield ()

`diff1` value is be reduced with early initialisation  approach:  `clock.currentDateTime.orDie *> lightProgram`

**Comment by heaven-born** [comment]
The new `schedule` method almost eliminates this issue if  `.repeat(Schedule.spaced(100.millis))`is replaced with `.schedule(Schedule.once ++ Schedule.spaced(100.millis))`  or `.schedule(Schedule.spaced(100.millis))`

Though there is still about 15 milliseconds difference between the first two calls.

    putStrLn(System.nanoTime()/1000000  + " ms;"  )
      .schedule(Schedule.once ++ Schedule.once ++ Schedule.once ++ Schedule.once)

returns

40203**848** ms;
40203**863** ms;
40203**864** ms;
40203**865** ms;

**Comment by jdegoes** [comment]
I think we can call this issue fixed, although we could open a separate one to optimize the performance of schedule initialization.

Thanks for your feedback!
