### ISSUE TITLE
Cond like constructor

### ISSUE THREAD

**Issue by LukeDefeo** [zio/zio#3854]
Hello I was looking for a method like cond on Either. It would work like so:

```
object ZIO {
 def cond[E, A](predicate: Boolean, error: => E, result: => A): IO[E, A] = if (predicate) ZIO.succeed(result) else ZIO.fail(error)
}
```

is there another way of doing this? if not would you consider a pr with a method like this?

**Comment by adamgfraser** [comment]
@LukeDefeo I don't think we have something with that signature today but sounds like a great addition!

**Comment by gerdreiss** [comment]
@adamgfraser I've added the Either.cond like constructor to ZIO. Could you please review, since you've approved the idea? ;)
