### ISSUE TITLE
ZStream.tick does not run the action first before waiting the interval

### ISSUE THREAD

**Issue by loicdescotte** [zio/zio#3863]
`ZStream.tick(duration)` relies on `ZStream.spaced(duration)`, which is defined like this in the scaladoc :
`|action|-----interval-----|action|-----interval-----|action|`

But it seems that it is rather behaving like this  : `-----interval-----|action|-----interval-----|action|`

Example : 

```scala
object TestTick extends App {

  val tick = ZStream.tick(1.second).map(_ => "tick")
  val tack = ZStream.tick(10.second).map(_ => "tack")
  zio.Runtime.default.unsafeRun(
    tick.merge(tack).foreach(t => putStrLn(t))
  )
}
```

If you run this, you will not see "tack" directly but only after 10 seconds : 

```
tick
tick
tick
tick
tick
tick
tick
tick
tick
tack <-
```

**Comment by simpadjo** [comment]
I expect `ZStream.tick` not to emit a tick immediately (the most useful behavior IMHO), so `tick` looks correct to me. 
Clarification could be added, though.

`ZSchedule.spaced` description seems a bit misleading: actual behavior of it is 
`-----interval-----|action|-----interval-----|action|` .
But when you call `action.repeat(Schedule.spaced(t))`, the timeline is like in docs:
` |action|-----interval-----|action|-----interval-----|action|`

**Comment by simpadjo** [comment]
Idk, I'd personally just call `ZStream(()) ++ ZStream.tick` but let @iravid decide.

**Comment by iravid** [comment]
All of the stream scheduling combinators are using the "perform once and then use the schedule", so we should definitely align `ZStream.repeatEffectWith` (which underlies `tick` and all the rest) with this scheme.
