### ISSUE TITLE
Set Execution Context in ZIO.fromFuture

### ISSUE THREAD

**Issue by politrons** [zio/zio#3864]
Hi all, I´m reading the documentation of ZIO future https://zio.dev/docs/interop/interop_future 
But I cannot find a way to specify the ExecutionContext that I want to use for that Future. I guess by default it's using the Scala global one, but that one give us a very poor performance and I would like to specify a one from us.

**Comment by adamgfraser** [comment]
@politrons The future will be run on ZIO's thread pool by default. You can control the execution context using the `ZIO#lock` or `ZIO#on` combinators. If you want to come over to Discord happy to provide whatever other help you need.

**Comment by politrons** [comment]
Hi, do you have any documentation that I can read regarding ZIO#lock and ZIO#on ? otherwise where can I find a link to Discord 😅

**Comment by adamgfraser** [comment]
I don't think we have a section on it in the documentation (contributions always appreciated! 😃). Here is a [link](https://javadoc.io/static/dev.zio/zio_2.12/1.0.0-RC21/zio/ZIO.html#on(ec:scala.concurrent.ExecutionContext):zio.ZIO[R,E,A]) to the Scaladoc. The link to Discord is [here](https://discord.gg/2ccFBr4). Basically you give the effect an `ExecutionContext` and then it will be run on that.

**Comment by politrons** [comment]
I´m trying doing this

`ZIO.lock(ec)(ZIO.fromFuture(_ => service(request).asScalaFuture()))`

But the only way to obtain that ExecutionContext is implementing a trait which if I honest with you I dont feel comfirtable without know what I have to implement

```
  val ec = new Executor {
    override def yieldOpCount: Int = ???

    override def metrics: Option[ExecutionMetrics] = ???

    override def submit(runnable: Runnable): Boolean = ???

    override def here: Boolean = ???
  }
```

There's no Factory like Java does where I only have to specify the number of threads of my pool?

**Comment by adamgfraser** [comment]
Okay, so there are a couple of things here. First, the signature of `ZIO#fromFuture` is:

```scala
def fromFuture[A](make: ExecutionContext => scala.concurrent.Future[A]): Task[A] =
```

So ZIO is giving you an exception context to run your future on. So I think the way you want to write this is just:

```scala
ZIO.fromFuture { implicit ec =>
  service(request).asScalaFuture()
}
```

That will import a `Future` into a `ZIO` and make sure that the execution context the future runs on is controlled by ZIO (assuming that `service(request).asScalaFuture` takes an implicit `ExecutionContext`). The ZIO runtime is already optimized to provide an efficient executor so I think you probably don't need to do anything else. If you do want to customize an executor you can use `lock` or `on` and some of the combinators on them to customize the execution but you should generally not need to do that.

Does that help?

**Comment by politrons** [comment]
It helps a lot, as I explain bellow I found how to create the executionContext

```
  private val executorService = Executors.newFixedThreadPool(100)
  private val executor: Executor = Executor.fromExecutionContext(100)(ExecutionContext.fromExecutor(executorService))

```

my only remain question is what is `yieldOpCount0` that I passing to `fromExecutionContext`

Also regarding the default ExecutionContext of ZIO, how many threads is using?. The Scala global default is normally the number of cores of your machine, and in our benchmakrs we detect that configuration for our use case is not good enough.

Regards.

**Comment by adamgfraser** [comment]
Great! ZIO also uses the number of available cores by default so if you want more than that then you should definitely customize your `Executor`. The `yieldOpCount` is the maximum number of operations the ZIO runtime will execute on a fiber before yielding to other fibers. So it is a tradeoff between efficiency and fairness (lower numbers mean yielding more often which improves fairness but at some cost to efficiency). The default value is 2,048 operations.

The other thing to keep in mind as you are transitioning from `Future` is that with `Future` the `ExecutionContext` is often optimized for "mixed" workloads that include both non-blocking and potentially blocking work. In ZIO the model is for a very strong separate between blocking and non-blocking work, with all non-blocking work handled by the default Executor with a small number of underlying threads that are expected to always be working, and all blocking work done on a special blocking thread pool provided by the `Blocking` service. Not sure if that is relevant to you but just wanted to highlight that.

**Comment by politrons** [comment]
Well that last sentence just blow my mind 😂  what can be consider a block work?. I guess the transition from Future to Fiber is something so rudimental like on complete of the future make succeed or fail a promise that we use to create a Fiber before, but not blocking is happening there right?.

In any case if I set my own ZIO ExecutionContext with lock it means the resolution of the future it will happen first in his own ExecutionContext, and then we move the result into another ZIO fiber which it will use the ExecutionContext that I define right?.
Hard topic to explain here without a whiteboard 😅  thanks for all the support!

**Comment by adamgfraser** [comment]
So blocking work would be anything where the underlying thread is blocking waiting for something to happen. Like if you have a database call and the thread just sits there until the database has the result that would be blocking versus if you give the database a callback to invoke when it has a result that would be nonblocking. ZIO operates with a small number of underlying threads for efficiency and switches between them to execute a large number of fibers so if blocking work is being done on the main thread pool it can lead to deadlocks or poor performance. Note that all operations in ZIO, even the ones that seem like they require "semantically" blocking like waiting on a promise are actually implemented without blocking under the hood. So you really only need to worry about blocking if you are using third party party libraries or interacting with other systems that might block.

If you set your own execution context that will be used to both create and run the future. That is the reason that `fromFuture` gives you an execution context, so we can make sure the future is actually created with our execution context. This assumes the method you are using to construct the future accepts an execution context. If it has already been constructed with its own execution context then there is nothing we can do about it after the fact.

Definitely come over to Discord! There is a great group of folks over there who can help you as you are buildings things with ZIO.

**Comment by politrons** [comment]
Sure thing!, I will continue my benchmarks and I will let you guys know in Discord. Thanks a lot again for the master class 😉
