### ISSUE TITLE
Rename 'master' branch

### ISSUE THREAD

**Issue by simpadjo** [zio/zio#3868]
Masters considered harmful.

Let's rename it to e.g. "main"

**Comment by neko-kai** [comment]
I propose `develop` since all 7mind projects already used `develop`, so were unaffected by the `master` controversy 😛
Renaming to `develop` across the board will reduce my personal command-line typos when updating `izumi-reflect`

**Comment by iravid** [comment]
Slightly larger context: once 1.0 hits, it'd be nice to have topic branches so we can start work on an eventual binary incompatible 2.0 and still backport fixes and improvements to 1.0. Would we still need a main branch with that setup?

**Comment by mijicd** [comment]
I'm with @iravid here. We need to have a branching strategy to support post 1.0 work. That includes discussing which model works best for us, but also adjusting our CI, which is known to cause a trouble or two anyhow.

That said, I am strongly against renaming branches before 1.0 lands. Once we have that one, I'm open for all suggestions.

**Comment by simpadjo** [comment]
From a project that is aiming to overthrow the FP scene and breaks things (in a good way!) every minor release, I expect a bit more courage when thinking about potential problems with CI :smile:

**Comment by softinio** [comment]
I think what needs to be considered here timing of such change so as not to duplicate effort. From the last conversations I had with @jdegoes we are evaluating moving our ci (to GitHub Actions) which I am hoping to start work on later this summer from the current one so my preference would be to coincide this change with that change together with the strategies we agree on for 1.0 as already mentioned.

**Comment by jdegoes** [comment]
I think I concur with @iravid and @mijicd!
