### ISSUE TITLE
Layer composition seems to hang on some cases

### ISSUE THREAD

**Issue by toxicafunk** [zio/zio#3871]
There are at least 2 cases when composing layers block, one using `>>>` and another using `>+>`. For `>>>`:

```scala
object SimpleMetricsLayer extends App {

  type Metrics = Has[Metrics.Service]

  object Metrics {
    trait Service {
      def log(): Task[Unit]
    }

    val receiverHas: ZLayer[Has[String], Nothing, Metrics] =
      ZLayer.fromFunction[Has[String], Metrics.Service](
        text =>
          new Service {
            override def log(): Task[Unit] = Task(println(text))
          }
      )
  }

  val rLayerHas: ZLayer[Any, Nothing, Metrics] = ZLayer.succeed[String]("My cool text") >>> Metrics.receiverHas
  val combinedLayer: ZLayer[Any, Nothing, Metrics with Console] = rLayerHas ++ Console.live
  println(s"combined: $combinedLayer")
  val rtReceiverHas = Runtime.unsafeFromLayer(combinedLayer)

  println("defining Test program")
  val program =
    for {
      m <- RIO.environment[Metrics]
      _ <- m.get.log()
    } yield ()

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    program.exitCode.provideLayer(combinedLayer)
}
```

The above code *fails* when run as `App` or as a main 
```scala
def main(args: Array[String]): Unit =
    rtReceiverHas.unsafeRun(program)
```

but for some reason succeeds when run from zio-test `zio.test.test("unsafeFromLayer") { ... }`

The other case (`>+>`) was found by @ghostdogpr :
```scala
  object Test2 {
    val rts: zio.Runtime[Console with Clock] =
      zio.Runtime.unsafeFromLayer(Clock.live >+> Console.live, Platform.default)
  }
...
  zio.test.test("composeTest") {
    println(Test2.rts)
    assertCompletes
 }
```

It fails regardless of being run as `App` `main` or from a `test`.

**Comment by ghostdogpr** [comment]
Interesting: if I change `zipWithPar` to `zipWith` in `ZLayer#scope`:
```scala
case ZLayer.ZipWithPar(self, that, f) =>
        ZManaged.succeed(memoMap => memoMap.getOrElseMemoize(self).zipWith(memoMap.getOrElseMemoize(that))(f))
```
The problem disappears.

**Comment by ghostdogpr** [comment]
OK, after a thorough debugging session I found out we are running into a Scala bug: https://github.com/scala/bug/issues/7646
See also https://stackoverflow.com/questions/20157977/why-does-scala-hang-evaluating-a-by-name-parameter-in-a-future

Moving the by-name parameter (here, the layer) to another object solves the problem.

The only thing ZIO could do to prevent this issue would be to _not_ use by-name parameter in `>+>` and friends. @adamgfraser  do you think by-name is required there?

**Comment by adamgfraser** [comment]
@ghostdogpr Good find! And glad to know it is not related to the other issues we are seeing. It is somewhat useful to have that be lazy because the layer you call `fold` on is either going to be a success or a failure so we only even need to evaluate one and it lets us create layers like in `retry` that call themselves until success without recurring infinitely. There may be a way to do that without this, though I think there will still be some operators like `orElse` where we probably do need the laziness. Interesting that we haven't run into this with ZIO. Let me work on it.

**Comment by toxicafunk** [comment]
The scala bug found by @ghostdogpr seems related https://github.com/zio/zio/issues/1841
