### ISSUE TITLE
OOM using bufferSliding

### ISSUE THREAD

**Issue by jsfwa** [zio/zio#3882]
**ZIO version**: 1.0.0-RC21

Hi guys, simple reproducible OOM via `bufferSliding`:
```scala
 ZStream
      .repeat(Foo(1L))
      .bufferSliding(1)
      .runDrain
      .exitCode
```
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/7480075/85884081-b4192b00-b7ea-11ea-9f1e-fe7958d2a939.png">
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/7480075/85884219-f2164f00-b7ea-11ea-963d-a7d0499abc55.png">

**Comment by iravid** [comment]
Thank you for reporting (and minimizing!) @jsfwa. We'll look into this.

**Comment by jsfwa** [comment]
Just checked, the problem is in this recursive call https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L434
changed it to 
```
Take.fromPull(as).tap(take => queue.offer(take)).doWhile(_ != Take.end).unit
```
And looks like it solved the problem, but not sure about the correctness of this approach

**Comment by iravid** [comment]
@jsfwa Interesting. Would you like to open a PR with the fix and we can verify it there?

**Comment by narma** [comment]
Hey! I'm @jsfwa colleague, and he asked me to create PR because he away from the computer for a weekend.
