### ISSUE TITLE
Provide a more safe alternative to the Random service

### ISSUE THREAD

**Issue by shvimas** [zio/zio#3893]
At the moment `Random` service returns `UIO` for any operation even if some inputs may not result in a return value (e.g. `random.nextIntBetween`). Due to [this Discord conversation](https://discordapp.com/channels/629491597070827530/630498701860929559/726330286534688899) I see that when working with some static values it is more convenient to have such "untruthful" methods but in the case of working with, say, user-defined values it becomes a real problem since one needs to keep track of if input values were validated before consuming.
I propose to add an alternative service with the same methods as in `Random.Service` but return `IO` with some explicit error type where applicable, like `IO[InvalidBounds, Int]` for `nextIntBetween`.
Also I believe that the fact that method that returns UIO may actually fail a fiber is worth mentioning in the ScalaDoc (at least I could not find mention of it anywhere).

**Comment by shvimas** [comment]
I can implement this if maintainers agree on the overall idea.

**Comment by adamgfraser** [comment]
👍 on adding a note to the ScalaDoc.

Personally, I am 👎 on adding another service here. I think it adds significant complexity and cases like this where invalid input is provided by the user and can be known statically (essentially an `IllegalArgumentException`) are appropriately handled by the unchecked error channel (e.g. constructing a Semaphore with a negative number of permits).

**Comment by shvimas** [comment]
@adamgfraser TBH I do not follow: what error channel are you talking about? Since `random.nextIntBetween` returns `UIO` I have the only option to use `ZIO.catchSomeDefect` to recover from the potential bad input (assuming no explicit input validation). Did you mean this as an appropriate handling or am I missing something?

**Comment by adamgfraser** [comment]
@shvimas Yes, in ZIO we have the "checked" error channel with typed errors embodied by the `E` parameter and we have the "unchecked" error channel with errors that are a subtype of `Throwable` as part of the `Die` case of `Cause`. I think ideally you would validate the input before calling these methods if necessary or otherwise you could potentially do `catchSomeDefect`.

**Comment by shvimas** [comment]
I see. Thanks for the quick response!
