### ISSUE TITLE
Introduce foreachWhile

### ISSUE THREAD

**Issue by natansil** [zio/zio#3903]
It would be nice if ZIO could have a functionality of iterating over an `Iterable`, and executing effects but stopping if the effect returns false.

Something like

```scala
    def foreachWhile[R, E, A](as: Iterable[A])(f: A => ZIO[R, E, Boolean]): ZIO[R, E, Unit] =
      ZIO.effectTotal(as.iterator).flatMap { i =>
        def loop: ZIO[R, E, Unit] =
          if (i.hasNext) f(i.next).flatMap(result => if(result) loop else ZIO.unit)
          else ZIO.unit
        loop
      }
```

Mind you there is already `ZStream#foreachWhile`
and @iravid raised the following reservation in discord:

> Definitely does (have virtue - N.S.), but I think the number of variants of foreach is pretty high currently so this might impose quite a bit of maintenance overhead. Not sure what I think about that :man_shrugging_tone3:
> foreach, foreach_, foreachPar, foreachPar_, foreachParN_, ...
> Oh and there's validate and partition too.
> And all of these need to be replicated to all the ZIO companion objects.

So should I open a PR or not?

**Comment by natansil** [comment]
@iravid WDYT, should I open a PR or not?

**Comment by adamgfraser** [comment]
Going to close this as I think it is probably better addressed through streams or existing operators.
