### ISSUE TITLE
Tests unrelated to submitted code failing 

### ISSUE THREAD

**Issue by adrianfilip** [zio/zio#3908]
I noticed the build for my  pull request https://github.com/zio/zio/pull/3901 keeps failing for reasons unrelated to the PR code.

<img width="1260" alt="Screenshot 2020-06-29 at 00 08 45" src="https://user-images.githubusercontent.com/3481889/85958235-b622eb80-b99c-11ea-805f-d73bc3eaed2e.png">

<img width="1260" alt="Screenshot 2020-06-29 at 00 09 32" src="https://user-images.githubusercontent.com/3481889/85958248-d2268d00-b99c-11ea-8b6b-7df134d6fa1a.png">

<img width="1260" alt="Screenshot 2020-06-29 at 00 10 05" src="https://user-images.githubusercontent.com/3481889/85958253-e66a8a00-b99c-11ea-9d73-4832349d494d.png">

You can find more details here:
https://app.circleci.com/pipelines/github/zio/zio/8173/workflows/e1585ec5-e41b-495b-877f-baf34739c69f/jobs/82620/steps

https://app.circleci.com/pipelines/github/zio/zio/8173/workflows/e1585ec5-e41b-495b-877f-baf34739c69f/jobs/82625/steps

https://app.circleci.com/pipelines/github/zio/zio/8173/workflows/e1585ec5-e41b-495b-877f-baf34739c69f/jobs/82621/steps

**Comment by unclebob418** [comment]
Possibly related to #3851? Looks like it's been fixed but the failing tests are in the same areas so maybe not quite? Quite the coincidence if it's unrelated!

**Comment by unclebob418** [comment]
Cc @adamgfraser @ghostdogpr

**Comment by adamgfraser** [comment]
Going to close this as I think it is a little stale at this point. Let's open issues for any specific flaky tests we observe going forward.
