### ISSUE TITLE
RC21-1 The fiber's scope has ended before the fiber itself has ended

### ISSUE THREAD

**Issue by Fristi** [zio/zio#3910]
Since upgrading to RC21-1 we'll get:

```
java.lang.IllegalStateException: Defect: The fiber's scope has ended before the fiber itself has ended
```

Anyone else? We are using interop-cats, http4s, doobie.

Working on a reproduction case

**Comment by sebver** [comment]
This is a reproduction with http4s: https://github.com/sebver/zio-http4s-scope-issue

There are some instructions in the readme, you should see the error appear after a wile.

The requests don't actually fail - so I'm not sure what the consequences are.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.

**Comment by adamgfraser** [comment]
Looks like this issue also replicates on RC21. Can you confirm?

**Comment by sebver** [comment]
I just checked and I can confirm. We hadn't noticed since we upgraded straight to RC21-1 from RC20.

**Comment by adamgfraser** [comment]
Makes sense, it just helps narrow down the cause since it eliminates one potential change that was made in RC21-1 as a candidate.

**Comment by adamgfraser** [comment]
@Fristi @sebver We just merged #3910 which should fix this. If you have a chance and are able to test with snapshots could you let me know if this resolves your issue?

**Comment by sebver** [comment]
@adamgfraser I just let it run locally for a while and it appears to be fixed! 🙏

Just checking if there are any plans for an RC21-2 at some point? Don't mind verifying it in our test/production environments, but a snapshot is a bit of a hard sell there. 😄

**Comment by adamgfraser** [comment]
@sebver Totally makes sense! :smiley:

Yes, I think so, maybe after #3883 and #3919 get merged.

**Comment by Fristi** [comment]
Thank you so much!
