### ISSUE TITLE
[Zio-test] Navigation links for failed tests in Intellij Idea

### ISSUE THREAD

**Issue by fokot** [zio/zio#3911]
When I'm using `scalatest` in Intellij I get clickable lines for all failures. And I find it very handy. Not sure how hard it would be to do with zio-test but it would be cool

**Comment by adamgfraser** [comment]
This would be a great feature to add and is one we have talked about. I think to do this we need to capture the tracing information in ZIO Test for all test failures (right now we only capture it for runtime failures) and then we can report it ourselves with tools like ZIO Intellij provides a more advanced interface on top of this. I know @hmemcpy has spent some time thinking about this as well.

**Comment by hmemcpy** [comment]
I experimented a little with adding Li Haoyi's [Sourcecode](https://github.com/lihaoyi/sourcecode) macros with some success (see #3152). Unfortunately, I never progressed beyond the initial spike.

In general, source information for both failed and successful runs would be great - it would enable tooling support. I'm not entirely sure if it's possible to capture via just tracing information, though.

**Comment by adamgfraser** [comment]
Closed by #4242.
