### ISSUE TITLE
Introduce ZIO.foreach and ZIO.collect that takes BuildFrom/CanBuildFrom implicit

### ISSUE THREAD

**Issue by SimY4** [zio/zio#3942]
It can be useful for ZIO foreach/collect API to accept implicit CanBuildFrom/BuildFrom implicit.

It'll provide a way to collect elements into your own collection type. The biggest value I see in when you try to collect to Map. Or even just aggregate values into a single value (count, min, max).

**Comment by adamgfraser** [comment]
Yes I think this would be really helpful. Ideally by doing this we could also eliminate the different variants of these methods that currently exist (e.g. `ZIO#foreach` for `List`, `Chunk`, and `Option`).

**Comment by SimY4** [comment]
Ran a few experiments for this proposal:

- Add CanBuildFrom to existing foreach:

```
def foreach[R, E, From <: Iterable[A], A, B, To](in: From)(f: A => ZIO[R, E, B])(implicit bf: CanBuildFrom[From, B, To]): ZIO[R, E, To] = ???
```

Type inference doesn't help here. It works when such methods sit on the actual collection type where you can fix `From` at least. This definition here will always pick Iterable to Iterable build from unless you advise on all types.

- Add CanBuildFrom as a partially applied type argument

```
def foreach[To]: ForEach[To] = new ForEach[To]
...
class ForEach[To] {
  def apply[R, E, From <: Iterable[A], A, B](in: From)(f: A => ZIO[R, E, B])(implicit bf: CanBuildFrom[From, B, To]): ZIO[R, E, To] = ???
}

// example
ZIO.foreach[List[Int]](List(1, 2, 3))(ZIO.effectTotal(_))
```

But that will require to specify the fully resolved final type. If it's a map, it'll have to be a map with both arguments specified

- Add CanBuildFrom as a partially applied type argument with a hole

```
def foreach[To[_]]: ForEach[To] = new ForEach[To]
...
class ForEach[To[_]] {
  def apply[R, E, From <: Iterable[A], A, B](in: From)(f: A => ZIO[R, E, B])(implicit bf: CanBuildFrom[From, B, To[B]]): ZIO[R, E, To[B]] = ???
}

// example
ZIO.foreach[List](List(1, 2, 3))(ZIO.effectTotal(_))
```

The solution starts to look too complicated. For Map case, the user would need a type alias to fit a map in a singly holed API (or ZIO would have to have an overload for 0, 1, 2, etc. holes foreach).

And I still doubt that inference would work with any of these approaches.
