### ISSUE TITLE
Performance regression between 1.0.0-RC20 and 1.0.0-RC21-2

### ISSUE THREAD

**Issue by williammmeyer** [zio/zio#3949]
We've started to use zio + tapir + http4s in an internal project and noticed performance issues after upgrading to 1.0.0-RC21-2

The zio http4s example in the tapir repo demonstrates the same behavior we're seeing:

https://github.com/softwaremill/tapir/blob/3e3549644735256e22d756616a9187c109e0e7ec/examples/src/main/scala/sttp/tapir/examples/ZioExampleHttp4sServer.scala

v0.16.1 - 3075b5836f8be2575381113b180e937a65a7d249
```
sbt:tapir> examples/runMain sttp.tapir.examples.ZioExampleHttp4sServer
$ ab -n 1000 -c 25 http://127.0.0.1:8080/pet/35
...
Concurrency Level:      25
Time taken for tests:   4.140 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      164000 bytes
HTML transferred:       76000 bytes
Requests per second:    241.53 [#/sec] (mean)
```

vs.

Master - 3e3549644735256e22d756616a9187c109e0e7ec
```
sbt:tapir> examples/runMain sttp.tapir.examples.ZioExampleHttp4sServer
$ ab -n 1000 -c 25 http://127.0.0.1:8080/pet/35
ctrl-c after it's stalled
...
Concurrency Level:      25
Time taken for tests:   14.003 seconds
Complete requests:      94
Failed requests:        0
Total transferred:      15416 bytes
HTML transferred:       7144 bytes
Requests per second:    6.71 [#/sec] (mean)
```

The diff https://github.com/softwaremill/tapir/compare/v0.16.1...3e3549644735256e22d756616a9187c109e0e7ec is pretty small - typos and scala-steward version bumps.

```
-  val zio = "1.0.0-RC20"             
-  val zioInteropCats = "2.1.3.0-RC15"
+  val zio = "1.0.0-RC21-2"           
+  val zioInteropCats = "2.1.3.0-RC16"
```

**Comment by Fristi** [comment]
I think this is related to #3926

**Comment by williammmeyer** [comment]
Closing this issue - same as #3926
