### ISSUE TITLE
zio-macros: support polymorphic service

### ISSUE THREAD

**Issue by octavz** [zio/zio#3950]
Hi, it seems the macro doesn't accept polymorphic services

```scala
@accessible
object Module {
    trait Service[T <: X] {
        ....
      }
  }
```

should work

**Comment by octavz** [comment]
i also have the situation where I have more than one parameter ie.
```scala
@accessible
object Module {
    trait Service[S <: Y, T <: X] {
        ....
      }
  }
```
I don't know if is easy to do this for any number of parameters, but would be a nice to have feature.
They simply need to be forwarded as type params to the helper functions, together with their bounds.

**Comment by neko-kai** [comment]
It would also be great to support higher-kinded services e.g.

```scala
trait Service[F[_, _]] {
   def x: F[Throwable, Unit]
}
val service: Service[ZIO[Has[Service[IO]], ?, ?]]
```
