### ISSUE TITLE
zio-macros: support higher-kinded polymorphic services

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#3971]
follow up to https://github.com/zio/zio/issues/3950

It would be great if `@accessible` macro supported higher-kinded polymorphic services e.g.

```scala
@accessible
trait Service[F[_, _]] {
   def x: F[Throwable, Unit]
}

// generated object:
object service extends Service[ZIO[Has[Service[IO]], ?, ?]] {
  def x = ZIO.accessM[Service[IO]](_.x)
}
```

**Comment by Fristi** [comment]
Typically these tagless final algebras live in modules which don't have a zio dependency. Would be great if you could derive 'em like so

```scala
trait Service[F[_]] {
   def x: F[Unit]
}

// generated value:
val service = Derive.accessors[Service, Task] // first param (* -> *) -> *, second param effect type * -> *
```

**Comment by neko-kai** [comment]
@Fristi yep, there's another ticket for that - https://github.com/zio/zio/issues/3261
