### ISSUE TITLE
[zio-test] Control checkM behaviour via aspects

### ISSUE THREAD

**Issue by darl** [zio/zio#4007]
It will be very helpful if this things could be controlled via aspects:
1. Disabling or limiting shrinking. Current default is 1000 and it cannot be controlled. 
2. Running some effect before or after checkM's `test`. E.g. cleaning up db state.

**Comment by lemastero** [comment]
I am using zio-test and I ❤️  it. I would like to support it - by contributing.

**Comment by adamgfraser** [comment]
This would be great. There is a related issue in #2851. We already have `Sized` in the environment to allow configuring the size of generated values but would be great to expand this to something like `TestConfig` that includes additional parameters like number of times to run property based tests, whether to shrink, how many times to shrink, etc... Then those could also be modified using test aspects.

**Comment by lemastero** [comment]
Thank you @adamgfraser for letting me know. There is good chance problem 1 will be solved by #2851 I will wait for this.

Problem 2 could be explored.
Making a common setup for every test in a suite sounds like nice thing to have - set up DB before all tests, clean table contents after every test. Similar to: `beforeAll`, `afterAll`. `before`, `after` from ScalaTest JUnit.

Possibly

```scala
final def suite[R, E, T](
    label: String,
    specs: ZIO[R, E, Vector[Spec[R, E, T]]],
    exec: Option[ExecutionStrategy]
  )
```

could be extended by:

```scala
final def suite[R, E, T](
    label: String,
    specs: ZIO[R, E, Vector[Spec[R, E, T]]],
    actions: Vector[ZTestAction]
    exec: Option[ExecutionStrategy]
  )

ZTestAction = Before(...) | BeforeAll(...) | After(...) | AfterAll(...)
```
I will poke around in the code and propose something.

Not sure if that should happen before 1.0 - sounds like a change that could be not binary compatible.

**Comment by adamgfraser** [comment]
@lemastero For the before and after functionality take a look at the existing `before` and `after` test aspects. `provideLayer` with a layer that includes the before or after actions can also be used.

**Comment by darl** [comment]
@lemastero will you work on this?

**Comment by adamgfraser** [comment]
I can also work on this once 1.0 is released.
