### ISSUE TITLE
OOM with RC21-2 with cats-interop 2.1.3.0-RC15 after upgrading from RC20

### ISSUE THREAD

**Issue by Fristi** [zio/zio#4024]
We've been developing with a stack composed of zio, interop-cats, cats-effect, fs2 and fs2-kafka for a while. 

Recently we've tried upgrading to RC21, but our applications started to consume more memory and eventually crashed due to an OOM.

Me and @sebver worked on a reproduction case which can be found here: github.com/Fristi/zio-memory-issue/

The program runs fine for about 10 minutes and after that it crashes with an OOM, while RC20 seems to be working fine 

<img width="1680" alt="Screenshot 2020-07-30 at 12 03 46" src="https://user-images.githubusercontent.com/141265/88913527-64060c00-d261-11ea-94e4-16b50052bfe7.png">

I'll be off for holidays next week and @sebver will come back to follow up on this if needed!

**Comment by ghostdogpr** [comment]
So I did a few tests and found out the problem doesn't happen with RC21-2 and interop-cats RC16. It seems to be caused by interop-cats RC17, where the only related changed was https://github.com/zio/interop-cats/pull/205.

**Comment by Fristi** [comment]
Together been digging with @ghostdogpr to find out what the issue. The issue seems to be introduced since the change of `race`. 

 We are not sure what it is, but it seems the `LinkedMap[Id, A => Unit]` is growing in a specific case used in cats-effect `Deferred.get` as seen here https://github.com/typelevel/cats-effect/blob/2bb878fd3ca0255ec6d035280339f2238b8578b1/core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala#L201

The strange thing is that in most cases it is not growing while in other cases it is. My gut feeling says that it has to do with some combination of `ConcurrentEffect.race(Deffered.get, ...)` which appears to happen in multiple places

https://github.com/fd4s/fs2-kafka/blob/fcbb8b2011c40fc2e1fa4b86124e5f5d90548c8e/modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala#L418
https://github.com/fd4s/fs2-kafka/blob/fcbb8b2011c40fc2e1fa4b86124e5f5d90548c8e/modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala#L457
https://github.com/fd4s/fs2-kafka/blob/fcbb8b2011c40fc2e1fa4b86124e5f5d90548c8e/modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala#L460
https://github.com/fd4s/fs2-kafka/blob/fcbb8b2011c40fc2e1fa4b86124e5f5d90548c8e/modules/core/src/main/scala/fs2/kafka/KafkaConsumer.scala#L533

To be continued!

**Comment by ghostdogpr** [comment]
Found a fix and opened a PR: https://github.com/zio/interop-cats/pull/212
