### ISSUE TITLE
Add ZSink.take(Int)

### ISSUE THREAD

**Issue by mmuschalik** [zio/zio#4028]
Hi guys,

Is there a function on ZStream[R,E,O] such as:

`  def runTake(n: Int): ZIO[R,E,(Chunk[O], ZStream[R,E,O])] `

Not sure I got it all right, but looking for a function that will return an effect that can collect n items and return the remainder stream.
I can also think of a number of other functions that could operate similarly, such as using runTakeUntil, runfoldUntil etc.

For example I want to do:

```
for
  (xs,rem) <- stream.runTake(100)
  _            <-  rem.map(some_func(xs)).run(ZSink....)
  yield ()
```

**Comment by iravid** [comment]
Hi @mmuschalik, we have `ZStream#peel` for the times when you'd like to consume a prefix of the stream (and keep the rest inside the stream).

What we're missing is a sink that reads N elements; then you'd be able to do `stream.peel(ZSink.take(10))`. I'll change the title of the issue to reflect that.

Let me know if you'd like to try adding that sink!

**Comment by mmuschalik** [comment]
I had a look at the PR, which looks good to me at a glance. Boy you guys are quick, thanks heaps! So with this approach you use the sink to pull out items and to continue on pulling from the remainder stream, you effectively reuse the original stream, which will be positioned correctly. Is that how it should be used?
