### ISSUE TITLE
Version 1.0.0 requires Clock dependency for basic retry

### ISSUE THREAD

**Issue by manusgallagher** [zio/zio#4050]
Since updating from `1.0.0-RC21-2` to `1.0.0` my code is failing to compile due to a dependency requirement on `Clock` for a simple `recurs` retry.

This is the retry code here: `.retry(Schedule.recurs(5))`

Seems similar to https://github.com/zio/zio/issues/1494

**Comment by adamgfraser** [comment]
@manusgallagher For simple use cases like this you can you `ZIO#retryN`, `ZIO#retryUntil`, and `ZIO#retryWhile`. Schedule is designed for more complex use cases involving scheduling effects to occur at specified durations or points in time.

**Comment by manusgallagher** [comment]
@adamgfraser thanks. I can't find `ZIO#retryN`.

**Comment by adamgfraser** [comment]
@manusgallagher See [here](https://javadoc.io/doc/dev.zio/zio_2.12/latest/zio/ZIO.html#retryN(n:Int)(implicitev:zio.CanFail[E]):zio.ZIO[R,E,A]).

**Comment by manusgallagher** [comment]
@adamgfraser Thanks! Sorted now.
