### ISSUE TITLE
Queue not working form Scalaz to dev.ZIO

### ISSUE THREAD

**Issue by politrons** [zio/zio#4068]
Hi all, I recently migrate my project form Scalaz 0.19 to dev.ZIO 1.0 and all the migration has been smooth so far. The only issue that I found and my code stop working is the Queue system that I create with Scalaz Queue which now with ZIO queue I dont manage to make it work. Here the code base

I just create a simple example that I'm also unable to make it works

```

import zio.{Queue, Semaphore, Task, ZIO}

object ZIOQueue extends App {

  val main: zio.Runtime[zio.ZEnv] = zio.Runtime.default


  val queue: Queue[Task[Unit]] = main.unsafeRun {
    for {
      semaphore <- Semaphore.make(permits = 100)
      queue <- Queue.bounded[Task[Unit]](100)
      _ <- queue.take.flatMap(program => {
        for {
          _ <- semaphore.withPermit(program)
        } yield ()
      }
      ).forever.fork
    } yield queue
  }

  val program = Task.effect(println("hello world"))

  main.unsafeRun(queue.offer(program))


}
```

**UPDATE** I manage to make it work using `forkDeamon` instead `fork` someone can explain me the difference? 

Regards

**Comment by ghostdogpr** [comment]
Ah, you already found the solution, I was gonna suggest `forkDaemon` 😄

When you use regular `fork`, the fiber will be terminated when the parent is terminated (which happens immediately in your example). Using `forkDaemon` you make the fiber independent from its parent so it'll continue even when the parent completes.

**Comment by adamgfraser** [comment]
@politrons Did you get this working? Can we close this? Definitely feel free to reach out here or on Discord if you have any other issues migrating!

**Comment by politrons** [comment]
Sure sorry I forgot to close the issue.

Regards
