### ISSUE TITLE
Ref.set does not respect `when` conditions

### ISSUE THREAD

**Issue by jsfwa** [zio/zio#4081]
_zioVersion = 1.0.0_

Hello guys, simple issue:

```scala
val list = List.empty[Int]

for {
        r <- Ref.make(1)
        _ <- r.update(_ => list.last).when(list.nonEmpty) //Valid
        _ <- r.set(list.last).when(list.nonEmpty) //Throws no such element
} yield ()
```

**Comment by joprice** [comment]
Looks like `set`'s parameter is call by value https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZRef.scala#L77

You could use the `when` on the companion object of ZIO https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZIO.scala#L3751, but doesn't have the nice syntax.

**Comment by adamgfraser** [comment]
Yes. `Ref.set` expects an existing value, not an expression to compute a value that may be evaluated later and I don't think there is a way to change that which preserves binary compatibility.

**Comment by jsfwa** [comment]
Yeah, but it was just a tricky case for us to catch in more complex circumstance. Especially after `idea` suggested to use `when` in such way.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/7480075/90057529-2e453680-dce9-11ea-8651-e72b9d5bcdb6.png">
Anyway, if we are not allowed to change it to call-by-name, I think we can close this issue. Thanks everyone.

**Comment by ritschwumm** [comment]
since list.last is unsafe, i'd avoid it alltogether and refactor the abovr to sth like `list.lastOption.traverse(r.set)` anyway...

**Comment by adamgfraser** [comment]
@jsfwa No problem. Thanks for raising! Definitely something to think about.
