### ISSUE TITLE
`ZIO.foreach` can't be used for `Map[K, +V]`

### ISSUE THREAD

**Issue by taeguk** [zio/zio#4083]
`ZIO.foreach` was changed in #4037 below:
```scala
def foreach[R, E, A, B, Collection[+Element] <: Iterable[Element]](
  in: Collection[A]
)(f: A => ZIO[R, E, B])(implicit bf: BuildFrom[Collection[A], B, Collection[B]]): ZIO[R, E, Collection[B]]
```

But, it can't be used for `Map[K, +V]` because the number of type parameters is two.

**Comment by joroKr21** [comment]
You can upcast `map: Iterable[(K, V)]`

**Comment by adamgfraser** [comment]
Yes, I spent some time playing with this. Unfortunately I don't think we can further overload `foreach` but we could potentially add another variant for this, maybe `foreachMap`? I will work on this.

**Comment by joroKr21** [comment]
Would `foreachMap` expect you to return a tuple?

**Comment by adamgfraser** [comment]
Good question. I think conceptually we want a method that take a map and returns a map. I think there are potentially at least three ways to implement it:

1. Function from keys and values to new keys and new values. This is the most general. Some concern here that you could create new keys that collide. Also just requires you to return a tuple every time.
2. Function from keys and values to new values. This gives you access to both the old key and old value but just returns the new value, so you can't create key collisions, though you also can't update the keys.
3. Function from values to values. Simplest signature but least powerful.

I think my inclination is to do the first, basically treating this as a convenience to avoid upcasting to an `Iterable` and then back to `Map`, but feedback welcome.

**Comment by joroKr21** [comment]
I think that's reasonable since you can always forward the original key.
