### ISSUE TITLE
ZLayer.succeed() is not referentially transparent

### ISSUE THREAD

**Issue by Nekdo** [zio/zio#4085]
Replacing this code:
```
def layer = commonLayer ++ (commonLayer >>> depLayer)
```
by this code: 
```
def layer = {
  val c = commonLayer
  c ++ (c >>> depLayer)
}
```

Changes behaviour of a program.

It seems, that the deduplication of services constructed by `ZLayer`s is not done based on the `zio.Tag`s (as I would expect), but based on the instances of the ZLayer objects.

This was tested on `1.0.0`

**Comment by Nekdo** [comment]
Full test case here:
```
import ZLayerTests._
import zio._
import zio.test._
import zio.test.Assertion._

object ZLayerTests {
  def deduplicationTest = testM("test1") {
    class BaseService
    case class DepService(service: BaseService)

    def commonLayer = ZLayer.succeed(new BaseService)

    def depLayer = ZLayer.fromService(DepService(_))

    def layer = commonLayer ++ (commonLayer >>> depLayer)
//    The test passes if the calls to commonLayer are replaced by a reference to the same value (layer) like this:
//    def layer = {
//      val c = commonLayer
//      c ++ (c >>> depLayer)
//    }

    val test =
      ZIO.services[BaseService, DepService]
        .map { case (base, dep) =>
          assert(base)(equalTo(dep.service))
        }

    test.provideLayer(layer)
  }
}

object ZLayerSpec
  extends DefaultRunnableSpec
{
  def spec =
    suite("Playground")(
      deduplicationTest
    )
}
```

**Comment by adamgfraser** [comment]
Hi @Nekdo. This is actually an intentional design decision. See discussion [here](https://github.com/zio/zio/pull/2775#issuecomment-583364278).

We can't use the tags to determine whether two layers are the same because layers may produce values that don't have tags at all. In addition, you could have two different layers that return a type with the some tag (e.g. one layer produces a value of a type and another layer transforms that value, producing a different value of the same type).

We thought about adding some kind of identifier field but felt that the risk of unintentional collisions in large systems was too high.

Given this, we felt that the best solution was using object equality for the layers. This way, you never have collisions and in the worst case you have a program that is correct but inefficient because it creates the layer a second time unnecessarily. As you identified you can correct this by simply assigning your layer to a `val` or a `lazy val`.

**Comment by alexknvl** [comment]
@Nekdo It looks like your example doesn't show that the code is referentially non-transparent. You are comparing by *reference*, so by the same logic adding two `BigInt`s or doing `x :: xs` twice in a row is referentially non-transparent.

**Comment by Nekdo** [comment]
@adamgfraser Thanks for the link to the discussion. After more thinking, I see why the deduplication is done like this.

After more experimenting with this, it seems, that the deduplication is done in terms of the `==` method on the layers.
However, it is complicated to to tell, when two layers are equal and when not. 
E.g.:

    val managed = ZManaged.succeed(new BaseService)
    val managedService = managed.asService

    println(s"${ZLayer.fromManaged(managed) == ZLayer.fromManaged(managed)}") // false
    println(s"${ZLayer.fromManagedMany(managedService) == ZLayer.fromManagedMany(managedService)}") // true

Therefore I came to the conclusion, that when one wants to be sure two layers get de-duplicated, they should be the same (in terms of `eq()`). This can be easily achieved by always assigning a layer to `val` or `lazy val`.

**Comment by joroKr21** [comment]
@alexknvl with `val x` this prints once, with `def x` twice 👇 
```scala
 val x = ZLayer.fromEffect(putStrLn("Launch missiles"))
 val y = x ++ (x >>> ZLayer.succeed(42))
 y.build.use_(ZIO.unit)
```

**Comment by alexknvl** [comment]
👍 @joroKr21 that strikes me as very unsatisfactory.

**Comment by heaven-born** [comment]
I spent some time investigating it, and I found that the reason for such behaviour is memoization logic inside `ZLayer#MemoMap`. In that part of the code `ZLayer` objects are used as a key in a `Map[ZLayer, ...]`. For this map both occurrences of `x` are just the same layer. One more way to make this map see them as different layers is to use `fresh`.

```scala
val x = ZLayer.fromEffect(putStrLn("Launch missiles"))
val y = x ++ x.fresh
val r = y.build.use_(ZIO.unit)
```

**Comment by gugliermocollina** [comment]
Hello @adamgfraser,


> Hi @Nekdo. This is actually an intentional design decision. See discussion [here](https://github.com/zio/zio/pull/2775#issuecomment-583364278).

Looking at the discussion seems the decision was taken considering that "it will have no effect on behavior, only performance", I have a counter example (minimized from some prod code) here which is affecting behavior. Maybe you can consider reopening the Issue?

```scala
    val aLayer = layerBuilder(10)

    def layerBuilder(i: Int): ZLayer[Any, Throwable, Has[Int]] =
      Task{
        println(s"Launching missiles $i")
        i
      }.toLayer

    def runLayer(l: ZLayer[Any, Throwable, Has[Int]]): ZIO[Any, Throwable, Unit] =
      l.build.use { _ => ZIO.unit }

    val test1 = runLayer(aLayer ++ aLayer)

    val test2 = runLayer(layerBuilder(10) ++ layerBuilder(10))

``` 

test2 launches the missiles 2 times and test1 only once.

**Comment by adamgfraser** [comment]
@gugliermocollina The point of that discussion was not that there could never be occasions where there would be an observable difference but that this design decision made sense on balance. Memoization is a key feature for the efficient construction of layers. Not using reference equality would require users to manually define identifiers for each layer, which would both be unergonomic and require global knowledge to avoid creating duplicate identifiers.

I think that judgment has very much been borne out over the last two years. Layers have become a integral part of building ZIO applications and automatic sharing and memoization has been a major part of that. People have also had a variety of issues with layers we have addressed such as better error messages, fewer constructors, and automatic layer construction. But I don't think I have ever seen problems around this outside of a couple comments on this issue over the years.

**Comment by gugliermocollina** [comment]
I understand the need for ergonomics in this case. I believe however that not being referential transparent in this case deserve at least a big disclaimer in the documentation.
