### ISSUE TITLE
Unable to build project on Windows 

### ISSUE THREAD

**Issue by BananaPlantain** [zio/zio#4096]
I was able to determine the commit that introduces this issue

50be11e5abf592bb79129cf98d15895ac917c0e3

this issue is masked by another issue on this commit but can be unmasked by cherry-picking this commit

bb2ded5ffefb0bc3e7ef441e90d69c10e8882d49

Log of build errors from master.

[scratch_1.txt](https://github.com/zio/zio/files/5072743/scratch_1.txt)

**Comment by adamgfraser** [comment]
@BananaPlantain Thanks for the detailed analysis! Would you be interested in trying your hand at a fix?

**Comment by BananaPlantain** [comment]
I can look but build issues are not my strong suite.

**Comment by BananaPlantain** [comment]
This issue appears to be resolved

**Comment by adamgfraser** [comment]
@BananaPlantain Thanks for the update!
