### ISSUE TITLE
scheduleA || scheduleB completes unexpectedly when scheduleA is done

### ISSUE THREAD

**Issue by svroonland** [zio/zio#4101]
Given
```scala
scheduleA = Schedule.recurWhile[Boolean](_ == true)
scheduleB = Schedule.fixed(1.second)
schedule = scheduleA || scheduleB
```

In RC21-2 this would create a schedule that continued at intervals of 1 seconds whenever the input was `false`. But in ZIO 1.0 the schedule stops as soon as an input of `false` is seen. 

The definition of this behavior seems to be in `Schedule#combineWith` which translates the `Done` of either side to a `Done` of the combined Schedule. 

See also https://scastie.scala-lang.org/pV3odrT4TwqI7XQFYWnBgA 

For context, my use case here is AWS Kinesis polling, where a value in the response indicates whether more data is available to poll, in which case I want to repeat the poll action immediately, otherwise wait for a second.

**Comment by reibitto** [comment]
I also ran into what I believe is the same issue. I was relying on `||` to "return a new schedule that continues as long as either schedule continues" (prior to 1.0.0), but `||` doesn't seem to do that anymore if only one side decides to continue. I don't know if this was an intended change or not.
