### ISSUE TITLE
Stream broadcast doesn't seem to cope with termination of some downstream streams

### ISSUE THREAD

**Issue by jportway** [zio/zio#4108]
I have a stream that i broadcast to two streams. One of these subsequent streams maps over the entire incoming stream, the other one just takes the first element of the incoming stream, and then should (presumably) terminate.
The problem is that the "broadcast" can't cope with one of the downstream streams terminating while the other is still listening  it seems to still be buffering elements waiting for the terminated stream to accept them.

```
val rt = Runtime.default
val stream = Stream.fromIterable(1 to 5)
val split=stream.broadcast(2,1)
val blah = split.use{
  case fullStream :: headStream :: Nil =>
    for {
      x <- fullStream( a => s"[${a}]").runCollect
      y <- headStream => s"+${a}+").runHead
    } yield (x,y)
}

rt.unsafeRun(blah)
```

 The code above will stall - but if i change the broadcast parameters to broadcast(2,5) then it works - obviously this is an impractical solution for longer streams, but it makes me suspect that the broadcast is buffering elements and waiting to be drained by the terminated stream.

**Comment by jportway** [comment]
In the code about I used "runHead", but I've also tried using take (1) on the "headStream" with the same effect

**Comment by iravid** [comment]
@jportway Thanks for opening! The problem here is that you are consuming `fullStream` in its entirety before moving on to consume `headStream`. For `broadcast`, you must either consume the elements from all streams or shutdown one of the streams (which would cause the underlying queue buffering the elements for that particular stream to shutdown).

So this should work for you:

```scala
split.use {
  case fullStream :: headStream :: Nil =>
    fullStream.runCollect zipPar headStream.runHead
}
```

**Comment by jportway** [comment]
@iravid Thanks for the explanation. I think I understand now.

In case it helps with documentation or something - I think my confusion stemmed from not quite realising when I was declaring the stream structure, and when I was actually executing the stream. I think I was expecting the library to manage concurrency for me.
It seems to me that this must be a very common case with "broadcast" that the downstream streams would be run concurrently (I can't really think why you would ever want them to run sequentially). Perhaps there could be an alternative function that included the zipPar? Im thinking of something like :

```stream.broadcast(bufferSize)(streamA => ???) (streamB => ???)```

I haven't thought it through really, but it seems something like that should be feasible and might be more straightforward to use with less gotchas?

**Comment by jportway** [comment]
looking back - this was me be very embarassingly dumb. 
Apologies. 
And thanks for your patience.
