### ISSUE TITLE
`unsafeExecute` evaluates on the current thread pool

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#4117]
Currently, there is an undocumented behavior around `unsafeExecute` where typically when you call it inside your program it would always evaluate the given ZIO instance on the current thread unless an async boundary is reached.

```scala
object Main extends App {
  // Print the current thread name
  def threadName = UIO(println(Thread.currentThread.getName))

  // Yield to trigger async boundary and then print the current thread name
  def threadNameY = ZIO.yieldNow *> threadName

  // Test program that "tries" to run the provided ZIO in a thread
  def program(uio: UIO[Unit]) =
    ZIO.runtime[Any].flatMap { runtime =>
      UIO {
        new Thread("my-thread") {
          override def run = runtime.unsafeRunAsync_(uio)
        }.start()
      }
    }

  def run(args: List[String]) =
    (for {
      _ <- program(threadName)  // Prints "my-thread"
      _ <- program(threadNameY) // Prints zio-async-thread
    } yield ()).exitCode
}

```
In the above example using `threadName` actually prints "my-thread" when in fact it should have printed something that's prefixed with "zio-async-thread...". The computation moves only to the `zio-async-thread` when an async boundary is seen for the first time. Which is what is being synthetically inside `threadNameY`.

It seems like `.lock` doesn't help either —

```diff
   def program(uio: UIO[Unit]) =
    ZIO.runtime[Any].flatMap { runtime =>
       UIO {
         new Thread("my-thread") {
-         override def run = runtime.unsafeRunAsync_(uio)
+         override def run = runtime.unsafeRunAsync_(uio.lock(runtime.platform.executor))
         }.start()
       }
     }
```

This IMHO is a bit counter-intuitive and can potentially be missed, thus causing some thread designed for handling only events to choke by spending time in evaluating ZIO fibers.

**Comment by adamgfraser** [comment]
@tusharmath Thanks for reporting! Just submitted a PR for this.

**Comment by tusharmath** [comment]
Woah! I might have taken longer just to document the issue :D
