### ISSUE TITLE
Improve Scaladoc

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#413]
The Scaladoc for classes and traits inside ZIO can use improvement. In particular:

 - All methods should have Scaladoc.
 - All functions should include Scaladoc descriptions for all parameters.
 - Where useful, methods should have code examples to show users how to use the method.

This is a great issue for new contributors and folks wanting to learn how to use ZIO! Even if you don't know how to use ZIO, don't let that stop you. If you have any questions, post them here and me or another ZIO contributor can help you out.

Sign up for documenting one of the following classes:

 - [ ] **scalaz.zio.Ref**
 - [ ] **scalaz.zio.RefM**
 - [ ] **scalaz.zio.Queue**
 - [ ] **scalaz.zio.ExitResult**
 - [ ] **scalaz.zio.ExitResult.Cause**
 - [ ] **scalaz.zio.Clock**
 - [ ] **scalaz.zio.Async**
 - [ ] **scalaz.zio.IO**
 - [ ] **scalaz.zio.Fiber**
 - [ ] **scalaz.zio.FiberLocal**
 - [ ] **scalaz.zio.FiberFailure**
 - [ ] **scalaz.zio.KleisliIO**
 - [ ] **scalaz.zio.Managed**
 - [ ] **scalaz.zio.Promise**
 - [ ] **scalaz.zio.Schedule**
 - [ ] **scalaz.zio.Semaphore**
 - [ ] **scalaz.zio.ZIO**
 - [ ] **scalaz.zio.system**
 - [ ] **scalaz.zio.console**

If you grab one of these, please write the documentation that you would appreciate as a new user of the library. 😄

**Comment by hepin1989** [comment]
The scaladoc should descript the type parameter and parameters too, not just the behavior of the method.

**Comment by samuelsayag** [comment]
Hello,
I am really a beginner with this library but thought I could do some scaladoc to learn it. Is there somebody already doing it?
That is also my first time contributing to anything so please give first aid/advice/thing not to do if relevant.
 
By the way, if it is of any importance:
I cloned the project and add it for the console just to see the look but it could not be generated. 
And then after searching I saw there is an open issue: https://github.com/scala/bug/issues/8124
console being a package object the documentation will not be generated.

**Comment by ttymck** [comment]
Would we like to have the "superpolymorphic" types added to their respective `Data Types` pages? If so I can add notes on `ZSchedule` to `Schedule`.

**Comment by saeltz** [comment]
Hello,

I saw this ticket being open for a long time and a good first issue. I wanted to start out contributing with something easy, so I added some Scaladoc for Ref.

Please take a look if this looks fine:
https://github.com/zio/zio/compare/master...saeltz:master

If so, I may create the PR or continue with more Scaladoc to get to know ZIO better before jumping into any actual coding.

**Comment by jdegoes** [comment]
@saeltz Looks good! Thanks for the effort. Please do create the PR / continue with more.

**Comment by saeltz** [comment]
@jdegoes I finished Ref, RefM, Queue, Fiber.

I guess that ExitResult was renamed to Exit and Async to EffectAsync.

Does it make sense to add ScalaDoc to deprecated FiberLocal?

**Comment by adamgfraser** [comment]
@saeltz I think we are deleting everything deprecated prior to the release of 1.0 in September so I would skip `FiberLocal`.

**Comment by saeltz** [comment]
Created the PR: https://github.com/zio/zio/pull/1513
Please review.

**Comment by alexvanolst** [comment]
Would it be possible for a maintainer to update the list in the issue so it's a bit easier for new contributors to jump in. Currently the package names are not up to date and the completed scaladocs are not marked as done.

Current status as far as I can tell is:
- [x] zio.Ref
- [x] zio.RefM
- [ ] zio.Queue - _there are a couple more methods remaining after the PR from @saeltz_
- [ ] zio.Exit - _this has been renamed from `zio.ExitResult`_
- [ ] zio.Cause - _this has been renamed from `zio.ExitResult.Cause`_
- [ ] zio.Clock
- [ ] zio.Async
- [ ] zio.IO
- [x] zio.Fiber
- [ ] zio.FiberLocal
- [ ] zio.FiberFailure
- [ ] zio.KleisliIO - _not sure if this exists anymore_
- [ ] zio.Managed
- [ ] zio.Promise
- [ ] zio.Schedule
- [ ] zio.Semaphore
- [ ] zio.ZIO
- [ ] zio.system
- [ ] zio.console

**Comment by adamgfraser** [comment]
I think the Scaladoc can always be improved but it has been built out quite substantially and at this point this issue does not feel very actionable so am going to close for now. Anyone should feel free to open more specific issues with particular areas where they would like to see more documentation.
