### ISSUE TITLE
zipPar fiber failures not handled correctly

### ISSUE THREAD

**Issue by Adriani-Furtado** [zio/zio#4136]
When using `zipPar`, if one of the `ZIO` contains a fiber failure, said failure will be seen as an "unchecked error" even if the error has been handled.

```scala
val a = ZIO.succeed(1) zipPar ZIO.dieMessage("Error!") // zipPar with a fiber failure
val res = a.sandbox.catchAll(_ => UIO(1)) // Failure is handled however we get a log message stating
/*
Fiber failed.
An unchecked error was produced.
*/
```

[Reproduced issue](https://scastie.scala-lang.org/GAQgcoemTYqn3Sl3nCvlHQ)

**Comment by adamgfraser** [comment]
@Adriani-Furtado Thanks for reporting this! I have an open PR that should take care of it.
