### ISSUE TITLE
ZStream#repeat doesn't repeat a stream evenly. ZStream#schedule is probably broken either.

### ISSUE THREAD

**Issue by heaven-born** [zio/zio#4144]
This code is supposed to repeat the entire stream once per 10 sec, but in fact after 10 sec it repeats the stream unpredictable number of times/delays and only after that starts working as expected :

     ZStream.fromIterable(1 to 10)
            .repeat(Schedule.fixed(10.seconds))
            .foreachChunk(e => putStrLn(s"E $e"))

It seems that `ZStream#schedule(Schedule.fixed(10.seconds))` is working not very smoothly either. At the beginning of the stream It produces elements of the stream somehow strange, not evenly. Seems to be the same source of the issue as for `repeat`.

Tested with ZIO 1.0.1

**Comment by iravid** [comment]
The problem appears to be in `Schedule.fixed`. Until we have a fix, you can use `Schedule.spaced` instead @heaven-born. Let me know if that works for you.

**Comment by heaven-born** [comment]
@iravid `Schedule.spaced` works for me. Thank you.
