### ISSUE TITLE
LayerBuilder proposal

### ISSUE THREAD

**Issue by caeus** [zio/zio#4150]
I've been dealing with the new way of DI using Layer and it's somewhat verbose. Specially defining dependencies as a type (i.e `Has[Service1] with Has[Service2] with Has[Service3]...`)
Thinking about a way to reduce the boilerplate of that, I thought of this:

```scala
sealed trait LayerBuilder[R] {
  def and[A]: LayerBuilder[R with Has[A]]
  final def from[A]: LayerBuilder[R with Has[A]] = and[A]
  final def map[A: Tag](b: R => A): RLayer[R, Has[A]] =
    ZManaged.fromFunctionM { r: R =>
      ZIO.fromEither(Try(b(r)).toEither).toManaged_
    }.toLayer
  final def mapTotal[A: Tag](b: R => A): URLayer[R, Has[A]] =
    ZManaged.fromFunction(b).toLayer

  final def mapM[E, A: Tag](b: R => ZIO[Any, E, A]): ZLayer[R, E, Has[A]] =
    ZManaged.fromFunctionM { r: R =>
      b(r).toManaged_
    }.toLayer
  final def mapManaged[E, A: Tag](b: R => ZManaged[Any, E, A]): ZLayer[R, E, Has[A]] =
    ZManaged.fromFunctionM(b).toLayer
}
object ZLayer extends LayerBuilder[Any] {
    def and[R] = this.asInstanceOf[LayerBuilder[Has[R]]]
...
```

This construction allows me to describe dependencies of a service like this:

```scala
ZLayer.from[Service1].and[Service2].and[Service3].and[Service4].mapTotal{r =>
  Service5(r.get[Service1], r.get[Service2], r.get[Service3], r.get[Service4])
}
```
Just an idea. I'm using it on my projects, and it saves a lot of the boilerplate

**Comment by adamgfraser** [comment]
@caeus Isn't this just?

```scala
ZLayer.fromServices[Service1, Service2, Service3, Service4, Service5](Service5)
```

In fact, since the types of the dependencies of the service are known from the definition of `Service5`, here this can be written without the type annotations as:

```scala
ZLayer.fromServices(Service5(_, _, _, _))
```

**Comment by caeus** [comment]
How did I miss that?

**Comment by adamgfraser** [comment]
@notxcain You can do:

```scala
import zio._

object Service5 {
  trait Service5
  trait A1
  trait A2
  trait A3
  trait A4
  trait A5
  def apply(a1: A1, a2: A2, a3: A3, a4: A4, a5: A5): Service5 = ???
  def layer: ZLayer[Has[A1] with Has[A2] with Has[A3] with Has[A4] with Has[A5], Nothing, Service5] =
    ZLayer.fromServicesMany[A1, A2, A3, A4, A5, Service5](Service5(_, _, _, _, _))
}
```

The `fromServices` constructor automatically lifts the output value into a `Has`. If you don't want this you can use the `fromServiceMany` constructor as I have done here. Note that you need to specify the type parameters due to [this](https://github.com/scala/bug/issues/11898) compiler bug. As a workaround you can assign the result to an intermediate value.

```scala
def layer: ZLayer[Has[A1] with Has[A2] with Has[A3] with Has[A4] with Has[A5], Nothing, Service5] = {
  val layer = ZLayer.fromServicesMany(Service5(_, _, _, _, _))
  layer
}
```

**Comment by adamgfraser** [comment]
Going to close this as I believe it is addressed by existing `ZLayer` constructors.
