### ISSUE TITLE
Improve microsite

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#417]
# Documentation

- [x] Home — The "why"
- [x] Getting Started — Hello World
- [x] Overview — On-boards developers to the effect train
  - [x] Creating Effects
  - [x] Basic Operations
  - [x] Handling Errors
  - [x] Handling Resources
  - [x] Basic Concurrency
  - [x] Testing Effects
  - [x] Running Effects
  - [x] Background
- [ ] Data Types — Provides an introduction to every data type in ZIO
     - [ ] Concurrent
       - [ ] Promise
       - [ ] Queue
       - [ ] Ref
       - [ ] RefM
       - [ ] Semaphore
       - [x] STM
       - [x] TPromise
       - [x] TQueue
       - [x] TRef
       - [x] TSemaphore
   - [ ] Effects
     - [ ] IO
     - [ ] Task
     - [ ] TaskR
     - [ ] UIO
     - [ ] ZIO
   - [ ] Fibers
     - [ ] Cause
     - [ ] Exit
     - [ ] Fiber
     - [ ] FiberLocal
   - [ ] Miscellaneous
     - [ ] Chunk
     - [ ] Schedule
   - [ ] Resources
     - [ ] Managed
     - [ ] Reservation
   - [ ] Streams
     - [ ] Sink
     - [ ] Stream
 - [ ] Interop — Provides information on interop with the broader ecosystem
   - [ ] Cats
   - [ ] Cats Effect
   - [ ] Future
   - [ ] Java
   - [ ] Javascript
   - [ ] Monix
   - [ ] Scalaz 7.x
   - [ ] Scalaz 8
 - [ ] Use Cases — Provides information targeted at specific use cases for ZIO
   - [ ] Asynchronicity
   - [ ] Blocking IO
   - [ ] Concurrency
   - [ ] Error Management
   - [ ] Parallelism
   - [ ] Queuing
   - [ ] Retrying
   - [ ] Scheduling
   - [ ] Streaming
   - [ ] Thread Management
 - [ ] Advanced - In-depth, technical nitty-gritty for power users
   - [ ] Concurrency Model
   - [ ] Error Model
   - [ ] Interruption Model
   - [ ] Performance
   - [ ] Runtime System

**Comment by sidnt** [comment]
@jdegoes wouldn't it be better to setup a different repository for the microsite altogether? That'd be a nice way to pave way for a richer microsite in the longer term and have its development stay out of the way of core zio code. I'd love to take it up and write documentation / tutorials / sample programs.

**Comment by lemastero** [comment]
There will be hackaton. We would like to work on docs. Well unless someone is already taking care of that.

**Comment by NeQuissimus** [comment]
@lemastero Go for it!

**Comment by lahiguera** [comment]
I volunteer for the `Data Types` section, except for `Stream` since @lemastero is already working on that. However I first need to understand ZIO, so I'm might not be as quick as desired but it will be a constant progress.

My plan is to tackle each sub-section of `Data Types` one after the other, in different PRs, but not necessarily in the order that they appear in the "table of content" of phase two above.

What do yo think, people?

**Comment by NeQuissimus** [comment]
Honestly, writing docs is perfect for learning. Go for it, see what you can come up with an PR it. Even the smallest improvement to the docs is still an improvement!

**Comment by lemastero** [comment]
@lahiguera If you add some Streams stuff in docs I don't mind. I've prepared some examples, wanted to translate stuff from fs2 and monix tutorial. But the time ... and zio api changed in the meanwhile too :)

**Comment by Vilkina** [comment]
I'm working on "Effects" now.

**Comment by jdegoes** [comment]
Refreshed the above list of topics.

**Comment by ttymck** [comment]
I would be glad to work on `Use Cases > Scheduling`. I think transcribing some examples from [this  presentation](https://www.slideshare.net/jdegoes/zio-schedule-conquering-flakiness-recurrence-with-pure-functional-programming-119932802) would be a good start, and I can try to add some of my own use cases.

**Comment by LGLO** [comment]
I'm taking Promise

**Comment by kitlangton** [comment]
I think this is being addressed by @khajavi's work
