### ISSUE TITLE
Audit RTS

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#418]
A comprehensive audit of every line of RTS for correctness and performance. No sense doing this until 1.0 is closer to shipping (maybe mid January).

**Comment by RaasAhsan** [comment]
One thing that isn't very clear to me is how the `killed` field in `FiberContext` (https://github.com/scalaz/scalaz-zio/blob/master/core/jvm/src/main/scala/scalaz/zio/RTS.scala#L173) is properly made visible. It's declared non-volatile, but can be accessed from multiple threads (the thread running the fiber, and a thread running an interrupt on the fiber).

If its taking advantage of the full volatile guarantee (all writes to non-volatile variables are visible after a write to a volatile variable), its not very clear how that's being done.

**Comment by jdegoes** [comment]
@RaasAhsan It is intentionally not made visible. The worst thing that can happen is that the runtime system executes an interrupted `IO` for longer than it "should". If we benchmark and making it volatile doesn't effect performance, we could and should make that change.

**Comment by jdegoes** [comment]
Or actually, just use `interrupted`, which involves `AtomicReference.get`.

**Comment by adamgfraser** [comment]
Closing as this was in preparation for 1.0 release.
