### ISSUE TITLE
ZStream#groupByKey performance

### ISSUE THREAD

**Issue by svroonland** [zio/zio#4191]
I experienced that when using `ZStream#groupByKey`, stream throughput suffers a lot. I suspect it's because `distributedWithDynamic` breaks the chunk structure. 

It might be worth to have a dedicated implementation that tries to preserve chunks, like [so](https://github.com/svroonland/zio-kinesis/blob/128dd18ff10f8850a87b9d10d3e5ea269ba0883d/src/main/scala/nl/vroste/zio/kinesis/client/Util.scala#L55) or perhaps `distributedWithDynamic` can be improved.

**Comment by iravid** [comment]
Yeah agreed. Would be a welcome improvement to preserve chunks in some way in `distributedWithDynamic`.

**Comment by mschuwalow** [comment]
I'll take a look at this one

**Comment by mschuwalow** [comment]
Hmm, this one is interesting.

For a stream of 10000 chunks of size 500 groupBy is about 6 times _slower_ after the change.
Do we have a canonical stream / chunksize we are optimizing for?

**Comment by mschuwalow** [comment]
Let's wait for the new streams if that's fine with you

**Comment by miroslavmachura** [comment]
Hello everyone, just want to ask if there's some plan for fixing this?

We just hit this throughput issue in production and had to get rid of all `ZStream.groupBy` usages, as it made the grouping approximately 16 times slower than our previous implementation.

Anyway using ZStream.groupBy was more convenient, would be great if it was fixed and we could get back to using it.

**Comment by adamgfraser** [comment]
Will take a look at this.

**Comment by miroslavmachura** [comment]
I see the fix was merged into `zio:series/2.x` branch. Is the fix going to be also applied zio1?
