### ISSUE TITLE
ZIO.foreachParN when using Array does not compile due to invariance

### ISSUE THREAD

**Issue by aappddeevv** [zio/zio#4198]
Collections with invariant elements (like Array) need to have type ascription to use them:

```scala
ZIO.foreachParN(10)(Array(1,2,3):Iterable[Int])(i => UIO(println(i))) 
res2: ZIO[Any, Nothing, Iterable[Unit]] = <function1>
```

This means you have to add type info back in later to call other methods e.g. length. The issue is that there should be consideration for an invariant version of the methods, like for Set.

This is per a discord conversation with adamfraser.

**Comment by adamgfraser** [comment]
This is the same issue we had with `Set`. Agree it makes sense to add something here. It may be worth seeing if we can abstract over invariant types, though not sure we will be able to do it in a binary compatible way or really how many types there are like that other than `Set` and `Array`. I will add.

**Comment by adamgfraser** [comment]
This can definitely be implemented but wondering if this makes sense given that `Array` is a mutable data structure. Should we be pushing uses of this to `Chunk`?

**Comment by aappddeevv** [comment]
The issue is to avoid the conversion of Array (in my case js.Array).

What is your thought around how mutability of the collection arg affects things?

**Comment by adamgfraser** [comment]
It just means we can't necessarily reason about things in the same way, for example what happens if one of the collection elements is mutated while we are in the process of working with it?

**Comment by aappddeevv** [comment]
I think it’s ok though. It seems like the real issue is that it’s a variance api thing. Arrays have that issue all over the jvm and js surface area.

**Comment by adamgfraser** [comment]
I tend to think that is right. I just submitted a pull request to add this.
