### ISSUE TITLE
Memory Leak in clock.delay

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#4208]
The below program leaks memory via `java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask`

```scala
import zio._
import zio.stream._
import zio.duration._

import scala.language.postfixOps

object ZIOHeapLeak extends App {

  def run(args: List[String]): zio.URIO[zio.ZEnv, ExitCode] =
    (for {
      _ <- console.putStrLn("Take a heap dump and press enter:")
      f <- clock.sleep(Int.MaxValue seconds).fork
      _ <- console.getStrLn // Take a heap dump
      _ <- f.interrupt
    } yield ()).repeatN(10).exitCode
}
```

**Screenshot**

<img width="1284" alt="Screenshot 2020-09-17 at 1 02 57 AM" src="https://user-images.githubusercontent.com/194482/93383627-88559080-f881-11ea-900f-67d8ebe2f1e2.png">

**Comment by adamgfraser** [comment]
@tusharmath Thanks for reporting! Just opened a pull request that will fix this.

**Comment by tusharmath** [comment]
thankyou!

**Comment by tusharmath** [comment]
Just verified, the issue has been fixed!

**Comment by adamgfraser** [comment]
Awesome!
