### ISSUE TITLE
Test: Implement LawfulF and LawsF for Divariant

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio#4211]
So far, there are `LawfulF` and `LawsF` for `Covariant`, `Contravariant` and `Invariant`.
The implementation for "Divariant" is missing. It would look like
```scala
package object laws {
  object LawfulF {
    type Divariant[-CapsF[_[-_, +_]], -Caps[_]] = ZLawfulF.Divariant[CapsF, Caps, Any]
  }
  object LawsF {
    type Divariant[-CapsF[_[-_, +_]], -Caps[_]] = ZLawsF.Divariant[CapsF, Caps, Any]
```

**Comment by lemastero** [comment]
🏃‍♂️ On my way!

**Comment by lemastero** [comment]
My work in progress is in https://github.com/zio/zio/compare/master...lemastero:fix-4211-WIP?expand=1
Still fighting with compilation errors :)

**Comment by adamgfraser** [comment]
@lemastero Awesome! Let me know if you want me to take a look at the compilation errors.

**Comment by lemastero** [comment]
I have [WIP version](https://github.com/zio/zio/compare/master...lemastero:fix-4211-WIP?expand=1).
* I need to think about the shape of laws in `ZLawsF2`. Finishing https://github.com/zio/zio-prelude/pull/293 would be helpful - to understand what shape we need for functions testing laws.
* Tests for PR are in progress. One of the issues with that is mentioned: https://github.com/zio/zio-prelude/issues/92
