### ISSUE TITLE
Replace ZIO#repeat(Schedule) with ZIO#schedule(Schedule)

### ISSUE THREAD

**Issue by heaven-born** [zio/zio#4218]
Current implementation of `ZIO#repeat(Schedule)` combines both scheduling and repeating concepts which leads to behaviour that is not easy to predict from method signature and also hard to customise. 

Here is an example: let's say I have `Schedule` that recur on Mondays. Assume that today is `Monday` and I want my effect to repeat starting from today. Now I can do `putString("Hello Monday").repeat(mondaySchedule)` and expect it to repeat one time today . But this will immediately print `Hello Monday` two times - first time initiated by `repeat`-specific logic and the second time by `mondaySchedule` because today is Monday, which is not what I would expect from this method. Even if today wasn't Monday it would still print `Hello Monday` one time, which is also pretty unexpected.

Another example of this confusion is issue #3850. Having `schedule` method instead of `repeat` in that case would have prevented problem of the extra delay by combining two schedules: 

```scala
putString("foo").schedule(Schedule.once ++ Schedule.spaced(100.millis))
```

New `schedule` method must not emit original effect outside flow managed by `Schedule` delays.

**Comment by jdegoes** [comment]
I agree we need something like this.
