### ISSUE TITLE
Gen.usASCII returns "Chunk("…

### ISSUE THREAD

**Issue by fsvehla** [zio/zio#4227]
`Gen.usASCII` generates values like `"Chunk(\b…`
Looks to me that it calls `Chunk#toString`

```scala
val usASCII: Gen[Random with Sized, String] =
  chunkOf(anyASCIIString).map(chunk => chunk.toString)
```

It’s not clear to me what it’s purpose is since `Gen.anyASCIIString` exists, which is _“A generator US-ASCII strings. Shrinks towards the empty string.”_

**Comment by adamgfraser** [comment]
Yes. Looks like this was added to facilitate one test involving the transducer for this but I agree it is confusing. Will remove.
