### ISSUE TITLE
ZStream.zip() can consume extra elements

### ISSUE THREAD

**Issue by fillson-shady** [zio/zio#4229]
Hello!

I've met some strange behaviour of `ZStream.zip()` - it can consume more then necessary elements from zipped stream.

```scala
import zio._
import zio.console._
import zio.duration._
import zio.stream._

object Test extends App {
  def run(args: List[String]): URIO[ZEnv, ExitCode] =
    (for {
      queue <- Queue.unbounded[Unit]
      _     <- queue.offerAll(List.fill(10)())
      _     <- queue.size.flatMap(queueSize => putStrLn(s"queue size: $queueSize")).repeat(Schedule.spaced(1.second)).fork
      _ <- ZStream(1)
        .zip(ZStream.fromQueue(queue))
        .runDrain
    } yield ExitCode.success)
}
```

This code produces following output:
```
queue size: 10
queue size: -1
```

So, for consuming single element from source `ZStream(1)` `zip()` consumes all 10 elements from the `queue`.
Is it a bug or an expected behaviour?

Thank you!

**Comment by iravid** [comment]
Yes, this is expected, but unrelated to `zip`; `ZStream.fromQueue` eagerly dequeues multiple elements to create chunks.

There's a pending PR that introduces a parameter that controls this behavior.
