### ISSUE TITLE
Mocks only work for single fiber programs

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio#4255]
Observed:
* When a fiber uses a mock defined in another fiber, while there is a missing expectations, the test hangs and no error message is printed.
* When several fibers are using a mock (e.g. using `foreachPar`) with multiple expectations (combined with `&&` because order can not be guaranteed from multiple fibers), the test never passes. Reducing parallelism to 1 (using `foreachParN`) the test does pass.

Expected:
* Which fiber using the mock does not matter. Missing expectation should always be visible.
* Expectations combined with `&&` should be usable even when called from multiple fibers concurrently.

Is this a known limitation? Are there plans to solve this?

**Comment by adamgfraser** [comment]
Copying @ioleo.

**Comment by vpavkin** [comment]
Can confirm, have the same issue with `foreachPar` not hitting all the expectations, while `foreach` works fine.

**Comment by serrufSe** [comment]
Have the same problem, when parallelism exceeds 1
```
package pack

import pack.SomeService.SomeService
import zio._
import zio.test.Assertion._
import zio.test._
import zio.test.mock.Mock

case class SomeClass(param1: Int, param2: String)

object SomeService {

  type SomeService = Has[Service]

  trait Service {
    def someEffect(param: SomeClass): Task[Unit]
  }

  def someEffect(param: SomeClass): ZIO[SomeService, Throwable, Unit] =
    ZIO.accessM[SomeService](_.get.someEffect(param))
}

object Programm {
  val parallelism = 2

  val app = {
    val args = List(
      SomeClass(1, "one"),
      SomeClass(2, "two")
    )
    ZIO.foreachParN(parallelism)(args)(arg => SomeService.someEffect(arg))
  }
}

object SomeServiceMock extends Mock[SomeService] {

  object SomeEffect extends Effect[SomeClass, Nothing, Unit]

  val compose: URLayer[Has[mock.Proxy], SomeService] = ZLayer.fromService { proxy =>
    new SomeService.Service {
      override def someEffect(param: SomeClass): Task[Unit] = proxy(SomeEffect, param)
    }
  }
}

object MockParallelSuite extends DefaultRunnableSpec {
  override def spec: ZSpec[_root_.zio.test.environment.TestEnvironment, Any] = suite("test")(
    testM("test") {
      val mock = SomeServiceMock.SomeEffect(equalTo(SomeClass(1, "one"))) and SomeServiceMock.SomeEffect(
        equalTo(SomeClass(2, "two"))
      )
      val app = Programm.app.as(assertCompletes)
      app.provideLayer(mock)
    }
  )
}

```

**Comment by senia-psm** [comment]
`foreachPar` should be fixed here: #4539

**Comment by adamgfraser** [comment]
@senia-psm Can we close this issue now or other there other aspects to this that aren't resolved by your PR?

**Comment by senia-psm** [comment]
@adamgfraser I don't know how to reproduce the first part ("test hangs and no error message is printed"). And I believe my PR can't fix such issue.

**Comment by erikvanoosten** [comment]
I can probably reproduce the problem. How can I get updated jars?

**Comment by senia-psm** [comment]
@erikvanoosten you can try something like this:
```
resolvers += Resolver.sonatypeRepo("snapshots")
libraryDependencies += "dev.zio" %% "zio" % "1.0.3+118-51b5bbe0-SNAPSHOT" // use latest snapshot version
```

**Comment by erikvanoosten** [comment]
Progress! My tests no longer hang.

However, there is a new problem. The test where a lot of stuff happens in parallel reports `unsatisfied expectations in any order`. The list of unsatisfied expectations changes every run! Also, simple logging confirms that the mocks are in fact invoked with the correct parameters (which is what you'd expect because with `foreachParN(1)` instead of `foreachPar` everything works fine).

Therefore, my hypothesis is that there is a race condition while recording the mock invocations.

**Comment by senia-psm** [comment]
@erikvanoosten could you please create a minimal reproducer? Something like this: https://github.com/senia-psm/zio-test-issue-4472 or this: https://github.com/senia-psm/zio/blob/90c5d1ed24c5b8bb0c1c93f07a41d55d4e032756/test-tests/shared/src/test/scala/zio/test/mock/ParallelMockSpec.scala

**Comment by erikvanoosten** [comment]
It took some time, but here is a failing (parallel) and succeeding test (sequential): https://github.com/erikvanoosten/zio-test-issue-4255

**Comment by senia-psm** [comment]
@erikvanoosten it seems like version `1.0.3+118-51b5bbe0-SNAPSHOT` is too old. I published `zio` locally (with `sbt +publishLocal`) and tested you code with local version - both tests are green.

**Comment by erikvanoosten** [comment]
That is very good news! Let's close this issue then.
