### ISSUE TITLE
Flaky ZStream Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4278]
```
[info] - ZStream JVM
[info]   - Constructors
[info]     - fromOutputStreamWriter
[info]       - is not affected by closing the output stream
[info] Timeout of 1 m exceeded.
```

https://app.circleci.com/pipelines/github/zio/zio/9149/workflows/2a360637-ff15-48ee-929e-f516f3808140/jobs/93193

**Comment by robmwalsh** [comment]
duplicate of #4264

**Comment by adamgfraser** [comment]
@robmwalsh Thank you! 🙏

**Comment by robmwalsh** [comment]
@adamgfraser no problems - you may wish to add the labels to the other issue (I don't have permission)

**Comment by adamgfraser** [comment]
@robmwalsh Done!
