### ISSUE TITLE
[zio-test-magnolia] Missing DeriveGen[Instant]

### ISSUE THREAD

**Issue by Edvin-san** [zio/zio#4319]
Hello, I'm trying out zio-test-magnolia and got some compile errors for the following code:

```scala
case class InstantWrapper(
  date: Instant
)
val myGen: Gen[Random with Sized, InstantWrapper] = DeriveGen[InstantWrapper]
// could not find implicit value for parameter ev: zio.test.magnolia.DeriveGen[InstantWrapper]
```

I looked around and found out how to fix it:
```scala
implicit val genInstant: DeriveGen[Instant] = DeriveGen.instance(Gen.anyInstant)
case class InstantWrapper(
  date: Instant
)
val myGen: Gen[Random with Sized, InstantWrapper] = DeriveGen[InstantWrapper]
// Compiles!
```

Implicit instances of `DeriveGen` are already provided for `LocalDateTime` and `LocalDate`. Is there a reason that there is no instance provided for `Instant`? Should it be added?

**Comment by aartigao** [comment]
I think it's reasonable to add Instant given that other `Gen` like the ones that you mention are already provided. I can create a PR for that 👍🏽
