### ISSUE TITLE
Fiber Prioritization

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#4327]
## Requirement
I want to be able to specify that certain blocks to be executed on a higher priority than others.

## Problem
I have a web-socket based server that does two things 
1. Accept HTTP requests and upgrade them to a web-socket one.
2. Publish messages on the already established web-socket connections.

The issue is that broadcasting messages can take up a bit too much of CPU time and all my zio threads are busy working on it. 
This affects the latency of the HTTP requests and results in a connection timeout failure.

## Proposed Approach

Create a separate operation `setPriority` to set the priority for a set of instructions

```scala

// Two computationally expensive programs
val program1: UIO[Unit] = ???
val program2: UIO[Unit] = ???

val high   = setPriority(1)(program1)
val medium = setPriority(10)(program2)
val result = high <&> medium

```

**Comment by adamgfraser** [comment]
@tusharmath Why don't you create a separate `Executor` for the two types of tasks and then `lock` effects to the appropriate `Executor`?

**Comment by jdegoes** [comment]
@adamgfraser That's a good idea, in fact, it could be implemented in user code as something like:

```scala
priority(1)(zio)
```

Which would go and create a pool with that priority if it didn't already exist.

Good idea for a user library, although I'd suggest it's too niche a case to include in ZIO.
