### ISSUE TITLE
Ignored tests not visible in report

### ISSUE THREAD

**Issue by francisdb** [zio/zio#4347]
With other test frameworks ignored tests are still shown in the report and marked in yellow

eg:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/161305/96849408-db5ccd80-1455-11eb-96b6-c8fbd14ed847.png">

For zio test you only see that tests were ignored in the summary line which is less likely to get attention

`Ran 2 tests in 926 ms: 1 succeeded, 1 ignored, 0 failed`

zio-test `1.0.3`
sbt `1.4.1`

**Comment by lmserrano** [comment]
I'll look into this.

**Comment by hmemcpy** [comment]
Yes! This will be a great addition, so I can render ignored tests in the IntelliJ test runner as well! 🙏
