### ISSUE TITLE
new operator toSet on STM#TSet

### ISSUE THREAD

**Issue by phderome** [zio/zio#4376]
I am finding myself artificially working with lists when I am starting off with a set For example I need a `retryUntil(_.nonEmpty)` starting off from a `TSet` and I must convert using `tset.toList.retryUntil(_.nonEmpty)`

**Comment by adamgfraser** [comment]
@phderome Doesn't this already exist? See [here](https://github.com/zio/zio/blob/ccc3f2fe375e0cffff79ce63205bf989e036e537/core/shared/src/main/scala/zio/stm/TSet.scala#L105).

**Comment by phderome** [comment]
sorry, I must have used an older version and maybe it was not published to Maven repo. I'll check that. Non issue then.
