### ISSUE TITLE
Add ZStream.execute

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#4388]
Something like this:

```scala
object ZStream {
  def execute[R, E, A](zio: ZIO[R, E, A]): ZStream[R, E, Nothing] = ZStream.fromEffect(zio).drain
}
```

**Comment by meckesl** [comment]
Hi, I'd like to take a first issue, is it available ?

**Comment by adamgfraser** [comment]
@meckesl Go for it!

**Comment by meckesl** [comment]
I am struggling to run sbt build and tests with decent performance. Any recommendation for the dev environment - like Java version, memory settings, and the computer specs ? Regards,

**Comment by adamgfraser** [comment]
@meckesl Try navigating to a specific project, like within `sbt` to `project streamsJVM` or `project streamsTestsJVM`.

**Comment by meckesl** [comment]
@adamgfraser thanks, that helps !

**Comment by DomWos** [comment]
@meckesl are You working on that ?

**Comment by jeroenr** [comment]
I think this one can be closed now since it's added by https://github.com/zio/zio/pull/6091
