### ISSUE TITLE
1.0.3 regression: "Defect in zio.Has" exceptions due to izumi-reflect 1.0.0-M9 dependency

### ISSUE THREAD

**Issue by nktpro** [zio/zio#4391]
This issue has been filed in the right place https://github.com/zio/izumi-reflect/issues/98 but I'd like to also link it here to:

- Help anyone else who also runs into this exception and comes here first to search for it
- Remind us to upgrade `izumi-reflect` dependency in the next release once the issue is resolved

It's a rather tough one to narrow down for non-contributors, and it has quite a large impact since any custom `Service[T]` traits with non-primitive `T` would hit this issue

**Comment by virusdave** [comment]
Any word on this?  It's pretty debilitating.  :(

**Comment by neko-kai** [comment]
@virusdave If you could make a standalone reproduction of the issue that does not resolve after setting `optimized.equals=false` system property, that would help a lot! I was not aware there was another case unrelated to equals

**Comment by virusdave** [comment]
> @virusdave If you could make a standalone reproduction of the issue that does not resolve after setting `optimized.equals=false` system property, that would help a lot! I was not aware there was another case unrelated to equals

Copied from: https://discord.com/channels/629491597070827530/629491597070827534/801357923611574292

----

https://github.com/virusdave/maxinebot/tree/scratch/zio-has-defect
(Note the branch name - it's not on `main`)

`./bazel run //experimental:slack` will demonstrate this (need to either have Bazel 3+ or Nix installed)

```
java.lang.Error: Defect in zio.Has: Could not find SttpBackend[=λ %1:0 → ZIO[-Any,+Throwable,+1:0],-Nothing,-λ %1:0 → WebSocketHandler[=1:0]] inside Map(AccessToken -> AccessToken(),
SttpBackend[=λ %1:0 → ZIO[-Any,+Throwable,+1:0],-ZStream[-Any,+Throwable,+Byte],-λ %1:0 → WebSocketHandler[=1:0]] -> sttp.client.FollowRedirectsBackend@7be6c8a,
```


Hmm, looks like maybe i hit this: zio/zio#4391
Not sure how to work around it. Setting the system property doesn't seem to have helped.

indeed, this looks more like a problem with the macro than with the equals implementation.

My conclusion that it was macro-related was by duplicating the SlackClient's Service definition locally (but using the actual underlying SttpClient.Service rather than the type alias), at which point it works correctly.

This works:
```
/** Local impl because of seeming macro bug in LightTypeTag macro impl */
object LocalSlackClient {
  def live: ZLayer[Has[SttpClient.Service], Nothing, SlackClient] =
    ZLayer.fromFunction[Has[SttpClient.Service], SlackClient.Service](
      client =>
        new SlackClient.Service {
          override def send[T, E](request: Request[Either[ResponseError[E], T], Nothing]): ZIO[Any, Throwable, T] =
            for {
              result <- client.get[SttpClient.Service].send(request)
              json   <- ZIO.fromEither(result.body)
            } yield json
        }
    )
}

// snip

  private val slackLayer = {
    ((ZIO.access[AppConfig](_.get.accessToken) >>= AccessToken.make).toLayer ++
      AsyncHttpClientZioBackend.layer() ++
      ZLayer.requires[AppConfig]
      ) >+> (
      LocalSlackClient.live ++
        NewSlackRealtimeClient.live
      )
```

**Comment by neko-kai** [comment]
@virusdave Yeah, I've seen your messages, I'll hopefully look at it some time soon, but if you can minimize the case even further, such that it does not require bazel/nix, that would speed things up a lot, and I'll be able to include your case as a regression test as well.

**Comment by virusdave** [comment]
> @virusdave If you could make a standalone reproduction of the issue that does not resolve after setting `optimized.equals=false` system property, that would help a lot! I was not aware there was another case unrelated to equals

One can set this here:
https://github.com/virusdave/maxinebot/blob/scratch/zio-has-defect/experimental/BUILD.bazel#L50-L51

by adding
```
jvm_flags = [
  "-Dblah.blah.optimized.equals=false"
],
```

**Comment by virusdave** [comment]
> @virusdave Yeah, I've seen your messages, I'll hopefully look at it some time soon, but if you can minimize the case even further, such that it does not require bazel/nix, that would speed things up a lot, and I'll be able to include your case as a regression test as well.

I'll see what I can do when I have time - _might_ be able to do this over the weekend.
