### ISSUE TITLE
Release for Scala 3.0.0-M1

### ISSUE THREAD

**Issue by adamw** [zio/zio#4397]

**Comment by aappddeevv** [comment]
with scala.js

**Comment by aappddeevv** [comment]
Thanks @Lvitaly. When I started drilling down I became concerned that there were specific dotty issues still outstanding for reflect but I'm hoping I was wrong and your issue covers the entire punchlist.

**Comment by sideeffffect** [comment]
This can be closed because of https://github.com/zio/zio/pull/4425

**Comment by sideeffffect** [comment]
Can we expect 1.0.4 (i.e. supporting Scala 3.0.0-M1) anytime soon?
