### ISSUE TITLE
ZIO project build failing - "qa.hedgehog\hedgehog-core" dependency not found

### ISSUE THREAD

**Issue by lmserrano** [zio/zio#4417]
About 2 days ago there was [a commit](https://github.com/zio/zio/commit/0be5bb0265ff91983e761203d720047b21bdb042) bumping `qa.hedgehog\hedgehog-core` dependency version from `0.5.1` to `0.6.0`. However, this version does not seem to be currently available on [mavenrepository](https://mvnrepository.com/artifact/qa.hedgehog/hedgehog-core).

Currently I am unable to build the project due to this dependency:

```
[info] compiling 83 Scala sources to ...\zio\test\native\target\scala-2.11\classes ...
[error] stack trace is suppressed; run last benchmarks / update for the full output
[error] (benchmarks / update) sbt.librarymanagement.ResolveException: Error downloading qa.hedgehog:hedgehog-core_2.12:0.6.0
[error]   Not found
[error]   Not found
[error]   not found: ...\.ivy2\local\qa.hedgehog\hedgehog-core_2.12\0.6.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_2.12/0.6.0/hedgehog-core_2.12-0.6.0.pom
[error]   not found: https://dl.bintray.com/hedgehogqa/scala-hedgehog/qa.hedgehog/hedgehog-core_2.12/0.6.0/ivys/ivy.xml
[error] Total time: 201 s (03:21), completed 21 Nov 2020, 00:49:07
```

About 10 hours ago, someone has already reported encountering this issue too for the same dependency: https://github.com/zio/zio/pull/4416#issuecomment-731203937

We should roll back the dependency for the time being. Following up with a PR with this.

**Comment by mijicd** [comment]
This should be fixed in https://github.com/zio/zio/pull/4419. Please double-check.

**Comment by lmserrano** [comment]
I confirm @mijicd . Although that issue is not initially related with this, the person working on it added this fix as part of the resolution.

**Comment by mijicd** [comment]
That's also true :). Can we close this issue, or any further action is needed?

**Comment by lmserrano** [comment]
Closed, @mijicd
