### ISSUE TITLE
Promise.await not always interrupting properly

### ISSUE THREAD

**Issue by jsfwa** [zio/zio#4457]
During research of the previous problem https://github.com/zio/zio/issues/4395 find out that we have a probability to not properly cancel `await` in https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1981
```
errorSignal.await raceFirst f(a)
```
Here is simple reproducible scenario, the faster you create & interrupt fibers, the more chance that Canceler will not get fired
```
testM("joiners should properly clean up") {
      (for {
        p <- Promise.make[Throwable, Unit]

        spawner = ZStream.repeatEffect(ZIO.unit raceFirst p.await).runDrain

        _ <- spawner.fork

        joinersCount <- Task
          .succeed(p.state.get.asInstanceOf[Pending[_, _]].joiners.size)
          .tap(_ => p.succeed(()))
          .delay(60.seconds)

      } yield assert(joinersCount)(isLessThan(2)))
        .provideCustomLayer(zio.clock.Clock.live)
}
```

After debug this piece of code we are able to see such picture, some of fibers got interrupted, but not cleaned up:
![image](https://user-images.githubusercontent.com/7480075/100338066-2fc11300-2fe9-11eb-90d0-d16149488e6d.png)

Upd. the problem appears when we delegate interruption to another fiber:
```
for {
        p <- Promise.make[Throwable, Unit]
        _ <- ( for {
          fb <- p.await.fork
          _ <- fb.interrupt.fork //<<< If remove this fork and keep just `fb.intterupt`, everything works fine
        } yield ()).forever.fork
        _ <- p.succeed(()).delay(30.seconds)
      } yield ()
```

**Comment by adamgfraser** [comment]
I am looking into this.

**Comment by jsfwa** [comment]
I added FiberDescription to Promise and for all joiners, that haven't cleaned up we have:
```
```

**Comment by jsfwa** [comment]
Okay, I found the race condition
In FiberContext all stacks are mutable and not threadsafe, when we call `evaluateLater` there is a chance that two functions `evaluateNow` will work at the same time and all kind of magic will possibly happen there

Right now I just added synchronized on `evaluateNow` and it fixed my problem, but personally suggest to refactor `evaluateLater` to push effect on stack safely, instead of sending it directly to executor
