### ISSUE TITLE
Could we have DeriveGen instances for Refined types through a module zio-test-magnolia-refined?

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio#4475]
Refined library has been quite big in defining data types in applications.
```scala

val host: Refined[String, NonEmpty] = ???

```

Is there already a module integration giving the DeriveGen instances for these types? If not, can we have one such module as part of ZIO?  I can work on this if the issue makes sense.

The feature is going to be immediately useful for `zio-config-refined`.

The only issue that I can see here is we need to keep updating the library whenever `Refined` comes with up new phantom type representing a new set of validations.

**Comment by adamgfraser** [comment]
@afsalthaj I think that would be great. We already have support for Magnolia so I think if we are going to have other libraries in the ZIO ecosystem provide support for that then it makes sense for ZIO Test to as well. If you want to work on that would be fantastic and happy to help in any way I can!

**Comment by afsalthaj** [comment]
Thank @adamgfraser 

Yes. I can work on this. 

I think the only concern here is ensuring all Refine (NonEmpty, GreaterThan etc) have instances of DeriveGen, and keep up with the changes that happen in Refined.

**Comment by adamgfraser** [comment]
This has been implemented now.
