### ISSUE TITLE
TestRandom.deterministic

### ISSUE THREAD

**Issue by Fristi** [zio/zio#4481]
Is there any reason that `TestRandom` is set to `deterministic` in https://github.com/zio/zio/blob/master/test/jvm/src/main/scala/zio/test/PlatformSpecific.scala#L46 ? This rersults that every suite you run which uses zio-test generators will be set up with the same seed for generators, resulting in the same value. Might be useful, but in our case it's better to have it set a random

**Comment by adamgfraser** [comment]
@Fristi It makes tests reproducible so you get the same results for your test whether you run it again, add another test, or change the order of your tests. There is definitely a trade-off here between reproducibility and sampling a larger part of the total space of generated values by repeatedly running a test with a nondeterministic seed. We felt like this was the best default but if you want the other behavior you can easily change it by using the `nondeterministic` test aspect around your entire suite or creating your own subtype of `DefaultRunnableSpec` and including `nondeterministic` in the list of default test aspects.

**Comment by Fristi** [comment]
That sounds very reasonable! Couldn't find it in the docs, if it's not there shall I document this?

**Comment by adamgfraser** [comment]
@Fristi That would be great!
