### ISSUE TITLE
ZStream in ZLayer.fromManaged

### ISSUE THREAD

**Issue by jeubank12** [zio/zio#4489]
Following the zio.dev resource https://medium.com/@svroonland/processing-zio-effects-through-a-pipeline-c469e28dff62 this seems like the most basic implementation of a background stream.
https://gist.githubusercontent.com/svroonland/c66c1eb93d7724c80eeb7ca665032ed4/raw/eb22f3c9edd2508dba05a6eccb0675367afe4a4e/Pipeline.scala

Extending the example and putting it into a ZLayer (via ZLayer.fromManaged) results in the ZStream immediately exiting instead of persisting as a background processing Pipeline.

Is this intended behavior or should the stream persist as long as the application/layer is in use?

Simplified example:
```scala
val live: ZLayer[Logging, Nothing, Has[Queue[UIO[Unit]]] = ZLayer.fromManaged(
  for {
    q <- Queue.unbounded[UIO[Unit]].toManaged_
    _ <- ZStream.fromQueue(q)
        .mapM(effect => effect)
        .runDrain
        .onExit(_ => log.debug("Exiting Stream"))
        .forkManaged
  } yield q)
```

**Comment by jeubank12** [comment]
As an attempt to determine whether the stream or the ZLayer is at fault, I modified the ZStream creation as follows:
```scala
ZStream.fromQueue(q)
  .merge(ZStream.fromSchedule(Schedule.spaced(5.seconds))
    .as(UIO.unit))
  .mapM(effect => effect)
  .runDrain
  .onExit(_ => log.debug("Exiting Stream"))
  .forkManaged
```

The stream exits after completing the first item from the merged stream, leading me to suspect the Layer management causing the stream to close early

**Comment by jeubank12** [comment]
For complete context, this is running on http4s BlazeServer

**Comment by adamgfraser** [comment]
@jeubank12 I will take a look at this later today.

**Comment by jeubank12** [comment]
I was able to change `.forkManaged` to `.forkDaemon.toManaged_` and it keeps the stream open. I do not know what the cleanup looks like at this time because sbt just kills the jvm instead of shutting down in my current configuration

**Comment by jdegoes** [comment]
@adamgfraser This is probably auto-supervision kicking in somewhere, maybe implying we're not using the transplant/grafting machinery everywhere.

**Comment by adamgfraser** [comment]
@jdegoes Will take a look at this.

**Comment by adamgfraser** [comment]
@jeubank12 I took a look at this and with the following example the behavior seems to be correct with the the stream created within the layer not being terminated until the layer is released. I also looked through the code in `ZLayer` and did not notice any forking of fibers that would potentially be problematic. Do you have a small example like this that reproduces what you are seeing so we can track down further?

```scala
import zio._
import zio.clock._
import zio.console._
import zio.duration._
import zio.stream._

object Example extends App {

  def run(args: List[String]): zio.URIO[ZEnv, ExitCode] =
    program.provideCustomLayer(live).exitCode

  val program: URIO[Has[Queue[UIO[Unit]]] with Console with Clock, Unit] =
    ZIO.service[Queue[UIO[Unit]]].flatMap { queue =>
      for {
        _ <- console.putStrLn("Starting")
        _ <- queue.offer(UIO(println("Tick"))).delay(1.second).repeatN(5).fork
        _ <- console.getStrLn.orDie
        _ <- console.putStrLn("Ending")
      } yield ()
    }

  val live: ZLayer[Console, Nothing, Has[Queue[UIO[Unit]]]] =
    ZLayer.fromManaged {
      for {
        q <- Queue.unbounded[UIO[Unit]].toManaged_
        _ <- ZStream
               .fromQueue(q)
               .mapM(effect => effect)
               .runDrain
               .onExit(_ => console.putStrLn("Exiting Stream"))
               .forkManaged
      } yield q
    }
}

```

**Comment by jeubank12** [comment]
I had a hard time making a sample and in doing so I found the issue. BlazeServerBuilder was configured with `Task` instead of `RIO` which meant that it was not managing the layer.

Closing this since it was an issue particular to the code I was working in. 

For anyone coming to this issue because you have also experienced it, if you are using http4s/sttp then you should follow the recommended example for providing ZLayer to BlazeServerBuilder found here https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/sttp/tapir/examples/ZioEnvExampleHttp4sServer.scala
