### ISSUE TITLE
fork.toManaged(_.interrupt) never exits.

### ISSUE THREAD

**Issue by caeus** [zio/zio#4500]
The following snippet of code never stops printing "Hello"
```scala
(for {
        _ <- console.putStrLn("Hello").forever.fork.toManaged(_.interrupt)
      } yield ()).use(_ => console.putStrLn("Finished"))
```
However, the following one, does stop
```scala
(for {
        fiber <- console.putStrLn("Hello").forever.fork.toManaged_
        _     <- ZIO.unit.toManaged(_ => fiber.interrupt)
      } yield ()).use(_ => console.putStrLn("Finished"))
```

Why?

**Comment by adamgfraser** [comment]
@caeus `toManaged` treats the effect as the `acquire` action of a `ZManaged`, which is not uninterruptible. Therefore, the fiber is forked in an uninterruptible region and is also uninterruptible and so when the `release` action of the `ZManaged` attempts to interrupt it after performing the `use` action it suspends indefinitely. Your second example also suspends indefinitely when I run it on `master`.

**Comment by caeus** [comment]
Is there a way to interrupt a fiber in the release, that doesn't suspend indefinitely?

**Comment by adamgfraser** [comment]
If you just don't want to wait for interruption to complete you can fork the interruption (e.g. `fiber.interrupt.fork`). The better solution is to not make the forking uninterruptible if you intend to interrupt it. For example `ZManaged.makeInterruptible(effect.fork)(_.interrupt)`.
