### ISSUE TITLE
If the first layer, of multiple layers combined with >+>, fails, prettyPrinting the cause, takes TOO long.

### ISSUE THREAD

**Issue by caeus** [zio/zio#4503]
I have a piece of code like this 
```scala
ZLayer.requires[ZEnv] >+>
      ConfigProvider.live >+>
      AppConfig.live >+>
      ThingConfig.live >+>
      ThingLogging.live >+>
      HttpConfig.live >+>
      AsyncHttpClientZioBackend.layer().asInstanceOf[ZLayer[Any, Throwable, Has[SttpClient.Service]]] >+>
      //<Business>
      StuffClient.Config.live >+>
      StuffClient.live >+>
      SomeClient.Config.live >+>
      SomeClient.live >+>
      SomeSmsUpdatesConf.live >+>
      SomeSmsUpdates.live >+>
      SmsTester.Config.live >+>
      InventoryServiceConf.live >+>
      InventoryService.live >+>
      SmsTester.live >+>
      ResultNotifier.live >+>
      SmsTestsSrv.live >+>
      HealthChecks.live >+>
      //</Business>
      //<HTTP>
      HealthCheckRoute.live >+>
      SmsTestRoutes.live >+>
      SomeSmsUpdatesRoute.live >+>
      AppRoutes.live >+>
      AppServer.live >+>
      AdminRoutes.live >+>
      AdminServer.live >+>
      AdmindServer.live
```
Lots of layers. Yep. If ConfigProvider.live layer fails, the app may take several minutes, or even fail with an `OutOfMemoryError`.

How to deal with that?

**Comment by adamgfraser** [comment]
Which ZIO version are you on?

**Comment by caeus** [comment]
1.0.3 scala 2.13

**Comment by caeus** [comment]
@adamgfraser I fixed the problem with the current snippet.
`implicit final class ZLayerNonParallel[-RIn, +E, +ROut](private val self: ZLayer[RIn, E, ROut]) extends AnyVal {
    def >++>[E1 >: E, RIn2 >: ROut, ROut1 >: ROut, ROut2](
      that: ZLayer[RIn2, E1, ROut2]
    )(
      implicit union: Has.Union[ROut1, ROut2]
    ): ZLayer[RIn, E1, ROut1 with ROut2] = {
      ZLayer(for {
        deps1 <- self.build
        deps2 <- that.build.provide(deps1)
      } yield union.union(deps1, deps2))
    }
  }`
I then replaced the use of `>+>` for `>++>`.

I noticed that the operator `>+>` depends on `ZLayer.ZipParWith` which means the more I use `>+>` the more it forks, even when a previous layer failed.

Can we add such operator in ZLayer to avoid such problem?

**Comment by adamgfraser** [comment]
@caeus Thanks for following up on this! Let me take a look. That definitely helps narrow down the problem. I would like to try to address this in a way that fixes the general case without needing special operators, but this definitely helps me focus on the right thing.

**Comment by adamgfraser** [comment]
@caeus Spent some more time looking at this. Although fibers do get forked they are immediately interrupted so I don't think that is the issue.

It looks to me like the issue is really that the cause that is created is very large and it takes a long time to pretty print. I would suggest it might make more sense to tackle it from that angle. For example, in my testing even if I have a very large layer with a failure if I do something like `myProgramLogic.catchAllCause` and print something like the first failure I don't have any issue.

**Comment by caeus** [comment]
@adamgfraser I've seen it taking too long, even if I don't pretty print it.

**Comment by adamgfraser** [comment]
@caeus Okay will spend some more time on this.

**Comment by caeus** [comment]
@adamgfraser I saw the PR. Thanks for paying attention to this. I actually think that the `>+>` is the most awesome operator of ZLayer.

**Comment by adamgfraser** [comment]
@caeus Definitely! Sorry it took a little while and thank you for your work helping to identity the issue.

Yeah it is funny. When we were originally developing `ZLayer` we thought that the `>>>` and `++` operators would be what people would use. But there are a lot of people who like using `>+>` for everything.
