### ISSUE TITLE
ZIO Test: Add new spec type

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#4518]
To provide a more "flat" style and without any commas, it would be nice to define a mutable spec, supporting the following syntax:

```scala
object MySpec extends MutableRunnableSpec {
  suite("foo") {
    testM("name") {
    } @@ ignore

    test("name 2") {
      suite("another suite") {
      }
    }
  }
}
```

This would be accomplished by defining `suite` and `test` and `testM` methods directly inside `MutableRunnableSpec`, which would mutably append to a data structure, which would be materialized when the `def spec` of the parent runnable spec is called.

In order to support annotations, the `test` and `suite` methods would have to return some object with `@@` side-effect method, which modifies in-place the last definition by applying the test aspect.

The goal would be to preserve the existing ZIO Test syntax and feature set almost exactly, while at the same time getting away from the "comma" syntax which many find annoying.

**Comment by fokot** [comment]
I will take this

**Comment by hmemcpy** [comment]
Thanks so much for this! I'll add support for it in the IntelliJ plugin and it will make my teammates happy 👍 

One question: can top-level tests be added without suite?

**Comment by jdegoes** [comment]
Yes, no need for top-level suites. By default there is a top-level suite that has the same name as the spec object.

**Comment by hmemcpy** [comment]
Excellent! Thank you!

**Comment by hmemcpy** [comment]
Also I think this issue can be closed?
