### ISSUE TITLE
Support mirroring FiberRef contents to ThreadLocal

### ISSUE THREAD

**Issue by dkarlinsky** [zio/zio#4528]
It would be really useful for `FiberRef` contents to be mirrored to non-zio infra (outside of our control) backed by `ThreadLocal`s.
For example, when using NewRelic and it's [Tokens](https://docs.newrelic.com/docs/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications#tokens) to connect async flows to what they call a transaction (think an incoming request).
In this case, we would store the new relic token in a `FiberRef` like this:
```scala
    FiberRef.make(nrToken, link = _.link())
```
The provided `link` function will be called by zio after every async boundary so any effect running in this fiber (or a fiber inheriting this ref) will run on a thread "linked" to the token.
There might also be a need for `unlink` function to clear the the thread at the end.

(`MDC` is a simpler example, but maybe easier to work around with libraries like `zio-logging` or `FiberRef.unsafeAsThreadLocal`)

I've created this [Draft PR](https://github.com/zio/zio/pull/4421) a while back with a naive implementation for this.

@adamgfraser, @jdegoes WDYT?

**Comment by dkarlinsky** [comment]
Gentle Ping :) 
@adamgfraser @jdegoes

**Comment by jdegoes** [comment]
I think some generic RTS work could be done that would satisfy this use case, although it would not be specifically connected to thread local. Some sort of callback that can be invoked when a fiber starts running on a thread. In fact, the existing code that sets the active fiber (in a thread local) could leverage that mechanism

**Comment by dkarlinsky** [comment]
Yes that is exactly my idea - provide a callback when creating `FiberRef` that will be invoked after every async boundary.
I mentioned `ThreadLocal` since, in most cases the callback will be setting some state backed by a `ThreadLocal`.
My [Draft PR](https://github.com/zio/zio/pull/4421) already implements this, but I did want some guidance on where the correct spot was in `FiberRef`, to insert the call to the `link` callback. 
And I expect there will have to be some benchmarks, to make sure there was no performance hit, especially when not providing the `link` callback.

**Comment by jdegoes** [comment]
I wouldn't do it when creating fiber ref, but do it separately. There's nothing necessarily connected to fiber ref in such a feature. It may be more connected with `Supervisor`. Let me think about this for a week, but I do absolutely think we can get this into ZIO (thanks for the suggestion).

**Comment by dkarlinsky** [comment]
Thanks @jdegoes !

**Comment by d12frosted** [comment]
Unfortunately, I would love to have this in ZIO arsenal :smile_cat: 

@jdegoes did you have some time to think about including this feature? Thanks in advance.

**Comment by dkarlinsky** [comment]
Gently pinging again @jdegoes @adamgfraser :)

**Comment by jdegoes** [comment]
I am spec'ing this in a different way, but one that satisfies @dkarlinsky's requirements.

Essentially, in ZIO 2.0, we will add a `RuntimeConfigAspect`, along the lines of the following:

```scala
object RuntimeConfigAspect {
  ...
  def trackFiberRef[A](fiberRef: FiberRef.Runtime[A])(onResume: A => Unit): RuntimeConfigAspect = ...
  ...
}
```

The implementation of this `RuntimeConfigAspect` will be based on #5794, in particular, the two new methods it add to `Supervisor` which allow tracking suspension / resumption.
