### ISSUE TITLE
ZIO Test: allow run @@ ignore tests

### ISSUE THREAD

**Issue by domartynov** [zio/zio#4530]
When `@@ ignore` is used to mark an integration test (see [sample](https://github.com/zio/zio-cli/pull/76/files#diff-058ad5c887028233aa7521c6a5d8f8bf5ea7fd94da62fed0c033effa4f2eb501R38-R39)), is there a way to run the test (without removing `@@ ignore`)?

If not, can we add somthing like `-ri` or/and `--runIgnored` to `zio.test.TestArgs`, so `zio.test.FilteredSpec` removes `TestAnnotation.ignored` allowing to use `testOnly FooSpec -ri` in SBT?

**Comment by adamgfraser** [comment]
I think a more extensible way to achieve this might be through the use of tags. We already support tags for tests, so for example you can do `@@ tag("integration")` and then do `testOnly FooSpec -- -tags "integration". I think the only thing we are missing right now is support for a "not" command line operator so you could run all tests except integration tests normally and then run all tests including integration tests.

**Comment by domartynov** [comment]
I agree, how about to extend with a minus-tag, so in my case I can add `Test / testOptions += Tests.Argument("-tags", "it")` to `build.sbt` and use `@@ tag("it") to mark tests? (with last tag wins semantics, to be able to override build-level options with the command args)

But it does not solve the `@@ ignore` case. Today, i can mark tests with ignore, so they're skipped. If i have a GUI which list tests including ignored tests (e.g. an IDE plugin), there is not way to implement an action to send a specific test ignoring the ignore :smile: -- I think it's useful to be able to run ignored tests just via test args without changing in the code.

**Comment by adamgfraser** [comment]
Closing as this is handled in a more principled way by being able to use tags and either run only tests containing certain tags with `-tags` or run all tests that don't contain certain tags with `-ignore-tags`.
