### ISSUE TITLE
Publish ZIO for Scala.js on Scala 3

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4592]
We currently publish ZIO for Scala 3.0.0-M3 on the JVM and publish ZIO for Scala.js on Scala 2, but we don't publish for Scala.js on Scala 3. This ticket is to add support for Scala.js on Scala 3 by doing the following:

- [ ] Update the build file to publish snapshots and release for Scala.js on Scala 3
- [ ] Update the CI configuration to run the test suite on Scala.js on Scala 3
- [ ] Compile and run the tests locally and resolve any issues that arise

**Comment by scalavision** [comment]
@adamgfraser , I think izumi-reflect also needs to be published for scalajs before this can be done for zio? I tried a couple a months ago but got stuck on izumi dependency. Unfortunately I am not able to work on this at the moment, but it would be really great to have zio out on scalajs for scala 3.

**Comment by ghostdogpr** [comment]
Blocked by https://github.com/zio/izumi-reflect/issues/159

**Comment by neko-kai** [comment]
Unblocked in https://github.com/zio/izumi-reflect/releases/tag/v1.1.2

**Comment by ghostdogpr** [comment]
Next (and last?) blocker is scala-java-time but should be resolved soon: https://github.com/cquiroz/scala-java-time/pull/286

**Comment by ghostdogpr** [comment]
Getting a compiler crash, if anyone has an idea: https://github.com/zio/zio/pull/5101/checks?check_run_id=2592670075

**Comment by ghostdogpr** [comment]
Firgured it out, it's ready now.
