### ISSUE TITLE
ZIO Test: Upstream Generators From ZIO Test Refined Module

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4600]
We just merged support for generating values of types from the `refined` library through the `zio-test-refined` module thanks to work from @afsalthaj and @pierangeloc .

In [this](https://github.com/zio/zio/blob/2769933b193e47a21a205a9fcecd626876333f02/test-refined/shared/src/main/scala/zio/test/refined/CharInstances.scala#L12) file there are a couple of generators for alphabetical, numeric, and whitespace characters that could be more generally applicable. We should move these instances to the `Gen` companion object in ZIO Test and just use them here. A completed ticket will also add tests verifying that the generators generate values in the appropriate range and shrink to the expected values.

**Comment by maxim092001** [comment]
I think I can handle this one. But this is my very first experience with open source contribution, is there any guideline for newbies?

**Comment by 987Nabil** [comment]
@adamgfraser can this be closed?

**Comment by adamgfraser** [comment]
@987Nabil Yes!
