### ISSUE TITLE
ZIO Test: Separate Generation and Automatic Derivation of Refined Types

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4601]
We just merged support for generating values of types from the `refined` library through the `zio-test-refined` module thanks to work from @afsalthaj and @pierangeloc .

Currently, generation of values for these data types is linked with automatic derivation of generators powered by Magnolia. This provides a great user experience for the common case where the user just wants to automatically derive values for the refined type. However, if the user wants to manually generate their own values for the refined type and add custom logic it gets a little clunky because the user has to unpack the `DeriveGen` instance to get a `Gen` that they can compose using normal operators.

We can address that by first creating a set of constructs that just return `Gen` values that generate each data type from the `refined` library. Then we can build the `DeriveGen` instances on top of these. That way users who want automatic derivation will have it and users who want to manually build instances will have easy access to generators of refined types.

**Comment by jxnu-liguobin** [comment]
Hi @adamgfraser , Can I try this problem ?

> We can address that by first creating a set of constructs that just return `Gen` values that generate each data type from the `refined` library. Then we can build the `DeriveGen` instances on top of these. That way users who want automatic derivation will have it and users who want to manually build instances will have easy access to generators of refined types.

Can you give an example of using `all.scala`(p.s I'm a novice and I don't know used scenario.)
Give it an self type? like here 
```scala

//need Gen(maybe default)
object all1 extends StringGen
//if user need `DeriveGen` can add with StringInstances
object all2 extends StringGen with StringInstances
trait StringInstances {
  self: StringGen =>

  implicit def endsWithStringDeriveGen[S <: String](implicit ws: Witness.Aux[S]): DeriveGen[Refined[String, EndsWith[S]]] =
    DeriveGen.instance(self.endsWithStringGen(ws))

  implicit def startsWithStringDeriveGen[S <: String](implicit
    ws: Witness.Aux[S]
  ): DeriveGen[Refined[String, StartsWith[S]]] =
    DeriveGen.instance(self.startsWithStringGen(ws))

  implicit val uuidStringDeriveGen: DeriveGen[Refined[String, Uuid]] =
    DeriveGen.instance(
      self.uuidStringGen
    )
}


trait StringGen {

  implicit def endsWithStringGen[S <: String](implicit ws: Witness.Aux[S]): Gen[Random with Sized, Refined[String, EndsWith[S]]] =
    Gen.anyString.map(value => Refined.unsafeApply(value + ws.value))

  implicit def startsWithStringGen[S <: String](implicit ws: Witness.Aux[S]): Gen[Random with Sized, Refined[String, StartsWith[S]]] =
    Gen.anyString.map(value => Refined.unsafeApply(ws.value + value))

  implicit def uuidStringGen: Gen[Random, Refined[String, Uuid]] = Gen.anyUUID.map(value => Refined.unsafeApply(value.toString))

}
```

**Comment by adamgfraser** [comment]
@jxnu-liguobin Please!

I think the approach can be a little simpler. Basically, right now we have something like:

```scala
implicit val uuidStringDeriveGen: DeriveGen[Refined[String, Uuid]] =
  DeriveGen.instance(
    Gen.anyUUID.map(value => Refined.unsafeApply(value.toString))
  )
```

We would like to turn it from something that returns a `DeriveGen` to something that returns a `Gen`:

```scala
val uuidStringGen: Gen[Random with Sized, Refined[String, Uuid]] =
  ???
```

This way users can use generators for refined types if they want to compose their generators explicitly versus deriving them with Magnolia. Then we can recover the existing functionality by doing:

```scala
implicit val uuidStringDeriveGen: DeriveGen[Refined[String, Uuid]] =
  DeriveGen.instance(uuidStringGen)
```

**Comment by jxnu-liguobin** [comment]
> I think the approach can be a little simpler. Basically, right now we have something like:

@adamgfraser Oh. It only need to provide an implicit method?(I'm worried about conflict.)
```scala
trait StringInstances {

  implicit def endsWithStringGen[S <: String](implicit ws: Witness.Aux[S]): Gen[Random with Sized, Refined[String, EndsWith[S]]] =
    Gen.anyString.map(value => Refined.unsafeApply(value + ws.value))

  implicit def startsWithStringGen[S <: String](implicit ws: Witness.Aux[S]): Gen[Random with Sized, Refined[String, StartsWith[S]]] =
    Gen.anyString.map(value => Refined.unsafeApply(ws.value + value))

  implicit def uuidStringGen: Gen[Random, Refined[String, Uuid]] = Gen.anyUUID.map(value => Refined.unsafeApply(value.toString))


  implicit def endsWithStringDeriveGen[S <: String](implicit ws: Witness.Aux[S]): DeriveGen[Refined[String, EndsWith[S]]] =
    DeriveGen.instance(endsWithStringGen(ws))

  implicit def startsWithStringDeriveGen[S <: String](implicit
    ws: Witness.Aux[S]
  ): DeriveGen[Refined[String, StartsWith[S]]] =
    DeriveGen.instance(startsWithStringGen(ws))

  implicit val uuidStringDeriveGen: DeriveGen[Refined[String, Uuid]] =
    DeriveGen.instance(uuidStringGen)
}
```

**Comment by adamgfraser** [comment]
We don't want to provide new implicit methods. We want to provide new non-implicit methods and replace the implementations of the existing implicit methods. So in my example above `implicit val uuidStringDeriveGen` already exists and we are just implementing it in terms of a new non-implicit `val uuidStringGen` that we are creating.

**Comment by jxnu-liguobin** [comment]
> We don't want to provide new implicit methods. We want to provide new non-implicit methods and replace the implementations of the existing implicit methods. So in my example above `implicit val uuidStringDeriveGen` already exists and we are just implementing it in terms of a new non-implicit `val uuidStringGen` that we are creating.

👌

**Comment by kmatasflp** [comment]
@jxnu-liguobin are you still working on it or I can try and take a crack at it?

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin are you still working on it or I can try and take a crack at it?

I have done. The problem was forgotten to close. @adamgfraser
