### ISSUE TITLE
ZIO Test: Add Gen Instances For Additional Refined Types

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4602]
We just merged support for generating values of types from the `refined` library through the `zio-test-refined` module thanks to work from @afsalthaj and @pierangeloc .

This ticket is to go through all refined types defined in the `refined` library and make sure that we have a corresponding generator for them. This ticket can potentially be worked on by multiple people, so a good first step would be to comment on this ticket with a checklist of all types that don't currently have generators. People can them pick off groups of them to implement.

**Comment by alim16** [comment]
@adamgfraser I had a long look at this and concluded that I can't do it, but I had a go at creating the TODO list
I only did it partially, because I'm not sure I understood it correctly
I'll add what I have after this comment

let me know if it's incorrect and I'll delete the comment

**Comment by alim16** [comment]
https://github.com/fthomas/refined/blob/master/modules/core/shared/src/main/scala/eu/timepit/refined/types/numeric.scala#L97
  NumericInstances: **for each one there are also Negative and NonNeg and NonPos except for NonNaNFloat
  and NonNanDouble

 CharInstances: (zio-test-refined has more like `whiteSpace` and `Digit`)
| Type            | Description                                         | Done
| ----------------| -----------                                         | --- 
| PosByte         | A `Byte` in the range from 1 to `Byte.MaxValue`.    | partially?
| PosShort        | A `Short` in the range from 1 to `Short.MaxValue`.  | partially?                
| PosInt          | An `Int` in the range from 1 to `Int.MaxValue`.     | partially?      
| PosLong         | A `Long` in the range from 1 to `Long.MaxValue`.    |       
| PosBigInt       | A `BigInt` greater than 0.                          | 
| PosFloat        | A `Float` greater than 0.                           |
| PosDouble       | A `Double` greater than 0.                          | partially?
| PosBigDecimal   | A `BigDecimal` greater than 0.                      | 
| NonNaNFloat     | A `Float` that is not NaN.                          |       
| NonNaNDouble    | A `Double` that is not NaN.                         |            



*For the ones marked "partially? "zio-test-refined has `lessThan` and `greaterThan` instances
I don't know how that maps across

---------------------------------------------
https://github.com/fthomas/refined/blob/master/modules/core/shared/src/main/scala/eu/timepit/refined/types/char.scala

CharInstances: (zio-test-refined has more like `whiteSpace` and `Digit`)
| Type            | Description | Done
| ----------------| ----------- | --- 
| LowerCaseChar   |             | ✅
| UpperCaseChar   |             | ✅
---------------------------------------------

*TO BE ADDED

BooleanInstances: ???

--------------------------------------------
StringInstances: ???

--------------------------------------------
CollectionInstances: ???

--------------------------------------------
GenericInstances: ???

**Comment by ausmarton** [comment]
@adamgfraser I've tried to compile a list of the types defined in `eu.timepit.refined.types`. Please let me know if this is useful, cheers!
- [ ] all
    - [ ] AllTypes
        - [ ] CharTypes
            - [ ] LowerCaseChar
            - [ ] UpperCaseChar
        - [ ] DigestTypes
            - [ ] MD5
            - [ ] SHA1
            - [ ] SHA224
            - [ ] SHA256
            - [ ] SHA384
            - [ ]  SHA512
        - [ ] NetTypes
            - [ ] PortNumber
            - [ ] SystemPortNumber
            - [ ] UserPortNumber
            - [ ] DynamicPortNumber
            - [ ] NonSystemPortNumber
            - [ ] Rfc1918ClassAPrivate
            - [ ] Rfc1918ClassBPrivate
            - [ ] Rfc1918ClassCPrivate
            - [ ] Rfc1918Private
            - [ ] Rfc5737Testnet1
            - [ ] Rfc5737Testnet2
            - [ ] Rfc5737Testnet3
            - [ ] Rfc5737Testnet
            - [ ] Rfc3927LocalLink
            - [ ] Rfc2544Benchmark
            - [ ] PrivateNetwork
        - [ ] NumericTypes
            - [ ] PosInt
            - [ ] NonNegInt
            - [ ] NegInt
            - [ ] NonPosInt
            - [ ] PosLong
            - [ ] NonNegLong
            - [ ] NegLong
            - [ ] NonPosLong
            - [ ] PosFloat
            - [ ] NonNegFloat
            - [ ] NegFloat
            - [ ] NonPosFloat
            - [ ] PosDouble
            - [ ] NonNegDouble
            - [ ] NegDouble
            - [ ] NonPosDouble
        - [ ] StringTypes
            - [ ] FiniteString[N]
            - [ ] NonEmptyString
            - [ ] TrimmedString
            - [ ] HexString
        - [ ] TimeTypes
            - [ ] Month
            - [ ] Day
            - [ ] Hour
            - [ ] Minute
            - [ ] Second
            - [ ] Millis
    - [ ] AllTypesBinCompat1
        - [ ] NumericTypesBinCompat1
            - [ ] PosByte
            - [ ] NonNegByte
            - [ ] NegByte
            - [ ] NonPosByte
            - [ ] PosShort
            - [ ] NonNegShort
            - [ ] NegShort
            - [ ] NonPosShort
            - [ ] PosBigInt
            - [ ] NonNegBigInt
            - [ ] NegBigInt
            - [ ] NonPosBigInt
            - [ ] PosBigDecimal
            - [ ] NonNegBigDecimal
            - [ ] NegBigDecimal
            - [ ] NonPosBigDecimal
    - [ ] AllTypesBinCompat2
        - [ ] NumericTypesBinCompat2
            - [ ] NonNaNFloat
            - [ ] NonNaNDouble
    - [ ] AllTypesBinCompat3
        - [ ] StringTypesBinCompat1
            - [ ] NonEmptyFiniteString[N]

**Comment by maxim092001** [comment]
@ausmarton am I right that this list is relevant and I can try to implement something?

**Comment by adamgfraser** [comment]
@maxim092001 Yes!

**Comment by ausmarton** [comment]
@adamgfraser Thanks for confirming that.

**Comment by kazchimo** [comment]
@adamgfraser Shulod this be closed?

**Comment by adamgfraser** [comment]
@kazchimo Yes.
