### ISSUE TITLE
collectAllParN_ discards failed effects since 1.0.4

### ISSUE THREAD

**Issue by kusaeva** [zio/zio#4612]
I noticed that `collectAllParN_` started to discard failed effects since 1.0.4.
So this code will not fail:

```
val tasks = List.fill(10)(ZIO.fail(new RuntimeException))

ZIO.collectAllParN_(5)(tasks)
```

But it will fail with `.collectAllParN` or `.collectAll_`
Is this intentional behaviour?

**Comment by adamgfraser** [comment]
@kusaeva Thanks for reporting! Will fix.

**Comment by iravid** [comment]
@adamgfraser Can we release 1.0.4.1 with this fix?

**Comment by adamgfraser** [comment]
@iravid Yes. Will do this morning.
