### ISSUE TITLE
Questions About Queue Composition Semantics

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4636]
I'm looking at the implementation of some of the composition operators on `ZQueue` and some of the ways of composing them seem somewhat ill-defined.

For example in `bothWith` the capacity is the minimum of the capacity but the size is the maximum of the size, so you could potentially have one queue with 10 elements and 100 capacity and another with 1,000 elements and 10,000 capacity and get back a combined queue with size 1,000 and capacity 100, which doesn't really make sense. I'm not sure there is an obviousy better way to do this.

Another example is in a queue where we have filtered the inputs if we offer a group of values to the queue we return `true` as long as we successfully offer any value to the queue, even if we drop other values, whereas like a dropping queue returns `false` for `offerAll` if it drops any elements. Maybe `offerAll` should return a collection of the values that you weren't successful in offering instead of just a `Boolean` to preserve information?

Another idea would be to do something like we did with `Fiber` where as have a concept of a "primitive" versus a "synthetic" queue. Then we could potentially say some concepts just don't make sense for synthetic queues.

**Comment by adamgfraser** [comment]
Another example of this is in the implementation of the `takeAll` and `takeUpTo` operators, which call `zip` on the collections coming from the two queues when the collections could be of different sizes and thus risks silently dropping elements. It seems like at the least we would need something like `zipAll` here that let us handle the case of different sizes or the composite queue would have to do some internal buffering. But it feels like we are getting close to stream territory here.

**Comment by iravid** [comment]
After a year or so with these combinators , I ended up only using contramap/M, map/M and filterInput.

I think we knew about these shortcomings (and I seem to recall that we documented them?) but in hindsight I think we should just delete queue zipping; just too many pitfalls to be useful.

**Comment by adamgfraser** [comment]
That is kind of my view as well.
