### ISSUE TITLE
STM: NullPointerException and ArrayIndexOutOfBoundsException in TMap

### ISSUE THREAD

**Issue by ravisharnagat** [zio/zio#4648]
This might be an issue with TMap (haven't tried with other STM data structures yet)

```
import zio.stm.{TMap, ZSTM}
import zio.Runtime
import zio.{ZIO, _}

Runtime.default.unsafeRun {
  for {
      map <- TMap.make[Int, Int]().commit
      _ <- ZIO.foreach_(0 to 10) { i =>
        for {
        _ <- map.put(i, i).commit
        _ <- map.delete(i).commit.fork
        _ <- map.foreach((_, _) => ZSTM.unit).commit.fork
      } yield ()
    }
  } yield map
}
```
https://scastie.scala-lang.org/DaD8pAXySjSitvvOCCcBfA

- NullPointerException happens intermittently in case of a race between delete  and foreach
- ArrayIndexOutOfBoundsException happens intermittently while running foreach (it is independent of deleting entry from map, try removing `_ <- map.delete(i).commit.fork` in above code

**Comment by adamgfraser** [comment]
@mijicd Could you take a look at this?

**Comment by mijicd** [comment]
Will do, thanks for reporting!

**Comment by ravisharnagat** [comment]
@mijicd I have updated the code. 
Replaced `_ <- map.delete(i).commit` with `_ <- map.delete(i).commit.fork` just to make sure both of them(`delete` and `foreach`) executes in separate fiber.
It will help in recreating NullPointerException easily.

**Comment by adamgfraser** [comment]
I can replicate locally as well.
