### ISSUE TITLE
Publish ZIO for Scala 3.0.0-RC1

### ISSUE THREAD

**Issue by lvitaly** [zio/zio#4732]
https://github.com/lampepfl/dotty/releases/tag/3.0.0-RC1

**Comment by adamgfraser** [comment]
Will do as soon as a new version of `Izumi-reflect` is published.

**Comment by pshirshov** [comment]
Don't hesitate to ping me/Kai when you need a new release :)
This work is mostly mechanical.

**Comment by adamgfraser** [comment]
@pshirshov Thanks! Will do!

**Comment by pshirshov** [comment]
@adamgfraser : could you drop into https://github.com/zio/zio/issues/4729 and share your thoughts please?

**Comment by adamgfraser** [comment]
@pshirshov Will do!

**Comment by neko-kai** [comment]
On it (https://github.com/zio/izumi-reflect/pull/141). Seems like there were some changes in tasty-reflect which make this update less trivial than the previous updates by incrementing the version :ˆ)

**Comment by lvitaly** [comment]
@neko-kai, could it be caused by https://github.com/lampepfl/dotty/issues/11557 ?

**Comment by neko-kai** [comment]
@lvitaly Possibly, but unlikely since we do not use Expr.summon.

**Comment by adamgfraser** [comment]
@sideeffffect A release is currently in process.
