### ISSUE TITLE
Potential Scala 3 Compatibility Issue With Tags

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4739]
This program runs correctly on Scala 2 but fails on Scala 3:

```scala
import zio._
import zio.console._

object Example {

  type FakeExchange = Has[FakeExchange.Service]

  object FakeExchange {
    trait Service {
      def blah(): UIO[Unit]
    }
    def blah(): ZIO[FakeExchange, Nothing, Unit] = ZIO.accessM(_.get.blah())
    val fakeExchangeLayer: ZLayer[Any, Nothing, FakeExchange] =
      ZLayer.succeed {
        new FakeExchange.Service {
          override def blah() = UIO.unit
        }
      }
  }
}

object Main extends App {
  import Example._
  import Example.FakeExchange.fakeExchangeLayer
  def run(args: List[String]) = {
    val infra = ZLayer.requires[zio.console.Console] ++ ZLayer.requires[zio.clock.Clock] ++
      ZLayer.requires[zio.blocking.Blocking] ++ ZLayer.requires[zio.random.Random]
    type TargetEnv = zio.console.Console
      with zio.clock.Clock
      with zio.blocking.Blocking
      with FakeExchange
      with zio.random.Random
    val finalLayer: ZLayer[
      zio.random.Random with zio.console.Console with zio.clock.Clock with zio.blocking.Blocking,
      Nothing,
      TargetEnv
    ] =
      infra >+> fakeExchangeLayer
    val program2: ZIO[TargetEnv, Nothing, Int] = ZIO.succeed(0)
    (putStrLn("running...") *> program2).provideCustomLayer(finalLayer).exitCode
  }
}
```

The error message on Scala 3 is:

```
Fiber failed.
An unchecked error was produced.
java.lang.Error: Defect in zio.Has: HashSet(Example$::FakeExchange$::Service, package$::Console$::Service, package$::Random$::Service, package$::Blocking$::Service, package$::Clock$::Service) statically known to be contained within the environment are missing
```

Given that it works correctly on Scala 2 I am thinking that this is an issue with the `Tag` machinery and the way it interacts with Scala 3.

@neko-kai Could you take a look when you have the chance?

**Comment by heksesang** [comment]
So, I played a bit with the example in Scastie.

This one, the same as in the example, does not compile:
https://scastie.scala-lang.org/gmOTh5a1SiWkoxkE17Badw

This one, however, does compile:
https://scastie.scala-lang.org/qP7rYVmgSbCfmUKNmM81rg

The difference is that I have reduced the number of services in the environment from five to four. Doesn't matter which of the services I remove, it seems to only care about the number of services. Once it goes beyond four, the code breaks.

**Comment by heksesang** [comment]
Any ETA on when this will be fixed?

**Comment by adamgfraser** [comment]
@neko-kai Any update on this one?

**Comment by neko-kai** [comment]
@adamgfraser Haven't had the time to look into this yet!
@heksesang No ETA but could possibly find the time within next week. If you're interested in a faster fix, you could investigate further, e.g. if Map1-4 theory is correct then the issue may be in unlawfulness of hashCode wrt equals (exclusive to Scala 3 impl), this would mean that wrapping an existing LightTypeTag in a proxy wrapper that overrides hashCode to 0 would quickly prove/disprove that theory.

**Comment by adamgfraser** [comment]
@neko-kai Thanks for the update!

**Comment by heksesang** [comment]
In my project, I worked around it by splitting my environment in sets of max 4 services, and supplying each set with `provideSomeLayer`. For the ZIO-based `SttpClient` I had to provide that as its own layer, as soon as I tried to combine anything else with that layer it failed with the same error as described in this issue regardless of number of services (which seems to support the theory that there is a problem with the hashCode?).
