### ISSUE TITLE
Create ZLayer.ifM or make ZLayer a monad 

### ISSUE THREAD

**Issue by heaven-born** [zio/zio#4745]
After [this](https://discord.com/channels/629491597070827530/630498701860929559/815129598592286730) question I thought, maybe it would be nice to have something like `ZLayer.IfM(...)` for covering cases where conditional creation of layers needed. 

Or even make `ZLayer` a monad (or just introduce flatMap), so the following would be possible:

    val live:URLayer[Configuration,Foo] = for {
        c             <-  ZLayer.service[Configuration.Service]
        enabled       <- c.isFooEnabled.toLayer
        res           <- if (enabled) never else ignore
     } yieldr res

     val never: ULayer[Foo] = ZLayer.succeed(new Service {
        override def run: UIO[Unit] = UIO.never
      })

      val ignore: ULayer[Foo] = ZLayer.succeed(new Service {
          override def run: UIO[Unit] = UIO.unit
      })

Maybe it would be even more readable than `ZLayer.fromServices` for introducing multiple dependencies.

**Comment by adamgfraser** [comment]
@heaven-born We don't want to make it a monad so that we can statically know the structure of the dependency graph. I think the ideal way to do that would be to make the dependency part of the input type of the layer so it is `ZLayer[Configuration, Foo]` or `ZLayer[Has[Boolean], Foo]` or just have `never` and `ignore` be effects instead of layers in this case. We can support conditionality through `Fold` but I would like to tie it to some notion of what is the "happy path" versus "alternative path" so that we can still say things like "on the happy path the number of layers in the dependency graph is X".

**Comment by heaven-born** [comment]
@adamgfraser  I'm wondering, If layers have such limitations, wouldn't it be more clear in most cases to use ZIO effect for creating "layers", and then convert them to `ZLayer` right before they have to be used this way - on the layer composition stage? Or even do it implicitly. 

I remember [your answer](https://discord.com/channels/629491597070827530/630498701860929559/811485812784365568) about the nature of the ZLayer, but it looks like using `ZLayer` explicitly makes developers do the same things as they can do with zio effect, but in a different way. And they also have to keep in mind the limitations. 

The constructors like`ZLayer.fromServices` are useful, but a unified approach is also a good thing.

**Comment by heaven-born** [comment]
closing as a "matter of taste" issue.

**Comment by adamgfraser** [comment]
@heaven-born I hear you about having multiple ways of doing things.

I would think about `ZLayer` as a specialized solution for the problem of "gluing together" an application's dependencies and not use it for anything else.

There are a ton of things you can do with `ZIO` such as forking fibers that you can't do directly with `ZLayer` so `ZLayer` is never going to be a replacement for `ZIO`.

I would use `ZLayer` exclusively when you have a service you want in the environment, with a service being defined roughly as something that provides some functionality where you only want one of that thing in your application (e.g. one `Persistence`, one `Logging`) and potentially want to provide multiple implementations such as test implementations.

I would do all the work to set up and tear down each of those services within a layer constructor and I would basically only use the `++` and `>>>` operators for putting those layers together (or `>+>` depending on your tastes).

So like in your example above I would build `live` in a single `ZLayer` constructor and would think as a rule of thumb layers should only consume or output services. That's obviously a bit of personal preference as you say but I think that is a relatively idiomatic way to use layers that distinguishes when you want to use layers and when you don't.
