### ISSUE TITLE
weird dependency between projects

### ISSUE THREAD

**Issue by virusdave** [zio/zio#4787]
`zio-macros` has compile (not test) dependencies on `zio-test-sbt` which itself has compile (not test) dependencies on `zio-test`.

This inhibits clean use in build systems like `bazel`, which would prohibit testonly dependencies (like `zio-test`) from being transitive compile dependencies of non-test code.  This basically makes zio-macros unusable (at least, without some possibly truly ugly hacks).

Is this dependency correct?  can it be made a test-only dependency instead?  If not, what's the rationale for relying on a testing library for non-test code?

**Comment by adamgfraser** [comment]
Yes I don't think there is any reason this should be there. Will fix after ZIO World unless someone else gets to it first.

**Comment by virusdave** [comment]
Thanks for the rapid response!  I will eagerly be watching for the next release so I can use `zio-macros` in my own code (as well as dependees like `zio-magic` and friends!  Huzzah 🥳
