### ISSUE TITLE
Stream.bracket produces stream with only first element

### ISSUE THREAD

**Issue by wongelz** [zio/zio#481]
Not sure if this is the correct usage, as there isn't much documentation to go by, but Stream.bracket seems to only ever produce 1 element...

```
import scalaz.zio._
import scalaz.zio.stream.Stream

object StreamMain extends App {

  def run(args: List[String]): IO[Nothing, ExitStatus] = {
    Stream.bracket(IO.now(Iterator("hello", "world")))(_ => IO.now(())) {
      i => IO.sync { if (i.hasNext) Some(i.next()) else None }
    }
    .foreach(n => IO.sync { println(n) }) // only prints "hello"
    .map(_ => ExitStatus.ExitNow(0))
  }
}
```

(File IO swapped out for simple reproducible code in the example)

**Comment by RaasAhsan** [comment]
Correct me if I'm wrong, but it seems like your `use` is just reading a single value off the `Iterator`.

**Comment by wongelz** [comment]
Yes, given the type signature `read: A => IO[E, Option[B]]`, I would expect it to keep calling until it receives `IO` containing `None`.
