### ISSUE TITLE
zio.App does not exit if fatal error occurs

### ISSUE THREAD

**Issue by lyubortk** [zio/zio#4810]
The following program never stops:

```
import zio.{ZIO, URIO, ExitCode}

object Main extends zio.App {
  def program: ZIO[zio.ZEnv, Throwable, Any] =
    // make sure that shutdown hook is registered
    zio.clock.sleep(java.time.Duration.ofSeconds(2)) *> ZIO.effect(throw new OutOfMemoryError())

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = program.exitCode
} 
```

I suppose that JVM just waits for that shutdown hook to finish its work (but it never happens):
https://github.com/zio/zio/blob/2200981909e54296275db55f9944e9018a918cc7/core/jvm/src/main/scala/zio/App.scala#L57-L61

Could it be that the fiber in which a fatal error was thrown just cannot be interrupted? If so then it explains why the shutdown hook blocks indefinitely.

<br>

P.S.
For some reason it looks like the code finishes normally when run with sbt (sbt 1.4.9 prints that the program has completed and then just freezes). However, if the compiled jars are invoked directly with `java` then the program never stops just as I described.

ZIO 1.0.5
openjdk 11.0.10

**Comment by jdegoes** [comment]
The desired behavior of this program is that `System.exit` is invoked with a dump of the out of memory error.

**Comment by adamgfraser** [comment]
It looks like we suspend indefinitely on attempting to interrupt the fiber in the shut down hook. One possibility is to fork the interruption so we don't wait for it. That results in printing the out of memory error and exiting. Looking into why we can't interrupt there.
