### ISSUE TITLE
create ZStream.fromIterator(java.util.Iterator) 

### ISSUE THREAD

**Issue by domdorn** [zio/zio#4839]
I've noticed that we only have a ZStream.fromIterator method for scala-iterators. Wondering if we should also provide one for the java iterators or we should just let the users convert them manually using `scala.jdk.CollectionConverters` ?

**Comment by adamgfraser** [comment]
@domdorn I think we already have this [here](https://github.com/zio/zio/blob/30a30a4ae925a9de37434874aeb354703cc35868/streams/shared/src/main/scala/zio/stream/ZStream.scala#L3679).

**Comment by domdorn** [comment]
oh, right.. would have expected that the method is just overloaded. closing

**Comment by adamgfraser** [comment]
We tend to avoid overloading.
