### ISSUE TITLE
ZIO Test: Setting the seed doesn't work with shared layers

### ISSUE THREAD

**Issue by ollyw** [zio/zio#4840]
In some test with a base class that extends `DefaultRunnableSpec` and adds either `nondeterministic` or `setSeed` or calls `TestRandom.setSeed` in an aspect, the seed is reverted to the default if the Suite uses `provideSomeLayerShared` or `provideLayerShared` and the environment has `Random` either directly, or as part of `TestEnvironment.any`, `ZEnv.any`, etc.

After finding the cause, the behaviour seems reasonable in some aspects, but it renders test aspects in base classes useless, and also is very prone to user error when the test aspect is placed after the provideSomeLayerShared, which is a very easy mistake to make. 

I have these reproducers:

```
import zio.ZIO
import zio.test.Assertion._
import zio.test.TestAspect.setSeed
import zio.test._
import zio.test.environment.{TestEnvironment, TestRandom}

object RandomPuzzle extends DefaultRunnableSpec {
  override def spec = suite("RandomPuzzle")(
    testM("check seed") {
      for {
        s <- TestRandom.getSeed
      } yield assert(s)(equalTo(1L))
    }
  ) @@ setSeed(1)
}

object RandomPuzzleSetSeedThenShared extends DefaultRunnableSpec {
  override def spec = (suite("RandomPuzzleSetSeedThenShared")(
    testM("check seed") {
      for {
        s <- TestRandom.getSeed
      } yield assert(s)(equalTo(1L))
    }
  ) @@ setSeed(1)).provideSomeLayerShared[TestEnvironment](TestEnvironment.any ++ ZIO.unit.toLayer)
}

// Works
object RandomPuzzleSharedThenSetSeed extends DefaultRunnableSpec {
  override def spec = suite("RandomPuzzleSharedThenSetSeed")(
    testM("check seed") {
      for {
        s <- TestRandom.getSeed
      } yield assert(s)(equalTo(1L))
    }
  ).provideSomeLayerShared[TestEnvironment](ZIO.unit.toLayer) @@ setSeed(1)
}

// Doesn't work
object RandomPuzzleSharedThenSetSeedWithTestEnv extends DefaultRunnableSpec {
  override def spec = suite("RandomPuzzleSharedThenSetSeed")(
    testM("check seed") {
      for {
        s <- TestRandom.getSeed
      } yield assert(s)(equalTo(1L))
    }
  ).provideSomeLayerShared[TestEnvironment](TestEnvironment.any >>> ZIO.unit.toLayer) @@ setSeed(1)
}
```

After finding the cause, I also managed to find this message on Discord which is related, but didn't find any follow up https://discord.com/channels/629491597070827530/630498701860929559/702914356551221368

**Comment by scottweaver** [comment]
I just discovered the same issue effects the `samples` aspect when positioned after `provideSomeLayer`/`provideCustomLayer` as well.  This leads me to believe most , if not all aspects get "overwritten" in these cases, at least for ones that manipulate the environment state.

```
testM("Test a thing.") {
  checkM(Gen.unit) {
     zio.console.putStrLn(">>> EXECUTING TEST <<<") >>> assertM(ZIO.unit)(anything)  
  }
  
} @@ samples(1) provideSomeLayer(testEnv)
``` 
prints `>>> EXECUTING TEST <<<` once as expected.

However:
```
testM("Test a thing.") {
  checkM(Gen.unit) {
     zio.console.putStrLn(">>> EXECUTING TEST <<<") >>> assertM(ZIO.unit)(anything)  
  }
}.provideSomeLayer(testEnv) @@ samples(1)
``` 
ends up printing `>>> EXECUTING TEST <<<` a number of times equal to the default samples setting which appears to be 100.

**Comment by ollyw** [comment]
Yes, indeed, when test aspected used in tests are dependent on the order  mixed in. This can create subtle bugs when the aspects seem unrelated to the test environment.

For example, in the codebase I am working on, where it seems that property based testing is doing its thing and providing many cases, but actually the seed were the same for a given test every time because the seed was always the default. This can hide bugs and is something that doesn't get picked up easily with code reviews.

In order to reduce the chances of this happening a hack was added to force the seed by overriding the test running in the common Spec trait that are used for tests:
```
  private def getSeed = sys.env.get("CI_JOB_ID").flatMap(_.toLongOption).getOrElse(defaultSeed)

  override def runner: TestRunner[TestEnvironment, Any] = TestRunner(
    TestExecutor.default(testEnvironment >+> (for {
      seed <- UIO(getSeed)
      _    <- TestRandom.setSeed(seed)
    } yield ()).toLayer)
  )
  ```
  It isn't pretty, but works and makes sure that failing tests in CI can be recreated locally and ensuring that the seed is actually used. There must be a much nicer way though...

**Comment by adamgfraser** [comment]
Test aspects like `samples` or `setSeed` modify the environment. If the environment has already been provided there is nothing left to modify. So in examples like:

```scala
testM("Test a thing.") {
  checkM(Gen.unit) {
     zio.console.putStrLn(">>> EXECUTING TEST <<<") >>> assertM(ZIO.unit)(anything)  
  }
}.provideSomeLayer(testEnv) @@ samples(1)
```

If you are already providing the test environment then there is nothing else for `samples` to modify. I think best practice here is to not provide the `TestEnvironment` manually and allow the test framework to do that for you.

**Comment by ollyw** [comment]
We can close this off now, as the behaviour has been explained, although is not ideal. Perhaps it is different in ZIO 2 Test
