### ISSUE TITLE
type alias for Checks, converting from Some to error

### ISSUE THREAD

**Issue by tyrcho** [zio/zio#4841]
I have identified a recurring pattern in our project using ZIO.

We want to fail when some function returns Some(x) and succeed when it returns None.

I'm thinking of defining a method like this one:

```scala
def noneOrFail[E,O](o:Option[O], f:O=>E):IO[E,Unit]=
    ZIO.fromEither(o.toLeft(())).mapError(f)
    // similar implementation
    //ZIO.getOrFailUnit(o).flip.mapError(f) 
````

And maybe a new type Alias
```scala
type Check[E] = IO[E, Unit]
```

Is there a more standard way to do this with ZIO?
Otherwise, is this an extension you'd be interested to add ?

**Comment by adamgfraser** [comment]
I think variants of `getOrFail` that expect the `None` case would be fine. `Check` type alias seems a little specialized to me.

**Comment by tyrcho** [comment]
thanks for the reply. I agree for the type alias.

about noneOrFail, would you like me to submit a PR ? only the ZIO trait needs a change, right ?

**Comment by adamgfraser** [comment]
I think it would be a constructor so it would go on the `ZIO` companion object, right? When we add methods to the companion object we also add aliases for them to the companion objects for the various `ZIO` type aliases like `Task` with the appropriate constraints.

**Comment by tyrcho** [comment]
Here is the PR : #4851 

I struggled with the unit tests.

**Comment by tyrcho** [comment]
cleaned the format + signed the CLA

**Comment by tyrcho** [comment]
actually, I'll let this open until the feature is available in the next release

**Comment by adamgfraser** [comment]
I think if we have implemented the feature we should close the issue even if it is not in the latest release yet.
