### ISSUE TITLE
STM: read uncommitted value

### ISSUE THREAD

**Issue by durban** [zio/zio#4870]
I may be missing something, but it seems that it is possible to read an uncommitted value with STM. The JCStress test below occasionally fails (approximately once in about 10-20 tries on my machine). zio version is 1.0.5. Scala 2.13.5.

```scala
package something

import zio.IO
import zio.stm.{ STM, ZSTM, TRef }

import org.openjdk.jcstress.annotations._
import org.openjdk.jcstress.annotations.Outcome.Outcomes
import org.openjdk.jcstress.annotations.Expect._
import org.openjdk.jcstress.infra.results.LL_Result

@JCStressTest
@State
@Description("ZSTM")
@Outcomes(Array(
  new Outcome(id = Array("Success(A), Success(A)"), expect = ACCEPTABLE, desc = "OK")
))
class ZSTMTest {

  import ZSTMTest._

  private[this] val rt =
    zio.Runtime.default

  private[this] val q: Something =
    rt.unsafeRunTask(Something.apply)

  @Actor
  def write1(r: LL_Result): Unit = {
    r.r1 = rt.unsafeRunSync(ZSTM.atomically(q.write))
  }

  @Actor
  def write2(r: LL_Result): Unit = {
    r.r2 = rt.unsafeRunSync(ZSTM.atomically(q.write))
  }
}

object ZSTMTest {

  final object Something {
    def apply: IO[Nothing, Something] = for {
      // initial value is "A":
      inner <- TRef.makeCommit("A")
      outer <- TRef.makeCommit(inner)
    } yield new Something(outer)
  }

  final class Something(outer: TRef[TRef[String]]) {

    def write: STM[Nothing, String] = {
      // new ref also contains "A":
      TRef.make("A").flatMap { fresh =>
        outer.get.flatMap { inner =>
          inner.get.flatMap { s =>
            if (s != "A") {
              // we should never read anything other than "A":
              ZSTM.die(new IllegalStateException("impossible: " + s))
            } else {
              // we write "X", but we never commit it
              // (because we replace the inner ref):
              inner.set("X") *> outer.set(fresh).as(s)
            }
          }
        }
      }
    }
  }
}
```

When it fails, JCStress reports something like this (usually a few thousand times out of a million):
```
Success(A), Failure(Traced(Die(java.lang.IllegalStateException: impossible: X),ZTrace(Id(1617362016312,2),List(SourceLocation(ZSTM.scala,zio.stm.ZSTM$,atomically,975), SourceLocation(ZSTM.scala,zio.stm.ZSTM$,atomically,974)),List(SourceLocation(ZSTMTest.scala,dev.tauri.choam.ZSTMTest,write2,34)),None)))
```
Instead of the expected:
```
Success(A), Success(A)
```

I think it should not be possible to ever read `X`, since we never commit anything other than `A`.

Interestingly, if instead of the `if (...) die else ...` I have the `else` branch unconditionally, I can't seem to observe the uncommitted read. That is, if instead of:
```scala
if (s != "A") {
  ZSTM.die(new IllegalStateException("impossible: " + s))
} else {
  inner.set("X") *> outer.set(fresh).as(s)
}
```
I simply have:
```scala
inner.set("X") *> outer.set(fresh).as(s)
```
Then the result of the transaction will always seem to be `A`. (At least I tried to run it for a while, and it never produced anything else.)

**Comment by alextoth** [comment]
I can reproduce
I see the following test cases(TC) failing from time to time: 

```
TC 2 | JVM options: [-XX:+UnlockDiagnosticVMOptions, -XX:+StressLCM, -XX:+StressGCM] Iterations: 5 Time: 1000
TC 3 | JVM options: [-XX:-TieredCompilation] Iterations: 5 Time: 1000
TC 4 | JVM options: [-XX:-TieredCompilation, -XX:+UnlockDiagnosticVMOptions, -XX:+StressLCM, -XX:+StressGCM] Iterations: 5 Time: 1000
TC 5 | JVM options: [-XX:TieredStopAtLevel=1] Iterations: 5 Time: 1000
```

The following cases are ok which is expected:
```
TC 1 | JVM options: [] Iterations: 5 Time: 1000
TC 6 | JVM options: [-Xint] Iterations: 5 Time: 1000
```

**Comment by adamgfraser** [comment]
It would be good to try running this against the `series/2.x` branch.

**Comment by alextoth** [comment]
I ran against `series/2.x`.
Same fate, maybe worse since this time I also found `TC 1` errors along with `TC 3` `TC 5` and `TC 6`.

Occurrence of errors is around 40% ( I ran 10 runs, 4 came back faulty )

You need this in your `project/plugins.sbt`

```sbt
addSbtPlugin("pl.project13.scala"                % "sbt-jcstress"                  % "0.2.0")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"                       % "0.4.0")
addSbtPlugin("pl.project13.scala"                % "sbt-jcstress"                  % "0.2.0")
```

then `sbt jcstress:run`

**Comment by jdegoes** [comment]
It is possible to read an uncommitted value in a transaction that will not succeed.

However, the conflict will be detected and the transaction will be rolled back. 

Possibly what is happening is that `die` is treated as a catastrophic error, so the transaction is not being rolled back, allowing you to leak state that you would otherwise not see.

This is probably an argument to modify `die`, but also if `die` is retried, it could lead to an infinite loop, because whatever defect caused the `die` might happen again.

It would be interesting to see if you can see this in any transaction that succeeds. If STM is working correctly, you would not be able to find such a case.

**Comment by alextoth** [comment]
@jdegoes thank you for the explanation.

Changing the test to use `ZSTM.fail(new Exception("impossible: " + s))` instead of `ZSTM.die`
and adapting to `STM[Exception, String]` and `IO[Exception, Something]`
clears the problem.

@durban I guess this can be closed.

**Comment by adamgfraser** [comment]
@alextoth Is this true on both ZIO versions?

**Comment by durban** [comment]
@alextoth Wait, but why? It's very good if `fail` behaves correctly in this case, but, as far as I can tell, `die` still does not.

Also, please note, that this transaction will not succeed _because_ it reads an uncommitted value.

**Comment by adamgfraser** [comment]
Why don't we just delete `die` from the API? The guarantee is supposed to be that you can potentially observe inconsistent state during an STM transaction but that you can never successfully commit such a transaction. Throwing errors within an STM transaction is clearly a kind of side effect just like printing the values observed within an STM transaction to the console. By exposing this operator we are essentially indicating that you can do this.

We don't have any of the other operators on STM that would allow working with untyped errors within STM in a principled way so I I'm not sure what the point is of exposing this.

**Comment by adamgfraser** [comment]
Or alternatively at least for errors using the `die` constructor they need to be captured as their own data type and interpreted like other errors.

**Comment by adamgfraser** [comment]
Submitted #4962 to fix this on the `series/2.x` branch. I think we can back port the fix to `master` with the same approach.
