### ISSUE TITLE
remove prelude -> zio-test dependency, or split non-test stuff from zio-test into a non-test library

### ISSUE THREAD

**Issue by virusdave** [zio/zio#4952]
Similar to https://github.com/zio/zio/issues/4787, there's a dependency edge between `zio-prelude` and `zio-test`, which seems incorrect.  Should it be a test dependency?  Or not exist at all perhaps?

**Comment by virusdave** [comment]
This matters because zio-magic depends on zio-prelude :'(

**Comment by virusdave** [comment]
Based on [discussion here](https://discord.com/channels/629491597070827530/630498701860929559/831201842523406336), a possible better approach would be to split functionality that lives in zio-test that is legitimately useful in non-test contexts into a non-test library.

**Comment by adamgfraser** [comment]
I think this is best addressed at the ZIO Prelude level.
