### ISSUE TITLE
Make BootstrapRuntime's platform lazy

### ISSUE THREAD

**Issue by phderome** [zio/zio#4970]
Some usage in the field seems to show that loading both `BootstrapRuntime` and `default` one in memory leads to NPE on `ZIO.scala` accessing `platform`.

From Discord's conversation on zio-users (Apr 18 2021): https://discord.com/channels/629491597070827530/630498701860929559/833355246822359040

In a multi-module project, I have two modules `A`  and  `B` that both depend on ZIO. `A` has a dependency on `B` in `build.sbt` but is not compile-dependent on `B`; it's an artificial/accidental dependency. `B` uses `zio.Runtime.default` whereas `A` uses (inconsistently) `zio.BootstrapRuntime`.
Removing `B` as a `build.sbt` dependency from `A` makes the problem of NPE go away in `ZIO.scala` and so does using consistent `zio.Runtime.default` inside `A`.

**Comment by adamgfraser** [comment]
I will take care of this.

**Comment by phderome** [comment]
```
java.lang.NullPointerException
        at zio.Runtime.unsafeRunWith(Runtime.scala:185)
        at zio.Runtime.unsafeRunSync(Runtime.scala:81)
        at zio.Runtime.unsafeRunSync$(Runtime.scala:78)

```
v1.0.3:
```
  private final def unsafeRunWith[E, A](
    zio: => ZIO[R, E, A]
  )(k: Exit[E, A] => Any): Fiber.Id => (Exit[E, A] => Any) => Unit = {
    val InitialInterruptStatus = InterruptStatus.Interruptible

    val fiberId = Fiber.newFiberId()

    val scope = ZScope.unsafeMake[Exit[E, A]]()

    val supervisor = platform.supervisor
```

**Comment by phderome** [comment]
> I will take care of this.

you fixed it already: https://github.com/zio/zio/pull/4917
My jar is 1.0.3.

**Comment by adamgfraser** [comment]
😂

**Comment by adamgfraser** [comment]
So can we close this?

**Comment by phderome** [comment]
yes.
