### ISSUE TITLE
sealed ZHub - problem with test instance

### ISSUE THREAD

**Issue by PawelJ-PL** [zio/zio#5045]
Hi,

I've found a pretty fresh PR https://github.com/zio/zio/pull/4925 (already merged). This approach makes unit tests more complicated. Normally I would create my custom implementation of `ZHub` for the test which would use `Ref` to collect published messages (to verify them later in the test). But since this change it's impossible.
Now I have to implement not nice solution like:

```scala
 for {
      internalMessages    <- Ref.make[List[InternalMessage]](List.empty)
      internalTopic       <- Hub.bounded[InternalMessage](16)
      internalMessageCollector =
        ZStream.fromHub(internalTopic).run(ZSink.foreach(message => internalMessages.update(prev => prev :+ message)))
      serviceQuery = UsersService.createUser(newUserReq)
      user                <- internalMessageCollector.raceEither(serviceQuery).rightOrFail(new RuntimeException("Stream finished to soon"))
      sentMessages        <- internalMessages.get
    } yield assert(sentMessages)(hasSameElements(List(InternalMessage.UserRegistered(...)
```

I think, It may be worth considering treating `ZHub` as a regular trait instead of sealed

**Comment by adamgfraser** [comment]
@PawelJ-PL `ZHub` was a `sealed trait` prior to that PR being merged so you wouldn't have been able to extend it even then. You can use `tapInput` to perform an effect like writing to a `Ref` for each value that is published to the hub. I am 👎 on removing the seal as I don't think the hub is meant to be extended by third party code and it creates binary compatibility issues.

**Comment by PawelJ-PL** [comment]
Solution with `contramapN` will work as fine in tests as a custom implementation based on `Ref`.

**Comment by adamgfraser** [comment]
@PawelJ-PL Awesome! Are we good to close this then? Thanks for trying out ZHub` and for raising this.

**Comment by PawelJ-PL** [comment]
Yes, I'll close issue. Thank you for suggestion.
