### ISSUE TITLE
Remove Blocking from ZEnv / environment / standard services

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5076]
There is almost never a need to use a separate blocking pool. We should just bake one global blocking pool into the application, move all the blocking operators to `ZIO.*` (and companion objects), and delete the `Blocking` service and package.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by heaven-born** [comment]
Multiple blocking pools can be useful in some cases. Let's say you have multiple DB connections and you want to have separate metrics for each of them. Having multiple blocking pools makes it possible to just instrument underlying execution services and have separate metric sets for each connection.

**Comment by adamgfraser** [comment]
Closed by #5080.
