### ISSUE TITLE
ZIO Test: Make specs more compositional

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5093]
Depends on #5092 .

The goal of this ticket is to support:

```scala
object MySpec1 extends DefaultRunnableSpec ...

object MySpec2 extends DefaultRunnableSpec...

object MySpec3 extends DefaultRunnableSpec {
  def spec = MySpec1 + MySpec2
}
```

In order to support this, we would probably have to change `Spec` from a case class to a `trait` with a `fold` method that encodes the subtypes of `SpecCase`. 

Then `DefaultRunnableSpec` and friends could implement the abstract methods of the `Spec` trait and get operators like `+` for free.

**Comment by hmemcpy** [comment]
This would also be great for creating a mega spec with shared dependencies, allowing creating "global" before/after (useful for test containers, where I'd like to start a container before any of the specs are run, and tear it down after all had finished).

**Comment by swoogles** [comment]
@adamgfraser I believe we can close this one 🙂
