### ISSUE TITLE
Relax requirement on provide

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5095]
I use ZIO as an arrow in a compiler, and I have a term of my language `const: A => Lang[Any, A]` which I translate to `ZIO[Any, E, A]`. Haha, you guess where it's heading: I cannot `provide` anything, because the compiler will raise an error. However here, I really want to provide _anything_. Not sure many people use ZIO that way, and I may have to wrap it in a function instead, but I thought I'd raise anyway.

**Comment by adamgfraser** [comment]
@regiskuckaertz The only thing that prevents this is the `NeedsEnv` warning, which is designed to prevent users from accidentally providing an environment to an effect that doesn't require one. For advanced use cases you can import `zio.NeedsEnv.needsEnv` to silence this warning.

```scala
import zio.NeedsEnv.needsEnv

ZIO.unit.provide(42) // okay
```

**Comment by regiskuckaertz** [comment]
Oh, I did not know you could do that, thanks heaps!
