### ISSUE TITLE
dimap has disappeared

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5103]
Somewhere along the way, `ZIO.dimap` has disappeared, even though it is still part of other data types API.

**Comment by adamgfraser** [comment]
I'm not sure it disappeared so much as was never there. It looks like it exists on concrete data types that take some "input" and "output" (e..g  `ZQueue`, `ZHub`, `ZRef`, `Schedule`, `ZSink`) but hasn't been defined for any effect type with respect to its environment. There is no implementation for `ZIO`, `ZManaged`, `ZSTM`, or `ZStream` for example.

It is certainly well defined, though I wonder a bit about adding another environment operator that does not really fit with the idiomatic we generally use the environment. There is also some issue with naming conflicts with data types that support implementing `dimap` in more than one way.

**Comment by domdorn** [comment]
in 1.0.10 its deprecated on `ZIO` with a note that it should be replaced with `.mapBoth`

**Comment by adamgfraser** [comment]
@domdorn I believe @regiskuckaertz was asking about `dimap` not `bimap`.

**Comment by domdorn** [comment]
doh, sorry my fault!

**Comment by adamgfraser** [comment]
Going to close this as I think this operator did not actually exist and it makes less sense with `ZEnvironment` being baked in to the environment.
