### ISSUE TITLE
add (performant) abstraction over semilattices

### ISSUE THREAD

**Issue by hochgi** [zio/zio#512]
I describe an aspect of the problem in a blog post:
https://blog.hochgi.com/2019/01/fp-ish-patterns.html?view=classic

In general, given a "join" function that is commutative and associative, we can optimize computation by re-ordering the application of that function over a sequence of elements.

here's an example to clarify what I mean:
```scala
def foo[A](as: Seq[A])(f: (A,A) => A): A 
```

This can obviously be implemented as `a.reduce(f)`, but it means the order of computation cannot be changed. Think about the [matrix chain multiplication problem](https://en.wikipedia.org/wiki/Matrix_chain_multiplication) for instance.

(actually, matrix multiplication is associative, but not commutative, so not a 1:1 example, but you get the idea, and maybe there is a way to define an abstraction for that as well)

disclaimer: I'm not very familiar with scalaz. this issue was suggested to me by @jdegoes, and I will be happy to provide any further details or a more detailed example.

**Comment by iravid** [comment]
Closing as this is out-of-scope for ZIO
