### ISSUE TITLE
catchAll doesn't catch all!

### ISSUE THREAD

**Issue by immanol** [zio/zio#5123]
It seems if we use an impure function which by mistake throws an exception inside a map part of a for comprehensions, the zio can't catch the exception. In the below code the `y = Integer.parseInt(yString)` throws an exception which is not catched in the `myApp.catchAll(e => putStrLn(s"Error: $e"))`.
I don't see this behaviour for example in Cats-effects and at least I can log my exception when I'm using Cats-Effects.
I understand that we shouldn't write such an error-prone code like `Integer.parseInt(xString)` but sometimes it is inevitable and a developer by mistake could write a method that could throw an exception and use that in a map.
`
object ZIOMain extends zio.App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = myApp.catchAll(e => putStrLn(s"Error: $e")).exitCode

  val xOrError: Either[Throwable, String] = Right("1")
  val yOrError: Either[Throwable, String] = Right("2#")

  val myApp: ZIO[Any, Throwable, Int] = for{
    xString <- ZIO.fromEither(xOrError)
    yString <- ZIO.fromEither(yOrError)
    x = Integer.parseInt(xString)
    y = Integer.parseInt(yString)
  }yield x * y
}
`

**Comment by luis3m** [comment]
@immanol as you said parseInt may fail so it must be wrap with ZIO. If you don't then it's a "defect" in your application and to catch those you'd need `catchAllCause` instead.

Hope that helps.

**Comment by immanol** [comment]
Thanks for your reply
