### ISSUE TITLE
chunkN / bufferTumblin / sliding for StreamChunk API

### ISSUE THREAD

**Issue by lemastero** [zio/zio#513]
I did not notice capability to split the stream into parallel n chunks like here: https://github.com/monix/streaming-benchmarks/blob/master/src/main/scala/streaming/benchmarks/ChunkedEvalFilterMapSumBenchmark.scala#L116

ZIO benchmarks: https://github.com/scalaz/scalaz-zio/blob/master/benchmarks/src/main/scala/scalaz/zio/StreamBenchmarks.scala#L64 create nested structure before the stream is created. This seems like a workaround for missing feature.

Is there a place for chunkN / bufferTumblin / sliding for StreamChunk API? Maybe it can be achived using existing API?

**Comment by YuvalItzchakov** [comment]
I'd like to work on this one :)

**Comment by iravid** [comment]
@saraiva132 Closing this issue as Rafael will open subsequent more accurate issues.
