### ISSUE TITLE
Move logic of retrying and repetition to Clock service

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5132]
Without changing the current API, we should move the retrying, repetition, and scheduling logic (embodied by such methods as repeat, repeatOrElse, etc.) into the `Clock` service.

This will solve a common anti-pattern, whereby middleware in application that uses `Clock` via this retrying, repetition, or scheduling logic (but must, itself, provide `R = Any` in its service definition) must `provideLayer` clock on every method invocation.

After this change, the API will not change but the `Clock` trait will become bigger, having more methods that implement the raw scheduling logic.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
Thank you!
