### ISSUE TITLE
Missing sjsir files in Scala 3 jars for Scala.js 

### ISSUE THREAD

**Issue by MI3Guy** [zio/zio#5152]
From what I can see the sjsir files are missing. For example, the file zio_sjs1_3-1.0.8.jar contains class files and tasty files, but not sjsir. The result of this is that, while you can compile code using ZIO on Scala 3/Scala.js, it will not link. This is also the case for zio-test (and interop-cats which is a separate repository).

**Comment by adamgfraser** [comment]
Thanks for reporting! We are investigating and working on resolving but if anyone has a solution for this PRs welcome.
