### ISSUE TITLE
ZIO 2.0 Name Changes

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5221]
We should rename the old methods to the new names, but also, create the old methods that forward to the new methods, and use the `@deprecated` annotation, marking 2.0.0 as the deprecation version.

 - `ZIO.effect` => `ZIO.attempt`
 - `ZIO.effectTotal` => `ZIO.succeed`
 - `ZIO.effectSuspend` => `ZIO.suspend`
 - `ZIO.effectSuspendTotal` => `ZIO.suspendSucceed`
 - `ZIO.effectSuspendWith` => `ZIO.suspendWith`
 - `ZIO.effectSuspendTotalWith` => `ZIO.suspendSucceedWith`
 - `ZIO#run` => `ZIO#exit`
 - `ZManaged.make` => `ZManaged.bracket`
 - `ZIO#ensuring_` => `ZIO.ensuring`
 - `ZIO#ensuring` => `ZIO.ensuringWith`
 - `ZIO#toManaged_` => `ZIO#toManaged`
 - `ZIO#toManaged` => `ZIO#toManagedWith` / `ZIO#bracketManaged`
 - `putStrLn` => `printLine`
 - `getStrLn` => `readLine`
 
More generally, there is an intention to replace all `_` methods in ZIO 2.0 (`bracket_`, etc.). This naming convention stems from Haskell and has no analogues in the JVM.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
Awesome, thank you! There will be variations of some of these methods (e.g. ZIO#run).

**Comment by jdegoes** [comment]
For posterity, @kitlangton also suggested `ZManaged` => `ZResource` (with pros & cons).

**Comment by kitlangton** [comment]
Also, possibly:

`environment`
`access` -> `environmentWith`
`accessM` -> `environmentWithM`

to be in line with

`service`
`serviceWith` (Though there is no `serviceWithM` variant, to encourage the recommended module pattern. `serviceWith` expects a ZIO to be returned)

**Comment by adamgfraser** [comment]
Closed by #5229.
