### ISSUE TITLE
ZIO 2.0 - Improve compositionality of blocking interrupt

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5225]
Currently, we have variations of effect blocking, one which will not attempt to translate ZIO interruption into thread interruption, and one which will translate ZIO interruption into thread interruption.

Rather than having two separate versions, we can instead improve the compositionality of a single version, by making it aware of the regional interruption status.

The goal is to make this code have the same effect as `zio.blocking.effectBlockingInterruptible`:

```scala
ZIO.interruptible(ZIO.attemptBlocking(...))
```

Now it is difficult to do this right now because `InterruptStatus` is either `Interruptible` or `Uninterruptible`. If we have a `Root` or `Default`, then we can now detect the difference from "implicitly interruptible" and "explicitly interruptible", which would allow us to collapse the 2 versions of `effectBlocking` down to a single version.

**Comment by adamgfraser** [comment]
Are we going to have an issue with punching a whole in uninterruptible regions if we use `interruptible` like this?

**Comment by jdegoes** [comment]
@adamgfraser You're right. Will close. Guess we're stuck with multiple variations for now.
