### ISSUE TITLE
ZIO 2.0: By-name parameter check

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5261]
This ticket is to review all parameters for all methods that return a ZIO effect, and ensure they are by-name; and to, if a by-name parameter is referenced more than once, to put it into a local `lazy val` to ensure it is not evaluated more than once.

This will improve the ability of ZIO to deal with "accidentally embedded side-effects", which are quite common in practice.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
Thank you! 🙏
