### ISSUE TITLE
ZIO 2.0: Composable zips

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5267]
The goal of this ticket is to ensure that when zipping together different effects:

1. Tuples are not nested.
2. Units do not contribute to output.

For example:

```scala
(x1: Task[Int]) <*> (x2: Task[Unit]) <*> (x3: Task[String]) <*> (x4: Task[Boolean]) : Task[(Int, String, Boolean)]
```

**Comment by adamgfraser** [comment]
Will do.

**Comment by heaven-born** [comment]
probably item 2  can be done for `race` as well. Instead  of `raceLeft/Right` as I proposed in #5264
