### ISSUE TITLE
Don't suspend side-effects in function closures

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio#527]
some of our interop methods look like this
```scala
def fromFuture[A](ec: ExecutionContext)(ftr: () => Future[A]): IO[Throwable, A] =
def fromFutureIO[A, E >: Throwable](ec: ExecutionContext)(ftrio: IO[E, Future[A]]): IO[E, A] =
def fromFutureAction[A](ftr: ExecutionContext => Future[A]): IO[Throwable, A] =
```

but we shouldn't be suspending side-effects in function closures (`() => Future[A]`). thus the signatures should be (we might need to remove some methods):

```scala
def fromFuture[A, E >: Throwable](ec: ExecutionContext)(ftrio: IO[E, Future[A]]): IO[E, A] =
def fromFuture[A](ftr: ExecutionContext => IO[Future[A]]): IO[Throwable, A] =
```

**Comment by jdegoes** [comment]
@sideeffffect Is this done?

**Comment by sideeffffect** [comment]
@jdegoes
not done yet, there's still one file with definitions like mentioned above
but something happened... methods like `fromFuture` disappeared from `interop-future`. how can I convert `scala.concurrent.Future` to `IO` now?

@Vilkina
the only remaining file is:
```
src/main/scala/scalaz/zio/interop/javaconcurrent.scala
```

**Comment by jdegoes** [comment]
@sideeffffect It's built into core now, just do `ZIO.fromFuture`, `ZIO#toFuture`, and the Fiber methods.

**Comment by sideeffffect** [comment]
@jdegoes oh I see!

@Vilkina have a look at
 * `/interop-java/shared/src/main/scala/scalaz/zio/interop/javaconcurrent.scala`: all methods with names`fromFutureJava`, `fromCompletionStage`
 * `/core/shared/src/main/scala/scalaz/zio/Fiber.scala`: `fromFuture`
 * `/core/shared/src/main/scala/scalaz/zio/ZIO.scala`: `fromFuture`

since you'll be changing `javaconcurrent`, would you mind moving it from `shared` to `jvm`?
```
/interop-java/shared/src/main/scala/scalaz/zio/interop/javaconcurrent.scala => /interop-java/jvm/src/main/scala/scalaz/zio/interop/javaconcurrent.scala
```

**Comment by Vilkina** [comment]
@sideeffffect I'll try to look today.

**Comment by Vilkina** [comment]
> since you'll be changing `javaconcurrent`, would you mind moving it from `shared` to `jvm`?
> 
> ```
> /interop-java/shared/src/main/scala/scalaz/zio/interop/javaconcurrent.scala => /interop-java/jvm/src/main/scala/scalaz/zio/interop/javaconcurrent.scala
> ```
@sideeffffect , do you mean copy then delete "javaconcurrent.scala" from /interop-java/shared/src/main/scala/scalaz/zio/interop/javaconcurrent.scala and move to /interop-java/jvm/src/main/scala/scalaz/zio/interop/javaconcurrent.scala ?

**Comment by sideeffffect** [comment]
yes 👍

**Comment by Vilkina** [comment]
@sideeffffect , can you help me to solve this error? 
[https://travis-ci.org/scalaz/scalaz-zio/jobs/505836577](url) 

[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:42:47: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     def ftr: Future[Unit] = CompletableFuture.supplyAsync(evaluated = true)
[error]                                               ^
[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:49:41: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     IO.fromFutureJava(CompletableFuture.supplyAsync(evaluated = true))
[error]                                         ^
[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:72:55: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     def cs: CompletionStage[Unit] = CompletableFuture.supplyAsync(evaluated = true)
[error]                                                       ^
[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:79:46: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     IO.fromCompletionStage(CompletableFuture.supplyAsync(evaluated = true))
[error]                                              ^
[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:131:47: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     def ftr: Future[Unit] = CompletableFuture.supplyAsync(evaluated = true)
[error]                                               ^
[error] /home/travis/build/scalaz/scalaz-zio/interop-java/jvm/src/test/scala/scalaz/zio/interop/javaconcurrentSpec.scala:138:44: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (evaluated: Boolean)
[error]     Fiber.fromFutureJava(CompletableFuture.supplyAsync(evaluated = true))
[error]                                            ^
[error] 6 errors found

**Comment by Vilkina** [comment]
@sideeffffect , I'll do two different PR's. First with microsite changes, second is #527.
