### ISSUE TITLE
[zio-test] Inconsistent behaviour of checkM and after/before aspects

### ISSUE THREAD

**Issue by poslegm** [zio/zio#5285]
`after`/`before` aspects doesn't evaluate on `checkM` iterations.

Example:

```scala
var runCount = 0
var afterCount = 0

suite("test aspects with checkM")(
  testM("example") {
    checkNM(10)(zio.test.Gen.anyInt) { int =>
      for {
        _ <- ZIO.effectTotal(runCount += 1)
      } yield assertTrue(runCount == afterCount) && assertTrue(int.toString.toInt == int)
    }
  }
)  @@ after(ZIO.effectTotal(afterCount += 1))
```

Output:
```
32 was not equal to 0
```

Is there a possibility to run `after`/`before` aspect action on **every** `checkM` iteration?

**Comment by poslegm** [comment]
Related: https://github.com/zio/zio/issues/4007

**Comment by adamgfraser** [comment]
@poslegm Supporting this behavior with test aspects would be a significant change. Property based tests create a single "test" that can be modified by test aspects. Iterations of a property based test are not themselves tests. For example, what would it mean to apply a label with `tag` to an iteration of a property based test?)

For the specific case of using resources within an iteration of a property based test you can use a `ZManaged` and the `useNow` operator or `ensuring` if you only need to do something after a test.

This will also be nicer with generalized aspects in ZIO 2.0 because then you will be able to write `@@ after(???)` directly after the assertion in your property based test.

**Comment by jdegoes** [comment]
@adamgfraser What if we expanded a `check` into a dynamic suite with `N` tests inside them?

The reason why I am thinking about this:

1. A property test is like a lot of little unit tests all strung together. It's a useful mental model, anyway.
2. If the individual tests are separate initially, you could imagine a `ZSpec#consolidate` operator that would consolidate all tests into a single test. However, if the checks are a single test, then there can exist no corresponding operator to break them apart. Orthogonality suggests, therefore, the better design is separate tests.

I think what would be necessary to make this happen is unlabeled collections of tests, which is something I've wanted for a while.

What else might be required??

**Comment by adamgfraser** [comment]
@jdegoes Yes, I was thinking about that as well. It definitely fits in with the ongoing work we are doing on binary composition of tests. I think what that suggests is a model where individual "test" failures aren't reported separately but instead are rolled up to the first level of "labeling". So then you could think of a property based tests as a (dynamically generated) collection of tests with a single label. I think that generally makes sense but probably requires relatively significant changes in the structure of specs, test aspects, and how they are reported. It also requires thinking about what we do when there is not a label to "roll up" to.

**Comment by adamgfraser** [comment]
The other issue here is that this would be a significant breaking change. Currently if you do `provideLayer` or  `around` it will provide the layer to or perform the effect around the whole property based test, which makes sense with the conceptualization of a property based test as a "single test".  With this change those operators would do the same thing for each iteration of the property based tests, which while well defined is very different behavior.

**Comment by adamgfraser** [comment]
Going to close this as while the idea of expanding property based tests into a suite of tests is interesting there are significant differences that justify modeling them as separate data types. For example individual iterations of a property based test are not rendered and a timeout would normally be expected to apply to an entire property based test and not each iteration. Thanks for raising though!
