### ISSUE TITLE
Adding serviceWithManaged to ZManaged contructors

### ISSUE THREAD

**Issue by remiguittaut** [zio/zio#5288]
`ZIO` and `ZManaged` companion objects have very convenient constructors `serviceWith` which more or less replace the previous `accessM` to account for the new module recommendation, i.e. dropping the type aliases `type ServiceName = Has[ServiceName.Service]` and using a more flattened convention.

`serviceWith` allows to access the service from the environment to execute an effectual service member, effectively duplicating the behavior of `accessM` without dealing with `_.get`, in the function argument, because we're now dealing directly with a service instance, unwrapped from its `Has[_]`. There is an `accessManaged` overload, which has the same behavior as `accessM`, but this time to deal with service members not only returning an effectual computation, but a managed one.

The same overload of `serviceWith` seems to be missing, when dealing with managed services members in the module pattern "2.0".

**Comment by adamgfraser** [comment]
Agree this makes sense.
