### ISSUE TITLE
ZIO 2.0: Make Schedule serializable

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5337]
The current encoding of Schedule makes state implicit, which cleans up the implementation for operators and constructors, but means there is not a clear path to making schedule state serializable.

By reverting to a more "unfold" like definition, e.g.:

```scala
trait Schedule[-Env, -In, +Out] {
  type State
  def initial: State
  def step(OffsetDateTime, In, State): ZIO[Env, Nothing, (State, Out, Schedule.Decision)]
}
...
sealed trait Decision { ... }
object Decision {
  case object Done extends Decision
  final case class Continue(
    interval: Interval
  ) extends Decision
}
```

We make it possible to think about serialization. Now, updating the logic for all the schedule operators and constructors is not trivial, but it will always be possible since the two ways to encode schedules are equivalent (implicit vs explicit state).

In order to handle serialization "from the outside", we would need to type every constructor for schedule to return a more specific type. The first step in this process would be introducing a type alias for the more specific type, inside the `Schedule` companion object:

```scala
object Schedule {
  type WithState[State0, -In0, +Out0] = Schedule[In0, Out0] { type State = State0 }
}
```

The second step would be changing any return type in any method inside the `Schedule` trait or inside the `Schedule` companion object from `Schedule[A, B]` to `Schedule.WithState[S, A, B]` for some state type `S`.

Then, with all methods and constructors precisely typed, serialization can happen in user-land code according to whatever method the user desires (a `ZIO Schema` integration would be ideal).

Probably we would modify the `Driver` to expose the state of the schedule to facilitate serialization in-progress.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by iravid** [comment]
😂 we've come a full circle

**Comment by jdegoes** [comment]
@iravid Sort of. The other one was the worst of both worlds (explicit state but no way to save / restore it, also a significantly complicated / irregular encoding with effectful first state).
