### ISSUE TITLE
ZIO 2.0: Add ZLayer#flatMap

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5339]
Mainly so people can choose what layer to make based on data read from configuration.

**Comment by adamgfraser** [comment]
Will add.

**Comment by adamgfraser** [comment]
You don't think this can be addressed by having layers accept configuration data as an input type?

**Comment by jdegoes** [comment]
They want to branch on the configuration data, even if it's ready from a layer. 

We can already do flat map without changing ZLayer constructors (of course, the inner part becomes opaque from a graph analysis POV).

**Comment by adamgfraser** [comment]
Yes agree it is not a problem from an implementation standpoint. Could potentially address through more of a arrow choice concept but that is not as dynamic and admittedly we have not done a whole lot with the ability to statically analyze the graph.

**Comment by jdegoes** [comment]
A less powerful version would be `Map[A, ZLayer[B]]`, which is a "switch" statement that tests for equality. It allows analysis but only finite enumerated choices. It would probably be sufficient but at the same time `for` comprehensions would be easier to use and we aren't yet doing any static analysis (plus you can already do flatMap yourself if you want).

**Comment by adamgfraser** [comment]
Yeah I think we just do it.
