### ISSUE TITLE
ZIO 2.0: ClockLive (and others) should not be private[zio]

### ISSUE THREAD

**Issue by notxcain** [zio/zio#5342]
Sometimes (in legacy apps) it's handy to be able to access instances without dealing with `ZLayer`.

**Comment by adamgfraser** [comment]
@notxcain Hi! Thanks for raising! These actually already available as `Clock.Service.live`. There is also `ZEnv.Services.live` for accessing all of the services in the default environment outside the context of a layer.

**Comment by adamgfraser** [comment]
Ah I see you changed the title to be about the `series/2.x` branch. Yes I think those variants got removed in the refactoring to remove the additional package objects for each of the services. Will add those back. For now you can use `ZEnv.Services.live`.

**Comment by notxcain** [comment]
@adamgfraser thank you!
