### ISSUE TITLE
ZIO 2.0: add .toManaged_ as deprecated method

### ISSUE THREAD

**Issue by domdorn** [zio/zio#5345]
I'm just trying to migrating a small project from 1.0.9 to 2.0.0-M1. While most methods that need changing are deprecated and have a corresponding message on what to do, the `.toManaged_` got removed without a proper message leading to compile errors. I think it might be a better user experience if we'd keep that one with a proper message at least for a few minor versions so people's code still compiles and they see what they have to do.

**Comment by adamgfraser** [comment]
Yeah I think the issue there is we can't do one for `toManaged` because we are both deprecating the old one and adding a new one but can do for `toManaged_`.
