### ISSUE TITLE
Illegall reflective access in jvm/PlatformSpecific

### ISSUE THREAD

**Issue by erdeszt** [zio/zio#5353]
I get a warning from a zio app about illegal reflective access:
```
WARNING: Illegal reflective access by zio.internal.PlatformSpecific (file:dev.zio.zio_2.13-1.0.9.jar) to field java.lang.Throwable.cause
```
It's happening here: https://github.com/zio/zio/blob/d79dcfcec4e0af21a3f21aad32be0995e5972a06/core/jvm/src/main/scala/zio/internal/PlatformSpecific.scala#L155

[Oracle recommends](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B) that I contact the library authors when I run into this(as this access might get disabled in a future JDK release) so I just wanted to poke you about it.

**Comment by adamgfraser** [comment]
@erdeszt Thank you! Will take a look!
