### ISSUE TITLE
Remove Sink.Step in favor of methods on Sink

### ISSUE THREAD

**Issue by iravid** [zio/zio#538]
We can (probably) do away with Sink.Step by adding `def leftover(s: State): Chunk[A0]` and `def cont(s: State): Boolean` to Sink.

**Comment by vasilmkd** [comment]
I got pretty familiar with Step when working on throttling. Should I give this a shot, if it's still something worth looking into?

**Comment by iravid** [comment]
It'd definitely save allocations at the cost of making some combinators harder to write. I'd try and write a parallel implementation of `Sink`, a few sink combinators and `Stream.{run,transduce}` to see how ergonomic it is.

**Comment by vasilmkd** [comment]
Continuing work on stepless sink.

**Comment by vasilmkd** [comment]
https://github.com/vasilmkd/zio/tree/zsink-stepless

Whole migration done. Just worried it might be too much for a single PR.

**Comment by iravid** [comment]
We'll deal with it :-) Feel free to open a PR
