### ISSUE TITLE
ZIO 2.0: Integrate support for `HasMany` (WIP)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5475]
Currently, ZIO's type-indexed map has the form, `Has[X] with Has[Y] with Has[Z]`.

This is convenient in cases where a type uniquely identifies a service. However, there are many cases where a type alone is not sufficient, and some additional key is necessary to locate a value stored in the environment. Currently the number one solution is to introduce a `Map` into the environment, e.g. `Has[Map[K, A]]`, but this comes without the niceties of non-keyed services.

To deal with such cases, it may be possible to introduce a subtype to `Has` that is designed to allow access by key, hypothetically named `HasMany[K, A]`. A `HasMany[K, A]` might be a `Has[_ <: Map[K, A]]` or similar. 

Type signatures for type-indexed maps would then be in the form, `Has[X] with HasMany[K, Y] with Has[Z]`. 

New combinators in the mold of `ZIO.service` (`ZIO.serviceAt[A](k)`, or possibly `lookup` or `getAt`?) could allow easy but fallible access to keyed services (fallible because it might not exist in the map).

**Comment by adamgfraser** [comment]
I will work on this.

**Comment by adamgfraser** [comment]
Closed by #5481.
