### ISSUE TITLE
ZIO 2.0: Ensure consistent use of *Cause variants

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5483]
Currently we have some variation in the *Cause variants, including, on the one hand, a convention of adding the `Cause` postfix immediately following the `Error` postfix, e.g.:

 - `ZIO.failCause`
 - `ZIO.mapErrorCause`

And on the other hand, dropping `Error` entirely and just using the `Cause` suffix directly:

 - `ZIO.tapCause` (`ZIO.tapError`)

We should standardize on which form we want to adopt and drop the other one, leaving deprecations until the 2.0 release.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
🙏
