### ISSUE TITLE
ZIO 2.0: Platform improvements

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5501]
`zio.internal.Platform` could stand a number of improvements in ZIO 2.0:

1. Rename `Platform` => `RuntimeConfig`.
2. Rename `PlatformAspect` => `RuntimeConfigAspect`.
3. Move `RuntimeConfig` **and** `RuntimeConfigAspect` to `zio`, rather than `zio.internal`.
4. Move `Platform.OS` / `Platform.os` into `System` companion object, because it is logically more related to `System` than `RuntimeConfig`.
5. Introduce several `RuntimeConfigAspect` for modifying `RuntimeConfig`, inside the companion object of `RuntimeConfigAspect` (currently there is only `identity`). These could include:
    - `RuntimeConfigAspect.addSupervisor`
    - `RuntimeConfigAspect.addReportFailure`
    - `RuntimeConfigAspect.addReportFatal`
    - `RuntimeConfigAspect.addLogger`
    - `RuntimeConfigAspect.setTracing`
    - `RuntimeConfigAspect.setExecutor`
    - `RuntimeConfigAspect.setBlockingExecutor`
    The `add` methods would be additive: they would not replace, but rather, compose the existing fields inside the `RuntimeConfig`. The `set` methods would replace the existing fields.

Inside the `zio.internal` package object, deprecated `type` and `val` aliases (`type Platform = _root_.zio.RuntimeConfig; val Platform = _root_.zio.RuntimeConfig`) can be added to ease migration from ZIO 1.x to ZIO 2.x.

An open question is whether to push the `unsafe` prefix into `RuntimeConfig` since this will be top-level visible package that users would be expected to see and interact with as part of configuring ZIO applications.

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
@adamgfraser Thank you! 🙏
