### ISSUE TITLE
ZIO 2.0: Leverage logging for reportFailure

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5503]
Currently, default `reportFailure` in Platform (/RuntimeConfig) logs to console. This is not desirable. Instead, anytime we have a failure, we should use the logger inside Platform (/RuntimeConfig), using the same parameters as a user would trigger, if the user called `ZIO.logCause`.

This will allow us to delete `reportFailure` and give the user a uniform way of handling errors.

Ideally, at the same time, we should rename `ZIO.logCause` to `ZIO.logErrorCause` to be consistent with the new naming convention.

**Comment by adamgfraser** [comment]
Will do this.

**Comment by jdegoes** [comment]
🙏
