### ISSUE TITLE
ZIO 2.0: Rename / move zio.Fiber.Id => zio.FiberId

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5511]
Rather than hiding the `Id` data type inside the companion object of `Fiber`, which is non-standard, we should pull it out into the top-level package (renaming to `FiberId`), leaving behind `type` / `val` aliases in the companion object that are deprecated for 2.0.

**Comment by adamgfraser** [comment]
Will do.

**Comment by jdegoes** [comment]
Thank you! 🙏
