### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/reflect/internal/Names$Name starting from zio 1.0.5

### ISSUE THREAD

**Issue by nryanov** [zio/zio#5528]
Not sure about reasons but in some cases i got an error:

<details>
  <summary>stacktrace</summary>
 
- test
  - test
    Fiber failed.
    An unchecked error was produced.
    java.lang.NoClassDefFoundError: scala/reflect/internal/Names$Name
    	at experiments.ZioTest2$anon$genericOptionPrinter$macro$14$1.inst$macro$7$lzycompute(ZioTest2.scala:13)
    	at experiments.ZioTest2$anon$genericOptionPrinter$macro$14$1.inst$macro$7(ZioTest2.scala:13)
    	at experiments.ZioTest2$.$anonfun$test$1(ZioTest2.scala:13)
    	at zio.ZIO$.$anonfun$effectSuspendTotal$1(ZIO.scala:2687)
    	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:582)
    	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:769)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.Names$Name
    	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
    	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    	... 9 more
    
    Fiber:Id(1630875756638,60) was supposed to continue to:
      a future continuation at zio.test.package$ZTest$.apply(package.scala:110)
    
    Fiber:Id(1630875756638,60) execution trace:
      at zio.ZIO$.effectSuspendTotal(ZIO.scala:2687)
    
    Fiber:Id(1630875756638,60) was spawned by:
    
    Fiber:Id(1630875756248,31) was supposed to continue to:
      a future continuation at zio.ZIO.run(ZIO.scala:1672)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
      a future continuation at zio.ZIO.run(ZIO.scala:1672)
      a future continuation at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:373)
      a future continuation at zio.test.package$Annotations$$anon$1.withAnnotation(package.scala:639)
      a future continuation at zio.ZIO.run(ZIO.scala:1672)
      a future continuation at zio.ZIO$BracketRelease_.apply(ZIO.scala:4155)
      a future continuation at zio.FiberRef.locally(FiberRef.scala:96)
      a future continuation at zio.ZIO.run(ZIO.scala:1672)
      a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
    
    Fiber:Id(1630875756248,31) execution trace:
      at zio.ZIO.bracket_(ZIO.scala:256)
      at zio.internal.FiberContext.evaluateNow(FiberContext.scala:614)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
      at zio.Supervisor$.fibersIn(Supervisor.scala:170)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:374)
      at zio.ZIO$TapFn.apply(ZIO.scala:4219)
      at zio.test.package$Annotations$.annotate(package.scala:612)
      at zio.test.TestAspect$$anon$16.perTest(TestAspect.scala:364)
      at zio.ZRef$.make(ZRef.scala:756)
      at zio.ZIO$BracketRelease_.apply(ZIO.scala:4155)
    
    Fiber:Id(1630875756248,31) was spawned by:
    
    Fiber:Id(1630875753677,0) was supposed to continue to:
      a future continuation at zio.ZIO$.foreach(ZIO.scala:2861)
      a future continuation at zio.ZIO.zipWith(ZIO.scala:2182)
      a future continuation at zio.ZIO$.foreach(ZIO.scala:2862)
      a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3058)
      a future continuation at zio.ZIO$.foreachPar_(ZIO.scala:3058)
      a future continuation at zio.ZIO$.foreachParN(ZIO.scala:3097)
      a future continuation at zio.ZIO.refailWithTrace(ZIO.scala:1426)
      a future continuation at zio.ZManaged$.foreachParN(ZManaged.scala:1713)
      a future continuation at zio.ZManaged.mapM(ZManaged.scala:484)
      a future continuation at zio.ZIO.run(ZIO.scala:1672)
    
    Fiber:Id(1630875753677,0) execution trace:
      at zio.ZIO.zipWith(ZIO.scala:2182)
      at zio.ZIO$.foreach(ZIO.scala:2861)
      at zio.ZIO.zipWith(ZIO.scala:2182)
      at zio.ZIO$.foreach(ZIO.scala:2861)
      at zio.ZIO.zipWith(ZIO.scala:2182)
      at zio.ZIO$.foreach(ZIO.scala:2860)
      at zio.ZIO$.foreachPar_(ZIO.scala:3023)
      at zio.ZIO$.foreachPar_(ZIO.scala:3023)
      at zio.ZRef$.make(ZRef.scala:756)
      at zio.ZIO$.foreachPar_(ZIO.scala:3023)
    
    Fiber:Id(1630875753677,0) was spawned by: <empty trace>
Ran 1 test in 1 s 786 ms: 0 succeeded, 0 ignored, 1 failed
- test
  - test

</details>

zio version: `>= 1.0.5`
scala version: `2.12.13`

If scala `2.13.x` or zio `<= 1.0.4` is used then test completes successfully.

`build.sbt`:
```
version := "0.1"

//scalaVersion := "2.13.6"
scalaVersion := "2.12.13"

//val zioVersion = "1.0.11"
val zioVersion = "1.0.5"
//val zioVersion = "1.0.4" 
//val zioVersion = "1.0.3" 
val shapelessVersion = "2.3.7"

libraryDependencies ++= Seq(
  "com.chuusai" %% "shapeless" % shapelessVersion,
  "dev.zio" %% "zio-streams" % zioVersion,
  "dev.zio" %% "zio-test" % zioVersion % Test,
  "dev.zio" %% "zio-test-sbt" % zioVersion % Test
)

testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework")
```

I get this error in project which uses `shapeless` so i tried to make a small but reproducible example:
<details>
  <summary>code</summary>

`test`:
```
import experiments.AutoValuePrinter._

object ZioTest2 extends DefaultRunnableSpec {
  final case class A(f1: Int, f2: Long, f3: String)

  val test = testM("test") {
    val value: Option[A] = Some(A(1, 2L, "3"))
    val optS = ValuePrinter[Option[A]]

    for {
      _ <- ZIO.effectTotal(println("Start"))
      _ <- ZIO.effectTotal(println(optS.print(value)))
      _ <- ZIO.effectTotal(println("End"))
    } yield assertCompletes
  }

  override def spec: ZSpec[_root_.zio.test.environment.TestEnvironment, Any] =
    suite("test") {
      test
    }
}
```

```
trait ValuePrinter[A] {
  def print(v: A): String
}

object ValuePrinter {
  def apply[A](implicit inst: ValuePrinter[A]): inst.type = inst

  implicit val intPrinter: ValuePrinter[Int] = (v: Int) => s"[int] $v"
  implicit val longPrinter: ValuePrinter[Long] = (v: Long) => s"[long] $v"
  implicit val stringPrinter: ValuePrinter[String] = (v: String) => s"[string] $v"

  implicit def fromOption[A](implicit inst: ValuePrinter[A]): ValuePrinter[Option[A]] = new ValuePrinter[Option[A]] {
    override def print(v: Option[A]): String = {
      val str = v.map(inst.print)
      s"[option] $str"
    }
  }
}
```

```
import shapeless._
import shapeless.labelled._

object AutoValuePrinter extends LowPriorityValuePrinter

trait LowPriorityValuePrinter extends LowestPriorityValuePrinter {
  implicit def genericPrinter[A, H <: HList](implicit
    gen: LabelledGeneric.Aux[A, H],
    hPrinter: Lazy[ValuePrinter[H]]
  ): ValuePrinter[A] = (v: A) => hPrinter.value.print(gen.to(v))

  implicit val hnilPrinter: ValuePrinter[HNil] = (v: HNil) => "[hnil]"

  implicit def hlistPrinter[K <: Symbol, H, T <: HList](implicit
    hPrinter: Lazy[ValuePrinter[H]],
    tPrinter: Lazy[ValuePrinter[T]]
  ): ValuePrinter[FieldType[K, H] :: T] = { case h :: t =>
    s""" 
         |{
         |  ${hPrinter.value.print(h)}
         |  ${tPrinter.value.print(t)}
         |}
         |""".stripMargin
  }
}

trait LowestPriorityValuePrinter {
  implicit def genericOptionPrinter[A, H <: HList](implicit
    gen: LabelledGeneric.Aux[A, H],
    hPrinter: Lazy[ValuePrinter[Option[H]]]
  ): ValuePrinter[Option[A]] = new ValuePrinter[Option[A]] {

    override def print(v: Option[A]): String = v match {
      case v @ Some(_) => s"[option] Some(${hPrinter.value.print(v.map(gen.to))})"
      case None        => "[option] None"
    }

  }

  implicit val hnilOptionPrinter: ValuePrinter[Option[HNil]] = new ValuePrinter[Option[HNil]] {

    override def print(v: Option[HNil]): String = "[option] None"
  }

  implicit def hlistOptionPrinter1[K <: Symbol, H, T <: HList](implicit
    hPrinter: Lazy[ValuePrinter[Option[H]]],
    tPrinter: Lazy[ValuePrinter[Option[T]]],
    notOption: H <:!< Option[Z] forSome { type Z }
  ): ValuePrinter[Option[FieldType[K, H] :: T]] = new ValuePrinter[Option[FieldType[K, H] :: T]] {

    override def print(v: Option[FieldType[K, H] :: T]): String = {
      def split[A](v: Option[H :: T])(f: (Option[H], Option[T]) => A): A = v.fold(f(None, None)) { case h :: t =>
        f(Some(h), Some(t))
      }

      split(v) { case (head, tail) =>
        val printedHead: String = hPrinter.value.print(head)
        val printedTail: String = tPrinter.value.print(tail)

        s"""
           |[option] Some(
           |$printedHead
           |$printedTail
           |)
           |""".stripMargin
      }
    }

  }

  implicit def hlistOptionPrinter2[K <: Symbol, H, T <: HList](implicit
    hPrinter: Lazy[ValuePrinter[Option[H]]],
    tPrinter: Lazy[ValuePrinter[Option[T]]]
  ): ValuePrinter[Option[FieldType[K, Option[H]] :: T]] =
    new ValuePrinter[Option[FieldType[K, Option[H]] :: T]] {

      override def print(v: Option[FieldType[K, Option[H]] :: T]): String = {
        def split[A](v: Option[Option[H] :: T])(f: (Option[H], Option[T]) => A): A =
          v.fold(f(None, None)) { case h :: t => f(h, Some(t)) }

        split(v) { case (head, tail) =>
          val printedHead: String = hPrinter.value.print(head)
          val printedTail: String = tPrinter.value.print(tail)

          s"""
             |[option] Some(
             |$printedHead
             |$printedTail
             |)
             |""".stripMargin
        }
      }
    }
}
```

</details>

**Comment by adamgfraser** [comment]
@nryanov Can you try to add an explicit dependency on `scala.reflect`? I have a feeling this is being driven by inconsistent versions between the two libraries.

**Comment by nryanov** [comment]
@adamgfraser thank you, it helped. I'll close an issue because it seems that it's not directly related with zio
