### ISSUE TITLE
Create .whenOption operator

### ISSUE THREAD

**Issue by domdorn** [zio/zio#5534]
It would be great if we'd have a `.whenOption` operator, that returns a `Option[A]` when applied to a  `ZIO[_,_,A]` that is `Some(A)` when the effect was executed and `None` when it wasn't executed. 

Code that I have that could use it: 
```scala
    val e: ZIO[System, Throwable, Option[File]] = for {
    sys <- ZIO.service[zio.system.System.Service]
    shouldLog <- sys.envOrElse("TRACE_REQUESTS", "false").map(_.toLowerCase == "true").orDie
    logLocation <- sys.envOrElse("TRACE_REQUESTS_STORAGE_PATH", ".").orDie
    logDir <- createLogDirectory(correlationId, jobId, calculationId, logLocation).whenOption(shouldLog)
  } yield (logDir)
```

I think the code could like this: 
```scala
  def whenOption[R, E,A](b: => Boolean)(zio: => ZIO[R, E, A]): ZIO[R, E, Option[A]] =
    effectSuspendTotal(if (b) zio.map(Some(_)) else None)
 ```
 
 WDYT?

**Comment by jdegoes** [comment]
Let's just modify the existing `when` to return the `Option`. We will have to target for 2.x.

**Comment by adamgfraser** [comment]
I will take a look at this.
