### ISSUE TITLE
ZIO 2.0: Simplify runnable spec (ZIO Test)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5536]
Requires discussion:

In an ideal world, there would be only 1 spec type, which would itself extend `zio.ZIOApp`:

```scala
object MySpec extends ZIOSpec {
  override def layer = ZEnv.live ++ myLayer

  def spec = ...
}
```

**Comment by adamgfraser** [comment]
Yes. There is a little bit of plumbing in just using the new `ZIOApp` functionality. The trickier issue is what we want to do with the dreaded comma since that was the motivation for the second spec type in the first place.

**Comment by jdegoes** [comment]
I am quite liking this:

```scala
def spec = 
  suite("foo") {
    test("...") {
    } + 
    ...
  }
}
```

I feel with a warning for non-composed tests, it might be enough.

**Comment by jdegoes** [comment]
Trying to think of 1 shape to support all. Perhaps something like:

```scala
class ZIOSpec[R](layer: ZLayer[TestEnvironment, Any, R]) extends AbstractRunnableSpec with ZIOApp {
  type Environment = R
  def spec: ZSpec[TestEnvironment with Environment, Any]
  def aspects: List[TestAspect[Nothing, TestEnvironment with Environment, Nothing, Any]] = ...
}
```

1. The user's layer may depend on the test environment
2. The spec may depend on both the test environment, and the user environment, produced from the user layer
3. The aspects may require both the test environment, and the user environment
4. Neither environment nor failure are relevant outside the definition of `ZIOSpec`
5. The layer and aspects have defaults so only `spec` need be implemented

The main difficulty is unifying "user brings their own layer" with "no custom layer".

```scala
object MySpec1 extends ZIOSpec(ZLayer.any) {
  def spec = ???
}
object MySpec2 extends ZIOSpec(myCustomLayer) {
  def spec = ???
}
```

Perhaps having 2 classes to avoid the boilerplate isn't so bad:

```scala
object MySpec1 extends ZIOSpecDefault {
  def spec = ???
}
object MySpec2 extends ZIOSpec(myCustomLayer) {
  def spec = ???
}
```

**Comment by adamgfraser** [comment]
We could potentially just have the default layer be `ZLayer.environment[TestEnvironment]`.

I think it might be useful to think about what we are trying to solve for at this point. With the changes currently in the `series/2.x` branch we already have one spec type that extends `ZIOApp`, supports composition with `+`, and has a list of test aspects that the user can override.

So are we really just saying we want to have a default layer so we move from the user having to do `provideLayer` or `provideLayerShared` to just overriding `layer`?

What are the intended semantics of this layer? Is it supposed to be provided per test or shared?

**Comment by jdegoes** [comment]
Globally Shared across all specs that use the layer.

**Comment by adamgfraser** [comment]
Okay. I think that makes sense.

**Comment by jdegoes** [comment]
Hmmm. If provideLayer variants used a free encoding (layer embedded in spec), that would be enough to do globally shared layers?

**Comment by adamgfraser** [comment]
I'm not sure we even need that. I think there are a couple of things we need to do:

1. I think ideally if we go down this road spec composition should work if implemented in terms of the `<>` operator on `ZIOApp`. That won't work right now because `ZIOApp` expects each application to have its environment provided so we will end up providing the shared layer twice. I think we could resolve by either moving the concept of the shared layer up to `ZIOApp` or making `<>` non-final so we could override it in `AbstractRunnableSpec` and then make the implementation basically zip both together and then provide both layers (since then memoization of layers will automatically solve the sharing problem for us.
2. We need to refactor the SBT test runner to compose all the tests into one big spec using `<>`. Then in combination with the above we will solve this problem.

**Comment by adamgfraser** [comment]
Something like this:

```scala
trait ZIOSpec extends ZIOApp { self =>

  type Environment <: Has[_]

  def layer: ZLayer[Any, Nothing, Environment]

  def execute: ZIO[Environment, Any, Any]

  final def run: ZIO[Any, Any, Any] =
    execute.provideLayer(layer)

  def <>(that: ZIOSpec): ZIOSpec =
    new ZIOSpec {
      type Environment = self.Environment with that.Environment
      def layer: ZLayer[Any, Nothing, Environment] =
        self.layer ++ that.layer
      def execute: ZIO[Environment, Any, Any] =
        self.run.zip(that.run)
    }
}
```
