### ISSUE TITLE
Documentation For Metrics

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5542]
Now that metrics are part of `zio` additional documentation needs to be added describing how users can work with metrics. Some of the existing documentation from `zio-zmx` can be leveraged here though further improvement is needed. Some aspects involving using these metrics can be relatively domain specific (e.g. how histogram works, definition of quantiles for summary) so we need to make sure we cover that.

**Comment by khajavi** [comment]
After the migration guide, I can work on this.

**Comment by adamgfraser** [comment]
@khajavi Fantastic!

**Comment by 987Nabil** [comment]
@adamgfraser can this be closed?
