### ISSUE TITLE
Implement Developer Mode Metrics Reporting

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5543]
It would be nice to have some "developer mode" metrics reporting when users are working with ZIO directly without using any metrics backend. This would likely be extremely minimal since we do not want to have any dependencies in ZIO (the existing developer mode server would not be in `zio`).

Possibly this could just consist of taking a snapshot of all the metrics recorded in the application at the end of the application and rendering them in a visually attractive way, or just providing an operator that allowed the user to do this themselves.

**Comment by adamgfraser** [comment]
Copying @kitlangton.

**Comment by jdegoes** [comment]
We could possibly tap into a [process signal](http://www.docjar.com/html/api/sun/misc/Signal.java.html) to do the metrics dump.

**Comment by emilhotkowski** [comment]
Is this still relevant? I could pick this up

**Comment by jdegoes** [comment]
This ticket is still relevant. I think @vigoo recently did some work in ZIO Flow that could be useful to port to ZIO 2.0.

**Comment by vigoo** [comment]
What I did in zio-flow is just dumping all collected metrics at once at the end of test runs:
https://github.com/zio/zio-flow/blob/main/zio-flow-runtime/src/test/scala/zio/flow/DumpMetrics.scala

something like this could be added to ZIO Core, probably with optional periodic dump not just final

**Comment by arumus** [comment]
I can pick this up if this is still available.
