### ISSUE TITLE
ZIO 2.0: Improvements to ZLogger

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5546]
The data type `ZLogger` is almost pure and could be pulled out into the main package `zio`.

To accomplish this change:

 - Change `def logged(f: A => Unit): ZLogger[Unit]` to `def map[B](f: A => B): ZLogged[B]` (a natural generalization)
 - Move `zio.internal.ZLogger` to `zio.ZLogger`

**Comment by adamgfraser** [comment]
Will do.
