### ISSUE TITLE
ZIO.serviceWith is too restrictive

### ISSUE THREAD

**Issue by tuleism** [zio/zio#5555]
Currently it's implemented as:

```scala
  final class ServiceWithPartiallyApplied[Service](private val dummy: Boolean = true) extends AnyVal {
    def apply[E, A](f: Service => ZIO[Has[Service], E, A])(implicit tag: Tag[Service]): ZIO[Has[Service], E, A] =
      new ZIO.Read(r => f(r.get))
  }
```

which requires that `f` return a `ZIO[Has[Service], ...]`. Why do we need that?

Let's say `Service.doSomething` is a function with type `ZIO[Has[AnotherService], ...]`, then this works:

```scala
ZIO.service[Service].flatMap(_.doSomething) :: ZIO[Has[Service] with Has[AnotherService], ...]
```

while this doesn't:

```scala
ZIO.serviceWith[Service](_.doSomething)
```

**Comment by jdegoes** [comment]
I don't mind generalizing this type signature if no one objects. 👍

**Comment by adamgfraser** [comment]
I will take a look at this.
