### ISSUE TITLE
Add THub to zio.stm

### ISSUE THREAD

**Issue by TobiasPfeifer** [zio/zio#5564]
There is no direct way to publish elements to a `ZHUB` inside a STM transaction.

I find it rather cumbersome to integrate the publish side of a Hub in zio.stm (using a fiber to shift elements offered to a TQueue to a Hub):
```scala
class EventQueue[A] private[EventQueue] (
  hub: Hub[Take[Nothing, A]],
  queue: TQueue[Take[Nothing, A]]
) {
  def offer(a: A): TaskSTM[Unit] = queue.offer(Take.single(a))

  def stream(): ZStream[ZEnv, Nothing, A] = ZStream.fromHub(hub).flattenTake

  def shutdown = (queue.takeAll *> queue.offer(Take.end)).commit.ensuring(hub.shutdown)
}

object EventQueue {
  def make[A]: ZIO[Any, Nothing, EventQueue[A]] =
    (for {
      hub   <- Hub.dropping[Take[Nothing, A]](1024)
      queue <- TQueue.bounded[Take[Nothing, A]](1024).commit
      _     <- ZStream.fromTQueue(queue).flattenTake.intoHub(hub).forkDaemon
    } yield new EventQueue(hub, queue))
}
```

A THub would be a perfect fit for usecases that require publish/subscribe in zio.stm transactions (i.e `def publish(a: A): ZSTM[RA, EA, Unit]`).

However I'm uncertain about how the signature of subscribe should look.  If it is `def subscribe: ZSTM[Any, Nothing, ZManaged[Any, Nothing, ZDequeue[RB, EB, B]]` a commit will yield `ZIO[Any, Nothing, ZManaged[Any, Nothing, ZDequeue[RB, EB, B]]]` and need to be flattened (`.toManaged_.flatten`) to get a `ZManaged[Any, Nothing, ZDequeue[RB, EB, B]]`

An alternative would be `def subscribe: ZManaged[Any, Nothing, ZDequeue[RB, EB, B]]`. With this approach subscriptions cannot be part of a zio.stm transaction.

If there is interest I'd like to work on this. Need some input about the API (see above) though.
A naive internal representation would be to keep a TQueue for every subscriber and distribute elements to all queues on publish. However this has a bad memory footprint. A more efficent way is follow the ZHub implementation (keep published elements in a RingBuffer and just keep indexes to read from for every subscription).

**Comment by adamgfraser** [comment]
@TobiasPfeifer I have been working on this. Will submit a PR shortly.
