### ISSUE TITLE
Intermittent failure in RTS spec reusing cached thread

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#559]
```
[error]     x unyielding reuses cached thread
[error]  Success(false) != Success(true) (RTSSpec.scala:974)
```

**Comment by jdegoes** [comment]
@kaishh Any ideas on this one?

**Comment by kaishh** [comment]
Likely just interference from other tests running in parallel, causing a new thread to appear in unyielding pool that fails `eq` test. will address

**Comment by jdegoes** [comment]
@kaishh Thanks!
