### ISSUE TITLE
repeatN not intuitive (zio 2.0)

### ISSUE THREAD

**Issue by domdorn** [zio/zio#5593]
this came up during `advanced-zio` course.
```scala
      test("repeat 5 times") {
        for {
          r <- Ref.make(0)
          _ <- r.update(_ + 1).repeatN(5)
          v <- r.get
        } yield assertTrue(v == 5)
      } + 
      test("repeat 0 times = never") {
        for {
          r <- Ref.make(0)
          _ <- r.update(_ + 1).repeatN(0)
          v <- r.get
        } yield assertTrue(v == 0)
      }
```

for stuff that adds on top, we could maybe have a `thenRepeatN(5)` operator? 
```scala
      test("repeat 5 times") {
        for {
          r <- Ref.make(0)
          _ <- r.update(_ + 1).thenRepeatN(5)
          v <- r.get
        } yield assertTrue(v == 6)
      } + 
      test("thenRepeat 0 times") {
        for {
          r <- Ref.make(0)
          _ <- r.update(_ + 1).thenRepeatN(0)
          v <- r.get
        } yield assertTrue(v == 1)
      }
```

WDYT ?

**Comment by balajirrao** [comment]
Thank you @domdorn. I don't think `repeatN(0)` doing a repeat `0` times is possible - because `returnN` *has* to return an effect that produces a value of the original success type.

**Comment by adamgfraser** [comment]
I think having two versions of this that are off by one is quite confusing and we should only have one of them.

The current implementation has some logic to it in that you are running the effect once and then repeating it five times. It also has a symmetry with `retryN` where you run the effect once and then retry it five times. And this fits in with a variety of `Schedule` operators. For example, `Schedule.recurs(5)` is going to cause the effect to be run once and then repeated another five times if you use it with `repeat` and is going to cause the effect to be run once and then retried five times if you use it with `retry`.

In addition, as @balajirrao says above we have to return an `A`, which indicates we have to run it at least once, which also supports the existing interpretation.

One further consideration is if we change the existing implementation in ZIO 2.0 there is a significant risk of silent breakage.

I do agree that this can be confusing but tend to think that this is the most logical interpretation on balance, though definitely open to thinking about whether there is a better way.

**Comment by balajirrao** [comment]
Could the documentation be changed to read "returns the effect that executes the passed effect `max(1, n + 1)` times"?

**Comment by adamgfraser** [comment]
Yes I will work on the documentation.

**Comment by domdorn** [comment]
or maybe "executes the effect *and then* repeats it n times, returning the last result produced"

**Comment by domdorn** [comment]
When thinking about this.. should we maybe have a `.times(n)` effect that basically does the behavior described above , meaning when called with n = 0 the effect is never run and with n = 5 it is run exactly 5 times?

**Comment by adamgfraser** [comment]
@domdorn That is `replicateZIO`.

**Comment by domdorn** [comment]
hmm.. then I challenge the wording of `replicate`.. today during the lecture with John, it took me quite some time to actually remember `replicate` when all I wanted was to "execute the effect 100 times" (vs. `effect.repeatN(99)`)
Maybe that's just an issue for a non-native english speakers, but I guess there are quite a few thousand zio developers out there that have the same issue.. `times` is known from simple math, like `z times 0 = 0`, `z times 5 = 5z` etc..

**Comment by adamgfraser** [comment]
Spent some time on this and I think the documentation improvement is the best step for now. I think part of the issue may be that we just need to make `replicate` more prominent in our teaching.

`repeat` needs to be consistent with `Schedule` and `Schedule` is a function that needs to do repeats after the initial value, so we need another name here. I'm open to alternatives but personally I am not a fan of `times` and `replicate` has at least some basis.
