### ISSUE TITLE
add @@ to TestAspect as alias of >>>

### ISSUE THREAD

**Issue by domdorn** [zio/zio#5597]
allow refactoring this code by extracting a variable: 
```scala
object IntegrationSystem extends DefaultRunnableSpec {

  /**
   * EXERCISE
   *
   * Explore jvmOnly, windows, linux, ifEnv, and other test aspects that
   * are useful for running platform-specific or integration / system tests.
   */
  def spec = suite("IntegrationSystem")() @@ js(flaky) @@ jvm(nonFlaky) @@ ifEnvSet("slow") @@ timeout(5.seconds)
}

```
like this
```scala
object IntegrationSystem extends DefaultRunnableSpec {
  val myAspect = js(flaky) @@ jvm(nonFlaky) @@ ifEnvSet("slow") @@ timeout(5.seconds)
  /**
   * EXERCISE
   *
   * Explore jvmOnly, windows, linux, ifEnv, and other test aspects that
   * are useful for running platform-specific or integration / system tests.
   */
  def spec = suite("IntegrationSystem")() @@ myAspect
}

```

**Comment by jdegoes** [comment]
I really like this for refactorability reasons. 

A question is how function composition (`a >>> b`) relates to aspect application (`a @@ b`).

You can view a function as having a `FunctionAspect`, which would transform the function (`Function => Function`), and indeed, in such a world, aspect composition (`a >>> b`) is precisely equivalent to transforming the function `a` into a new function, by applying the function  aspect `b`, and therefore could be syntactically represented as `a @@ b` (if one wants to ignore the fact that we have no such thing as `FunctionAspect`).

**Comment by adamgfraser** [comment]
On it.
