### ISSUE TITLE
ZIO 2.0: Change ZIO#repeatXYZ combinators to be lossless

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5599]
Currently a lot of things like `zio.repeatN(2)` just return the last result. It is more useful to return a chunk of results, which allow you to pull out the last yourself with a `map` operation (`zio.repeatN(2).map(_.last)`).

**Comment by adamgfraser** [comment]
At that point those operators become really similar to the `replicate` operators with the exception of whether they insert a yield.

**Comment by luis3m** [comment]
Wouldn't it be better just to keep as-is and add a note in the doc on `repeat` variants about `replicate`?

**Comment by adamgfraser** [comment]
@luis3m I have a PR that does that is #5594 but I think documentation description is a lot less ideal that just something doing what you would naturally expect it to, though I don't think we have what that would look like fully fleshed out yet.

**Comment by adamgfraser** [comment]
Closing for the reasons discussed in #5593 as well as the issues in implementing #5604.
