### ISSUE TITLE
ZIO Streams 2.0: Chunking operators

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5624]
I know there is `flattenChunks` already but the consistency would be nice:
 
```scala
trait ZStream[R, E, A] { self =>
  def chunked: ZStream[R, E, Chunk[A]] = self.mapChunks(chunk => Chunk(chunk))
  def unchunked[A1](implicit ev: A <:< Chunk[A1]): ZStream[R, E, A1] = 
    self.asInstanceOf[ZStream[R, E, Chunk[A1]].mapChunks(_.flatten)
}
```

Alternate names: `chunks` / `unchunks`, `chunk` / `unchunk`.

**Comment by jdegoes** [comment]
Possibly this pair of operators could replace the need for so many chunking variants, although performance implications would have to be investigated.

**Comment by jdegoes** [comment]
Maybe also: 

```scala
// (<leftover>, <newchunk>) => (<newleftover>, <newchunk>)
def rechunkedWith(f: (Chunk[A], Chunk[A]) => (Chunk[A], Chunk[A])): ZStream[R, E, A] = ...

def rechunked(n: Int): ZStream[R, E, A] = rechunkedWith(...)
```

**Comment by adamgfraser** [comment]
I could have sworn we had an operator to expose the chunk structure of the stream at some point.

**Comment by jdegoes** [comment]
Yes, I know we did.

**Comment by adamgfraser** [comment]
I think the problem with most of the chunk variants are in the constructors. Perhaps in the ZIO 2.0 stream encoding the `ChannelExecutor` could have various parameters, such as the default chunk size to use, that could be composed regionally.

**Comment by adamgfraser** [comment]
We do!

```scala
   * Exposes the underlying chunks of the stream as a stream of chunks of elements
   */
  def chunks: ZStream[R, E, Chunk[A]] =
    mapChunks(Chunk.single)
```

**Comment by adamgfraser** [comment]
It is only available in the experimental streams encoding though. Will fix. I have somewhat mixed feelings on `unchunks`. I can't deny the symmetry but it is a little bit of a strange name and `flattenChunks` is also deeply intuitive with the analogy of a stream as like a collection.

**Comment by adamgfraser** [comment]
I'm not sure `rechunkWith` is powerful enough to describe all the changes we potentially want to make to the chunk structure since we could potentially want to emit multiple chunks for each original chunk.

**Comment by jdegoes** [comment]
It's definitely not powerful enough, but if you keep going up in power you would probably end up with foldWeighted or something similar, which already exists. Now maybe we should just stop at `rechunk(n)`?

**Comment by adamgfraser** [comment]
I tend to think that's right. We currently have that operator called `chunkN`. Shall we rename it to `rechunk`? That seems like a better name.

**Comment by jdegoes** [comment]
I personally went looking for it under the name 'rechunk' (not that it means much!).

**Comment by vigoo** [comment]
I think `rechunk` is a good name. The `unchunked ` feels a bit misleading to me as although the `Chunk` goes away from the element type the stream itself is still chunked under the hood. So for me `flattenChunks` seems to be better.
