### ISSUE TITLE
ZIO Streams 2.0: Utilities for non-Path-based files

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5631]
`Path` may be the best way to denote paths in modern Java, but File is still around, and String is more convenient than both. I think we should overload constructors that take `Path` to also take `File` and `String`, purely for ease-of-use. This pattern is common in Java and also Scala (e.g. `scala.io.Source`).

**Comment by adamgfraser** [comment]
I don't think we can overload if we are using default arguments which we do in the `ZStream` constructors for `chunkSize`. Perhaps we could have a naming convention like `fromPath`, `fromFile`, `fromFileString`? Or perhaps this is another push to developer a more compositional solution to the chunking problem.

**Comment by NavidKJalali** [comment]
Can I do this?

**Comment by NavidKJalali** [comment]
@jdegoes @adamgfraser Can I do this?

**Comment by adamgfraser** [comment]
@NavidKJalali Sure!
