### ISSUE TITLE
Bring back the newsletter subscribe button on the ZIO web page

### ISSUE THREAD

**Issue by atooni** [zio/zio#5648]
TODO after migrating to docusaurus 2.0

**Comment by IdiosApps** [comment]
- Current zio.dev footer has `Copyright © 2022 ZIO Maintainers - Built with [Docusaurus **v2**](https://v2.docusaurus.io/)`, so I guess this ticket can be actioned now.
- I was looking for how to get regular ZIO updates and came across this ticket

I didn't look into exactly how the docs are generated, but I found that [the DocusaurusPlugin is being used](https://github.com/zio/zio/blob/2ab578b477a9eee550fc17d5dad094a30dadfc1e/build.sbt#L649). That project is archived and the last release was Dec 2018 - it has moved to https://scalameta.org/mdoc/.

**Comment by atooni** [comment]
Hi @IdiosApps  - you are correct - we have migrated. Will look into that. 

Regarding the DocusaurusPlugin. This is actually not used to build the site anymore. From the sbt perspective it was used to drive Docusaurus itself AFTER the md files had been compiled. 

The compilation of md files to Docusaurus consumable files is actually done by the Mdoc plugin, which is a small wrapper around the mdoc library. 

The site build is CI scripted in the `scripts` directory in the `createSite.sh`
