### ISSUE TITLE
ZStream.timeoutError wrapping error channel

### ISSUE THREAD

**Issue by miroslavmachura** [zio/zio#5665]
Hi, I've noticed different behavior for timeouting `ZIO` and `ZStream` type:

```scala
// following effect ends with "OriginalError" in error channel
val e1 = ZIO.fail("OriginalError").timeoutFail("TimeoutError")(15.minutes)

// following effect ends with "TimeoutError" in error channel
val e2 = ZStream.fail("OriginalError").timeoutError("TimeoutError")(15.minutes).runDrain
```

I would expect both `ZIO.timeoutFail` and `ZStream.timeoutError` to behave in a same way (not to wrap original error), however ZStream always wraps original error with timeout error, thus hiding the original error. This seem unexpected because IMHO original error usually has bigger value in terms of why did the stream fail. So is this intended behavior?

**Comment by adamgfraser** [comment]
Yes this seems like a bug. I will take a look.
