### ISSUE TITLE
does "unsafeRunSync" block thread?

### ISSUE THREAD

**Issue by BaekGeunYoung** [zio/zio#5666]
I have a long running task which returns ZIO, and I want to make my code wait for this task complete without blocking thread.
Following is my code:

```scala
class ZIOTest extends AnyFlatSpec {
  "zio unsafeRunSync" should "not block thread" in {
    zio.Runtime.default.unsafeRunSync(longRunningTx)
  }

  def longRunningTx: ZIO[Has[Clock] with Has[Console], Throwable, Int] = {
    ZIO.sleep(10.second).map { _ =>
      println(Thread.currentThread().getName)
      10
    }
  }
}
```

I want to "run" the ZIO synchronously, and don't want to block thread. Am I doing right? If not, then what is the correct answer?

**Comment by adamgfraser** [comment]
@BaekGeunYoung `unsafeRunSync` does block the thread and there really isn't a way to avoid that other than not calling `unsafeRunSync`. By its nature, `unsafeRunSync` has to not return until the ZIO effect has completed execution. And we have to return an actual value, not a `ZIO` effect, so we can't for example register a non-blocking callback to be completed when the effect completes execution. So we can't do anything other than block the thread in this case.

Not sure what your exact use case but if possible would encourage pushing the logic that you want to be performed when the effect completes execution into a call back or another `ZIO` effect.
