### ISSUE TITLE
ZIO 2.0 exit code on error

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#5678]
It appears that in "2.0.0-M3" the runtime returns always error code = 0, even if there are exceptions.

for example, the following minimal code:

```scala
object Zio20 extends ZIOAppDefault {

  override def run: ZIO[Environment with ZEnv with Has[ZIOAppArgs], Any, Any] =
    ZIO.fail(new RuntimeException("Test Error"))
}
```

completes with:

```text
Process finished with exit code 0
```

Not sure if that is expected?

I expected code `1` to be returned.

**Comment by adamgfraser** [comment]
Will take a look.

**Comment by gchudnov** [comment]
thank you!

**Comment by gchudnov** [comment]
thank you very much!

**Comment by adamgfraser** [comment]
Thanks for raising!
