### ISSUE TITLE
Search result page of the new zio.dev docs site is broken

### ISSUE THREAD

**Issue by ithinkicancode** [zio/zio#5685]
On the new `zio.dev` docs site, the search result page directs you to a URL that has `docs` sub-directory. But the URL doesn't seem to be valid. For example, when searching `Hub`, the result page takes you to this url: https://zio.dev/docs/datatypes/concurrency/hub#docsNav. When you navigate to this url, you'd get a "Page Not Found".

If you remove the `docs` sub-directory from the url, then it will take you to the correct page. (In the example given, the correct url is https://zio.dev/datatypes/concurrency/hub/#docsNav)

**Comment by ithinkicancode** [comment]
Possible duplicate of ##5649

**Comment by khajavi** [comment]
We can close this issue since it has been resolved.

**Comment by adamgfraser** [comment]
🎉
