### ISSUE TITLE
ZIO 2.0: ZIOApp broken on Scala.js

### ISSUE THREAD

**Issue by codingismy11to7** [zio/zio#5696]
I have a simple reproduction here: https://github.com/codingismy11to7/zio2_zioapp_sjs

The long and short of it is, while `zio.App` in ZIO1 works fine on Scala.js, the simplest program using `zio.ZIOApp` in ZIO2 always fails with `Cannot block for result to be set in JavaScript`

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.
