### ISSUE TITLE
Streaming test results in ZIO Test

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#5713]
It seems like at the moment the test results are accumulated and then printed altogether. In a fairly large project with hundreds of tests, it results in a bad user experience because you are looking at a blank screen for minutes sometimes.

It would great to keep outputting test results as and when they are complete. The user experience this way will become far better.

**Comment by adamgfraser** [comment]
Yes it would be good to add this. We have to be careful when we do so that we maintain the ordering of test results and do not interleave them since multiple specs are likely being executed concurrently.

**Comment by tusharmath** [comment]
I guess this is now fixed in rc 4

**Comment by adamgfraser** [comment]
@tusharmath Yes! Thank you for pushing for this! Please let us know your feedback once you get a chance t use it!
