### ISSUE TITLE
Element-level error combinators for Stream

### ISSUE THREAD

**Issue by sbogutyn** [zio/zio#573]
I would like to have a possibility to continue processing the stream in case of failure.
In example below, just skip the current number on failure and process next one:

```scala
def somethingThatCanFail(number: Int): IO[Throwable, Int] = ???
def throwablePrinter(error: Throwable): IO[Nothing, Unit] = putStrLn(s"Processing error: ${error.getMessage}")

Stream.range(1, 100)
      .mapM(
        somethingThatCanFail(_).flatMapError(throwablePrinter)) // this stops stream on failure
      .run(Sink.drain)
```

**Comment by iravid** [comment]
Hi @sbogutyn, we're currently lacking in error handling combinators on `Stream` itself. In the mean time, you can work around that by using handling the error on `IO`:
```scala
Stream
  .range(1, 100)
  .mapM(
    somethingThatCanFail(_).redeemWith(
      v => IO.succeed(Chunk(v)),
      e => throwablePrinter(e) *> IO.succeed(Chunk.empty)
    )
  )
  .mapConcat(identity)
  .run(Sink.drain)
```

**Comment by sbogutyn** [comment]
Hi @iravid, thanks for help, this solved my problem.

**Comment by jdegoes** [comment]
@iravid I think this ticket can be a good use case for at least one error combinator on `Stream`, which handles not the errors of the `Stream`, but the errors of the function passed to fold.

**Comment by iravid** [comment]
Ah that's a good idea. I'm lacking mental bandwidth right now so I'll try and come back to this next week.
