### ISSUE TITLE
`assertTrue` ignores the label, if assigned to AssertionResult

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio#5743]
It's possible to label the assertion result by `assert(...).map(_.label("my label"))`

It seems that doing this with `assertTrue` does not render the label.

![image](https://user-images.githubusercontent.com/601206/136595250-85802e2e-f2b5-4ac4-b84a-0c5f87bfd198.png)

**Comment by kitlangton** [comment]
labels now work #6709
