### ISSUE TITLE
Zio version in Getting Started does not exist

### ISSUE THREAD

**Issue by WillemHoman** [zio/zio#5786]
```
(update) sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio_2.13:2.0.0-M2+139-8caf95dd-SNAPSHOT
Not found
```
https://zio.dev/getting_started/
![zio3](https://user-images.githubusercontent.com/2238749/137605019-bc6e9466-e6a8-4da2-b909-f6d5a2a82226.png)

![zio2](https://user-images.githubusercontent.com/2238749/137604999-b8ae10d2-53eb-4147-8335-db9edc703a63.png)

**Comment by adamgfraser** [comment]
@khajavi @atooni We should tie this to the latest release.

**Comment by khajavi** [comment]
Yes, I noticed that before. I will check it later today.
