### ISSUE TITLE
Add ZIO 2.0 Migration Guide Section for Library Authors

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5797]
This should cover ZIO 2.0 features that are relevant to contributors to ZIO ecosystem libraries as opposed to users. Suggested topics:

- [ ] Adding implicit trace parameters so the "guts" of your library don't show up in user execution traces
- [ ] Making all parameters to operators returning an effect by name
- [ ] Updating names to match ZIO 2.0 naming conventions
- [ ] Changing parallelism operators to use structured concurrency operators, if applicable

**Comment by khajavi** [comment]
Will do that.
