### ISSUE TITLE
ZIO 2.x: Ecosystem Migration Status

### ISSUE THREAD

**Issue by khajavi** [zio/zio#5809]
In the migration guide, we have a section in which we ask users to make sure that their direct and transitive dependencies were migrated to the ZIO 2.x, before starting the migration process. 

It would be better to have a place to follow up and present project statuses.

## Offical Libraries

| Project                                                     | Status |
|-------------------------------------------------------------|--------|
| [zio-actors](https://github.com/zio/zio-actors)             |        |
| [zio-akka-cluster](https://github.com/zio/zio-akka-cluster) |        |
| [zio-cache](https://github.com/zio/zio-cache)               |        |
| [zio-config](https://github.com/zio/zio-config)             |        |
| [zio-ftp](https://github.com/zio/zio-ftp)                   |        |
| [zio-json](https://github.com/zio/zio-json)                 |        |
| [zio-kafka](https://github.com/zio/zio-kafka)               |        |
| [zio-logging](https://github.com/zio/zio-logging)           |        |
| [zio-metrics](https://github.com/zio/zio-metrics)           |        |
| [zio-nio](https://zio.github.io/zio-nio/)                   |        |
| [zio-optic](https://github.com/zio/zio-optics)              |        |
| [zio-prelude](https://github.com/zio/zio-prelude)           |        |
| [zio-process](https://github.com/zio/zio-process)           |        |
| [zio-query](https://github.com/zio/zio-query)               |        |
| [zio-redis](https://github.com/zio/zio-redis)               |        |
| [zio-rocksdb](https://github.com/zio/zio-rocksdb)           |        |
| [zio-s3](https://github.com/zio/zio-s3)                     |        |
| [zio-schema](https://github.com/zio/zio-schema)             |        |
| [zio-sqs](https://github.com/zio/zio-sqs)                   |        |
| [zio-telemetry](https://github.com/zio/zio-telemetry)       |        |
| [zio-zmx](https://github.com/zio/zio-zmx)                   |        |

## Community Libraries

| Project                                                                    | Status |
|----------------------------------------------------------------------------|--------|
| [caliban](https://github.com/ghostdogpr/caliban)                           |      |
| [munit-zio](https://github.com/poslegm/munit-zio)                          |        |
| [quill](https://github.com/getquill/quill)                                 |        |
| [rezilience](https://github.com/svroonland/rezilience)                     |        |
| [tranzactio](https://github.com/gaelrenoux/tranzactio)                     |        |
| [zio-amqp](https://github.com/svroonland/zio-amqp)                         |        |
| [zio-arrow](https://github.com/zio-mesh/zio-arrow/)                        |        |
| [zio-aws](https://github.com/vigoo/zio-aws)                                |        |
| [zio-aws-s3](https://github.com/zio-mesh/zio-aws-s3)                       |        |
| [zio-grpc](https://github.com/scalapb/zio-grpc)                            |        |
| [zio-http](https://github.com/dream11/zio-http)                            |        |
| [zio-k8s](https://github.com/coralogix/zio-k8s)                            |        |
| [zio-kinesis](https://github.com/svroonland/zio-kinesis)                   |        |
| [zio-pulsar](https://github.com/apache/pulsar)                             |        |
| [zio-saga](https://github.com/VladKopanev/zio-saga)                        |        |
| [zio-slick-interop](https://github.com/ScalaConsultants/zio-slick-interop) |        |
| [zio-test-akka-http](https://github.com/senia-psm/zio-test-akka-http)      |        |

**Comment by adamgfraser** [comment]
@khajavi Completely agree. Where do you think would be the best place for this to live? Was thinking we could have a Google Doc with this but could also just track it in an issue or somewhere else.

Copying @swoogles who has been doing some work on helping with ZIO 2.0 migration.

**Comment by swoogles** [comment]
Here's the current doc-

https://docs.google.com/spreadsheets/d/1QIKgavognTRgh84xAqPTJriJ1VDGbaw8S1fmzMGgf98/edit?usp=drivesdk

If there's a better place for that information to live and be edited by the relevant people, I'd be happy to move it!
