### ISSUE TITLE
ZIO 2.0: Create test suite for Cause.prettyPrint

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5849]
A simple test suite can verify that useful traces are captured in multi-method scenarios.

An example:

```scala
object TraceExample extends ZIOAppDefault {
  def otherFailure =
    for {
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.fail("Uh oh!").ensuring(ZIO.dieMessage("other failure"))
    } yield ()

  def deepFailure =
    for {
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- otherFailure
    } yield ()

  def run = deepFailure.catchAllCause(cause => Console.printLine(cause.prettyPrint))
}
```

We want to see the `run`, `otherFailure`(inside `deepFailure`), and `ZIO.fail` (inside `otherFailure`) in the stack trace, together with the finalizer failure (inside `ensuring`) as a `Suppressed` cause.

A few simple examples like this which test tracing and pretty printing together can constitute our test suite.

**Comment by baldram** [comment]
Hi #zio-hackathon! I would like to work on this issue 😸

**Comment by adamgfraser** [comment]
Awesome! It is all yours!

**Comment by baldram** [comment]
Here is a draft implementation: https://github.com/zio/zio/pull/5900 
Would you please have a look whether I'm on the good track?

I might try moving a code to the `StackTracesSpec.scala`, however this test seems to be a bit different from others, as it's kind of alone in the `scala-2.12` tree, and doesn't run locally from my IDE (no issues with others).

PS: The PR got stuck, as I'm the "first time contributor" requiring an approval for running workflows.

**Comment by baldram** [comment]
I created a new clean PR for this. It is blocked by a #5931 bug fix.
Once a bugfix is merged, time to rebase the MR of this ticket, and the all done.

**Comment by baldram** [comment]
In general tests are implemented. I might implement one more scenario to verify embedded stack traces (2nd and 3rd level); however, a possible bug requires fixing first. More details here: https://discord.com/channels/724305612166660202/776907921761370112/908299720160600124
