### ISSUE TITLE
ZIO 2.0: Make Cause#prettyPrint stack safe

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5852]
Looking at Cause#prettyPrint, one can identify a number of recursive functions that are not tail-recursive. These functions should be refactored to be tail-recursive so that the Cause rendering is stack safe, even for very deep renderings.

**Comment by aartigao** [comment]
Sorry folks, unexpected plans happened for the weekend 🥲 

I won't be able to work on this during the Hackaton. If someone else want to fix this, feel free to take it 🚀

**Comment by adamgfraser** [comment]
@aartigao No worries. Hope everything is good on your end! I will take this.
