### ISSUE TITLE
ZIO 2.0: Delete ZTrace#prettyPrint

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5853]
Instead, pretty printing should directly utilize methods similar to `Cause#prettyPrint` (in fact, maybe `Cause#prettyPrint` can always be used).

As far as I know, the only place that uses this is fiber dumps.

**Comment by zhrebicek** [comment]
I'll take this (hope kids would let me finish it)

**Comment by zhrebicek** [comment]
@jdegoes There was really only one place it was used. 

Is it ok like in the PR?
```
-       |${dump.trace.fold("")(_.prettyPrint)}
+      |${dump.trace.fold("")(Cause.traced(Cause.empty, _).prettyPrint)}
```

**Comment by zhrebicek** [comment]
@jdegoes 
I did it, it complies locally just fine but it does not see `Cause#traced` in the CI, what am I missing here?

```
[error] /home/runner/work/zio/zio/core/shared/src/main/scala/zio/internal/FiberRenderer.scala:65:5: value traced is not a member of object zio.Cause; incompatible interpolation method s
[error]     s"""
[error]     ^
```

**Comment by zhrebicek** [comment]
Did not give it enough time to see I just did not pulled latest changes that remove `Cause#traced` it should be ok now.
