### ISSUE TITLE
ZIO 2.0: Generalize ZLogger to accept messages of type `-Message`

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5855]
ZLogger should get a new type parameter:

```scala
trait ZLogger[-Message, +Output] { ... }
```

This will allow generalizing the `message: () => String` parameter of `ZLogger#apply` from `String` to `Message`. 

Existing functionality can be captured by requiring `ZLogger[String, A]` wherever the old `ZLogger[A]` was required.

This will pave the way for later tickets that generalize the primitive ZIO logging operator to accept messages of `Any` type, which will later allow higher-performance structured logging.

/cc @vigoo

**Comment by xsistens** [comment]
Hi John, love the work you and your team are doing with ZIO. I would love to give this a try but it will be my first OSS contribution, so maybe I need some help here and there.

**Comment by jdegoes** [comment]
Happy to help! Hit me up here or on Discord.
