### ISSUE TITLE
ZIO Streams 2.0: Readd some old methods as deprecated to help migration 

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5857]
Some of the operators in the new ZStream encoding were renamed. We should also have *deprecated* methods with their old names in the new classes to help migration.

Specifically the following methods on `zio.stream.experimental.ZStream`:

- `timeoutError` is now called `timeoutFail`
- `timeoutErrorCause` is now called `timeoutFailCause`
- `into*` methods are now prefixed with `run`
- `fold*` methods are now prefixed with `run`
- `foreach*` methods are now prefixed with `run`

**Comment by planetstrike** [comment]
I'd like to give this a shot as a first time contributor.

**Comment by stsatlantis** [comment]
@planetstrike Based on your message on discord, I'll take this over.
