### ISSUE TITLE
ZIO Streams 2.0: implement when/whenZIO

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5860]
The ZIO Streams 1.0 API defines `when`, `whenM` (deprecated) and `whenZIO`. These are not yet defined on the new `zio.streams.experimental.ZStream`.

The goal is to have all the methods of the old `ZStream` trait and companion object starting with `when` (`when`, `whenCase`, `whenM`, `whenCaseM`, `whenZIO`, `whenCaseZIO` defined in the new `ZStream` too (including the deprecated ones!), to avoid breaking the API.

**Comment by NavidJalali** [comment]
I'd like to do this!
