### ISSUE TITLE
ZIO Streams 2.0: Implement the fromInputStream constructors

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5862]
There are several constructors for ZIO Stream2 1.0 working with `InputStream`:

- fromInputStream
- fromInputStreamEffect
- fromInputStreamZIO
- fromInputStreamManaged

Some of them for are currently missing from the ZIO Streams 2.0 implementation. 
Make sure to have them implemented for all supported platforms (JVM, JS, Native)!

Additionally, for JVM, please make an alias for `fromReaderEffect` called `fromReaderZIO`, deprecating the first, just as it was done in the 1.0 implementation.

**Comment by asakaev** [comment]
I'd be happy to work on this.
