### ISSUE TITLE
ZIO Streams 2.0: fromJavaStream constructors

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5863]
Some of the changes to the JVM-specific `fromJavaStream` constructors of `ZStream` were not yet migrated to the ZIO Streams 2.0 implementation. 

Check that all the variants are defined in `zio.stream.experimental.ZStreamPlatformSpecific`. This involves defining some new aliases and deprecate the old methods.

**Comment by stsatlantis** [comment]
I'd be happy to work on this over the weekend.
