### ISSUE TITLE
ZIO Streams 2.0: Implement ZSink#fromQueue and fromHub

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5866]
ZIO Streams 2.0's sink does not have `fromQueue`, `fromHub`, `fromQueueWithShutdown` and `fromHubWithShutdown` yet.
Define these and write some tests for them.

**Comment by kmatasfp** [comment]
@vigoo I can try this one, I imagine the signature should match the one we have in ZIO Streams 1.0?

**Comment by vigoo** [comment]
Yes they should have the same signature. It is possible the implementation will be also very similar, you will have to check how it was implemented and whether the same primitives exist and can be used to reimplement it in the new sink.

**Comment by kmatasfp** [comment]
sounds good 👍
