### ISSUE TITLE
ZIO Streams 2.0: JVM-specific ZSink#fromOutputStream and fromOutputStreamManaged

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5867]
The new ZIO Streams 2.0 sink does not have `fromOutputStream` and `fromOutputStreamManaged` yet. 
These are JVM-specific constructors and should be defined in `zio.stream.experimental.ZSinkPlatformSpecificConstructors`.

Some tests should also be added for them in the JVM-specific test suite.

**Comment by grouzen** [comment]
Hi! I would like to try this one.
