### ISSUE TITLE
ZIO Streams 2.0: JVM-specific ZSink#fromFile

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5868]
The JVM-specific `ZSink` constructor, `fromFile` is not yet defined for the new ZIO Streams 2.0 `ZSink`, in `zio.stream.experimental.ZSinkPlatformSpecificConstructors`.

Define it in the same way as it was for ZIO Stream 1.0 and provide some tests.

**Comment by ithinkicancode** [comment]
This issue is blocked by #5865 because the `fromFile` implementation relies on `&>` combinator, which in turn depends on `zipWithPar`.
