### ISSUE TITLE
ZIO Streams 2.0: Implement character decoding as pipelines

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5869]
Currently in ZIO Streams 2.0 we have a family of character decoding _sinks_, such as `ZSink#utfDecode`. We also have a new kind of streaming primitive called `ZPipeline` which is essentially a stream transformer.

We would like to have character decoding defined as a `ZPipeline` so it can be applied to any byte stream and convert it to a stream of characters.

Note that this is partially possible by using `transduce` and the existing sinks, but it is not correct for cases requiring to maintain state over the whole stream, such as `utfDecode`. Transducing that sink repeats the `take(4)` that determines the BOM for each chunk which is incorrect.

**Comment by vigoo** [comment]
Related work: https://github.com/zio/zio/pull/5262

**Comment by grouzen** [comment]
I'm gonna try this!

**Comment by ithinkicancode** [comment]
I'll pick this up post-Hackathon if no one else is going to tackle this. From the last PR I did regarding the decoders, I'm fairly familiar with them.

**Comment by ithinkicancode** [comment]
My initial experiment with ZPipeline went well so I'm picking up this ticket. Should have a PR up by tomorrow.
