### ISSUE TITLE
ZIO 2.0: Redesign FiberId to be more efficient and more accurate

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5871]
Currently, FiberID is a `case class` that contains a timestamp and a sequence number. There is no way to represent composite fiber ids, or the absence of a fiber id, and various hacks are used to work around both issues.

We should instead refactor it to the following:

```scala
sealed trait FiberId
object FiberId {
  case object None extends FiberId 
  final case class Runtime(id: Int, startTime: Int) extends FiberId 
  final case class Both(left: FiberId, right: FiberId) extends FiberId
}
```

where `Runtime#id` is a monotonically increasing sequence number, and `startTime` is a measure of the starting time of the fiber that will fit into a 32 bit integer.

The reason for making `id` and `startTime` both `Int` instead of `Long` is that it will allow us to pack both of these values into a single `Long`, which can be stored in the `Fiber`, with the `FiberId` computed only when necessary (e.g. `def fiberId = ...`).

**Note**: _This ticket is only to redesign `FiberId` and update the code, not to actually utilize a more efficient way of storing the fiber id inside the fiber._

**Comment by adamgfraser** [comment]
I will do this.

**Comment by jdegoes** [comment]
@adamgfraser Awesome! Maybe a good idea to call 'Both' something else like Composite.
