### ISSUE TITLE
ZIO 1.0: Backport some improvements to supervisor

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5877]
We can add these two new methods to ZIO 1.x `Supervisor` data type, with default, "do-nothing" implementations.

```scala
private[zio] def unsafeOnSuspend[E, A](fiber: Fiber.Runtime[E, A]): Unit
private[zio] def unsafeOnResume[E, A](fiber: Fiber.Runtime[E, A]): Unit
```

These methods must be called on fiber suspend / resume.

/cc @dkarlinsky

**Comment by dkarlinsky** [comment]
Will start on this while waiting on input on https://github.com/zio/zio/pull/5907
