### ISSUE TITLE
Rename Platform#nonFatal => fatal and thoroughly document

### ISSUE THREAD

**Issue by oxbowlakes** [zio/zio#588]
I'm somewhat confused (I've looked at PR #182) as to whether there is a bug in https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/internal/FiberContext.scala#L293-L297. The code is 

    } catch {
        // Catastrophic error handler. Any error thrown inside the interpreter is
        // either a bug in the interpreter or a bug in the user's code. Let the
        // fiber die but attempt finalization & report errors.
        case t: Throwable if (platform.nonFatal(t)) =>
          curIo = terminate(IO.die(t))
    }

To me this reads as "if the platform thinks the throwable is *not* fatal, then terminate", which seems the wrong way round. Some background:

I have been writing fully-functional applications in `scalaz.IO` for around 5 years now, and have realised that you can absolutely *not rely on user-discipline*: you should always assume that at some point, the code might do this:

    ioa.map { a =>
      throw new Exception("Indisciplined")
      f(a)
    } 

In scalaz, when building a program as a single `IO[Unit]` this is as simple as adding a handler at the top level:

    onBigIOUnit.except { unexpected =>
      IO {
        t.printStackTrace(scala.Console.err)
        sys.exit(666)
      }
    }

In scalaz-zio, I seem to be able to achieve the same effect under `App` as follows:

    object MyMain extends scalaz.zio.App {

      override val Platform: Platform = PlatformLive.Default
        .withNonFatal(_ => true)
        .withReportFailure {
          case Die(t) => 
            t.printStackTrace(scala.Console.err)                          
            sys.exit(42)
        }
      ...

I have no idea whether this is an idiomatic solution for what I want to achieve, but it led me into thinking that it's odd that I am declaring all exceptions as `nonFatal` and only by doing this does my program terminate (at first I added `_ => false` to indicate that anything would be fatal)

I'm sure this is my misunderstanding but cannot find more information to disabuse myself of the notion that it could be a bug

**Comment by jdegoes** [comment]
It's conventional to _not_ catch any catastrophic VM-level errors 

The reason is that, for example, if the VM is out of memory, then subsequent cleanup operations that allocate additional memory are not well-defined.

Now by default, only a `VirtualMachineError` should be considered "fatal". So an ordinary `Exception` should make it to the error reporter, allowing you to exit the VM (which I think is good practice, btw!).

Is this not the behavior you're seeing?

**Comment by oxbowlakes** [comment]
The behaviour I'm seeing is consistent with what you have explained here - it was my misunderstanding of what "non-fatal" might mean in the context of ZIO's top-level exception handling. I think that it might warrant some documentation on the method `Platform::withNonFatal` what the intended use of that is, and what the consequences of it will be.

For example, the default implementation is a confusing double negative:

      def nonFatal(t: Throwable): Boolean =
        !t.isInstanceOf[VirtualMachineError]

Apologies for the mistaken bug-report

**Comment by jdegoes** [comment]
No worries! Let's leave this open with a new title to document the method and rename it to `fatal` instead of `nonFatal`.

**Comment by justinhj** [comment]
I'm working on this. This may be a breaking change, is that ok since we're not at 1.0.0?

**Comment by ghostdogpr** [comment]
Done in #738
