### ISSUE TITLE
ZIO 2.0: Extract Profiling Into Separate Project

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5888]
We just merged support for profiling ZIO applications in #5794.

It was necessary to do this as part of ZIO Core initially because there was functionality in the ZIO runtime that needed to be modified to support this functionality.

However, not that the functionality exists, it would be good to extract profiling into its own project. This will allow the profiling functionality to be built out over time and evolve independently of ZIO Core.

I have created a new repository for `zio-profiling` [here](https://github.com/zio/zio-profiling). This ticket is to create a new ZIO project in this repository using the [ZIO project seed](https://github.com/zio/zio-project-seed.g8) and then extract the functionality in the `profiling` module into this project.

Copying @mschuwalow.

**Comment by 987Nabil** [comment]
I'll do this.

**Comment by adamgfraser** [comment]
@987Nabil Thank you! 🙏

**Comment by 987Nabil** [comment]
@adamgfraser Should I open a pr too that is removing the code from this repo?

**Comment by adamgfraser** [comment]
@987Nabil Opened a couple of tickets in the new repository if you are interested in working more on this.
