### ISSUE TITLE
Add scala set-like methods to ConcurrentSet

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5890]
After #5823 is done, we can start adding operators that will bring the data structure closer to what a collection type looks like in Scala-land. Things like:

- |, &, &~
- collect, collectFirst, filter
- map, flatMap, fold, groupBy, grouped
- exists, forall
- etc

**Comment by kitlangton** [comment]
This issue will topple before my gaze.

**Comment by kitlangton** [comment]
Not sure if `|`, `&`, `&~` make sense to combine two `ConcurrentSet`s. Would it return a mutated version of the first ConcurrentSet? Would it create a new ConcurrentSet? Could we assure that we have a consistent view of both sets at the same time. This might make more sense in an STM context. 

Let me know what you think 😄 Skipping those for now.

**Comment by regiskuckaertz** [comment]
Hm, good point. Do you think these equations are valid:

```scala
xs | ys = xs.addAll(ys)
xs & ys = xs.retainAll(ys)
xs &~ ys = xs.removeAll(ys)
```

?

**Comment by kitlangton** [comment]
Pretty much! I just think that those other method names, accepting Iterables, would be better—to help distinguish them from their immutable variants.

Also, `.map` `.collect` may not be valid. Something like `def transform(f: A => A)` would work (like what's on `TMap`.

**Comment by regiskuckaertz** [comment]
I agree 💯

Also you cannot write `xs | ys | zs`, which is pretty much the raison d'être of these operators.
