### ISSUE TITLE
ZIO Test 2.0: Use ZTraceElement instead of SourceLocation

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5903]
ZIO Test independently evolved the ability to capture source locations. Now that we have ZTraceElement which directly captures source locations, we can replace usages of SourceLocation inside ZIO Test with ZTraceElement.

**Comment by hmemcpy** [comment]
I'd like to work on this!

**Comment by pshemass** [comment]
does this cover the fact that trace doesn't match regex in `ZTraceElement.SourceLocation`?

**Comment by hmemcpy** [comment]
I don't know yet, I just learned about it from the chat. Is there an issue describing the problem?

In any case, I'm running CI for now just to see if something got broken, will address specific issues right after!

**Comment by pshemass** [comment]
#5914 I created issue for this

**Comment by hmemcpy** [comment]
Thanks, I'll take a look at it, if @baldram doesn't beat me to it :)

**Comment by baldram** [comment]
I think my tests will be higher-level (sort of integration tests) which will survive future refactorings, and so on. If anything changes in a shape of what we render, adjustment will be easy. It's good we will cover a current shape now. 👍

**Comment by hmemcpy** [comment]
Ok, I did find a bug with the source location reporting! It reports the wrong location from assert/assertM, and I know why. Working on it!
