### ISSUE TITLE
ZTraceElement.SourceLocation does not work

### ISSUE THREAD

**Issue by pshemass** [zio/zio#5914]
to reproduce

```
object App extends ZIODefaultApp {
   def getClassNameFromTrace(implicit trace: ZTraceElement) = trace match {
     case ZTraceElement.SourceLocation(_, clazz, _, _) => ZIO.succeed(clazz)
     case _ => ZIO.fail("blah")
  }
  def run = getClassNameFromTrace
 }
```

it seems that format of the trace in my case `zio.logging.slf4j.Slf4jLoggerTest.spec(/Users/rzbikson/projects/zio-logging/slf4j/src/test/scala/zio/logging/slf4j/Slf4jLoggerTest.scala:31:28)` doesn't match regex in `zio.internal.stacktracer.Tracer#regex`

**Comment by jdegoes** [comment]
Possibly related to #5917

**Comment by baldram** [comment]
Ok, I might have a look at this one as well, and handle it as a part of https://github.com/zio/zio/issues/5917.
This seems to be connected.

**Comment by baldram** [comment]
All right, this PR https://github.com/zio/zio/pull/5931 should fix this issue as well.

Here is a test via Ammonite. I haven't delivered implementation details test for the `Tracer` itself as currently (ZIO Hackathon) there is a discussion whether we are able to get rid of the regex at all. However there is a high-level test of course which verifies the `Cause`.

Here is how I tested it via Ammonite (using the improved regex from the mentioned PR).

```scala
val regex = """(.*?)\((.*?):([^:]*?):([^:]*?)\)""".r

val parse: String => Option[(String, String, Int, Int)] = {
  case regex(location, file, line, column) => Some((location, file, line.toInt, column.toInt))
  case _ => None
}

val printDetails: String => Unit = s => {
  val maybeTuple = parse(s)
  println(maybeTuple.get._1)
  println(maybeTuple.get._2)
  println(maybeTuple.get._3)
  println(maybeTuple.get._4)
}

val example1 = """zio.StackTracesSpec.spec.failure(C:\data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:81:26)"""
val example2 = """zio.logging.slf4j.Slf4jLoggerTest.spec(/Users/rzbikson/projects/zio-logging/slf4j/src/test/scala/zio/logging/slf4j/Slf4jLoggerTest.scala:31:28)"""

printDetails(example1)
printDetails(example2)
```

The outcome:
```
zio.StackTracesSpec.spec.failure
C:\data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala
81
26
zio.logging.slf4j.Slf4jLoggerTest.spec
/Users/rzbikson/projects/zio-logging/slf4j/src/test/scala/zio/logging/slf4j/Slf4jLoggerTest.scala
31
28
```

Once the PR https://github.com/zio/zio/pull/5931 is merged, we might close this issue as well.

**Comment by adamgfraser** [comment]
Verified that this works correctly on the latest version of the `series/2.x` branch.
