### ISSUE TITLE
ZIO 2.0: Create more robust regular expression for deconstructing ZTraceElement

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#5917]
Inside `Tracer.scala` (there are **two** of these, for Scala 2.x and Scala 3.x), there is a regular expression that tries to extract out the location, file name, row, and column of a trace element.

However, it does not do a good job on Windows because Windows uses the colon operator (:) for drives.

We need to improve this regular expression so it does not match against `:` inside the path name. 

One possibility is as follows:

```
(.*?)\((.*?):([^:]*?):([^:]*?)\)
```

(See [here](https://regex101.com/r/ddGSAU/1))

We need to update these regular expressions so they are more robust to paths that contain colons.

**Comment by jdegoes** [comment]
@baldram Do you want to take this one??

**Comment by baldram** [comment]
Yes, I can do so. It blocks my ticket 😄

**Comment by robmwalsh** [comment]
My bad -_- I'm terrible at regex
https://xkcd.com/1171/

**Comment by baldram** [comment]
I'm about to make a MR. This will be a separate regex for Windows, or I need to make sure how about the other platform whether this "more robust" is ok for all use cases.

**Comment by baldram** [comment]
Ok, a PR https://github.com/zio/zio/pull/5931 closes the other connected issue as well.
Ready for review.
