### ISSUE TITLE
ZIO Streams 2.0: splitLines, splitOn, splitOnChunk

### ISSUE THREAD

**Issue by vigoo** [zio/zio#5918]
Implement the `splitLines`, `splitOn` and `splitOnChunk` transducers from the ZIO Streams 1.0 as ZIO Streams 2.0 `ZPipeline`s

**Comment by NavidJalali** [comment]
I'd like to pick this up if no one is doing it

**Comment by NavidJalali** [comment]
This can be resolved now! 🥳

**Comment by adamgfraser** [comment]
@NavidJalali Great work on this!
