### ISSUE TITLE
Review ConcurrentSet.addAll and containsAll

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#5919]
Currently not atomic

**Comment by mijicd** [comment]
The odd thing is, even the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.KeySetView.html#addAll-java.util.Collection-) states that `addAll` is implemented this way :thinking:

**Comment by regiskuckaertz** [comment]
Yeah, I was going through it and there are many of them that could be improved. Perhaps ZIO should have its own implementation 😁

**Comment by regiskuckaertz** [comment]
I will close, it doesn't look possible.
