### ISSUE TITLE
ZIO.log* should have overload with cause 

### ISSUE THREAD

**Issue by pshemass** [zio/zio#5930]
it would be nice to have overload for `ZIO.log`, `ZIO.logInfo`, `ZIO.logDebug` and `ZIO.logError` that takes `Cause[Any]`

Cause should be propagated all the way to `ZLogger` as `Option[Cause[Any]]`. This will allow to create better DSL for format in zio-logging 

```
label("timestamp") + timestamp()
      |-| label("level") + level
      |-| label("thread") + fiberNumber
      |-| label("message") + line 
      newLine cause
```

**Comment by adamgfraser** [comment]
Should we have special treatment for `Cause` or handle this as part of a more general solution to structured logging as contemplated by #5855 and #5856?
