### ISSUE TITLE
ZIO 2.0: Bring back the stack trace and fiber ID for Cause.prettyPrint

### ISSUE THREAD

**Issue by baldram** [zio/zio#5955]
**A problem**:

It looks like we got a regression. We are not seeing a nice stack trace.
The `Cause.prettyPrint` used to show a source locations and fiber ID.

**How to reproduce?**

Once the PR https://github.com/zio/zio/pull/5949 is merged, there are few tests. Enable `debug` (L117), run one of tests, and see the console.

The test suite might be now easy extended to check the Fiber ID (at least some regex on it) and the existence of stacktrace.

**Findings**:

It might be a blind shot, but this might be connected with Refactor Cause (#5873 / https://github.com/zio/zio/issues/5848).
A Stackless was introduced in place of Traced.
Right, now the trace only exists in the nodes.
The `prettyPrint` should have access to the traces at the leaf node and render them.

**Description**:

Example stacktrace lacking source location and fiber information.
```
Exception in thread "zio-fiber-" java.lang.String: Oh no!

    Suppressed: java.lang.RuntimeException: other failure
```

Looking at `Cause.prettyPrint.unify`, we match now the following `case (cause @ Fail(_, _)) :: more => loop(more, fiberId, accum, stackless, unifyFail(cause.value) :: result)` .

The object has source data.

```
Then(Fail(Oh no!,ZTrace(Runtime(1635705898,27),Chunk(zio.StackTracesSpec.spec.underlyingFailure(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:89:26),zio.StackTracesSpec.spec.underlyingFailure(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:89:60),zio.StackTracesSpec.spec.underlyingFailure(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:89:15),zio.StackTracesSpec.matchPrettyPrintCause(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:125:26),zio.StackTracesSpec.spec(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:95:17),zio.StackTracesSpec.spec(C:\Data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala:85:45),zio.test.RunnableSpec.main.exitCode(C:\Data\git\zio-hackaton\zio\test\shared\src\main\scala\zio\test\RunnableSpec.scala:53:43)))),Stackless(Die(java.lang.RuntimeException: other failure,ZTrace(None,Chunk())),true))
```

**Comment by adamgfraser** [comment]
I will take a look at this.
