### ISSUE TITLE
Using ZStream#mapMPar makes it impossible to retry the stream

### ISSUE THREAD

**Issue by KCala** [zio/zio#5959]
This ZIO program works as expected. Processes commands for 10 seconds, logs an exception, starts processing from start after 5 seconds, repeats forever.
```scala
(ZStream(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) ++ ZStream.fail(new Throwable("Boom")))
  .mapM { a =>
    ZIO.sleep(1.second) *> ZIO.effect(println(a))
  }
  .runDrain
  .resurrect
  .tapError(e => ZIO.effect(println(s"Unexpected error when running stream $e")))
  .retry(Schedule.fixed(5.seconds))
  .exitCode
```

Output: 
```
1
2
3
4
5
6
7
8
9
10
Unexpected error when running stream java.lang.Throwable: Boom
1
2
3
// repeats forever...
```
---------------
This program, however, fails after reaching the failure in the stream. Retry doesn't work, the `tapError` doesn't work. The whole system process just finishes with an error code. 
```scala
(ZStream(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) ++ ZStream.fail(new Throwable("Boom")))
  .mapMPar(2) { a =>
    ZIO.sleep(1.second) *> ZIO.effect(println(a))
  }
  .runDrain
  .resurrect
  .tapError(e => ZIO.effect(println(s"Unexpected error when running stream $e")))
  .retry(Schedule.fixed(5.seconds))
  .exitCode
```

Output: 
```
2
1
3
4
5
6
7
8
Fiber failed.
An interrupt was produced by #2.
No ZIO Trace available.
```

---------------

The ZIO.sleep(1.second) in the failing example is crucial, because the program actually works correctly if there is no sleep. I think that if the upstream in ZIO stream throws an exception at the exact same moment when there is some running fiber inside of mapMPar, the stream tries to interrupt this fiber, but interrupts the whole stream instead. I think it would eventually also happen without `ZIO.sleep(1.second)`, but with longer sleep it is more likely for the exception to happen while the fiber is still active, hence the issue is easier to reproduce. 

The problem doesn't happen when using `mapMParUnordered`, only with `mapMPar`.

**Comment by adamgfraser** [comment]
@KCala Thanks for reporting? What ZIO version are you on?

**Comment by KCala** [comment]
@adamgfraser We're using the newest stable version - `1.0.12`. I'm not sure how to interpret the question mark in your response though. Have I done something wrong?

**Comment by adamgfraser** [comment]
@KCala As me making a typo. That was supposed to be an exclamation mark. 😃

**Comment by KCala** [comment]
@adamgfraser Oh, all good then! I was scared that I've done some faux pas 😅

**Comment by adamgfraser** [comment]
@KCala No reporting issues like this is fantastic and really appreciate the reproducer. 🙏

**Comment by luis3m** [comment]
@adamgfraser @KCala this seems to work: https://scastie.scala-lang.org/ExM4PsjYQx28v4gkJ8lFvA
```scala
_ <- permits.withPermit {
          latch.succeed(()) *>
            ZIO.uninterruptibleMask(restore => 
              (restore(errorSignal.await) raceFirst restore(f(a)))
                .tapCause(errorSignal.halt)
                .run
                .flatMap(p.done(_))
             )
        }.fork
```
I'll check later today if this does not break any other test.

**Comment by luis3m** [comment]
Also ZIO 2.x needs a fix as well apparently: https://scastie.scala-lang.org/io93DYCZQzefiVt5SNSjkw

**Comment by vigoo** [comment]
> Also ZIO 2.x needs a fix as well apparently: https://scastie.scala-lang.org/io93DYCZQzefiVt5SNSjkw
> 
> I'd assume a similar change to `ZChannel#mapOutZIOPar` would work.

Note that it's still the old `ZStream` in your example. If you use `zio.stream.experimental._` it works.

**Comment by adamgfraser** [comment]
Unfortunately it looks like this breaks several other tests.

**Comment by adamgfraser** [comment]
I think we need a more fundamental solution here. I am working on something.

**Comment by ChipChopChippy** [comment]
Are there any updates on this (on ZIO. 1.x)? Happy to act as a testing guinea-pig or in any other way that I can

**Comment by adamgfraser** [comment]
@ChipChopChippy Thanks for the reminder! Just submitted a PR for this.
