### ISSUE TITLE
Document new zio.concurrent datatypes

### ISSUE THREAD

**Issue by mijicd** [zio/zio#5965]
Document the newly introduced data types from `zio.concurrent`:

- ConcurrentMap
- ConcurrentSet
- CountdownLatch
- CyclicBarrier

**Comment by pooriatgh** [comment]
I want to work on this as my first contribution.

**Comment by mijicd** [comment]
@pooriatgh All yours, thank you!

**Comment by Wosin** [comment]
@pooriatgh Are You still working on that task ? Do You need any help ?

**Comment by pooriatgh** [comment]
> @pooriatgh Are You still working on that task ? Do You need any help ?

Yes, I couldn't do it. Sorry, I have to spend more time with Zio before picking any issues.

**Comment by mijicd** [comment]
Tackled in #6332
