### ISSUE TITLE
ZIO 2.0: Migrate All Tests to New Spec Type

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5968]
Now that #5932 has been merged we should migrate all tests to the new spec type. That means all tests should extend `ZIOSpecDefault` instead of `DefaultRunnableSpec`. We should deprecate `DefaultRunnableSpec` and its related data types `RunnableSpec` and `AbstractRunnableSpec`. This will keep us on the latest spec implementation and allow us to identity any issues with it.

Copying @swoogles.

**Comment by swoogles** [comment]
I'll work on this!

**Comment by swoogles** [comment]
@adamgfraser  Before I go too far down this path, I want to confirm the general steps needed here.
Starting with this Spec:
```
  object HasSpec extends DefaultRunnableSpec {
    override def spec: ZSpec[Environment, Failure] = ???
  }
```
One possible migration is:
```
  object HasSpec extends ZIOSpecDefault {
    override def spec: ZSpec[Environment, Any] = ???

    override def layer: ZLayer[Has[ZIOAppArgs], Any, TestEnvironment] =
      zio.ZEnv.live >>> TestEnvironment.live
  }
```
Which is broken down into these steps:
1. Convert `DefaultRunnableSpec` to `ZIOSpecDefault`
   I don't think there's much discussion needed on this point.
   
2. Convert `Failure` to `Any`
  Please confirm if this is a safe thing to do for the general case

3. Make sure a `layer` is defined for the `Spec`
   Some options:
    - Insert the default `layer` into the body of each implemented `Spec`
    - Define the default `layer` in `ZIOSpecDefault` and let people override it as desired in their specific cases
    
  The 2nd option would be significantly less code changes, but might be overreaching.

**Comment by adamgfraser** [comment]
@swoogles I would just remove the type parameters. I don't think you should have to define a layer of we are using the default one because it already has one and I don't think there are any cases where we need to share a custom layer.

**Comment by swoogles** [comment]
Removing the types is an easy fix, thanks.

On the other point about layers- currently `ZIOSpecDefault` is implemented as:
```
abstract class ZIOSpecDefault(implicit trace: ZTraceElement) extends ZIOSpec[TestEnvironment] {

  final val testLayer: ZLayer[TestEnvironment, Any, TestEnvironment] = ZLayer.environment(Tracer.newTrace)

  def spec: ZSpec[TestEnvironment, Any
```
Which doesn't cover `layer` needed by `ZIOApp`. So if we don't define one in either the final leaf `Spec` implementation, or in `ZIOSpecDefault`, we get this error:
```
[error] /home/bfrasure/Repositories/swoogles/zio/core-tests/shared/src/test/scala/zio/HasSpec.scala:6:8: object creation impossible. Missing implementation for:
[error]   def layer: zio.ZLayer[zio.Has[zio.ZIOAppArgs],Any,zio.HasSpec.Environment] // inherited from trait ZIOApp
[error] object HasSpec extends ZIOSpecDefault {
```
Happy to zoom if we should have a more general old Spec VS new Spec discussion that would clarify some of this for me.

**Comment by swoogles** [comment]
@adamgfraser this can be closed
