### ISSUE TITLE
ZIO 2.0 Stream schedule will produce a unlimited stack in the fiber

### ISSUE THREAD

**Issue by zheh12** [zio/zio#5993]
```
import zio._
import zio.stream._

object TestZIO extends ZIOAppDefault {

  def produce(state: ZState[Int]) = for {
    number <- state.get
    ans <- ZIO.attemptBlocking {
      Thread.sleep(1000)
      if (number % 100000 == 0) {
        Some(2)
      } else None
    }
    _ <- state.update(i => i + 1)
  } yield ans

  override def run = for {
    state <- ZState.make(0)
    _ <- ZStream.repeatZIO(produce(state))
      .mapZIO(x => ZIO.logInfo(s"found ${x}").as(x))
      .filter(_.isDefined)
      .map(_.get)
      .schedule(Schedule.spaced(100.millis))
      .foreach { x =>
        ZIO.logInfo(s"receive ${x}")
      }
  } yield ()
}
```

With the code, It will produce a very long stack.Then at the end it will cost all the cpu usage for too long stack.

I use zio 2.0.0-M4 and java 11.

![image](https://user-images.githubusercontent.com/2442257/140077917-2ee3b4c8-a3d9-4912-bfbc-197c8825624a.png)

**Comment by adamgfraser** [comment]
@zheh12 Thanks for reporting! We need to audit all these recursive operators with the new stack traces.

**Comment by adamgfraser** [comment]
@zheh12 Are you able to reproduce on latest version of `series/2.x`?

**Comment by zheh12** [comment]
> @zheh12 Are you able to reproduce on latest version of `series/2.x`?

Ok, I will try.

**Comment by zheh12** [comment]
@adamgfraser. I pull the newest code from series/2.x branch. And build local 2.0.0-M4+88-83abb441-SNAPSHOT. And It works. The stack size now is always 34 now. Thanks for the fix.
