### ISSUE TITLE
TestClock hangs when used with zio-kafka layer

### ISSUE THREAD

**Issue by KadekM** [zio/zio#5994]
Minified example - using https://github.com/zio/zio-kafka, test hangs on `TestClock`:
```scala
object Hang extends DefaultRunnableSpec {
  val theLayer = 
      Consumer.make(ConsumerSettings(List("localhost:9092"))).toLayer.orDie
      
  def spec = {
    suite("hang")(
      testM("test") {
        for {
          _     <- zio.console.putStrLn("start")
          _     <- TestClock.adjust(1.hour)
          _     <- zio.console.putStrLn("end")
        } yield assertCompletes
      }.provideCustomLayer(theLayer),
    )
  }
}
```

without `theLayer` (which isn't used in test) it passes.

```
ZIO 1.0.12
ZIO-Kafka 0.17.1
```

**Comment by adamgfraser** [comment]
@KadekM Does `Consumer` create a background fiber? `TestClock` waits for all fibers in the test to suspend before advancing the clock, so if there is a background fiber that runs forever the clock will never advance.

**Comment by KadekM** [comment]
> @KadekM Does `Consumer` create a background fiber? `TestClock` waits for all fibers in the test to suspend before advancing the clock, so if there is a background fiber that runs forever the clock will never advance.

I believe it does. Is there anything we can do about this?

**Comment by KadekM** [comment]
I am closing this because I've decided to just provide live Clock instances to the Kafka layer, but the initial hangout did take me by surprise :-)
