### ISSUE TITLE
`ZStream#aggregateAsync` doesn't wait for downstream

### ISSUE THREAD

**Issue by paulpdaniels** [zio/zio#6025]
When running aggregateAsync with a much faster upstream producer, it doesn't seem to properly accumulate events:

```scala
Runtime.default.unsafeRun(
  ZStream
      .repeatWith(1, Schedule.windowed(10.millis))
      .aggregateAsync(ZTransducer.foldLeft(0)(_ + _))
      .mapM(b => ZIO.sleep(1.seconds) as b)
      .take(5)
      .foreach(value => putStrLn(s"Value of $value"))
)
```

In the case above I would expect that the result should be 5 results of approximately 100 (upstream is 100x faster than the downstream) however instead it prints "Value of 2" at 1 second intervals.

Switching to `aggregateAsyncWithin(ZTransducer.foldLeft(0)(_ + _), Schedule.fromDuration(1.second))` improves the performance, but still results in an alternating set of results (103, 3, 103, 2, 103).

See this scastie for a repro: https://scastie.scala-lang.org/RxjSCj8XSr6rDSinduFc6g

**Comment by narma** [comment]
About `aggregateAsyncWithin`:  Schedule.fromDuration recurs only once. `Schedule.spaced` make the trick https://scastie.scala-lang.org/narma/OZ6gNMt8RweJLpyjroCTQA

**Comment by daron666** [comment]
Hi! I'm working on a fix.

**Comment by paulpdaniels** [comment]
@narma yeah figured that one out a bit later, still I think the either the docs are incorrect for these operators or the implementation. I'm curious, @daron666 what is your proposed fix?

**Comment by daron666** [comment]
@paulpdaniels Oh yeah sorry, according to my investigation you should use `Schedule.spaced` for that purpose, cause `Schedule.fromDuration` is meant to proc only once.

**Comment by narma** [comment]
Well,  one thing I can't understand - why `aggregateAsync`  which is `aggregateAsyncWithin(sink, Schedule.forever)` recurs only once?
