### ISSUE TITLE
ZIO 2.0.0-M5 - ZPipeline -- take(n: Long) ?

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#6036]
Wondering, is it worth to add `take(n: Long)` to `ZPipeline`?

in ZIO 2.0.0-M4 I was using the following construction that allowed conditionally make a Stream take N elements:

```scala
ZStream
  .xx
  .via(withOptionalLimit)
  .xx
```

where `withOptionalLimit` was defined as:

```scala
val limit: Option[Int] = ...

private def withOptionalLimit[R, T](in: ZStream[R, Throwable, T]): ZStream[R, Throwable, T] =
  limit.map(n => in.take(n)).getOrElse(in)
```

now, `.via` takes a `ZPipeline` that has `takeUntil`, `takeWhile`, but there is no `take(n)`.

Probably I can define `take(n)` myself, but it would be great to have it in `ZPipeline`.

Thank you!
Grigorii

**Comment by adamgfraser** [comment]
@gchudnov Yes! Will add!

**Comment by gchudnov** [comment]
Thank you!

**Comment by gchudnov** [comment]
Will close it, the method was added.

Thank you!
