### ISSUE TITLE
Prefix aspect operator

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#6048]
So I'm writing these test suites and I want to _change their behaviour_ with a few aspects.

The "problem" I face is one of usability, as the spec grows in size, aspects are buried further down the file. As they disappear, I forget they're even there. Out of sight, out of mind.

I get why this looks great in a line like `program @@ changeThis @@ changeThat`, however I feel like sometimes the change in question is important enough that it must always be visible.

Would you consider adding:

```scala
val spec = changeThis @@: changeThat @@: suite("Hey Baby!")(...)
```

?

**Comment by adamgfraser** [comment]
You can always do this with the `apply` method on aspects so this could be written in the more prominent style as:

```scala
changeThis {
  changeThat {
    suite("Hey baby!")(...)
  }
}
```

I tend to think that is more regular than the right associative prefix operator but there is definitely some subjectivity here.

**Comment by regiskuckaertz** [comment]
Of course 🤦‍♂️ I agree, totally fine by me
