### ISSUE TITLE
Macro expansion exception when upgrading from 2.0.0-M4 to 2.0.0-M6-2

### ISSUE THREAD

**Issue by earldouglas** [zio/zio#6071]
When upgrading from 2.0.0-M4 to 2.0.0-M6-2, I [started getting a compile-time exception][1] when using `ZLayer.succeed` without an explicit type argument:

```
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.RuntimeException: TYPEREPR, UNSUPPORTED: class dotty.tools.dotc.core.Types$CachedRefinedType - RefinedType(...)
[error]    |    at izumi.reflect.dottyreflection.Inspector.inspectTypeRepr(Inspector.scala:96)
[error]    |    at izumi.reflect.dottyreflection.Inspector.buildTypeRef(Inspector.scala:22)
[error]    |    at izumi.reflect.dottyreflection.TypeInspections$.apply(TypeInspections.scala:10)
[error]    |    at izumi.reflect.dottyreflection.Inspect$.inspectAny(Inspect.scala:18)
```

Here's a minimal project to reproduce the issue:

*build.sbt:*

```scala
scalaVersion := "3.1.0"
libraryDependencies += "dev.zio" %% "zio" % "2.0.0-M6-2"
```

*project/build.properties:*

```
sbt.version=1.5.5
```

*src/main/scala/Foo.scala:*

```scala
object Bar:
  trait Service:
    def bar(): zio.Task[Int]

object Foo:
  val http: zio.ULayer[Bar.Service] =
    zio.ZLayer.succeed { // doesn't work
    // zio.ZLayer.succeed[Bar.Service] { // works
      new Bar.Service:
        def bar(): zio.UIO[Int] = zio.ZIO.succeed(42)
    }
```

[1]: https://github.com/earldouglas/sectery/pull/292/files#diff-5fc55b0d1a0f4b318d959097aaf698a5a2073e63f6d5fb52b37a63e88863a0d9R14

**Comment by kitlangton** [comment]
I’ll get on that :)

**Comment by kitlangton** [comment]
Hrmmm. CachedRefinedType. I remember seeing a special note about this in Izumi-reflect, @neko-kai @pshirshov. Do you happen to know anything about that weird type?

**Comment by neko-kai** [comment]
@kitlangton No, haven't seen that one, the note was probably about LazyTypeRef. But CachedRefinedType sounds like a similar generic wrapper - there may be a method on it to access the underlying type that you could access reflectively. It may also help you to look for it in dotty source code. I'm not near a PC atm so can't help investigate right now.

**Comment by kitlangton** [comment]
Same :) will look tomorrow. Enjoy the weekend! And thanks for the tip.

**Comment by kitlangton** [comment]
Have a PR that should address the issue. Seems like a Dotty bug as well.
