### ISSUE TITLE
ZIO 2.0: Improvements to ZTraceElement

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6077]
ZTraceElement has a few issues we should fix before 2.0 release:

 - [x] **Security**. `ZTraceElement` macro tracks the full source code location to the file on the machine that did the packaging. Under ordinary circumstances, a path will not leak any private information, but we don't have any guarantee what user names (in a home directory) or hashes or other pieces of information might be embedded in the full path leading to a file. We should change the macro so it only captures the file name, not the full path to the file on the user's local machine. 
 - [x] **Performance**. `ZTraceElement` macro tracks the column number. This means when the traces are converted to Java-style traces, before rendering, the traces have to be de-duplicated by column number, which imposes a performance impact. Column number is not likely to be useful enough to justify this performance cost, so we should omit it. 
 - [x] **Interop**. Related to the column number, there is no way to convert a StackTraceElement from Java into a ZTraceElement. That's because they are not information-equivalent. We should make them information equivalent so we can go both ways: from ZTraceElement, to a StackTraceElement, and from a StackTraceElement, to a ZTraceElement. We should add to/from helper functions on the `ZTraceElement` companion object to do just this, and then leverage these in `ZTrace`.

**Comment by adamgfraser** [comment]
Will do this.
