### ISSUE TITLE
TMap: removeIf should return keys of removed elements

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6083]
currently I have to use code like this to figure out which elements have been removed:
```scala
...
 jobMap = TMap[JobId, Timestamp]
...
      jobKeys <- jobMap.keys
      _ <- jobMap.removeIf{ case(_, ts) => before.value >= ts.value }
      newJobKeys <- jobMap.keys
      removedJobs = jobKeys.diff(newJobKeys)
```
      
would be good if `removeIf` would return me a `List`/`Seq`/`Chunk` of the *keys* or elements that got removed

**Comment by domdorn** [comment]
maybe its wise to add an additional operation `removeIfReturning` to not unnecessarily allocate resources when not needed

**Comment by jeroenr** [comment]
This is added in `series/2.x` by https://github.com/zio/zio/pull/6092
