### ISSUE TITLE
Unable to filter tests by tag

### ISSUE THREAD

**Issue by danilbykov** [zio/zio#6095]
I wrote simple test with `TestAnnotation`
```scala
object MySpec extends DefaultRunnableSpec {
  override def spec = suite("MySpec")(
    test("test") {
      assert(42)(equalTo(42))
    }
  ).annotate(TestAnnotation.tagged, Set("UnitTest"))
}
```

Now I run tests and want to filter out this test by tag
```
sbt testOnly -- -tags ContainerTest
```

But even I specify another tag `MySpec` is executed. It looks like problem is in class
https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/FilteredSpec.scala#L38
Instead of `.getOrElse(spec)` it should return `Spec.empty`.

Is it bug? Can I fix it?

**Comment by adamgfraser** [comment]
@danilbykov It was actually International behavior at the time that if you try to filter for a tag that doesn't exist we run all the tests so you don't accidentally filter out all the tests and get a test suite that passes if you haven't run anything. But I am fine with changing it.

**Comment by danilbykov** [comment]
> you try to filter for a tag that doesn't exist we run all the tests so you don't accidentally filter out all the tests

There is another example more confusing case. Let's assume that we two specs: one with tag UnitTest and another with tag ContainerTest. Now I run tests with tag UnitTest. First spec is executed because it matches with my filter tag. Second spec is also executed because doesn't contain filter tag.

So I will probably open PR tomorrow.

**Comment by adamgfraser** [comment]
Sounds good. We should make the same change for filtering by labels.

**Comment by danilbykov** [comment]
https://github.com/zio/zio/pull/6113
