### ISSUE TITLE
Compiler error when using injectSome

### ISSUE THREAD

**Issue by sebver** [zio/zio#6117]
I was playing around with 2.0.0-M6-2 on scala 2.13.7 and received a compiler error for the following snippet:

```
import zio._

object Main extends ZIOAppDefault {

  trait A
  trait B

  val layerA = ZLayer.succeed(new A {})
  val layerB = ZLayer.succeed(new B {})

  val program = (ZIO.service[A] *> ZIO.service[B]).injectSome[B](layerA)

  def run = program.provide(layerB).unit
}
```

Pretty long error but here's the gist:
```
[error]   EmptyScope.enter
[error]         during phase: globalPhase=erasure, enteringPhase=posterasure
[error]      library version: version 2.13.7
[error]     compiler version: version 2.13.7
[error]
[error]   last tree to typer: TypeTree(class AtomicBoolean)
[error]             tree tpe: java.util.concurrent.atomic.AtomicBoolean
[error]               symbol: class AtomicBoolean in package atomic
[error]    symbol definition: class AtomicBoolean extends Serializable (a ClassSymbol)
[error]       symbol package: java.util.concurrent.atomic
[error]        symbol owners: class AtomicBoolean
```

Not having any issues when using `provideSome`.

(By the way: loving the lack of Has 🙏 )

**Comment by kitlangton** [comment]
Weird! I will look into this. Thanks for the report ❤️

**Comment by kitlangton** [comment]
This appears to work on the newest series/2.x branch.

**Comment by sebver** [comment]
Hey @kitlangton, sorry, somehow missed this.

I've tried again with RC2, `injectSome` doesn't exist anymore, so I tried with both `provideSome` and `provideSomeLayer`. `provideSomeLayer` works, but I still get a compiler error for `provideSome`. Not sure what the difference is between the two.

**Comment by adamgfraser** [comment]
@sebver `provideSomeLayer` doesn't use automatic layer construction, so it indicates the issue is there.

**Comment by sebver** [comment]
This is fixed in RC4 so closing this one.

**Comment by kitlangton** [comment]
Yay!
