### ISSUE TITLE
zio-test: Test-Reports in junit.xml format

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6132]
For reporting test numbers/reports in Jenkins, a junit.xml compatible file needs to be generated. 
The specification of this file can be found here:
https://llg.cubic.org/docs/junit/

Possible workaround?:
Change the object of the test to be a class with the `ZTestJunitRunner` as described in 
https://github.com/zio/zio/blob/master/docs/usecases/testing.md

**Comment by adamgfraser** [comment]
How is this different from the XML reports that SBT already generates?

Would certainly like to support reporting and I think we have new tools to do this with metrics built in but would not want to make the default spec extend the JUnit one.

**Comment by domdorn** [comment]
hmm.. I'll have to check again.. when migrating the last gradle project in our system to sbt, I had to pass specific parameters to the scalatest test runner (thats when I created this ticket).. have to look again tomorrow at work... will report back.

**Comment by domdorn** [comment]
I checked again and they are generated correctly by default. I'll close this ticket.
