### ISSUE TITLE
zio 2.0: provide equivalent of `_.locally(SomeLogAnnotation, value)` in new logging mechanism

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6146]
`zio-logging` provides a way to store a key-value pair (e.g. "correlationId" -> "abcd", "userId" -> "domdorn") in the logger which is then passed down to MDC and thus will be transfered to third party systems like kibana. 
The new logging functionality in zio 2.0-M6-2 provides `LogSpan`s, however they are there for measuring how long a span was used. 
A functionality like `_.locally(..)` is missing and should be provided for upgrading 1.x apps.

**Comment by adamgfraser** [comment]
The logging functionality in ZIO is intended to provide the basic interface for logging that other libraries can rely on, not to replace higher level logging libraries like ZIO logging. I would wait for `zio-logging` to be released for ZIO 2.0 before upgrading applications that use functionality from that library.

**Comment by domdorn** [comment]
please wait with merging your PR, I'll want to show you my approach with a PR

**Comment by adamgfraser** [comment]
I think you are right that you can represent spans as "just another annotation", basically the stack is just the value of an annotation, but given the importance of spans as a concept I think it is nice to be able to access them directly in the logger versus having to go through an annotation.

**Comment by domdorn** [comment]
ok, after failing to setup my current dev environment (intellij is confused and unable to resolve various zio classes) and reviewing your PR again, I conclude that its indeed a good idea to keep spans and annotations apart. Maybe we can even provide a way to access the annotations? e.g. use `ZIO.logAnnotate(key, value)` to store something and `ZIO.logAnnotations` to retrieve the `LogAnnotations` object? 

Also, do the `LogSpan`s and Annotations propagate to child fibers?

**Comment by adamgfraser** [comment]
Added in my latest commit. Yes they are propagated to child fibers.

**Comment by domdorn** [comment]
perfect. now we need to make appropriate helpers on `ZStream` e..g 
 
```scala

val stream = for { 
 _ <- ZStream.unit
 _ <- ZStream.logAnnotate("calculationId", UUID.randomUUID)
 _ <- ZStream.logDebug("calculationId has been set")
 _ <- for { 
    _ <- ZStream.unit
    _ <- ZStream.log("in child stream")
  } yield ()
 } yield () 
 
zio.Runtime.unsafeRun( stream.logAnnotate("correlationId", UUID.randomUUID()).runNow )
 
 ```

**Comment by domdorn** [comment]
The PR looks already excellent! 
What would be the way to disable logging for a certain effect / stream / managed ? 

e.g. something along the lines
```scala

val e = { 
 _ <- ZIO.unit
 _ <- ZIO.logDebug("something")
 } yield ()
 
zio.Runtime.default.unsafeRun( e.logLevel(None) ) 
```

**Comment by adamgfraser** [comment]
Thanks! And thanks for all your feedback!

It is up to loggers to decide what to do with log messages, potentially just doing nothing if they are not of a high enough severity. You can use the `filterLogLevel` operator on loggers to specify that you only want to log messages at a certain log level.

**Comment by domdorn** [comment]
hmmm.. with `zio-logging` I once achieved that by doing (kind of)  
```scala
myEffect.updateService[Logger[String]](new Logger { 
def log (...) = ZIO.unit
})
```

could I do something similar here? e.g. switch out the logger for a certain effect ?

**Comment by adamgfraser** [comment]
Yes the logger is part of the `RuntimeConfig` so you can use the `withRuntimeConfig` operator to run a particular effect with a different runtime configuration.

**Comment by domdorn** [comment]
perfect! it would be great if you could do a `2.0.0-M6-3` or `2.0.0-M7` release once this is merged.. then I can take another stab at migrating my service.. :-)

**Comment by adamgfraser** [comment]
I don't think we will be doing another release before `RC1`. 😃

**Comment by domdorn** [comment]
oh.. I'm fine with a `RC1` soon as well :-D 

If I would be to provide a `ZLogger` implemention that e.g. would bridge to SLF4J or render JSON, where should I put that? extra project? additional module in this project?

**Comment by adamgfraser** [comment]
That is exactly what `zio-logging` is for! 😃

**Comment by domdorn** [comment]
I think it now ticks all the boxes I need for migration. once you publish a new M7 or RC1, I'll be able to try out and see what's needed to replace the `zio-logging` 0.5.something version in my services (and possibly provide logger implementations)

**Comment by domdorn** [comment]
:( this didnt make it into the RC1... Can I help somehow?

**Comment by adamgfraser** [comment]
There is ongoing work in `zio-logging` around log annotations and we are still figuring out what belongs there versus in ZIO Core. Stay tuned.
