### ISSUE TITLE
zio-test: feature request to add never and times / exactly utility methods to Expectation type

### ISSUE THREAD

**Issue by ksarath** [zio/zio#6167]
Would like to request to add the below utility methods to `Expectation`

- `times(n)` or `exactly(n)` to test whether the expectation was called exactly `n` times
- `never` to test a never called expectation

**Comment by alexvanolst** [comment]
As far as I can tell these both exist on ZIO 1.x and 2.x

**Comment by adamgfraser** [comment]
@ksarath Going to close this for now as both of these operators already exist but please feel free to re-open if there is something else you would like to see!

**Comment by ksarath** [comment]
@alexvanolst & @adamgfraser,

I do see `atMost`, `atLeast`, `repeats` and `optional` etc options on `Expectation`.

Let's say I have the following 

```scala
trait Service1 {
  def doSomething(a: Int): Task[Int]
}

object Service1Mock extends Mock[Has[Service1]] {
  object doSomethingMethod extends Method[Int, Throwable, Int]

  val compose = ZLayer.fromService(proxy =>
    new Service1 {
      override def doSomething(a: Int) = proxy(doSomethingMethod, a)
    }
  )
}
```

Now how do I set my expectation such as `Service1Mock.doSomethingMethod(equalTo(1), value(1))` was never called or called exactly 1 time. 

Right now I use `repeats` to achieve this like
```scala
Service1Mock.doSomethingMethod(equalTo(1), value(1)).repeats(0 to 0)

Service1Mock.doSomethingMethod(equalTo(1), value(1)).repeats(1 to 1)```
