### ISSUE TITLE
Memory leak when using ZStream.tick()

### ISSUE THREAD

**Issue by ajrnz** [zio/zio#6186]
In 2.0.0-RC1 running the following causes a progressive memory leak, CPU usage also increases to max with no GC pressure.

```scala
    ZStream.tick(50.millis)
      .zipRight(ZStream.fromIterator{ Iterator.from(0) })
      .tap{ x => printLine(s"$x")}
      .runDrain
      .exitCode
```

It doesn't seem to matter which zip version you use or the order of the zip. Using `jstack` sometimes I see large stack traces in the scheduler (~1000 items -  in the scala iterator internals). I've no idea if this is normal.

The same code runs without issue on 1.0.13.

**Comment by vigoo** [comment]
Could you share some details on how fast this happens for you? How much CPU and memory increase per 1000 elements for example? I would like to make sure I'm reproducing it properly

**Comment by ajrnz** [comment]
I put 50 milliseconds in the example so that it was a rate any clock could keep up with. However if you make the rate faster, say 10ms then you start to see a noticeable slowdown at about 1000 elements (zio1 has no problems with this rate).

At about 1000 elements I see (using VisualVM) about 16MB allocated as Int array

![image](https://user-images.githubusercontent.com/1515832/146909264-7e58ccef-d129-4e50-a3c1-89c1114a8643.png)

It's pretty much maxing out one CPU by this stage.

**Comment by vigoo** [comment]
Thanks for the details! I'm working on getting rid of the unnecessary chunk operations, then we will see if further optimizations are necessary.
