### ISSUE TITLE
sbt script fails with JDK 17 (JVMCI)

### ISSUE THREAD

**Issue by eaborm** [zio/zio#6219]
The Java-level JVM compiler interface (JVMCI) has been removed from JDK 17, but the sbt script tries to enable it with JVM options "-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler".  The result is that the sbt script fails to start with error "Cannot use JVMCI compiler: No JVMCI compiler found".

As a temporary workaround, I have removed those options from line 260 of my local copy of the sbt script. I am not sure how the project uses JVMCI, but it generally seems to be working without those options.

**Comment by adamgfraser** [comment]
@eaborm Thanks for reporting! I just submitted a PR to update the SBT script to resolve.
