### ISSUE TITLE
hasSubset is broken when right argument contains duplicate.

### ISSUE THREAD

**Issue by strokyl** [zio/zio#6229]
Currently the following test break:
```
    test("hasSubset must succeed when the other iterable is a subset of the iterable but with duplicate") {
      assert(Seq(1, 2, 3, 4))(hasSubset(Seq(1, 2, 2, 3, 3)))
    },
```
The fix is really easy, we just need to replace:
```
  def hasSubset[A](other: Iterable[A]): Assertion[Iterable[A]] =
    hasIntersection(other)(hasSameElements(other))
```
by:
```
  def hasSubset[A](other: Iterable[A]): Assertion[Iterable[A]] =
    hasIntersection(other)(hasSameElementsDistinct(other))
```

I can contribute if you don't think the solution would be to change the signature of `hasSubset` to `Set` instead of `Iterable`

**Comment by adamgfraser** [comment]
I think the current behavior is correct. `1, 2, 2, 3, 3` is not a subset of `1, 2, 3, 4`. `2` and `3` appear two times in the left hand side but only one time in the right hand side.

More formally, if we think of these as multi sets we can represent it as the left being `Map(1 -> 1, 2 -> 1, 3 -> 1, 4 -> 1)` and the right as being `Map(1 -> 1, 2 -> 2, 3 -> 2)` and define `right` as a subset of `left` if every element in `right` appears at least as many times in `left`.
