### ISSUE TITLE
ZIO 2.x: Renaming the `ZIO#toManagedWith` operator to `ZIO#toManagedWithZIO`

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6237]
Our current implementation of ZIO#toManaged doesn't line up with `ZIO.serviceWith` or `ZIO.serviceWithZIO` operators.  As a user, I expect the `ZIO#toManagedWith` to not require an effectful operation, like what the `ZIO.serviceWith` does.

Instead, we may need to add another operator for non-effectful operations:

```scala
ZIO.attempt(scala.io.Source.fromFile("file.txt"))
  .toManagedWith(_.close())
```

Please correct me if I’m wrong!

**Comment by adamgfraser** [comment]
I'm not sure we need another variant here. In operators like `serviceWith` we can potentially do something with a service that is not effectual. For example, consider:

```scala
trait Server {
  def port: Int
}
```

Here `port` just gives us a constant value of the port, and so something like `ZIO.serviceWith[Server](_.port)` makes a lot of sense.

In contrast, a finalizer is inherently effectual. The type of a finalizer is `URIO[R, Any]` so it doesn't have any meaningful return value and the only way it can do anything at all is by performing some kind of effect. In the example above `close` is performing the side effect of closing the file so `close` really needs to be wrapped in an effect constructor or we need to use another constructor that does this wrapping for us like `acquireReleaseSucceed`.

**Comment by khajavi** [comment]
Ah! You are right! The `close` is inherently effectual. I didn't use the proper term "effectful" to introduce my point.

I was wondering if we can have a consistent naming within operators like`*with[A](something)` and `*withZIO[A](somethingElse)` where the `something` should be a non-zio value whether it is a constant value like the `port` you mentioned or the `close` operation which performs a side effect, and the `somethingElse` for zio values. 

Following your explanation, I am convinced that it doesn't make sense to do that.

Thank you!

**Comment by adamgfraser** [comment]
Definitely! All your questions as you have been working through the documentation are super valuable!
