### ISSUE TITLE
Publish ZIO for Scala 3 and scala-native

### ISSUE THREAD

**Issue by st33v3** [zio/zio#6247]
Scala native project added support for Scala 3 sources since version 0.4.3 (currently in release candidate stage). ZIO currently supports scala native or scala 3, but not both. Is it possible to release artifacts for this combination? Or at least is it on project roadmap?
Perhaps I could build native ZIO for scala 3 myself, in such case a would appreciate some hints what and where I should change in ZIO build settings.

**Comment by heksesang** [comment]
What's the status on this?

**Comment by ThijsBroersen** [comment]
Exists since v2.0.1? -> https://mvnrepository.com/artifact/dev.zio/zio_native0.4_3/2.0.1
