### ISSUE TITLE
checkM should not run more tests than the values it can generate from generators

### ISSUE THREAD

**Issue by mbaechler** [zio/zio#6288]
```
      sealed trait Parent
      case object Foo extends Parent
      case object Bar extends Parent
      val gen: Gen[Random & Sized, Parent] = DeriveGen[Parent]

      testM("adt values are tested several times") {
        checkM(gen) { value =>
          for {
            _ <- ZIO.debug(value)
          } yield assertCompletes
        }
      }
```

This test is run a large number of times. It could limit the number of run to 2 as there's only 2 valid instances of Parent.

**Comment by adamgfraser** [comment]
The semantics of `check` are "generate the specified number of samples". If you want to generate all the samples of a generator you can use `checkAll` instead.

**Comment by mbaechler** [comment]
Thank you for the answer @adamgfraser
