### ISSUE TITLE
ZHub / ZStream interop not as advertised // `intoHub` and the like

### ISSUE THREAD

**Issue by simlei** [zio/zio#6338]
Hi all, I am getting an uncomfortable compiler message when trying out Hub/ZHub (2.0.0-RC2)
```scala
    hub <- ZHub.unbounded[GraphHistory[Either[Err, ?]]]
    merged = streamP.merge(streamQ).merge(streamE)
    history: ZStream[Any, Nothing, GraphHistory[Either[Err, ?]]] = merged.scan(GraphHistory.ofEmpty(ParamsGraph))((acc, fresh) => acc.run(fresh))
    _ <- history.intoHub(hub)
```
The fault lies in the line following the  `history: [...]` line. `intoHub` expects another argument. The compiler has to say:
```
src/main/scala-3/rsaelgamal/RSAUIMainController.scala|212| [E007] Type Mismatch Error
|| [error] 212 |    _ <- history.intoHub(hub)
|| [error]     |                         ^^^
|| [error]     |Found:    (hub : 
|| [error]     |  zio.ZHub[Any, Any, Nothing, Nothing, 
|| [error]     |    bci.metamodel.Graphs.GraphHistory[Either[rsaelgamal.RSAModel.Err, ?]]
|| [error]     |  , bci.metamodel.Graphs.GraphHistory[Either[rsaelgamal.RSAModel.Err, ?]]]
|| [error]     |)
|| [error]     |Required: zio.ZHub[Any, Nothing, Nothing, Any, 
|| [error]     |  zio.stream.Take[Any, 
|| [error]     |    bci.metamodel.Graphs.GraphHistory[Either[rsaelgamal.RSAModel.Err, ?]]
|| [error]     |   & bci.metamodel.Graphs.GraphHistory[Either[rsaelgamal.RSAModel.Err, _]]]
|| [error]     |, Any]
|| [error] one error found
```

A more-boiled-down example would be:
```scala
    val hub = ZHub.unbounded[Int]
    val s = ZStream(1,2,3,4)
    hub.flatMap { h =>
      s.intoHub(h)
    }
```
Error here is:
```
|| [error] 10 |      s.intoHub(h)
|| [error]    |                ^
|| [error]    |Found:    (h : zio.Hub[Int])
|| [error]    |Required: zio.ZHub[Any, Nothing, Nothing, Any, zio.stream.Take[Any, Int], Any]
```

There is more...
`intoQueue` suffers similar problems, actually, I had to forgo all my attempts with `ZHub` and the like and use `ZStream#broadcast`.

The only currently documented working example on `ZHub` is using contrived quasi-sequentialization with a promise [1]. Is that what `intoHub` etc. are supposed to alleviate? If so, I would be very happy to get to try it out :)

After getting stoked reading ["Hubs play extremely well with streams."](https://zio.dev/next/datatypes/concurrency/hub#hubs-and-streams) I must say I find myself a bit tired and disappointed but of course, that does neither lessen the great strides ZIO has made with 2.0 from what I can glean. So take it nonconfrontational please :)

[1]
```scala
import zio._
import zio.stream._

object Example extends App {

  def run(args: List[String]): URIO[ZEnv, ExitCode] =
    for {
      promise <- Promise.make[Nothing, Unit]
      hub     <- Hub.bounded[String](2)
      stream = ZStream.managed(hub.subscribe).flatMap { queue =>
                 ZStream.fromEffect(promise.succeed(())) *>
                   ZStream.fromQueue(queue)
               }
      fiber     <- stream.take(2).runCollect.fork
      _         <- promise.await
      _         <- hub.publish("Hello")
      _         <- hub.publish("World")
      collected <- fiber.join
      _         <- ZIO.foreach(collected)(console.putStrLn(_)).orDie
    } yield ExitCode.success
}
```

**Comment by adamgfraser** [comment]
As discussed on Discord, you need to use `Hub.make[Take[Nothing, Int]]` in your example. `Take` is an algebraic data type that represents the different potential results of pulling from a stream, including getting a chunk of values, an error, or an end of stream signal. I will take a look at the documentation to see if there is more we can do here.

**Comment by adamgfraser** [comment]
As discussed previously, my understanding is you were using the `unsafeRunSync` which returns an `Exit` value containing either the successful result of the computation or the full cause of the failure, which you can then handle as desired (e.g. logging it, throwing it, etc...). The `unsafeRun` variant wraps the failure in a `FiberFailure` and throws it. So I don't think there is any unexpected behavior here, though happy to discuss further.
