### ISSUE TITLE
foldWhile in zio-streams doesn't take into account the termination condition

### ISSUE THREAD

**Issue by digy** [zio/zio#6339]
Running this with zio and zio-streams version 1.0.13

```scala
    ZStream
      .fromIterable(
        List(1, 1, 1, 1, 1)
      )
      .foldWhile(0)(_ < 3)(_ + _)
      .flatMap(x => putStrLn(x.toString))
```
Produces an effect that prints 5, while I would expect this to produce an effect that prints 3.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.
