### ISSUE TITLE
Generalize ZStream with input/output error types to allow for combinators like `mapError`

### ISSUE THREAD

**Issue by runtologist** [zio/zio#634]
mapError should allow for transforming errors before running the Stream. Proposed signature:

```scala
def mapError[E2](f: E => E2): ZStream[R, E2, A]
```

**Comment by runtologist** [comment]
The only way I could make it work so far is by going via a Queue unfortunately. Any better proposals are welcome.

**Comment by iravid** [comment]
Hah yeah, this is interesting, `E` is in fact in contravariant position when working inside the `fold` function. I didn't realize this up till now. cc @jdegoes 

It might be impossible to actually implement directly. I'll play around with this too.

**Comment by jdegoes** [comment]
@iravid We just need producer / consumer error types in ZStream

**Comment by iravid** [comment]
type parameter galaxy brain..

**Comment by iravid** [comment]
@jdegoes Ah, ok, I get what you mean - like how `IndexedContT` is formulated?

**Comment by iravid** [comment]
@runtologist this is what it should end up as, if you're up for the task:
```scala
package object stream {
  type Stream[E, A] = ZStream[Any, E, E, A]
  type StreamR[E, A] = ZStream[R, E, E, A]
}

object ZStream {
  type Fold[R, -EI, +EO, +A, S] = ZIO[Any, Nothing,
    (S, S => Boolean, (S, A) => ZIO[R, EI, S]) => ZIO[R, EO, S]]
}

trait ZStream[-R, +EI, +EO, +A] extends Serializable { self =>
  import Stream.Fold

  def fold[R1 <: R, EI1 >: EI, EO1 >: EO, A1 >: A, S]: Fold[R1, EI1, EO1, A1, S]

  def foldLeft[A1 >: A, S](s: S)(f: (S, A1) => S): ZIO[R, EO, S] =
    self.fold[R, EI, EO, A1, S].flatMap(f0 => f0(s, _ => true, (s, a) => IO.succeed(f(s, a))))

  def map[B](f: A => B): ZStream[R, EI, EO, B] =
    new ZStream[R, EI, EO, B] {
      def fold[R1 <: R, EI1 >: EI, EO1 >: EO, B1 >: B, S]: Fold[R1, EI1, EO1, B1, S] =
        IO.succeedLazy { (s, cont, f0) =>
          self.fold[R1, EI1, EO, A, S].flatMap { f1 =>
            f1(s, cont, (s, a) => f0(s, f(a)))
          }
        }
    }

  def mapError[EO2](f: EO => EO2): ZStream[R, EI, EO2, A] = 
    new ZStream[R, EI, EO2, A] {
      def fold[R1 <: R, EI1 >: EI, EO3 >: EO2, A1 >: A, S]: Fold[R1, EI1, EO3, A1, S] =
        IO.succeedLazy { (s, cont, f0) =>
          self.fold[R1, EI1, EO, A, S].flatMap { f1 =>
            f1(s, cont, (s, a) => f0(s, a)).mapError(f)
          }
        }
    }
}
```

It's a big change, but we can probably take a more incremental approach and not convert all combinators to the generalized form at once.

**Comment by runtologist** [comment]
hehe, yes, I've been at that version of mapError, but hoped there would be another way than extending the type signatures. :) I'll make a stab at it.

**Comment by runtologist** [comment]
Observations so far:

There are a few places where `EI =:= EO` (basically everything returning `Stream` or `StreamR`). Due to 
```scala
StreamZ.fold[R1 <: R, EI1 >: EI, EO1 >: EO , A1 >: A, S]: Fold[R1, EI1, EO1, A1, S]
```
`EI1` and `EO1` may diverge.  In a few places, where the `E` is `Nothing`, there is a workaround, but I  don't see a generic way around this.  

Also, I don't know yet, what to do with `run`. I think this change also requires changes to `Sink`. However, if this is done naively, `Sink` needs to fail in `EI` in `step` and in `IO` in `extract`, which does not feel right.

Any opinions?

**Comment by runtologist** [comment]
Another one: Also after this change, it is IMO impossible to build a "Processor", i.e. a `Stream with Sink`, which just passes everything through. Most streaming libraries/frameworks allow that. Implementing a Processor probably is a good test for whether errors really are handled in a compositional way. I'll think a bit more about what changes to Sink would be needed to make that possible.

**Comment by iravid** [comment]
I realize now that the variance signature for EI1 and EO1 may be wrong; it is possible that one of them should actually be a subtype of the original error, as they occur on different sides of the function. Not entirely sure about this but worth verifying.

If so, then it simplifies the case where EI ~ EO because then EI1 and EO1 can be widened to the same type.

**Comment by jdegoes** [comment]
Paste from a pull request:

-------

I think we have to separate producer errors from consumer errors.

```scala
ZStream[-R, +ProducerError, +ConsumerError, +A]
```

like `ZQueue`. 

Then things like `mapError` on `ZStream` will operate only over `ProducerError`. That is, they will not say anything about consumer errors.

Consumer errors are those generated from effectful folding functions / sinks. We can have separate combinators for those, but we need to know the relationship between producer errors and consumer errors.

If we want to use subtyping (which is maybe the right choice???), then when running a stream, you should get the lowest common supertype between producer error and consumer error.

**Comment by iravid** [comment]
I had some time to work on this. Here's a definition of `ZStream` that separates consumer errors (which are errors emitted by the continuation given to the fold), and producer errors (which are errors that the effectful fold may emit):
```scala
trait ZStream2[-R, -EC, +EP, +A] extends Serializable { self =>
  def fold[R1 <: R, EC1 <: EC, EP1 >: EP, A1 >: A, S](s: S)(cont: S => Boolean)(
    f: (S, A1) => ZIO[R1, EC1, S]
  ): ZIO[R1, EP1, S]

  def map[B](f0: A => B): ZStream2[R, EC, EP, B] =
    new ZStream2[R, EC, EP, B] {
      def fold[R1 <: R, EC1 <: EC, EP1 >: EP, A1 >: B, S](
        s: S
      )(cont: S => Boolean)(f: (S, A1) => ZIO[R1, EC1, S]): ZIO[R1, EP1, S] =
        if (cont(s)) self.fold(s)(cont)((s, a) => f(s, f0(a)))
        else UIO.succeed(s)
    }

  def mapError[EP1](f0: EP => EP1): ZStream2[R, EC, EP1, A] =
    new ZStream2[R, EC, EP1, A] {
      def fold[R1 <: R, EC1 <: EC, EP2 >: EP1, A1 >: A, S](
        s: S
      )(cont: S => Boolean)(f: (S, A1) => ZIO[R1, EC1, S]): ZIO[R1, EP1, S] =
        self.fold[R1, EC1, EP, A1, S](s)(cont)((s, a1) => f(s, a1)).mapError(f0)
    }

  def run[R1 <: R, E >: EP <: EC, A0, A1 >: A, B](sink: ZSink[R1, E, A0, A1, B]): ZIO[R1, E, B] =
    sink.initial.flatMap { state =>
      self
        .fold[R1, EC, EP, A1, ZSink.Step[sink.State, A0]](state)(ZSink.Step.cont) { (s, a) =>
          sink.step(ZSink.Step.state(s), a)
        }
        .flatMap { step =>
          sink.extract(ZSink.Step.state(step))
        }
    }

  def mapConsumerErrors[EC1](f0: EC1 => EC): ZStream2[R, EC1, EP, A] =
    new ZStream2[R, EC1, EP, A] {
      def fold[R1 <: R, EC2 <: EC1, EP1 >: EP, A1 >: A, S](
        s: S
      )(cont: S => Boolean)(f: (S, A1) => ZIO[R1, EC2, S]): ZIO[R1, EP1, S] =
        self.fold[R1, EC, EP, A1, S](s)(cont)((s, a1) => f(s, a1).mapError(f0))
    }
}
```

This looked pretty promising! Note how for combinators that actually run the stream, like `run`, we need to relate both `EP` and `EC` to the `E` parameter so they may be unified.

So I got around to implmenting the constructors. Here's `fromEffect`:
```scala
  def fromEffect[R, E, A](a: ZIO[R, E, A]): ZStream2[R, E, E, A] =
    new ZStream2[R, E, E, A] {
      def fold[R1 <: R, EC1 <: E, EP1 >: E, A1 >: A, S](
        s: S
      )(cont: S => Boolean)(f: (S, A1) => ZIO[R1, EC1, S]): ZIO[R1, EP1, S] =
        if (cont(s)) a.flatMap(f(s, _))
        else ZIO.succeed(s)
    }
```

That was fairly simple. Any continuation given to `fromEffect`'s fold may only fail with `E`; and the fold itself may fail with `E`.

However, something weird happens with `fromChunk`, which should delegate the effectful fold to the chunk itself:
```scala
  def fromChunk[A](c: Chunk[A]): ZStream2[Any, Any, Nothing, A] =
    new ZStream2[Any, Any, Nothing, A] {
      def fold[R, EC, EP, A1 >: A, S](
        s: S
      )(cont: S => Boolean)(f: (S, A1) => ZIO[R, EC, S]): ZIO[R, EP, S] =
        c.foldMLazy(s)(cont)(f)
    }
```

This does not compile with the following error on the call to `foldMLazy`:
```
scalac: type mismatch;                              
 found   : (S, A1) => scalaz.zio.ZIO[R,EC,S]        
 required: (S, A) => scalaz.zio.ZIO[R,EP,S] (lsp-ui)
```

The problem is of course that the error type of the continuation and the output of the fold are different. Any ideas?

**Comment by runtologist** [comment]
That's the point where I got stuck as well. :/

**Comment by iravid** [comment]
Snippet from @jdegoes that might have the right variance incantation: https://scalafiddle.io/sf/Zenzi9P/1

**Comment by iravid** [comment]
To avoid the generalized subtyping constraints in the snippet (which impose either `asInstanceOf` calls or `mapError(ev)` calls), this monstrous signature for `fold` can be used:

```scala
trait ZStream[R, +EP, -EC, +A] {
  def fold[R1 <: R, E >: EC1, EP1 >: EP <: E, EC1 <: EC, A1 >: A, S](z: S)(cont: S => Boolean)(f: (S, A1) => ZIO[R1, EC1, S]): ZIO[R1, E, S]
}
```

**Comment by mschuwalow** [comment]
@runtologist are you still working on this?
If not I would like to take a stab at it.

**Comment by iravid** [comment]
@mschuwalow I think it's ok for you to get started on this, thanks for picking this up!

**Comment by runtologist** [comment]
@mschuwalow go ahead, I'm quite busy atm.

**Comment by mschuwalow** [comment]
Alright, will do. Let's see how far I can get until the types get me. :)

**Comment by mschuwalow** [comment]
I experimented a bit with the signature posted by @iravid.
Sadly, I was unable to implement mapConsumerError / mapProducerError faithfully. Also the type signatures seem far more complex than reasonable. It would be great if I could get some early feedback on whether what I'm doing seems reasonable. This is what I currently have:
https://scastie.scala-lang.org/iqA30zFvTiWVsHWZdAbKTQ

**Comment by iravid** [comment]
Yes, those signatures do seem exotic 😂 I'll have time later this week hopefully to see what went wrong there.

**Comment by mschuwalow** [comment]
Cool. Thank you :sweat_smile:

**Comment by jdegoes** [comment]
@mschuwalow @iravid 

After thinking about this more, I think the "most powerful" / primitive / base fold should require _explicit unification of error types_, e.g., something like [this](https://scalafiddle.io/sf/puJOwch/0).

Syntax classes can be used to do the rest, but the foundation should be explicit.

**Comment by iravid** [comment]
This approach does sound saner rather than juggling variance signatures everywhere

**Comment by iravid** [comment]
Random thought: most concurrency combinators (which pipe elements through a queue) would probably require a unification of the error type as well

**Comment by mschuwalow** [comment]
This indeed looks far saner. I'll get started with this later this week. Depending on how much work this ends up being it probably makes sense to split this up into multiple PRs. @iravid what do you think is the best way to split this up?

**Comment by iravid** [comment]
I think a big PR that changes all the signatures is unavoidable. Feel free to write it out and we’ll hold the rest of the PRs until it’s done.

Excited about this!

**Comment by mschuwalow** [comment]
Hi,
Just wanted to say that I'm still working on this. I ended up being busier than I expected, but I'll try to get some good progress on this next week.

As far as I can currently tell most interesting combinators will end up looking something like this
```
  def mapConsumerError0[ECC, EC1 <: EC, EP1 >: EP](f0: ECC => EC1, f1: EC1 => EP1): ZStream[R, EP1, ECC, A] =
    new ZStream[R, EP1, ECC, A] {
      def fold0[R1 <: R, EP2 >: EP1, ECC1 <: ECC, E, A1 >: A, S](ep: EP2 => E, ec: ECC1 => E): ZStream.Fold[R1, ECC1, E, A1, S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          self.fold0[R1, EP1, EC1, E, A1, S](ep, f1 andThen ep).flatMap { fold =>
            fold(s, cont, (s, a) => f(s, a).mapError(f0))
          }
        }
    }

  final def flatMap0[R1 <: R, E2, EPP >: EP, ECC <: EC, B](f0: A => ZStream[R1, ECC, ECC, B], f1: ECC => EPP): ZStream[R1, EPP, ECC, B] =
    new ZStream[R1, EPP, ECC, B] {
      override def fold0[R2 <: R1, EPP1 >: EPP, ECC1 <: ECC, E, B1 >: B, S](ep: EPP1 => E, ec: ECC1 => E): Fold[R2, ECC1, E, B1, S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          self.fold0[R2, EPP1, ECC, E, A, S](ep, f1 andThen ep).flatMap { foldOuter =>
            foldOuter(s, cont, (s, a) => {
              f0(a)
                .fold0[R2, ECC, ECC, ECC, B1, S](identity, identity)
                .flatMap { foldInner =>
                  foldInner(s, cont, f)
                }
                .use(ZIO.succeed)
            })
          }
        }
    }
```
With versions in an implicit class that use either
```
(implicit ep: EP <:< E, ec: EC <:< E)
```
or
```
(implicit ev: EC <:< EP)
```
to map the errors. Is this the right way to organize?

Also I'm currently not quite convinced that this is the right way to go. An alternative approach that I think could be better is:
```
trait ZStream[-R, +EP, +A] extends Serializable { self =>
  def fold0[R1 <: R, E, A1 >: A, S](ep: EP => E): Fold[R1, E, A1, S]
}
```
This still allows to trivially implement mapError but has cleaner type signatures. The one disadvantage I see is that it is impossible to implement combinators on consumer errors, but I don't know how big of an issue that is.

**Comment by jdegoes** [comment]
@mschuwalow 

> to allow versions without explicit error mapping. Is this the right way to organize?

Yes. The base version should require explicit mapping, and syntax can perform the mapping in common cases, where error types can be implicitly unified.

> Also I'm currently not quite convinced that this is the right way to go. An alternative approach that I think could be better is:

I like this. It's quite a bit simpler. Sinks already have "combinators on consumer errors", so maybe the lack of that on Stream wouldn't be that limiting.

@iravid ???

**Comment by iravid** [comment]
I'd love to take a look at a WIP branch. I get lost in the variance jungle without seeing everything fit together.

**Comment by mschuwalow** [comment]
Sure. A branch implementing the approach mentioned in my last comment is here https://github.com/mschuwalow/scalaz-zio/commit/4853f711b06cfbfbf42de09a475e9fbc5c2bf434.
If you want I can also do one with the more polymorphic version.

**Comment by iravid** [comment]
@mschuwalow I took a look and really liked how everything was formulated in terms of foldMapError, and especially how most uses of `ZStream#fold` remain unchanged. 

I agree that this looks like the right approach.

Could you try implementing `catchAll` and `orElse`?

**Comment by mschuwalow** [comment]
@iravid Sure I'll give it a try once I get home.

**Comment by iravid** [comment]
I did not manage to wrangle `catchAll` into compiling, maybe you'll have more luck:
```scala
  final def catchAll[R1 <: R, E1 >: E, A1 >: A](catcher: E => ZStream[R1, E1, A1]): ZStream[R1, E1, A1] =
    new ZStream[R1, E1, A1] {
      def foldMapError[R2 <: R1, E2, A2 >: A1, S](e: E1 => E2): Fold[R2,E2,A2,S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          for {
            fold <- self.foldMapError[R2, E2, A2, S](e)
            s1    <- fold(s, cont, f).catchAll { e2 =>
              val stream = catcher(e2)
            }
          } yield s1
        }
    }
```

**Comment by mschuwalow** [comment]
@iravid I added version of both to the branch. Sadly I was not able to write catchAll without using a
queue.
```
final def catchAll[R1 <: R, E1, A1 >: A](catcher: E => ZStream[R1, E1, A1], capacity: Int = 12): ZStream[R1, E1, A1] =
  new ZStream[R1, E1, A1] {
    def foldMapError[R2 <: R1, E2, A2 >: A1, S](e: E1 => E2): ZStream.Fold[R2, E2, A2, S] =
      ZManaged.succeedLazy { (s, cont, f) =>
        for {
          out    <- Queue.bounded[Take[E1, A2]](capacity).toManaged(_.shutdown)
          _      <- self.foreach(a => out.offer(Take.Value(a)).unit).foldM(
                      err =>
                        catcher(err).foreach(a => out.offer(Take.Value(a)).unit).foldCauseM(
                          cause => out.offer(Take.Fail(cause)),
                          _     => out.offer(Take.End)
                        ),
                      _ => out.offer(Take.End)
                    ).fork.toManaged(_.interrupt)
          s      <- ZStream.fromQueue(out).unTake.foldMapError[R2, E2, A2, S](e).flatMap(fold => fold(s, cont, f))
        } yield s
      }
  }

final def orElse[R1 <: R, E1 >: E, A1 >: A](that: ZStream[R1, E1, A1]): ZStream[R1, E1, A1] =
  new ZStream[R1, E1, A1] {
    def foldMapError[R2 <: R1, E2, A2 >: A1, S](e: E1 => E2): Fold[R2, E2, A2, S] =
      ZManaged.succeedLazy { (s, cont, f) =>
        self.foldMapError[R2, E2, A2, S](e).flatMap { foldThis =>
          foldThis(s, cont, (s, a) => f(s, a)).orElse {
            that.foldMapError[R2, E2, A2, S](e).flatMap { foldThat =>
              foldThat(s, cont, (s, a) => f(s, a))
            }
          }
        }
      }
}
```
I also have a question about the semantics of orElse and catchAll.
If the primary stream fails should the second stream 'resume' from the last element / state (how 
 my catchall currently works) or should the second stream be consumed from scratch instead as in orElse?

**Comment by iravid** [comment]
Yes, we need to preserve the state of the fold when failing over to the second stream. Otherwise things like `ZStream#take` go haywire. We'd need to check how the `orElse` implementation interacts with other combinators that rely on the state.

I admit that I am pretty frustrated that we can't implement `catchAll` directly without going through a queue, but I guess that this is how internal iteration of a sequence works; whenever you're "being called", you can't control the sequence that is being fed to you. There's no way around switching over to an external iteration model to implement something like this.

**Comment by mschuwalow** [comment]
I think that the fact the first stream was partially consumed would only be visible through side effects
by ZStream#mapM or similar. At least I haven't seen anything unintuitive happen in the little testing I have done.

I agree. I believe that us having to go through a queue is a good sign that we haven't found a good encoding for this yet.
I played around with the definition of fold a little more and have something I propose we could try:
```
type Fold[R, EC, +EP, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, EC, S]) => ZManaged[R, Either[EC, EP], S]]
```
So instead of trying to unify the errors we keep them distinct internally. Inside of run they can then be unified without introducing any new constraints. As far as I can tell this allows us to implement everything without going through queues.
I have no intuition  whether the overhead introduced by either is a problem. But I think at least with dottys unions this might be a better approach

**Comment by iravid** [comment]
@mschuwalow Right. I played around with this and it looks like a better direction. It may be better to be slightly more polymorphic and keep the distinction between producer and consumer errors, allowing the combinators that need to distinguish to do so via Either as you suggest:
```scala
trait ZStream2[R, EP, EC, A] { self =>
  def fold[R1 <: R, E, A1 >: A, S](p: EP => E, c: EC => E): ZStream2.Fold[R1, EC, E, A1, S]

  def catchAll[R1 <: R, EP1, A1 >: A](catcher: EP => ZStream2[R1, EP1, EC, A1]): ZStream2[R1, EP1, EC, A1] =
    new ZStream2[R1, EP1, EC, A1] {
      def fold[R2 <: R1, E, A2 >: A1, S](p: EP1 => E, c: EC => E): ZStream2.Fold[R2, EC, E, A2, S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          self.fold[R2, Either[EP, EC], A2, S](Left(_), Right(_)).flatMap { foldSelf =>
            foldSelf(s, cont, f).foldM(
              e =>
                e match {
                  case Left(producerError) =>
                    catcher(producerError).fold[R2, E, A2, S](p, c).flatMap(_.apply(s, cont, f))
                  case Right(consumerError) => ZManaged.fail(c(consumerError))
                },
              s => ZManaged.succeed(s)
            )
          }
        }
    }
}

object ZStream2 {
  type Fold[R, EC, E, A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, EC, S]) => ZManaged[R, E, S]]

  def fromChunk[A](chunk: Chunk[A]): ZStream2[Any, Nothing, Any, A] =
    new ZStream2[Any, Nothing, Any, A] {
      def fold[R1, E, A1 >: A, S](p: Nothing => E, c: Any => E): ZStream2.Fold[R1, Any, E, A1, S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          chunk.foldMLazy(s)(cont)(f).mapError(c).toManaged_
        }
    }
}
```

(I'm not sure Dotty unions would help here, as with unions you lose the distinction between the sides when both have a common supertype)

This is in fact what @jdegoes suggested in this snippet https://scalafiddle.io/sf/puJOwch/0 in https://github.com/zio/zio/issues/634#issuecomment-511210134. We should have listened ;-)

**Comment by mschuwalow** [comment]
@iravid 
I think that property of unions would actually be great because of:
```
  type Fold[R, E, +A, S] = Fold0[R, E, E, A, S]
  type Fold0[R, EC, +EP, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, EC, S]) => ZManaged[R, EC | EP, S]]
```
But you wouldn't be able to pattern match on them because of generics, so it's a stupid idea anyway.

I don't think going back to that signature of fold is a good idea, as it makes working with it quite painful. I also don't quite see the advantage of constraining the consumer error on the stream, unless you have some specific combinators in mind that need that. At least  when making it contravariant on EC, I ran into a lot of problems because ```c: EC => E``` has some subtype of EC as its domain inside of fold. At least for me the types then often ended up not working.

I think our current encoding is actually quite good. It ends up being equivalent do basing the Stream on a fold that returns an either, so we can implement the combinators either (hah) way.
The question would just be which encoding we prefer from an ergonomics / performance perspective.
After that I think I can clean this up , implement any additional combinators we want and open a pr.
Or am I missing something?
```
import zio._
trait ZStream1[-R, +E, +A] { self =>
  import ZStream._
  
  def foldMapError[R1 <: R, E1, A1 >: A, S](e: E => E1): Fold[R1, E1, A1, S]
  def fold0[R1 <: R, EC, EP >: E, A1 >: A, S]: Fold0[R1, EC, EP, A1, S] =
    ZManaged.succeedLazy { (s, cont, f) =>
      self.foldMapError[R1, Either[EC, EP], A1, S](Right(_)).flatMap { fold =>
        fold(s, cont, (s, a) => f(s, a).mapError(Left(_)))
      }
    }
}

trait ZStream2[-R, +E, +A] { self =>
  import ZStream._
  
  def foldMapError[R1 <: R, E1, A1 >: A, S](fe: E => E1): Fold[R1, E1, A1, S] = {
    ZManaged.succeedLazy { (s, cont, f) =>
    	self.fold0[R1, E1, E, A1, S].flatMap { fold =>
      	fold(s, cont, (s, a) => f(s, a)).mapError {
          case Left(e) => e
          case Right(e) => fe(e)
        }
      }
    }
  }
  
  def fold0[R1 <: R, EC, EP >: E, A1 >: A, S]: Fold0[R1, EC, EP, A1, S]
}

object ZStream {
  type Fold[R, E, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, E, S]) => ZManaged[R, E, S]]
  type Fold0[R, EC, +EP, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, EC, S]) => ZManaged[R, Either[EC, EP], S]]
}

```

**Comment by iravid** [comment]
@mschuwalow Thanks for being so dilligent on this :-)

- *`Either` in `Fold`*: Keeping `Fold` polymorphic in the error result type is indeed equivalent to using `Either`. However, keeping `Either` out of the signature has one advantage: combinators that don't need to distinguish between producer/consumer errors can avoid paying the cost of Either. Since it is recoverable by using `Left(_), Right(_)` I lean towards thinking that this is a slightly better choice.

So the signatures would be:
```scala
type Fold[R, EC, +E, +A, S] = ZManaged[R, Nothing, (S, S => Boolean, (S, A) => ZIO[R, EC, S]) => ZManaged[R, E, S]]
  def foldWith[R1 <: R, E, EC, A1 >: A, S](p: EP => E, c: EC => E): ZStream2.Fold[R1, EC, E, A1, S]
  def foldEither[R1 <: R, A1 >: A, EC, S]: ZStream2.Fold[R1, EC, Either[EP, EC], A1, S] =
    foldWith(Left(_), Right(_))
  def fold[R1 <: R, EC, A1 >: A, S](implicit ev: EP <:< EC): ZStream2.Fold[R1, EC, EC, A1, S] =
    ZManaged.succeed { (s, cont, f) =>
      foldEither[R1, A1, EC, S].flatMap { fold =>
        fold(s, cont, f).mapError(_.fold(ev(_), identity))
      }
    }
```
- Having `EC` on the stream has a slightly simplifying effect on the signatures of the folds; without it you'd need to keep `EC` on the method signatures which is slightly more verbose:
```scala
  def foldWith[R1 <: R, E, EC, A1 >: A, S](p: EP => E, c: EC => E): ZStream2.Fold[R1, EC, E, A1, S]
  def foldEither[R1 <: R, A1 >: A, EC, S]: ZStream2.Fold[R1, EC, Either[EP, EC], A1, S] =
    foldWith(Left(_), Right(_))
  def fold[R1 <: R, EC, A1 >: A, S](implicit ev: EP <:< EC): ZStream2.Fold[R1, EC, EC, A1, S] =
    ZManaged.succeed { (s, cont, f) =>
      foldEither[R1, A1, EC, S].flatMap { fold =>
        fold(s, cont, f).mapError(_.fold(ev(_), identity))
      }
    }
```

Having `EC` on the stream also constrains how consumers may fail. Which, when you think of it, means that you can create completely infallible streams - i.e. they can be safely "compiled" into `UIO`. I think this is something that is unavailable when `EC` is free on the methods.

**Comment by mschuwalow** [comment]
Sure. Sorry for taking so long with this.

> Either in Fold: Keeping Fold polymorphic in the error result type is indeed equivalent to using Either. However, keeping Either out of the signature has one advantage: combinators that don't need to distinguish between producer/consumer errors can avoid paying the cost of Either. Since it is recoverable by using Left(_), Right(_) I lean towards thinking that this is a slightly better choice.

I agree that this makes the most sense

> EC on the Stream: Having EC on the stream has a slightly simplifying effect on the signatures of the folds; without it you'd need to keep EC on the method signatures which is slightly more verbose. This is how the signatures look with EC on the trait

This would be with an invariant EC, right? I briefly played around with it and would require
a few clarifications before going further with it.
* How would you recommend encoding StreamPure with this?
* As far as I can tell the combinators that actually change the consumer error would end up looking something like this:
```scala
def handleConsumerErrors[R1 <: R, EC1](onError: EC1 => ZIO[R1, EC, _], ec2: EC => EC1): ZStream1[R1, EC1, EP, A] 
```
I think it is simpler and more intuitive to leave all of this to downstream data structures such as zsink.
In general my mental model here is that EP are "upstream" errors and EC are "downstream" errors. At least from that perspective it feels weird to overly constrain EC. Maybe you can give me an insight  into this.

**Comment by iravid** [comment]
Yes, this is with an invariant `EC`. I tried making it contravariant, but the types stop aligning at that point 🤦🏼‍♂️

Interestingly, we can write `catchConsumerError` like so:
```scala
  def catchConsumerError[R1 <: R, EC1 <: EC, EP1 >: EP, A1 >: A](catcher: EC => ZStream2[R1, EP1, EC1, A1]): ZStream2[R1, EP1, EC1, A1] =
    new ZStream2[R1, EP1, EC1, A1] {
      def foldWith[R2 <: R1, E, A2 >: A1, S](p: EP1 => E, c: EC1 => E): ZStream2.Fold[R2, EC1, E, A2, S] =
        ZManaged.succeedLazy { (s, cont, f) =>
          self.foldEither[R2, A2, S].flatMap { foldSelf =>
            foldSelf(s, cont, f).foldM(
              e =>
                e match {
                  case Left(producerError) => ZManaged.fail(p(producerError))
                  case Right(consumerError) =>
                    catcher(consumerError).foldWith[R2, E, A2, S](p, c).flatMap(_.apply(s, cont ,f))
                },
              s => ZManaged.succeed(s)
            )
          }
        }
    }
```

This does allow us to "eliminate" errors from a stream by going to a stream that has `EC1 = Nothing`. I do wonder about the usefulness of this. You're right in saying that we can defer this to sinks.

Let's start with `EC` on the methods as you suggested; if everything works out we can deal with this later and maybe work on this during one of the upcoming hackathons.
