### ISSUE TITLE
ZPipeline.splitLines lost data in stream.

### ISSUE THREAD

**Issue by linteck** [zio/zio#6360]
If a string is ended with '\r\r\r\n', the ZPipeline.splitLines will lose the line.
val tout = ZStream("AAAAABBBB#\r\r\r\n", "test")  
s2 <- tout.via(ZPipeline.splitLines >>> ZPipeline.map(s => s.trim())).run(ZSink.collectAll)
The s2 will be "Chunk(,test)".  
 The string 'AAAAABBBB" is lost.

**Comment by vigoo** [comment]
Thanks for reporting, I'm checking it
