### ISSUE TITLE
zio-test - in zio2 Assert and TestResult are not interchangeable whereas in zio1 they were

### ISSUE THREAD

**Issue by TimPigden** [zio/zio#6375]
this makes combining them difficult.
We have a big battery of functions that do assert or assertTrue and return the result to other functions that combine them with other results (we're comparing complex data models with many levels of objects)
It all worked fine in zio1 but in zio2 it just would not compile. I ended up having to convert several hundred asserts into assertTrue but that prevents me mixing in things like assert(x)(isApproximatelyEqualTo)  - or whatever it is exactly - without mucking around 
Can they not be re-unified?
I'm ok now but others will find it difficult.

**Comment by kitlangton** [comment]
Currently exploring unifying these two variants.

**Comment by kitlangton** [comment]
#6709 We have achieved convergence!
