### ISSUE TITLE
Issue on Reporting Fatal Error Using RuntimeConfigAspect

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6377]
When I add a `addReportFatal` using `RuntimeConfigAspect`, ZIO‌ runtime cannot reach the specified report function:

```scala
import zio._

object Main extends scala.App {
  val reportFatal =
    RuntimeConfigAspect.addReportFatal { f =>
      println("It should print the fatal message but it doesn't work!")
      throw f
    }

  Runtime.default
    .mapRuntimeConfig(reportFatal)
    .unsafeRun(
      ZIO.attempt(
        throw new StackOverflowError("exceeds the stack bound!")
      )
    )
}
```
I think the cause is here, where the first `System.exit` prevents running the chain of aspects:
https://github.com/zio/zio/blob/ab11bde7df7c52b27c10c507da2fc819456c115a/core/jvm/src/main/scala/zio/RuntimeConfigPlatformSpecific.scala#L67-L73

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
