### ISSUE TITLE
TestClock.advance not interacting as expected with retry(Schedule) Starting with zio-test 1.0.2

### ISSUE THREAD

**Issue by dccorona** [zio/zio#6383]
I'm trying to update some code that tests a retry schedule to the latest zio 1.0 release, but encountering issues with all versions of zio-test >= 1.0.2

Scastie that demonstrates the issue: https://scastie.scala-lang.org/UTva8b5hQlulD8tHBlH82g
If you set zio-test to 1.0.1 or 1.0.0, that code works just fine, but anything >= 1.0.2 results in the test hanging forever.

Am I doing something wrong here in the way I'm testing schedules, or is this a bug?

Here's the source code for reference:

```scala
import zio._
import zio.duration._
import zio.test._
import zio.test.environment._

val prog = {
  for {
    counter <- Ref.make(0)
    effect = for {
      count <- counter.get
      _ <- Live.live(console.putStrLn(s"attempt $count"))
      _ <- counter.set(count + 1)
      _ <- if (count == 0) ZIO.fail("err") else ZIO.succeed(())
    } yield ()
    fiber <- effect.retry(Schedule.fixed(50.milliseconds)).fork
    _ <- TestClock.adjust(1.second)
    _ <- fiber.join
    _ <- Live.live(console.putStrLn("success!"))
  } yield ()
}.provideLayer(testEnvironment)

Runtime.default.unsafeRun(prog)
```

**Comment by adamgfraser** [comment]
@dccorona The `TestClock` works with `TestAspect.fibers` which is automatically installed by the test framework to make sure that all fibers have entered a suspended state before advancing the clock. So you can test your schedule like this:

```scala
testM("schedule") {
  for {
    counter <- Ref.make(0)
    effect = for {
                count <- counter.get
                _     <- Live.live(console.putStrLn(s"attempt $count"))
                _     <- counter.set(count + 1)
                _     <- if (count == 0) ZIO.fail("err") else ZIO.succeed(())
              } yield ()
    fiber <- effect.retry(Schedule.fixed(50.milliseconds)).fork
    _     <- TestClock.adjust(1.second)
    _     <- fiber.join
    _     <- Live.live(console.putStrLn("success!"))
  } yield assertCompletes
}
```

**Comment by dccorona** [comment]
I see - so if I understand correctly, TestClock may not work as expected from outside of ZIO test specs? The code I'm working on upgrading currently leverages ScalaTest - we could port this test suite to ZIO Test and move both our ScalaTest and ZIO Test suites to actually run via JUnit, but I want to confirm that my understanding is actually correct before undertaking that (for various reasons, we aren't using SBT, so installing and running ZIO Test alongside ScalaTest is not straightforward).

**Comment by adamgfraser** [comment]
That's right.

**Comment by dccorona** [comment]
Just to update here: I've demonstrated that using ZIO test works in Scastie, but locally in my actual project I'm still observing issues. What I'm observing is really strange (for example, some but not all of my tests will complete - until I add printing to the effect, then suddenly _all_ of them hang). There are so many moving parts that I'm not sure when I'll be able to figure out how to create a small reproducible example, and once I do it seems likely that it'll end up being completely unrelated to this issue anyway, so I think it's ok to close this and I can open a new one if I can find a way to reproduce.

**Comment by adamgfraser** [comment]
Okay. Please feel free to reopen if you are able to reproduce.

**Comment by TizocFranco** [comment]
Hi, I think I'm having this problem as well. The code snippet from above is actually the most self-contained, reproducible example I can find so far.

```scala
import zio.duration.durationInt
import zio.test.environment.{ Live, TestClock, TestEnvironment }
import zio.test.junit.JUnitRunnableSpec
import zio.test.{ ZSpec, assertCompletes }
import zio.{ Ref, Schedule, ZIO, console }

class Test extends JUnitRunnableSpec {
  override def spec: ZSpec[TestEnvironment, Any] = suite("test") (
    testM("schedule") {
      for {
        counter <- Ref.make(0)
        effect = for {
          count <- counter.get
          _     <- Live.live(console.putStrLn(s"attempt $count"))
          _     <- counter.set(count + 1)
          _     <- if (count == 0) ZIO.fail("err") else ZIO.succeed(())
        } yield ()
        fiber <- effect.retry(Schedule.fixed(50.milliseconds)).fork
        _     <- TestClock.adjust(1.second)
        _     <- fiber.join
        _     <- Live.live(console.putStrLn("success!"))
      } yield assertCompletes
    }
  )
}
```

The above code hangs every single time when I run the unit test, with the following output:
```
attempt 0
``` 

I believe I'm using ZIO 1.0.10, Scala 2.12, running my unit tests in IntelliJ. I would like to help to make this as easily reproducible as possible. Please let me know if there's anything else I can do (or information I can share about my setup) to make this easier to reproduce. Also please let me know if I should open a new issue for this.

**Comment by adamgfraser** [comment]
Hmmm, this appears to work fine.

```scala
import zio.duration.durationInt
import zio.test.environment.{ Live, TestClock, TestEnvironment }
import zio.test.{ ZSpec, assertCompletes }
import zio.{ Ref, Schedule, ZIO, console }

object ExampleSpec extends DefaultRunnableSpec {
  override def spec: ZSpec[TestEnvironment, Any] = suite("test") (
    testM("schedule") {
      for {
        counter <- Ref.make(0)
        effect = for {
          count <- counter.get
          _     <- Live.live(console.putStrLn(s"attempt $count"))
          _     <- counter.set(count + 1)
          _     <- if (count == 0) ZIO.fail("err") else ZIO.succeed(())
        } yield ()
        fiber <- effect.retry(Schedule.fixed(50.milliseconds)).fork
        _     <- TestClock.adjust(1.second)
        _     <- fiber.join
        _     <- Live.live(console.putStrLn("success!"))
      } yield assertCompletes
    }
  )
}
```

Possibly there is an issue with `JUnitRunnableSpec` or the way it is being applied in IntelliJ.

**Comment by TizocFranco** [comment]
Ah, yes, you're right - it took me a second visit to realize you had changed it to extend `DefaultRunnableSpec`. That code works perfectly for me running it from IntelliJ with the change to `DefaultRunnableSpec`.

Referencing issue #3840, it seems that the TestClock relies on the TestAspect [fibers](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/TestAspect.scala#L345) being applied. For DefaultRunnableSpec this is done in [`runSpec`](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/DefaultRunnableSpec.scala#L43). I set a debugger breakpoint on both of those linked lines and observed that when running the above test case with the `DefaultRunnableSpec`, both of those breakpoints were hit, but when using the `JUnitRunnableSpec`, neither was hit (and the test hangs). 

Looking up a level, `runSpec` called from [`RunnableSpec.run`](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/RunnableSpec.scala#L31) which is called from [here](https://github.com/zio/zio/blob/master/test/shared/src/main/scala/zio/test/RunnableSpec.scala#L48). That's the path for the `DefaultRunnableSpec` case, but for the `JUnitRunnableSpec` case it seems there a separate analogous code path [here](https://github.com/zio/zio/blob/master/test-junit/jvm/src/main/scala/zio/test/junit/ZTestJUnitRunner.scala#L85) and the fibers never appear to be applied.

I'm not very familiar with any of this stuff, but it seems like this might be the problem I'm facing. Does this seem reasonable? Should I open an issue to track this?

**Comment by adamgfraser** [comment]
Yes the aspects need to be applied in `JUnitRunnableSpec`.
