### ISSUE TITLE
ZIO 2.0: Replace TimeUnit with ChronoUnit

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6433]

**Comment by emilhotkowski** [comment]
There are tons of uses of `TimeUnit`. Would it make sense to tackle modules one by one? I am offering my time to change `core`.

**Comment by emilhotkowski** [comment]
Could you specify what is the end-goal for this task? I would like to help but I'd rather now what usages we want to change. 
For example ZIO uses `ScalaFiniteDuration` in `Duration` class, which is bound to use `TimeUnit`. On the other hand we could change every use outside of some low level calls to scala library. Start by changing the way we create Duration object and propagate upwards
`def apply(amount: Long, unit: ChronoUnit): Duration = fromNanos(unit.getDuration.toNanos * amount)`

**Comment by jdegoes** [comment]
ZIO uses `java.time.Duration`, although with compatibility for Scala Duration.

I think it would make sense to, in any case where we have a method which accepts `TimeUnit`, have an override that accepts `ChronoUnit`. That could be done in a backward-compatible way, I think.

Thanks for your interest in this!

**Comment by adamgfraser** [comment]
Yeah I don't think it actually appears in many places. Basically the `currentTime` method on `Clock`. It appears a lot in the benchmarks as part of the integration with JMH but I don't think there is any need to change that.

**Comment by emilhotkowski** [comment]
Basically everything related to ZIO functionality should have option to accept `ChronoUnit`, but leave benchmark as it is? I pick this task if it is suitable for first contribution.

**Comment by adamgfraser** [comment]
So I think you could implement an additional constructor for `Duration`:

```scala
object Duration {
  def apply(amount: Long, unit: ChronoUnit) =
    ???
}
```

And then implement another variant of `currentTime`:

```scala
trait Clock {
  def currentTime(unit: ChronoUnit): Long
  private[zio] def unsafeCurrentTime(unit: ChronoUnit): Long
}
```

**Comment by adamgfraser** [comment]
@emilhotkowski Yeah that would be great!

**Comment by emilhotkowski** [comment]
I successfully added constructor and tests to `Duration` class but I have a problem with `Clock` trait. I am making changes on `series/2.x` branch of my fork and when I try to add new `currentTime` signature I get errors related to type eraser.

> [error] /Users/emilhotkowski/Documents/programming/opensource/zio/zio/core/shared/src/main/scala/zio/Clock.scala:32:7: double definition:
> [error] def currentTime(unit: => java.util.concurrent.TimeUnit)(implicit trace: zio.ZTraceElement): zio.UIO[Long] at line 30 and
> [error] def currentTime(unit: => java.time.temporal.ChronoUnit)(implicit trace: zio.ZTraceElement): zio.UIO[Long] at line 32
> [error] have same type after erasure: (unit: Function0, trace: Object): zio.ZIO
> [error]   def currentTime(unit: => ChronoUnit)(implicit trace: ZTraceElement): UIO[Long]
Do you have any input on how to solve this? Maybe there is some common/official way of fixing type eraser problems in ZIO. I wanted to ask before sinking my time into fixing this my way.

**Comment by adamgfraser** [comment]
@emilhotkowski You can use a dummy implicit. See the implementation of `ZIO.fromFile` for an example of this pattern.

**Comment by emilhotkowski** [comment]
@adamgfraser Is there any more work necessary here?

**Comment by adamgfraser** [comment]
@emilhotkowski Yes!
