### ISSUE TITLE
[2.0 Scope] provide equivalent to ZManaged.acquireReleaseWith(..)(..).toLayer

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6449]
Before `2.0.0-RC3` I could do this to create a layer of a ressource: 
```
import com.microsoft.playwright._

val playwrightLayer = ZManaged.acquireReleaseWith(ZIO.attempt(Playwright.create()))(pw => ZIO.succeed(pw.close())).toLayer
```

The new `ZIO.aquireReleaseWith()` does not provide a `.toLayer` method and also the available documentation does not explain how to migrate the code (at least I couldn't find it..).

Please provide a `.toLayer` method or explain how to migrate the code.

**Comment by domdorn** [comment]
Ok, so it looks like we now have a `ZLayer.fromAcquireRelease` for this. 
It would be great if the migration guide could be linked from the release page and a section about scopes be added. 
https://github.com/zio/zio/blob/series/2.x/docs/howto/migrate/migration-guide.md

**Comment by adamgfraser** [comment]
@domdorn You can also use `ZLayer.scoped` to convert a scoped workflow into a layer.
