### ISSUE TITLE
`ZIO#someOrDie` and `ZIO#someOrDieMessage` Operators

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6461]
While working with ZIO error combinators, I found that we haven't these two operators.

**Comment by adamgfraser** [comment]
We actually have a good number of `XYZorFail` operators that don't have `XYZorDie` variants. `Die` causes should be less common than `Fail` causes so I think it makes sense that there wouldn't be a variant for everything. Is there some reason you think we particularly need these two?

**Comment by khajavi** [comment]
I wasn't aware that this is intentional, so I have no urge. 
Yeah, your reasoning makes sense.
