### ISSUE TITLE
Add FunctionIO "profunctor" methods to ZIO

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#647]
All the `FunctionIO` methods which do not exist on `ZIO` can now be added to the `ZIO` data type, because the `ZIO` data type now cleanly subsumes the capabilities of `FunctionIO` (minus performance, of course, for the cases in which `FunctionIO` is specialized).

So we can now "move over" all the `FunctionIO` methods to `ZIO`, including:

 - [x] `compose` (with type alias `<<<`)
 - [x] `andThen` (with type alias `>>>`)
 - [x] `first`
 - [x] `second`
 - [x] `left`
 - [x] `right`
 - [x] `&&&`
 - [x] `|||` (`join`)
- [ ] `asEffect`

And the most useful ones in the companion object:

- [x] `identity`
- [x] `swap`
- [ ] `ifThenElse`
- [x] `_1`
- [x] `_2`

At this point, we can delete `FunctionIO`, and push optimization into the ZIO runtime at some point (no rush since no one seems to be using `FunctionIO` 😄 ).

**Comment by stsatlantis** [comment]
Hi, I would like to give it a try.

**Comment by jdegoes** [comment]
@stsatlantis 🙏 💪

**Comment by regiskuckaertz** [comment]
@jdegoes I can submit `ifThenElse` but isn't `asEffect` just:
```scala
def asEffect: ZIO[R, E, Any] = self
```
?

**Comment by saraiva132** [comment]
@jdegoes What is the required work here to remove FunctionIO and close this ticket. In #667 you commented that a ticket is needed to port performance improvements to ZIO + ifThenElse was removed as per your comment from the PR and asEffect is either not required or straightforward as @regiskuckaertz said. WDYT ?

**Comment by ghostdogpr** [comment]
Closing after FunctionIO was removed.
