### ISSUE TITLE
zio-test Spec.provideCustomLayer does not allow Scope requirement in custom layer

### ISSUE THREAD

**Issue by jeffmay** [zio/zio#6471]
Even though `Spec.spec` allows requiring a `Scope` when providing a `ZLayer`, you cannot propagate this requirement to any shared `ZLayer` when using `.provideCustomLayerShared` because it requires that the `Scope` already be provided by the custom layer.

### Solution

I think the definition just needs to be updated to allow depending on the surrounding `Scope`.

The code in 2.0.0-RC3 is:
```scala
  /**
   * Provides all tests with a shared version of the part of the environment
   * that is not part of the `TestEnvironment`, leaving a spec that only depends
   * on the `TestEnvironment`.
   *
   * {{{
   * val loggingLayer: ZLayer[Any, Nothing, Logging] = ???
   *
   * val spec: ZSpec[TestEnvironment with Logging, Nothing] = ???
   *
   * val spec2 = spec.provideCustomLayerShared(loggingLayer)
   * }}}
   */
  def provideCustomLayerShared[E1 >: E, R1](layer: ZLayer[TestEnvironment, E1, R1])(implicit
    ev: TestEnvironment with R1 <:< R,
    tagged: EnvironmentTag[R1],
    trace: ZTraceElement
  ): Spec[TestEnvironment, E1, T] =
    provideSomeLayerShared(layer)
```

The code should be:
```scala
/**
   * Provides all tests with a shared version of the part of the environment
   * that is not part of the `TestEnvironment`, leaving a spec that only depends
   * on the `TestEnvironment`.
   *
   * {{{
   * val loggingLayer: ZLayer[Any, Nothing, Logging] = ???
   *
   * val spec: ZSpec[TestEnvironment with Logging, Nothing] = ???
   *
   * val spec2 = spec.provideCustomLayerShared(loggingLayer)
   * }}}
   */
  def provideCustomLayerShared[E1 >: E, R1](layer: ZLayer[TestEnvironment with Scope, E1, R1])(implicit
    ev: TestEnvironment with Scope with R1 <:< R,
    tagged: EnvironmentTag[R1],
    trace: ZTraceElement
  ): Spec[TestEnvironment with Scope, E1, T] =
    provideSomeLayerShared(layer)
```

Although, I'm curious, why not just add `Scope` to the `TestEnvironment`?

### Workaround

The current workaround is to provide the same `ZLayer`s as the underlying `Spec.layer` but without requiring the unused `ZIOAppArgs`. In other words:

```scala
import zio._
import zio.test._

trait Custom
object Custom {
  val layer: ULayer[Custom] = ZLayer.succeed(new Custom {})
}

object ExampleSpec extends ZIOSpecDefault {
  override val spec: ZSpec[TestEnvironment with Scope, Any] = suite("example")(
    test("scope is required") {
      for {
        _ <- Scope.addFinalizer(ZIO.logInfo("shutting down..."))
      } yield assertCompletes
    },
  ) // DESIRED:
    // .provideCustomLayer(Custom.layer)
    // OR:
    // .provideSomeCustomLayer(Custom.layer)
    //
    // WORKAROUND:
    .provideLayer(
      ZEnv.live >>> TestEnvironment.live >+> Custom.layer
    )
    // OR:
    // .provideSomeLayer(
    //   ZEnv.live >>> TestEnvironment.live >+> Custom.layer
    // )
}
```

**Comment by adamgfraser** [comment]
I tend to think that conflating the `TestEnvironment` with `Scope` like this creates confusion because it mixes the concepts of default implementations of the standard ZIO services with whether something is resourceful.

You can do this either with `provideSomeLayer[TestEnvironment with Scope](Custom.layer)` or `provideCustomLayer(Custom.layer ++ Scope.default)`.

Also, in most cases I wouldn't recommend creating a shared `Scope` for tests as we want separation between tests and any necessary finalization for shared resources can be described as part of the layer  construction without `Scope`.

**Comment by jeffmay** [comment]
> Also, in most cases I wouldn't recommend creating a shared `Scope` for tests as we want separation between tests and any necessary finalization for shared resources can be described as part of the layer construction without `Scope`.

My use case is that I want to create a shared embedded `RedisServer` for testing (for some reason, every instance create a pop-up in Mac OSX, which cascades and fills up the screen when dozens of them are started), and each test has an isolated namespace, so it is safe to share. I just want the server and client pool to shutdown when the last test finishes so that the app doesn't hang (although it seems to be hanging anyway... 2 threads named `process reaper` and `pool-1-thread-1` are parked in `TIME_WAITING` on some condition... but that's a different story).

I'm curious, is there a difference between supplying a `Scope` with `provideCustomLayer(Custom.layer ++ Scope.default)` and reusing the `Scope` available from the underlying `ZIOApp`? I assume that if there is something that happens after the specs run in the underlying `ZIOSpec`, then the finalizers for the scoped `ZLayer`s will wait for that work to finish as well?

**Comment by adamgfraser** [comment]
If you want to have a shared scope for everything then I would use `ZLayer.environment[Scope]` which would pass through the scope versus `Scope.default` which would make a new scope for each test (assuming you use `provideLayer` versus `provideLayerShared`.

The other thing I would be thinking about is why you need a scope here at all. Layers can already be resourceful, using either `ZLayer.fromAcquireRelease` or `ZLayer.scoped`, without a `Scope` in the environment. So I would use a layer to describe all the logic to set up and shut down my Redis server.

**Comment by jeffmay** [comment]
I think I understand now. Using a ZLayer to manage the shared resource does not require the surrounding `Scope`. I was able to test this and it worked properly. I'm gonna close this issue as I think I misunderstood the purpose of `Scope`.
