### ISSUE TITLE
provideShared silently ignores tests

### ISSUE THREAD

**Issue by senia-psm** [zio/zio#6531]
With tests like this I'm getting no errors:

```scala
suite("TmpSpec")(
  test("failed") {
    assertM(ZIO.runtime[SomeEnv].as(false))(isTrue)
  },
).provideShared(SomeEnv.live)
```
```
 0 tests passed. 0 tests failed. 0 tests ignored.
[info] No tests were executed
```

Without `provideShared` it works as expected.

See this project with executable example: https://github.com/senia-psm/zio-bug-provideShared-ignores-tests

**Comment by adamgfraser** [comment]
I believe this was fixed #6528. Your example works as expected on `series/2.x`.

**Comment by senia-psm** [comment]
@adamgfraser sorry, I thought RC4 was fresh enough - didn't test on `series/2.x` (I can't find snapshots for RC4).
Should I close it?

**Comment by adamgfraser** [comment]
@senia-psm No worries. Sorry we missed this one! Yes I think we can close this.
