### ISSUE TITLE
`ZLayer.service[A]` returns `Has[A]` instead of `A`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6535]
I just stumbled on this when refactoring some layer construction in my 1.0.13 codebase.

`ZLayer.service[A]` returns a `Has[A]` instead of a `A` (e.g. like `ZIO.service[A]` or `ZManaged.service[A]` does).

So I have to write code like 

```scala
  val flywayMigrations = ZLayer.service[Config].flatMap(config => FlywayMigrations
    .ofManualConfig(
      config.get.getString("db.url"),
      config.get.getString("db.user"),
      rawDbConfig.getString("db.user_read_only"),
      config.get.getString("db.password"),
      false
    ))
 ```
 
 instead of 
 
 ```scala
   val flywayMigrations = ZLayer.service[Config].flatMap(config => FlywayMigrations
    .ofManualConfig(
      config.getString("db.url"),
      config.getString("db.user"),
      rawDbConfig.getString("db.user_read_only"),
      config.getString("db.password"),
      false
    ))
 ```

It would be great if `ZLayer.service` would behave similar to `ZIO.service` (e.g. the `service` call always returns an `A` wheras if you need an `Has[A]` you'd call `ZIO.environment[A]` .. probably this is all not needed anymore in `2.0` as we don't have `Has` there anyway.

**Comment by adamgfraser** [comment]
We can't change the signature of this operator on ZIO 1.0 and in ZIO 2.0 `ZEnvironment` is built in to `ZLayer` so I don't think there is anything we can do about this. In your example you can extract `config` into its own variable like `val config = environment.get`. Normally you want to avoid composing layers like this entirely though understand that sometimes it may be necessary.
