### ISSUE TITLE
zio tests that pass with zio 2.0.0-RC3 hang with RC4

### ISSUE THREAD

**Issue by pjfanning** [zio/zio#6538]
The project is https://github.com/pjfanning/zio-metrics-micrometer and `sbt test` works fine in the `zio2` branch. If I change the ZIO version to 2.0.0-RC4, one or maybe 2 tests will pass before the whole process hangs. I have created an `rc4` branch - just in case I do more changes on the `zio2` branch.

If I use Ctrl-X, the tests then seem to complete.

I'm using TestFramework("zio.test.sbt.ZTestFramework") and have disabled parallelExecution in the tests (but that doesn't seem to affect whether the hang happens or not).

This is the trace I see after the Ctrl-X.
```
java.lang.InterruptedException
  | => rat java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1000)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:243)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at zio.CancelableFuture.result(CancelableFuture.scala:48)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at zio.test.sbt.BaseTestTask.execute(BaseTestTask.scala:76)
```

I would appreciate it if someone could have a look. I apologise for not producing a standalone scenario to test this but I hope running the existing build is not too time consuming.

**Comment by pjfanning** [comment]
thanks @adamgfraser - I'll try the snapshot

**Comment by pjfanning** [comment]
@adamgfraser I tried 2.0.0-RC4+8-1b5bac57-SNAPSHOT but still get the same hang result

**Comment by pjfanning** [comment]
Just pushed to 'rc4' branch of https://github.com/pjfanning/zio-metrics-micrometer

This is not urgent if you have other priorities.

**Comment by pjfanning** [comment]
@adamgfraser thanks for the fix to my code. Is it worth keeping this open due to the hang or is it ok to close it?

**Comment by pjfanning** [comment]
Thanks for your expertise - I'm very much the ZIO novice

**Comment by adamgfraser** [comment]
You're writing your own library! That's awesome!

**Comment by adamgfraser** [comment]
Going to close this and open a separate issue for the warnings.
