### ISSUE TITLE
Navigation on website (zio.dev) always navigates to pages for 1.x

### ISSUE THREAD

**Issue by DaniRey** [zio/zio#6540]
Currently the main navigation on the website (zio.dev), always navigates to pages for version 1.x, even when version 2.x is selected.

This only concernes the main navigation (Overview, Data Types, Use Cases,How to, Resources, About).

**Comment by adamgfraser** [comment]
Thanks for reporting! Copying @atooni.

**Comment by atooni** [comment]
Will take a look - perhaps we need to bump docusaurus or something

**Comment by khajavi** [comment]
Hi Andreas @atooni 
Did you try to look at it?

**Comment by kyri-petrou** [comment]
I believe this was resolved some time ago so closing as completed
