### ISSUE TITLE
The compiler cannot infer the scoped environment after `flatMap` on `ZIO.acquireRelease`

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6552]
When I `flatMap` on the result of `ZIO.acquireRelease` my editor cannot infer the proper type.

For example, the compiler infers the `ZIO[Any, IOException, Int]` for the type of the following code instead of `ZIO[Scope, IOException, Int]`:

```
ZIO
  .acquireRelease(
    ZIO.attemptBlockingIO(scala.io.Source.fromFile("file.txt"))
  )(r => ZIO.succeed(r.close()))
  .flatMap(x => ZIO.succeed(x.getLines().length))
```

**Comment by adamgfraser** [comment]
Hmmm, are you using IntelliJ? VS Code and I think the Scala compiler infers the correct type. The only thing slightly unusual we're doing here is have separate `R` and `R1` parameters for the `acquire` and `release` workflows but that is the same technique we used with `ZManaged.make` for the life of ZIO 1.0.

**Comment by khajavi** [comment]
Ah, yes this is the IntelliJ.
Another note is that It can infer the proper type for the `map` operation
but not for `flatMap`.
