### ISSUE TITLE
"provideCustomLayerShared" seems to not work anymore since ZIO RC4

### ISSUE THREAD

**Issue by dylandoamaral** [zio/zio#6573]
All my tests depending on a layer provided as a shared layer using "provideCustomLayerShared" are not detected as tests anymore since ZIO RC4 (worked correctly with ZIO RC3).

They are not even considered as tests, the coverage doesn't works on them and when running "sbt test" it says that there is no test.

Here is a snippet that reproduce the bug:

```
package io.univalence.test

import zio._
import zio.test._

object TestShared extends ZIOSpecDefault {
  def test1: Spec[Int, TestFailure[Throwable], TestSuccess] = suite("suite 1")(test("test 1") {
    def effect: RIO[Int, Int] = ZIO.serviceWith[Int] { i => i * 2 }
    effect.map(i => assertTrue(i == 4))
  })

  def test2: Spec[Int, TestFailure[Throwable], TestSuccess] = suite("suite 2")(test("test 2") {
    def effect: RIO[Int, Int] = ZIO.serviceWith[Int] { i => i * 4 }
    effect.map(i => assertTrue(i == 8))
  })

  override def spec: Spec[TestEnvironment, TestFailure[Throwable], TestSuccess] =
    suite("All tests")(test1, test2).provideCustomLayerShared(ZLayer.succeed(2))
}
```

And the output:

```
0 tests passed. 0 tests failed. 0 tests ignored.
```

**Comment by adamgfraser** [comment]
@dylandoamaral This was fixed by #6528. Can you try running on the latest snapshot?

**Comment by dylandoamaral** [comment]
My bad, I didn't notice that there is an issue for that. I tried with the latest snapshot and it works !

Thank you for your hard work.

**Comment by adamgfraser** [comment]
No problem! Sorry we messed that one up!
