### ISSUE TITLE
Migration document might need to be updated.

### ISSUE THREAD

**Issue by zhiwilliam** [zio/zio#6574]
Hey, 

I am trying to give ZIO 2.0 a test, I just copied code from migration readme file. But it cannot find toLayer method.

  trait Logging {
    def log(line: String): UIO[Unit]
  }

  case class LoggingLive() extends Logging {
    override def log(line: String): UIO[Unit] =
      ZIO.attempt(println(line)).orDie
  }

  object LoggingLive extends (() => Logging) {
    val layer: URLayer[Any, Logging] = LoggingLive.toLayer
  }

Please help! Is it because I miss some import? Or it's a bug? It happens in ZIO 2.0.0 - RC4

**Comment by khajavi** [comment]
Thank you for reporting.
The documentation is updated. We should update the microsite to reflect the latest changes.

**Comment by khajavi** [comment]
@adamgfraser 
Could you please add a new tag (e.g. `docs.2022-04-08`) to the `series/2.x` branch to trigger the microsite workflow?

**Comment by zhiwilliam** [comment]
Ah, I found out what happened. In your ZIO-2.0 RC4 branch, zio package defined as:
package object zio
    extends BuildFromCompat
    with EitherCompat
    with IntersectionTypeCompat
    with VersionSpecific
    with DurationModule 

But in master branch it defined zio extends .... with with FunctionToLayerOps. I don't know why they are so different. But RC4 loses FunctionToLayerOps leads toLayer not working anymore.

**Comment by khajavi** [comment]
@zhiwilliam 
Please check again, we update the website recently.
