### ISSUE TITLE
RC5 zio test provide now behaves same as provide shared - regression error?

### ISSUE THREAD

**Issue by TimPigden** [zio/zio#6588]
I've an unexpected regression problem in my tests for RC5 - I just want to understand the expected behaviour:
```
val suiteInner = suite("test solver jobs")((
  testNIterationsRepeatUntil,
) @@ sequential).provide(
  OptCtrlIdGen.generatorZ)

override def spec = suite("outer")(suiteInner) @@ nonFlaky(1)
```
In the above code, the generatorZ layer is created just once. Since the nonFlaky is doing a repeat outside of the suiteInner, I would have expected (and I believe previously experienced) the layer being created for every internal run. This is important since my tests are checking specific id values from a zero base.
But now it only  gets created once. Is this deliberate?

Also even if I move the layer to the test itself, it still only gets created once
and in similar vein:
```
val suiteInner = suite("test solver jobs")(
  testNIterationsRepeatWhile,
  testNIterationsRepeatUntil,
).provide(
  OptCtrlIdGen.generatorZ,
  OpkRandom.seededRandomZ(31))
```
creates just a single generator, whereas previously i believe it would have created one per test and the use of provideShared would create a single one

**Comment by adamgfraser** [comment]
@TimPigden In the first example I believe providing the layer only once is the corrected behavior and was the behavior on prior versions. In the second example the layer should be built twice and provided to each test.
