### ISSUE TITLE
ZIO app throws exception when interrupted with SIGTERM

### ISSUE THREAD

**Issue by somdoron** [zio/zio#6596]
ZIO Version: 1.0.13
Expect behavior: when interrupted the app should exit gracefully

In production, we are monitoring any crash of the app (Kubernetes pods), the problem is, every time we release a version the pod gets interrupted by Kubernetes, instead of exiting gracefully `zio.App` throws FiberFailure exception and the JVM prints:

```
Exception in thread "main" zio.FiberFailure: Fiber failed.

An interrupt was produced by #16566
```

Simple code to reproduce:

```
object MyApp extends zio.App {
  override def run(args: List[String]) = for {
    fiberId <- ZIO.fiberId
    result <- ZIO.halt(Cause.interrupt(fiberId)).exitCode
  } yield result
}
```

I've tracked down the problem to:
https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Runtime.scala#L59

I think maybe `zio.App` should use the `unsafeRunSync` method and only throw on non InterruptedOnly (and exit with 0 on interrupted), something like:

```
final def main(args0: Array[String]): Unit =
    try sys.exit(
      unsafeRunSync(
        for {
          fiber <- run(args0.toList).fork
          _ <- IO.effectTotal(
                java
                  .lang
                  .Runtime
                  .getRuntime
                  .addShutdownHook(new Thread {
                    override def run() =
                      if (FiberContext.fatal.get) {
                        println(
                          "**** WARNING ***\n" +
                              "Catastrophic JVM error encountered. " +
                              "Application not safely interrupted. " +
                              "Resources may be leaked. " +
                              "Check the logs for more details and consider overriding `Platform.reportFatal` to capture context."
                        )
                      } else {
                        val _ = unsafeRunSync(fiber.interrupt)
                      }
                  })
              )
          result <- fiber.join
          _      <- fiber.interrupt
        } yield result.code
      ) match {
        case Failure(cause) if cause.interruptedOnly => 0
        case Failure(cause)                          => throw FiberFailure(cause)
        case Success(value)                          => value
      }
    )
    catch { case _: SecurityException => }
```

**Comment by somdoron** [comment]
@adamgfraser it doesn't return an exit code of 1, it throws the FiberFailure exception which is caught by JVM and may be translated into exit code of 1. I'm fine with exit code of 1. 

The `.exitCode` doesn't work on interrupted errors.

**Comment by adamgfraser** [comment]
Adding a debug statement to your original example I see:

```scala
object MyApp extends zio.App {
  override def run(args: List[String]) = for {
    fiberId <- ZIO.fiberId
    result <- ZIO.halt(Cause.interrupt(fiberId)).exitCode
    _      <- ZIO.debug(s"The exit code is $result")
  } yield result
}
```

```
Fiber failed.
An interrupt was produced by #1.
No ZIO Trace available.
The exit code is ExitCode(1)
```

**Comment by somdoron** [comment]
Interesting, probably my code is not a good enough example, because it is not terminated by another fiber, the following for example doesn't print for me if I ctrl+c or send SIGTERM:

```
  override def run(args: List[String]) =
    for {
      result <- ZIO.never.exitCode
      _      <- ZIO.debug(s"The exit code is $result")
    } yield result
```

**Comment by somdoron** [comment]
and throws FiberFailture, which is the problem. Instead of just exiting quietly with exit code of 1.

**Comment by somdoron** [comment]
after "CTRL+C" the above code with graalvm it prints "Exception in thread "main". This is what we try to avoid, we would like to exit gracefully when SIGTERM is sent. When running in Kubernetes cluster, the fact that the app is going down with a crash makes it difficult to monitor real crashes. 

Even if we try to write a log rule to catch all "Fiber failed" messages, again the fact that the ZIO app is crashing on interrupt makes it very difficult.

**Comment by adamgfraser** [comment]
Yes. We significantly reworked this in ZIO 2. Basically `ZIOApp` should always translate its result into an exit value rather than failing. Can you take a look at the linked PR and see if it resolves your issue?

**Comment by somdoron** [comment]
Would catchAllCause catch Cause.Interrupt as well? Anyway, you might want to print the cause as well, like `ZIO.exitCode` does.

Internally, for now, we copied `zio.App` and replaced `unsafeRun` with `unsafeRunSync` and matched the result in the end:

```
match {
        case Exit.Failure(cause) if cause.interruptedOnly => 1
        case Exit.Failure(cause)                                           => throw FiberFailure(cause)
        case Exit.Success(value)                                         => value
      }
```

**Comment by adamgfraser** [comment]
Yes it does.

**Comment by somdoron** [comment]
Cool, looks good to me.

**Comment by adamgfraser** [comment]
Thanks for raising and for taking a look!
