### ISSUE TITLE
ZPipeline.iso_8859_1Decode does not fully process the stream

### ISSUE THREAD

**Issue by tewecske** [zio/zio#6624]
If I run this

```
    ZStream.fromFile(new File("data.txt"))
        .via(ZPipeline.utf8Decode)
//        .via(ZPipeline.iso_8859_1Decode)
        .via(ZPipeline.splitLines)
      .runForeachChunk(c => Console.printLine(s"chunk: ${c.length}"))

```
I get
```
chunk: 30
chunk: 28
```

but if I run with the ISO_8859_1Decode then I get this
```
chunk: 30
chunk: 1
```

There is no buffer in `textDecodeUsing` and it doesn't process the end of the stream. It needs to be similar to `utf8DecodeNoBom`.

**Comment by tewecske** [comment]
Sorry, no buffer is needed, just the processing of the end of the stream.
I don't know if this the correct solution but instead of this:

```
      def transform(charset: Charset): ZChannel[Any, ZNothing, Chunk[Byte], Any, Nothing, Chunk[String], Any] =
        ZChannel.readWith(
          received => {
            if (received.isEmpty)
              transform(charset)
            else
              ZChannel.write(stringChunkFrom(received, charset))
          },
          error = ZChannel.fail(_),
          done = _ => ZChannel.unit
        )
```

I did this:

```
      def transform(charset: Charset): ZChannel[Any, ZNothing, Chunk[Byte], Any, Nothing, Chunk[String], Any] =
        ZChannel.readWith(
          received => {
            ZChannel.write(stringChunkFrom(received, charset)) *>
            transform(charset)
          },
          error = ZChannel.fail(_),
          done = _ => ZChannel.unit
        )
```

I guess an isEmpty check should be there somewhere.

**Comment by tewecske** [comment]
I was able to reproduce it without using a file.

https://scastie.scala-lang.org/tewecske/4qkIibsXTN6d7ANUlMqy1A/9

`fromReader` is similar to `fromFile` so looks like it works the same way.
`fromIterable` is different and the issue is not reproducible with it.

So I'm not sure if the issue is with the decoder or with the stream construction using `fromReader` or `fromFile`.

**Comment by vigoo** [comment]
The problem is with chunking. Unfortunately the chunking tests for the encoder/decoder pipelines were disabled - enabling them shows the problem. Fix coming soon
