### ISSUE TITLE
2.0 migration guide: ZRef got removed

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6632]
The migration guide https://zio.dev/next/howto/migrate/zio-2.x-migration-guide/#zref says ZRef is still there, but in 2.0.0-RC5 it is gone. I had to migrate instances of ZRef to Ref

**Comment by adamgfraser** [comment]
I just published a new version of the website so those references should be gone momentarily.

We should add a section about deletion of the more polymorphic versions of concurrent data types to the migration guide.

Copying @khajavi.
