### ISSUE TITLE
2.0 testing:  reference to test is ambiguous

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6633]
I used to have 
```scala
import zio._
import zio.test._
```
in my test classes. Now that `testM` got renamed to `test`, the compiler complains that `test` is ambiguous. 

```
[error] /Users/domdorn/acme/jobs-service/src/test/scala/com/acme/viopt/jobs/web/CreateCalculationSpec.scala:129:5: reference to test is ambiguous;
[error] it is imported twice in the same scope by
[error] import zio.test._
[error] and import zio._
[error]     test("accept request and create a job with multiple calculations")(
[error]     ^
```

I can manually change the imports to use explicit imports instead of the wildcard, but the developer experience was better before... maybe we can fix this for RC6 ?

**Comment by adamgfraser** [comment]
`ZIOSpec` defines its own `test`` and `suite` methods so if you define your tests within `ZIOSpecDefault` this shouldn't be an issue for you. This was the same solution as we used for `test` in ZIO 1.0 and `test` in `DefaultRunnableSpec` in earlier versions of ZIO 2.0.

**Comment by domdorn** [comment]
This is especially bad when having to deal with e.g. Durations as the implicits for writings something like `20.seconds` only gets imported from `import zio._` .. if I try to import methods from `zio.test._` explicitly its quite a lot of work and stuff like `scala.predef.assert` gets picked before the one defined in `zio.test.assert`

**Comment by adamgfraser** [comment]
This works fine.

```scala
import zio._
import zio.test._

object MySpec extends ZIOSpecDefault {
  
  def spec = suite("MySpec")(
    test("my test") {
      assertTrue(2 + 2 == 4)
    }
  )
}
```

**Comment by domdorn** [comment]
hmm.. I have a huge amount of integration tests in this service. to create expensive resources only once and share them between all of them, I've split the various tests to own files and then imported them in one file. 

e.g. 
TestsA.scala
```scala

import zio._
import zio.test._

object TestsA { 
  val tests = suite("...")( ... )
} 
```

TestsB.scala
```scala

import zio._
import zio.test._

object TestsB { 
 ... 
} 
```

IntegrationSpec.scala
```scala

import zio._
import zio.test._

object MyIntegrationSpec extends ZIOSpecDefault { 
 def spec = suite ("integraiton spec")( 
   TestsA.tests,
   TestsB.tests
} 
```

I've now managed to get rid of the compile errors in TestsA and TestsB by making them also implement `ZIOSpecDefault` and just having a dummy spec there

e.g.
TestsA.scala
```scala

import zio._
import zio.test._

object TestsA extends ZIOSpecDefault { 
  override def spec: ZSpec[TestEnvironment with Scope, Any] = suite("empty")(test("dummy")(assertTrue(true)))

  val tests = suite("...")( ... )
} 
```

**Comment by adamgfraser** [comment]
In ZIO 2 you can implement the `layer` method of `ZIOSpec` and that layer will be shared between all specs so you don't need to use that pattern anymore.

**Comment by domdorn** [comment]
is there a sample of this somewhere?

**Comment by adamgfraser** [comment]
In the code below, `IntService` will only be constructed once.

```scala
object IntService {
  val layer = ZLayer(ZIO.debug("I'm making an Int!").as(1))
}

object MyFirstSpec extends ZIOSpec[Int] {
  val layer = IntService.layer
  def spec = ???
}

object MySecondSpec extends ZIOSpec[Int] {
  val layer = IntService.layer
  def spec = ???
}
```

**Comment by adamgfraser** [comment]
@khajavi Would be good to add an example of this to the documentation on testing and the migration guide.

**Comment by khajavi** [comment]
@adamgfraser Will do!

**Comment by adamgfraser** [comment]
Going to close this as I don't think there is an action item here. The inclusion of `test` in `ZIOSpec` solves the problem within specs and especially with the ability to share layers between specs all tests should be able to be written within a `ZIOSpec` object. Beyond this I don't think there is. a lot we can do beyond changing the name of the project itself or changing the name of the operator you use to define tests, both of which seem extremely disruptive.
