### ISSUE TITLE
2.0 migration guide: DefaultRunnableSpec gone

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6634]
Apparently (from looking at sources in this repo) the new base class is ZIOBaseSpec. This should be documented in the migration guide

**Comment by khajavi** [comment]
@adamgfraser This is already documented [here](https://zio.dev/next/howto/migrate/zio-2.x-migration-guide/#composable-test-apps). It encourages using `ZIOSpecDefault`. Let me know if we need to change that to `ZIOBaseSpec`.

**Comment by adamgfraser** [comment]
@khajavi Perfect!
