### ISSUE TITLE
2.0 documentation: testing documentation contains no code of a test

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6635]
The documenation about testing in zio contains not a single example of a spec
https://zio.dev/next/overview/overview_testing_effects

The bare minimum it should contain is 

```scala
import zio._
import zio.test._

object MySpec extends ZIOSpecDefault {
  
  def spec = suite("MySpec")(
    test("my test") {
      assertTrue(2 + 2 == 4)
    }
  )
}
```

with more examples on how to work with dependencies etc.

**Comment by adamgfraser** [comment]
@ domdorn I think you want to be looking [here](https://zio.dev/next/howto/test-effects).

There are several pages that reference testing that could use to be combined into one page and improved on.

Copying @khajavi.

**Comment by khajavi** [comment]
@adamgfraser @domdorn 
After we published the recent changes on the website, currently we have [one section](https://zio.dev/next/datatypes/test/) which introduces ZIO Test.

**Comment by adamgfraser** [comment]
@khajavi Great!
