### ISSUE TITLE
No stream output with combination of buffer and mergeTerminateEither

### ISSUE THREAD

**Issue by svroonland** [zio/zio#6649]
Using 2.0.0-RC5+23-3d67af5f-SNAPSHOT

The code below is an attempt at a minimal reproducer from some library code. With the buffer line commented out, I get an output line every 2 seconds, but when it's uncommented, only the first output appears. The `mergeTerminateEither` is necessary to get this behavior. In my actual code I'm seeing an interruption of an effect carried out by stream2, but I wasn't able to make a reproducer for that.

```scala
import zio.stream._
import zio.test.TestAspect.withLiveClock
import zio.test._
import zio._

object MergeWithIssueTest extends ZIOSpecDefault {
  override def spec = suite("test")(
    test("show issue") {

      val stream1 = ZStream.fromZIO(Promise.make[Nothing, Unit]).mapZIO(_.await)

      val stream2 = ZStream
        .repeatZIOWithSchedule(ZIO.sleep(2.seconds), Schedule.spaced(1.second))
//        .buffer(2)

      val stream = stream1 mergeTerminateEither stream2

      stream.debug.runCollect.as(assertCompletes)
    }
  ) @@ withLiveClock
}
```

**Comment by adamgfraser** [comment]
I see the issue. Will submit a PR shortly.

**Comment by svroonland** [comment]
Thanks @adamgfraser !
