### ISSUE TITLE
2.0.0-RC5 ZLayer.succeed does not infer correct type anymore with anonymous implementations

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6660]
Sample code:
```scala
trait KeySetProvider {
def getKeySet(): Task[JWKSet]
}

def test(resourcePath: String): ULayer[KeySetProvider] =
    ZLayer.succeed(() => ZIO.effect(JWKSet.load(getClass.getResourceAsStream(resourcePath))))
```
this correctly worked in ZIO 1.0, but in ZIO 2.0.0-RC5

```scala
 def test(resourcePath: String): ULayer[KeySetProvider] =
    ZLayer.succeed(() => ZIO.attempt(JWKSet.load(getClass.getResourceAsStream(resourcePath))))
```    
![grafik](https://user-images.githubusercontent.com/100349/163981299-0054f625-bf15-4684-be7c-f52a86bb6223.png)

To make it work, I have to explicitly cast it, e.g. 

```scala
def test(resourcePath: String): ULayer[KeySetProvider] =
    ZLayer.succeed((() => ZIO.attempt(JWKSet.load(getClass.getResourceAsStream(resourcePath)))): KeySetProvider)
```

**Comment by adamgfraser** [comment]
Going to close this as not able to replicate and I think any degradation in type inference is a result of using by name parameters which is necessary for correctness. Feel free to re-open if you have an example you would like us to take a look at!
