### ISSUE TITLE
2.0 `ZLayer.requires` gone

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6662]
`ZLayer.requires[A]` seems to be gone. I think its replacement is `ZLayer.service[A]`. Not sure whats the strategy, but I would have expected it to be deprecated with a note to use `ZLayer.service` instead. 

![grafik](https://user-images.githubusercontent.com/100349/164012541-365a4667-2a9a-4839-a742-bd8b212818fb.png)

Please also make sure to update the documentation.

**Comment by adamgfraser** [comment]
Yes, `ZLayer.service` is the appropriate replacement.

@khajavi Can you make sure this is in the migration guide?

We will also make sure this is covered by the automated migration tool.
