### ISSUE TITLE
Add combinators fromEitherM and fromOptionM

### ISSUE THREAD

**Issue by Fristi** [zio/zio#668]
As `IO` is a `EitherT[F, E, A]` I tend to use `EitherT.fromOptionF` and `EitherT.fromEitherF` quite frequently when I reach to an API or database.

**Comment by jdegoes** [comment]
Good idea!

**Comment by jdegoes** [comment]
```scala
trait ZIOFunctions {
  ...
  def fromOptionM[A](uio: UIO[Option[A]]): IO[Unit, A] = ???
  def fromEitherM[E, A](io: IO[E, Either[E, A]]): IO[E, A] = ???
  ...
}
```

**Comment by Vilkina** [comment]
I'll take this one

**Comment by Fristi** [comment]
I was just thinking about this aswell, but what if `fromOptionM` goes to the database? Then you want `IO`.

**Comment by Fristi** [comment]
```scala
  def fromOptionTask[A, E](ifEmpty: => E, onError: Throwable => E)(opt: Task[Option[A]]): Result[E, A] =
    opt
      .catchAll(err => ZIO.fail(onError(err)))
      .flatMap {
        case Some(x) => ZIO.succeed(x)
        case None => ZIO.fail(ifEmpty)
      }
```

**Comment by Vilkina** [comment]
@Fristi, I think we need to use 'IO' instead of 'Result'
`  def fromOptionTask[A, E](ifEmpty: => E, onError: Throwable => E)(opt: Task[Option[A]]): IO[E, A] =
  opt
    .catchAll(err => ZIO.fail(onError(err)))
    .flatMap {
      case Some(x) => ZIO.succeed(x)
      case None => ZIO.fail(ifEmpty)
    }`

What do you think?

**Comment by Fristi** [comment]
Yes `Result` was a type alias. Alternatively we could also use `orDie`. Then you don't need `fromOptionTask`.

**Comment by Vilkina** [comment]
https://github.com/scalaz/scalaz-zio/pull/720 I don't know why Travis doesn't want to pass it :)

**Comment by ghostdogpr** [comment]
Isn’t `fromOptionM` redundant with already existing `get`?

**Comment by Fristi** [comment]
With `get` you cannot provide an error. 
```scala
final def get[E1 >: E, B](implicit ev1: E1 =:= Nothing, ev2: A <:< Option[B]): ZIO[R, Unit, B]
```

This is what you do with `ifEmpty`

**Comment by ghostdogpr** [comment]
Yes, a version with `ifEmpty` brings something, but the version mentioned initially (and in the PR) is just the same as `get`. And for Either there is `absolve`.

**Comment by Vilkina** [comment]
I'm back. Will finish this issue soon :)

**Comment by jdegoes** [comment]
It was @ghostdogpr who pointed out we may not need these combinators after all, because they are so similar to the other ones. So I will close this for now. 

I think we may be missing some combinators around Option/Try, mainly to submerge them into the main error type, but I haven't thought about what they should be.

Will close this one for now. Thank you @Vilkina for your work to date on it.
