### ISSUE TITLE
2.0.0-RC5: foreachParN gone

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6693]
I can't find the replacement for `foreachParN`. the ability to limit the parallelism is important when accessing third party systems that are easily overwhelmed by too much parallelism

**Comment by vigoo** [comment]
You can use `ZIO.withParallelism(n) { ZIO.foreachPar(...) }` 
or an aspect like `ZIO.foreachPar(...) @@ parallel(n)`

**Comment by domdorn** [comment]
thx
