### ISSUE TITLE
ZIO 2 ZPool.get method is not timeout-able

### ISSUE THREAD

**Issue by scalajos** [zio/zio#6697]
zpool.get().timeout(sometimeout) ignores the timeout when pool is exhausted for a long time.
Using a fiber is a way to overcome this limitation : 
zpool.get.fork.flatMap(resFiber => resFiber.join.timeout(thetimeout))
Having a standard timeout-able get on zpool would be very useful

**Comment by adamgfraser** [comment]
@scalajos You can use `pool.get.disconnect.timeout` for this.
