### ISSUE TITLE
Add JUnit 5 TestEngine support

### ISSUE THREAD

**Issue by tewecske** [zio/zio#6724]
Only JUnit 4 is supported in zio-test-junit.
Add JUnit 5 platform support.

Here is the scalatest implementation for reference: https://github.com/helmethair-co/scalatest-junit-runner/blob/main/src/main/java/co/helmethair/scalatest/ScalatestEngine.java

**Comment by tewecske** [comment]
Oh, maybe the JUnit 5 vintage test engine can run zio tests. I'll check tomorrow.

**Comment by adamgfraser** [comment]
You want to work on this? 😃

**Comment by tewecske** [comment]
JUnit vintage engine can run zio-test tests so this is not an issue.
I mean this is nice to have but not necessary.

**Comment by adamgfraser** [comment]
We like things to be nice! 😃

**Comment by domdorn** [comment]
could we use this to make cross-test shared layers, e.g. one db connection pool or testcontainers, over multiple test-classes (.scala files) work? JUnit has this with JUnitExtension + @ExtendWith .. or is this now working in 2.0 ?

**Comment by adamgfraser** [comment]
Shared test layers are already supported in ZIO 2. Just override the `bootstrap` layer in `ZIOSpec`.
