### ISSUE TITLE
Update Migration Guide For Elimination Of Default Services From Environment

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#6753]
The migration guide should be updated with additional content regarding the deletion of the default services in the environment. I particular:

- All usages of `ZEnv`, `Console`, `Clock`, `Random`, or `System` in the environment type of `ZIO`, `ZStream`, and `ZLayer` should generally be deleted
- There is no need to access these services or provide them anymore
- If you want to use the live version in tests you can use test aspects such as `withLiveClock`
- If you need to modify the implementation of one of these services on a more fine grained basis you can do `ZEnv.services.locally` or one of its variants

**Comment by khajavi** [comment]
Will do!
