### ISSUE TITLE
Update Migration Guide For Deletion of RuntimeConfig and RuntimeConfig Aspect

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#6756]
Key points:

- `RuntimeConfig` and `RuntimeConfigAspect` have been deleted.
- To access information about the configuration of your ZIO program as you are running you can use more specific operators such as `ZIO.executor` or `ZIO.logger`.
- To customize the runtime, we use layers. This allows us to use ZIO workflows in customizing our runtime (e.g. loading some configuration information to set up logging).
- Basic layers are available in the `Runtime` companion object (e.g. `addLogger`). ZIO ecosystem libraries like ZMX will define their own layers that install all necessary functionality
- When we access a `Runtime` using `ZIO.runtime` it will inherit all of the configuration of the current workflow so if we use it to run effects they will be run with the same logger and so on.
- To create a custom runtime in mixed applications we combine all the layers that do our customization and then do `Runtime.unsafeFromLayer`.

**Comment by khajavi** [comment]
Thank you for the notes! Will do!
