### ISSUE TITLE
String diff fails with NPE when one of the Strings is null

### ISSUE THREAD

**Issue by nightscape** [zio/zio#6764]
When comparing a `String` with `null` the Differ fails with a `NullPointerException`.
Minimal repro:
```scala
import zio.Scope
import zio.test._
object StringDiffTest extends ZIOSpecDefault {
  override def spec: ZSpec[TestEnvironment with Scope, Any] =
    test("String diffing fails") {
      assertTrue("" == null)
    }
}
```

The reason is that [`DiffInstances#stringDiff` tries to split the Strings at newlines](https://github.com/zio/zio/blob/4d0fd60c90eb90ec3eb496af1f519007e10d0721/test/shared/src/main/scala/zio/test/diff/Diff.scala#L27), which won't work for `null`.

I know using `null` is not a best practice, but sometimes one doesn't have a choice when interacting with Java APIs...
I would propose adding a special case for `null` at the beginning of the diffing, but I'm open to other suggestions.

**Comment by kitlangton** [comment]
Ah! What version of ZIO are you on?

**Comment by calvinlfer** [comment]
This is the behavior in RC6 

```scala
import zio.test._

object StringDiffTest extends ZIOSpecDefault {
  override def spec: Spec[Any, Nothing] =
    test("String diffing fails") {
      assertTrue("" == null)
    }
}
```


```
runSpec
  - String diffing fails
    ✗ ERROR: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "x" is null
      zio.test.diff.DiffInstances.zio$test$diff$DiffInstances$$$anonfun$stringDiff$1(Diff.scala:45)
      zio.test.diff.DiffInstances$$anonfun$stringDiff$6.diff(Diff.scala:41)
      zio.test.diff.DiffInstances$$anonfun$stringDiff$6.diff(Diff.scala:41)
      zio.test.internal.SmartAssertions$.$anonfun$equalTo$1(SmartAssertions.scala:286)
    "" == null
    at AnotherOne.scala:7
    ````

**Comment by kitlangton** [comment]
👍 I'll add a null check before triggering diffs! You're a bug reproducing machine @calvinlfer! Henceforth, you shall be known as **The Minimizer**.
