### ISSUE TITLE
The `Runtime.track` Layer Cannot be Provided to a ZIO workflow

### ISSUE THREAD

**Issue by khajavi** [zio/zio#6784]
```scala
object MainApp extends ZIOAppDefault {
  val app = ZIO.debug("Appalication started!")

  def run =
    app.provide(
      Runtime.track(true)
    )
}
```

Compiler error:
```
[error] ──── ZLAYER WARNING ──────────────────────────────────────────────────
[error] 
[error]  You have provided more than is required.
[error]  You may remove the following layer:
[error]    
[error]    1. Runtime.track(true)
[error]   
[error] ──────────────────────────────────────────────────────────────────────
[error] 
[error]     app.provide(
[error]                ^
```

Not sure but I think it is because of the wrong type signature of this layer.

**Comment by adamgfraser** [comment]
Yes it is because the automatic layer construction algorithm only permits unused layers when the return type is `Unit` rather than `Any`. Just submitted a PR to fix the signature.

@kitlangton Do you think it is possible to update the algorithm to handle `Any` as well?

**Comment by kitlangton** [comment]
> Yes it is because the automatic layer construction algorithm only permits unused layers when the return type is `Unit` rather than `Any`. Just submitted a PR to fix the signature.
> 
> @kitlangton Do you think it is possible to update the algorithm to handle `Any` as well?

I think that might confuse the algorithm, due to Any being a supertype of all the things. But I can look into it. If not, I can at least add suggestion to use `.unit` on the layers you'd like to be side-effecting.
