### ISSUE TITLE
package object zio type symbols not found in 2.0.0-RC6

### ISSUE THREAD

**Issue by KeithGrant** [zio/zio#6820]
After library change from RC5 to RC6 several of the type symbols (Task, IO) were not found by the compiler. Moving back to RC5 fixed the issue.

[error] -- [E006] Not Found Error: 
[error] 49 |    Task.scoped {
[error]    |    ^^^^
[error]    |    Not found: Task
[error] Explanation
[error] ===========
[error] The identifier for `Task` is not bound, that is,
[error] no declaration for this identifier can be found.

**Comment by adamgfraser** [comment]
The type alias companion objects were deleted in `RC6`. You can replace all usages of them with `ZIO`. For example instead of `Task.scoped` you would do `ZIO.scoped`. See #6615 for further discussion.
