### ISSUE TITLE
Add "Automatic-Module-Name" for release artifacts

### ISSUE THREAD

**Issue by ajaychandran** [zio/zio#6838]
Please consider adding "Automatic-Module-Name" to the manifest file of released JAR files. This would allow users on Java 9 (and Maven) to use the library.

This can be achieved by adding the following SBT setting:
```sbt
Compile / packageBin / packageOptions += Package.ManifestAttributes("Automatic-Module-Name" -> moduleName.value)
``` 

A more detailed description of the issue is available [here](https://github.com/makingthematrix/scala-suffix).

**Comment by ajaychandran** [comment]
For reference, the `scala3-library` jar has this entry:
```
Automatic-Module-Name: org.scala.lang.scala3.library
```

**Comment by adamgfraser** [comment]
Do you want to submit a PR for this?

**Comment by ajaychandran** [comment]
Will do.
