### ISSUE TITLE
clearOutputErr missing (to match clearOutput and clearInput) in TestConsole

### ISSUE THREAD

**Issue by bbarker** [zio/zio#6839]
See [test/shared/src/main/scala/zio/test/environment/package.scala](https://github.com/zio/zio/blob/006f6f3ffc0e735cb09ead595b86f60bdb78bfcc/test/shared/src/main/scala/zio/test/environment/package.scala).

I'm happy to try to add this in a PR if there are no objections.

**Comment by adamgfraser** [comment]
Thanks for reporting! Just submitted a PR to add.
