### ISSUE TITLE
Add specialized bitwise operations to BitChunk

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6848]
**ISSUE**

BItChunks, being backed by arrays of bytes, can support efficient bitwise operations, such as bitwise and, bitwise or, bitwise xor, and bitwise negation. Yet, currently no such operations exist.

**SOLUTION**

These methods should be added to `Chunk.BitChunk`. For ease of use, they should also be accessible on the parent `Chunk` when there is proof the element type is a `Boolean`. This means they need a generic implementation that works even when the chunk is not backed by a `BitChunk`, but is in fact backed by, for example, an array of booleans.

```scala
sealed trait Chunk[+A] {
  def & (that: Chunk[Boolean])(implicit ev: A <:< Boolean): BitChunk = ...
  ...
}
object Chunk {
  class BitChunk extends Chunk[Boolean] {
    override def & (that: Chunk[Boolean])(implicit ev: A <:< Boolean): BitChunk = ...
    ...
  }
}
```

**IMPACT**

`Chunk` is already used for high-performance code. In the future, we'd like to use it to power binary codecs, which requires efficient implementation of bit methods.

**WHERE TO LOOK**

 - [BitChunk](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Chunk.scala#L1731)
 - [Old Issue](https://github.com/zio/zio/issues/3388)

**PROBLEMATIC ISSUES**

The use of implicit evidence `<:<` may be confusing, please ask for clarification if you've not seen this way of "selectively" adding methods to a data type.

**Comment by NavidJalali** [comment]
I can do this

**Comment by NavidJalali** [comment]
I would like to give this a try
