### ISSUE TITLE
Add new constructors for Chunk[Boolean] from Int/Long, which accept Endianness

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6849]
**ISSUE**

ZIO's `Chunk[Boolean]` can be backed by `Chunk[Byte]`, which is useful when a byte stream should be interpreted as a chunk of bits (booleans) for purposes of decoding binary data. However, this special support is only provided for `Chunk[Byte]`. Many binary protocols use `Int` or `Long` to encode bits, and their may be different choices for "Endianness" (big endian / little endian).

**SOLUTION**

New constructors for `Chunk[Boolean]` that can convert from `Chunk[Int]` and `Chunk[Long]` into `Chunk[Byte]` (currently, only `Chunk[Byte]` can be "interpreted" as a `Chunk[Boolean]`). These constructors must accept `Endianness` (`BigEndian` or `LittleEndian`) in order to know how bytes are packed into an int or long. 

```scala
sealed trait Endianness
object Endianness {
  case object BigEndian extends Endianness
  case object LittleEndian extends Endianness
}

sealed trait Chunk[+A] {
  ...
  def asBitsInt(endianness: Endianness)(implicit ev: A <:< Int): Chunk[Boolean] = 
    Chunk.BitChunkInt(self.asInstanceOf[Chunk[Int]], endianness)
  def asBitsLong(endianness: Endianness)(implicit ev: A <:< Int): Chunk[Boolean] = 
    Chunk.BitChunkLong(self.asInstanceOf[Chunk[Int]], endianness)
}
object Chunk {
  ...
  final case class BitChunkInt(chunk: Chunk[Int], endianness: Endianness) extends Chunk[Boolean] { ... }
  final case class BitChunkLong(chunk: Chunk[Int], endianness: Endianness) extends Chunk[Boolean] { ... }
  ...
}
```

**IMPACT**

ZIO's Chunk must be improved to provide full support for decoding binary data. Adding this feature to ZIO Chunk will help pave the way for `ZIO Codec` library.

**WHERE TO LOOK**

 - [BitChunk](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Chunk.scala)
 - [Endianness](https://en.wikipedia.org/wiki/Endianness)

**PROBLEMATIC ISSUES**

Knowledge of the concept of "endianness" is required to implement this ticket.

**Comment by 987Nabil** [comment]
I'll work on this
