### ISSUE TITLE
Generalize BitChunk* constructors to accept minBit / maxBit

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6850]
**ISSUE**

Currently, taking or dropping on a `Chunk[Boolean]` that is backed by a `BitChunk*` will involve wrapping it in the `Range` chunk. The more times take or drop are called, the more levels of wrapping there will be. As taking / dropping happens a lot in binary decoding, it is important to make the operations very efficient.

**SOLUTION**

For performance reasons, it may be desirable to generalize the `BitChunk*` constructors to accept `minBit` and `maxBit`, i.e. allow the user to define a range on the raw Chunk with the byte/int/long data. With this range, we could further specialize `take`, `drop`, and `slice` on `Chunk[Boolean]` in order to accelerate these operations by using the range parameters.

**NOTE**: This optimization looks partially implemented in `BitChunk` (not fully, e.g. for `slice`), and also won't be implemented out of the box for new types of bit chunks (`BitChunkInt`, `BitChunkLong`).

**IMPACT**

Chunk must become better before it can be the basis for high-performance binary decoding.

**WHERE TO LOOK**

 - [BitChunk](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Chunk.scala#L1731)

**PROBLEMATIC ISSUES**

This issue depends on #6849.

**Comment by 987Nabil** [comment]
@rajcspsg this issue depends on #6849 which I am still on. Also I did already implement this specialized `drop` and `take` methods, since I followed the ideas that where already impl. in `BitChunk`
