### ISSUE TITLE
Add ways to pack Chunk booleans into byte, int, or long

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6851]
**ISSUE**

There is a way to go from `Chunk[Byte]` (or after #6849, `Chunk[Int]`/`Chunk[Long]`) to `Chunk[Boolean]`, with efficient / specialized operations designed for packed bits. However, the reverse operators do not exist: after efficiently generating a `Chunk[Boolean]`, it may be necessary to go back to bytes, or ints or longs (with endianness).

**SOLUTION**

Conversion methods added to `Chunk[Boolean]` (which can go from `Chunk[Boolean]` to `Chunk[Byte]`, `Chunk[Int]`, or `Chunk[Long]`). When going to either `Int` or `Long` (but not when going to `Chunk[Byte]`), the destructor must accept `Endianness`, because it affects how the bytes are packed into the resulting int or long values. 

```scala
sealed trait Chunk[+A] {
  def toPackedByte(implicit ev: A <:< Boolean): Chunk[Byte]
  def toPackedInt(endianness: Endianness)(implicit ev: A <:< Boolean): Chunk[Int]
  def toPackedLong(endianness: Endianness)(implicit ev: A <:< Boolean): Chunk[Long]
}
```

The methods would be overridden and high-performance specialized (i.e. no real packing when possible) for the `BitChunk*` subtypes of `Chunk`.

**IMPACT**

To make incremental progress toward using Chunk for fast binary decoding.

**WHERE TO LOOK**

 - [BitChunk](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/Chunk.scala#L1731)

**PROBLEMATIC ISSUES**

Depends on #6849.

**Comment by 987Nabil** [comment]
@jdegoes or @adamgfraser When talking about little vs big endian, then what is one unit? I mean do I only look at the bits of each Long/Int in a different order or of the whole chunk?

**Comment by adamgfraser** [comment]
Just following up on our conversation on Discord this refers to each `Int` or `Long`.

**Comment by 987Nabil** [comment]
@adamgfraser i commented on the wrong ticket :( my bad

**Comment by adamgfraser** [comment]
@987Nabil No worries!

**Comment by 987Nabil** [comment]
Any how, I'd like to continue with this issue, since I already worked on #6849

**Comment by 987Nabil** [comment]
@adamgfraser this issue can be closed or?
