### ISSUE TITLE
Optimize performance of WeakConcurrentBag

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6852]
**ISSUE**

In ZIO 2, `WeakConcurrentBag` is used for storing root fibers. However, this structure has not been optimized, which means if there are large number of daemon fibers, it may not perform optimally.

**SOLUTION**

Benchmarks can be created that add increasing numbers of items to `WeakConcurrentBag`. A comparison benchmark can be created, which adds increasing numbers of items to a mutable set.

Based on these benchmarks, small tweaks can be made to improve performance of `WeakConcurrentBag`.

**IMPACT**

`WeakConcurrentBag` is critical to built-in fiber dumps in ZIO 2.0 and making it faster will make high-fiber applications perform better.

**WHERE TO LOOK**

 - [WeakConcurrentBag](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/internal/WeakConcurrentBag.scala)
 - [benchmarks](https://github.com/zio/zio/tree/series/2.x/benchmarks/src/main/scala/zio/internal)

**PROBLEMATIC ISSUES**

To create and run a benchmark, it will be necessary to copy/paste an existing benchmark and lookup the command for running sbt-jmh. Strategies to optimize can be discussed on this issue or on Discord.

**Comment by emilhotkowski** [comment]
@jdegoes Can OSS contributors chime in with ideas or follow discussion on Discord ?

**Comment by adamgfraser** [comment]
@emilhotkowski Definitely!
