### ISSUE TITLE
Optimize performance of FiberRefs#join

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6853]
**ISSUE**

In ZIO 2, fiber refs under fork and join have become much more principled, relying on patch theory. However, this means the cost of joining has increased.

**SOLUTION**

This improvement is to add a benchmark to measure performance of `FiberRefs#join`, and then use this benchmark to do low-hanging-fruit optimization against the benchmark.

**IMPACT**

Fork/join happens a lot. In particular, it happens for all parallel operations, such as `foreachPar`. Optimizing the performance of `join` for the happy path will increase app performance.

**WHERE TO LOOK**

 - [benchmarks](https://github.com/zio/zio/tree/series/2.x/benchmarks/src/main/scala/zio)
 - [FiberRefs](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/FiberRefs.scala)

**PROBLEMATIC ISSUES**

Solving this issue will require copy/pasting an existing benchmark and becoming familiar with running benchmarks using sbt-jmh. If there are questions about the join algorithm, this issue or Discord may be used.

**Comment by mschuwalow** [comment]
I'll take this one

**Comment by adamgfraser** [comment]
Great!
