### ISSUE TITLE
Bug in secondOfMinute method Series/2.x

### ISSUE THREAD

**Issue by zarucki** [zio/zio#6854]
Small typo here. I believe this should be 

```s"Invalid argument in `secondOfMinute($second0)`. Must be in range 0...59")```

https://github.com/zio/zio/blob/1939f3bf4a1f1b9401f666e1b0136ba98e42e64e/core/shared/src/main/scala/zio/Schedule.scala#L1421

If I understand correctly this now refers to method`def second`.

**Comment by adamgfraser** [comment]
@zarucki Thanks for reporting! Just submitted a PR to fix this.
