### ISSUE TITLE
Elements don't make it past aggregateAsync stage

### ISSUE THREAD

**Issue by svroonland** [zio/zio#6862]
This is a follow up of #6831. I have create a minimal reproducer, but it depends on zio-aws and a local docker container to reproduce the issue. I have tried to remove all of this but removing any of the lines in this file would change the behavior. Removing `ZIO.scoped` usages seems to change the behavior of the test, perhaps that's a clue. Also, changing `aggregateAsync(batcher)` to `aggregateAsyncWithin(batcher, Schedule.spaced(1.second))` results in the issue not showing up anymore.

https://github.com/svroonland/zio-kinesis/blob/8b1c61fe1166231c40b5147d277ce1cd0fd8b235/core/src/test/scala/nl/vroste/testie/AggregateAsyncIssueTest.scala

To run it, it should be sufficient to launch [this docker-compose file](https://github.com/svroonland/zio-kinesis/blob/master/docker/docker-compose.yml) and run the test. Note that the first run will print "Got past aggregateAsync", but when running it again, it won't. So the stream needs to already exist.

**Comment by svroonland** [comment]
@vigoo @adamgfraser

**Comment by adamgfraser** [comment]
@svroonland Thanks! Will take a look but I think we are going to need to minimize to just ZIO to really tackle this.

**Comment by adamgfraser** [comment]
This is fixed on the latest version of `series/2.x`.
