### ISSUE TITLE
zio.test.Live required when ZIOSpecDefault test has the timeout aspect

### ISSUE THREAD

**Issue by gurghet** [zio/zio#6873]
I have the [following code](https://scastie.scala-lang.org/z9ODaBJITGqM5DBdLCDQUg):
```
import zio.*
import zio.test.*
import zio.test.TestAspect.*

object T extends zio.test.ZIOSpecDefault:

  def spec =
    suite("o")(
      test("b") {
        for {
          _ <- ZIO.service[zio.Console]
        } yield assertCompletes
      } @@ timeout(3.seconds)
    ).provide(zio.Console.live)
```
I get
```
──── ZLAYER ERROR ────────────────────────────────────────────────────

 Please provide a layer for the following type:

   [2m1. zio.test.Live
      
──────────────────────────────────────────────────────────────────────
```
I'm trying to understand why the `timeout` aspect basically cancels out the `TestEnvironment` provided by default.
If this is intended please close this issue.

**Comment by adamgfraser** [comment]
The `timeout` test aspect uses the `Live` service to access the "live" environment even when the test environment is provided, since we want the timeout to use the normal clock even when we do provide the live clock. So in your example above you can just use `provideCustom` or `provideSome`.
