### ISSUE TITLE
Race condition between fiber suspension/resumption and supervisor callbacks

### ISSUE THREAD

**Issue by oridag** [zio/zio#6893]
When a fiber is suspended and then immediately resumed, the `unsafeOnResume` callback may be called before the `unsafeOnSuspend`, which might cause in inconsistent state in the supervisor. The same is true for the other way around (resumed and immediately suspended)

**Comment by oridag** [comment]
Actually, since each suspend/resume pair is happening on the same thread, it's only an issue when a fiber is resumed immediately after suspending, not the other way around.

So this is what I think is happening: a fiber is resumed on thread `a`, after a while it is suspended and then immediately resumed on thread `b`. The expected sequence of supervisor calls would be `resume (thread a) -> suspend (thread a) -> resume (thread b)`. But since there's a race between the onSuspend callback running on thread `a` and the fiber resuming on thread `b`, a possible (and quite frequent) sequence of calls is `resume (thread a) -> resume (thread b) -> suspend (thread a)`.

I also noticed the following comment at the call site to `unsafeOnSuspend`, which I think refers to this issue:
```
// FIXME: Race condition on fiber resumption
```

**Comment by adamgfraser** [comment]
This will be fixed with the changes to the runtime that are forthcoming.

**Comment by adamgfraser** [comment]
This is fixed on the latest version of `series/2.x`.
