### ISSUE TITLE
Documentation not properly linked with series/2.x/zio/docs

### ISSUE THREAD

**Issue by DaniRey** [zio/zio#6894]
The documentation on the website still uses ZTraceElement, while it was updated to Trace in the series/2.x/zio/docs. 

![image](https://user-images.githubusercontent.com/7700482/171433517-5b2cec25-8d1e-4177-81af-71be050038f4.png)

Also the "edit this page" button doesn't work for "series/2.x"

![image](https://user-images.githubusercontent.com/7700482/171433787-8b324272-c968-462b-9cfe-2a2608149ede.png)

It points to https://github.com/zio/zio/edit/series/2.x/docs/howto/migrate/migration-guide.md instead of https://github.com/zio/zio/edit/series/2.x/docs/guides/migrate/migration-guide.md (howto vs guides)

**Comment by khajavi** [comment]
This issue has been resolved, so we can close it.
