### ISSUE TITLE
Cannot get effectful shared layer to run with live environment in tests

### ISSUE THREAD

**Issue by gurghet** [zio/zio#6897]
> ZIO 2, scala 3

I have the following code
```scala
case class BigBen(time: LocalDateTime)
object BigBen:
  val layer = ZLayer(localDateTime.map(BigBen.apply))

object Test extends ZIOSpecDefault:
  def spec =
    suite("suite")(
      test("test") {
        for
          bigBen <- ZIO.service[BigBen]
          _ <- printLine(bigBen.toString)
        yield assertCompletes
      }
    ).provideShared(BigBen.layer)
```
I would like the `BigBen` to be initialized with the real time in tests, but it invariably displays the epoch time, meaning it's fetching the test environment.
I tried to get the layer like this:
```scala
val `liveLayer?` = ZEnv.live.flatMap { zenv =>
  BigBen.layer.map(l => l.unionAll(zenv))
}
```
But it still doesn't work.

In short: how to provide a shared layer that is instantiated with effects run on live services?

**Comment by adamgfraser** [comment]
Remember the default services are not in the environment anymore in ZIO 2.0 so providing them in the environment is not going to do anything. On `series/2.x` you can use the `ZIO.withClock` and `ZIO.withClockScoped` operators to control the implementation of the clock that is used, so you could do something like `ZLayer.scoped(ZIO.withClockScoped(Clock.ClockLive)) >>> myLayer`. That operator was added after `RC6` so for now you could do something like `ZLayer.scoped(ZEnv.defaultServices.locallyScopedWith(_.add(Clock.ClockLive))) >>> myLayer`.
