### ISSUE TITLE
ZIO Test: `TestAspect.nondeterministic` isn't that deterministic

### ISSUE THREAD

**Issue by kubukoz** [zio/zio#6907]
`TestAspect.nondeterministic` seems to only set the seed once before each test, so if two tests happen to start around the same time, they might get the same seed - and in turn, generate the exact same sequence numbers.

I can reproduce this semi-reliably by running the following suite (3-6 out of 10 runs)

```scala
import zio.ZIO
import zio.clock.Clock
import zio.duration._
import zio.random.Random
import zio.test.Assertion._
import zio.test.DefaultRunnableSpec
import zio.test.ZSpec
import zio.test._
import zio.test.environment.TestEnvironment

import java.util.concurrent.atomic.AtomicReference

object MyTest extends DefaultRunnableSpec {
  override def aspects
      : List[TestAspect[Nothing, TestEnvironment, Nothing, Any]] = List(
    TestAspect.nondeterministic
  )

  private val values = new AtomicReference[Set[String]](Set.empty)

  val randomLetter: ZIO[Random, Nothing, Char] =
    zio.random.nextIntBetween('a', 'z').map(_.toChar)

  val randomTestString: ZIO[Random, Nothing, String] =
    ZIO
      // 50 runs of the generator - too much to be a coincidence
      .collectAll(List.fill(50)(randomLetter))
      .map(_.mkString)
      .tap { v =>
        ZIO
          .effectTotal {
            values.getAndUpdate(_ + v)
          }
          .flatMap { existing =>
            if (existing.contains(v))
              ZIO.effectTotal(println("found dupe")) *>
                ZIO.dieMessage(
                  "duplicate value generated! " + v + s" (among $existing)"
                )
            else ZIO.unit
          }
      }

  val simpleRandomTest = assertM {
    randomTestString
  }(isNonEmptyString)

  def spec: ZSpec[Environment, Failure] = suite("example")(
    (1 to 100).toList.map { i => testM(s"Test$i")(simpleRandomTest) }: _*
  )
}
```

A workaround that seems to work fine is to `.provideCustomLayer(Random.live)` on the suite.

Version: zio-test 1.0.15

JRE: openjdk11

**Comment by adamgfraser** [comment]
Yes, the implementation uses the current time in nanoseconds to set the seed so if multiple tests start at exactly the same time they could have the same seed.

I guess the question is whether this is a problem. I don't think this operator purports to give you seeds that are distinct from each other and in most cases I think the value of this operator is that you get different values between different runs of the same test versus you get different values between different tests not he same run.

**Comment by kubukoz** [comment]
That makes sense. Are there any aspects I can use to just use the live Random instead? (and for some tests, even the whole Live ZEnv)?

**Comment by adamgfraser** [comment]
In ZIO 1.0 you need to do it with a layer like `Random.live` or `ZEnv.live`. In ZIO 2.0 there are a set of aspects `withLiveRandom` or `withLiveEnvironment` you can use.

**Comment by adamgfraser** [comment]
@kubukoz I think this should have the behavior you want on ZIO 2 since the seed is set with a random long from the live `Random` service instead of the time. Not sure what version you are on.

**Comment by kubukoz** [comment]
I was on 1.x, but I'm on a different team that doesn't use ZIO anymore.
