### ISSUE TITLE
ZIO test: Test Results print incorrectly, if a Suite only contains one Test

### ISSUE THREAD

**Issue by BalduinLandolt** [zio/zio#6912]
Given the following test:

```scala
object ProjectDomainSpec extends ZIOSpecDefault {

  override def spec = suite("main suite")(subsuite1, subsuite2)

  val subsuite1 = suite("sub-suite 1")(
    test("test 1 in sub-suite 1") {
      val _ = "do something here"
      assertTrue(true)
    },
    test("test 2 in sub-suite 1") {
      val _ = "do something here"
      assertTrue(true)
    }
  )

  val subsuite2 = suite("sub-suite 2")(
    test("test 1 in sub-suite 2") {
      val _ = "do something here"
      assertTrue(true)
    }
  )
}
```

the expected test output would be:

```
+ main suite
    + sub-suite 1
        + test 2 in sub-suite 1
        + test 1 in sub-suite 1
    + sub-suite 2
        + test 1 in sub-suite 2
```

however I actually get

```
+ main suite
    + sub-suite 1
        + test 2 in sub-suite 1
        + test 1 in sub-suite 1
        + test 1 in sub-suite 2
```

It seems, if a test suite only contains one test element, the suite name does not print in the test results.

If I add a second test to the suite, it works as expected.

ZIO/ZioTest version: 2.0.0-RC6

**Comment by swoogles** [comment]
Thanks for reporting @BalduinLandolt !
This should already be resolved via: https://github.com/zio/zio/pull/6793
That was merged in the week following the RC6 release 🙂 

Testing your example on the latest version of ZIO gives the expected output:

<img width="1435" alt="Screen Shot 2022-06-14 at 12 59 23 PM" src="https://user-images.githubusercontent.com/2054940/173668010-7270e32e-0670-414e-970e-94d4a1e20819.png">

**Comment by BalduinLandolt** [comment]
Wonderful! All the more reason to await the 2.0 release eagerly 🙂  
I guess this can be closed, then.
