### ISSUE TITLE
ZIO Fiber - interrupt all fibers if one fiber fails

### ISSUE THREAD

**Issue by frevib** [zio/zio#6915]
We run a ZIO app that runs multiple fibers. We would like to crash the whole app when one of the fibers fails. I cannot find a method to do that. I tried e.g. `zip` or `<*>`, but this method will wait for all fibers to return.

Example:

```Scala
  def run(args: List[String]) = for {
    failMe <- ZIO.fail(new Exception("test")).catchAll(_ => UIO(ExitCode.failure)).fork
    daemon <- someDaemon.catchAll(_ => UIO(ExitCode.failure)).fork
    // interrupt daemon if failMe fails, but also interrupt failMe if daemon would fail
  } yield ExitCode.success
```

**Comment by adamgfraser** [comment]
I believe this was answered on Discord. As discussed there `raceFirst` is a good operator for this.
