### ISSUE TITLE
Decrease minimum duration of a timed test from 6 seconds to 60 ms (speeds up tests)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#695]
See [here](https://github.com/scalaz/scalaz-zio/pull/576) for background.

Essentially, with a small change, we can greatly speed up the whole test suite! 🎉 

Code has been written above, just needs reworking to master.

**Comment by ksarath** [comment]
Can I pick up this task?

**Comment by jdegoes** [comment]
@ksarath That would be great!

**Comment by ksarath** [comment]
@jdegoes Thank you

**Comment by ghostdogpr** [comment]
Done in #735
