### ISSUE TITLE
2.0 Release notes: add info about `ZManaged` lib, link migration guide and mention scalafix migrations

### ISSUE THREAD

**Issue by domdorn** [zio/zio#6974]
1.) I suggest to add a sentence like this to the release notes: 

[quote]
While we encourage you to write new code using `Scope`s, you don't have to change your whole codebase to upgrade to ZIO 2. Using the `zio-managed` library 

```
"dev.zio" %% "zio-managed" % "2.0.0"
```
allows you to keep your `ZManaged` code until you're ready to migrate.

[/quote]

2.) <del> the `zio-managed` lib needs to be released for 2.0 (currently its 2.0.0-RC6).</del>

3.) The migration guide should be linked and 
4.) the existance of the scalafix migrations should explicitely be noted in the release notes.

**Comment by vigoo** [comment]
I think it is released: https://search.maven.org/artifact/dev.zio/zio-managed_2.13/2.0.0/jar

**Comment by domdorn** [comment]
ok, then https://mvnrepository.com/artifact/dev.zio/zio-managed needs to catch up..

**Comment by adamgfraser** [comment]
![image](https://user-images.githubusercontent.com/20825463/175781493-e7c3400b-fbf8-48ed-9150-1d70e7e62940.jpeg)

This is already done.

**Comment by domdorn** [comment]
I did not find a mention of the `ZManaged` lib and the link to the migration guide leads to a 404.. 
![grafik](https://user-images.githubusercontent.com/100349/175824384-7b0ede4b-5bd5-41c2-bc48-3a8214f496a9.png)
![grafik](https://user-images.githubusercontent.com/100349/175824399-986e0fd2-79f0-4afc-8838-0808386fd29f.png)

**Comment by adamgfraser** [comment]
The location of the migration guide change was changed when we published the updated documentation yesterday. Just updated the link to reflect that.
