### ISSUE TITLE
The search bar on the ZIO documentation website is no longer there

### ISSUE THREAD

**Issue by beneyal** [zio/zio#6979]
Hi!

Congratulations on the new release and docs! Will it be possible to bring back the search bar that was present in the previous version of the docs website? It was tremendously helpful!

Thanks 🙂

**Comment by adamgfraser** [comment]
Yes we're working on some issues with the search bar and will enable it again when those issues are resolved.

**Comment by khajavi** [comment]
Search bar fixed via #7419

**Comment by khajavi** [comment]
Search bar fixed via #7419
