### ISSUE TITLE
ZIO 2 looses stack trace when integrating with non-zio classes

### ISSUE THREAD

**Issue by myazinn** [zio/zio#7003]
New tracing system doesn't work well when non-zio classes are involved. Here's a code example with ZIO 2
https://scastie.scala-lang.org/N0FidrcFReqaDqWewGulLg
Based on the stack trace provided, it's impossible to tell where the exception was generated nor how we got there. Absence of stack traces in such cases can be a real headache when integrating with legacy / poorly written code.
Apparently, there is a way to restore this information
https://scastie.scala-lang.org/ACQ5kLEwQiClotmoxHZh3Q
But it's not user-friendly at all. Besides, not everyone would know about it (I didn't know).

Meanwhile, it was easy to do with ZIO 1.
https://scastie.scala-lang.org/DblQen8yRqGyG02z0YunZQ
Although these traces had a lot of unnecessary things, they had necessary things as well :)
Could you please somehow combine old and new approaches to give a programmer more information by default?

**Comment by adamgfraser** [comment]
Hmmm this looks like the correct trace to me:

```scala
import zio._

object Example extends ZIOAppDefault {

  class POJOService {

    def something(i: Int): String = if (i > 0) foo(i) else bar(i)

    private def foo(i: Int): String = if (i < 100) i.toString else ???

    private def bar(i: Int): String = if (i > -100) i.toString else ???

  }

  val effect =
    for {
      service <- ZIO.service[POJOService]
      _ <- ZIO.attempt(service.something(1))
      _ <- ZIO.attempt(service.something(-1))
      _ <- ZIO.attempt(service.something(101))
      _ <- ZIO.attempt(service.something(-101))
    } yield ""

  val run =
    effect.provide(ZLayer.succeed(new POJOService))
}
```

```
[info] timestamp=2022-06-29T12:59:48.841225Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" scala.NotImplementedError: scala.NotImplementedError: an implementation is missing
[info]  at <empty>.Example.effect(Example.scala:20)
[info]  at <empty>.Example.run(Example.scala:25)"
```

Line 25 is the third `ZIO.attempt` call, where the failure occurs. Line 20 is the body of `run`, which is where `effect` was called from. So this seems like the correct and minimal execution trace that points you to `ZIO.attempt(service.something(101))`, which is indeed the source of the problem.

**Comment by adamgfraser** [comment]
We may be able to do more to preserve part of the Java stack trace here.
