### ISSUE TITLE
Docs have a lot of small errors

### ISSUE THREAD

**Issue by olekslitus** [zio/zio#7007]
I was currently reading through new docs for ZIO 2 and saw a lot of little errors, example text will mention `provide`, but example will have `provideEnvironment`. I do not have a full list, as I do not have enough time to compose one (sorry).

**Comment by adamgfraser** [comment]
Thanks for your feedback! If you see any please point them out and we will fix!

**Comment by salvalcantara** [comment]
In [the-three-laws-of-zio-environment](https://github.com/zio/zio/blob/series/2.x/docs/datatypes/contextual/index.md#the-three-laws-of-zio-environment), it says:

> Using ZIO environment follows three laws:
> 
> 1. Service Interface (Trait) — When we are defining service interfaces we should never use the environment for dependencies of the service itself.
> 
> For example, if the implementation of service X depends on service Y and Z then these should never be reflected in the trait that defines service X. It's leaking implementation details.
> 
> So the following service definition is wrong because the Console and Clock service are dependencies of the Logging service's implementation, not the Logging interface itself:
> 
> ```scala
> import zio._
> trait Logging {
>   def log(line: String): ZIO[Any, Nothing, Unit]
> }
> ```

I think the above definition is **right** (not **wrong**, as the text says) since the Console and Clock dependencies are not reflected in the Logging interface trait. I would propose something along these lines:

> [...] So the following Logging service is defined without any explicit mention to Console and Clock (even if the actual implementation depends on them, as seen later):
> 
> ```scala
> import zio._
> trait Logging {
>   def log(line: String): ZIO[Any, Nothing, Unit]
> }
> ```

**Comment by adamgfraser** [comment]
@salvalcantara The example just needs to be updated to use services that aren't the default services that are built into the ZIO Environment, which was just done so if you look at `series/2.x`.

**Comment by khajavi** [comment]
Thank you for reporting. All issues related to the default services have been addressed and published to zio.dev.  So I'm going to close this issue.

If you find any other errors in the documentation, please report them separately, and we will fix them as soon as possible.
