### ISSUE TITLE
Promise + repeatZIOChunkOption memory leak

### ISSUE THREAD

**Issue by adwells-ds** [zio/zio#7066]
We were investigating the memory leak(https://github.com/zio/zio-kafka/issues/485) in `zio-kafka` after upgrade to ZIO 2.0 and apparently Fibers/Promises are causing OOM again(we had the similar issue about 2 years ago with ZIO 1.0, ref https://github.com/zio/zio/issues/4457)
Simplified example from `zio-kafka`:
```
  case class Record(x: Int)

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    def stream(queue: Queue[Promise[Option[Throwable], Chunk[Record]]]) =
      {
        for {
          p <-  Promise.make[Throwable, Unit]
          s  = ZStream.repeatZIOChunkOption(for {
            request <- Promise.make[Option[Throwable], Chunk[Record]]
            _       <- queue.offer(request).unit
            result  <- request.await
          } yield result).interruptWhen(p)
        } yield  (p, s)
      }

    for {
      queue <- Queue.unbounded[Promise[Option[Throwable], Chunk[Record]]]
      // fulFill promise
      _ <- ZStream
        .fromQueue(queue)
        .mapZIO(_.succeed(Chunk.fromIterable(0.to(100).map(Record))))
        .runDrain
        .fork
      tup <- stream(queue)
      // dummy consumer
      _ <-
        tup._2.tap{ _ =>
          val (p, s) = tup //just for the debug purpose
          ZIO.unit
        }.runDrain
    } yield ()
  }
```
After couple seconds the number of observers will be up to 100k and continue to grow, not allowing gc to cleanup linked resources:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/87975016/178754413-8e93f1f8-21fb-4bc9-b046-89461de8c5e7.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/87975016/178754292-987783d8-af4d-4a62-a21c-06884bb6c007.png">

**Comment by vigoo** [comment]
Nice reproducer!

**Comment by vigoo** [comment]
Problem is caused by `.interruptWhen(p)`

**Comment by vigoo** [comment]
Smaller reproducer:

```scala
    def emit(n: Int): ZChannel[Any, Any, Any, Any, Nothing, Record, Nothing] =
      ZChannel.write(Record(n)) *> emit(n + 1)

    for {
      p <- Promise.make[Throwable, Unit]
      _ <- emit(0).interruptWhen(p).runDrain
    } yield ()
```

**Comment by adwells-ds** [comment]
A bit more details, I was not able to find any calls of `removeObserver` or `removeChild`. Parent fiber is full of 'dead' children
<img width="955" alt="image" src="https://user-images.githubusercontent.com/87975016/178792302-e3068959-fb35-4956-a55b-0497856ae2f4.png">
Here is the place where we add both observer and child
https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L2487-L2491

**Comment by jdegoes** [comment]
In ZIO 2.0, currently if you cancel `await`, it will not remove the observer. That needs to be fixed, and it should then resolve this issue.

**Comment by jdegoes** [comment]
See `FiberRuntime#await` implementation.

**Comment by jdegoes** [comment]
Looks like @adwells-ds identified a separate issue [here](https://github.com/adwells-ds/zio/commit/cc6496800841e248347da8744f80d5756596b421).

**Comment by adwells-ds** [comment]
If I'm not mistaken, we have a case when we execute the effect but did not set the `exitValue`, hence we have 'dead' Fiber with `running = false`, empty queue and we not able to remove it from observers. 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/87975016/178821770-18e15f7b-63dd-4e09-9dc4-ee3b32131c4a.png">
