### ISSUE TITLE
Non-blocking Code Being Shifted To Autoblocking Pool, Degrading CPU Performance By Running Too Many Tasks In Parallel

### ISSUE THREAD

**Issue by dccorona** [zio/zio#7074]
I'm working on migrating a large production workload from ZIO 1.x to 2.x, and am encountering issues with the autoblocking detection. The detection seems to be picking up on things that are not blocking and shifting them to the blocking threadpool, which in turn is resulting in the app paralleling at a higher factor than it used to, overloading the CPU, and slowing the entire application.

My reading of the autoblocking implementation suggests that as it exists today, the definition of "blocking" is "took more than 100ms to execute", which is certainly not a compatible definition with our app. Something that is taking over 100ms because of its CPU usage is exactly the kind of thing that we want to keep on a threadpool that is bounded by number of processors. I also have some concerns around whether a long GC pause might cause something to be incorrectly flagged, though there may be reasons I'm missing that make that one a non issue. Finally, the mechanism for determining whether or not 100ms have elapsed [looks to be based on `System.currentTimeMillis()`](https://github.com/zio/zio/blob/series/2.x/core/jvm/src/main/scala/zio/internal/ZScheduler.scala#L208), which in our environment might fluctuate as the system clock updates, again potentially resulting in something being incorrectly flagged as "blocking".

Admittedly, I may be totally misunderstanding the code, so I don't want to get too deep into speculation around what the issue might be. But regardless, this has been my observation, and I've written an example app to show it. All this app really does is 1. runs a deep fibonacci computation with tail recursion, designed to take over 100ms to run (you may have to modify the example's depth based on your hardware), 2. tries to run 10,000 of them in parallel, 3. they get incorrectly detected as blocking and begin to submit to a blocking threadpool, 4. CPU goes to 100% and the app eventually crashes.

Running the same app on the latest ZIO 1.x version just takes a long time and spins the CPU up to *near* 100% (as expected) but does not crash.

I'm hoping that we can at least get a configuration option to disable autoblocking detection (which is probably a good option to have whether this can be fixed or not). 

```scala
package zio.scheduler.test

import zio.{Scope, ZIO, ZIOAppArgs}

import scala.annotation.tailrec

object BlockingSchedulerTest extends zio.ZIOAppDefault {

  override def run: ZIO[ZIOAppArgs with Scope, Any, Any] = {
    ZIO.foreachParDiscard(0 until 10000)(i => runFibThreadInfo(s"$i"))
  }

  def runFibThreadInfo(id: String) = runThreadInfo(id, runFibTimed(1000000000))

  def runThreadInfo[R, E, A](id: String, task: => ZIO[R, E, A]) = {
    for {
      beforeThread <- ZIO.succeed(Thread.currentThread().getName)
      _ <- task
      afterThread <- ZIO.succeed(Thread.currentThread().getName)
      _ <- zio.Console.printLine(s"$id started on thread $beforeThread and ended on thread $afterThread")
    } yield ()
  }

  def runFibTimed(n: Long) = {
    for {
      start <- zio.Clock.nanoTime
      _ <- ZIO.succeed(fib(n))
      end <- zio.Clock.nanoTime
      time = scala.concurrent.duration.Duration.fromNanos(end - start)
      _ <- zio.Console.printLine(s"took ${time.toMillis} ms")
    } yield ()
  }

  def fib(n: Long): Long = {
    @tailrec
    def fib_tail(n: Long, a: Long, b: Long): Long = n match {
      case 0 => a
      case _ => fib_tail(n - 1, b, a + b)
    }

    fib_tail(n, 0, 1)
  }
}
```

**Comment by adamgfraser** [comment]
Code like this is "effectively blocking" in the sense that it does not yield control back to the runtime for a significant period of time, which could compromise the runtime's ability to process other requests.

This problem can be easily solved by using `withParallelism(8)` after `foreachParDiscard`. Alternatively, if you want to solve it at the level of the `Executor` you can use `withExecutor` with an `Executor` backed by a fixed thread pool using `Executor.fromJavaExecutor` or `Executor.fromExecutionContext`.

**Comment by narma** [comment]
At least 4 point deserves attention, app shouldn't goes into crash in such circumstances

**Comment by dccorona** [comment]
I agree that code like this, in general, is a problem needing to be solved. I'm not sure that I'd agree that the solution is to move to a blocking pool, I'd instead say that really this code should be rewritten to use ZIO more comprehensively (i.e. so that it yields at every recursion). I certainly don't think that one should be *required* to agree with the "shift it to a blocking pool" approach to use ZIO.

The `foreachpar` was just there to present a toy example that demonstrates the risk, not as a real production example. In practice, what this looks like in an app like ours is that there is code that is not "fully-ZIO'ed", in the sense that large, computationally expensive sections of code (deep loops or traversals, etc) are wrapped up in ZIO as-is, without using ZIO primitives to make them yield at each iteration. And they aren't explicitly massively parallelized like in my example, but rather peppered throughout a complex app (say, a web server handling many requests), and as these not actually segments get shifted off the main pool, the parallelism of the compute portion of the app continues to grow and grow until it reaches an unsustainable point and everything begins to slow.

Again, I do agree with the notion that a rewrite is probably ideal, if possible, for code like this, so that it yields to the runtime more frequently. But that's often a lot of work, and sometimes impossible (i.e. if the thing you're wrapping in ZIO is a lib you don't control). However, it worked quite well on ZIO 1.0, and I think it should be possible to upgrade to 2.0 without having to rewrite everything to a totally new style first.

Constraining the blocking executor would help, however that is only a viable fix for apps that don't also have a lot of truly blocking code that they *do* want to send to the blocking executor.

And again, none of that addresses the concerns around false-positive detection of blocking code. We're seeing things that execute almost instantaneously get marked as blocking. We're not yet sure whether this is due to GC pauses, clock skew, or the fact that the "key" for a blocking effect is its trace, meaning that if the code happens to be written in a one-liner form (i.e. `nonblockingEffect *> blockingEffect` or similar), both things will share an identifier and (as far as I can tell) will both be flagged as blocking if one of them is.

**Comment by adamgfraser** [comment]
I agree with you that the underlying issue here is that this code is doing a large block of synchronous work without yielding control back to the ZIO runtime. In a typical ZIO application a large number of small workflows would be composed together using operators like `flatMap`, frequently yielding control back to the runtime. When you have large blocks of third party code that doesn't happen.

I would question the notion that this worked quite well in ZIO 1.0. In the example above, assuming the 10,000 workflows each took 100 milliseconds to execute it would take up to 17 minutes for the runtime to be able to process any new work, such as an interrupt signal saying that this work isn't even necessary. So even though it does not block a thread it compromises the runtime's ability to be responsive and probably should have been shifted to the blocking thread pool or a dedicated thread pool in ZIO 1.0.

I think the two most straightforward ways to deal with this is either to limit parallelism at a higher level (e.g. using `withParallelism` or a `Semaphore`) or using `onExecutor` with your own executor with a fixed number of threads. `withParallelism` is regional so applying it at a higher level will limit parallelism at lower levels, though I agree there can be some issues here when parallel workflows spawn other parallel workflows. `Semaphore.withPermit` can be a very nice solution if you use that with your compute intensive workflows. Finally, using `onExecutor` with a fixed thread pool is a very nice way to say you want to run this compute intensive work and you want to use the executor to control the degree of parallelism.

**Comment by dccorona** [comment]
I think this conversation is over-indexing a bit on the toy example provided. Again, that was just thrown together to quickly demonstrate that you can pretty easily write code that makes the 2.0 runtime crash due to resource exhaustion. Yes, the toy example also doesn't run quickly on the old runtime, but it does at least complete.

In either case, what we do in production looks nothing like this. What we're seeing there is that this 'blocking' classification is happening also for tasks that are not long-running. It immediately begins when you start the application, which classifies some of the 'main' function as blocking - possibly related to GC and lazy initialization both on the code source and the JVM side (e.g. JIT optimizations). That said it's also not easy to debug or introspect into this as the entire logic and state is private and only the debugger can shed light on what's happening. 

As you already pointed out this can be a big problem with code that has high parallelization levels. And that's exactly what we observe in our case for a web service after upgrading from 2.0.0-RC2. 

We run a fiber-per-request model that takes a request coming from a Netty-based HTTP engine (it's not zio-http) and hands it over to ZIO with `Runtime.unsafe.fork(...).unsafe.addObserver(...)`. The maximum degree of parallelization gets limited within the ZIO runtime, i.e. we measure parallelism, mark requests that exceed a certain level and reject those with HTTP 5xx. This essentially maps to unconstrained parallelism between the point where we hand over the request to ZIO and the point where we reject the request. With RC2 this has been working perfectly and the measured peak parallelism maxed out only slightly above the throttle limit - even under extreme overload scenarios during stress tests. 

With ZIO 2.0 final this degrades in a catastropic way because of auto-blocking. What previously peaked at ~35 parallel fibers then turned into several hundreds during stress test scenarios (e.g. peak load +100%) with code profilers measuring 2/3 of the total CPU time spent on the blocking thread pool (with 100% RUNNABLE thread states). The entire application does not have a single blocking operation, nor does it have long-running synchronous code - which means that all 'blocking' traces are false-positives. For most stress test runs now the service crashes at some point - and even if it doesn't its performance is permanently degraded as tasks that are classified as blocking once will be treated as such for as long as the application runs.

We also did a cross-check by terminating the `ZScheduler-Supervisor` thread (kill thread by name) at application startup time and it immediately fixes the problem. For those stress test runs the behavior is approximately the same as for RC2 with highly stable and predictable latencies (even in the high quantiles), no thread count spikes and no crashes.

In my opinion this behavior defeats the purpose of the auto-blocking feature - at least in our case, this is not better than the consequences of forgetting to mark something as blocking. Given the catastrophic failure mode that we observed plus the inability to recover after load goes back to normal, it makes up two red flags for our use case with ZIO 2.0 in terms of resiliency. Overriding the executor as you suggested (which is what zio-http does) disables auto-blocking (as it only applies to ZScheduler), however you also lose the Tokio-style optimizations that you did, so it's not a great option for us.

Please note that the way that you detect blocking tasks (by polling every 100ms) is extremely prone to false positives for a couple of possible reasons:
* Long GC pauses (>=100ms isn't super uncommon with G1 if your heap is sufficiently large).
* Lazy initialization of the code (i.e. takes >100ms the first time you call it but then it's sigifnicantly faster).
* Lazy JVM compilation (i.e. C2 compiler).
* Any sort of OS hickup, e.g. VMs being migrated to another host. 
* Clock skew.

And the consequences of false-positives can be generally degraded performance, partially unbounded parallelism all the way to crashing applications.

**Comment by adamgfraser** [comment]
Yeah, I think you totally have the right idea in stepping back.

Autoblocking uses a heuristic which works for most ZIO programs but is based on the assumption that workflows are going to be composed of many small operations that are executed quickly, which is not the case in your program. It is a heuristic so there may be false positives which is also generally not a problem except when you do things with unbounded parallelism. Unbounded parallelism is itself not ideal but you can do it.

So I see basically three solutions to your problem:

1. Control the degree of parallelism. If you created one semaphore at the top of your program with permits equal to the desired parallelism and did `Runtime.unsafe.fork(semaphore.withPermit(???))` you would achieve I think exactly your desired semantics in what it sounds like from your description would be a couple line change.
2. Shift the execution of the workflows. If these workflows are really long running they really shouldn't be run on the core thread pool and you could also achieve your semantics by shifting them to a dedicated compute pool. Probably running each effect on a single threaded executor would actually be ideal for efficiency.
3. If you really don't want either of these then just run the whole thing on a fixed thread pool, which would use the thread pool to get you the desired degree of parallelism and get you back to the ZIO 1.0 behavior.

We could also potentially make whether autoblocking is enabled configurable, but I tend to think one of the first two solutions is preferable as if you are piling up a giant queue of long running work that really is going to compromise the responsiveness of the runtime.

Have you tried the first solution above? I think that would be very easy and would get you exactly what you are looking for.

**Comment by dccorona** [comment]
I think we still have some of the original proof-of-issue example mixed in with the actual production use case here. Ignore everything about long-running tasks (> 100ms). We don't have any in our actual production system. I made things that run for over 100ms in my example because I couldn't craft a code snippet that would guarantee a false-positive due to unpredictable events like JVM warmup or GC pauses, etc.

So in the real production system, what we have is a lot of tasks that are *not* long running getting flagged over to the blocking pool. Our speculation is that it is for one or more of those false-positive-causing issues I listed above. Ultimately this boils down to the idea that whether or not the autoblocking heuristic is a fit is a function not only of the app logic, but *also the runtime environment*. The hardware in use (i.e. if you use something like an AWS spot instance and a piece of logic is unfortunate enough to get stuck running right when you exhaust your CPU credits), the JVM settings, the bytecode itself and how heavily it relies on JIT to reach its optimal runtime, etc. etc. In our case, this heuristic isn't working for us, not because we have long running tasks that take over 100ms in the average (or even p99) case, but because our runtime environment causes them to take over 100ms (or *look* like they do because of clock adjustments) very, very infrequently. But the heuristic for autoblocking only needs that to happen once, and then that's it for the life of the app.

We have not tried the semaphore approach. Although it seems like it would work for the current version of our app, we are currently working on an enhancement to the throttling logic that, during periods of load, more intelligently throttles the traffic (basically, we'll eventually be tagging candidates for throttles and then separately using logic to decide what gets bounced and when gets allowed through from among that set, so a simple semaphore will no longer fit). So that isn't really a great solution for us because we'll just end up right back here again when we do eventually release that logic.

Again, we're not piling up a queue of long-running work. We're piling up a queue of quick work that the runtime *thinks* is long-running because, for various reasons, it happens to have been flagged as such incorrectly.

I don't see a path forward for us to move onto 2.0 without the ability to disable autoblocking detection, at least in its current form.

**Comment by adamgfraser** [comment]
We can definitely look at either making a version of the scheduler available that doesn't do autoblocking or making the autoblocking heuristic more robust to these kinds of intermittent delays but I think you have a couple of really straightforward paths to upgrade right away.

First is just to use a fixed thread pool. That is going to get you back to exactly the behavior you have today.

Second I think the semaphore solution will either work with your throttling solution or will be rendered unnecessary by your throttling solution because it has the same effect as using a fixed thread pool. If the throttling solution is itself throttling things down to the acceptable level of parallelism then that will solve your problem. If the throttling solution is still letting through more tasks than the desired degree of parallelism the semaphore will limit you to the desired level of parallelism. And again I think that should be a very quick change.

**Comment by aartigao** [comment]
@dccorona Thank you very much for your detailed description. I think we're hitting the same issue.

Today we merged the ZIO 2 code for one of our services and boy... the performance drop was dramatic: x3 slower than versions that didn't have the autoblocking heuristics.

We've a very simple app setup: Tapir (using ZIO HTTP) + Doobie via cats-interop. Can't share more details now, because we're in the middle of the investigation. But we're most probably going to rollback to RC2, which was the one used in Prod that was working perfectly.

If I can suggest, in my opinion, I think the idea of having autoblocking as an option and not a force for the runtime is the right approach. I suspect the more people updates to ZIO 2 final, the more complains we'll see. I like the idea of trying new things but maybe this change should've been tagged as experimental, and not a fundamental change on the core system in the last minute.

**Comment by adamgfraser** [comment]
I will take a look at this.
