### ISSUE TITLE
[2.0] no useful trace when ZIO dies

### ISSUE THREAD

**Issue by artur-jablonski** [zio/zio#7111]
I would expect this:

```scala
 ZIO.succeed("ITEM")
      .map(_ => List.empty.head) //kaboom!
```

to print an error message that would allow me to trace the problem back to the code, but this is what I get:

```
timestamp=2022-07-21T12:50:21.656468272Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)"
```

which is only partially useful, I still don't know where exactly I tried to access head of empty list. What am I missing?

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
