### ISSUE TITLE
provide `flatten` on `ZIO[R,E, List[List[A]]]` that returns `ZIO[R,E, List[A]]`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7117]
given a helper method
```scala
def getOptEinheiten(assetId: AssetId): ZIO[Any, FailureException, List[OptimierbareEinheitAsset]]
```

I want to be able to use `.flatten` after using `ZIO.foreach` to flatten the list. 
e.g. I want to be able to write this:
```scala
for { 
... 

        optEinheiten <- ZIO.foreach(speicherKWIDs)(assetId => getOptEinheiten(assetId)).flatten
      } yield AssetInfo(assetId, details.name, zr,  optEinheiten)
```

instead of having to write this
```scala
for { 
... 

        optEinheitenList <- ZIO.foreach(speicherKWIDs)(assetId => getOptEinheiten(assetId))
        optEinheiten = optEinheitenList.flatten
      } yield AssetInfo(assetId, details.name, zr,  optEinheiten)
```

In this service, I'm currently stuck on ZIO 1.x .. maybe this is already fixed in ZIO 2.x

**Comment by adamgfraser** [comment]
You can just do:

```scala
for { 
... 

        optEinheiten <- ZIO.foreach(speicherKWIDs)(assetId => getOptEinheiten(assetId)).map(_.flatten)
      } yield AssetInfo(assetId, details.name, zr,  optEinheiten)
```

**Comment by domdorn** [comment]
I know I can do this, it would just be a little more convenient, like the helpers we have for `.some` or `.right` , etc.
If convenience methods like these are not a priority, feel free to close the issue

**Comment by adamgfraser** [comment]
Yeah, there is a trade-off here of have a single method would be slightly more convenient in this case but also there is an aggregate effect of more methods on ZIO make it harder to find the method you want and there are already a large number of operators on ZIO.

In this case in particular there are a ton of different collection operators that can currently be done as `zio.map(_.someCollectionOperator)` that could potentially have `zio.someCollectionOperator` convenience methods but I think this just results in an explosion of additional ZIO operators without much benefit.

In addition, in this case in particular there is an issue that we would then have to `flatten` variants, one that takes a `ZIO[R, E, ZIO[R, E, A]]` and flattens it and one that takes a `ZIO[R, E, List[List[A]]]` and flattens it. Those are conceptually quite different in that one runs an inner `ZIO` workflow versus the other just transforms the output of a single one. So while these could both work I think this also creates some risk of confusion.

So going to close this though thanks for raising!

**Comment by 987Nabil** [comment]
@domdorn or anyone who finds this later on. I think especially with Scala 3, we should use extension methods to have some convince like this. So we can tailor some common convince methods for our own code base, without polluting our favorite library.
In Scala 2 this has some drawbacks and ppl tend to avoid this. But Scala 3 removes this pain, I'd say.

**Comment by domdorn** [comment]
@987Nabil hmm.. 

I know this way to do it in scala2.. 
```scala
implicit class FlattenExt[R,E,A](in: ZIO[R, E, List[List[A]]) { 
 def flatten: ZIO[R, E, List[A]] = in.map(_.flatten)
 } 
```

how would scala3 make this better/remove the pain?

**Comment by 987Nabil** [comment]
```scala
extension [R, E, A](effect: ZIO[R, E, List[List[A]]])
  def flatten: ZIO[R, E, List[A]] = effect.map(_.flatten)
```
@domdorn this does not create a new object when called. It is more syntactic sugar. Also the explicit `extension` makes intention more clear and easier for new defs.
