### ISSUE TITLE
Unused type paramter R1 in checkAllPar and some check and checkAll overloads cause compilation failures and makes them unusable

### ISSUE THREAD

**Issue by frabbit** [zio/zio#7118]
I'm currently trying to figure out how checkAllPar can be used. I can't get my example compiled and i wonder if this is related to the unused type parameter R1, see: https://github.com/zio/zio/blob/10fc3699b9c0e36748bc4b20f736c36422c6a3da/test/shared/src/main/scala/zio/test/package.scala#L527

There are also variants of check and checkAll which might suffer from the same problem, see: https://github.com/zio/zio/blob/10fc3699b9c0e36748bc4b20f736c36422c6a3da/test/shared/src/main/scala/zio/test/package.scala#L358
https://github.com/zio/zio/blob/10fc3699b9c0e36748bc4b20f736c36422c6a3da/test/shared/src/main/scala/zio/test/package.scala#L484

**Comment by adamgfraser** [comment]
@frabbit I think that type parameter could be deleted and frankly I don't love the current type signature but we are also limited in our ability to change that by binary compatibility. However, I just checked and it looks like it works fine. You can use it like this:

```scala
      test("returns the list of results") {
        checkAllPar(functionIOGen, listGen, 1) { (f, list) =>
          val res = ZIO.foreach(list)(f)
          assertZIO(res)(isSubtype[List[Int]](anything) && hasSize(equalTo(100)))
        }
      }
```

**Comment by frabbit** [comment]
Thx @adamgfraser, It seems that my issue is related to the type of Generators that require Any as dependencies in combination with assertZIO. 

For example, the following example fails to compile for me:
```scala
test("checkAllPar should work") {
  checkAllPar(Gen.int,  2) { (s1) =>
    assertZIO(ZIO.unit)(equalTo(()))
  }
}
```
The error is quite confusing:
```
no implicit argument of type zio.test.TestConstructor[Nothing, 
  zio.ZIO[?1.OutEnvironment, ?2.OutError, zio.test.TestResult]
] was found for parameter testConstructor of method test in class ZIOSpec

where:    ?1 is an unknown value of type zio.test.CheckConstructor.WithOut[R, zio.ZIO[Any, Nothing, zio.test.TestResult]
  , 
R & Any, Nothing]
          ?2 is an unknown value of type zio.test.CheckConstructor.WithOut[R, zio.ZIO[Any, Nothing, zio.test.TestResult]
  , 
R & Any, Nothing]
.
I found:

    zio.test.TestConstructor.AssertZIOConstructor[R, E, A]

But method AssertZIOConstructor in trait TestConstructorLowPriority1 does not match type zio.test.TestConstructor[Nothing, 
  zio.ZIO[?1.OutEnvironment, ?2.OutError, zio.test.TestResult]
].bloop
```


On the other hand, the following examples work fine:
```scala
test("checkAllPar with assert should work") {
  checkAllPar(Gen.int,  2) { (s1) =>
    assert(())(equalTo(()))
  }
}
```

```scala
test("checkAll should work") {
  checkAll(Gen.int) { (s1) =>
    assertZIO(ZIO.unit)(equalTo(()))
  }
}
```

```scala
test("checkAllPar with Generator requiring Any should work") {
  checkAllPar(Gen.string, 2) { (s1) =>
    assertZIO(ZIO.unit)(equalTo(()))
  }
}
```

**Comment by adamgfraser** [comment]
@frabbit What Scala version are you on? I just ran these tests with all of your examples and they all worked fine with the exception of a warning that the result of the generator was not actually being used.

```scala
import zio._
import zio.test.Assertion._

object ExampleSpec extends ZIOSpecDefault {

  def spec = suite("ExampleSpec")(
    test("checkAllPar should work") {
      checkAllPar(Gen.int, 2) { _ =>
        assertZIO(ZIO.unit)(equalTo(()))
      }
    },
    test("checkAllPar with assert should work") {
      checkAllPar(Gen.int, 2) { _ =>
        assert(())(equalTo(()))
      }
    },
    test("checkAll should work") {
      checkAll(Gen.int) { _ =>
        assertZIO(ZIO.unit)(equalTo(()))
      }
    },
    test("checkAllPar with Generator requiring Any should work") {
      checkAllPar(Gen.string, 2) { _ =>
        assertZIO(ZIO.unit)(equalTo(()))
      }
    }
  )
}
```

**Comment by frabbit** [comment]
I ran them with scala 3.1.0 and 3.1.3. Both fail with the same error. I had to add `zio.test._` to the imports to get your spec compiling:

The full error is this
```
[E] [E1] src/test/scala/ExampleSpec.scala:12:6
[E]      no given instance of type zio.test.TestConstructor[Nothing, 
[E]        zio.ZIO[?1.OutEnvironment, ?2.OutError, zio.test.TestResult]
[E]      ] was found for parameter testConstructor of method test in class ZIOSpec
[E]      
[E]      where:    ?1 is an unknown value of type zio.test.CheckConstructor.WithOut[R, zio.ZIO[Any, Nothing, zio.test.TestResult]
[E]        , 
[E]      R & Any, Nothing]
[E]                ?2 is an unknown value of type zio.test.CheckConstructor.WithOut[R, zio.ZIO[Any, Nothing, zio.test.TestResult]
[E]        , 
[E]      R & Any, Nothing]
[E]      .
[E]      I found:
[E]      
[E]          zio.test.TestConstructor.AssertZIOConstructor[R, Nothing, zio.test.TestResult]
[E]      
[E]      But method AssertZIOConstructor in trait TestConstructorLowPriority1 does not match type zio.test.TestConstructor[Nothing, 
[E]        zio.ZIO[?1.OutEnvironment, ?2.OutError, zio.test.TestResult]
[E]      ].
[E]      L12:     },
[E]                ^
[E] src/test/scala/ExampleSpec.scala: L12 [E1]
```
i compiled with bloop 1.5.2, but i get the same error with sbt 1.6.2.

**Comment by frabbit** [comment]
Removing the first test from your spec makes it compile again.

**Comment by adamgfraser** [comment]
@frabbit Thanks! I can replicate now and just submitted a PR for this. By the way, not sure if this is just a simplified example but with the random generators you have here I would use `check` versus `checkAll`. I would only use `checkAll` if I had a deterministic finite generator like one constructed using `Gen.fromIterable`.

**Comment by frabbit** [comment]
Thx @adamgfraser . I guess it's indeed better in that case to use check. But at least i could help fixing this bug ;).
