### ISSUE TITLE
[ZIO 2] Converting from Java stream to ZStream can easily cause Out Of Memory Exceptions

### ISSUE THREAD

**Issue by andreazube** [zio/zio#7144]
# Summary

Converting a Java stream to a ZStream can lead to a incredibly high memory usage, and even cause an OOM exception on most systems.
Below, you can read more context, a toy example and a possible culprit.

### Context

I have a ZIO1 application that uses streams to process some data. The original stream comes from a third party java API, which I converted to ZStream and then processed further. Each elements weights a few KBs.

Upgrading to ZIO2 caused the application to use a lot more memory to process even just one element from the stream (e.g. with `.take(1)`), and go out of memory.

### Toy example

You should be able to replicate the behavior by executing this little snippet, which uses ZIO 2 

```
object MainApp extends ZIOAppDefault {

  def createHeavyObject() = Array.fill(1_000_000)(scala.util.Random.nextInt()) // ~4MB

  val javaStream: java.util.stream.Stream[Array[Int]] =
    java.util.stream.Stream.iterate(createHeavyObject(), _ => createHeavyObject())

  val zioStream: ZStream[Any, Throwable, Array[Int]] = zio.stream.ZStream.fromJavaStream(javaStream)

  def run = zioStream.take(1000).foreach(_ => ZIO.logInfo("Element processed..."))
}
```

If you run it, you're very likely to get an out of memory exception after a few seconds.

However, this equivalent snippet in ZIO1 works fine

```
object Main extends zio.App {

  def createHeavyObject() = Array.fill(1_000_000)(scala.util.Random.nextInt()) // ~4MB

  val javaStream: java.util.stream.Stream[Array[Int]] =
    java.util.stream.Stream.iterate(createHeavyObject(), _ => createHeavyObject())

  val zioStream: ZStream[Any, Throwable, Array[Int]] = zio.stream.ZStream.fromJavaStream(javaStream)

  val program = zioStream.take(1000).foreach(_ => ZIO.effect(println("Element processed...")))

  override def run(args: List[String]) = program.exitCode
}
```
Of course, this is a very simplified and exaggerated example, but as I mentioned before a similar behavior can be observed with more reasonable programs.

Furthermore, this third and last ZIO 2 snippet works fine
```
ZStream.iterate(createHeavyObject())(_ => createHeavyObject()).take(1000).foreach(_ =>
    ZIO.logInfo("Element processed...")
  ) 
```
, so it looks like a "Native" ZStream can handle things that one originated from a java stream cannot. 

### Possible culprit

I tried to investigate a bit on my own, and I came to the conclusion that at least part of the issue is with the new signature of `ZStream.fromIterator`, one of the methods called by `ZStream.fromJavaStream`.
In ZIO1, the signature looks like this

`def fromIterator[A](iterator: => Iterator[A], maxChunkSize: Int = 1): ZStream[Any, Throwable, A]`

while the ZIO2 signature is currently

```
def fromIterator[A](iterator: => Iterator[A], maxChunkSize: => Int = DefaultChunkSize)(implicit
    trace: Trace
  ): ZStream[Any, Throwable, A]
```

... and `final val DefaultChunkSize = 4096`

If I'm correct, then this at least partly explains the issue I've been facing. In the toy example, ZIO would attempt to load about 4096 * ~4MB = ~16GB of data in memory from the get go. 

I tried replicating the `ZStream.fromJavaStream` function on my own, changing only the `maxChunkSize` in the `fromIterator ` call, and that did seem to solve the memory issue.

### Questions

Is this more aggressive chunking strategy intended? 
If it is, then I think it should be mentioned in the [migration guide ](https://zio.dev/guides/migrate/zio-2.x-migration-guide#zio-streams), because it could dramatically change the behavior of existing applications (like it did for mine).

It'd also be great to be able to select the chunk size from the beginning, as right now it doesn't seem to be possible (or at least I wasn't able to find out how).

Thanks for reading, and have a great day :)

**Comment by vigoo** [comment]
I think we should have a `chunkSize` parameter for all these `fromXyz` methods
