### ISSUE TITLE
[2.0] zio app error - broken link

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7150]
see screenshot:
![grafik](https://user-images.githubusercontent.com/100349/181917996-f3ab374c-1a45-483b-9cf4-c95890627e85.png)

https://zio.dev/next/datatypes/contextual/ is a 404. it should either contain the advertised content or redirect to the right place

**Comment by domdorn** [comment]
@khajavi could u maybe add a redirect? everyone running 2.0.0 will not have the new link till they update.

**Comment by khajavi** [comment]
@domdorn I was thinking of that, before. There is a redirect plugin for docusaurus that can help us to perform these redirections. If you are willing to contribute, I appreciate it. Otherwise, I'll get to it as soon as I have a chance.
