### ISSUE TITLE
[2.0] logSpan is not added to log in same way as annotations

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7153]
annotations are key (string) value (string) pairs. 
When using the `SLF4J` logger that is provided by `zio-logging`, `zio.LogAnnotation`s are correctly passed as fields, so they can be used e.g. with the `Logstash-Json-Encoder` to properly translate to ElasticSearch/Kibana/Logback.

For some reason, this behaviour does not work out of the box for `logSpan`s. In the case of SLF4J, I have to explicitely add them to the LogFormat like this:

```scala
  private val logger = zio.Runtime.removeDefaultLoggers >>> SLF4J.slf4j(LogLevel.All, LogFormat.line |-| LogFormat.spans)
```

with example code like this: 
```scala
  def zioEffect[E <: Throwable](f: ZIO[CorrelationId, E, Route])(
    implicit r: zio.Runtime[Any]): Route = Route {
    Directives.extractRequest { req =>
      val e = for {
        _ <- ZIO.unit
        c          = CorrelationId.random()
        baseEffect = ZIO.logDebug(s"Processing Req. ${req.method} ${req.uri}") *> f

        annotations = ZIO.logAnnotate(
          zio.LogAnnotation("correlation-id", c.value.toString),
          zio.LogAnnotation("request-uri", req.uri.toString()),
          zio.LogAnnotation("request-method", req.method.value)
        )

        annotated = annotations(baseEffect).logSpan("request-time")

        provided = annotated.provide(ZLayer.succeed(c))
        running <- provided
      } yield running

      StandardRoute { ctx =>
        val future: Future[RouteResult] =
          Unsafe.unsafe(implicit u => r.unsafe.runToFuture(e)).flatMap(v => v(ctx))(ctx.executionContext)
        future
      }
    }
  }
```

a request that goes through this code properly puts the annotations "correlation-id", "request-uri" and "request-method" into the corresponding json fields, however "request-time" is only available as a text-property in the message, e.g.

```json
{"@timestamp":"2022-07-31T00:13:49.533+02:00","@version":"1","message":"Processing Req. HttpMethod(GET) http://localhost:8160/api/v1/limits/dummy request-time=1ms","logger_name":"zio-slf4j-logger","thread_name":"ZScheduler-Worker-0","level":"DEBUG","level_value":10000,"request-method":"GET","request-uri":"http://localhost:8160/api/v1/limits/dummy","correlation-id":"aeda7e48-d641-4fee-b33e-9b2463380c5b","user-id":"Dominik.Dorn@acme.com","application":"acme-limit-service","stage":"LOCAL"}
```

As a User, I want to have logSpans also to be handled like Annotations so that they go to the corresponding fields when translating to json and I'm able to use the capabilities that are provided by my log-environment (e.g. Kibana). E.g. when every `logSpan` is put into a own field, I can create queries like "show me all logs from requests with url xxx and request-time > yyy"

**Comment by adamgfraser** [comment]
I think this has to be addressed at the `zio-logging` level. In ZIO we can capture the log spans which it seems like we are doing but it is up to the logger implementation what to do with them.
