### ISSUE TITLE
[2.0] Not enough context in debug message coming form ZIO internals

### ISSUE THREAD

**Issue by artur-jablonski** [zio/zio#7156]
With logging set to `DEBUG` level I suddenly see lines like this one logged:

```
timestamp=2022-08-01T10:55:06.541484778+02 level=DEBUG thread=zio-fiber-271 message="Fiber zio-fiber-271 did not handle an error"
```

This would be more useful if there was more context to know what error is not handled and where did it originate from. 

I see this log originates from `FiberRuntime.scala`:

```scala
 def reportExitValue(v: Exit[E, A])(implicit unsafe: Unsafe): Unit = v match {
      case Exit.Failure(cause) =>
        try {
          if (!cause.isInterruptedOnly) {
            log(
              () => s"Fiber ${fiberId.threadName} did not handle an error",
              cause,
              getFiberRef(FiberRef.unhandledErrorLogLevel),
              id.location
            )
          }
[...]
```

and it looks like this captures `Cause`, but then it's not logged...

**Comment by artur-jablonski** [comment]
I checked in debug session that `Cause` in this particular case is of type

`final case class Then[+E](left: Cause[E], right: Cause[E]) extends Cause[E]`

if that matters

**Comment by adamgfraser** [comment]
@artur-jablonski Hi! Could you create a small reproducer? I tried to do so with the below:

```scala
package zio

object Example extends ZIOAppDefault {

  val logger =
    ZLogger.default.map(println)

  override val bootstrap: ZLayer[ZIOAppArgs with Scope,Any,Any] =
    Runtime.removeDefaultLoggers >>> Runtime.addLogger(logger)

  val run =
    for {
      _ <- ZIO.fail("fail").forkDaemon
      _ <- ZIO.sleep(1.second)
    } yield ()
}
```

And I get a log output of:

```
[info] timestamp=2022-08-01T20:24:46.463927Z level=DEBUG thread=#zio-fiber-7 message="Fiber zio-fiber-7 did not handle an error" cause="Exception in thread "zio-fiber-7" java.lang.String: fail
[info]  at zio.Example.run(Example.scala:13)" location=zio.Example.run file=Example.scala line=13
```

This includes the `Cause` and the trace, which I think is the expected output.

Are you using a different logger that does not do anything with the `Cause`? As you can see from the code in `reportExitValue` above the implementation passes `cause` into `log` so then it is the responsibility of the `ZLogger` implementation to do something with that `Cause`, which `Logger.default` does. So I think the problem may be that the `ZLogger` implementation you are using does not do that.

**Comment by artur-jablonski** [comment]
I am using the console logger from `zio-logging` `v2.0.1` (latest release). With this configuration and your snippet I can see the bahviour I described:

```scala
import zio.logging.slf4j.bridge.Slf4jBridge
import zio.logging.{LogFormat, console}

override val bootstrap: ZLayer[ZIOAppArgs with Scope, Any, Any] =
    Runtime.removeDefaultLoggers >>> console(
      LogFormat.colored,
      LogLevel.Debug,
    ) ++ Slf4jBridge.initialize

```

perhaps I missed something in `zio-logging` documentation or perhaps it's a bug/lack of feature on their side :thinking:

**Comment by adamgfraser** [comment]
@artur-jablonski Will take a look at that implementation.

**Comment by adamgfraser** [comment]
Yes, the underlying issue is that `LogFormat.default` and `LogFormat.colored` do not include the `Cause`. I opened zio/zio-logging#487 for this.
