### ISSUE TITLE
[2.0] scalafix: remove usages of zio.ZEnv

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7157]
remove import completly
```scala
import zio.ZEnv
```

replace `ZIO.runtime[ZEnv]` with `ZIO.runtime[Any]`
e.g.
```scala
r <- ZIO.runtime[ZEnv]
```
with
```scala
r <- ZIO.runtime[Any]
```

replace `ZEnv with` with the empty String

**Comment by adamgfraser** [comment]
There are some limits to how many changes we can make with the automated migration tool.

@swoogles Do you think this is feasible?

**Comment by domdorn** [comment]
its no big deal if that is not possible, I'm just reporting the things that are not migrated when migrating service by service now.

**Comment by adamgfraser** [comment]
Totally. Just to be clear the expectation is not that the automated tool will handle 100% of your migration but that it will handle ~90% of it and make it easy to do the rest. Clearly on the margin we would like to do more but there are some technical limitations that prevent us from doing everything.
