### ISSUE TITLE
Deadlock/livelock with http4s Blaze after updating to ZIO 2

### ISSUE THREAD

**Issue by dhpiggott** [zio/zio#7158]
I migrated a couple of services to ZIO 2 over the last few of weeks and ran into a strange issue along the way. We have one service left to migrate to ZIO 2, but it receives high traffic volumes and performance is essential for it, so we want to understand the issues we saw with the initial pilot conversions.

Both of the services we've migrated so far (both receive relatively low traffic volumes) have end to end tests which are written as a ZIO Test suite, with up to around 100 test cases, which each involve one or more HTTP calls from the machine the tests are running on to the deployed service. The tests used http4s with Blaze as the client. What I found after updating the services and tests to ZIO 2 was that most test runs would make good progress through 99% of the tests, but would stall with one or two tests outstanding. I speculatively swapped out Blaze for Ember in those code bases and the issue effectively went away, allowing us to complete the migration of those services to ZIO 2.

To better understand the issue I've created a smaller reproducible example and pushed it to https://github.com/dhpiggott/zio-http4s. It has two modules - one using ZIO 1, and one using ZIO 2. Both modules spin up http4s Blaze servers and clients and use the clients to make 10,000 requests with a parallelism of 1,000. The ZIO 1 version completes fine each time, while the ZIO 2 version hangs with a handful of requests outstanding on virtually every run.

Having read https://github.com/zio/zio/issues/7074 I wanted to rule out auto-blocking as the cause, so the ZIO 2 version applies a patch using reflection to `ZScheduler.blockingLocations` setting it to a custom set that always returns false for `contains` and returns itself when elements are added. This doesn't appear to have helped. I also tried setting the executor to a fixed size thread pool (though I've not pushed that) but continued seeing the issue.

**Comment by davidlar** [comment]
I have a similar problem and I suspect it's the same bug. 
In my case I use skunk via cats-interop and the tests usually hangs in the end of each test run.
If I run the tests sequentially it works, though.
On ZIO 1 there was no problem at all.

I haven't managed to create a small reproducer yet, so I'm hoping that the bug could be fixed by using your reproducer!  ;-)

**Comment by adamgfraser** [comment]
Would be great if we could minimize this further!

**Comment by davidlar** [comment]
Found my issue (mentioned above) now and it's not the same as this, so I will file a new issue...

Sorry for hijacking this case! :smiley:

**Comment by dhpiggott** [comment]
I know there've been a few perf improvements and resource safety/memory leak/GC type issues found and fixed in ZIO (and maybe some in Cats Effect/Cats Effect Interop too) in the last couple of months so thought it would be a good idea to check if this issue still exists in newer versions.

I updated the minimal reproducible example I shared above to Scala 3.2.1, ZIO 2.0.6, and ZIO Interop Cats 23.0.0.1 (https://github.com/dhpiggott/zio-http4s/commit/3767dabdf5e0c66056236b90de9e87c5142405ae). I didn't narrow it down to which, but one of those has resolved this - I was able to run `zio-2/run` multiple times and have all 10,000 requests promptly execute!

**Comment by adamgfraser** [comment]
Great! Thanks for the update!

**Comment by dhpiggott** [comment]
I nearly forgot to test that it's also good with the hack that disabled auto-blocking removed. https://github.com/dhpiggott/zio-http4s/commit/c8a2e13fa386b7e7bd82c111b747c088bfc04825 removed that hack. A few more runs of `zio-2/run` confirmed it's all good.

**Comment by adamgfraser** [comment]
👍
