### ISSUE TITLE
[2.0] document scoping changes of fibers when constructing layers

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7168]
apparently there is a difference in scoping when construcing layers in zio 2.0

the following code was keeping the forked fiber alive even after the layer construction finished in zio 1

```scala
  val live: ZLayer[Clock with Logging with Has[KeySetProvider], Nothing, Has[VioptAuthenticator]] =
    (for {
      _ <- ZIO.unit
      // unfortunately unsafeGet on ZRef is private so we need to use a AtomicReference here
      keyRef = new AtomicReference[JWKSet](new JWKSet())
      initialFetch   <- Promise.make[Nothing, Unit]
      keySetProvider <- ZIO.service[KeySetProvider]
      reloadKeys = (for {
        response <- keySetProvider
          .getKeySet()
          .tap(res => logging.log.debug(s"successfully fetched jwt keyset with ids: $res"))
          .tapError(err => logging.log.error(s"fetching jwk keyset failed: $err ", Cause.fail(err)))
        _ <- ZIO.effect(keyRef.set(response))
      } yield response).timeout(10.seconds).some.ensuring(initialFetch.succeed(()))

      _ <- reloadKeys
        .retry(Schedule.exponential(500.millis))
        .timeout(30.seconds)
        .catchAll {
          case Some(error) => logging.log.error(s"Error fetching JWK key set: ${error.getMessage}", Cause.fail(error))
          case None        => logging.log.error("Failed to fetch JWK key set due to timeout")
        }
        .repeat(Schedule.spaced(5.minutes))
        .fork
      _ <- initialFetch.await
    } yield VioptAuthenticatorLive(() => keyRef.get)).toLayer
```
    
while in zio 2, we have to do a `forkDaemon` to keep the reloading fiber alive after the layer is constructed
 
```scala
      val live: ZLayer[KeySetProvider, Nothing, VioptAuthenticator] = ZLayer.fromZIO(
    for {
      _ <- ZIO.unit
      // unfortunately unsafeGet on ZRef is private so we need to use a AtomicReference here
      keyRef = new AtomicReference[JWKSet](new JWKSet())
      initialFetch   <- Promise.make[Nothing, Unit]
      keySetProvider <- ZIO.service[KeySetProvider]
      reloadKeys = (for {
        response <- keySetProvider
          .getKeySet()
          .tapBoth(
            err => ZIO.logErrorCause(s"fetching jwk keyset failed: $err ", Cause.fail(err)),
            res => ZIO.logDebug(s"successfully fetched jwt keyset with ids: $res"))
        _ <- ZIO.attempt(keyRef.set(response))
      } yield response).timeout(10.seconds).some.ensuring(initialFetch.succeed(()))

      _ <- reloadKeys
        .retry(Schedule.exponential(500.millis))
        .timeout(30.seconds)
        .catchAll {
          case Some(error) => ZIO.logErrorCause(s"Error fetching JWK key set: ${error.getMessage}", Cause.fail(error))
          case None        => ZIO.logError("Failed to fetch JWK key set due to timeout")
        }
        .repeat(Schedule.spaced(5.minutes))
        .forkDaemon
      _ <- initialFetch.await
    } yield VioptAuthenticatorLive(() => keyRef.get)
  )
```
  
this screenshot shows our zio 1 branch (master) on the left and the required code for zio 2 on the right
![grafik](https://user-images.githubusercontent.com/100349/182706734-c4ae7da4-35fb-4464-83ea-6a30afce0433.png)

apparently in zio 2, a forked fiber gets interrupted once the layer construction completes, whereas in zio 1 the fiber was kept alive. That's why we had to change this to `.forkDaemon`. 

While I'm wondering why it ever was working with just a `fork` in zio 1, it might be good if this could be added somewhere in the migration guide, as it took me half a day to find this bug. 

I'm not looking for/expecting a solution, workaround or explaination. Please just decide if you want to put this into the documentation or not.

**Comment by adamgfraser** [comment]
@domdorn Thanks for reporting!

Yes on both ZIO 1 and ZIO 2 you should either use `forkManaged` / `forkScoped` to tie the life of a background fiber created in a layer to the life of a layer or `forkDaemon` to fork it as a daemon fiber. For example the below code in ZIO 1 also terminates the background fiber early.

There may be something else that is changing the lifetime of the particular fiber that this is forked in but I think it is difficult to document it as a change when the behavior is not defined in ZIO 1.

@khajavi What I would suggest we do is just focus on the "right" behavior of forking background processes like this using `forkScoped` or `forkDaemon`. There is also `forkSchedule` for this. This way your background fibers will have the right behavior without you having to rely on the lifetime of the current fiber, which you may not even have control over.

```scala
object Example extends App {

  val layer =
    ZLayer.fromEffect {
      for {
        _ <- console.putStrLn("Still going").repeat(Schedule.fixed(1.second)).fork
      } yield 42
    }

  override def run(args: List[String]): URIO[ZEnv, ExitCode] =
    for {
      fiber <- ZIO.service[Int].provideLayer(layer).fork
      _     <- ZIO.sleep(10.seconds)
    } yield ExitCode.success
}
```
