### ISSUE TITLE
ZIO helpers for tests

### ISSUE THREAD

**Issue by ratoshniuk** [zio/zio#717]
Can we provide some helpers to assert left or right branches?

```scala
val eff : ZIO[Any, Failure, Int] = ???
```
And imagine we have some test scope, where we need to perform assertion for specific step

```scala
eff.assertValue(_ == 1)
eff.assertFailure(f == ADTValueOfFailure)
```

It could be implicit class for testz and be imported like follow:

```scala
import testz.zio._
```

**Comment by ratoshniuk** [comment]
Or i should address this issue to testz project?

**Comment by NeQuissimus** [comment]
I can probably at least send a PR for what I was thinking. Will need polishing. I hope to get around to it on the weekend

**Comment by ratoshniuk** [comment]
@NeQuissimus looks great, thank you!
