### ISSUE TITLE
Fiber zio-fiber-12 did not handle an error

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7173]
I'm seeing the following error logged in a service we recently migrated to zio 2:
```json
{"@timestamp":"2022-08-02T02:53:55.646+01:00","@version":"1","message":"Fiber zio-fiber-12 did not handle an error ","logger_name":"zio-slf4j-logger","thread_name":"zio-default-blocking-1","level":"DEBUG","level_value":10000,"application":"viopt-limit-service","stage":"LOCAL"}
```

I'm missing a trace-info here.. basically some info into which code I have to look to fix the problem.. fiber-12 could be anything. 

Is there a way to enable this?

**Comment by adamgfraser** [comment]
@domdorn Can you try on the latest ZIO snapshot?

**Comment by adamgfraser** [comment]
Going to close this as I believe this has been fixed by recent improvements to tracing but feel free to open again with a small reproducer if you are still having issues.
