### ISSUE TITLE
Add Ability to Accumulate arbitrary value in `ZSink.fromFile`

### ISSUE THREAD

**Issue by bgolding355** [zio/zio#7197]
# The Problem
There is no easy way to accumulate a value while streaming information to a file in `ZStreams`.

Here is the use case. Lets say I have an API that successfully returns a `String` 80% of the time, but fails the other 20% of the time. My goal is to use this API to fetch a large number of strings, print them to a file, then afterwords know how many of the calls succeeded vs failed. Since this API is so unreliable, I don't want the stream to fail over a few bad calls.

In this example I have a `ZStream`
```
val stringsFromApiStream : ZStream[SomeContext, Nothing, Option[String]] = ???
```

I want to construct a `ZSink`
```
case class StreamResult(successCount: Int, failureCount: Int)
val zsinkThatWillYieldSuccessAndFailureCount:  ZSink[Blocking, Throwable, Byte, Byte, StreamResult] = ???
```

Such that I can do:
```
stringsFromApiStream.run(zsinkThatWillYieldSuccessAndFailureCount)
```

And get a `ZIO[Blocking with SomeContext, Throwable, StreamResult]`

# Current workarounds
1. Use some special code. In this example I could print the string if it is a `Some` or the literal character `None` if the call fails, then construct a second ZStream to strip out the `None`'s and count how many of them there are
2. `tap` the stream, and provide a function with changes some mutable value then feed that to the stream. In this case I could do something like
```
var successCount: Int = 0
var failureCount: Int = 0

val streamWithTap = stringsFromApiStream.tap {
   case Some(_) => 
      successCount++
      ZIO.succeed(())
  case None =>
      failureCount++
     ZIO.succeed(())
}
```

But both of these solutions are terrible.

I would add that there is probably a clever tail recursive solution to this that uses continuations but I couldn't figure out how to implement it.

# A proposed solution
Implement a function:
```
// In ZSink
def fromFileAccumulate[A,B](
    path: => Path,
    position: Long = 0L,
    options: Set[OpenOption] = Set(WRITE, TRUNCATE_EXISTING, CREATE)
)(
accumulator: A => B
)(
combine: (B,B) => B
) : ZSink[Blocking, Throwable, Byte, Byte, Option[B]] = ???
```

Where the sink will yield `Some(B)` if the stream has elements and `None` if the stream is empty.

**Comment by adamgfraser** [comment]
This feels pretty special purpose. I think a more composable solution would just be combining two sinks that deal with the concerns of writing to the files and counting various types of results. This could be accomplished with:

```scala
stream.run(sinkThatWritesToFail &> sinkThatCountsErrorsAndSuccesses)
```

You could also use `tapSink` to write the contents of the stream to a file and then use normal stream operators like `scan` or `fold` to count successes and failures if you wanted to stay within the streaming context.

**Comment by bgolding355** [comment]
@adamgfraser thanks, that is a much better solution then what I found. I did not know that it was possible to compose `ZSink`s or `tap` them.

One thing I would note is that neither the `tapSink` nor the `&>` operator are documented in https://zio.dev/version-1.x/datatypes/stream/zsink/. It would be useful to document these features

> This feels pretty special purpose. I think a more composable solution would just be combining two sinks that deal with the concerns of writing to the files and counting various types of results. This could be accomplished with:
> 
> ```scala
> stream.run(sinkThatWritesToFail &> sinkThatCountsErrorsAndSuccesses)
> ```
> 
> You could also use `tapSink` to write the contents of the stream to a file and then use normal stream operators like `scan` or `fold` to count successes and failures if you wanted to stay within the streaming context.

**Comment by adamgfraser** [comment]
@khajavi See above suggestion regarding documentation.
