### ISSUE TITLE
ZChannel is missing contramap operations for input errors

### ISSUE THREAD

**Issue by pvgoran** [zio/zio#7202]
`ZChannel` has `contramapIn`/`contramapInZIO` for mapping input elements and `contramap`/`contramapZIO` for mapping input end result, but no way to transform input errors. Because of this, I can't satisfy type restrictions on `InErr`, see https://github.com/zio/zio/discussions/7201 .

**Comment by pvgoran** [comment]
Possible implementations (in the form of implicit classes):

```scala
  implicit class ZChannelWithContramapErr[-Env, -InErr, -InElem, -InDone, +OutErr, +OutElem, +OutDone](
    channel : ZChannel[Env, InErr, InElem, InDone, OutErr, OutElem, OutDone]
  )
  {
    @inline def contramapErr[InErr0](f : InErr0 => InErr) : ZChannel[Env, InErr0, InElem, InDone, OutErr, OutElem, OutDone] =
    {
      lazy val reader: ZChannel[Any, InErr0, InElem, InDone, InErr, InElem, InDone] =
        ZChannel.readWith(
          (in: InElem) => ZChannel.write(in) *> reader,
          (err: InErr0) => ZChannel.fail(f(err)),
          (done: InDone) => ZChannel.succeedNow(done),
        )

      reader >>> channel
    }
  }

  implicit class ZChannelWithContramapErrZIO[Env, -InErr, -InElem, -InDone, +OutErr, +OutElem, +OutDone](
    channel : ZChannel[Env, InErr, InElem, InDone, OutErr, OutElem, OutDone]
  )
  {
    @inline def contramapErrZIO[InErr0, Env1 <: Env](f : InErr0 => ZIO[Env, InErr, InErr]) : ZChannel[Env1, InErr0, InElem, InDone, OutErr, OutElem, OutDone] =
    {
      lazy val reader: ZChannel[Env1, InErr0, InElem, InDone, InErr, InElem, InDone] =
        ZChannel.readWith(
          (in: InElem) => ZChannel.write(in) *> reader,
          (err: InErr0) => ZChannel.fromZIO(f(err).flatMap(ZIO.fail)),
          (done: InDone) => ZChannel.succeedNow(done),
        )

      reader >>> channel
    }
  }
```

Did I miss anything?

**Comment by pvgoran** [comment]
One particular concern regarding the implementation above (and the similar implementations of other contramap operations): The documentation for `ZStream.run` says "The channel must not read any input or write any output". The channels produced by contramap operations (including my implementations above) are build using `ZChannel.readWith`, which suggests that they read their input. Do these channels meet the restriction cited above regarding "not reading any input"? That is, can I call `run` for them??

**Comment by vigoo** [comment]
These are only missing by accident, I think. Your implementation looks good to me, would you like to add it in a PR?

The comment regarding `ZStream.run` is true, channels with input (for example those created by these functions) cannot be executed without first "plugging in" something in their inputs.

**Comment by pvgoran** [comment]
Thank you!
(Even though I determined that these operations are irrelevant for my purposes. :) )
