### ISSUE TITLE
2.0 metrics: align metric names with Micrometer.io names

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7206]
to increase interoperability, we should align our metrics names with the ones that are in use by https://micrometer.io/docs/ref/jvm
That way, we can leverage existing dashboards already in use in the industry and also make lives easier for Ops running already non-zio apps in a mixed environment. 
This way, we can add an additional bullet point to the reasons why people should use zio, e.g.
 - Plugs seamlessly into your existing metrics collection solution

Small sample of changes required:

| zio-name | micrometer name | jmx-name | note |
| ---- | ---- | --- | --- | 
| jvm_classes_loaded | jvm.classes.loaded | classLoadingMXBean.getLoadedClassCount | |
| jvm_classes_loaded_total | jvm.classes.loaded.total | classLoadingMXBean.getTotalLoadedClassCount | |
| jvm_classes_unloaded_total | jvm.classes.unloaded | classLoadingMXBean.getUnloadedClassCount | the "total" here should go away |
| ... | ... |

(see https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ClassLoaderMetrics.java ) 
We should do that with all the instrumentations found here: 
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm

With this, people will be able to use existing dashboards, like
https://grafana.com/grafana/dashboards/4701-jvm-micrometer/

if wanted, I could try to make a PR for this.
//cc @vigoo @atooni

**Comment by domdorn** [comment]
I've noticed that the `.` gets converted to underscore. So in the table above, we would just need to adjust the `jvm_classes_unloaded_total` to `jvm_classes_unloaded`. Other metrics differ more (e.g. switching order of words)

**Comment by atooni** [comment]
@domdorn I am open to the suggestion.  This having said, the names are coming from the Prometheus jvm instrumentation and we have chosen them to maintain compatibility for users who have been using that.

Changing the names would mean that current users would also have to change their dashboards.

Secondly, the jvm metrics are a function of ZIO core, so if we would change the names it would have to be over there. 

@vigoo perhaps some way to select either the Prometheus or micrometer names? Like injecting a name provider into the instrumentation ?

**Comment by domdorn** [comment]
hmm.. ok, I didn't knew that Prometheus itself also has a java metrics lib. I see that `jvm_classes_unloaded_total` is spelled that way in there (although I think its a mistranslation from the JMX Bean) https://github.com/prometheus/client_java/blob/e68daf23336eb5de7856df406eb1d497f51ad3be/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/ClassLoadingExports.java#L35 

If we would proceed with renaming, I could provide a SED or AWK script for people wishing to translate their dashboards.
Alternatively, we could also extract the names into a trait that gets provided by the config to the corresponding metric. 

My goal is/was to reach the biggest possible audience. As we have limited resources in providing ready2use dashboards, my thinking was to adopt the naming of an already established project that has ready2use dashboards.

**Comment by vigoo** [comment]
Hi, yes I explicitly used the Prometheus names because wanted keep compatibility when migrating to zmx/zio2 from the prometheus java library. I understand micrometer uses different names but I guess there are even more conventions than these two, so I think if we should rather think about how to provide different "naming styles" than select an arbitrary other one to follow. 

(I am definitely a little biased because at every production environment I have seen it was using the prometheus jvm metrics and never seen the micrometer one but I don't see why that particular one would reach the biggest possible audience. Downloadable dashboards exist for the prometheus naming convention too (for example https://grafana.com/grafana/dashboards/3066-jvm/)

**Comment by 987Nabil** [comment]
If I am not mistaken, micrometer is the default for Spring. I know in our company both, prometheus and micrometer, are flying around.

Anyway, I had the same thoughts like @vigoo and think this is the right way to go. And maybe having micrometer and prometheus predefined makes sense.

**Comment by domdorn** [comment]
@vigoo I just tried the dashboard you linked (its very old, last updated in 2017 with only one revision): its very limited. 
Then I tried this one: https://grafana.com/grafana/dashboards/8878-jvm-dashboard-for-prometheus-operator/?tab=revisions .. its more advanced, but is based on kubernetes concepts (namespace/service/pod) 
![grafik](https://user-images.githubusercontent.com/100349/184893900-0f0600e6-a224-45f6-98ce-b6cdb3ee91ca.png)

I couldn't find a existing dashboard with the pure prometheus naming that is compatible with how we export metrics from zio. 
What I want is a dashboard that is at least comparable in features/comfort with this one: https://grafana.com/grafana/dashboards/6756-spring-boot-statistics/ or this one: https://grafana.com/grafana/dashboards/4701-jvm-micrometer/ 

One way to approach this is to change our names to match those that are used by micrometer.
Another would be to copy one of those dashboards and adjust it for our names.

Another question is if monitoring is something that should be easily available for the community or is a special service that Ziverge provides to paying customers. I would prefer the first. If we're on the same page on this, we should provide either a competive dashboard or allow using existing ones that are already fairly advanced.

**Comment by domdorn** [comment]
I'll try to migrate one from the micrometer dashboards now.. will post it once I have something.

**Comment by domdorn** [comment]
ok, I have a first version based on rev 9 of https://grafana.com/grafana/dashboards/4701-jvm-micrometer/?tab=revisions 

screenshots here:
![grafik](https://user-images.githubusercontent.com/100349/184982414-7a7947e2-4122-427f-ba33-238514ee3df3.png)
![grafik](https://user-images.githubusercontent.com/100349/184982481-57593e8d-4c5e-498b-8d52-95f74fe0f80d.png)
![grafik](https://user-images.githubusercontent.com/100349/184982647-c59b9966-ec9e-4f4d-a5d6-13266cc564b0.png)

It still misses quite a few things to be fully compatible with https://grafana.com/api/dashboards/4701/images/5594/image 

One TODO I have is this one:
```
# TODO
# include id's and area to jvm_memory_used_bytes (micrometer) / jvm_memory_bytes_used (zio)
# see https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java
# zio/metrics/jvm/MemoryPools.scala:58
```
This would add id's of the pools as additional tags. They can then be selected in the dropdowns on the top of the page. 
( see https://stackoverflow.com/a/1262474 ) 

I'm currently missing the following metrics that are also used in the dashboard:
```
# process_memory_swap_bytes
# system_cpu_usage (? docker?)
# process_cpu_usage (? docker?)
# process_uptime_seconds
#
# system_load_average_1m
# system_cpu_count
# process_threads
# jvm_gc_pause_seconds_max
# jvm_gc_memory_allocated_bytes_total
# jvm_gc_memory_promoted_bytes_total
```


I'm currently wondering if we should try to patch the current metrics or it would be better to create additional metrics based on the micrometer ones and provide them as zio-metrics-micrometer lib/jar. Then people could just add that one instead of the `DefaultJvmMetrics.live` to their bootstrap. WDYT? 

Here is the current version of the dashboard: [jvm-zio_rev1.json.txt](https://github.com/zio/zio/files/9354661/jvm-zio_rev1.json.txt)

**Comment by domdorn** [comment]
I'm creating a small lib that allows bridging metrics collected by micrometer to ZIOs metrics and will talk with the customer about if/how this can be opensourced. Closing for now.

**Comment by adamgfraser** [comment]
@domdorn Awesome! Look forward to seeing it!

**Comment by domdorn** [comment]
@adamgfraser this is how its looking so far. 
I'm using the micrometer metrics for basic jvm, unix processes, http.server.request (zio's timer does not export all necessary timeseries) and hikaricp 
I'm using the zio-metrics for the zio-runtime-metrics (fibers).. I'm not yet happy with the fibers dashboard. 

OPS: Service Status is little distorted, cause I had to scale it in the browser.

![grafik](https://user-images.githubusercontent.com/100349/191284866-b14644a1-3566-4546-a057-e6f1c99ce299.png)
![grafik](https://user-images.githubusercontent.com/100349/191285175-51e29f3f-435d-42f0-b6c1-5916807161c1.png)
![grafik](https://user-images.githubusercontent.com/100349/191285406-d9e54971-05f8-49e9-92b0-531191938c74.png)
![grafik](https://user-images.githubusercontent.com/100349/191285538-e48c1f3e-a819-4ef1-a098-aec6ee48279c.png)
![grafik](https://user-images.githubusercontent.com/100349/191286974-f35160ca-1b39-4a04-9531-7a3b59ac90f8.png)

**Comment by adamgfraser** [comment]
@domdorn Wow that looks amazing! Copying @vigoo and @atooni.
