### ISSUE TITLE
The `ZIOAppArgs` service doesn't work with `ZIO#provide`

### ISSUE THREAD

**Issue by khajavi** [zio/zio#7215]
The following code doesn't work with `ZIO#provide` but works with `ZIO#provideLayer`:

```scala
import zio._

case class AppConfig(poolSize: Int)

object AppConfig {
  def poolSize: ZIO[AppConfig, Nothing, Int] =
    ZIO.serviceWith[AppConfig](_.poolSize)

  val layer: ZLayer[ZIOAppArgs, Nothing, AppConfig] =
    ZLayer {
      ZIOAppArgs.getArgs
        .map(_.headOption.map(_.toInt).getOrElse(8))
        .map(poolSize => AppConfig(poolSize))
    }
}

object MainApp extends ZIOAppDefault {
  val myApp: ZIO[AppConfig, Nothing, Unit] =
    for {
      poolSize <- AppConfig.poolSize
      _        <- ZIO.debug(s"Application started $poolSize pool size.")
    } yield ()

  def run = myApp.provide(AppConfig.layer)
}
```

Compiler output:

```
[error] ──── ZLAYER ERROR ────────────────────────────────────────────────────
[error] 
[error]  Please provide a layer for the following type:
[error] 
[error]    Required by AppConfig.layer
[error]    1. zio.ZIOAppArgs
[error]       
[error] ──────────────────────────────────────────────────────────────────────
[error] 
[error]   def run = myApp.provide(AppConfig.layer)
[error]                          ^
[error] one error found
```

**Comment by adamgfraser** [comment]
@khajavi You need to do `provideSome[ZIOAppArgs]`.

**Comment by khajavi** [comment]
@adamgfraser 
Yes, that works. But I expect that `ZIO#provide` and `ZIO#provideLayer` have the same functionality, except the fact that the first one does metaprogramming and the other requires manual layer construction. If it is an expected behavior it also shouldn't work for `ZIO#provideLayer`.

**Comment by adamgfraser** [comment]
@khajavi I don't think that is the correct expectation. If you look at the signature of `provideLayer` it provides a layer which may have some dependencies of its own and returns a new workflow that has the dependencies of the provided layer. In contrast `provide` provides a collection of layers and returns a new workflow that has no dependencies at all. So this is expected behavior.

**Comment by khajavi** [comment]
Thank you for the clarification.
