### ISSUE TITLE
Implement `Gauge#increment` and `Gauge#decrement`

### ISSUE THREAD

**Issue by frekw** [zio/zio#7217]
Ran across this when [trying to implement an in-flight requests metric for zio-http](https://github.com/dream11/zio-http/pull/1394).

There's currently no way to increment or decrement a gauge based on its current value. This makes metrics like these much harder to implement since I both need to maintain the state myself via a `Ref` or a `Ref.Synchronized` and have to trade off between correctness and performance, see [this comment](https://github.com/dream11/zio-http/pull/1394#discussion_r949357738).

Had a quick look to see if I could submit a PR instead but it wasn't immediately obvious to me how I'd go about doing so.

**Comment by adamgfraser** [comment]
This could potentially just be represented using two counters, for example for started requests and completed requests.

**Comment by frekw** [comment]
Just for context;

It's true that might be a workaround in some scenarios.

However, for me, I have a reliability team at `$WORK` that has a policy that will not allow me to deploy HTTP (or gRPC for that matter) applications without certain metrics, `http_inflight_requests_total` being one of them.

The code in `zio-http` has been extracted out of some internal support libs we use.  We started out using `zio-metrics` but started to move all metrics over to `zio-zmx` once it was communicated that its design was quite close to what would be integrated directly into core. Both of these supported `increment` and `decrement` for gauges, but neither support ZIO 2.

This leaves be a bit stuck when it comes to upgrading to ZIO 2. 😞


I care a lot of operations and this point was, to me, one of the biggest selling points of ZIO 2:

> Operations - ZIO must scale with you to support the needs of the most complex industry scale application with support for logging, metrics, and execution tracing.

But It think this shows that we're not quite there yet.

I'd be _very_ willing to dig into and help fixing this, but I suspect I need some assistance because my attempts thus far haven't been very successful. Currently it's hard to implement functionality for a single type of metric (and adding something like `modify` or `getAndUpdate` doesn't make a whole lot of sense in the case of e.g  histograms, summaries and frequencies). I suspect that we might need to tweak the design to allow making the underlying implementations for a metric more specific instead of using `MetricHook` for all metrics, but I may very well be wrong because I don't fully grok the value of that abstraction in the first place 🤔

**Comment by adamgfraser** [comment]
Isn't `http_inflight_requests_total` just `http_requests_started` - `http_requests_completed`?

**Comment by adamgfraser** [comment]
I have an idea for this. Will post something tomorrow.

**Comment by frekw** [comment]
Amazing. 🙏

Just ping if there's anything I can do, I'd be super happy to help out with making this happen!

**Comment by frekw** [comment]
> Isn't http_inflight_requests_total just http_requests_started - http_requests_completed?

Yes, but in order to avoid 2x performance and storage overhead when querying, you'd have to setup a [recording rule](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules) to expose it as a single metric, which makes it harder to ship it as a "complete" solution.
