### ISSUE TITLE
2.0 unintuitive api: `runtime.unsafe.runToFuture`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7224]
given a 

```scala
r: zio.Runtime[Any]
```
it feels very unintuitive to have to write the following code to run an effect to a future:

```scala
val future = Unsafe.unsafe(implicit unsafe => r.unsafe.runToFuture(retrieveEffect))
```

why do I have to provide a `unsafe` to `runToFuture`, when I'm already calling `r.unsafe` ? This does not make any sense, especially as `Unsafe` has no methods or anything to implement. I already know that I'm doing something unsafe by calling `r.unsafe`

I also noticed that a deprecation on the companion object of `Unsafe` mentions a version `3.0.0` which is kind of strange, as we're currently at zio 2.0.1 
![grafik](https://user-images.githubusercontent.com/100349/185766303-0e17eaee-17bc-43dd-93b6-f5a7e9334f3b.png)

I'm not sure if this can be fixed in zio 2.0 or we have to wait for 2.1 or 3.0.. it certainly feels strange and unnecessary (at least to me).

**Comment by adamgfraser** [comment]
There is a trade-off here between making it easy to use these unsafe operators and controlling their usage.

The problem with just using the `unsafe` prefix is that you know that you are using an unsafe operator, but the Scala compiler doesn't know and so it can't help you. The idea of the `Unsafe` capability is that operators that are unsafe require this capability and if you call this in a method the compiler enforces that you either provide the `Unsafe` capability directly using `unsafe` or ideally propagate it to a higher level by adding a requirement to your method that it also has the `Unsafe` capability. This way the requirement propagates up until you get to a region where you provide it, ideally in a constructor such as `ZIO.succeed` that can safely manage arbitrary side effects.

Clearly there is some trade-off here in having to use `unsafe` or propagate the requirement and your mileage may vary in whether that is worth it for you. However, other users have found this extremely valuable to be able to get the compiler to help them manage where they are using unsafe operators and ensure they are only doing it in intended places.

If you find yourself doing this a lot and want to just be able to unsafely run things to futures without providing the capability you can create your own operator or extension method that does that.

**Comment by domdorn** [comment]
thanks for clarifying!
