### ISSUE TITLE
logger of a Runtime is not propagated when constructing layers

### ISSUE THREAD

**Issue by TobiasPfeifer** [zio/zio#7230]
There is a problem when replacing the default logger on the `Runtime` and using the `Runtime` as a dependency in a service to run an effect to a `Future`. The effect that is `runToFuture` does not use the provided logger although it should be run by the same `Runtime`.

Snippet to reproduce: https://scastie.scala-lang.org/uMbGsvuARg6WNutvIDNEgA
The `ZIO.fromFuture(...runToFuture(...))` in this example is for demonstration purposes. In production the inner effect needs to be run to a Future to compose akka-http Routes.

```
import zio.Scope
import zio.ZIO
import zio.ZIOAppDefault
import zio.ZLayer
import zio.Unsafe
import zio.logging.LogFormat
import zio.Schedule
import zio.durationInt
import scala.concurrent.ExecutionContext
import scala.concurrent.Future

object DemoApplication extends ZIOAppDefault {
  val logger =
    zio.Runtime.removeDefaultLoggers >>> zio.logging.console(format = LogFormat.enclosingClass |-| LogFormat.line)

  override def run: ZIO[Any with Scope, Any, Any] = {
    val e = for {
      r <- ZIO.runtime[Any]
      printerService <- ZIO.service[PrinterService]
      _ <- ZIO.logInfo("this info log uses the provided logger")

      _ <- ZIO
        .acquireRelease(
          ZIO.fromFuture(implicit ec => printerService.print()).repeat(Schedule.fixed(2.seconds).upTo(10.seconds)).fork
        )(printFiber => printFiber.interrupt).forkScoped
    } yield ()

    ZIO.scoped(e)
      .provide(
        logger,
        PrinterService.live,
      )
  }

  sealed trait PrinterService {
    def print(): Future[Unit]
  }

  object PrinterService {
    val live: ZLayer[Any, Nothing, PrinterService] = ZLayer.fromZIO(ZIO.runtime[Any].map(r => PrinterServiceImpl(r)))
  }

  final case class PrinterServiceImpl(zioRuntime: zio.Runtime[Any]) extends PrinterService {
    override def print(): Future[Unit] = {
      val printEffect = ZIO.logInfo("this info log should also use the provided logger")
      Unsafe.unsafe(implicit u => zioRuntime.unsafe.runToFuture(printEffect))
    }
  }
}
```

Expected output:

```
main.scala this info log uses the provided logger
main.scala this info log should also use the provided logger
main.scala this info log should also use the provided logger
main.scala this info log should also use the provided logger
main.scala this info log should also use the provided logger
main.scala this info log should also use the provided logger
main.scala this info log should also use the provided logger
```

Actual output:

```scala
main.scala this info log uses the provided logger
timestamp=2022-08-23T09:14:43.469075592Z level=INFO thread=#zio-fiber-11 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
timestamp=2022-08-23T09:14:45.518789507Z level=INFO thread=#zio-fiber-12 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
timestamp=2022-08-23T09:14:47.501023370Z level=INFO thread=#zio-fiber-13 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
timestamp=2022-08-23T09:14:49.498244229Z level=INFO thread=#zio-fiber-14 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
timestamp=2022-08-23T09:14:51.498631708Z level=INFO thread=#zio-fiber-15 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
timestamp=2022-08-23T09:14:53.498315461Z level=INFO thread=#zio-fiber-16 message="this info log should also use the provided logger" location=<empty>.DemoApplication.PrinterServiceImpl.print.printEffect file=main.scala line=45
```

Our workaround:
Explicitly provide the same logger on the inner effect (`val printEffect`).
```val printEffect = ZIO.logInfo("this info log should also use the provided logger").provide(DemoApplication.logger)```

**Comment by adamgfraser** [comment]
@TobiasPfeifer You need to build the logging layer before the printer layer so that its configuration is set when the printer layer is created using `logger >>> PrinterService.live`.

**Comment by TobiasPfeifer** [comment]
@adamgfraser, thanks for your response. However, I feel the behavior without explicitly composing the logger with the layer is inconsistent. When constructing a layer `A` that needs a `B`, then `x.provide(A, B)` will inject `B` into `A`. The same is not true when constructing a layer `C` that needs a 'Runtime'-Layer i.e `x.provide(C, Runtime)`.

I'm aware that the `Runtime` requirement differs from a regular dependency (it's not even part of the `RIn` type param) but is there any reason not to treat it equally?

Should `a.provide(b.provide(c))` not equal `a.provide(b, c)` if `a` requires `b` and `b` requires `c`?

**Comment by adamgfraser** [comment]
@TobiasPfeifer Yes there is a difference because there is no basis for saying that `B` "needs" `A` in this case.

Consider the following layers:

```scala
val layer1: ZLayer[X, Nothing, Y] = ???
val layer2: ZLayer[Y, Nothing, Z] = ???
```

In this case we can objectively say that `layer2` "needs" `layer1`. `layer2` requires a dependency, `Y` that is provided by `layer1`. We can formalize this notion by viewing each layer as an edge in a directed acyclic graph and layer construction as performing a topological sort.

Now consider the following layers:

```scala
val layer3: ZLayer[Any, Nothing, Unit] = ???
val layer4: ZLayer[Any, Nothing, Z] = ???
```

In this case there is no basis for saying that `layer4` "needs" `layer3`. In your case you know that one is a logging layer, the other is some service, and you want the configuration of the first to apply to the second. But there is nothing from the type signatures that tells us that. And someone else might want the service to not use the configuration.

So when we want to tell the compiler that one layer "needs" another even though it is not reflected in the type signature we do that by using `>>>` to indicate that one layer should be constructed and then the other.

**Comment by TobiasPfeifer** [comment]
I understand your point, and changing the semantics of the `provide` macro might not be a great solution (or bringing back `Logging` to the Env-Param like it was with `ZEnv`).

Maybe I'm missing a way to configure a global Runtime that is used when constructing layers? I think this is an actual use case, especially for logging. Configuring logging at the top level of the application should also affect layer construction. If a layer needs a custom logger, I can explicitly construct it with `logger >>> layer`

As a user, I don't want to write
```
val logger = ....
x.provide(
  logger >>> Service1.live,
  logger >>> Service2.live,
  logger >>> Service3.live,
  logger >>> Service4.live,
  logger >>> Service5.live,
  logger >>> Service6.live,
  ...
)
```

**Comment by adamgfraser** [comment]
No, you want to factor out the logger.

```scala
val services: ZLayer[Any, Nothing, Services] =
  ZLayer.make[Services](
    Service1.live,
    Service2.live,
    Service3.live,
    Service4.live,
    Service5.live,
    Service6.live
  )

x.provide(logger >>> services)
```

**Comment by TobiasPfeifer** [comment]
@adamgfraser thanks for your help and clarification

**Comment by TobiasPfeifer** [comment]
We found that this issue can also be addressed by chaining multiple calls  to `provide`:
```
x
  .provide(serviceLayer1, serviceLayer2, serviceLayer3)
  .provide(logger)
```
