### ISSUE TITLE
Add support to ignore tests by tag

### ISSUE THREAD

**Issue by johnduffell** [zio/zio#7232]
At the moment it's possible to tag tests and then run them based on the tag
e.g. this snippet
```scala
    test("foo") {
      assertTrue(true)
    }.annotate(TestAnnotation.tagged, Set("IntegrationTest")),
```
then 
`Test/runMain ExampleSpec -tags "-IntegrationTest"`

This is similar to the way to run tests by label documented here: https://zio.dev/reference/test/running-tests

However, it doesn't appear to be possible to only run the tests not tagged with that (or only run the untagged tests)

Having checked the source code there doesn't seem to be any support, so would it be possible to add an -excludeTags or similar?
Line that does the filtering (include only) https://github.com/zio/zio/blob/d78b16664d7ebf2c4b95b8519434594924d6c15e/test/shared/src/main/scala/zio/test/FilteredSpec.scala#L37

Line that parses the argument (include only)
https://github.com/zio/zio/blob/d78b16664d7ebf2c4b95b8519434594924d6c15e/test/shared/src/main/scala/zio/test/TestArgs.scala#L38

If you need any more info I'd be happy to provide, and also we would be happy to provide a small PR if the approach is validated before hand.

**Comment by adamgfraser** [comment]
@johnduffell I think this would be a great feature to add. These types of command line interfaces are always going to have limitations in terms of expressivity but being able to include or exclude specified tags seems like a good set of features to have.

**Comment by Wosin** [comment]
@adamgfraser  we can close that one :)
