### ISSUE TITLE
ZIO 2.0.1, FiberRuntime memory leak vol.2

### ISSUE THREAD

**Issue by adwells-ds** [zio/zio#7233]
Apperantly we haven't completely fixed the previous issues https://github.com/zio/zio/issues/7066 and https://github.com/zio/zio-kafka/issues/485 

For some reason succeeded `FiberRuntime's` continiue to live in memory with related resources
In case of `zio-kafka` it makes all kafka records not available for gc:
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/87975016/186240360-a7b020ba-daaa-4a88-aece-bab93d2655f0.png">

I tried to find the simple reproducible example and only came up with the next one(it not a 100% `zio-kafka` case, but very similar one):
```scala
override def run =
  def f = ZIO.attempt(Record(1))

  val io =  for {
    _ <- f.forkScoped.flatMap(fb => fb.join).forever
  } yield ()

  io.exitCode
``` 
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/87975016/186238887-cf64bb22-d2d2-4c43-8f4f-648745ca7d3d.png">
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/87975016/186241245-1afc57cc-1e7b-4a31-abff-175c0ba4c880.png">

Looks like it not always get removed from the queue, since the numbers correlate:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/87975016/186245833-0acb0285-17c7-4816-aad0-1f6f2312abd2.png">

fyi @adamgfraser , we will definitely need your help here:)

**Comment by adamgfraser** [comment]
@adwells-ds Will take a look! Thanks for the minimized reproducer!
