### ISSUE TITLE
ZIO 2.0.1, FiberRuntime memory leak, vol. 3

### ISSUE THREAD

**Issue by adwells-ds** [zio/zio#7235]
Apparently.. https://github.com/zio/zio/issues/7233 solves only the primitive case, but when `FiberRuntime` has cross-reference on each other(?) and already succeeded it will not be removed from the `_children` queue(?) and will keep all related resources (this is exact https://github.com/zio/zio-kafka/issues/485 case)

How to reproduce(I tried to simplified it, but it is the smallest example I was able to come up with)
We have 2 independent streams, one is requesting records from another, the second fulfilling the requests:
```scala

import zio.*
import java.util.concurrent.atomic.AtomicLong
import zio.stream.*

object Main extends ZIOAppDefault:
  case class Record(i: Int)
  case class Request(cont: Promise[Option[Throwable], Chunk[Record]])

  case class ConsumerLocal(
    queue: Queue[Request]
  ):
    // Fulfill promises
    def runloop() = ZStream
      .fromQueue(queue)
      .mapZIO(_.cont.succeed(Chunk.fromIterable(0.to(100).map(Record(_)))))
      .runDrain
      .forkScoped

    // Request new records
    def makeStream() =
      for {
        p <- Promise.make[Throwable, Unit]
        s = ZStream
              .repeatZIOChunkOption(for {
                request <- Promise.make[Option[Throwable], Chunk[Record]]
                _       <- queue.offer(Request(request)).unit
                result  <- request.await
              } yield result)
              .interruptWhen(p)
      } yield (p, s)

    def stream() = ZStream.fromZIO(makeStream())

  override def run =
    val io = for {
      q <- Queue.unbounded[Request]
      c  = ConsumerLocal(q)
      _ <- c.runloop()
      _ <- c.stream()
             .mapZIOParUnordered(4) { case (_, b) =>
               b.groupedWithin(100, 1.millis)
                 .mapZIO { rr =>
                     ZIO.attempt(rr)
                 }
                 .runDrain
             }
             .runDrain
    } yield ()
    io.exitCode

```
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/87975016/186354453-61ae6dc6-1b5b-4e3d-8793-a805603f2517.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/87975016/186351004-cc3fe7be-86f0-4c7e-98d4-5972e4bfb7c1.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/87975016/186348038-82d0fee8-5662-471c-ac38-1cc46c268fe7.png">

@adamgfraser Sorry to disturb you again, but I believe it is the last issue:)

**Comment by 987Nabil** [comment]
It would be really nice if this could be fixed asap and also have a patch release for ZIO, when done.

**Comment by adamgfraser** [comment]
Got a chance to look at this. I don't think it is actually related to the ZIO runtime. If you replace the use of `groupedWithin` in your example with `grouped` I observe constant memory consumption. This indicates that the issue is with `aggregateAsync`, which `groupedWithin` is implemented in terms of. This perhaps shouldn't be surprising as `aggregateAsync` is probably the most complex operator in ZIO Stream and has been associated with memory leaks in the past.

Anyway, none of this changes that this is still a problem and still needs to be fixed but wanted to share my findings to date.

**Comment by adwells-ds** [comment]
Thanks for pointing in the right direction and yeap, you are correct about the runtime, I just checked the `aggregateAsync` and there is an issue with a recursion:
https://github.com/zio/zio/blob/series/2.x/streams/shared/src/main/scala/zio/stream/ZStream.scala#L279-L282

But as I understand we always have `scheduleAggregate` as a last call, so why tail recursion is not working here?

I simplified the function to demonstrate the problem, but couldn't find a correct way to untangle it, since the logic looks fine to me:
```scala
object Main extends ZIOAppDefault:
  case class Record(i: Int)

  override def run =
    val recordsFb = ZIO.attempt(Chunk.fromIterable(0.to(100).map(Record(_)))).forkScoped

    def scheduleIO = for {
              fb <- recordsFb
              _ <-  schedule(fb)
            } yield ()


    def schedule(fiber: Fiber.Runtime[Throwable, Chunk[Record]]): ZIO[Scope, Any, Unit] =
      def handle(records: Chunk[Record]): ZIO[Scope, Any, Unit] =
        scheduleIO

      fiber.join.raceWith(ZIO.unit.forever)(
        (ex, fb) => fb.interrupt *> ZIO.done(ex).flatMap(handle),
        (ex, fb) => fb.interrupt *> ZIO.done(ex).flatMap(_ => handle(Chunk.empty[Record]))
      )

    scheduleIO

```


**Upd.** Okay, I figured out, how to fix it for my case, but with the original function it would be more tricky, btw this works good:
```scala
object Main extends ZIOAppDefault:
  case class Record(i: Int)

  override def run =
    val recordsFb = ZIO.attempt(Chunk.fromIterable(0.to(100).map(Record(_)))).forkScoped

    def schedule(fiber: Fiber.Runtime[Throwable, Chunk[Record]]): ZIO[Scope, Any, Unit] =
      def loop(fiber2: Fiber.Runtime[Throwable, Chunk[Record]], records: Chunk[Record]) : ZIO[Scope, Any, Unit]  =
        fiber2.join.raceWith(ZIO.unit.forever)(
          (ex, fb) => fb.interrupt *> ZIO.done(ex).flatMap(r => recordsFb.flatMap(loop(_, r))),
          (_, _) => ZIO.fail(new RuntimeException())
        )

      loop(fiber, Chunk.empty)

    for {
      fb <- recordsFb
      _ <- schedule(fb)
    } yield ()
```

**Comment by narma** [comment]
Related issue https://github.com/zio/zio/issues/6613

**Comment by adamgfraser** [comment]
@ad-wells The use of the for comprehension in your example above is not effectually tail recursive since the de-sugaring adds a final `map` after the recursive call to `schedule`. Your first example will work in constant memory if you rewrite `scheduleIO` as follows:

```scala
def scheduleIO: ZIO[Any with Scope, Any, Unit] =
  recordsFb.flatMap(fb => schedule(fb))
```

**Comment by ak0rz** [comment]
@adamgfraser 

> @ad-wells The use of the for comprehension in your example above is not effectually tail recursive since the de-sugaring adds a final `map` after the recursive call to `schedule`.

It would not with pretty common `better-monadic-for` scalac plugin.

Just to mention it. :)

**Comment by adamgfraser** [comment]
@ya-goodfella I'm not a fan of third party compiler plugins versus fixing the language itself but you can do what you want. 😃

**Comment by ak0rz** [comment]
@adamgfraser could you please make a maintenance release with that fix? Memory leak in ZStream is a major issue for some of our applications which blocks their transition to zio2. 

Thanks! 

cc @darl

**Comment by adamgfraser** [comment]
@ya-goodfella Yes but let's make sure this actually fixes the issue for the affected users first.

**Comment by adwells-ds** [comment]
@adamgfraser Thanks for the fix, I just tested it with original app and `zio-kafka` consumer as well, no signs of any old/new memory leaks, looks pretty stable :+1:

**Comment by ak0rz** [comment]
@adamgfraser our leak seems to be resolved in latest zio2 snapshot, thanks.
