### ISSUE TITLE
Cannot call macro class <case class> defined in the same source file

### ISSUE THREAD

**Issue by simlei** [zio/zio#7236]
This is a compile-time error. MRP below. The error message is:
`Cannot call macro class <case class> defined in the same source file`

ZIO version: 2.0.1

MRP:

```scala
import zio.*

def serviceUser(i: Int): URIO[Test.Service, Test.CC] = for {
  view <- ZIO.succeed(true)
} yield Test.CC(i)

val program = for {
  service <- ZIO.succeed(Test.service)
  i <- ZIO.succeed(1)
  uiRunning <- serviceUser(i).provide(ZLayer.succeed(service))
} yield ()


object Test {
  type Service = String
  val service: String = "service"
  case class CC(i: Int)
}
```

https://scastie.scala-lang.org/1roKxCSYRRyzLpOpcQ9JLg

**Comment by adamgfraser** [comment]
@kitlangton Do you think this can be improved?

**Comment by NavidJalali** [comment]
Just out of curiosity, was this on scala 3?

**Comment by kitlangton** [comment]
This is a Scala 3 bug. I think they fixed in in a patch. But it may not be released yet. There's a merged PR in the dotty repo.

**Comment by NavidJalali** [comment]
https://github.com/lampepfl/dotty/issues/12498 
Next release will have the fixes, looks like you might find a snapshot/nightly with the fix if its urgent but definitely it's not a problem with ZIO :D

**Comment by ruurtjan** [comment]
I ran into this issue as well, and it went away after upgrading to Scala `3.2.1-RC2`.

I've also tested the code snippet by @simlei, which also compiles fine on that Scala version.

**Comment by dnio99** [comment]
scala version: 3.2.0
```
  type AllEnv = R1 & R2 & R3

  val all = ZLayer.make[AllEnv](
    R1.live,
    R2.live,
    R3.live
  )
```
compile-time error. 
`Cannot call macro type AllEnv defined in the same source file`
needs to be replaced with

```
  type AllEnv = R1 & R2 & R3

  val all = ZLayer.make[R1 & R2 & R3](
    R1.live,
    R2.live,
    R3.live
  )
```
The following code can be compiled normally in scala version to 3.2.1-RC1
```
  type AllEnv = R1 & R2 & R3

  val all = ZLayer.make[AllEnv](
    R1.live,
    R2.live,
    R3.live
  )
```
