### ISSUE TITLE
Unsafe.unsafe breaking change in 2.0.1 under Scala 3

### ISSUE THREAD

**Issue by MI3Guy** [zio/zio#7237]
Previously this function accepted a context function when building for Scala 3. In some refactoring, this appears to have been changed from a context function to a normal function.

Where previously it was possible to use

```
Unsafe.unsafe {
  runtime.unsafe.run(...)
}
```

Now you must either use the older `implicit unsafe =>` syntax or manually create a given from the parameter. (I haven't found a direct alternative to `implicit` in this instance, though I may have overlooked it.)

**Comment by adamgfraser** [comment]
@MI3Guy Hi! There is an implicit conversion from an ordinary Scala function to an implicit function.

```scala
test("provides capability to implicit function") {
  def succeed[A](block: Unsafe ?=> A): ZIO[Any, Nothing, A] =
    ZIO.succeed(Unsafe.unsafe(block))
  assertCompletes
}
```

**Comment by MI3Guy** [comment]
I would think that passing the context function as a literal would be more common than declaring it separately. There are plenty of ways that this can be worked around, of course. But it is no longer possible to just use it directly as in the example in the original post.

**Comment by sbosley** [comment]
I encountered this same issue when I upgraded a project from 2.0.0 to 2.0.1. Under 2.0.0, `Unsafe.unsafe { runtime.unsafe.run(...) }` compiled and ran without issue. After updating to 2.0.1, it fails to compile with:

```
Type Mismatch Error: <filename>
[error]    |            Found:    (zio.Trace, zio.Unsafe) => zio.Exit[Nothing, Unit]
[error]    |            Required: zio.Unsafe => Any
```

I was able to work around this by changing the code to `Unsafe.unsafe { unsafe ?=> runtime.unsafe.run(...) }`, which isn't too big a deal. Nevertheless, it does seem like it was a breaking change in source compatibility between 2.0.0 and 2.0.1.

**Comment by adamgfraser** [comment]
Yes. The change is binary compatible and we thought it was source compatible but it looks like due to implicit resolution issues it is not in some cases. Basically if your lambda just requires a given `Unsafe` it works as shown in the example above button if it requires additional given parameters as well. We are working on this and have opened a Scala compiler issue for it.

**Comment by pvgoran** [comment]
I just upgraded from 2.0.0 to 2.0.2 and encountered it as well.

Not a big deal, but I hope we can have a new release that includes https://github.com/zio/zio/pull/7286 (or otherwise fixes this) soon. :)

**Comment by adamgfraser** [comment]
👍
