### ISSUE TITLE
ZStream.repeat is uninterruptible

### ISSUE THREAD

**Issue by n3ziniuka5** [zio/zio#7240]
The following ZIO app cannot be terminated by SIGINT/SIGTERM

```scala
object Main extends ZIOAppDefault {
  val run = ZStream.repeat("1").runDrain
}
```

@adamgfraser confirmed that interruptions are only checked for in ZIO workflows. It's easy to verify that by just adding simple processing or using `repeatZIO`, the apps bellow interrupt as expected:
```scala
object Main extends ZIOAppDefault {
  val run = ZStream.repeat("1").mapZIO(ZIO.logInfo(_)).runDrain
}
```
```scala
object Main extends ZIOAppDefault {
  val run = ZStream.repeatZIO(ZIO.succeed("1")).runDrain
}
```

Completely side-effect-free apps, such as `ZStream.range(...).map(...)` are also uninterruptible

**Comment by bertlebee** [comment]
I'll take this one
