### ISSUE TITLE
Spurious streams test failure

### ISSUE THREAD

**Issue by bertlebee** [zio/zio#7277]
happens not infrequently

to reproduce:
`streamsTestsJVM/testOnly *.ZChannelSpec -- -t "simple merge all"`

a couple of examples:
- ZChannelSpec / interpreter / ZChannel#mergeAll / simple merge all
        ✗ Set2(1, 6) was not equal to Set3(1, 4, 9)
        chunk.toSet did not satisfy equalTo(Set(1, 4, 9))
        chunk.toSet = Set2(1, 6)
        at /home/rob/code/zio/streams-tests/shared/src/test/scala/zio/stream/ZChannelSpec.scala:446

- ZChannelSpec / interpreter / ZChannel#mergeAll / simple merge all
        ✗ Set3(2, 6, 3) was not equal to Set3(1, 4, 9)
        chunk.toSet did not satisfy equalTo(Set(1, 4, 9))
        chunk.toSet = Set3(2, 6, 3)
        at /home/rob/code/zio/streams-tests/shared/src/test/scala/zio/stream/ZChannelSpec.scala:446

**Comment by adamgfraser** [comment]
I can reproduce locally.
