### ISSUE TITLE
Fiber hangs in ZStream#mapZIOParUnordered

### ISSUE THREAD

**Issue by EvgenyAfanasev** [zio/zio#7283]
```scala
ZStream.fromSchedule(Schedule.upTo(30.seconds))
    .mapZIOParUnordered(3)(_ => some_zio_effect)
    .runDrain
```

When I run this, 2 fibers starts fine, but the next fiber hangs. If I change `mapZIOParUnordered` to `mapZIOPar`, all 

Version: 2.0.2

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!

**Comment by adamgfraser** [comment]
@EvgenyAfanasev What is `some_zio_effect`? I am not able to reproduce, at least with a simple ZIO workflow.

**Comment by NavidJalali** [comment]
I think **_MAYBE_** I might have been able to reproduce this, but I cannot yet minimize it further, also it was very flakey. But will comment here if I can find a minimal reproducer

**Comment by adamgfraser** [comment]
Going to close this for now but feel free to re-open if you are able to reproduce!
