### ISSUE TITLE
Interruption error when providing layer 

### ISSUE THREAD

**Issue by davidlar** [zio/zio#7288]
Hi @adamgfraser!

I have a service with a lot of layers with fairly complicated acquire functions. The service worked fine with ZIO 2.0.0 but when I updated to ZIO 2.0.1 (or 2.0.2) it started to crash on startup in about 20-30 % of the cases. It seems to be some low level interruption from some of the layers that surfaces and interrupts the whole application when I do program.provide().
I tracked down the change that causes this to https://github.com/zio/zio/pull/7131
It feels like some kind of a race problem.

Sorry I didn't manage to create a small reproducer, but I'm happy to help testing out patches!

**Comment by adamgfraser** [comment]
@davidlar Hi! Thanks for reporting and for tracking it down! Can you see if #7289 resolves your issue?

**Comment by davidlar** [comment]
@adamgfraser it works like a charm! :smiley: 
I tested over 20 times without failure!
Thanks a lot for the quick fix!

**Comment by adamgfraser** [comment]
@davidlar Awesome!
