### ISSUE TITLE
[zio1] ZStream.mapMParUnordered prevents stream from failing with error

### ISSUE THREAD

**Issue by somdoron** [zio/zio#7293]
With zio version 1.0.16 `mapMParUnordered` prevents the stream from failing, test below:

```
package zio.zmq

import zio.test.*
import zio.test.Assertion.*
import zio.ZIO
import zio.duration.*
import zio.magic.*
import zio.stream.ZStream
import zio.blocking.Blocking

object SocketSpec extends DefaultMutableRunnableSpec {
  testM("interrupt blocking") {
    val blocks = zio.blocking.effectBlockingInterrupt {
        Thread.sleep(Long.MaxValue)
        1
    }.orDie

    val s = ZStream.repeatEffect(blocks)
    val e = ZStream.fromEffect(ZIO.fail("Fail please").delay(100.millis)).onError(_ => ZIO.debug("Error"))
    for {
      f <- ZStream
            .mergeAllUnbounded()(s, s, s, s, s, s, s, s, s, s, s, s, s, e)
            .mapMParUnordered(10)(a => ZIO.succeed(a)) // This line prevents the stream from failing
            .runDrain
            .injectSome[Blocking](zio.clock.Clock.live)
            .fork
      code <- f.await
    } yield assertTrue(!code.succeeded)
  }
}
```

**Comment by adamgfraser** [comment]
@somdoron Thanks for reporting!

**Comment by somdoron** [comment]
@adamgfraser I think the issue is interdependencies between the different fibers, the problem is that flatMapPar is using [Fiber.interruptAll](https://github.com/zio/zio/blob/series/1.x/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1504), but the order interrupting is important, especially when using the blocking variants, I can see one fiber waiting on another fiber, that is in the list for `interruptAll` but later in the sequence.

I think that interrupting all fibers and then waiting would solve this. Maybe fixing `Fiber.interruptAllAs`?

my suggested fix :
```
def interruptAllAs(fiberId: Fiber.Id)(fs: Iterable[Fiber[Any, Any]]): UIO[Unit] =
    ZIO.foreach(fs)(_.interruptAs(fiberId).fork).flatMap(fs => ZIO.foreach_(fs)(_.await))
```

I tested the fix and it is working.

**Comment by luis3m** [comment]
Indeed that small change fixes the problem: https://scastie.scala-lang.org/PXSa5XjoTTW5Vq6SPjP8gQ
