### ISSUE TITLE
Interrupted in finalizer

### ISSUE THREAD

**Issue by davidlar** [zio/zio#7299]
Hi @adamgfraser!

Got interrupted in the finalizer of ensuring during layer release. Finally managed to create a reproducer https://github.com/davidlar/zio-issue-1.
The culprit seems to be a call to disconnect in ZPool. I'm not sure if the problem is disconnect itself or the usage of it.
There are 2 main classes in the reproducer. 
One uses the standard ZPool and gets interrupted in the finalizer. 
The other one uses a ZPool without the disconnect call and works as expected

**Comment by adamgfraser** [comment]
@davidlar Thanks for reporting and for the reproducer! Will take a look!

**Comment by adamgfraser** [comment]
I see the issue. Working on a fix.
