### ISSUE TITLE
Separate project versioning from core versioning

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#730]
I am not sure exactly how to do this while keeping the release process easy and automated, but ideally the modules would be independently versioned. Following semver across all modules will be onerous and lead to unnecessary release versions.

Knowledge of SBT and plugins will be required for this ticket.

**Comment by NeQuissimus** [comment]
Separate repos + https://github.com/fthomas/scala-steward to keep core updated?

**Comment by mijicd** [comment]
Steward is already integrated but it might be suffering from [this](https://github.com/fthomas/scala-steward/pull/364#issuecomment-480937458). Fortunately, it is a known bug, and it can be fixed either by dropping the plugin, or via the approach described [here](cb372/sbt-explicit-dependencies#33).

Plugin-wise, [sbt-sonatype](https://github.com/xerial/sbt-sonatype) and [sbt-release](https://github.com/sbt/sbt-release) might be helpful here.

**Comment by adamgfraser** [comment]
I think at this point we are keeping versioning consistent for ZIO Core, ZIO Stream, and ZIO Test and the rest of the ecosystem can evolve independently so I don't think there is an actionable to do here.
