### ISSUE TITLE
Documentation: Ref link is broken

### ISSUE THREAD

**Issue by lwilli** [zio/zio#7304]
Under https://zio.dev/reference/#state-management, the `Ref` link points to https://zio.dev/reference/state/ref.md, which doesn't exist. I also noticed in the [Concurrency Primitives section](https://zio.dev/reference/#concurrency-primitives) there is another [`Ref` link](https://zio.dev/reference/concurrency/ref/), which does work.

As a ZIO newcomer, it's a little confusing if these are intended to be the same (I suspect they are). Could someone please unify/fix these? Thanks!

**Comment by adamgfraser** [comment]
@lwilli Thanks for reporting and welcome to ZIO! Just submitted a PR to fix this.
