### ISSUE TITLE
ZIO 2.0 Test: TestClock does not adjust time deeper than one forked effect

### ISSUE THREAD

**Issue by zeal18** [zio/zio#7314]
ZIO: 2.0.2
Scala: 2.13.8

```scala
import zio.test._
import zio._

object DoubleForkTestClockSpec extends ZIOSpecDefault {
  override def spec: Spec[TestEnvironment with Scope, Any] = suite("DoubleForkTestClockSpec") {
    test("test clock adjustment") {
      for {
        promise <- Promise.make[Nothing, Unit]
        effect = ZIO.sleep(10.seconds) *> promise.succeed(())

        _ <- effect.fork.fork

        _ <- TestClock.adjust(11.seconds)
        _ <- promise.await

      } yield assertCompletes
    }
  }
}
```

The test case hangs forever, which could mean that the TestClock is inside, but adjustment works only for the first fork.
The real code is a bit more complicated but the idea is the same: inside of one async effect there is another async scheduled effect which periodically synchronises data. The goal is to be able to control data synchronisations adjusting the TestClock according to the schedule.

**Comment by adamgfraser** [comment]
@zeal18 Thanks for reporting! Will take a look.

**Comment by adamgfraser** [comment]
@zeal18 Your test failure is not related to the `TestClock` but to fiber supervision. You fork a child fiber which forks a grandchild fiber. The child fiber completes execution immediately after forking the grandchild fiber. Under ZIO's fiber supervision model when a fiber completes execution it interrupts all of its children. So its grandchild is interrupted before completing the `Promise` and the test suspends indefinitely. If you replace both uses of `fork` with `forkDaemon` your test will complete immediately.

**Comment by zeal18** [comment]
> @zeal18 Your test failure is not related to the `TestClock` but to fiber supervision. You fork a child fiber which forks a grandchild fiber. The child fiber completes execution immediately after forking the grandchild fiber. Under ZIO's fiber supervision model when a fiber completes execution it interrupts all of its children. So its grandchild is interrupted before completing the `Promise` and the test suspends indefinitely. If you replace both uses of `fork` with `forkDaemon` your test will complete immediately.

Oh, right, thanks for the so fast answer and sorry for the false positive

**Comment by adamgfraser** [comment]
No worries!
