### ISSUE TITLE
ZIO 2.0.[012] bootstrap errors cause ZIOApp to exit without reporting problems

### ISSUE THREAD

**Issue by tim-2022** [zio/zio#7319]
This is a simplification of a bootstrap ZLayer which throws an error:

```
class Thing

object Main extends ZIOApp {

  override type Environment = Thing

  override def environmentTag: EnvironmentTag[Environment] =
    EnvironmentTag[Environment]

  override def bootstrap: ZLayer[ZIOAppArgs, Any, Environment] =
    ZLayer.succeed[Thing](throw new Exception)

  override def run: ZIO[Environment, Throwable, Unit] =
    printLine("Here")
}
```

It silently exits with a 1 status code, never reporting the source of the problem.  

Correctly reports exception under RC6 - https://scastie.scala-lang.org/tim-2022/uOUJVAgVTs215SBR3NX6ag/10

**Comment by swoogles** [comment]
Thanks, I will look into this.

**Comment by swoogles** [comment]
Well I _was_ going to take a look, but Adam beat me to it!

**Comment by tim-2022** [comment]
LOL!  My experience was also that Adam can be amazingly fast!
