### ISSUE TITLE
Re-add support for Scala 2.13

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#732]
Due to the fact that `mdoc` is not building on 2.13, I disabled the Travis build for 2.13.

Now that 2.13 is almost a thing, we need to get it building again. It looks like [there is a way to do that](https://github.com/scalameta/mdoc/issues/156) even before `mdoc` supports 2.13.

**Comment by denisgarci** [comment]
My best attempt at this lives here: https://github.com/denisgarci/scalaz-zio/tree/add-213-rc2
Some changes from `scala.collection` are not backward compatible between 2.13 and 2.12 / 2.11.
There are two ways to fix this:
* use  https://github.com/scala/scala-collection-compat (still waiting for https://github.com/scala/scala-collection-compat/issues/208 and https://github.com/scala/scala-collection-compat/issues/209) but this introduces a dependency on scala-collection-compat;
* or use different sub-directories for different Scala version (the affected files would be:
`FiberContext.scala`, `STM.scala` and`TQueue.scala`).

See https://docs.scala-lang.org/overviews/core/collections-migration-213.html

**Comment by jdegoes** [comment]
@denisgarci Thank you for your work on this and for posting your learnings and the code!

**Comment by ghostdogpr** [comment]
Closing this one as it’s duplicated by #1007 and the PR refers to the other one.
