### ISSUE TITLE
Performance regression in 2.0.0+

### ISSUE THREAD

**Issue by anovstrup** [zio/zio#7332]
I recently bumped the ZIO version in my application from 1.0.15 to 2.0.0 and noticed a significant performance regression in part of the workload, which involves substantial use of `ZStream` to read data from (very large) archive files, decode it from UTF-8, perform some other transformations in memory, and then write the data to disk again.  

Although I haven't isolated the issue yet, the ZIO overhead appears to be much higher than it had been before the update. The screenshot below from the jprofiler hotspot view was captured as the application ran the workload in question.  (This screenshot is actually from the application running against ZIO 2.0.2, which I tried after first observing the performance regression when running with ZIO 2.0.0.)

<img width="787" alt="image" src="https://user-images.githubusercontent.com/375423/189431290-4614bbd4-db8f-43bf-bdad-6e86e125f928.png">

**Comment by He-Pin** [comment]
How about provide a reproducer?

**Comment by anovstrup** [comment]
> How about provide a reproducer?

I hope to have some time next week to isolate and minimize the issue.

**Comment by anovstrup** [comment]
It looks like the trouble is related to the following `join` method in my application.

```scala
type Sink[-O] = ZSink[Any, Throwable, O, Nothing, Any]

def join[O, O2](s1: Sink[O], s2: Sink[O2]): Sink[(O, O2)] =
  s1.contramap((p: (O, O2)) => p._1) zipPar s2.contramap((p: (O, O2)) => p._2)
```

I believe the program sketched below will reproduce the issue:
```scala
val source: Stream[String] = ... infinite stream of reasonably large strings (each KBs long) ...
val logSink: Sink[String] = ... sinks its input to a log ...
val fileSink: Sink[Chunk[Byte]] = ... sinks its input to a file ...
val joined = join(logSink, fileSink)

// disproportionately slow
source map { s => (s, Chunk.fromArray(s.getBytes)) } >>> joined
// much faster (tupling/untupling here just for consistency)
source map { s => (s, Chunk.fromArray(s.getBytes)) } >>> 
  fileSink.contramap((p: (String, Chunk[Byte])) => p._2)
```

Digging into the implementation of `zipPar`, I see that it ends up using `raceWith`. Does that end up being a fairly heavyweight way to pass the same input to two sinks?

**Comment by adamgfraser** [comment]
Will take a look. `zipPar` does run the two sinks in parallel which has some overhead but that behavior was the same in ZIO 1.0 and ZIO 2.0 so conceptually that doesn't explain the difference though there may be something in the implementation that can be improved.

**Comment by anovstrup** [comment]
@adamgfraser It seems that we were using a different `join` implementation with ZIO 1.0 and only switched to the one above with ZIO 2.0 because a) the one above is simpler and b) we couldn't figure out how to do the same thing with the new API:

```scala
      def join[O, O2](s1: Sink[O], s2: Sink[O2]): Sink[(O, O2)] = zs.ZSink(for {
        p1 <- s1.push
        p2 <- s2.push
      } yield {
        case Some(chunk) => // chunk: Chunk[(O, O2)]
          // Apply p1 to the chunk of first elements of each pair and then (if successful) apply
          // p2 to the chunk of second elements of each pair. If either side halts/fails, the joined
          // sink halts/fails.
          p1(Some(chunk map (_._1))) *> p2(Some(chunk map (_._2)))
        case None        =>
          // We're at the end of the stream. Signal that to p1 and p2 by pushing None into each
          p1(None).catchSome {
            // Ignore the "failure" of p1 that signals that `sink` halted correctly with no
            // leftovers remaining to be pushed (see ZSink comments for a description of the
            // signaling mechanism embodied in the ZSink.Push type). The value in the Right can be
            // ignored (it's the value "emitted" by the sink on halting, which we don't care about).
            case (Right(_), zio.Chunk.empty) => zio.ZIO.unit
            // It's an error for `sink` to halt with leftovers when None is pushed
            case (Right(_), leftover)        =>
              zio.ZIO.fail(
                (Left(new RuntimeException("Unexpected leftovers in joined sink")), leftover))
            // Every other case is also an error and results in failure of the joined sink
          } *> p2(None)
      })
```

**Comment by adamgfraser** [comment]
@anovstrup Okay, so you have a custom implementation that sends the elements to both sinks but runs the sinks sequentially instead of in parallel. I could definitely see the overhead of the parallelism having a negative impact on performance if you are not actually getting a benefit from running the two sinks in parallel. Will take a look at how to do this in ZIO 2. Thanks for the follow up!

**Comment by anovstrup** [comment]
@adamgfraser Here's an actual program that reproduces the issue.  It runs similar workflows with and without a `join` operation and records their durations.  The discrepancy seems too large to be explained by parallelism overhead alone. e.g., in one run I got dur: PT55.033879744S ... dur2: PT9.726899208S ... dur3: PT53.146737292S, where dur & dur3 are the durations with `join` and dur2 is the duration without.
```scala
import zio._
import zio.stream._

import java.io.File

object ZioBugTest extends zio.ZIOAppDefault {
  type Sink[-O] = ZSink[Any, Throwable, O, Nothing, Any]

  def join[O, O2](s1: Sink[O], s2: Sink[O2]): Sink[(O, O2)] =
    s1.contramap((p: (O, O2)) => p._1) zipPar s2.contramap((p: (O, O2)) => p._2)

  val src: ZStream[Any, Nothing, (String, zio.Chunk[Byte])] =
    (ZStream.repeatZIO(Random.nextString(4096))
      take 100000
      mapChunks { _.map(s => (s, Chunk.fromArray(s.getBytes))) })

  var c = 0

  val sink1 = ZSink.foreach((_: String) =>
    ZIO.attempt {
      c += 1
      if (c % 10000 == 0) {
        println('.')
      }
    })

  val sink2 = ZPipeline.mapChunks((c: Chunk[Chunk[Byte]]) => c.flatten) >>>
    ZSink.fromFile(new File("out.txt")).ignoreLeftover

  val joined = join(sink1, sink2)

  override def run: ZIO[ZioBugTest.Environment with ZIOAppArgs with Scope, Any, Any] =
    for {
      (dur, _)  <- (src run joined).timed
      _         <- Console.printLine(s"\n\ndur: $dur")
      (dur2, _) <- (src run sink2.contramap((p: (String, Chunk[Byte])) => p._2)).timed
      _         <- Console.printLine(s"dur2: $dur2")
      (dur3, _) <- (src run joined).timed
      _         <- Console.printLine(s"dur3: $dur3")
    } yield ()

}
```

FWIW, this implementation of `join` also proves very slow relative to writing to a single sink:
```scala
        ZSink.fromChannel(
          s1.channel.contramapIn((c: Chunk[(O, O2)]) => c.map(_._1)) zipPar
            s2.channel.contramapIn((c: Chunk[(O, O2)]) => c.map(_._2)))
```

**Comment by adamgfraser** [comment]
@anovstrup Got it. Thanks!

**Comment by anovstrup** [comment]
One more update: I translated the above test to run it in ZIO 1.0 and observed very similar performance between the workflows with/without `join`, so it looks like this is in fact a performance regression and not just a performance issue.

The durations were dur: PT16.207304439S ... dur2: PT11.565797765S ... dur3: PT13.092716904S

```scala
package com.stottlerhenke.infotracker.suffixtree.api

import zio._
import zio.stream._

import java.io.File

object ZioBugTest extends zio.App {
  type Sink[-O] = ZSink[zio.ZEnv, Throwable, O, Nothing, Any]

  def join[O, O2](s1: Sink[O], s2: Sink[O2]): Sink[(O, O2)] =
    s1.contramap((p: (O, O2)) => p._1) zipPar s2.contramap((p: (O, O2)) => p._2)

  val src: ZStream[zio.random.Random, Nothing, (String, zio.Chunk[Byte])] =
    (ZStream.repeatEffect(zio.random.nextString(4096))
      take 100000
      mapChunks { _.map(s => (s, Chunk.fromArray(s.getBytes))) })

  var c = 0

  val sink1: Sink[String] =
    ZSink.foreach((_: String) =>
      ZIO.effect {
        c += 1
        if (c % 10000 == 0) {
          println('.')
        }
      }).dropLeftover

  val sink2: Sink[Chunk[Byte]] =
    (ZTransducer[Chunk[Byte]].mapChunks(_.flatten) >>>
      ZSink.fromFile(new File("out.txt").toPath)).dropLeftover

  val joined = join(sink1, sink2)

  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, ExitCode] =
    (for {
      (dur, _)  <- (src run joined).timed
      _         <- console.putStrLn(s"\n\ndur: $dur")
      (dur2, _) <- (src run sink2.contramap((p: (String, Chunk[Byte])) => p._2)).timed
      _         <- console.putStrLn(s"dur2: $dur2")
      (dur3, _) <- (src run joined).timed
      _         <- console.putStrLn(s"dur3: $dur3")
    } yield ExitCode(0)).orDie

}
```

**Comment by anovstrup** [comment]
Thanks, @adamgfraser! 🎉
