### ISSUE TITLE
Links to source code in test failures should include line number

### ISSUE THREAD

**Issue by swoogles** [zio/zio#7345]
When you click the link (at least in Intellij), the line number is not included, so you always just jump to the top of the file.

<img width="1470" alt="Screen Shot 2022-09-15 at 1 42 11 PM" src="https://user-images.githubusercontent.com/2054940/190495005-67d8e240-7157-4af6-9fb1-bd4d025d29df.png">

**Comment by adamgfraser** [comment]
Is this an issue with ZIO or with how IntelliJ is rendering the link? It looks like the line number is right there.
