### ISSUE TITLE
metrics: `zio.metrics.Metric#trackAll` should be `zio.metrics.Metric#trackAllWith`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7346]
I looked at Metrics.scala and I think `zio.metrics.Metric#trackAll` should actually be `zio.metrics.Metric#trackAllWith` .. 

kind of like 

```scala
  final def trackAll(implicit ev: In):  ZIOAspect[Nothing, Any, Nothing, Any, Nothing, Any] =
   trackAllWith(identity(_)) 


  final def trackAllWith(in: => In): ZIOAspect[Nothing, Any, Nothing, Any, Nothing, Any] =
    new ZIOAspect[Nothing, Any, Nothing, Any, Nothing, Any] {
      def apply[R, E, A](zio: ZIO[R, E, A])(implicit trace: Trace): ZIO[R, E, A] =
        zio.map { a =>
          unsafe.update(in)(Unsafe.unsafe)
          a
        }
    }
```

@vigoo you're the expert here.. wdyt?

**Comment by adamgfraser** [comment]
@domdorn The aspect is supposed to update the metric on either success or failure so if it does not use a constant value it would need a way to covert both a success as well as a cause with a failure into the metric input type. That could potentially be implemented as `trackAllWith` but the current signature of `trackAll` seems correct.

**Comment by domdorn** [comment]
Oh, I just figured out that this trackAll is coming from the `Metric` trait itself, while I was looking at it from the `Timer` point of view where it should be able to derive the right value in both cases (cause its the duration of the effect).
