### ISSUE TITLE
ZIO 2.x : ZIO.log() does logInfo() and never logs at the current log level

### ISSUE THREAD

**Issue by Jeancricri** [zio/zio#7358]
Here below is the current code :

/**
   * Logs the specified message at the current log level.
   */
  def log(message: => String)(implicit trace: Trace): UIO[Unit] =
    ZIO.withFiberRuntime[Any, Nothing, Unit] { (fiberState, _) =>
      fiberState.log(() => message, Cause.empty, None, trace)(Unsafe.unsafe)

      ZIO.unit
    }

**Comment by adamgfraser** [comment]
This does not appear to be accurate:

```scala
package zio

object Example extends ZIOAppDefault {

  val run =
    ZIO.logLevel(LogLevel.Error) {
      ZIO.log("log message")
    }
}
```

```
timestamp=2022-09-22T15:16:09.205627Z level=ERROR thread=#zio-fiber-6 message="log message" location=zio.Example.run file=Example.scala line=7
```

Notice that the log level is `Error`.

**Comment by Jeancricri** [comment]
My bad.
Probably an issue in my code ; I'm still working on it.
I was using
private val logger =
    Runtime.removeDefaultLoggers >>> console(LogFormat.default, LogLevel.Error )

**Comment by Jeancricri** [comment]
Thanks Adam for checking this case.
I think we may need a better documentation (or better comment in the source code) for "how to use ZIO.log()" in combo with ZIO.logLevel()

**Comment by adamgfraser** [comment]
What was your expectation of how this would work?

**Comment by Jeancricri** [comment]
I thought ZIO.log() would work without ZIO.logLevel(), using the current log level of the app I defined in  "private val logger =
Runtime.removeDefaultLoggers >>> console(LogFormat.default, LogLevel.Error )"

**Comment by adamgfraser** [comment]
Ah. That's the minimum log level that a logger will log. But a logger doesn't have to have any minimum log level and there could be different loggers that log at different levels. Think of that as the level of logs that a particular logger wants to "read", not the level you want to "write" at.

**Comment by Jeancricri** [comment]
Thanks Adam.
Could you tell how to change properly the current log level in a fiber of ZIOAppDefault ?

**Comment by adamgfraser** [comment]
No problem. You use the `ZIO.logLevel` operator. So if you do `ZIO.logLevel(LogLevel.Error)(workflow)` then `workflow` will be run with the default log level set to `LogLevel.Error`.
