### ISSUE TITLE
ZEnvironment.get dominates in cpu profile

### ISSUE THREAD

**Issue by darl** [zio/zio#7360]
In some of our applications `ZEnvironment.get` & `ZEnvironment.prune` consumes significant amount of cpu.

<img width="747" alt="Screenshot 2022-09-22 at 11 49 29" src="https://user-images.githubusercontent.com/423802/191753906-64f84260-d199-4a09-9c14-d701f33c934d.png">

I think this happens when:
1. ZEnvironment contains many different services
2. ZEnvironment frequently recreated by calling `.provideSome` 
In that case `cache` in `ZEnvironment` is always empty and `ZEnvironment.get` becomes linear search.

`LightTypeTag.<:<` is not simple too. And contains several iterations inside.

**Comment by adamgfraser** [comment]
It sounds like you are calling `provideEnvironment` too much. What I typically see when people have this problem is they are doing something like this:

```scala
  case class Live(innerService: InnerService) extends Outservice {
    override val bar: Task[Unit] = {
        InnerService.foo.provideEnvironment(ZEnvironment(innerService))
    }
  }
```

When you want to do this:

```scala
  case class Live(innerService: InnerService) extends Outservice {
    override val bar: Task[Unit] = {
        innerService.foo
    }
  }
```

**Comment by darl** [comment]
that example is too simple.
in reality it can be hidden in several abstractions levels.

also there are several classes that passed via environment:
  - zio.Scope !!
  - Connection from https://github.com/gaelrenoux/tranzactio
  - transactions

every time they provided ZEnvironment's cache got invalidated.

**Comment by adamgfraser** [comment]
Local capabilities such as `Scope` may require `provideSomeEnvironment` but this shouldn't be an issue as long as you are constructing services idiomatically.

**Comment by darl** [comment]
I created simple app with idiomatic service that creates new scope in a loop
https://github.com/darl/zio2-example/commit/c8ea34c76f713c93f19c8e613c8f4a50f1c49a8e

Time per cycle scales with count of services in environment.

`ZEnvironment.get` is biggest span in flame-graph.
![Screenshot 2022-09-22 at 21 56 20](https://user-images.githubusercontent.com/423802/191829043-6158df23-41ac-4521-9218-1a30f6b1ac82.png)


I think `LightTypeTag.<:<` requires some kind of caching.
Do you mind if i submit PR?

**Comment by adamgfraser** [comment]
Let me take a look.
