### ISSUE TITLE
ZChannel.pipeToOrFail can mix up errors

### ISSUE THREAD

**Issue by Marc-Ducret** [zio/zio#7381]
Using the latest snapshot `2.0.2+71-ba4565a2-SNAPSHOT`, nested calls to ZChannel.pipeToOrFail can mix up errors and even propagate errors that does not respect the compile time types.

In the following example that only uses the high level interface of ZStream and ZSink, the issue happens because `ZStream.run` and `ZSink.contramapZIO` both call `ZChannel.pipeToOrFail`.
```scala
import zio._
import zio.stream._
import zio.test._

object SinkErrorSpec extends ZIOSpecDefault {

  def spec =
    suite("ZSink Specification") {
      test("Failures propagation") {
        assertZIO(
          ZStream
            .fail(ErrorStream)
            .mapError(_ => ErrorMapped)
            .run(
              ZSink
                .drain
                .contramapZIO { (a: Any) => ZIO.attempt(a) }
                .mapError { (e: Any) => ErrorSink }
            )
            .exit
        )(
          Assertion.fails(
            Assertion.isSubtype[ErrorMapped.type](
              Assertion.equalTo(ErrorMapped)
            )
          )
        )
      }
    }

  private case object ErrorStream
  private case object ErrorMapped
  private case object ErrorSink

}

```

Results in:
```
+ ZSink Specification
  - Failures propagation
    ✗ ErrorSink$ is not an instance of ErrorMapped$
```

And replacing `.mapError { (e: Any) => ErrorSink }` with `.mapError { _ => ErrorSink }` produces a `ClassCastException`:
```
+ ZSink Specification
  - Failures propagation
    ✗ Exit.Failure did not contain a Cause.Fail
    <CODE>
    input = Failure(
      cause = Die(
        value = java.lang.ClassCastException: class SinkErrorSpec$ErrorMapped$ cannot be cast to class java.lang.Throwable (SinkErrorSpec$ErrorMapped$ is in unnamed module of loader 'app'; java.lang.Throwable is in module java.base of loader 'bootstrap'),
        trace = StackTrace(
          fiberId = None(),
          stackTrace = Chunk()
        )
      )
    )
 ```

**Comment by adamgfraser** [comment]
@Marc-Ducret Thanks for reporting! Will take a look.

**Comment by Marc-Ducret** [comment]
> @Marc-Ducret Thanks for reporting! Will take a look.

@adamgfraser Thanks! I think this PR https://github.com/zio/zio/pull/7382 is the right direction to fix the issue.

**Comment by adamgfraser** [comment]
@Marc-Ducret Yes great diagnosis! I think we can take advantage of reference equality to make sure the `ChannelFailure` we are unpacking is the same one we created without having to deal with tokens but similar idea.
