### ISSUE TITLE
`zio.Trace`: Store className and method name in different fields

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7408]
Situation:
----
`zio.Trace` stores the classname and method name concatinated as one string in the location field. 

Problem:
---
Loggers like e.g. zio-logging-slf4j have to break this up again **for every logline written**, which is quite wasteful, e.g.
https://github.com/zio/zio-logging/blob/master/slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala#L55

Proposition:
---
It would be great if we could have the classname and method name in distinct fields, kind of like the Java StackTraceElement does it. 

Side effects:
---
This is probably a source incompatible breaking change, so maybe we could plan this for ZIO 2.1.x ?

**Comment by adamgfraser** [comment]
A `Trace` just is a `String` which is itself a performance optimization to avoid additional allocations for each trace. Extracting the method name when necessary is quite cheap and is a cost that is only paid in certain cases where it is small relative to the cost of generating the trace, whereas a change to the representation of `Trace` would impact all applications. So I don't think this change makes sense.

**Comment by adamgfraser** [comment]
Going to close this as I do not think it is actionable for the reasons discussed above.
