### ISSUE TITLE
isEmpty/isFull clarification

### ISSUE THREAD

**Issue by gurghet** [zio/zio#7413]
Regarding the file https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/Enqueue.scala
isEmpty/isFull are implemented in terms of size.
```scala
def isEmpty(implicit trace: Trace): UIO[Boolean] =
  size.map(_ == 0)

def isFull(implicit trace: Trace): UIO[Boolean] =
  size.map(_ == capacity)
```
However, the method names are contradicted by the immediately above scaladoc of `size`:
```scala
/**
 * Retrieves the size of the queue, which is equal to the number of elements
 * in the queue. This may be negative if fibers are suspended waiting for
 * elements to be added to the queue. It may be greater than the capacity if
 * fibers are suspended waiting for elements to be removed from the queue.
 */
```
So the queue might be empty even if `isEmpty` returns `false` and it might be full even if `isFull` returns `false`. That should happens precisely when fibers are waiting for elements to be added/removed.
Is this intended?
> As a minor point, the paragraph starts by saying that the size of the queue is equal to the number of elements in the queue, which is also false.

**Comment by adamgfraser** [comment]
@gurghet Thanks for reporting! Will take a look!
