### ISSUE TITLE
Proper design for Encoders/Decoders

### ISSUE THREAD

**Issue by carlos-verdes** [zio/zio#7417]
I'm writing a client for a protocol that has different types of Encoders/Decoders so I need to abstract over them when writing my service trait, something like this:

```scala
trait Client[Encoder[_], Decoder[_]]:

  def command[I: Encoder, O: Decoder](message: Message[I]): IO[Error, Message[O]]
```

Then I have an implementation with JsonCodecs with something like this:
```scala
trait ClientHttpJson extends Client[JsonEncoder, JsonDecoder]
```

Now the first problem is I can't define in my Client object the method callers (and even if I'm able to fix this compilation issue, the code is really difficult to read):
```scala
object Client:
// this doesn't compile
  def command[I, Encoder[_], O, Decoder[_]](
      message: Message[I])(
      using Encoder[I], Decoder[O]
  ): ZIO[Client[Encoder, Decoder], Error, Message[O]] =
    ZIO.serviceWithZIO[Client[Encoder, Decoder]](_.command(message))
``` 

Compilation error:
```sh
[error] 38 |    ZIO.serviceWithZIO[Client[Encoder, Decoder]](_.command(message))
[error]    |                                                                    ^
[error]    |                                 Cannot find implicit Tag[Encoder]
```

Is there a better approach to design this?
The problem of abstracting over Encoders/Decoders (or SerDe) is really common when writing API's and IPC.

I'm not sure if this is related with #6829:
https://github.com/zio/zio/issues/6829

**Comment by carlos-verdes** [comment]
I think we can close, thanks @dashkose for pointing into right direction:
https://zio.dev/reference/service-pattern/defining-polymorphic-services-in-zio/

The main point is to add `TagK` for Encoder and Decoder (K is needed for kinder types)

**Comment by plokhotnyuk** [comment]
@carlos-verdes Beware that instantiation of `izumi.reflect.Tag` instances is quite expensive, so they should be cached somewhere on the caller side.

**Comment by carlos-verdes** [comment]
How should I implement this in a more effective way then @plokhotnyuk

**Comment by plokhotnyuk** [comment]
Best approach is starting from profiling of running service using performance tests.

For caching you can define an object with implicit vals for `TagK` instances and then import it in your implementation of services.

**Comment by carlos-verdes** [comment]
I have this in the JsonClient:
```scala

object Client:
  def command[Encoder[_]: TagK, Decoder[_]: TagK, I: Encoder : Tag , O: Decoder : Tag](
      message: Message[I])
  : ZIO[Client[Encoder, Decoder], Error, Message[O]] =
    ZIO.serviceWithZIO[Client[Encoder, Decoder]](_.command(message))

import zio.*
import zio.json.*

trait JsonClient extends Client[JsonEncoder, JsonDecoder]

object JsonClient:

  def command[I: JsonEncoder, O: JsonDecoder](
      message: Message[I])
  : ZIO[Client[JSonEncoder, JsonDecoder], Error, Message[O]] =
    Client.command(message)
