### ISSUE TITLE
Composing more than two ZIOApp:s via ZIOApp.Proxy stops propagating interruptions as expected

### ISSUE THREAD

**Issue by frekw** [zio/zio#7424]
Finally managed to track this one down. :)

See this [scastie](https://scastie.scala-lang.org/WRyUg6hWRPOy7bSiaqKHCQ).

Is we compose two apps, interruption works as intended, but if we add a third one we end up in a state where the application doesn't exit on error.

**Comment by frekw** [comment]
This might actually be an even more minimal reproducer of what's going on:

```scala
    ZIO.never.onInterrupt(ZIO.debug("exit 1")) <&>
      ZIO.never.onInterrupt(ZIO.debug("exit 2")) <&>
      ZIO.fail("booom").onInterrupt(ZIO.debug("exit 3"))
```

never exits, but this does:

```scala
    ZIO.never.onInterrupt(ZIO.debug("exit 1")) <&>
      ZIO.fail("booom").onInterrupt(ZIO.debug("exit 2"))
```

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!

**Comment by frekw** [comment]
@adamgfraser just FYI: I tried to do some digging. We do end up in the right case, but this [`interruptAs`](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L2460) call doesn't seem to actually interrupt the fiber.

Removing this [`ZIO.uninterruptibleMask`](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L2470) fixes that (but breaks other things, as is probably expected). 

After that I got somewhat stuck in the ZIO internals, but would be happy to keep digging if it's helpful!

**Comment by adamgfraser** [comment]
@frekw No worries. Will push something up soon.
