### ISSUE TITLE
ZIO hackathon September 21-22

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#743]
I'm planning a ZIO hackathon weekend on September 21-22 (possibly preceded by a day of informal talks), open to everyone—regardless of level, experience, or contributions to OSS, and of course, contributors to Cats Effect, Monix, or related ecosystems are welcome too!

Tentatively planning to hold this in Warsaw, Poland, as it's easy and cheap to get to from Europe, and most ZIO contributors are already located somewhere in Europe.

My current idea:

 - If you are a ZIO contributor, I'll pay for your lodging and try to find sponsors for food
 - If you aren't a ZIO contributor, then please come too—you can find lodging nearby or stay (at cost) wherever contributors stay

I think this could be a lot of fun and result in great networking opportunities, as well as brainstorming and useful contributions to the broader ecosystem.

What do folks think of this idea? And would you be able to make it???

**Comment by LGLO** [comment]
Idea is great!
I'll to make it, I'll take care for myself in regards of food and lodging.
The only problem is level of wifecoins, but it should be high again after vacations.

I think we need to organize place to code and reliable network there to have max productivity for these few days.

**Comment by jdegoes** [comment]
@LGLO Time to invest now! 😉 

Agreed on the place and network, have some volunteers to help with that side of things...

**Comment by xplosunn** [comment]
I'm not really a contributor, but I would attend.

**Comment by adilakhter** [comment]
I would like to attend!

**Comment by szymonm** [comment]
Not a contributor, but I would like to attend and can help with organization (I'm from Warsaw).

**Comment by wi101** [comment]
I will attend!

**Comment by NeQuissimus** [comment]
Love the idea. Won't be able to attend but we should collect some ideas for what to work on ahead of time and I'll leave feedback there.

**Comment by iravid** [comment]
I’m in!

**Comment by kamilkloch** [comment]
Great idea. I would love to come. Depends on the exact September date though. Non-contributor status thus far.

**Comment by Avasil** [comment]
You mentioned `Cats-Effect` on Twitter. If it's Warsaw I can 99% come on behalf of Monix or even just help with ZIO. I want to support brilliant idea!

**Comment by jdegoes** [comment]
@avasil That would be fantastic! Would love to have you there.

**Comment by regiskuckaertz** [comment]
wow, that's very generous and such an exciting idea! I'm in and keen to help with the setup in any way I can.

**Comment by ratoshniuk** [comment]
I would like to attend, would be funny:)

**Comment by Cereopsis** [comment]
I’ve never been to Poland. This could fix that.

**Comment by lbialy** [comment]
More VirtusLabers incoming, expect me too :smile: Can take care of both lodging and food for myself :+1:

**Comment by ghostdogpr** [comment]
Ok, if you’re all going to be there, I HAVE to make it!

**Comment by mijicd** [comment]
I love the idea, see you all there!

**Comment by mschuwalow** [comment]
Sounds like a great idea. I'll be there too.

**Comment by softinio** [comment]
I need to convince you to run one here in the Bay Area :-) Love the idea.

**Comment by jdegoes** [comment]
@softinio Sure, just convince more bay area engineers to contribute to ZIO. 😉

**Comment by ioleo** [comment]
I'll be there :)

**Comment by mmuschalik** [comment]
Make sure to send a personal invite to Mr. Ordersky :) . Effects made it on the list on https://dotty.epfl.ch/ but I'm certain won't make scala 3.0. If effects become more integrated into the language, I want to know how. Can it be done in a way that perhaps can still work on top of effect monads provided by libraries such as ZIO.

**Comment by dnaumenko** [comment]
I would like to attend!

**Comment by FrancoAra** [comment]
I will be there together with @adilakhter and probably with Assen Kolov

**Comment by cloudmark** [comment]
@jdegoes not a contributor but will attend!

**Comment by ang-mic** [comment]
I am not a contributor but I would like to be part of it :)

**Comment by runtologist** [comment]
I love the idea! I'll try to be there.

**Comment by mgibowski** [comment]
Awesome, I'll be happy to join this gathering! :)

**Comment by fakirAyoub** [comment]
Definitely in! Thanks for the organization @jdegoes, and please ask for any help you would need!

**Comment by smart-ass** [comment]
I'd like to join.

**Comment by dag2ww** [comment]
I'm not a contributor (yet :) ) - going to be there :)

**Comment by jdegoes** [comment]
Registration is [now open](https://www.eventbrite.com/e/zio-hackathon-2019-warsaw-edition-tickets-63933603128)!!!

![giphy](https://user-images.githubusercontent.com/156745/59890629-01b8b780-938f-11e9-8fdc-ba6f32db1eeb.gif)

**Comment by LukaszByczynski** [comment]
I going to be with a few friends from my company.
