### ISSUE TITLE
stacktrace loop failure when starting application

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7438]
I'm in the process of migrating our last microservice from zio 1 to zio 2... unfortunatelly, its also the biggest one and has lots of moving parts/layers. 

For some reason, very often the app crashes right at the start with kind of a endless interruption loop 
![grafik](https://user-images.githubusercontent.com/100349/196302445-2afe11d0-0e7d-45f2-bced-18c521734f88.png)
![grafik](https://user-images.githubusercontent.com/100349/196302456-8f07f92d-1cda-496f-bd6c-059b8da5bd28.png)
![grafik](https://user-images.githubusercontent.com/100349/196302479-d98e762a-6139-4238-ba62-928b2c902baa.png)
... 5 screenshots skipped .. 
![grafik](https://user-images.githubusercontent.com/100349/196302494-8a3ad241-508a-41e0-acfd-08aba22d7607.png)

The only meaningful thing that gets logged out in the beginning is 
```
[info] timestamp=2022-10-17T23:28:49.234685Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-69,14,93,9,77,103,95,43,99,23,15,6,85,21,33" java.lang.InterruptedException: Interrupted by thread "zio-fiber-99"
```

however, I'm unable to figure out what thread `zio-fiber-99` is and why its interrupting. 

it would be very helpful to get the information about where the fiber was forked or which `SourceLocation` actually started the interruption, so I can figure out whats the problem. afaik we should have both informations available at runtime. 

zio-version 2.0.2 is used in this service.

**Comment by adamgfraser** [comment]
@domdorn Can you try on the latest ZIO snapshot?

**Comment by domdorn** [comment]
@adamgfraser do you have a link at hand how to configure using zio snapshots in sbt? haven't found anything on google and zio.dev ( i had this once in a service, but can't find it anymore). will try then first thing in the morning (its 2am already here)

**Comment by adamgfraser** [comment]
@domdorn You just need to add the Sonatype snapshot resolver and use a ZIO snapshot version. Here is an example:

https://github.com/zio/zio-http/pull/1493/commits/3ea80917bf283668e19d7e313a0496df1a76a468

**Comment by domdorn** [comment]
Its not failing anymore with 2.0.2+97-fdf17fd9-SNAPSHOT ! ❤️ 🎉 
would it be possible to get a release? I cant merge the migration with a snapshot dependency.

**Comment by domdorn** [comment]
it looks like something changed in the `ZIOSpecAbstract` class..  I'm now getting an error like this when trying to compile my tests
```
[error] /Users/domdorn/acme/masterdata-service/masterdata-web-hooks/src/test/scala/com/acme/viopt/masterdata/hooks/HooksIntegrationSpec.scala:22:8: incompatible type in overriding
[error] def bootstrap: zio.ZLayer[Any,Any,com.acmeviopt.masterdata.hooks.HooksIntegrationSpec.Environment] (defined in class ZIOSpecAbstract)
[error]   with override val bootstrap: zio.ZLayer[zio.Scope,Any,zio.test.akkahttp.RouteTestEnvironment.TestEnvironment with zio.test.TestEnvironment] (defined in trait AkkaZIOSpecDefault);
[error]  found   : zio.ZLayer[zio.Scope,Any,zio.test.akkahttp.RouteTestEnvironment.TestEnvironment with zio.test.TestEnvironment]
[error]     (which expands to)  zio.ZLayer[zio.Scope,Any,akka.actor.ActorSystem with akka.stream.Materializer with zio.test.akkahttp.RouteTest.Config with zio.test.Annotations with zio.test.Live with zio.test.Sized with zio.test.TestConfig]
[error]  required: zio.ZLayer[Any,Any,com.acme.viopt.masterdata.hooks.HooksIntegrationSpec.Environment]
[error]     (which expands to)  zio.ZLayer[Any,Any,akka.actor.ActorSystem with akka.stream.Materializer with zio.test.akkahttp.RouteTest.Config with zio.test.Annotations with zio.test.Live with zio.test.Sized with zio.test.TestConfig]
[error] object HooksIntegrationSpec extends AkkaZIOSpecDefault {
[error]        ^
[error] one error found
```

I checked out the repo of the test-lib ( https://github.com/senia-psm/zio-test-akka-http ) and updated the zio version to the above mentioned snapshot and I'm getting this compile error when trying to compile the lib:

```
sbt:zio-test-akka-http> test
[info] compiling 8 Scala sources to /Users/domdorn/acme/zio-test-akka-http/target/scala-2.13/classes ...
[error] /Users/domdorn/acme/zio-test-akka-http/src/main/scala/zio/test/akkahttp/AkkaZIOSpecDefault.scala:8:16: incompatible type in overriding
[error] def bootstrap: zio.ZLayer[Any,Any,AkkaZIOSpecDefault.this.Environment] (defined in class ZIOSpecAbstract);
[error]  found   : zio.ZLayer[zio.Scope,Any,zio.test.akkahttp.RouteTestEnvironment.TestEnvironment with zio.test.TestEnvironment]
[error]     (which expands to)  zio.ZLayer[zio.Scope,Any,akka.actor.ActorSystem with akka.stream.Materializer with zio.test.akkahttp.RouteTest.Config with zio.test.Annotations with zio.test.Live with zio.test.Sized with zio.test.TestConfig]
[error]  required: zio.ZLayer[Any,Any,AkkaZIOSpecDefault.this.Environment]
[error]     (which expands to)  zio.ZLayer[Any,Any,akka.actor.ActorSystem with akka.stream.Materializer with zio.test.akkahttp.RouteTest.Config with zio.test.Annotations with zio.test.Live with zio.test.Sized with zio.test.TestConfig]
[error]   override val bootstrap: ZLayer[Scope, Any, RouteTestEnvironment.TestEnvironment with TestEnvironment] =
[error]                ^
[info] zio.ZLayer[zio.Scope,Any,zio.test.akkahttp.RouteTestEnvironment.TestEnvironment with zio.test.TestEnvironment] <: zio.ZLayer[Any,Any,AkkaZIOSpecDefault.this.Environment]?
[info] false
[info] zio.ZLayer[zio.Scope,Any,zio.test.akkahttp.RouteTestEnvironment.TestEnvironment with zio.test.TestEnvironment] <: zio.ZLayer[zio.ZIOAppArgs,Any,AkkaZIOSpecDefault.this.Environment]?
[info] false
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 4 s, completed 18 Oct 2022, 13:34:08

```

**Comment by domdorn** [comment]
I created a PR in the other project https://github.com/senia-psm/zio-test-akka-http/pull/173

**Comment by domdorn** [comment]
Ok, other project updated its lib :-) team agreed to run on the `2.0.2+97-fdf17fd9-SNAPSHOT` for a while, would still be awesome to get a zio 2.0.3 in the coming weeks (another one of our services shows similar behaviour on startup)!

**Comment by adamgfraser** [comment]
Working on it!
