### ISSUE TITLE
tests always returns exitcode=0

### ISSUE THREAD

**Issue by cobr123** [zio/zio#7440]
I have example project https://github.com/cobr123/matrix-rain
After `sbt nativeImageRunTest` or `./target/native-image/matrix-rain-0.7-with-tests-native` I check `echo $? ` and it shows 0 no matter there is some failed tests.

**Comment by adamgfraser** [comment]
@swoogles You want to take a look at this?

**Comment by swoogles** [comment]
Yep, will do

**Comment by dacr** [comment]
I confirm the issue, wanted to write the same issue, but you did it before me :) It happens with ZIO 2.0.2

**Comment by cobr123** [comment]
looks like adding 
```scala
      _ <- ZIO.when(summary.status == Summary.Failure) {
        ZIO.fail(new RuntimeException())
      }
```
to [zio.test.ZIOSpecAbstract#runSpec](https://github.com/zio/zio/blob/40bc3f2fb42dc52dbf768225529dc2681cc3a1f2/test/shared/src/main/scala/zio/test/ZIOSpecAbstract.scala#L71) can fix it

**Comment by hmemcpy** [comment]
Sorry to bump this very old issue. I just tried running a ZIO 2.0 test, and I'm getting the runtime failure message in my test output:

So for a simple:
```scala
object MySpec extends ZIOSpecDefault {
  override def spec: Spec[TestEnvironment with Scope, Any] =
    suiteAll("test") {
      test("Hello") {
        assertTrue(false)
      }
    }
}
```

I'm getting:
```
timestamp=2023-07-04T12:16:51.153236Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-22" java.lang.RuntimeException: null
	at zio.test.ZIOSpecAbstract.$anonfun$runSpec$11(ZIOSpecAbstract.scala:79)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3146)
	at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)"

Process finished with exit code 1

Assertion failed:
  ✗ Result was false
  false
  at /<path>/RegexSpec.scala:12 
```

Running with the IntelliJ runner, the error is rendered above the assertion output.
Could this have been solved by returning an ExitCode 1 rather than failing with a runtime exception?
