### ISSUE TITLE
ZIO Test: ZTestJUnitRunner : wrong total count and rendering issues

### ISSUE THREAD

**Issue by dacr** [zio/zio#7450]
ZIO 2.0.2

Invalid total test count reported by the **ZTestJUnitRunner** : Ignored tests are counted twice.

Minimal Reproducer : 
```
import zio.test.*
import zio.test.TestAspect.*
import org.junit.runner.RunWith

@RunWith(classOf[zio.test.junit.ZTestJUnitRunner])
class MainSpec extends ZIOSpecDefault {

  val junitRunnerMinimalSuite =
    suite("Z")(
      test("A")(assertTrue(true)),
      test("B")(assertTrue(true)) @@ ignore
    )

  override def spec = junitRunnerMinimalSuite
}
```

![image](https://user-images.githubusercontent.com/381901/197238003-8a869904-58d1-44c6-a587-5dc06601f676.png)

B appears as ignored and as tested with success; the total count is 3 and the suite name is dumped after the tests it contains have been dumped.

**Comment by dacr** [comment]
Of course with the ZIO console renderer everything is fine :
```
+ Z
  + A
  - B - ignored: 1
1 tests passed. 0 tests failed. 1 tests ignored.
```

**Comment by dacr** [comment]
Same issue if we extends `MainSpec` with `JUnitRunnableSpec` instead of using the `RunWith` annotation.
![image](https://user-images.githubusercontent.com/381901/197241124-efccfedc-8ffc-442b-b20a-201f17bfedbc.png)

**Comment by swoogles** [comment]
@hmemcpy it seems like this is an Intellij Renderer issue. Do you have any bandwidth for it?

**Comment by hmemcpy** [comment]
I could take a look, however, IntelliJ handles the rendering of junit output on its own. It would be helpful to see the JUnit XML output produced by this spec.

**Comment by dacr** [comment]
OK I just tested using just `sbt test` and with the `"com.github.sbt" % "junit-interface"     % "0.13.2"     % Test`  lib and there is no issue :

```
+ Z
  - B - ignored: 1
  + A
[info] Test run test.scala.fr.janalyse.ziotests.MainSpec started
[info] Test test.scala.fr.janalyse.ziotests.MainSpec.B started
[info] Test test.scala.fr.janalyse.ziotests.MainSpec.A started
[info] Test test.scala.fr.janalyse.ziotests.MainSpec.B ignored
[info] Test run test.scala.fr.janalyse.ziotests.MainSpec finished: 0 failed, 1 ignored, 1 total, 0.298s
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1, Ignored 1
```

So you're right it is probably an intellij Renderer issue.

**Comment by hmemcpy** [comment]
Cheers. I'm poking around ZIO test running anyway, so I'll take a look at this soon, see if I can fix this!

**Comment by hmemcpy** [comment]
Preliminary findings!

This is the output of the test runner that IntelliJ is parsing and turning into the tree representation. I think it's too chatty, there are some extra lines in the output (`suiteTreeNode` for example) which I don't recognize and I suspect cause the rendering issues.

The current point of origin is the `ZTestJUnitRunner#instrumentSpec` function, need to spend some time with it...

```
##teamcity[enteredTheMatrix]
##teamcity[suiteTreeStarted name='Z' locationHint='java:suite://Z']
##teamcity[suiteTreeNode name='HelloWorld.A' locationHint='java:test://HelloWorld/A']
##teamcity[suiteTreeNode name='HelloWorld.B' locationHint='java:test://HelloWorld/B']
##teamcity[suiteTreeEnded name='Z']
##teamcity[treeEnded]
##teamcity[rootName name = 'HelloWorld' location = 'java:suite://HelloWorld']
##teamcity[testSuiteStarted name='Z' locationHint='java:suite://Z']
##teamcity[testStarted name='HelloWorld.B' locationHint='java:test://HelloWorld/B']
##teamcity[testIgnored name='HelloWorld.B']
##teamcity[testFinished name='HelloWorld.B' duration='2']
##teamcity[testStarted name='HelloWorld.A' locationHint='java:test://HelloWorld/A']
##teamcity[testFinished name='HelloWorld.A']
##teamcity[testSuiteFinished name='Z']
##teamcity[testStarted name='HelloWorld.B' locationHint='java:test://HelloWorld/B']
##teamcity[testFinished name='HelloWorld.B']
```

**Comment by adamgfraser** [comment]
@hmemcpy Awesome!

**Comment by hmemcpy** [comment]
Found the culprit! This PR should fix it.
