### ISSUE TITLE
ZIO2 Update Docs ZMX, Metrics & zio-metrics-connectors

### ISSUE THREAD

**Issue by ianlintner** [zio/zio#7458]
As a consumer of ZIO & ZMX upgrading to ZIO 2 the changes to ZMX Metrics and the inclusion of core left an unclear migration path.

Potential Acceptance
* Update/Replace ZMX docs in ZIO or Notes about the change.
  * ZMX documentation in ZIO2 docs is still version 1 examples: https://zio.dev/ecosystem/officials/zio-zmx
  * Replace with link to [https://github.com/zio/zio-metrics-connectors publishers.](https://zio.dev/guides/tutorials/monitor-a-zio-application-using-zio-built-in-metric-system)

Details:
It appears ZMX Metrics integrated into core https://github.com/zio/zio/pull/5498 and the publishing was split into a new repo: https://github.com/zio/zio-metrics-connectors

https://zio.dev/guides/tutorials/monitor-a-zio-application-using-zio-built-in-metric-system

**Comment by adamgfraser** [comment]
@ianlintner Thanks for raising the issue and for your PR! I asked @khajavi to review.

**Comment by ianlintner** [comment]
Docs are updated online.
