### ISSUE TITLE
Bug: Stream stops/interupts early when using interruptWhen(Promise)

### ISSUE THREAD

**Issue by valentin-panalyt** [zio/zio#7460]
After migrating from ZIO 1 to ZIO 2.0.2, I found a problem with a background process.

```
    ZIO
      .acquireRelease {
        for {
          stop <- Promise.make[..., Unit]
          stream1 = ... 
          stream2 = ...
          combined = stream1.merge(stream2).tap(_ => ZIO.succeed(println("foo"))).interruptWhen(stop)
          _ <- combined.runDrain.forkDaemon
        } yield stop
      }{ stopRefresh => ZIO.succeed(println("stopping")) *> stopRefresh.succeed(()) }
```

I have two streams that I merge and run forever in background until some condition is met. (I'm essentially creating a stream which's lifetime I control through `Scope` - I couldn't find a better way to control the streams lifetime).

This worked before, but after ZIO 2 the stream doesn't start at all. Normally the streams run every 10 seconds.

I then changed this (using `ZStream.mergeAllUnbounded`) to

```
    ZIO
      .acquireRelease {
        for {
          stop <- Promise.make[..., Unit]
          stream1 = ... 
          stream2 = ...
          combined = ZStream.mergeAllUnbounded()(stream1, stream2).tap(_ => ZIO.succeed(println("foo"))).interruptWhen(stop)
          _ <- combined.runDrain.forkDaemon
        } yield stop
      }{ stopRefresh => ZIO.succeed(println("stopping")) *> stopRefresh.succeed(()) }
```

This made "foo" being printed only once. I then removed the `.interruptWhen(stop)` part and then everything worked as before, except that the stream just ran forever as expected. I can also confirm that the resource is not closed early because I can see it closing with printing "stopping" when it should really happen, so there can't be early scope consumption.

**Comment by adamgfraser** [comment]
Yeah there is definitely something off here. Thanks for reporting!

**Comment by valentin-panalyt** [comment]
I'm very pleased to see such a quick fix and release 👏
