### ISSUE TITLE
Equality assertion for Long and Int fails to compile

### ISSUE THREAD

**Issue by myazinn** [zio/zio#7461]
Example
```scala
import zio.test._
import zio.test.Assertion._

object MyZioSpec extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("sweet") {
      test("test") {
        val int: Int = 1
        val long: Long = int
        assert(long)(equalTo(int))
      }
    }
}
```
Compilation of the snippet above fails with the following error
```
This operation assumes that values of types Long and Int could potentially be equal. However, Long and Int are unrelated types, so they cannot be equal.
```
But they _can_.
If we change
```scala
assert(long)(equalTo(int))
```
to 
```scala
assertTrue(long == int)
```
then if also fails, but if we do this
```scala
val bool = long == int
assertTrue(bool)
```
then it passes.
I'm not sure what's the best way to fix this, I tried using `<:<` evidence, but it didn't work either. It is possible to just provide all the required pairs manually (e.g. `Eql[Int, Long]`, `Eql[Long, Int]`, `Eql[Byte, Int]`, `Eql[Double, Long]`, etc), but it looks too laborious. So maybe someone else will found a more elegant way to handle such cases.

I know that it can be easily fixed at calling side with the trick above or with `.toInt` / `toLong` conversions or with `L` / `f` literals, but it just feels awkward.

**Comment by adamgfraser** [comment]
This type of implicit numeric widening is normally considered a wart so I am not sure if it is something we want to support. You can easily compare the same numeric type and this can help prevent bugs where you are comparing things that don't make sense.

**Comment by narma** [comment]
I think current behaviour is much better than implicit numeric widening, type safety for the win.

Also scalatest with `must` matchers with triple equals (which I only use in case of using scalatest) doesn't allow such behaviour too.
<img width="317" alt="изображение" src="https://user-images.githubusercontent.com/91045/198276343-40814c0f-e786-4383-8833-6f6f5d532029.png">

**Comment by myazinn** [comment]
All right then, keep your types
