### ISSUE TITLE
Enhance test suite for ConfigProvider.fromMap

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7464]
`Config` and `ConfigProvider` are two new additions designed to bring a configuration front-end to ZIO 2.0.

In order to prepare release, we should develop a comprehensive test suite for `ConfigProvider.fromMap`, which is a developer-mode configuration provider that attempts to load configuration information from a map.

The code can be found inside `ConfigProvider.scala`, and the existing spec enhanced with many more tests to cover happy and unhappy paths, for common config types like primitives, collections, and tables.

**Comment by beneyal** [comment]
I would like to tackle this issue for the Hackathon 🙂

**Comment by swoogles** [comment]
@beneyal go for it!

**Comment by adamgfraser** [comment]
@beneyal Great!

**Comment by beneyal** [comment]
Taken care of in #7473 :slightly_smiling_face:
