### ISSUE TITLE
ZStream.mapZIO should preserve chunk size?

### ISSUE THREAD

**Issue by hindog** [zio/zio#7475]
When `mapZIO` is called on a `ZStream`, existing chunk size is not preserved.  Should the desired behavior be to preserve chunking when operating on individual elements in the stream?  In our case, we are using `ZStream.tap` (which utilizes `mapZIO`) to capture some metrics/logging, but we don't want to lose the upstream chunking when doing so.

Example:

```
import zio._
import zio.stream._

object ZIOStreamChunkExample extends ZIOAppDefault {
  override def run = {
    ZStream.fromChunk(Chunk(1, 2, 3)).runForeachChunk { chunk =>
      ZIO.logInfo(s"Chunk size (without tap): ${chunk.size}")
    } *>
      ZStream.fromChunk(Chunk(1, 2, 3)).tap(_ => ZIO.unit).runForeachChunk { chunk =>
        ZIO.logInfo(s"Chunk size (with tap): ${chunk.size}")
      }
  }
}
```

**Comment by adamgfraser** [comment]
@hindog It is not safe to preserve chunking in `mapZIO`. For example, the function `f` might take significant time to execute and the downstream might only want to take a limited number of elements or might take some further action based on an intermediate item. For efficiency in this case you can use `mapChunksZIO`.

**Comment by hindog** [comment]
@adamgfraser yeah that does make sense.  Do you feel the same way about `tap`?  I suppose `tap` could take significant time as well, but the "further action based on an intermediate item" use-case wouldn't apply to `tap`, correct?

**Comment by adamgfraser** [comment]
@hindog It definitely does. The evaluation of the `tap` for an earlier item could interrupt the entire stream or signal that fewer items need to be processed.

**Comment by hindog** [comment]
Ahh right, I was interpreting that differently (interpreting the mapped stream vs some signal sent via `.interrupt`/`Ref`/`Promise`/etc).  So I guess what I'd be looking for is something like `tapChunks`.  Easy enough to add an extension method on my end, or do you feel like that might be handy to have as part of the core API? (if so I can try to create a PR for it)

**Comment by adamgfraser** [comment]
We've been trying to avoid creating more chunk variants. You can already use `chunksWith` to perform an operator with the funk structure of the stream exposed so I think that is probably the way to go.
