### ISSUE TITLE
Console ZIO app built with `native-image` hangs when `Ctrl+C` is pressed

### ISSUE THREAD

**Issue by nartamonov** [zio/zio#7494]
### How to reproduce

1. Build the following app with Graal `native-image`:
```scala
object Main extends ZIOAppDefault {
  override def run: ZIO[ZIOAppArgs & Scope, Any, Any] = {
    Console.printLine("Started!") *> ZIO.sleep(1.seconds).forever
  }
}
```
2. Run it in console.
3. Press `Ctrl+C`

*Expected result*: program exits.

*Actual result*: program prints fiber dumps but does not exit. When `Ctrl+C` is pressed again, it prints fiber dumps again but doesn't exit.

### Possible causes

This issue could be affected by #5185.

### Test environment

* ZIO 2.0.3
* Windows 10
* GraalVM 22.3.0 Java 17 CE
* Java 17.0.5+8-LTS
* C compiler: cl.exe (microsoft, x64, 19.31.31107)

**Comment by zynque** [comment]
I'm experiencing the same behavior (program fiber errors are logged, but program does not exit). In my case it is an ordinary Scala app running in sbt on Windows.

ZIO 2.0.4
Scala 2.12
Windows 10
Java ZULU JDK 11

I tested with the App posted by nartamonov, and I continue to see the same behavior described.

**Comment by rudolfduplessis** [comment]
I'm having the same issue. Windows as well.
I did a little test and commented line 104 in ZIOApp:
`        if (System.os.isWindows) {
          //Platform.addSignalHandler("INT", dumpFibers)(Unsafe.unsafe)
          ()
        } else...
`
And then it shuts down as expected, my scope finalizers run, the works....
So its as if the signal handler (sun.misc.Signal in PlatformSpecific.addSignalHandler) takes the INT signal and then the JVM considers it handled, so the shutdown hook(s) is never called?
So I don't know how you want to handle this. Thought a problem identified is one half solved at least.
I'll be glad to make a pull request if you just want to remove that line 'cause this is quite annoying.

**Comment by rudolfduplessis** [comment]
@adamgfraser Thanks! Gave it a try just now and can say it works for me.

**Comment by adamgfraser** [comment]
@rudolfduplessis Awesome!
