### ISSUE TITLE
`ZIO#resurrect` and `ZIO#absorb` do not conform with documentation

### ISSUE THREAD

**Issue by rod1n** [zio/zio#7525]
```scala
val effect: Task[Unit] = ZIO.fail(new Exception())
  .orDie
  .resurrect
```
Documentation says that this should work, but it doesn't because of restriction the `E IsSubtypeOfError Throwable`. Same for `absorb`.

**Comment by adamgfraser** [comment]
@rod1n The code above compiles as written.

**Comment by rod1n** [comment]
Sorry, it's IDE 🤦🏻‍♂️
