### ISSUE TITLE
Failing to compile when using the error channel with `suiteAll`

### ISSUE THREAD

**Issue by ncreep** [zio/zio#7530]
Hi,

I seem to have stumbled on a typing bug when using `suiteAll`.
Consider the following the test:
```scala
def spec = suiteAll("a") {
  test("b") {
    ZIO.fail(new Exception).as(assertCompletes)
  }
}
```

Trying to compile this with ZIO `2.0.3` and Scala `2.13.4` I get the following error:
```scala
... type mismatch;
[error]  found   : zio.test.Spec[Any,Exception]
[error]  required: zio.test.Spec[Any,Nothing]
[error]     test("b") {
[error]         ^
[error] one error found
```

While the same test written with `suite` compiles just fine:
```scala
def spec = suite("c") {
  test("a") {
    ZIO.fail(new Exception).as(assertCompletes)
  }
}
```

Adding an `orDie` to the first test will also make it compile, but seems a bit cumbersome.

A quick look at the `specAll` macro suggests [this](https://github.com/zio/zio/blob/cdbd86d4b23b3bd433b08c0ff534742141582977/test/shared/src/main/scala-2/zio/test/SmartSpecMacros.scala#L61) line to be the culprit:
```scala
val specBuffer = scala.collection.mutable.ListBuffer.empty[Spec[$refined,Nothing]]
```

Which predetermines the error channel to be `Nothing`.
Seeing how `Spec` is covariant, wouldn't `Any` be a better choice of type here?

Thanks

**Comment by swoogles** [comment]
Thanks for submitting the problem and most of the fix @ncreep !
