### ISSUE TITLE
follow up to zio-config: secrets management

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7540]
This is a follow up to the general zio config concept - thanks for bringing config as a first class citizen to ZIO! 

besides reading configs from environments/system properties, modern applications also come with requirements to secrets management (think hashicorp vault or k8s/openshift secrets in special files or spring config server). 

it would be great if zio would provide ways to get a hold of fixed and rolling secrets, e.g.
 - service 2 service communication secrets, e.g. basic auth tokens / username+password stored in a config file/env variable (provide a way that a secret is not stored in memory or at least just as a byte[])
 - rolling secrets / jwt based (e.g. retrieved via web-api /refresh endpoints )
 - rolling secrets for things like db-connections, e.g. the password of the postgresql connection gets migrated. this would require either the connection pool to reinitialise or maybe the whole dependency graph. 
 
For ZLayer, there already seems to be something prepared (`ZLayer.service[A].reloadableAutoFromConfig(...)`) ?

For rolling secrets, I think we'd need a data structure that kind of acts like a `Ref[MySecret]` which gets used by the process (e.g. connection pool) but gets updated/kept up2date by some external process (e.g. a fiber regularly reading from the secret file or regularly fetching a refresh token). 
We'd also need a mechanism that the old secret keeps being used until the new secret got "validated"/"activated" or generally is marked as "ready to use".  
Some providers (e.g. key rotation in JWT) also provide ways of specifying "not valid before" timestamps.. 

also encrypting secrets is a requirement in some enterprise environments, e.g. the app gets a base-secret which then is used to request other secrets from the secrets-provider. This base-secret is purged from memory as soon as its not required anymore, e.g. to prevent leaking it in case attackers are able to get access to the process memory. 

Of course, with manual labor all of this can already be done nowadays in ZIO. I'm not looking for solutions/workarounds, 
please just think about adding maybe some of these requirements to the roadmap. Thanks. 

Feel free to close this issue at will.

**Comment by jdegoes** [comment]
This is great, I think the amount of work to do in ZIO is small (much of thi sis out of scope for `core`), mainly limited to using macros to generate a `Ref`-backed proxy around a service trait.

Most of the other work would go into ZIO Config. Can you open a ticket there?

**Comment by jdegoes** [comment]
Closed this ticket, as I opened one on hot-swap.
