### ISSUE TITLE
Write Scala 2 / Scala 3 macro for Ref-backed proxy class

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7556]
Imagine we have a service trait like so:

```scala
trait Clock {
  def now: UIO[Instant]
}
```

We want an implementation of `Clock` to be updatable at any time. In order to do this, we need to generate a proxy class, which delegates all the methods of `Clock` to an instance of `Clock` that can be changed at any time.

Of course, the idiomatic way to do this is to put the "current instance" into a `Ref`.

If we were to write the proxy class manually, it might look something like this:

```scala
def proxyClock(service: ScopedRef[Clock]): ZIO[R with Scope, E, Clock] = 
  new Clock {
    def now: UIO[Instant] = service.get.flatMap(_.now)

    // Etc. for all methods of Clock: they delegate to the `Clock` inside the service ref
  }
```

Now this proxy clock can be put into ZIO environment, and code can use the clock anywhere; but also, it is possible to "hotswap" the clock instance with a new one (by interacting with the `ScopedRef`), thus achieving the ability to "dynamically reload" components in a seamless, transparent way.

Because `ScopedRef` rather than `Ref` is used, it is possible for hotswapping to handle resourceful components, without leaking any resources.

This ticket is to create Scala 2 / Scala 3 macros that can generate such an anonymous class that delegates all methods of an interface to the instance stored inside a `ScopedRef`.

The signature of such a macro might be something like:

```scala
def generateProxy[A](service: ScopedRef[A]): A = ...
```

There is more functionality that needs to be built upon such a macro, but this ticket is merely to create and test the macro.

**Comment by jdegoes** [comment]
See #7540 for context.

**Comment by guersam** [comment]
I'm interested in it.
