### ISSUE TITLE
LogSpan: use `zio.Clock` instead of `System`

### ISSUE THREAD

**Issue by vagroz** [zio/zio#7574]
Now `LogSpan` uses `java.lang.System` to get `startTime`. When I wrote a unit-test for my own LogSpan serializer I found that this is untestable. E.g. when I adjust 5 seconds to `TestClock`, my logger prints **-1669803994127** milliseconds instead of **5000**.

Would it be better to use `zio.Clock`?

**Comment by adamgfraser** [comment]
We potentially could but for some of these very low level operators I think there is value in showing what actually happened (e.g. this is when the fiber actually started life, this is how long the fiber actually executed, this is how long this actually took). We also want to keep these operators as lightweight as possible and accessing the environment does have some cost.

I don't think this impacts the ability to test your serializer at all. You can just create your own log spans with arbitrary `String` labels and `Long` start times and serialize that.

**Comment by vagroz** [comment]
Ok, thank you!
> You can just create your own log spans 

Yes, fortunately `FiberRef.currentLogSpan` is not private, and I was able to add my LogSpan there :)
