### ISSUE TITLE
Potential memory leak when using `zio.stream.ZStream#groupedWithin`

### ISSUE THREAD

**Issue by imRentable** [zio/zio#7576]
Please consider the following ZIO 2.0.4 example that throws a `java.lang.OutOfMemoryError: Java heap space` for me after a rather short amount of time.

The JVM flags I used: `-Xmx1000M -Xms1000M -XX:+PrintCommandLineFlags -XX:+PrintFlagsFinal`

```
object OOM extends ZIOAppDefault{

  import zio._

    private val ones = Array.fill[Byte](1024 * 1024)(1)

    case class InboxMessage(bytes: Array[Byte] = ones.clone())

    val run =
      ZStream
        .fromIterator(Iterator.continually(InboxMessage()), 1)
        .throttleShape(3, 1.second)(_.size.toLong) // ~3 MiB/sec
        .groupedWithin(3, 1.seconds)
        .mapZIO { batch =>
          Console.printLine(s"got $batch")
        }
        .runDrain
}
```

The heap graph shows a steep increase:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/12008255/204777309-47e33de2-5cd8-44f0-8375-70801964ed22.png">

Since it seems to retain a lot of fibers:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/12008255/204776223-cb3007bd-88bd-4090-bb26-2034867890c5.png">

Additionally, the heap dump on OOM counts 493 `InboxMessage` live objects which is significantly more than I would've expected.
Furthermore, I ran the aforementioned example without heap size restrictions and it simply kept on consuming more heap.

Interestingly, if I remove the `groupedWithin`, it has a solid looking memory foot print and the GC takes proper effect:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/12008255/204777766-880f1b92-abc3-4354-a4de-c9c43e9c06c9.png">

Are my expectations from the aforementioned code example wrong or does something not work correctly here?

**Comment by adamgfraser** [comment]
@imRentable Can you try on the latest snapshot? Your example runs in constant space for me.

**Comment by imRentable** [comment]
@adamgfraser Thank you, it looks significantly better with `2.0.4+26-9bf983b0-SNAPSHOT`:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/12008255/204785370-9eb469a8-7d93-47b6-a380-a77c6bea0fee.png">

Therefore, I am closing this and hope for a release soon.
