### ISSUE TITLE
Increased heap usage with 2.0.3+ due to tracked Fiber roots in WeakConcurrentBag

### ISSUE THREAD

**Issue by hindog** [zio/zio#7587]
### Description

After bumping from 2.0.2 -> 2.0.3, we started to see OOM's were weren't seeing before.  Memory usage does cap out at some number, it's just quite a bit higher than what we needed on 2.0.2.

I took a heap dump to investigate and found a lot of application data that has already been processed still present in the heap.  When I calculate the path to "GC Root" for these objects, the are all being referenced by `FiberRuntime#reifiedStack` which, in turn, are being held by `Fiber._roots`.  Here is an example that shows the path to GC Root from one of these application objects being held in memory:

<img width="1061" alt="Screen Shot 2022-12-01 at 11 19 54 AM" src="https://user-images.githubusercontent.com/1185158/205141432-a15faf07-3b2b-4ac9-bcf4-41474a74583e.png">

From what I can tell, it looks like it may be related to changes made to `WeakConcurrentBag` as part of [this PR](https://github.com/zio/zio/pull/7272) (cc: @jdegoes).

So it seems that my application is creating a lot of Fiber "roots" leading to this data structure being filled up.  I have limited understanding of ZIO internals so I'm not sure if I'm doing something weird that's causing a lot of Fiber roots to be created and tracked vs non-root Fibers which (I'm assuming) wouldn't be tracked here.  Is there documentation or some relevant code that sheds more light on root vs non-root Fibers?

### Expected Behavior (?)

When a Fiber exits, any memory being held by its runtime should be eligible for GC.

**Comment by adamgfraser** [comment]
Resolved by #7553.
