### ISSUE TITLE
Add ZIO#logError

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7592]
A `ZIO#logError` method will `tapErrorCause` (probably uninterruptibly) and send that to `ZIO.logErrorCause`.

An alternate version of this method could take a short string message to attach to the logged errors.

This method is useful in cases like this:

```scala
myEffect.logError.ignore
```

We want to log the error but we cannot react to it at this point in the code, so we log and ignore the error.

**Comment by jdegoes** [comment]
Maybe it should be called `logErrorCause`.

We could have `logError` that only logs the `E`.

**Comment by adamgfraser** [comment]
Will add.
