### ISSUE TITLE
Add missing assertion rendering API

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio#7602]
There's an open issue in zio-mock (https://github.com/zio/zio-mock/issues/35) and I think there are several things to sort out. The first one is that assertions are just stringified in reporting messages but with the new encoding that does not work.

For example, here:
https://github.com/zio/zio-mock/blob/master/mock-tests/shared/src/test/scala/zio/mock/MockReporterSpec.scala#L60-L77

the `equalTo(foo)` is not rendered correctly. I don't think this can be fixed in zio-mock without changing zio-test. The best I could find was to match on the arrow and get the code:
```
ass.arrow match {
  case Meta(_, _, _, Some(code), _, _, _, _) => code
  ...
}
```

but that will only give you `equalTo`, `foo` is unavailable. The problem is that the argument given to the assertion is only captured in a closure:

https://github.com/zio/zio/blob/188cffbad33807bc56619352afdb9681eac9f30d/test/shared/src/main/scala-2/zio/test/AssertionVariants.scala#L27-L36

Do you agree with the assessment? Do you think the argument could be added to `Meta`, or do you have a better solution in mind?

**Comment by adamgfraser** [comment]
I think that makes sense. What you are saying is that given any `Assertion` we should be able to produce a string rendering of that assertion. This was a feature that previously existed and continues to be valuable for applications like `zio-mock`. Any help here would be greatly appreciated!

**Comment by regiskuckaertz** [comment]
Happy to! What I see is that all assertions are defined as such:

```scala
<assertion logic>.withCode(assertionName)
```

`withCode` wraps the assertion in a `Meta` element:

```scala
  def withCode(code: String): TestArrow[A, B] =
    meta(code = Some(code))
```

What is your gut feeling about adding optional args to `withCode`?

```scala
  def withCode(code: String, args: Any*): TestArrow[A, B] =
    meta(code = Some(code), args = Option.when(args.nonEmpty)(args.map(_.toString()).mkString(",")))
```

**Comment by adamgfraser** [comment]
Maybe `withCode` needs to take a more structured input. Right now it is just a string that basically denotes the "name" of the assertion but it doesn't include the arguments. If it was a more structured representation we could extract both the "name" of the assertion as well as the "full" assertion including the arguments from it. The `Assertion.Render` data type in ZIO 1.0 could be useful inspiration for this.

**Comment by regiskuckaertz** [comment]
Great, leave this with me.

**Comment by swoogles** [comment]
@regiskuckaertz 
How is this coming along? I'm finally able to spend some time on it, but will look at other things if you're knocking this out.

Also happy to pair on this with you!

**Comment by regiskuckaertz** [comment]
Great! I asked a colleague to look into this and will check up on him today so we can make progress. This is just one of at least two issues I think, the other one being the OP "UnsatisfiedExpectationsException: null" which I think should be caught somewhere (the `null` is because it doesn't have a `message`).
