### ISSUE TITLE
OOM/GC pressure with ZIO 2.0.3

### ISSUE THREAD

**Issue by TrustNoOne** [zio/zio#7608]
Hi, 
we started experiencing java heap OOMs in production after upgrading ZIO to 2.0.3. I spent some time debugging and managed to create a small program that puts a lot of pressure on the GC with 2.0.3 or 2.0.4 but not with 2.0.2:

```scala
object Main extends zio.ZIOAppDefault {
  import zio._

  override def run: UIO[Long] = {
    Ref.Synchronized.make[List[Long]](Nil)
      .flatMap { ref =>
        ref.updateZIO { longs =>
          (ZIO.succeed(longs) zipPar ZIO.succeed(None))
            .map(_ => List.fill(20000)(0L))
        }
          .repeat(Schedule.forever)
      }
  }
}

```
This is the behavior with 2.0.3:
![2 0 3](https://user-images.githubusercontent.com/1575319/205935659-2b9382c5-f7ee-4594-9e0a-16f43cee4069.png)

and this with 2.0.2:

![2 0 2](https://user-images.githubusercontent.com/1575319/205935667-95e6f299-32ce-4e54-9d44-2251e85d4c4f.png)

Even thought the `longs` parameter of the ref is just passed in the zipPar and never used, the problem seems to magically go away if the parameter is not used at all in the zipPar. The following screenshot is with 2.0.3 and replacing ` (ZIO.succeed(longs) zipPar ZIO.succeed(None))` with `(ZIO.succeed(None) zipPar ZIO.succeed(None))`
 
![2 0 3 no param](https://user-images.githubusercontent.com/1575319/205936168-8eb42979-dd32-432f-94bd-ed31b4c998d0.png)

Also using zip instead of zipPar: 

![2 0 3 no zipPar](https://user-images.githubusercontent.com/1575319/205935929-bf3d1317-4401-4b73-b15f-bea531e8c518.png)

Please let me know if I can help in any other way. For now I can't upgrade my production application because it consistently goes to java HEAP OOM after upgrading (only) zio 2.0.2->2.0.3

I'm running the test program using a forked run from sbt: 
```
ThisBuild / scalaVersion := "2.13.10"

lazy val `zio203-leak` = project
  .in(file("."))
  .settings(
    run / fork := true,
    run / javaOptions ++= Seq("-Xmx4g", "-Xms4G"),
    libraryDependencies += "dev.zio" %% "zio-streams" % "2.0.3",
  )

```

**Comment by TrustNoOne** [comment]
Following @ghostdogpr reply on discord I tried with the latest snapshot, here are the reuslts with a 2GB heap:

2.0.2:
![Screenshot 2022-12-06 at 15 35 58](https://user-images.githubusercontent.com/1575319/205940901-068a2071-a1ab-4e3f-a598-cf642c29f464.png)

2.0.4+52-8a4b632c-SNAPSHOT:
![Screenshot 2022-12-06 at 15 35 54](https://user-images.githubusercontent.com/1575319/205940911-9a1d6c3b-bcd6-4afd-a764-41f53b55adcf.png)

It seems better but still not completely ok, but at this point I'm not sure the increased CPU usage is just because of increased performance, I'll try to benchmark it

edit: I tried, and the latest snapshot even though it works better seems indeed slower

I haven't done a proper benchmark, just ran this on a cold jvm and checked how many iterations in one minute with the two libraries
```scala
object Main extends zio.ZIOAppDefault {
  import zio._

  override def run: UIO[Long] = {
    Clock.nanoTime.flatMap { start =>
      Ref.Synchronized.make[(Int, List[Long])]((0, Nil))
        .flatMap { ref =>
          ref.updateZIO { case (cnt, longs) =>
            Clock.nanoTime.flatMap(now =>
              ZIO.succeed(println(s"$cnt ${(now.toDouble - start.toDouble) / 1000000.toDouble}")),
            ).when(cnt % 10000 == 0) *>
              (ZIO.succeed(longs) zipPar ZIO.succeed(None))
                .map(_ => (cnt + 1, List.fill(20000)(0L)))
          }
            .repeat(Schedule.forever)

        }
    }
  }
}

```


2.0.4+52-8a4b632c-SNAPSHOT: 300000 62986.195908

2.0.2: 450000 59778.814084

**Comment by TrustNoOne** [comment]
After disabling `RuntimeFlag.FiberRoots` on a suggestion by @adamgfraser, the performance and memory profile seemed to get back to the 2.0.2 values:

2.0.4+52-8a4b632c-SNAPSHOT with FiberRoots disabled:

[info] 450000 59776.115118


![Screenshot 2022-12-06 at 15 56 27](https://user-images.githubusercontent.com/1575319/205946031-34132ba3-a59a-4507-acbe-119ad28dd859.png)

**Comment by adamgfraser** [comment]
@TrustNoOne Hi! We just released ZIO 2.0.5 which makes significant improvements in this area though there may still be room for further optimization. If you don't mind would love to hear about your experience using it one you get a chance to upgrade and we can further refine from there.

**Comment by TrustNoOne** [comment]
@adamgfraser thanks! I just deployed to our production environment after testing it for a bit to make sure the OOM wouldn't happen, for now everything looks pretty good. I'll monitor for a few more days to see latency and throughput

**Comment by adamgfraser** [comment]
@TrustNoOne Great!

**Comment by TrustNoOne** [comment]
everything looks fine so far in both cpu and memory usage, I think we can close this for now? great job as usual :)

**Comment by fsvehla** [comment]
@TrustNoOne Were you able to restore the default runtime configuration, or does this fix only work with you while also disabling FiberRoots?

**Comment by TrustNoOne** [comment]
in the production system 2.0.5 shows basically the same behavior as 2.0.2, while 2.0.3-4 crash with OOM.
No other change, just the library update.

disabling fiber roots only gave me a performance benefit in a crafted reproducer that allocates a list in an infinite recursive loop, nothing close to what I have in production (a loop with a schedule that runs every minute, there was some kind of leak there)
