### ISSUE TITLE
zio.Config: Problem loading env vars

### ISSUE THREAD

**Issue by juliano** [zio/zio#7614]
After migrating a project from 2.0.3 to 2.0.5 and adopt `zio.Config`, the app started crashing, not finding the env vars:
```
timestamp=2022-12-08T15:53:50.189983Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" zio.Config$Error$And: ((Missing data at ENV_A: Expected ENV_A to be set in properties) and (Missing data at ENV_B: Expected ENV_B to be set in properties))
        at example.Main.run(Main.scala:9)"
```
[Reproducible example here](https://github.com/juliano/zconfig-issue)

It seems to me it's related to having an url among the variables, if I change it to something else it works.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
