### ISSUE TITLE
Exception during macro expansion in ZIO test with ZIO 2.0.5

### ISSUE THREAD

**Issue by longliveenduro** [zio/zio#7631]
When I raise the ZIO version from 2.0.4 to 2.0.5 I get

```
[info] compiling 39 Scala sources to /home/chris/prj/toil/zio-geolocation/modules/core/target/scala-3.2.1/test-classes ...
[error] -- Error: /home/chris/prj/toil/zio-geolocation/modules/core/src/test/scala/com/tsystems/toil/geolocation/logic/google/CellHintTransformerSpec.scala:84:10 
[error] 84 |          assertTrue(
[error]    |          ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Exception: Expr cast exception: false
[error]    |of type: false
[error]    |did not conform to type: java.lang.Boolean
[error]    |
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:73)
[...]
[error] 85 |            geolocationPayload.cellTowers.toSeq.isEqualTo(
[error] 86 |              cellHintsToCellTowers.values.take(2).toSeq
[error] 87 |            ) // only the first 2 are GSM and they are the most prominent type in
[error] 88 |            // "cellHintsToCellTowers", so they are selected for the google maps payload
[error] 89 |              && geolocationPayload.considerIp == false && geolocationPayload.radioType == "gsm"
[error] 90 |          )
```

This keeps happening also when I only downgrade zio-test and zio-test-sbt to 2.0.4, while keeping ZIO itself to 2.0.5.
It is not present in 2.0.4.

**Comment by adamgfraser** [comment]
@longliveenduro Thanks for reporting! Can you create a small reproducer?

@wosin I think potentially related to #7310.

**Comment by longliveenduro** [comment]
@adamgfraser Seems to happen when Java Booleans are involved. See https://github.com/longliveenduro/zio-geolocation-tapir-tapir-starter/tree/ZIO-Test-Bug-7631_reproducer to reproduce.

**Comment by adamgfraser** [comment]
@longliveenduro Can you create a more minimal reproducer? For example this works fine:

```scala
object Example extends ZIOSpecDefault {

  val actual = java.lang.Boolean.FALSE

  def spec = suite("suite")(
    test("test") {
      assertTrue(actual == false)
    }
  )
}
```

**Comment by longliveenduro** [comment]
@adamgfraser is this one still too complicated? https://github.com/longliveenduro/zio-geolocation-tapir-tapir-starter/tree/ZIO-Test-Bug-7631_reproducer
If so, I will try my best, to boil it further down...

**Comment by adamgfraser** [comment]
@longliveenduro I think we should be able to replicate this without any dependencies.

**Comment by longliveenduro** [comment]
@adamgfraser removed all unnecessary deps and code. Please check again.

https://github.com/longliveenduro/zio-geolocation-tapir-tapir-starter/tree/ZIO-Test-Bug-7631_reproducer
