### ISSUE TITLE
Optimize performance of the code generated by the provideSome macro

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#7632]
When you call `provideSome[ExistingEnv](layer)`, it gets translated into `provideLayer(ZLayer.environment[Base1] ++ ZLayer.environment[Base2] ++ ... ++ newLayer)`. When `ExistingEnv` is large, the runtime performance of the combination of all layers is catastrophic (a lot of time spent in `ZEnvironment#prune` as well as the low-level runtime).

On the other hand, when you call `provideSomeLayer[ExistingEnv](layer)`, it just calls `provideLayer(ZLayer.environment[ExistingEnv] ++ layer)`, which triggers a single layer combination and a single `prune` (on the new layer). Runtime performance is good even though the environment is large.

It would be great if the macro could be "smarter" and generate code that is like `provideSomeLayer` and unsurprising at runtime.

**Comment by adamgfraser** [comment]
Will take a look at this.

**Comment by jdegoes** [comment]
Re-opening this as the reversion due to compilation time increases means that the issue is no longer fixed.
