### ISSUE TITLE
Docs mistake

### ISSUE THREAD

**Issue by waagnermann** [zio/zio#7653]
Why in [Blocking Operations](https://zio.dev/reference/core/zio/#blocking-operations) chapter you write about 20 blocking tasks but actually creating 100 of them in the corresponding code block?

p.s. also each of those tasks is recursive, which is also confusing

**Comment by khajavi** [comment]
@waagnermann Thank you for reporting. We need to update this section after. This snippet code is legacy from ZIO 1.x and doesn't look relevant to ZIO 2.x.

To learn more please compare the output behavior of that snippet code with the following code in ZIO 1.x:

```scala
import zio._

object BlockingExamples extends zio.App {

  def blockingTask(n: Int): ZIO[console.Console, Nothing, Unit] =
    console.putStrLn(s"running blocking task number $n").orDie *>
      ZIO.succeed(Thread.sleep(3000)) *>
      blockingTask(n)

  def run(args: List[String]): zio.URIO[zio.ZEnv, zio.ExitCode] =
    ZIO.foreachPar((1 to 100).toArray)(blockingTask).exitCode
}
```

In ZIO 2.x we have an auto-blocking mechanism that detects blocking operations and prevents thread starvation.
