### ISSUE TITLE
Switch from sbt-microsites to docusaurus 

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#766]
As the microsite becomes increasingly larger and more like a real website, it will be useful to take advantage of capabilities provided by [Docusaurus](https://docusaurus.io).

Since we have switched from `tut` to `mdoc`, this will be an easier transition:

 - <https://scalameta.org/mdoc/docs/docusaurus.html>

It requires someone at least mildly familiar with HTML / CSS / static site generators, and a willingness to dig in and look at how other Scala microsites were built with Docusaurus.

The documentation pages shouldn't change, since Docusaurus is also Markdown-driven; the main thing is how the information is organized and changing the build tasks to generate using Docusaurus.

**Comment by Dan-M** [comment]
I can take a look at this. But at some point I will probably need support regarding content and design.

**Comment by hamednourhani** [comment]
Hi @jdegoes is this issue still open?

**Comment by LGLO** [comment]
@hamednourhani  - there is an open [WIP PR](https://github.com/scalaz/scalaz-zio/pull/784) by @Dan-M

**Comment by hamednourhani** [comment]
Ok tnx
