### ISSUE TITLE
ZIO retry with policy hangs in test

### ISSUE THREAD

**Issue by fernanluyano** [zio/zio#7664]
I'm having an issue where if I retry a ZIO with a schedule (I have tried exponential backoff and fixed), the test hangs and I get the following message "Warning: A test is using time, but is not advancing the test clock, which may result in the test hanging". Honestly I'm not sure if this is an issue with the test suite or ZIO Schedules in general since I'm migrating a micro from Play to ZIO (due to Akka licensing) and ZIO is new to me. I'm attaching screenshots. Hopefully is something I'm doing incorrectly[](url)
![Screen Shot 2023-01-03 at 4 47 55 PM](https://user-images.githubusercontent.com/7608751/210446990-0dcd630d-db28-48ff-976e-fbf81d5f2c8e.png)
![Screen Shot 2023-01-03 at 4 47 19 PM](https://user-images.githubusercontent.com/7608751/210447006-42a4a90a-92b5-4c3e-9052-5950d7d4d5eb.png)

**Comment by adamgfraser** [comment]
@fernanluyano Tests use the `TestClock` which allow you to manually control the passage of time so you can write tests involving time that are deterministic and don't require waiting for real time to pass. If you just want to use the live clock you can use `TestAspect.withLiveClock`.

**Comment by fernanluyano** [comment]
Thank you
