### ISSUE TITLE
Move ZIO + ecosystem to separate Github organization

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#767]
In light of #730 and other ZIO projects increasingly cluttering up the `scalaz` organization, I think it makes sense to move both ZIO and other projects in its immediate ecosystem to a separate organization on Github, in advance of the impending 1.0 release (since the groupId and artifact names may change, and we need stability post 1.0).

Unfortunately the `zio` name was already taken, but it was abandoned, and when I reached out to Github, they kindly released the name, and I was able to register it.

Therefore, I am happy to announce that we now [hold the ZIO name](https://github.com/zio)!

If folks have thoughts or objections on this migration, please state them now.

**Comment by NeQuissimus** [comment]
Go ahead, seems like a good idea.

**Comment by ahjohannessen** [comment]
:+1:

**Comment by softinio** [comment]
👍 

Let me know if I can help with the migration and admin of new org

**Comment by jdegoes** [comment]
@softinio Careful what you wish for! You're an admin now. 😆 We can begin setting up one team per project and so forth.

@NeQuissimus I have a feeling the biggest pain of the migration is going to be deploying on Sonatype under a new groupid / etc. Do you think you could lend a hand there? 🙏

**Comment by NeQuissimus** [comment]
I have a few thoughts on that.
1) what about a domain? Sonatype generally asks for ownership of one.
2) package and artifact names? Do you want to change them as well?
3) I can do the Sonatype stuff once I have answers to the other two points

**Comment by jdegoes** [comment]
1. I have `zio.world` and `zioworld.com`. I'd like a better one...
2. `scalaz-zio` => `zio`, `scalaz.zio` => `zio`. Then we'll have a different repo for every module that should be versioned independently, e.g. `zio-cats`, `zio-scalaz`, etc.
3. 🙏

**Comment by jdegoes** [comment]
I know Github allows wholesale moving a repo from one org to another. That should make the setup easier.

**Comment by NeQuissimus** [comment]
zio-fp.io is available

**Comment by softinio** [comment]
When shall I start moving the repos over and setting up the teams? Guess we should figure out the sonatype side of things before doing the move. 

Also `zio.dev` domain is available but google domains has it marked as premium so are charing $98 per year for it

**Comment by NeQuissimus** [comment]
https://central.sonatype.org/pages/choosing-your-coordinates.html

Things need to happen in this order:
1) Figure out domain
2) Get Sonatype permissions
3) Move repos
4) Fix builds / publishing

**Comment by jdegoes** [comment]
- [x] Just got `zio.dev`

**Comment by NeQuissimus** [comment]
@jdegoes Enable 2FA for your GitHub ;)

Then enable https://github.com/organizations/zio/settings/security and verify https://github.com/organizations/zio/settings/domains please :)

**Comment by jdegoes** [comment]
@NeQuissimus 2FA is quite onerous, because I am traveling internationally and often change my SIM cards. Is it necessary? 🙏 😆

**Comment by NeQuissimus** [comment]
Not necessary I suppose... I would recommend it though.

https://www.yubico.com/works-with-yubikey/catalog/github/
https://authy.com/guides/github/

2FA via SMS is broken anyways, don't ever use that...

**Comment by jdegoes** [comment]
@NeQuissimus Since it's just an OSS project, my feeling is to keep things as simple as possible for now (rather than requiring all contributors do 2FA with phone or Yubikey). I'm 100% on board for private projects though.

**Comment by jdegoes** [comment]
I further signed up for [Netlify](http://netlify.com), which is free for OSS projects. A better Github Pages with custom SSL. 

I'm in the process of verifying zio.dev with Github. Could take a day.

**Comment by NeQuissimus** [comment]
Do you also want to replace Travis CI with Circle CI?

**Comment by softinio** [comment]
Great news re: `zio.dev`.

I know circleci really well let me know if I can help with that.

**Comment by jdegoes** [comment]
I'd love to make that change. I love Travis, but it's been very flaky recently.

**Comment by jczuchnowski** [comment]
I'm for CircleCI too, and could help moving NIO (zio-nio now :laughing:  ?)

**Comment by NeQuissimus** [comment]
@jdegoes Could you take care of this, please? It's to prove to Sonatype we own the domain `zio.dev`
> Add a TXT record to your DNS referencing this JIRA ticket: OSSRH-47886

**Comment by jdegoes** [comment]
@NeQuissimus 

[Done](https://dig.whois.com.au/dig/sonatype.zio.dev)

**Comment by jdegoes** [comment]
@NeQuissimus 

Also [verified zio.dev with Github](https://github.com/zio)

**Comment by jdegoes** [comment]
Other thoughts:

 - Moving the media assets to their own repository `zio-media` or something (they're big and not relevant for development)
 - Possibly having a dedicated `zio-website` project that is separate from `zio-core`.

**Comment by NeQuissimus** [comment]
If you're ready for ZIO publishing to be broken for a little while, go ahead and move the repo. I'll try to fix the build as soon as time permits.

**Comment by jdegoes** [comment]
@NeQuissimus Let me get one more RC candidate out then will be ready... thank you!

**Comment by softinio** [comment]
Moved `scalaz-actors` to new org and renamed it to `zio-actors`. Thought it was a good first repo to move as not in critical path for publishing and we can use it as the example repo to set everything up on and then do same for other repos. 

Will work on a PR for it next to rename anything `scalaz-actors` to new name and add circleci build.

@NeQuissimus Planning to configure the circleci build do use environment variables that gets set in circle for the sonatype creds when they are available if ok? I have used circleci for years and am not aware of them supporting anything similar to travis that lets us encrypt credentials and include in the repo. 

Ref: https://github.com/zio/zio-actors/issues/23

**Comment by NeQuissimus** [comment]
I added the Sonatype variables.
You'll also need an encrypted key to sign artifacts. I'll generate one over the weekend.

**Comment by softinio** [comment]
@NeQuissimus thank you Sir!

**Comment by NeQuissimus** [comment]
Key is now also in your ENV.

**Comment by jdegoes** [comment]
@softinio @NeQuissimus All right, we're ready to go on this. Help appreciated. 😄

**Comment by jdegoes** [comment]
I am ready to add people to Netlify to help with the microsite. If you're interested, send me your email address and I'll add you.

**Comment by ghostdogpr** [comment]
> I am ready to add people to Netlify to help with the microsite. If you're interested, send me your email address and I'll add you.

I can have a look. Sent you my email by DM on gitter.

**Comment by ghostdogpr** [comment]
Done for Netlify: https://zio.dev

**Comment by softinio** [comment]
@jdegoes @NeQuissimus @ghostdogpr I have bandwidth this weekend to get the circle build added and move repo to new repo. Just so we don't duplicate effort can I confirm you all fine with me to proceed with that or do you want to split the tasks between each other? I ask as I saw new issues opened for each of these and fixing the microsite is kind of part of it too which I am happy to help with. 

John, I will DM you my email address for netlify access so I can help with that also.

**Comment by NeQuissimus** [comment]
I yeah go ahead. I made a separate issue for it. Just grab it. All the necessary variables should be in Circle contexts "Sonatype" and "Website", respectively

**Comment by softinio** [comment]
@NeQuissimus On it. Thank you.

**Comment by jdegoes** [comment]
@softinio @NeQuissimus What else do we have to do here? Just fix the release process, right?

**Comment by softinio** [comment]
@jdegoes Assume by release process you mean publishing to sonatype. Thats all done and ready by my Circle PR that I merged today. We just need to test it (I have tested it with actors so should work with no issue with ZIO as same context/credentials and process to publish).

As a suggestion we should try to do a release and publish the current RC5 again but under the new org as a test and get it to work so that RC5 can co-exist in maven under zio org asap to get people used to it.

Anything else I can help with let me know.

**Comment by regiskuckaertz** [comment]
@softinio will the scaladoc be generated during release? I assume this is take. Care of by the sonatype release plugin?

**Comment by jdegoes** [comment]
@softinio I will try a release later today and report back.

Ditto on question for @regiskuckaertz: will it build and publish the homepage, with accompanying Scaladoc?

**Comment by softinio** [comment]
@jdegoes @regiskuckaertz good catch gentlemen. Created   #954 to make sure circle generates the scaladocs and publishes them with website.

Release should work though maybe wait to do release after I fix the scaladoc issue so we can see on release new website with scaladoc included in published also.

Hoping to get this done today after work before I sleep so PR within 24hours.

**Comment by softinio** [comment]
@jdegoes @regiskuckaertz as promised PR is ready for your review: #956 

Once this merges and we successfully test and publish  and release RC5 under the new org will need to tackle #955 

Let me know if I can help with anything more and look forward to your review in case I missed something but all will be revealed when we test :-) 

Got some ideas for improving on our build, release and documentation going forward. Will put my ideas in a new issue when I get a moment so we can all collaborate and decide way forward.
