### ISSUE TITLE
WeakConcurrentBag memory leak

### ISSUE THREAD

**Issue by petoalbert** [zio/zio#7672]
There is a memory leak in WeakConcurrentBag here: https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/internal/WeakConcurrentBag.scala#L77-L79

```scala
    if (graduateCount > nurserySize / 10) {
      gc()
    }
```

The `gc()` function is only called from `graduate()` if more than `nurserySize / 10` fibers have been graduated. That means that if we are creating root fibers at a rate that never hits this threshold, we never clean up `WeakReferences` from the `graduates` set.

Here is a short snippet that can reproduce this problem. Since `nurserySize / 10 = 1000`, we would need to create at least 1000 fibers so that [the scheduled call to graduate from ZScheduler](https://github.com/zio/zio/blob/7efadb73a2ae738e33361c51deda93d867441d42/core/jvm/src/main/scala/zio/internal/ZScheduler.scala#L320) calls `gc()`, but we only create 900 every second.
- if you do sequential heap dumps of this application, you can see `WeakConcurrentBag.graduates` keeps growing
- if you debug this application, you can see that `gc()` never gets called

```scala
object SimpleFibers extends ZIOAppDefault {
  val work = ZIO.replicateZIO(900)(ZIO.sleep(1.minute).forkDaemon).repeat(Schedule.fixed(1.second))
  val run = work *> ZIO.never
}
```

I think this issue could be fixed by calling `gc()` with an absolute threshold on the size of `graduates`, however I am not sure of the performance implications of that.

```scala
    if (graduates.size() > threshold) {
      gc()
    }
```

Kudos to @ollyw for helping me with this. The [issue he created for cats-interop](https://github.com/zio/interop-cats/issues/640) and his work on uncovering related performance issues have lead us here. This memory leak might explain the issues he has described with http4s, as http4s/zio-cats-interop creates a lot of deamon fibers. I can also reproduce this memory leak with a http4s server application with the proper setup.

**Comment by adamgfraser** [comment]
@petoalbert Thanks for reporting! Will take a look.

**Comment by robmckeown** [comment]
![image](https://user-images.githubusercontent.com/10225924/216713197-8583efbc-09a9-4737-a79a-80d45c543d3d.png)

Hey guys, kudos for resolving this so quickly - we just encountered it last week, and the update here seems to have resolved things for us!
