### ISSUE TITLE
A typo in documentation: izMumi-reflect

### ISSUE THREAD

**Issue by pshirshov** [zio/zio#7678]
See https://zio.dev/izumi-reflect/

Please fix

**Comment by yoohaemin** [comment]
I can still see the typo on the sidebar: https://zio.dev/izumi-reflect/

**Comment by adamgfraser** [comment]
@khajavi Do you want to publish a new version of the documentation?

**Comment by pshirshov** [comment]
Btw, still an issue.

**Comment by guizmaii** [comment]
@pshirshov Is this still an issue? Can we close this issue?

**Comment by pshirshov** [comment]
![Screenshot_20241217-115554.png](https://github.com/user-attachments/assets/21b620a6-fbd1-4e6d-bfe0-aa8dcf76117f)

Still an issue
