### ISSUE TITLE
Finish interruptible monadic regions

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#768]
## Annihilation Laws

Changes to interruptibility have "infinitesimally thin edges"; i.e. they do not introduce new regions in which interruptibility / uninterruptibility has an effect.

```scala
// Interruptible self-annihilation:
interruptible(interruptible(zio)) === interruptible(zio)
// Interruptible other-annihilation:
uninterruptible(interruptible(zio)) === interruptible(zio)

// Uninterruptible self-annihilation:
uninterruptible(uninterruptible(zio)) === uninterruptible(zio)
// Uninterruptible other-annihilation:
interruptible(uninterruptible(zio)) === uninterruptible(zio)
```

~~## Fusion Laws~~

~~Two adjacent interruptible/uninterruptible regions will be fused into a single region.~~

```scala
// Uninterruptible fusion law
uninterruptible(zio1).flatMap(a => uninterruptible(zio2(a))) ===
  uninterruptible(zio1 >>= zio2)

// Interruptible fusion law
interruptible(zio1).flatMap(a => interruptible(zio2(a))) ===
  interruptible(zio1 >>= zio2)
```

**EDIT**: _Deleted for being too surprising._

## Primitive Laws

Primitive effect constructors are not interruptible.

```scala
ZIO.fail(a) === uninterruptible(ZIO.fail(a))
ZIO.effect(a) === uninterruptible(ZIO.effect(a))
ZIO.effectTotal(a) === uninterruptible(ZIO.effectTotal(a))
ZIO.succeed(a) === uninterruptible(ZIO.succeed(a))
ZIO.succeedLazy(a) === uninterruptible(ZIO.succeedLazy(a))
```

/cc @mvv

**Comment by iravid** [comment]
Regarding absorption: 
```
uninterruptible(zio1).flatMap(a => uninterruptible(zio2(a))) ===
  uninterruptible(zio1 >>= zio2)
```

The LHS can be interrupted between `zio1` and `zio2`, but the RHS cannot. Is this intentional?

**Comment by jdegoes** [comment]
@iravid I am not sure if it's a good idea yet, but the intent is to make the LHS behave the same as the RHS, i.e. it cannot be interrupted:

 > If you're coming _out_ of an uninterruptible region and immediately proceeding _into_ an uninterruptible region, then the fiber will not be interrupted _between_ those regions.

**Comment by iravid** [comment]
That'd make big resource acquisition chains (e.g. Managed trees) uninterruptible between the acquisitions. Not sure if that's a good idea either :-)

**Comment by jdegoes** [comment]
@iravid You're right. Although it's not a huge loss since you can `uninterruptible(...) *> allowInterrupt`.

**Comment by iravid** [comment]
Another pattern (that I personally use a lot) that'd become mostly uninterruptible:
```
Task.foreach(items) { item =>
  managed.use { resource =>
    resource.save(item)
  }
}
```

Also `allowInterrupt` is a nice throwback to the cats-effect `IO.cancelBoundary` which was really annoying :-)

May I ask (in terms of reasoning) what do we gain from the absorption laws?

**Comment by jdegoes** [comment]
@iravid The only thing you gain is that if coming out of an uninterruptible section that acquires a resource, then you know it will be passed to a subsequent uninterruptible continuation. I don't think that use case justifies the "peek ahead" though, so I deleted those laws.

> Also allowInterrupt is a nice throwback to the cats-effect IO.cancelBoundary which was really annoying :-)

Yes. It could be useful in the middle of an uninterruptible block, at a safe point. Anyway, I saw Haskell had it, and I could express it in terms of existing operations, so I added it. 😄

**Comment by mvv** [comment]
> // Uninterruptible other-annihilation:
uninterruptible(interruptible(uninterruptible(zio))) === uninterruptible(zio)

Does not make much sense to me.

I tend to think about this in terms of interruption points. The primitive effects have no interruption points:
```
IO.succeed/Lazy(...)
IO.effect(...)
IO.fail(...) // Not exactly, given the current allowRecovery
```
`asyncEffectMaybe` is an interruption point (unfortunately, several) and so is `yieldNow`.

Fiber starts with an interruption point:
```
(<1> foo).fork
```

The set of interruption points of a `flatMap`
```
(<1> foo).flatMap { x => <2> bar(x) }
```
is the union of the sets of `foo` and `bar` plus `<1>` and `<2>`.

For `interruptible` we have `<1>` plus all interruption points in `foo`:
```
interruptible(<1> foo)
```
For `uninterruptive` we have the union of interruption points of all `interruptible` subexpressions in `foo`
```
uninterruptible(foo)
```
e.g. in
```
uninterruptible {
  (<X> interruptible {
            <1> uninterruptible {
                     (<X> pre).flatMap { x =>
                       <X> (<X> interruptible(<2> foo)).flatMap(y => <X> post(y))
                     }
                   }
          }).flatMap { z =>
    <X> wrap(z) 
  }
}
```
interruption points are `<1>`, `<2>` and all points in `foo`.

So, the `uninterruptible(interruptible(uninterruptible(zio)))` looks to me like
```
uninterruptible(interruptible(<1> uninterruptible(zio)))
```

**Comment by iravid** [comment]
Great explanation @mvv

**Comment by jdegoes** [comment]
@mvv @iravid 

That is the "fat edges" interpretation of `interruptible` / `uninterruptible`, where the combinators themselves add additional instructions, which can form the basis of interruption.

You can see this in your mental model:

```
interruptible(<1> uninterruptible(zio))
```

This is in fact the way things work right now, but I think a more algebraic model might be useful. Defining `(un)interruptible(foo)` to be the _exact_ same effect `foo`, but with a different interruptibility status for any regions in `foo` whose interruptibility is not already specified.

You can think of a 3 region `foo` like this:

```
| unspecified | interruptible | uninterruptible |
```

So if we call `uninterruptible` on it, then we get back:

```
| uninterruptible | interruptible | uninterruptible |
```

However, if we call `interruptible` on the original `foo`, then we get back:

```
| interruptible | interruptible | uninterruptible |
```

With this interpretation of the combinators, you can see how `uninterruptible(uninterruptible(foo))` must be exactly the same as `uninterruptible(foo)`; and `interruptible(interruptible(foo))` must be the same as `interruptible(foo)`.

Further, you can also see why the other-annihilation laws have to hold: whether we wrap `foo` in `uninterruptible` or `interruptible`, it's unspecified regions are now fully specified; so additional wrapping with either combinator has no effect.

Now why have such a model? Well, it's less imperative and less tied to the mechanics of evaluation. But more than that, it means that if you pass an uninterruptible `foo` to some code, which promptly wraps it in `interruptible`, then it will be as if it were _not_ so wrapped.

The original definition of `bracket` was like so:

```scala
uninterruptible(for {
  a <- acquire
  b <- interruptible(use(a)).ensuring(release(a))
} yield ())
```

If you take the "filling in holes" interpretation of the combinators, then an uninterruptible `use` composes into a bracket that is wholly uninterruptible. If you take the "fat edges" interpretation of the combinators, then while the `use` may be uninterruptible, the code as a whole can still be interrupted on either side of `use(a)`.

I believe, but do not know, that "thin edges" will be less surprising to users.

**Comment by iravid** [comment]
I agree that the thin edge model is less surprising. The `bracket` example, with `use` being constructed as uninterruptible and remains so even if wrapped in interruptible, appears more compositional.

**Comment by mvv** [comment]
Ah, a clash of intuitions :)

When I look at `IO.unit.interruptible`, I can't help but think that it is interruptible, just like `IO.unit.fork` is. But when I look at `bracket(acquire)(release)(x => uninterruptible(use(x)))`, I just see a fancy version of `acuire.flatMap(x => uninterruptible(use(x)))`, so I don't expect it to be uninterruptible as a whole, it's a combinator after all.

**Comment by iravid** [comment]
@jdegoes you wanted to follow up on the algebraic laws here?

**Comment by jdegoes** [comment]
@iravid Yes, I'd like to implement the good ones and test the already implemented ones... worth keeping it open.

**Comment by kitlangton** [comment]
Pretty sure this has been addressed
