### ISSUE TITLE
Make equality on Config.Secret more robust

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7681]
Due to the short-circuiting behavior of equality tests on Chunk, `Config.Secret` is vulnerable to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack). To make this more robust, the amount of time taken to compare two secrets should always be fixed (proportionate to the length of the longer array).

This means that all parwise chars from the two arrays should be compared, even after the first "false" is discovered (indicating the arrays of characters cannot be equal).

While inefficient, this constant-length equality implementation will help make `Secret` more robust to timing attacks.

**Comment by adamgfraser** [comment]
I will take a look at this.
