### ISSUE TITLE
Config.Sequence with a fallback value always returns the empty Chunk

### ISSUE THREAD

**Issue by IMax153** [zio/zio#7689]
## Description

The default behavior of `Config.Sequence` will fallback to an empty `Chunk` even for the case where the data is missing during resolution by the `ConfigProvider`. 

The logic that handles `ConfigError.MissingData` cases when resolving the `Config` for the `Config.Primitive` repeated by a `Config.Sequence` is here:

https://github.com/zio/zio/blob/d948ad03b2bbdabd682e0be7d379287f6c13fefa/core/shared/src/main/scala/zio/ConfigProvider.scala#L287-L295

Because `isEmptyOk` is set to `true` when looping over the primitive from a sequence operation, an empty `Chunk` is always returned, even if the data specified by the `Config` is missing.

The result is that the `ConfigProvider` always resolves `ConfigError.MissingData` for a `Config.Sequence` to an empty `Chunk`, even if the user has specified a fallback via the `withDefault` combinator.

### Example

```scala
import zio._

object Main extends ZIOAppDefault {
  def provider(map: Map[String, String]): ConfigProvider =
    ConfigProvider.fromMap(map)

  final case class Example(sequence: Chunk[String])

  object Example {
    val config: Config[Example] = Config
      .chunkOf(Config.string)
      .withDefault(Chunk("never get here"))
      .map(Example(_))
  }

  def run = {
    for {
      config <- provider(Map.empty).load(Example.config)
      _ <- ZIO.succeed(println(config)) // Always resolves to "Example(Chunk())"
    } yield ()
  }
}
```

## Discussion

I'm not entirely sure whether the behavior of `Config` described above could be considered a bug or the intended behavior, but I think it warrants a short discussion regardless.

I think that there are two good options here, and they depend entirely on how you interpret a missing value when resolving a `Config.Sequence`.

#### Interpret Missing Values as a ConfigError

Remove the default fallback behavior for `Config.Sequence` and instead return the `ConfigError.MissingData`. Given that we have combinators to handle the optionality of values when resolving a `Config`, a user could easily map `.optional` to an empty `Chunk`. 

#### Interpret Missing Values as is Done Currently

Keep the current behavior, and consider exposing combinators (i.e. `nonEmptyChunkOf` or `chunkOf1`) which require at least one value to be specified. These combinators could return `NonEmpty` variants of iterables such as `NonEmptyChunk`.

**Comment by patroza** [comment]
As optionality is handled by `.optional`, I would say that a missing value should not be silently interpreted as "an empty collection", so I am with option 1: "Interpret Missing Values as a ConfigError".

NonEmpty should be treated as another concern, e.g parsing from "" = empty, so should fail on the NonEmpty case, but should create an Empty Iterable otherwise.

I think this best captures intent. Otherwise it is arbitrary if omittance was intended or by error.
I certainly was surprised that the `withDefault` combinator wasn't triggering when I had omitted the value.

**Comment by jdegoes** [comment]
Flat representations do not have an "empty" value. So I think we need to ensure that `Sequence` can be read even if there are no entires in the underlying config data.

What we could do, however, is have a `NonEmptyChunk`, implemented as a subtype of `Sequence`, that fails if there is no data.

What do you think about that solution?

**Comment by patroza** [comment]
> What we could do, however, is have a NonEmptyChunk, implemented as a subtype of Sequence, that fails if there is no data.

I think it is a separate concern, I think there is: absence, empty, and non-empty.
In the other types, absence means ConfigError, and allows to be catched by `withDefault`,
so this case is rather the strange duck in the boat, to me anyway. I was surprised my `withDefault` didn't get hit.

The alternative to me would be to read it as `string`, and then do the conversion myself, but I would prefer to have a built-in solution, maybe a separate combinator then that uses map to Chunk internally?

**Comment by jdegoes** [comment]
This would mean that for property files, environment variables, and so forth, the sequences are **non-empty**. I think more people will complain if they cannot have empty sequences in those representations than who will complain if missing sequence data results in an empty sequence (just a guess, however).

**Comment by jdegoes** [comment]
Another option is we could generate a warning for empty sequence data if loaded from a non-flat configuration source, or something along those lines.

**Comment by patroza** [comment]
> I think more people will complain if they cannot have empty sequences

Might be, hard to tell, but isn't that what `optional` or `withDefault` is for? now it's a no-op for Chunk.
it's like a Chunk-with-benefits, except, for me it's the opposite, a Chunk-with-downsides :)

An alternative is providing a shortcut for others with `chunkWithFallback` etc.

**Comment by mikearnaldi** [comment]
Seems strange that there is a difference between sequences and anything else, one may argue that 0 is a valid default for an integer. A sound implementation would treat all the types equally, a NonEmpty would not allow for the case of an empty sequence to be specified which may not be what we want in a general case

**Comment by jdegoes** [comment]
It's not a no-op for chunk. It changes the type to `Option[Chunk[A]]`.

Looking at the code, the logic appears only in `fromFlat`, which assumes reading from flat data, in which there is no possible representation of an empty sequence.

A given `Flat` could always choose to return an error for an empty sequence, it's just the property and envirornment variable ones in ZIO don't do that.

**Comment by jdegoes** [comment]
I think a better definition of orElse could detect and recover from an empty chunk (from missing data). In which case this ticket is connected to the other ones on `orElse`.

**Comment by patroza** [comment]
> It's not a no-op for chunk. It changes the type to `Option[Chunk[A]]`.

Yea sorry, I meant it's like a no-op, because it always results in Some Chunk.

> I think a better definition of orElse could detect and recover from an empty chunk (from missing data). In which case this ticket is connected to the other ones on orElse.

Feels weird to me if `withDefault` and `orElse` behaviour don't match, could both of them detect and recover?

**Comment by adamgfraser** [comment]
I think about it a little differently that a `Config` is something that, when loaded, either succeeds with a value or fails with a configuration error. So `chunkOf` should behave like `ZIO.collectAll` in that it loads each of the underlying configurations and if all of them succeed puts them together into a collection and fails if any of them fails.

Then the current behavior is similar to `ZIO.collectAllSuccesses` and could be implemented in terms of the existing operator by basically calling `optional` on all of the values and then mapping the result to collect the values that do exist.

**Comment by IMax153** [comment]
@adamgfraser - just to clarify, you are suggesting that the current behavior of `chunkOf` is undesirable?

**Comment by adamgfraser** [comment]
So I think overall we're still figuring out the right mental model for `Config`, which I think is reflected in the fact that we're having this conversation. I'm suggesting a mental model of something like:

```scala
type Config[+A] = ConfigProvider => IO[Config.Error, A]
```

That's obviously an executable encoding versus `Config` actually is a declarative encoding but if you look at the signature of `ConfigProvider#load` that seems like a relatively accurate description.

My first observation would be that just loading `Config.string` in the example above fails:

```scala
object Example extends ZIOAppDefault {

  val config =
    Config.string

  val configProvider =
    ConfigProvider.fromMap(Map.empty)

  val run =
    configProvider.load(config).debug
}
```

```
[info] <FAIL> Fail((Missing data at : Expected  to be set in properties),Stack trace for thread "zio-fiber-4":
[info]  at zio.Example.run(Example.scala:12))
[info] timestamp=2023-01-11T18:35:42.325972Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" zio.Config$Error$MissingData: (Missing data at : Expected  to be set in properties)
[info]  at zio.Example.run(Example.scala:12)"
```

So my expectation would have been that `chunkOf` would basically be analogous to `ZIO.collectAll`:

```scala
def collectAll[A](configs: Chunk[Config[A]]): Config[Chunk[A]] =
  configProvider => ZIO.collectAll(configs.map(_(configProvider)))
```

That is it collects all the values assuming they are successful and fails with the error otherwise.

Then you could implement a variant that collects all successes and ignores the failures in terms of it like this:

```scala
def map[A, B](config: Config[A])(f: A => B): Config[B] =
  configProvider => config(configProvider).map(f)

def optional[A](config: Config[A]): Config[Option[A]] =
  configProvider => config(configProvider).option

def collectAllSuccesses[A](configs: Chunk[Config[A]]): Config[Chunk[A]] =
  map(collectAll(configs.map(optional)))(_.flatten)
```

Then you just have a question of which ones of these should be called `chunkOf` and which should be called something else. For example `collectAll` could be `chunkOf` and `collectAllSuccesses` could be something like `chunkOfSuccesses`.

It seems like both of these operators could potentially be useful and we could call them different things but I'm more interested in a consistent conceptual model for this data type which I think this is one possibility for but there are others such as one that is more "tree focused".

**Comment by IMax153** [comment]
Regardless of what is settled on for the underlying representation of `Config`, I agree with the mental model that you propose as, to me, that is the most intuitive mental model.

If we think of `chunkOf` as `collectAll(Config.string)`, and `Config.string` fails because there is missing data, then `collectAll(Config.string)` fails, whereas `collectAllSuccesses(Config.string)` returns the empty `Chunk`. 

Obviously naming is up for debate, but I agree with this mental model.

**Comment by patroza** [comment]
@adamgfraser how does it change the issue; I think in both of your cases you end up with an empty chunk, unless there is an error parsing values within the list.
collectAll will fail, collectAllSuccesses will return just the ones that succeeded parsing.
That’s a fine feature for sure.

But the issue at hand however is when a value for the whole sequence in the provider is missing, that we receive an empty Chunk instead of an error. Rendering withDefault and orElse useless for it.

I still think if you want an empty Chunk by default, one should use withDefault with an empty Chunk.  We could make a combinator for that called chunkOrEmptyOf or so.

**Comment by adamgfraser** [comment]
@patroza The first one would fail with an error.

**Comment by patroza** [comment]
> The first one would fail with an error.

Hm, for the env provider as example; what do the following cases return in your collectAll sample (my expectations listed):
- no key/value = error
- “” = empty
- “a” = (“a”)
- “a,b” = (“a”, “b”)


And a chunk of numbers:
- no key/value = error
- “” = empty
- “a” = error
- “1,2” = (1, 2)


If ‘no key/value’ in the collectAllSuccesses returns an empty chunk, then you have the problem that you don’t know if the list was not there, empty or just had errors. Perhaps that’s desired.

**Comment by adamgfraser** [comment]
So let's use code:

```scala
object Example extends ZIOAppDefault {

  val a = Map.empty[String, String]
  val b = Map("key" -> "")
  val c = Map("key" -> "value")
  val d = Map("key" -> "value1, value2")

  val e = Map.empty[String, String]
  val f = Map("key" -> "")
  val g = Map("key" -> "value")
  val h = Map("key" -> "value1, value2")

  val config =
    Config.chunkOf("key", Config.string)

  val run =
    for {
      _ <- ConfigProvider.fromMap(a).load(config).debug("a")
      _ <- ConfigProvider.fromMap(b).load(config).debug("b")
      _ <- ConfigProvider.fromMap(c).load(config).debug("c")
      _ <- ConfigProvider.fromMap(d).load(config).debug("d")
      _ <- ConfigProvider.fromMap(e).load(config).debug("e")
      _ <- ConfigProvider.fromMap(f).load(config).debug("f")
      _ <- ConfigProvider.fromMap(g).load(config).debug("g")
      _ <- ConfigProvider.fromMap(h).load(config).debug("h")
    } yield ()
}
```

Current output:

```
[info] a: Chunk()
[info] b: Chunk()
[info] c: Chunk(value)
[info] d: Chunk(value1,value2)
[info] e: Chunk()
[info] f: Chunk()
[info] g: Chunk(value)
[info] h: Chunk(value1,value2)
```

I tend to think that `a` and `e` should fail and the current behavior is otherwise correct. Note that all of these examples are also different from the original one where you attempt to just load a `chunkOf(Config.string)` instead of `ChunkOf("key", Config.string)` which I don't even really think maps sense because you're looking for a value without any key.

**Comment by patroza** [comment]
@adamgfraser yes, `a` and `e` should fail which is my point. We look for a Chunk at key, but the key is not in the Map.

You’re right, we missed the key before.
Could this've been a source of confusion?

**Comment by adamgfraser** [comment]
Let me get into the code to see what is going on and come back.

**Comment by patroza** [comment]
One related issue I find is that `withDefault` (is based on `orElse`) and catches all errors, not just MissingData:
The docs suggest it only uses the default when the information cannot be found: 
```
  /**
   * Returns a new config that describes the same structure as this one, but has
   * the specified default value in case the information cannot be found.
   */
```
And that would also be what I expected. If I describe a number, or a Chunk of numbers, but it finds a string, or a Chunk of strings, then when I define a default I would expect it to only use that default on the Missing case, and not on Invalid data case. Classically, a provided default is used when a value is missing, not when a value is in error, I believe.

Optionally I suppose a `catchAll` where we can customise the behaviour based on the error could be useful,
but again I think that should be used for the exceptional case where you may want to swallow multiple errors.

Or perhaps optional is intended for this; for defaults only on the missing case we can handle the Option?

**Comment by adamgfraser** [comment]
My expectation would have been that it would recover from all errors but someone else had the same question and agree it is an ambiguity that needs to be resolved.

**Comment by patroza** [comment]
> My expectation would have been that it would recover from all errors but someone else had the same question and agree it is an ambiguity that needs to be resolved.

Thanks. The problem is that even `optional` is using `orElse`, and there is no `catchAll` exposed, so there is no way for me to properly handle only a "missing key" case.
The only option right now I think is to make a custom provider which reads from Environment, and adds default values when missing, but then the nice `Config` expressiveness value starts to drop.

**Comment by vigoo** [comment]
Note: `optional` is no longer using `orElse`, `Config.Optional` was introduced in this commit: https://github.com/zio/zio/pull/7559 
ZIO 2.0.5 already includes this

**Comment by patroza** [comment]
> Note: `optional` is no longer using `orElse`, `Config.Optional` was introduced in this commit: #7559 ZIO 2.0.5 already includes this

thanks, but both `Config.Optional` and `orElse` are using `Config.Fallback` under the hood right, as it catches all errors, and then proposes the fallback value, I think the distinction doesn't change the behaviour, or am I overlooking something?

I'm currently running with a fork where the Fallback's `ZIO.catchAll` call filters only on `Missing`, and the behaviour is much more like I expect.
Now of course I don't have the option anymore to fallback on other/all errors.
While I need the Missing cases most, I suppose there's space for both.
Fallback maybe should support an error filter, and on top of that we can then build the other variations.

**Comment by vigoo** [comment]
`Optional` extends `Fallback` for binary compatibility reasons; so yes you are right if the actual config provider is not updated to handle it differently, you still have the problem. But the idea was to have specific cases in the providers for optional with different behavior.

**Comment by patroza** [comment]
@vigoo alright thanks, so basically Optional needs improved handling.
Only Missing error should be handled, resulting in None, in all other error cases, the error would not be handled and bubble up. Then `orElse` and `withDefault` could in all cases remain as is; catch all errors and fall back.
This would already be very valuable to me.

Only missing then is a way to provide a fallback Config just in the case of Missing/None. It kind of leads me back to thinking that it would be more flexible to remove Optional as an operation, instead extend Fallback with an optional error filter, ala `catchAll`, and then just build combinators for optional cases, and anything else as desired on top of that.

**Comment by adamgfraser** [comment]
@patroza I think the existence of `Optional` is independent of what the correct behavior of these operators is with regard to errors for missing data versus other error types and how if at all we should support providing different fallback logic based on the error type.

You are right that an operator like `catchAll` would be the most flexible way of handling errors but that would also mean that the structure of a configuration could not be statically introspected. You would not even know what the next configuration was you were supposed to load until you had loaded some other configuration and seen which error it failed with.

Anyway, will look at this issue and come back.

**Comment by patroza** [comment]
@adamgfraser thanks a lot for addressing via https://github.com/zio/zio/commit/a1d5e2a4d880f4a70af7696a302a57e6fca45c37
