### ISSUE TITLE
Provide a `Tests.Argument` for excluding tests by tag

### ISSUE THREAD

**Issue by jeffmay** [zio/zio#7703]
### Problem

I would like to be able to run all tests that do not match a given tag. For example, I have tests that require a database and vault to be running docker and all other tests can create their own Docker containers as needed. I want to mark the tests that require existing state on the host machine with a tag, so that I can exclude them from the default `sbt test` command.

### Proposed Solution

Implement a way to pass a parameter to exclude a set of tags via a `Tests.Argument` in sbt:

```scala
Test / testOptions += Tests.Argument("-xtags", "local-deployment")
```

Or directly in sbt:

```scala
testOnly FooSpec -- -xtags "local-deployment"
```

#### How would it work with `-tags`?

I think it could work the same as scalatest:

> Include and Exclude Tests with Tags
> You can specify tag names of tests to include or exclude from a run. To specify tags to include, use -n followed by a list of tag names to include. Similarly, to specify tags to exclude, use -l followed by a list of tag names to exclude. If tags to include is not specified, then all tests except those mentioned in the tags to exclude (and in the org.scalatest.Ignore tag), will be executed. (In other words, the absence of a -n option is like a wildcard, indicating all tests be included.) If tags to include is specified, then only those tests whose tags are mentioned in the argument following -n and not mentioned in the tags to exclude, will be executed. For more information on test tags, see the [documentation for Suite](http://doc.scalatest.org/3.0.1/#org.scalatest.Suite). Here are some examples:
>
> ```
> test-only org.acme.* -- -n CheckinTests
> test-only org.acme.* -- -n FunctionalTests -l org.scalatest.tags.Slow
> test-only org.acme.* -- -n "CheckinTests FunctionalTests" -l "org.scalatest.tags.Slow org.scalatest.tags.Network"
> ```

----

Related to https://github.com/zio/zio/issues/4530 but specifically about the suggested solution by @adamgfraser of using test tag negation.

**Comment by adamgfraser** [comment]
@jeffmay You can already do this with `-ignore-tags`.

**Comment by jeffmay** [comment]
Oh, nice! I love when a ticket is that easy 😅

I might file an issue to add this to the documentation and take a crack at it. Thanks!
