### ISSUE TITLE
Error in provide macro for Scala 3

### ISSUE THREAD

**Issue by davidlar** [zio/zio#7712]
There is a problem with the provide macro after updating to Scala 3 (Zio 2). 
It fails in some cases when there are multiple layers of the same type but with different type parameters. 

Reproducer:
```
import zio.*
import zio.test.*

object Testing extends ZIOSpecDefault {
  case class Test[A](a: Int)

  def create[A: Tag] = ZLayer.succeed(Test[A](1))

  val handlers = ZLayer.scoped {
    for {
      i <- ZIO.service[Test[Int]]
      l <- ZIO.service[Test[Long]]
    } yield ()
  }
  
  def spec = test("test") {
    for {
      _ <- ZIO.unit
    } yield assertTrue(1 == 1)
  }.provide(handlers, create[Int], create[Long])
}
```

I'm know we can work around the problem by wrapping the layer classes in new classes without type parameters, but it's not very convenient in our case. Hopefully it's easy to fix for a macro guru! :smiley: 
Thanks for your great work!

**Comment by adamgfraser** [comment]
Note that this only makes sense if the parameterized type is invariant so while this should with invariant types I would probably recommend creating a new nominal type regardless so you are not relying on this.

**Comment by neko-kai** [comment]
@davidlar This shouldn't happen on recent izumi-reflect versions, can you confirm the problem still reproduces on latest zio?

**Comment by shawjef3** [comment]
I confirmed this compiles with ZIO 2.0.19 and Scala 2.13.12 and Scala 3.3.1.

```scala
import zio._
import zio.test._

object Testing extends ZIOSpecDefault {
  case class Test[A](a: Int)

  def create[A: Tag]: ULayer[Test[A]] = ZLayer.succeed(Test[A](1))

  val handlers: ULayer[Test[Int] & Test[Long]] =
    create[Int] ++ create[Long]

  def spec = test("test") {
    for {
      _ <- ZIO.service[Test[Int]]
      _ <- ZIO.service[Test[Long]]
      _ <- ZIO.unit
    } yield assertTrue(1 == 1)
  }.provideSome[TestEnvironment with Scope](handlers)
}
```
