### ISSUE TITLE
zio.Config to allow not delimited string value

### ISSUE THREAD

**Issue by domartynov** [zio/zio#7716]
Cannot figure out how to pass JSON config via env var hitting the default comma delimiter in the default `ConfigProvider`.

E.g. 
```scala
  val config: Config[JsonConfig] = (
    string("JSON_CONFIGS")
      .mapOrFail(_.fromJson[Chunk[JsonConfig]].leftMap(Config.Error.InvalidData(Chunk.empty, _)))
```
Trying to bypass splitting using `secret` but i think there is a bug, so it does not work here: https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ConfigProvider.scala#L114

What's the idea behind splitting at the provider level instead of at `Config` level? 

Can we add a `RawString` primitive to skip splitting similar to `SecretType`? @adamgfraser

**Comment by domartynov** [comment]
probably `RawString` is not a good idea, as we already have `Sequence`. Maybe not to split in `Flat.load` eagerly but pass whether to split via a parameter and modify `loop` to pass `true` for a sequence and `false` for primitives? 🤔

**Comment by adamgfraser** [comment]
@domartynov Thanks for reporting! Can you create a simple reproducer with a configuration you are trying to load and I will take a look?

**Comment by domartynov** [comment]
Pushed a test that reproduces the issue in https://github.com/zio/zio/pull/7721/files @adamgfraser 
I think `ConfigProvider.fromEnv` is eager to split a string even in the case when a single value is expected.

**Comment by adamgfraser** [comment]
@domartynov Thanks! Will take a look. Note that you can get your test to work now by using `ConfigProvider.fromEnv` and specifying a sequence delimiter that is not `,`.
