### ISSUE TITLE
ConfigProvider.fromEnv should allow option to transform keys in and out

### ISSUE THREAD

**Issue by patroza** [zio/zio#7727]
Currently there is no conversion done (except nesting `.` -> `_`), and the rest of the format for Flat or Map is the same as for environment variables.
Which seems awkward to me.

Now if I define a Config, and want to read from Env, I am kind of forced to use ugly upper-case key names in my Config, making the Config specialised for Environment variables.
Or I must break with convention and live with `camelCase` key names to fit with Flat or Map providers.

## Proposal

1) Able to specify the key conversion from and to the Env.
2) Perhaps add the following as a default?

The convention for environment variables classically is `UPPERCASE`,
word separation is clasically with `_` so: `HOST_PORT`.
Nesting is currently also done with `_`, so I would instead propose `__` to avoid reasonable colissions.

key - current - suggestion
- `host` - `host` -> `HOST`
- `hostPort` - `hostPort` -> `HOST_PORT`
- `hostPort.port` - `hostPort_port` -> `HOST_PORT__PORT`

**Comment by adamgfraser** [comment]
@patroza There is no need for transforming the keys. The implementation will already upper case the keys for you. You can change the delimiter if you want but I think the current default makes sense.

```scala
      test("keys are upper cased") {
        for {
          _      <- TestSystem.putEnv("KEY", "value")
          config <- ConfigProvider.envProvider.load(Config.string("key"))
        } yield assertTrue(config == "value")
      }
```

**Comment by patroza** [comment]
@adamgfraser thanks, indeed a fork-error, didn't look closely enough in zio, my bad.
I think camelCase conversion could still be improved as per suggestion, and I would probably want to do that in my App,
so the ability to provide a conversion would imo still be useful.

**Comment by adamgfraser** [comment]
@patroza You can use camel case as well.

```scala
      test("camel case works too") {
        for {
          _      <- TestSystem.putEnv("MYKEY", "value")
          config <- ConfigProvider.envProvider.load(Config.string("myKey"))
        } yield assertTrue(config == "value")
      }
```

**Comment by patroza** [comment]
@adamgfraser 
```scala
test("camel case to constant case works too") {
        for {
          _      <- TestSystem.putEnv("MY_KEY", "value")
          config <- ConfigProvider.envProvider.load(Config.string("myKey"))
        } yield assertTrue(config == "value")
      }
  ```

Case conversion samples
“my key”
“MyKey” - pascal
“myKey” - camel
“my_key” - snake
“MY_KEY” - constant

**Comment by adamgfraser** [comment]
@patroza Yeah that isn't an issue of the case that is an issue of if you are going to include an underscore you need to actually include the underscore:

```scala
      test("camel case to constant case works too") {
        for {
          _      <- TestSystem.putEnv("MY_KEY", "value")
          config <- ConfigProvider.envProvider.load(Config.string("my_Key"))
        } yield assertTrue(config == "value")
      }
```

**Comment by patroza** [comment]
@adamgfraser alright, I beg to differ.
Just uppercasing things is imo loosing resolution.
Instead a case conversion is imo the correct approach.
That said, if I’m alone in that, it’s fine. 
Having a converter option I can specify would be great, but otherwise I stick to forking :)

**Comment by adamgfraser** [comment]
@patroza Different `ConfigProvider` implementations are free to do whatever they want but it feels like that is an implementation detail where we want to just specify what we want `Config.string("key")` and have that transformed into the appropriate representation for the `ConfigProvider` (e.g. `KEY`).

**Comment by patroza** [comment]
@adamgfraser nice. Do you prefer comments here or in PR?
I like that it’s flexible, like aop. But I’m not sure yet how I feel about the double conversion. Once in the provider and once in the wrapper.

**Comment by adamgfraser** [comment]
@patroza Not sure what you mean. There is only one conversion.

**Comment by patroza** [comment]
> @patroza Not sure what you mean. There is only one conversion.

`ConfigProvider.fromEnv`
`def makePathString(path: Chunk[String]): String         = path.mkString(pathDelim).toUpperCase`

So this fails:
```scala
      test("contramapPath2") {
        val configProvider = ConfigProvider.fromEnv().contramapPath(v => v + "test")
        for {
          _      <- TestSystem.putEnv("KEYtest", "VALUE")
          result <- configProvider.load(Config.string("key"))
        } yield assertTrue(result == "VALUE")
      }
```
And this succeeds:
```scala
      test("contramapPath2") {
        val configProvider = ConfigProvider.fromEnv().contramapPath(v => v + "test")
        for {
          _      <- TestSystem.putEnv("KEYTEST", "VALUE")
          result <- configProvider.load(Config.string("key"))
        } yield assertTrue(result == "VALUE")
      }
```

But I think it's perhaps alright. the Env provider does a final "let's make sure it's all caps",
he does the bare minimum, without an opinion on other conversion rules, which instead we can now do with `contramapPath`

**Comment by adamgfraser** [comment]
Yeah I think we need to distinguish operations on config providers, which should give people the ability to express their custom logic, with specific config provider instances, which should be optimized for the expected case of how configuration information from these sources is typically represented.

`contramapPath` is great if you want to do more "fancy" transformations but it would be unfortunate if you had to use that all the time and the basic case of `Config.string("key")` didn't work across common config providers.

**Comment by patroza** [comment]
@adamgfraser yea thanks, I think it's fair.


This succeeds, and that's what I'm after so :)
```scala
      test("contramapPath2") {
        val configProvider = ConfigProvider.fromEnv("__").contramapPath(v =>"[A-Z\\d]".r.replaceAllIn(v, {m =>
          "_" + m.group(0).toLowerCase()
        }))
        for {
          _      <- TestSystem.putEnv("KEY_TEST__CHILD", "VALUE")
          result <- configProvider.load(Config.string("child").nested("keyTest"))
        } yield assertTrue(result == "VALUE")
      }
```

**Comment by adamgfraser** [comment]
@patroza Nice!

**Comment by patroza** [comment]
@adamgfraser thanks for yet another great, and swift Config enhancement :)
This is starting to become really neat, and useful!

**Comment by adamgfraser** [comment]
@patroza Thanks for your feedback and pushing us to make it better!
