### ISSUE TITLE
Performance issue with `ZPipeline.utf8Decode` and `ZPipeline.splitLines`

### ISSUE THREAD

**Issue by rfkm** [zio/zio#7733]
Hi. I tried `ZPipeline.utf8Decode` and `ZPipeline.splitLines` to read files line by line, but ran into performance problems. On the other hand, zio-nio's `Files.lines` are acceptably fast. The following are actual measurements in my environment. Is there any room for improvement?

```scala
val path = "/path/to/file" // 3GB, 56053737 lines 

// 5 sec
Files.lines(zio.nio.file.Path(path)).runDrain

// 84 sec
ZStream.fromPath(Paths.get(path))
  .via(ZPipeline.utf8Decode >>> ZPipeline.splitLines).runDrain

// 24 sec
ZStream.fromPath(Paths.get(path))
  .via(ZPipeline.utf8Decode).runDrain
```

**Comment by adamgfraser** [comment]
@rfkm Thanks for reporting! Will take a look!

**Comment by adamgfraser** [comment]
@rfkm This should be dramatically faster now. Do you want to try running your benchmarks on the latest snapshot?

**Comment by rfkm** [comment]
Thank you so much! I have confirmed that its performance has greatly improved, although `Files.lines` is still a bit faster.

```scala
// 8 sec
ZStream.fromPath(Paths.get(path)).via(ZPipeline.utf8Decode >>> ZPipeline.splitLines).runDrain

// 5 sec
ZStream.fromPath(Paths.get(path))
  .via(ZPipeline.utf8Decode).runDrain

// 1.6 sec
ZStream.fromPath(Paths.get(path)).runDrain
```
Another thing I noticed is that the chunk size of `Files.lines` is fixed at 4096, but with `ZPipeline` it is less than 100 (probably depending on the line length. This may also mean that `fromPath` is a bit safer in terms of memory usage). This significantly affects the performance of subsequent operators. So, to get performance close to `Files.lines` in a real-world application, I had to set the chunk size of `fromPath` appropriately.
Anyway, you may close this issue now that it has achieved reasonable performance. 
Again, thank you!
