### ISSUE TITLE
Enhance ConfigProvider structural operators

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7759]
- `ConfigProvider#unnested` - The opposite of nested, such that `p.nested("foo").unnested("foo") == p`.
 -  `ConfigProvider#within(path: Chunk[String])((p: ConfigProvider) => p)`. Conceptually splits the config provider into 2 parts: an inner core (`p` in this example), defined by all the config stuff at `path`, and then the outer core. Then unnests the inner core by the path, and passes it to the specified function, which transforms it. Then nests the transformed provider at `path`, and finally reincorporates it into the outer core, to form a whole. Among others, `p.within(anyPath)(identity) == p`.

**Comment by adamgfraser** [comment]
Will do.
