### ISSUE TITLE
Think about case operators

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7760]
The user defines their configuration using `(Config.string("name") ++ Config.int("age)).nested("person")` and is able to load that from configuration providers that have different conventions (snake case, camel case, upper case, lower case), in a fashion similar to _ZIO Config_.

cc @afsalthaj

**Comment by adamgfraser** [comment]
I think this can be implemented in terms of `ConfigProvider#contramapPath`.

**Comment by jdegoes** [comment]
I agree, but has to be thought through carefully.

I was looking at a developer define config variables as `Config.string("SERVER_URL")`, and it was clear that developers will (1) arbitrarily choose some convention to express their path segment names, and (2) load it in a different part of their application (maybe by a different developer, even) from a config provider that uses some other convention.

There's an impedance mismatch: a developer chooses some style, and then the config provider chooses some style, and then we hope that they work out. 

To solve this, we need to:

1. Force (strongly carrot) users to adopt some naming convention.
2. Be able to change that flexibly for part or all of config (in general the config provider will be composite and come from many different sources); or maybe just be able to standardize the config sources, i.e. require every config source to do the conversion itself from our standardized naming convention.

Not sure what the solution is, but the goal should be that no matter how a developer chooses a naming convention, they should be able to make that `Config` work with any compatible `ConfigProvider`, given sufficient massaging.

**Comment by adamgfraser** [comment]
Yes. So for the first part it seems, at least from our tests, like our encouraged naming convention is camel case (e.g. `Config.string("hostPorts")`. We can definitely encourage this in the documentation.

For the second, I think we have the tools now in terms of `contramapPath` and the structural operators we implemented. It seems like what is missing is having some more specific operators (e.g. `upperCase`) implemented on `ConfigProvider` in terms of `contramapPath` that perform common transformations that reflect the domain.

Does that make sense?

**Comment by jdegoes** [comment]
Yes, I think it makes sense.

There is a little bit of tension between providing operators and adopting a convention:

1. On the one hand, we can say that Config should adopt camelCase, and that every ConfigProvider must ASSUME camelCase and translate into the underlying provider's case automatically.
2. On the other hand, we provide conversion operators so that you can fix mistakes in (a) how the Config was described; and / or (b) how the ConfigProvider was implemented.

Currently we don't provide variations for the flat providers and it's not clear that adding a bunch of booleans is the best solution. So maybe adding such operators is useful even in spite of (1).
