### ISSUE TITLE
ZIO magic (provide method) potential bug

### ISSUE THREAD

**Issue by guygo87** [zio/zio#7766]
Hey, I'm a software developer from Wix, and while working on one of our open source projects we encountered the following issue:

When using `provide` method to build the dependency tree automatically in unit tests, those tests become flaky.
It looks like some layers are shared / leaking between tests, or something similar. 

When using `provideLayer`, and building the dependency tree manually everything is working fine.

I've created a [PR](https://github.com/wix/greyhound/pull/538) with a single change to reproduce this issue. Feel free to use it

**Comment by adamgfraser** [comment]
@guygo87 Thanks for reporting! If you can create a small reproducer happy to take a look!

**Comment by adrian-2414745** [comment]
happened to me also.

**Comment by 987Nabil** [comment]
@guygo87 I took a short look at your pr and I am pretty sure, that the layer wiring is not equivalent. In the manual provide for example, you use the same layer twice, so it produces twice.
Maybe you could try layer debugging to find more differences and check, if the differences in construction might be the problem and not zio it self.
https://zio.dev/reference/di/automatic-layer-construction/#zlayer-debugging
@adrian-salajan you might have a similar issue.

**Comment by guizmaii** [comment]
@guygo87 Seeing Nabil's comment, can we close this issue?

**Comment by guygo87** [comment]
yes, you can close it. Thank you very much
