### ISSUE TITLE
ZIO state-management docs conflict

### ISSUE THREAD

**Issue by burakakca** [zio/zio#7773]
[Index MD](https://github.com/zio/zio/blob/series/2.x/docs/reference/state-management/global-shared-state.md)- ZIO has a powerful data type called Ref, which is the description of a mutable reference. ```We can use Ref to share the state between multiple fibers```, e.g. producer and consumer components.

[Global shared State](https://github.com/zio/zio/blob/series/2.x/docs/reference/state-management/global-shared-state.md) ```We cannot share the state between multiple fibers.```

Also in below example, we need the say join for global state?
```scala
import zio._

def getNames: ZIO[Any, String, List[String]] =
  for {
    ref <- Ref.make(List.empty[String])
    f1 <- Console
      .readLine("Please enter a name or 'q' to exit: ")
      .orDie
      .repeatWhileZIO {
        case "q"  => ZIO.succeed(false)
        case name => ref.update(_ appended name).as(true)
      }.fork 
      f2 <- ZIO.foreachDiscard(Seq("John", "Jane", "Joe", "Tom")) { name =>
        ref.update(_ appended name) *> ZIO.sleep(1.second)
      }
      .fork
    _ <- f1.join
    _ <- f2.join
    v <- ref.get
  } yield v
```

**Comment by adamgfraser** [comment]
@khajavi Can you take a look?

**Comment by khajavi** [comment]
@burakakca 
There are three ways to maintain state:
- Through Recursive Functions
- Global Shared State -> `Ref`
- Fiber-local State -> `FiberRef` and `ZState`

The first and last solution is not for sharing between multiple fibers.

**Comment by burakakca** [comment]
I didn't understand. Can you expand what did you want to say with example.

**Comment by adamgfraser** [comment]
@burakakca State maintained in a `FiberRef` (and `ZState`, which is implemented in terms of `FiberRef` is specific to each fiber. So two different fibers each have different values for a `FiberRef`. This can be very useful because each fiber can modify its own value of the `FiberRef` without impacting the other fiber. However, for the same reason it cannot be used to represent state that is shared between fibers. For that you want a `Ref`.

**Comment by khajavi** [comment]
1. In the following example, we maintain the user inputs inside recursive function arguments:

```scala
import zio._

def inputNames: ZIO[Any, String, List[String]] = {
  def loop(names: List[String]): ZIO[Any, String, List[String]] = {
    Console.readLine("Please enter a name or `q` to exit: ").orDie.flatMap {
      case "q" =>
        ZIO.succeed(names)
      case name =>
        loop(names appended name)
    }
  }

  loop(List.empty[String])
}
``` 

2. We can rewrite the previous example using `Ref`:

```scala
import zio._

def getNames: ZIO[Any, String, List[String]] =
  Ref.make(List.empty[String])
    .flatMap { ref =>
      Console
        .readLine("Please enter a name or 'q' to exit: ")
        .orDie
        .repeatWhileZIO {
          case "q" => ZIO.succeed(false)
          case name => ref.update(_ appended name).as(true)
        } *> ref.get
    }
```

But the ref is more powerful and we can share the state between multiple fibers. Assume you have two sources of inputs (e.g. file and socket) and you want to append all inputs into the same memory location. The `Ref` can do that for you:

```scala
import zio._

def getNames: ZIO[Any, String, List[String]] =
  for {
    ref <- Ref.make(List.empty[String])
    f1 <- Console
      .readLine("Please enter a name or 'q' to exit: ")
      .orDie
      .repeatWhileZIO {
        case "q"  => ZIO.succeed(false)
        case name => ref.update(_ appended name).as(true)
      }.fork 
      f2 <- ZIO.foreachDiscard(Seq("John", "Jane", "Joe", "Tom")) { name =>
        ref.update(_ appended name) *> ZIO.sleep(1.second)
      }
      .fork
    _ <- f1.join
    _ <- f2.join
    v <- ref.get
  } yield v
```  

In the above example, we have two fibers `f1` and `f2` which produce inputs, and the `ref` maintains both names produced by these two fibers.

3. Sometimes we have some contextual state that we should maintain, e.g. logging context, we can use Fiber-local data types like `FiberRef` and `ZState`. There are some good examples on zio.dev. In case of any ambiguity, please reach out, and I'll try to elaborate more.
