### ISSUE TITLE
Is there a way to attach attributes/annotations to `Cause`?

### ISSUE THREAD

**Issue by domartynov** [zio/zio#7778]
Today we can use two patterns to attach and log more info with a failure in ZIO:
1) `ZIO.logAnnotate` which is nice because there is no need to explicitly propagate details down the stack to the point where logging happens, but there are two issue with this approach:
  - usually logging happens not in the same scope as the source of a failure (ideally at framework level, e.g. HTTP request handler/middleware) so context is lost
  - alternative is doing logging at lower-level closer to failure, but i think low-level libraries usually do not have a good context to even understand the proper logging level. So (unless for debug level logging) it is problematic. E.g. `zio-jdbc` uses `ZIO.logError` to capture SQL atm here: https://github.com/zio/zio-jdbc/blob/main/core/src/main/scala/zio/jdbc/ZConnection.scala#L91
2) Wrap an underlying error into a custom error with additional data. The problem here is (besides being boilerplate in general) it plays agains ZIO strength in error handling where the typed error channel is reserved for the errors to have meaning and to be handled but a caller. While we just try to attach details relevant to a scope (e.g. requestId, userId) regardless of a kind of failure.

Not sure if my use case is clear, please see this feature of Sentry SDK (especially how well it integrated in Kotlin coroutines): https://docs.sentry.io/platforms/java/scope/. I think ZIO can support this approach even better than Koltlin and maybe the mechanism should be a part of ZIO core to contribute to ZIO's batteries included approach.

I'm not sure if `Cause` is the right place to solve it. Or a separate `FailureContext` (`LoggingContext` maybe) akin Sentry's `Scope` is more appropriate. Or maybe both as scope/contexts (as `Scope` is reserved notion in ZIO) should be matched with stack traces 🤔

**Comment by jdegoes** [comment]
_ZIO Logging_ lets you do things like:

```scala
myEffect @@ userId(user.id)
```

In addition, soon it will support structured logging for any user-defined data type.

Is this sufficient?

**Comment by adamgfraser** [comment]
I think the problem is more:

```scala
object Example extends ZIOAppDefault {

  def someLibraryCode(n:): ZIO[Any, Nothing, Int] =
    ZIO.fail("library failure")

  val myWorkflow =
    someLibraryCode @@ annotated("userId", "42")

  val run =
    myWorkflow.catchAllCause { cause =>
      ??? // annotation is not available here  
    }
}
```

If `someLibraryCode` doesn't want to actually log the error but just to pass it back as a failure to the caller so they can handle it however they want, then the error itself doesn't contain the information on the log annotations at the point at which the failure occurred. So outside the scope of `annotated` that information is no longer available.

**Comment by jdegoes** [comment]
Hmm. I wonder if `Cause` should automatically be augmented with all log annotations?

That's kind of a super cool feature that can't be done in Java.

**Comment by adamgfraser** [comment]
Yes I think it will be challenging to do that in a binary compatible way given operators and data types that expose the structure of `Cause` such as `fold` and `Folder` but maybe could be a good feature for ZIO 3?

**Comment by adamgfraser** [comment]
Maybe there is a way to work around that.

**Comment by jdegoes** [comment]
A subtype on one or more of the case classes would do it. Probably the leaf nodes.

**Comment by adamgfraser** [comment]
Yes I think it makes more sense on the leaf nodes.
