### ISSUE TITLE
Add `Config` usage to reference documentation on zio.dev

### ISSUE THREAD

**Issue by williamareynolds** [zio/zio#7780]
I've been using https://github.com/zio/zio-config to do configuration for my applications, but usually I only have 2-3 variables and they always come directly from the environment. These are very small microservices, and there genuinely isn't a need for much more than this. I only found out about `ZIO#config` and its related `Config` type recently, but I'm having a hard time finding much documentation for it. Most of the usage examples I can find are in the github issues, usually demonstrating a problem rather than practical usage. 
`zio-config` is great, but probably overkill for my case. The built-in config features of ZIO seem like they might be perfectly suited, but I have a team of engineers who I won't be able to convince if there isn't rich documentation.

**Comment by adamgfraser** [comment]
@khajavi Can you take a look at this?

**Comment by jdegoes** [comment]
@khajavi We need a whole section on configuration that explains:

 - `Config`
 - `ConfigProvider`
 - `ZIO.config`
 - `Runtime.addConfigProvider`

As well as how to test config or code that depends on config, for example, by using test environment variables or test system properties (probably we need a `TestConfigProvider` at some point to simplify).
