### ISSUE TITLE
dayOfHour(x) && (minuteOfHour(y) || minuteOfHour(z)) doesn't run on minuteOfHour(z)

### ISSUE THREAD

**Issue by evis** [zio/zio#7783]
Code: https://scastie.scala-lang.org/So7eV9wpTu2qabrfahMlMA

```scala
import zio.Schedule.Decision._
import zio.{Runtime, Unsafe}
import zio.Schedule._
import java.time.OffsetDateTime

val now = OffsetDateTime.parse("2023-02-04T18:48:00+03:00")
val zioSchedule = hourOfDay(18) && (minuteOfHour(53) || minuteOfHour(58))
val effect = for {
  (state, _, decision) <- zioSchedule.step(now, (), state = zioSchedule.initial)
  interval1 = decision.asInstanceOf[Continue].interval
  (state, _, decision) <- zioSchedule.step(now = interval1.end, (), state = state)
  interval2 = decision.asInstanceOf[Continue].interval
  (state, _, decision) <- zioSchedule.step(now = interval2.end, (), state = state)
  interval3 = decision.asInstanceOf[Continue].interval
} yield {
  println(s"${interval1.start} -> ${interval1.end}")
  println(s"${interval2.start} -> ${interval2.end}")
  println(s"${interval3.start} -> ${interval3.end}")
}
Unsafe.unsafe { implicit unsafe =>
  Runtime.default.unsafe.run(effect)
}
```

Expected output:

```
2023-02-04T18:53+03:00 -> 2023-02-04T18:54+03:00
2023-02-04T18:58+03:00 -> 2023-02-04T18:59+03:00
2023-02-05T18:53+03:00 -> 2023-02-05T18:54+03:00
```

Actual output:

```
2023-02-04T18:53+03:00 -> 2023-02-04T18:54+03:00
2023-02-05T18:53+03:00 -> 2023-02-05T18:54+03:00
2023-02-06T18:53+03:00 -> 2023-02-06T18:54+03:00
```

So, it runs on minuteOfHour(53), but doesn't run on minuteOfHour(58).

If we remove hourOfDay(18), then it runs as expected: https://scastie.scala-lang.org/VabbUaEwSsGucWNvF9KNWw

**Comment by evis** [comment]
Looks like here's a bug: https://github.com/zio/zio/blob/ba58425b23a4beb60b511ce2bb5babafc40de591/core/shared/src/main/scala/zio/Schedule.scala#L1862-L1865

We shouldn't immediately move to the next day, since there's a possibility that we still need to run more schedule executions during current hour. The same bug lies in other private nextXXX methods.

**Comment by adamgfraser** [comment]
I don't think this is correct. The semantics of `Schedule.dayOfHour` is that it wants to run once during the hour of the current day and the next time it wants to run is the next day. Otherwise it would never make progress if it was not composed with another schedule.

**Comment by evis** [comment]
Ok, I see. I will make several schedules then, and run them all. Thanks for your help!
