### ISSUE TITLE
doc code box selection highlighting is barely perceivable

### ISSUE THREAD

**Issue by tnielens** [zio/zio#7788]
The code boxes of the doc site uses a barely perceivable color. Would a lighter grey be better? In the example below, the dependency coordinates are highlighted. I tried to copy them to add them to my project.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/11885535/216822049-ad6c3510-1f12-4624-82a2-8ddb8e688ef1.png">

**Comment by adamgfraser** [comment]
@tnielens Not sure I understand. In what you pasted above the code box is in black and the text inside it `libraryDependencies += "dev.zio" %% "zip" % "2.0.6"` is in light grey so the contrast is extremely strong and it is extremely readable. Or are you referring to the copy and paste oval in the top right of the code box?

**Comment by tnielens** [comment]
If you try to select the code box partially, the selected text is highlighted in dark grey. The screenshot above illustrates this. The part `"dev.zio" %% "zip" % "2.0.6"` is highlighted. The dark grey is very similar to the the black background. It's easier to notice if you zoom in a little bit.

**Comment by adamgfraser** [comment]
I think that may be browser dependent. It looks relatively clear to me.

@khajavi You want to see if there is something we can do about this?
