### ISSUE TITLE
Ensure every ConfigProvider translates from camel case appropriately

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#7807]
By default, we are assuming that users describe names with camel case, e.g. `serverSettings`. Each ConfigProvider needs to translate from our "default case" into the naming convention appropriate to the configuration source.

This means that `Config.string("serverSettings")` should translate to `SERVER_SETTINGS` in the environment variable name source. For properties, it is less clear what to do, since camel case appears in property files, but so do snake case and dots.

**Comment by adamgfraser** [comment]
We already capitalize names in `ConfigProvider.fromEnv`. We don't currently insert underscores but we can implement that easily in terms of existing operators on `ConfigProvider`. I agree it is less clear what to do with properties. Potentially we need to defer this to the user and they can express the format they are using in terms of `ConfigProvider` operators such as `kebabCase`, `snakeCase`, and so on.

**Comment by jdegoes** [comment]
So should we implement the underscore, or leave that to user discretion?

**Comment by adamgfraser** [comment]
I tend to think we should leave it to user discretion. The other thing we need to think about is how this interacts with the convention for path delimiters. Currently the default path delimiter for environment variables is `_`, so an environment variable like `HOSTPORT_HOST` would be accessed using `Config.string("host").nested("hostPort")`. If we added an underscore then the environment variable would have to be written as `HOST_PORT_HOST` which would create ambiguity (is the `_` delimiting the path or part of one of the path segments?) or require us to use a different default delimiter which I think would be less standard.

**Comment by jdegoes** [comment]
All right, will close this, and perhaps @khajavi's documentation can cover these issues at length on [zio.dev](https://zio.dev).
