### ISSUE TITLE
acquireRelease hanging with TestAspect.withLiveClock

### ISSUE THREAD

**Issue by ghost** [zio/zio#7822]
Hi,

When using "acquireRelease" with "TestAspect.withLiveClock", hanging  in release function at ZIO.sleep.
Example code is here. Is there something wrong?

```
  "dev.zio" %% "zio" % "2.0.8",
  "dev.zio" %% "zio-test" % "2.0.8" % Test,
  "dev.zio" %% "zio-test-sbt" % "2.0.8" % Test,
  "dev.zio" %% "zio-test-magnolia" % "2.0.8" % Test
```

```
object TestHelloWorldWithLiveClock extends ZIOSpecDefault{

  object HelloWorld{
    def layer1 = ZLayer{
      ZIO.acquireRelease {
        ZIO.succeed(new HelloWorld())
      } { _ => Console.printLine("Closed.").orDie }
    }
    def layer2 = ZLayer{
      ZIO.acquireRelease {
        ZIO.succeed(new HelloWorld())
      }{ _ =>
        for {
          _ <- Console.printLine("[close] begin").orDie
          _ <- ZIO.sleep(3.seconds)
          _ <- Console.printLine("Closed.").orDie
        } yield ()
      }
    }
  }

  class HelloWorld() {
    def sayHello: ZIO[Any, IOException, Unit] =
      ZIO.sleep(3.seconds) *> Console.printLine("Hello, World!")
  }

  def spec =
    suite("Sample")(test("sample"){
        for {
          service <- ZIO.service[HelloWorld]
          _ <- service.sayHello
          output <- TestConsole.output
        } yield assertTrue(output == Vector("Hello, World!\n"))
      }
    ).provideLayer(HelloWorld.layer2) @@ TestAspect.withLiveClock
}
```

* HelloWorld.layer1 dose work.
* HelloWorld.layer2 doesn't work.

**Comment by adamgfraser** [comment]
@yshyya Hi! The fiber that closes a scope may not be the same one that added the finalizer to the scope and so may not have the same `FiberRef` values. You can get your example to work by doing `Live.live(ZIO.sleep(3.seconds))` in the finalizer.

**Comment by ghost** [comment]
@adamgfraser Thanks your response.

Yes `Live.live(ZIO.sleep(3.seconds))` dose work.
but above example is minimal reproduction  and `Live.live` is `zio.test` package. 

In actual code `HelloWorld.layer2`  is not in test package and `Live.live` can't use there.
Without `Live.live` is there any way to do?

**Comment by adamgfraser** [comment]
@yshyya Yes you can do `ZIO.sleep(3.seconds).withClock(Clock.ClockLive)`.

**Comment by ghost** [comment]
@adamgfraser Thank you very much. it works.

**Comment by adamgfraser** [comment]
@yshyya No problem!
