### ISSUE TITLE
catchAllCause does not catch interruptions 

### ISSUE THREAD

**Issue by mykytamykhailenko** [zio/zio#7825]
Hello!
I have a small question. Please, look at the following snippet.

```
import zio._

object App extends ZIOAppDefault {

  override def run = for {

    p <- Promise.make[Nothing, Unit]

    fib <- ZIO.sleep(3.second).catchAllCause(_ => p.succeed()).fork

    _ <- fib.interrupt

    _ <- p.await

  } yield ()

}
```

I thought that code would be equivalent to this one.

```
import zio._

object App extends ZIOAppDefault {

  override def run = for {

    p <- Promise.make[Nothing, Unit]

    fib <- ZIO.sleep(3.second).onInterrupt(_ => p.succeed()).fork

    _ <- fib.interrupt

    _ <- p.await

  } yield ()

}
```

But for some reason, `catchAllCause` does not catch the interruption and completes the promise.
So the code is blocked forever.

**Comment by adamgfraser** [comment]
@mykytamykhailenko That is correct. External interruption can never be recovered from. Someone else is telling you that you must stop and while you can wind down by running finalizers installed with operators such as `onInterrupt` you can never "catch" external interruption.

**Comment by mykytamykhailenko** [comment]
Could you please tell if it is possible to have an internal interruption?
Hopefully, this question makes sense :)

**Comment by adamgfraser** [comment]
Yes a fiber can "interrupt itself" by using `ZIO.interrupt`.

**Comment by mykytamykhailenko** [comment]
I see, now it makes much more sense. Thanks a lot!
