### ISSUE TITLE
update doc on zio-test-junit sbt support

### ISSUE THREAD

**Issue by tnielens** [zio/zio#7831]
The doc says zio-test-junit doesn't support sbt. But it seems to support it fine given a slight annotation adjustment: the `RunWith` annotation must be on the user test class and not the parent class.

So this example is executed as expected by `sbt test`
```scala
import zio._
import zio.test.{test, _}
import org.junit.runner.RunWith
import zio.test.junit.ZTestJUnitRunner

@RunWith(classOf[zio.test.junit.ZTestJUnitRunner])
class MySpec extends ZIOSpecDefault {
  def spec = suite("MySpec")(
    test("test") {
      for {
        _ <- ZIO.unit
      } yield assertCompletes
    }
  )
}
```
with this test dependency
```scala
    .settings(libraryDependencies += "com.github.sbt" % "junit-interface" % "0.13.2" % Test)
```

The test class finder logic in the sbt plugin is in [RunWithFingerPrint](https://github.com/sbt/junit-interface/blob/f8c6372ed01ce86f15393b890323d96afbe6d594/src/main/java/com/novocode/junit/RunWithFingerprint.java#L3).

**Comment by adamgfraser** [comment]
@khajavi Can you take a look?

**Comment by khajavi** [comment]
> @khajavi Can you take a look?

Will do!
