### ISSUE TITLE
TMap Vs. ConcurrentMap

### ISSUE THREAD

**Issue by mykytamykhailenko** [zio/zio#7833]
Hello, everyone!

I have created an application where I need to store a lot of entities in a map.
The map will be accessed concurrently, so I have to decide between `TMap` or `ConcurrentMap`.
The point of confusion is as far as I know, If I will use `TMap`, the application may become memory intensive.
My end goal is to reduce the memory footprint as much as possible.
Could you please advice how to approach the problem?

**Comment by mykytamykhailenko** [comment]
The point is, I will often need to collect all entities from the map.
So in case of `TMap` I will often call `.toMap.commit`
Besides, the map will be nested:, here is a quick example: `TMap[Int, TMap[Int, Entity[T]]]`

**Comment by adamgfraser** [comment]
It depends what guarantees you need. Both a `TMap` and a `ConcurrentMap` are safe for concurrent access. However, a `ConcurrentMap` only allows the value of a single key to be modified atomically whereas a `TMap` allows modifications of multiple keys to be performed as a single transaction. So I would use the least powerful data structure you need. A `ConcurrentMap` is definitely going to be faster than a `TMap`.

**Comment by mykytamykhailenko** [comment]
I don't really need transactional capabilities of `TMap`, so I think `ConcurrentMap` is the way out

Thank you for you suggestion :)
