### ISSUE TITLE
Description about `ZIO.attemptBlocking`'s limit in documents

### ISSUE THREAD

**Issue by jahun-kim** [zio/zio#7839]
there is a description about `ZIO.attemptBlocking` in the document (https://zio.dev/reference/core/zio/#creating-blocking-effects)
> The contract is that the thread pool will accept unlimited tasks (up to the available memory) and continuously create new threads as necessary.

but ZIO's `defaultBlockingExecutor` is using `ThreadPoolExecutor` with `SynchronousQueue` as worker queue and `1000` as max thread pool size.
doesn't it occur `RejectExecutionException` when submitting task under the situation that 1000 threads are all busy even with the available memory?

**Comment by adamgfraser** [comment]
@jahun-kim The `maxPoolSize` is `Int.MaxValue`.

**Comment by jahun-kim** [comment]
oh it changed since `v2.0.9`! I missed to check latest version 😅
