### ISSUE TITLE
'groupByKey' execute effect for each subsequent stream

### ISSUE THREAD

**Issue by mykytamykhailenko** [zio/zio#7846]
I have a piece of code where I execute following code

```
stream.groupByKey(_.entityID, chunkSize)((entityID, stream) =>
            registererPool(entityID).registerPartition(partition, stream))
```

The `registerPartition` is a simple ZIO effect, not a `ZStream`.

So, I want to execute the effect for each sub-stream, but `ZStream.GroupBy.apply` requires the use of `ZStream`.

Could you advice on how I can overcome this challange?

**Comment by adamgfraser** [comment]
@mykytamykhailenko You can use `ZStream.fromZIO` to convert any `ZIO` workflow to a stream.

**Comment by mykytamykhailenko** [comment]
Wow, that helps a lot!
