### ISSUE TITLE
ZStream.zipAllSortedByKey loses exception and cause stream hang-up

### ISSUE THREAD

**Issue by liewhite** [zio/zio#7878]
Reproduce the behavior:
```scala
object Main extends ZIOAppDefault {
  def run = {
    val s1 = ZStream(1, 2, 3, 4).map(i => { throw Exception("s1"); (i, i) })
    val s2 = ZStream(5, 6, 7, 8).map(i => { throw Exception("s2"); (i, i) })
    s1.zipAllSortedByKey(s2)(0, 0)
      .run(ZSink.foreach(i => ZIO.logInfo(i.toString())))
  }
}
```

Is this expected?  Or how may i workaround this.

**Comment by vigoo** [comment]
Thanks for reporting! It is definitely not expected. As a workaround you can use `mapZIO(i => ZIO.succeed { ... })` for now. (Or `ZIO.attempt` if you want to capture the exception as a typed error)

**Comment by adamgfraser** [comment]
Will take a look.
