### ISSUE TITLE
`ZStream#throtleShape` emits more elements than expected without burst

### ISSUE THREAD

**Issue by guersam** [zio/zio#7888]
I have a rate limit requirement for a third party API.

At first it sounded very easy as I already knew `ZStream#throttleShape`. But when I tested against the real server, several requests were blocked due to the rate limit. Here's a minimal reproduction:

### Step to reproduce
```sh
$ scala-cli https://gist.github.com/guersam/22cb2de7d9be63262c38e463c1484c60
```

```scala
//> using scala "3.2.2"
//> using dep "dev.zio::zio:2.0.9"
//> using dep "dev.zio::zio-test:2.0.9"

import zio.*
import zio.stream.*
import zio.test.*
import java.time.temporal.ChronoUnit

object ThrottleShapeSpec extends ZIOSpecDefault {

  val spec =
    suite("throttleShape")(
      test("delays chunks after limit when burst == 1") {
        for {
          start <- Clock.instant
          fiber <- Queue
            .bounded[Int](30)
            .flatMap { queue =>
              ZStream
                .fromQueue(queue, maxChunkSize = 1)
                .throttleShape(10, 1.second, 0)(_.size.toLong)
                .mapZIOParUnordered(Int.MaxValue)(_ =>
                  Clock.instant.map(start.until(_, ChronoUnit.MILLIS))
                )
                .toPull
                .flatMap { pull =>
                  for {
                    _ <- ZIO.foreachDiscard(1 to 30)(queue.offer)

                    res1 <- pull.replicateZIO(10).map(_.flatten)
                    _ <- assertTrue(res1.forall(i => 0 <= i && i <= 1000))

                    res2 <- pull.replicateZIO(10).map(_.flatten)
                    _ <- assertTrue(res2.forall(i => 1000 <= i && i <= 2000))
                  } yield assertCompletes
                }
            }
            .fork
          test <- fiber.join
        } yield test
      } @@ TestAspect.withLiveClock
    )

}
```

### Expected Result

Given rate limit of 10 per second, the second 10 timestamps should be at least 1 second from `start` because the limit of 10 is already reached within the first second

### Actual Result

The 11th elements is emitted even before 0.3 seconds

```
+ throttleShape
  - delays chunks enough when burst == 0
    ✗ Result was false
    res2.forall(i => 1000 <= i && i <= 2000)
    res2 = List(294, 397, 499, 605, 710, 816, 922, 1025, 1131, 1235)
```

p.s. I'm using `throttleShape` via [rezilience](https://github.com/svroonland/rezilience/blob/v0.9.2/rezilience/shared/src/main/scala/nl/vroste/rezilience/RateLimiter.scala#L62). Although I've tried manually setting burst to 0, had no luck.

**Comment by adamgfraser** [comment]
@guersam I don't think that reflects the token bucket algorithm. In the token bucket algorithm the bucket starts with capacity `units` tokens, here 10. A token is added every `duration / units`, here 100 milliseconds.

You seem to be assuming that after the tokens are taken from the bucket the bucket is not refilled at all until the `duration` elapses and then filled entirely but this is not the specification of the token bucket algorithm and would result in "bursty" network traffic whereas the idea of the algorithm is to smoothly add additional capacity./

**Comment by guersam** [comment]
@adamgfraser Thank you for explaining the token bucket algorithm. Based on my understanding, it may not be suitable for my particular use case. Can you recommend any alternative rate limiting approaches that would be more effective than simply introducing a delay of 100 milliseconds for each call?

**Comment by adamgfraser** [comment]
@guersam I think I would start by thinking about the exact algorithm you want to implement, which may depend on how the rate limited policy of the server works. Then the implementation of `throttleShapeZIO` is fairly straightforward and you can probably just adapt that for your use case. Alternatively `throttleShape` does provide the average rate you are looking for, so if you just have a few requests that are being rate limited you could just retry them.

**Comment by guersam** [comment]
@adamgfraser Thanks again! I took the second approach for now.

**Comment by guersam** [comment]
I ended up implementing my own sliding window throttler with `ZPipeline`. It took only 11 concise lines and works like a charm.

**Comment by adamgfraser** [comment]
Awesome!
