### ISSUE TITLE
zio-test 2.0.9 regression: OOMing Gen

### ISSUE THREAD

**Issue by guizmaii** [zio/zio#7893]
As discussed in Discord, our tests are OOMing since ZIO `v2.0.9`

Here's a minimal reproducer:

```scala

import zio.Scope
import zio.prelude.NonEmptySet
import zio.test.*
import zio.test.Assertion.*
import zio.test.Gen.*

//noinspection SimplifyAssertInspection
object OOMingSpec extends ZIOSpecDefault {

  implicit final class RichNonEmptySetType(private val dummy: NonEmptySet.type) extends AnyVal {
    def unsafe[A](iterable: Iterable[A]): NonEmptySet[A] =
      NonEmptySet
        .fromIterableOption(iterable)
        .getOrElse(throw new RuntimeException("Should never happen: Tried to put an empty set into a NonEmptySet"))
  }

  def nonEmptySet[R, A](gen: Gen[R, A]): Gen[R, NonEmptySet[A]] =
    small(setOfN(_)(gen), min = 1).map(NonEmptySet.unsafe)

  override def spec: Spec[TestEnvironment & Scope, Any] =
    suite("OOMing spec")(
      test("should OOM") {
        check(nonEmptySet(Gen.fromIterable(List("a", "b", "c")))) { v =>
          assert(v)(equalTo(v))
        }
      }
    )
}
```

**Comment by guizmaii** [comment]
FYI, if anyone reads this one day. A solution, suggested by @adamgfraser on ZIO Discord, to fix this OOM is to replace `small(setOfN(_)(gen), min = 1)` by `setOf1(gen)`:
 
 ```scala
package io.conduktor.devtools.api.core.adapters

import zio.Scope
import zio.prelude.NonEmptySet
import zio.test.*
import zio.test.Assertion.*
import zio.test.Gen.*

//noinspection SimplifyAssertInspection
object OOMingSpec extends ZIOSpecDefault {

  implicit final class RichNonEmptySetType(private val dummy: NonEmptySet.type) extends AnyVal {
    def unsafe[A](iterable: Iterable[A]): NonEmptySet[A] =
      NonEmptySet
        .fromIterableOption(iterable)
        .getOrElse(throw new RuntimeException("Should never happen: Tried to put an empty set into a NonEmptySet"))
  }

  def oomNonEmptySet[R, A](gen: Gen[R, A]): Gen[R, NonEmptySet[A]] =
    small(setOfN(_)(gen), min = 1).map(NonEmptySet.unsafe)

  def nonEmptySet[R, A](gen: Gen[R, A]): Gen[R, NonEmptySet[A]] =
    setOf1(gen).map(NonEmptySet.unsafe)

  override def spec: Spec[TestEnvironment & Scope, Any] =
    suite("OOMing spec")(
      test("should pass") {
        check(nonEmptySet(Gen.fromIterable(List("a", "b", "c")))) { v =>
          assert(v)(equalTo(v))
        }
      },
      test("should OOM") {
        check(oomNonEmptySet(Gen.fromIterable(List("a", "b", "c")))) { v =>
          assert(v)(equalTo(v))
        }
      },
    )
}
 ```

**Comment by adamgfraser** [comment]
Going to close this as the original example was attempting to generate a set of a size larger than could possibly be generated given the domain of the values.

**Comment by strokyl** [comment]
> Going to close this as the original example was attempting to generate a set of a size larger than could possibly be generated given the domain of the values.

I don't see why `mall(setOfN(_)(gen), min = 1)` would not produce set with 3 or less elements? There is probably something I missed

**Comment by guizmaii** [comment]
@strokyl What I understood is that the possible values in my example is: `List("a", "b", "c")` and `small(setOfN(_)(gen), min = 1)` might try to create a `Set` containing more than 3 values, which is impossible and will generate this OOM

**Comment by strokyl** [comment]
> @strokyl What I understood is that the possible values in my example is: `List("a", "b", "c")` and `small(setOfN(_)(gen), min = 1)` might try to create a `Set` containing more than 3 values, which is impossible and will generate this OOM

I understood the same thing, and for me this is definitely a bug.

**Comment by vigoo** [comment]
@strokyl if it is a bug, what behavior would you expect instead? If you explicitly say you want to generate a set of N elements (that's what `setOfN` is), producing an output that is _not_ having `N` elements does not seems to be correct. And that's what is happening here - `small` giving an `N` larger than `3`.

**Comment by strokyl** [comment]
> @strokyl if it is a bug, what behavior would you expect instead? If you explicitly say you want to generate a set of N elements (that's what `setOfN` is), producing an output that is _not_ having `N` elements does not seems to be correct. And that's what is happening here - `small` giving an `N` larger than `3`.

I would except setOfN not to OOM but to fail with a proper error message `Input cardinality is too low to generate a set of X elements`.

**Comment by adamgfraser** [comment]
`setofN` doesn't have any concept of the cardinality of the input domain, it just has a generator.

**Comment by strokyl** [comment]
> `setofN` doesn't have any concept of the cardinality of the input domain, it just has a generator.

I just realize it take an other then and not a collection, my bad.
