### ISSUE TITLE
`Metric.modify` not calling `ConcurrentMetricRegistry.notifyListeners`

### ISSUE THREAD

**Issue by ptrdom** [zio/zio#7897]
At [Mesmer](https://github.com/ScalaConsultants/mesmer) project we are working on an [OpenTelemetry](https://opentelemetry.io/) instrumentation library for Scala applications, and we are trying to improve our implementation for integrating ZIO metrics with OpenTelemetry. Looking at https://github.com/zio/zio-metrics-connectors, it seems that there are two approaches, both based on interactions with `ConcurrentMetricRegistry` - Prometheus connector polls `snapshots` periodically and publishes the metrics, however Datadog connector adds a listener to metric updates. It seem to me that using listeners is a cleaner approach and we are thinking of going with it, but looking internally at `Metric` `UnsafeAPI`, we can see that `notifyListeners` is only called for `update` method and not `modify` method. At a quick glance, both of these methods seem to do the same thing, but if the metric is updated using `modify` method, then listeners won't be notified and, in the case of Datadog connector, metrics won't get published. This seems like a bug.

What is the difference between `update` and `modify` methods of `Metrics` `UnsafeAPI`? Should `modify` also notify listeners?

Also, is there a good reason why https://github.com/zio/zio-metrics-connectors is using different approaches of interacting with `ConcurrentMetricRegistry` that we should also consider for Mesmer?

**Comment by adamgfraser** [comment]
Will take a look!

**Comment by adamgfraser** [comment]
For gauges `update` corresponds to setting the gauge whereas `modify` corresponds to incrementing and decrementing it. Both of them should notify the listeners.

As a metric client the metric registry interface is "pull based" where you read from the metric registry when you want to whereas the listener interface is "push based" where the listener is called whenever there is a metric event. So they exist to support metric clients that expect either interface. Though you still might want to aggregate events before sending them  to the metrics client for efficiency.

**Comment by ptrdom** [comment]
@adamgfraser Understood. As you can see code below, `modify` does not notify the listeners, unlike `update` just above it. Should this be fixed?
https://github.com/zio/zio/blob/ba58425b23a4beb60b511ce2bb5babafc40de591/core/shared/src/main/scala/zio/metrics/Metric.scala#L441-L463

**Comment by adamgfraser** [comment]
@ptrdom See above.

**Comment by ptrdom** [comment]
I guess I just did not explicitly understand if you approve that this is a bug and it needs to be fixed. I can create a PR for the fix then.

**Comment by adamgfraser** [comment]
If you look above I already submitted a pull request to fix it.

**Comment by ptrdom** [comment]
Ah, neat, thank you!

**Comment by ptrdom** [comment]
Looking at the how notifications work, I wonder if listeners can discern between setting and incrementing the gauge. In case of setting value to `1` and incrementing by `1`,  the `MetricListener.updateGauge` will receive the key and value of `1`. Is my thinking correct @adamgfraser?

**Comment by adamgfraser** [comment]
@ptrdom Will take a look.

**Comment by ptrdom** [comment]
> Looking at the how notifications work, I wonder if listeners can discern between setting and incrementing the gauge. In case of setting value to `1` and incrementing by `1`, the `MetricListener.updateGauge` will receive the key and value of `1`. Is my thinking correct @adamgfraser?

@adamgfraser I made a small manual test and I am pretty sure that this is correct. I guess it can be worked around by using `ConcurrentMetricRegistry.get` to get the state in the listener implementation before publishing it, though the `value` parameter is useless in the case of gauges then. Since you closed this issue, should the improvements to the listener API be explored in a new issue?

**Comment by adamgfraser** [comment]
@ptrdom Will fix.
