### ISSUE TITLE
Daemon fiber doesn't cleanup on program exit

### ISSUE THREAD

**Issue by guersam** [zio/zio#7907]
### Usecase

I have a background process (fiber) that can be stopped between deployments. To track the status of the process, I'd like log its termination.

### Sample code

```scala
//> using scala "2.13.10"
//> using dep "dev.zio::zio:2.0.10"

import zio._

object Main extends ZIOAppDefault {

  def track[R, E, A](tag: String)(zio: ZIO[R, E, A]): ZIO[R with Scope, E, A] =
    zio
      .onInterrupt(ZIO.debug(s"$tag Interrupt"))
      .onExit(exit => ZIO.debug((s"$tag Exit", exit)))
      .tapErrorCause(cause => ZIO.debug((s"$tag Error", cause)))
      // .withFinalizer(_ => ZIO.debug(s"$tag Finalizer")) // Adding this makes scala-cli hang

  val task =
    ZIO.debug("Running...")
      .repeat(Schedule.fixed(1.seconds) && Schedule.recurs(5))

  val run =
    track("Outer") {
      for {
        _ <- track("Inner")(task).fork
        _ <- track("Daemon")(task).forkDaemon
        _ <- ZIO.never
      } yield ()
    }
}

```

### Steps to reproduce
1. `$ scala-cli https://gist.github.com/guersam/96f51168a7bc1581c67094c5e2651264`
2. Stop the process using `Ctrl + C` within 10 seconds

### Expected result
"Inner", "Outer", "Daemon" fibers log some combinations of "Interrupt", "Exit", "Error", "Finalizer"

### Actual result
"Inner" and "Outer" tasks log about interrupt, but "Daemon" doesn't.

```
Running...
Running...
Running...
^COuter Interrupt
Inner Interrupt
(Inner Exit,Failure(Then(Then(Interrupt(Runtime(4,1678276602161,),Stack trace for thread "zio-fiber-":
),Interrupt(Runtime(4,1678276602161,),Stack trace for thread "zio-fiber-":
)),Interrupt(Runtime(4,1678276602161,),Stack trace for thread "zio-fiber-":
))))
(Outer Exit,Failure(Then(Interrupt(Runtime(3,1678276602159,),Stack trace for thread "zio-fiber-3":
),Interrupt(Runtime(3,1678276602159,),Stack trace for thread "zio-fiber-3":
))))
```

**Comment by adamgfraser** [comment]
You can use `forkScoped` instead of `forkDaemon` for this.

**Comment by guersam** [comment]
I actually trigger the task via an http4s endpoint, and use .forkDaemon so that the HTTP request can completes immediately.

Can I use forkScoped in this case either?

**Comment by adamgfraser** [comment]
Sure.

**Comment by guersam** [comment]
Thanks. Then how can I resolve the Scope added to the R type ensuring the scope outlives the HTTP request?

**Comment by adamgfraser** [comment]
Either the scope requirement propagate to the top of your application or create a scope at the top of your application and specify it with `forkIn`.

**Comment by guersam** [comment]
Thanks, I'll try it. Then the current behavior of .forkDaemon is as expected?

**Comment by adamgfraser** [comment]
That is the expected behavior currently but I just submitted a PR to add support for this.

**Comment by guersam** [comment]
Thank you so much! 

Besides, like the comment on the above example,  the program doesn't exit at all when I add a finalizer to `run`.

Minimal reproducer:

```scala
//> using scala "2.13.10"
//> using dep "dev.zio::zio:2.0.10"

import zio._

object Main extends ZIOAppDefault {
  val run = ZIO.debug("Hello World!").withFinalizer(_ => ZIO.debug("with finalizer"))
}
```

What do you think? If it's not intended behavior, I'll open another issue.

**Comment by adamgfraser** [comment]
Will take a look.

**Comment by adamgfraser** [comment]
@guersam Your example above  with `withFinalizer` works fine. Your original example does not and that is expected behavior. `withFinalizer` treats the workflow as the acquisition of a resource and executes it uninterruptibly. You then call `track` on `outer` which makes `outer` uninterruptible and since `outer` never terminates normally your program never terminates.

**Comment by guersam** [comment]
Understood, thanks! When I tried the second example first time, it didn't terminate. But it just works now... Probably I did something wrong at the first place.
