### ISSUE TITLE
ZStream support for method flip

### ISSUE THREAD

**Issue by carlos-verdes** [zio/zio#7916]
Is there any reason why we don't have ZStream.flip?

The use case for me is testing, trying to test the error scenario when using streams.

**Comment by adamgfraser** [comment]
@carlos-verdes `ZStream` is not symmetrical in the way that `ZIO` is.

A `ZIO` succeeds with exactly one value or fails with exactly one error, so `zio.flip.flip` is an identity. In contrast a stream succeeds with zero or more values or fails with exactly one error. So if we "flipped" a stream we would get a stream that failed the first time an element was emitted and never emitted an error, even if the original stream would have later failed with that error.

I think what you want is something like `stream.runDrain.flip`.

**Comment by carlos-verdes** [comment]
Thanks for your prompt response!!

Yeah what I'm doing is converting the stream into an expected ZIO and then run the test, what you say have sense.

Maybe another approach would be something like "runUntilFail" which should finish when we reach an error or the stream finish, the return type would be something like Option[Error], then if the stream never fails it will return None but if it fails will return Some(error) 

```scala
  
def fetchResource[R](urn: Urn): ZStream[ResourceError, R]

test("fetch non existent resource should fail with not found error") {
  for error <- fetchResource(wrongUrn).runUntilFails
  yield assert(error == Some(ResourceError.NotFound(wrongUrn))
}
```

**Comment by carlos-verdes** [comment]
In any case I'm going to close this comment, if someone find interesting my example let's create different issue for that.
