### ISSUE TITLE
Running scalafix rule fails on expired certificate

### ISSUE THREAD

**Issue by rogern** [zio/zio#7956]
I'm trying to upgrade a ZIO 1.x project and tried the scalafix rule from the migration page:
`sbt "scalafixEnable; scalafixAll github:zio/zio/Zio2Upgrade?sha=series/2.x"`

It however fails on a `[error] Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Mar 22 00:59:59 CET 2023`
The stacktrace is huge so didn't add it. If you can't reproduce, let me know and I'll give you the stacktrace.

Thanks!

**Comment by adamgfraser** [comment]
@swoogles You want to take a look?

**Comment by swoogles** [comment]
Huh, yeah. Weird error. I'll see what I can find

**Comment by swoogles** [comment]
@rogern 
I think we'll need more information. Just ran that exact command on a simple ZIO 1 project, and it completed successfully. Updated the code & no cert issues.

**Comment by rogern** [comment]
Ok, here goes:
[stacktrace.log](https://github.com/zio/zio/files/11112944/stacktrace.log)

**Comment by adamgfraser** [comment]
I think rather than a stack trace a small reproducer would help.

**Comment by rogern** [comment]
Ok, I'll see what I can do.

**Comment by rogern** [comment]
It seems to relate to the github url rule file download and today when I tried again I instead got "javax.net.ssl.SSLException: No PSK available. Unable to resume." And I found there's a bug in Jdk 11 around this: https://bugs.openjdk.org/browse/JDK-8213202 I will try another jdk and see if I still can reproduce.

**Comment by rogern** [comment]
Yep, no problems whatsoever using openjdk-17. Thank you for picking it up nevertheless! :)
Closing!

**Comment by swoogles** [comment]
Glad to hear it worked out for you!
