### ISSUE TITLE
Make mdoc Warnings Into Errors

### ISSUE THREAD

**Issue by khajavi** [zio/zio#7972]
When we compile docs using `sbt docs/mdoc`, we receive a large number of warnings. These warnings could result in broken links on the documentation site if left unresolved. To prevent this, I propose that we treat warnings as errors during compilation, thereby ensuring that they do not propagate into the documentation.

**Comment by abdheshkumar** [comment]
@khajavi I can work on this.

**Comment by abdheshkumar** [comment]
PR https://github.com/zio/zio/pull/8005
