### ISSUE TITLE
Expectation.Exactly does not render correctly

### ISSUE THREAD

**Issue by jeubank12** [zio/zio#8007]
When using Expectation.Exactly on zio 1.0.18, if the expectation fails then the rendered error is
```
Assertion failed:
  - unsatisfied expectations
```
(notice there is not a list of expectations that failed)

I believe this is due to the renderer not having a case for Exactly at https://github.com/zio/zio/blob/v1.0.18/test/shared/src/main/scala/zio/test/DefaultTestReporter.scala#L553

I understand that zio-mock is splitting from the library with 2.0 but if this fix could squeeze in 1.x that would be awesome. Maybe even this issue persists after the split

**Comment by adamgfraser** [comment]
@jeubank12 Thanks for reporting! Pull requests welcome!

**Comment by RayanRal** [comment]
@jeubank12 Are you currently working on this? If not, I'll be happy to give it a go

**Comment by jeubank12** [comment]
@RayanRal it looks like my previous PR to fix this would have been fine. I was just having a hard time groking the CI output at the time. I took a second look this morning and didn't find any problems (I was particularly confused because my home Windows computer fails the rendering tests locally due to path printing).

I've reopened this as #8246
