### ISSUE TITLE
Binary incompatibility in 2.0.12

### ISSUE THREAD

**Issue by zeal18** [zio/zio#8011]
Hi all, it seems the 2.0.12 doesn't solve the following binary incompatibility issue introduced in 2.0.11:
> java.lang.NoSuchMethodError: 'zio.internal.FiberRuntime zio.ZIO$unsafe$.makeChildFiber(java.lang.Object, zio.ZIO, zio.internal.FiberRuntime, int, zio.internal.FiberScope, zio.Unsafe)'

for example this is a part of the dependency tree I have:

```
[info]   +-dev.zio:zio-logging-slf4j_3:2.1.12
[info]   | +-dev.zio:zio-logging_3:2.1.12
[info]   | | +-dev.zio:zio-parser_3:0.1.9
[info]   | | | +-dev.zio:zio-streams_3:2.0.10 (evicted by: 2.0.11)
[info]   | | | +-dev.zio:zio-streams_3:2.0.11
[info]   | | | | +-dev.zio:zio_3:2.0.11 (evicted by: 2.0.12)
[info]   | | | | +-dev.zio:zio_3:2.0.12
[info]   | | | | 
[info]   | | | +-dev.zio:zio_3:2.0.10 (evicted by: 2.0.12)
[info]   | | | +-dev.zio:zio_3:2.0.12
```

**Comment by adamgfraser** [comment]
@zeal18 There is no binary compatibility guarantee with respect to internal ZIO APIs.

**Comment by zeal18** [comment]
@adamgfraser I see, thank you for the response
