### ISSUE TITLE
how to manage ZStream.zipAllSortedByKey lifecycle?

### ISSUE THREAD

**Issue by liewhite** [zio/zio#8037]
When I zip 2 stream with `zipAllSortedByKey`,  It does not have a `HaltStrategy` params, How to make the zipped stream terminate when one of the streams end?

For example, I zip a main stream with a tick stream, the tick stream is infinite, so the zipped stream become infinite too.

What should i do to make the zipped stream terminate after the main stream ends.

Another approach: How to bind a stream lifecycle to another one , so i can bind the tick stream to main one.

**Comment by adamgfraser** [comment]
@liewhite You can use operators like `interruptWhen` to terminate a stream based on some condition.

**Comment by liewhite** [comment]
> @liewhite You can use operators like `interruptWhen` to terminate a stream based on some condition.

Can `interruptWhen` detect the end of another stream? I didn't figure out it

**Comment by liewhite** [comment]
Currently, I copy the `zipAllSortedByKeyWith` to my project and remove pulling code in `DrainLeft` or `DrainRight` case.

**Comment by adamgfraser** [comment]
@liewhite You would signal that the stream has ended by completing the promise.

**Comment by liewhite** [comment]
Thank you. Very helpful
