### ISSUE TITLE
Migrate tests over to 'shared' so they run on Scala.js

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#804]
A bunch of test suites right now run only on the JVM. As many as possible should be migrated over to `shared` so they run in _Scala.js_ configuration.

The tests are currently located in `core/jvm/src/test/scala/scalaz/zio` and could be moved (one by one, PR by PR) to `core/shared/src/test/scala/scalaz/zio`.

 - [x] ArbitraryCause.scala
 - [x] ExitSpec.scala
 - [x] FiberLocalSpec.scala
 - [x] FiberSpec.scala
 - [x] FunctionIOSpec.scala
 - [x] GenIO.scala
 - [x] IOSpec.scala
 - [x] IOSyntaxSpec.scala
 - [ ] PlatformSpec.scala
 - [x] PromiseSpec.scala
 - [x] QueueSpec.scala
 - [x] RefMSpec.scala
 - [x] RefSpec.scala
 - [x] RetrySpec.scala
 - [x] stm/STMSpec.scala
 - [x] duration/DurationSpec.scala
 - [x] duration/DurationSyntaxSpec.scala

Some of these may reveal bugs in Scala.js support that can then be fixed separately.

If anyone has interest in giving a hand here, just reply to this thread and pick out one of the test suites to migrate over (some will be quite simple).

**Comment by kamilkloch** [comment]
`TestRuntime.scala` uses `TerminationMatchers` from specs2. TerminationMatchers cannot be used in Scala.js (reference to Thread.sleep). Any ideas?

**Comment by LGLO** [comment]
Not every test requires `TerminationMatchers`, so we could split `TestRuntime` and put restricted version to `shared`.
Quick test: `PromiseSpec` and `RefSpec` pass tests. `RefMSpec` errors on tests of `update` and `modify`.

**Comment by vilu** [comment]
Is anyone actively working on this one? If not I would give it or a part of it a go late next week.

**Comment by LGLO** [comment]
@vilu this issue can be split to many small PRs.

**Comment by mgibowski** [comment]
I take two easy ones for the start: `ArbitraryCause.scala` and `GenIO.scala`.
The migration is so simple that I will put it into one PR.

**Comment by mgibowski** [comment]
If anybody is interested in `stm/STMSpec.scala`, take a look at this first: #803

**Comment by mgibowski** [comment]
Today I migrate `RefSpec.scala` and `FunctionIOSpec.scala`.

**Comment by LGLO** [comment]
My idea for some other tests is to replace `runSync`, which is disallowed in JS, with `unsafeRunToFuture`, so tests return `Future[MatchResult[T]]`. Then we can use specs2 `Around` that uses `java.util.Timer` and `scala.concurrent.Promise` to create `Future` with timeout.
WDYT guys?

**Comment by LGLO** [comment]
We can't block for result in scala-js, scalacheck is 100% synchronous on the other hand.
`forAll` tests will be challenging. Doable but I think we'll have to write quite a chunk of code to cover `forAll`.

**Comment by vilu** [comment]
I was looking into PlatformSpec, should this one be really be considered in this ticket seeing how the implementation differs between js/jvm? Maybe just removing this one from the list would make sense?
