### ISSUE TITLE
ZIO 2.0.12 deadlock on unsafe run called from an object

### ISSUE THREAD

**Issue by fanf** [zio/zio#8044]
It seems that something is deadlocking in ZIO when I try to `unsafe run` from an object. 

The matter was discussed with @adamgfraser [on discord](https://discord.com/channels/629491597070827530/1095966426428354653) (not sure it's ok to put discord links here, let me know if not, I will remove it) 

An minimal project reproducing the problem is available here: https://github.com/fanf/zio2-deadlock-2023-04/blob/main/src/main/scala/Main.scala

**Comment by adamgfraser** [comment]
I think this is just an early initialization issue. In your example your call to the second object from the first one requires initializing the second object, which requires executing this workflow, which requires multiple other threads to reference the object while the original thread has a lock on the object while it is being initialized. An easy solution is to define `boot` as a `def` or a `lazy val`.

```scala
import zio._

object Main {
  def main(args: Array[String]): Unit =
    Test.boot()
}

object Test {

  def blockingExampleConsole =
    Unsafe.unsafe { implicit unsafe =>
      Runtime.default.unsafe
        .run(zio.ZIO.foreach(List("a", "b", "c", "d"))(x => Console.printLine(x)))
        .getOrThrowFiberFailure()
    }

  def boot() = {
    println("test")
    println("******************************** simple foreach in TEST  *********************************")
    blockingExampleConsole
  }
}
```

**Comment by fanf** [comment]
For reference, that was an early init issue. It is solved in our side by adding some more turtles, and only using `lazy val` and `def`. 

See the corresponding PR that keeps API compatibility and solve the problem: https://github.com/Normation/rudder/pull/4760

Nive side effect: boot is MUCH more effficient now
