### ISSUE TITLE
Replace scala.collection.JavaConverters._ with scala.jdk.CollectionConverters._

### ISSUE THREAD

**Issue by DaniRey** [zio/zio#8055]
The scala.collection.JavaConverters are deprecated and should be replaced with scala.jdk.CollectionConverters.

To do so https://github.com/scala/scala-collection-compat has to be added as a dependency, such that ZIO still compiles with Scala 2.12

**Comment by adamgfraser** [comment]
We don't want to add additional dependencies.

**Comment by DaniRey** [comment]
That's a good strategy.

After all it's no a big issue. Either drop Scala 2.12 support when a Scala version is released that no longer provides JavaConverters (might be quite far in the future, the current roadmap only talks about dropping forward binary compatibility - https://www.scala-lang.org/blog/2023/01/31/scala-center-2023-roadmap.html). Or copy the required code from https://github.com/scala/scala-collection-compat into the ZIO project.
