### ISSUE TITLE
`ZIO.foreachPar(nonEmptyList)(f)` doesn't compile

### ISSUE THREAD

**Issue by guizmaii** [zio/zio#8070]
That'd be nice if we had a version of `ZIO.foreachPar` that would work for `zio.prelude.NonEmptyList`

This, for now, doesn't compile:
```scala
object Example {
    def f(i: Int): UIO[Int] = ZIO.succeed(i + 1)
    val list                = zio.prelude.NonEmptyList(1, 2, 3)
    val res                 = ZIO.foreachPar(list)(f(_))
}
```

**Comment by adamgfraser** [comment]
The Scala collections framework does not support describing non-empty collections or builders of non-empty collections so this needs to be supported at the ZIO Prelude level versus in ZIO Core.
