### ISSUE TITLE
Leverage proxy macro to build dynamically-reloadable services

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8075]
Depends on #7556. 

This ticket consists of 2 parts. The first part is to provide an implementation of a "service reloader" class that can handle registration of services, as well as reloading of (registered) services.

Something along the lines of this:

```scala
trait ServiceReloader {
  def register[A: Tag](serviceLayer: ZLayer[Any, Any, A]): UIO[Unit] 

  def reload[A: Tag]: IO[ServiceReloader.Error, Unit]
}
object ServiceReloader {
  sealed trait Error extends Throwable
  final case class ServiceNotRegistered(serviceTag: LightTypeTag) extends Error
  final case class ServiceInitializationError(error: Any) extends Error

  val live: ZLayer[Any, Nothing, ServiceReloader] = ???
}
```

The second part is to implement a `reloadble` method on `ZLayer`, which utilizes the service reloader, together with the proxy macro, to enable a service to be reloaded dynamically.

For example:

```scala
val clockLayer: ZLayer[Any, Nothing, Clock] = ???

val reloadableClockLayer: ZLayer[ServiceReloader, Nothing, Clock] = clockLayer.reloadable

def example(reloader: ServiceReloader) = 
  (Clock.instant *> reloader.reload[Clock] *> Clock.instant).provide(ServiceReloader.live, relodableClockLayer)
```

In essence, the service reloader has some sort of map from tag to `ScopedRef`, which back the registered services, and it also keeps track of the layers that can build the services, and it can re-instantiate a layer and register the newly-initialized service, cleaning up the resources of the old service, as necessary.

**Note**: This is just a sketch and when implementing this issue, it may be things cannot be implemented exactly in this way. The goal, however, is to provide a very robust and simple means of taking an ordinary service, and making it reloadable "upon request". Other tickets can address common reloading use cases, such as reload-on-config-change, reload-every-n-minutes, etc.

**Comment by adamgfraser** [comment]
I will do this.
