### ISSUE TITLE
Graceful shutdown results in 'Exception in thread "main"'

### ISSUE THREAD

**Issue by rtimush** [zio/zio#8099]
If a ZIO application is gracefully shutdown by sending a TERM signal, it sometimes prints
```
Exception in thread "main"
``` 
to stderr without any other details.

I think this happens because the shutdown hook tries to interrupt the "main" fiber: https://github.com/zio/zio/blob/ae3d534b2605a66739f2b37573eed709bd0655ae/core/jvm/src/main/scala/zio/ZIOAppPlatformSpecific.scala#L48

This makes the effect executed by `runtime.unsafe.run` the `main` sometimes fail with an internal interruption (after `fiber.join` completes) and sometimes with an external interruption (by `Fiber.interruptAll`). The external interruption in turn triggers `getOrThrowFiberFailure`, which makes `main` throw and results in JVM printing the exception message.

**Comment by adamgfraser** [comment]
@rtimush Can you try on the latest snapshot? We have made some changes to this recently. Also a reproducer would be helpful in diagnosing any further issues. Thanks!

**Comment by rtimush** [comment]
I unfortunately don't have a small reproducer using the real `ZIOAppDefault`, even though we see it in a production service. 
I have reproduced it with this app that does a similar thing to what `ZIOAppDefault` does, though:
```scala
object Main {

  final def main(args: Array[String]): Unit =
    Unsafe.unsafe { implicit unsafe =>
      val runtime = Runtime.default
      runtime.unsafe
        .run {
          for {
            _ <- ZIO.succeed(java.lang.Runtime.getRuntime.addShutdownHook(new Thread {
              override def run(): Unit =
                runtime.unsafe.run(for {
                  thisFiberId <- ZIO.fiberId
                  roots <- Fiber.roots
                  _ <- Fiber.interruptAll(
                    roots.filterNot(r => r.id == thisFiberId)
                  )
                } yield ())
            }))
            _ <- ZIO.never
          } yield ()
        }
        .getOrThrowFiberFailure()
    }
}
```
unlike the real `ZIOAppDefault` it never completes with the internal interruption, so it always fails with `Exception in thread "main"`.

**Comment by rtimush** [comment]
I tried `2.0.13+30-187b38a8-SNAPSHOT` and it still happens for me.

**Comment by adamgfraser** [comment]
That seems correct. The application did not complete normally and in fact can never complete normally due to `ZIO.never` and only completed due to external interruption.

**Comment by rtimush** [comment]
Yes, but in `ZIOAppDefault` there is `fiber.join` instead of `ZIO.never` that I have in my example. This `fiber.join` races with the external interruption. If `fiber.join` wins, the application just shuts down normally as expected, but if "interruption" wins the application finishes with `Exception in thread "main"`.

**Comment by adamgfraser** [comment]
Right but if external interruption "wins" then the application has indeed been externally interrupted and did not complete normally just like in the `ZIO.never` example.

**Comment by rtimush** [comment]
The application has been indeed externally interrupted with `kill <pid>`, but this doesn't mean it should unpredictably print `Exception in thread "main"` to stderr, right?
I'd say it's enough that it exits with a non-zero exit code, and trivial applications indeed just do this. It's only after the application gets bigger (not sure what exactly changes), when it sometimes start win it starts occasionally print the error message to stderr.

**Comment by rtimush** [comment]
I was also able to kind of reproduce it with a trivial app (`object Main extends ZIOAppDefault { run = ZIO.never }`) if I add `Thread.sleep(100)` into the `tap` closure here: https://github.com/zio/zio/blob/def01ac9c56c13a8e72602fea70b68a2a075bfec/core/jvm/src/main/scala/zio/ZIOAppPlatformSpecific.scala#L53
Without this `sleep` killing the app just makes it finish, but with `sleep` it finishes with `Exception in thread "main"` most of the time.
