### ISSUE TITLE
Add ZIO.ignore

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8104]
The type signature and semantics should be:

```scala
object ZIO {
  def ignore[A](action: => A): UIO[Unit] = ZIO.attempt(action).ignore 
}
```

However, it's best to inspect the implementation of `ZIO.attempt` and copy it here, but modify it to have the semantics and type signature above, so that we can achieve higher performance relative to this composite implementation.

**Comment by adamgfraser** [comment]
Will do.
