### ISSUE TITLE
Create ZLayer.derived macro for Scala 2.x and Scala 3.x

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8106]
The macro should inspect the constructor for the class, and create `Ref`, `ScopedRef`, `FiberRef`, `Queue`, and other ZIO data structures, and should use `ZIO.service` to pipe in other dependencies. 

Finally, if a service has: `def initialize: ZIO[Scope, E, A]` and `def finalize: IO[E, A]` methods (or `val`s), then these should be invoked during layer construction and finalization, respectively, with errors propagating to the layer.

```scala
final case class MyClass(ref: Ref[Int], a: ServiceA, b: ServiceB)
val layer = ZLayer.derived[MyClass] // ZLayer[Int with ServiceA with ServiceB, Nothing, MyClass]
```

**Comment by andrzejressel** [comment]
I understand that Services are coming from layers, but about that Ref[Int]?

**Comment by adamgfraser** [comment]
It would just be generated wit `Ref.make`.

**Comment by andrzejressel** [comment]
No, no - I understand that. But I don't understand how that int should be passed in the first place. Shouldn't it be something like
`val layer = ZLayer.derived[MyClass] // Int => ZLayer[ServiceA with ServiceB, Nothing, MyClass]`
or 
`def layer(a: Int) = ZLayer.derived[MyClass](a) // ZLayer[ServiceA with ServiceB, Nothing, MyClass]`

**Comment by adamgfraser** [comment]
I don't think it would actually work with `Ref`, which needs a value inside it, unless it was provided as an argument to the method like you suggest. I think it makes more sense for a data type like a `Queue` or a `Promise` that start out empty.

**Comment by hearnadam** [comment]
Is it possible to use case class with a default value to set the value of the `Ref`?

**Comment by adamgfraser** [comment]
Sure!

**Comment by 987Nabil** [comment]
@adamgfraser how would you be using default values for `Ref`? `ref: Ref[Int] = Ref.unsafe.make[Int](0)`?

**Comment by adamgfraser** [comment]
@987Nabil I think that would actually not make sense because the value is of type `Ref[Int]` versus `Int`.

**Comment by 987Nabil** [comment]
That's what I thought and why your previous answer surprised me 😅

**Comment by jdegoes** [comment]
@andrzejressel @adamgfraser 

If we want, `Ref`, etc., initial values can be deferred to layer input, e.g.:

```scala
final case class GithubClient(ref: Ref[ClientState], httpClient: HttpClient)
// ZLayer[ClientState with HttpClient, Nothing, GithubClient]
```

I'm not sure if that's useful on the net. I wish we had `Default[A]` for cases like this.

**Comment by guersam** [comment]
I'd prefer `Default[A]` to adding `A` to `R`. I'll try this.

**Comment by adamgfraser** [comment]
@guersam I tend to think we don't actually want to do that since it would violate coherence.

**Comment by guersam** [comment]
@adamgfraser I see your point as it might cause weird behavior sometimes. I neither want `Int` in R type due to an `Ref[Int]`.

I'll break down the work into the following steps:
- [ ] Non-effectful constructor using `ZLayer.fromFunction`
- [ ] Effectful constructor containing ZIO data structures that don't require default value e.g. `Queue`, `Promise`
- [ ] Support for `initialize` and `finalize`
- [ ] Support for other ZIO data structures like `Ref` according to the result of the further discussion here

What do you think?

**Comment by guersam** [comment]
@jdegoes For `initialize` and `finalize`, do we need a marker trait which makes sure these hooks will be evaluated, or is it enough to rely on the convention?

**Comment by andrzejressel** [comment]
I'd personally would like to see trait to at least remove some of the macro magic.

**Comment by adamgfraser** [comment]
@guersam Maybe we could look in the companion object of the data type for a default value.

```scala
trait ClientState

object ClientState {
  val default: ClientState = ???
}
```

**Comment by guersam** [comment]
I hesitate adding another convention to macro expansion, but have no strong objection.

What can we do for standard data types like `Int`, `Map[K, V]`? For quick demo or test doubles I frequently use something like `Ref[Map[K, V]]`.

**Comment by adamgfraser** [comment]
Maybe a macro annotation on Scala 2? Perhaps we could just always use a set of default values like zero or an empty map and say if you want something custom you should implement it yourself. Or maybe that brings us back to the `Default` type class.

**Comment by guersam** [comment]
Prior art for Scala 3: https://github.com/zio/zio/pull/7300

**Comment by 987Nabil** [comment]
This sounds actually a little scary. Are we sure, we don't cross the border here of what is reasonable to automate/abstract?

**Comment by 987Nabil** [comment]
yes @guersam it should not be too hard to integrate into the code of #7300

**Comment by adamgfraser** [comment]
Maybe we should start by just mirroring the existing functionality on Scala 3 on Scala 2 and then we can explore further improvements from there.

**Comment by 987Nabil** [comment]
I think I can say why I feel a bit strange about this. The things that are automated are either things that are just glue, like the provide macros, or do something very obvious, like `ZLayer.fromFunction`.
But if we would use default values here, you would have no idea based on the macro name or the type signature what will happen. `Default[A]` won't be in the signature.
Imho, if we would use the default type class, we just trade one complexity with another in the best case. But I think you can make an argument that the type class is worse, because it is more obfuscating.

**Comment by guersam** [comment]
Opened #8134 that simply mirrors the current Scala 3 behavior in Scala 2 (not only for case classes though)
