### ISSUE TITLE
How to force a stream to execute immediately ? 

### ISSUE THREAD

**Issue by liewhite** [zio/zio#8107]
Hello, I have a situation:

I Call  `ZStream.zipAllSortedByKey` recursively to merge many streams into one, each of them takes seconds to prepare, it cause a delay of sum of their prepare time. 

Is there some workaround to force streams to execute immediately?

**Comment by adamgfraser** [comment]
You may want to use `ZStream.mergeAll` or `ZStream.mergeAllUnbounded` to merge the streams and then aggregate them but in general all of them should be executed immediately.

See the example below which recursively zips four streams that each take 5 seconds to start. The entire program completes in about five seconds and you can see that each stream begins executing immediately.

```scala
object Example extends ZIOAppDefault {

  val first =
    ZStream.fromZIO(ZIO.debug("first starting")) *>
      ZStream.fromZIO(ZIO.sleep(5.seconds)) *>
      ZStream((1, "A"), (2, "B"), (3, "C"))

  val second =
    ZStream.fromZIO(ZIO.debug("second starting")) *>
      ZStream.fromZIO(ZIO.sleep(5.seconds)) *>
      ZStream((2, "B"), (3, "C"))

  val third =
    ZStream.fromZIO(ZIO.debug("third starting")) *>
      ZStream.fromZIO(ZIO.sleep(5.seconds)) *>
      ZStream((1, "A"), (2, "B"), (3, "C"))

  val fourth =
    ZStream.fromZIO(ZIO.debug("fourth starting")) *>
      ZStream.fromZIO(ZIO.sleep(5.seconds)) *>
      ZStream((2, "B"), (3, "C"))

  val default     = ""
  val defaultPair = (default, default)

  val run =
    first
      .zipAllSortedByKey(second)(default, default)
      .zipAllSortedByKey(third.zipAllSortedByKey(fourth)(default, default))(defaultPair, defaultPair)
      .runCollect
      .debug
}
```

**Comment by liewhite** [comment]
You're right, may be there are some effect else in my code cost time
