### ISSUE TITLE
Supervision is unintuitive due to internal forks

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#811]
If you execute the following code:
```scala
UIO(println("ok")).fork.timeout(30 seconds).superviseWith { list =>
  IO.unit
}
```
You expect `list` to contain the fiber just created with `fork`. 
However, because `timeout` uses `race` internally and `race` forks some fibers, you receive the list of those fibers instead of the expected one. In other words, internal implementation is affecting the behavior or supervision, which leads to unexpected results for users.

**Comment by jdegoes** [comment]
In general, I think that monadic regions should be inheritable, and that the lack of inheritability causes confusion for users, requires global reasoning about whether or not effects "fork", and may violate an interpretation of fork/join identity law.

**Comment by iravid** [comment]
@jdegoes which is to say, a supervised fiber always forks supervised fibers?

**Comment by jdegoes** [comment]
More generally, a fiber with a regional effect will always propagate it on forking.

That means inheriting:

 - Current interruptibility status
 - Current executor (I think this is _already_ true)
 - Current supervision status
 - Soon, next-gen fiber locals

Any other stacks I missed?

**Comment by ghostdogpr** [comment]
If I understand your proposal, when we fork, we pass to the new `FiberContext` the current state of supervision (`supervising` and `supervised.peek`) and interruptibility (`interruptStatus.peek`), the same way we currently do with the executor (`platform`) and the environment (`environment.peek`).

I tried to do that, it works well for supervision (my example above returns all the fibers and not just the `race` ones) but it breaks a number of tests when I add the interruptibility status 🤔

**Comment by ghostdogpr** [comment]
Example of problem with interruptibility inheritance:
```scala
val io =
      for {
        promise <- Promise.make[Nothing, Unit]
        fiber   <- IO.bracket(promise.succeed(()) <* IO.never)(_ => IO.unit)(_ => IO.unit).fork
        res     <- promise.await *> fiber.interrupt.timeoutTo(42)(_ => 0)(1.second)
      } yield res
```

`fiber` in uninterruptible, and `timeoutTo` uses `race` and `interrupt` internally, which is not working anymore because it inherited the uninterruptibility.

**Comment by kaishh** [comment]
Inheriting interruptibility is not immediately intuitive to me, personally I always expect a fiber to start out interruptible...

**Comment by jdegoes** [comment]
These issues do require thought.

The flip-side: `ZIO.uninterruptible(foo)` would ideally have the same behavior as `ZIO.uninterruptible(foo.fork.flatMap(_.join))`. You shouldn't be forced to know whether or not a "fork" is used deep down inside an effect to know the behavior of the effect.

**Comment by kaishh** [comment]
ZIO's supervision is very closely related to nurseries / structured concurrency in JVM Project Loom, we may just copy their decisions. https://wiki.openjdk.java.net/display/loom/Structured+Concurrency

**Comment by jdegoes** [comment]
@ghostdogpr So I have a PR open (#897), but I don't think it will actually "fix" this issue.

It make sit so "hidden forks" can't go wrong (in the sense of observing the parent region effects, by default), but it won't change the fact that "hidden forks" can still be observed in the supervised child list.

I cannot think of a ready fix for that at the moment, and it seems more general than just fork, as if you sequence an effect that happens to fork, well, you wouldn't know about that just by locally examining the code. 

Maybe a better model would be to expose a single composite fiber for all the children. Then at least you wouldn't be able to inspect "how many" children there are. It would always appear as one. 

That might be enough to smooth out fork differences.

**Comment by ghostdogpr** [comment]
@jdegoes my initial problem was only that my fork was _not_ returned (only the internal forks were returned). I don't mind having the extra children caused by internal forks returned, I think it makes sense in a way, you might want to interrupt all of them.

I tried your branch and the example above now returns 5 children instead of 4: the 4 internal ones + the 1 that I created. So I consider the problem solved 👍

**Comment by ghostdogpr** [comment]
Reopening, see https://github.com/scalaz/scalaz-zio/pull/914#issue-283475782 about why and what to do.

**Comment by kaishh** [comment]
Observing it in this example:

```
import zio._
import zio.console._

object App extends App {
  def innerFork(p: Promise[Nothing, Unit]) = {
    putStrLn("bad line")
      .onInterrupt(putStrLn("interrupted") *> p.succeed(()))
      .forever
      .fork
  }

  override def run(args: List[String]) = {
    (for {
      latch <- Promise.make[Nothing, Unit]
      _ <- innerFork(latch).fork
      _ <- latch.await
    } yield 0).interruptChildren
  }
}
```

`innerFork` is never interrupted, because it's an *indirect* child of `run`, so it doesn't get into `run`s supervised list, and `run`s child does not inherit the supervision action.

**Comment by jdegoes** [comment]
Example from @ghostdogpr:

Before:

```scala
ZManaged.make(IO.never.fork)(_.interrupt).useForever
```

After:

```scala
ZManaged.make(IO.never.interruptible.fork)(_.interrupt).useForever
```

**Comment by jdegoes** [comment]
```scala
    unsafeRun(
      for {
        ref <- Ref.make(0)
        sub <- withLatch(set => (for {
          fiber <- IO.uninterruptibleMask(restore => 
            IO.forkAll(List.fill(8)(set *> restore(IO.never).onInterrupt(ref.update(_ + 1)))))
          result <- fiber.join
        } yield result).fork)
        _ <- sub.interrupt 
        count <- ref.get 
      } yield count must_=== 8
    )
```

**Comment by adamgfraser** [comment]
I believe this is solved by the fiber supervision model.
