### ISSUE TITLE
additional overload to Metric::timer for specification of boundaries

### ISSUE THREAD

**Issue by BalduinLandolt** [zio/zio#8119]
currently there are two `timer()` methods: https://github.com/zio/zio/blob/3b03c777b423d20b9d45eb89b079dbabf0d71eac/core/shared/src/main/scala/zio/metrics/Metric.scala#L532-L556

One lets you define your all custom boundaries, the other creates exponential boundaries with 2^64.

For me it would be useful to have a third one with an integer param `x` that results in 2^x exponential boundaries.

If that sounds useful, I'd like to add that. Any thoughts?

**Comment by adamgfraser** [comment]
Sure!
