### ISSUE TITLE
SBT runMain exits with exit code 0 even on failure

### ISSUE THREAD

**Issue by disordered** [zio/zio#8122]
I can't really figure out whether this is the issue with SBT or ZIO, so hopefully, you guys can help out.
When `ZIOApp` dies/fails, `sbt runMain` will exit with success no matter what. I tried with `fork` enabled/disabled - same result. However, if I call `exit(ExitCode.failure)` then it exits with code `1`.

Minimal code:
```
object Test extends ZIOAppDefault {
  override def run = ZIO.dieMessage("Die on purpose")
}
```

This exits as expected:
```
object Test extends ZIOAppDefault {
  override def run = exit(ExitCode.failure)
}
```

Invoke above with `sbt "runMain Test"` or just `sbt run`.

SBT version `1.8.3`
ZIO version `2.0.13`
Scala version `3.2.2`

**Comment by adamgfraser** [comment]
This exits with a failure exit code for me:

```scala
[info] running (fork) zio.Test 
[info] timestamp=2023-05-18T03:12:09.566553Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.RuntimeException: Die on purpose
[info]  at zio.Test.run(Test.scala:4)"
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1
```

**Comment by disordered** [comment]
Interesting, could you confirm that you tested with same versions as above?

**Comment by liewhite** [comment]
It seemds sbt runMain not wait for fibers

**Comment by disordered** [comment]
Thanks @adamgfraser , based on your log I spotted that I actually didn't test with `fork := true`, apparently I enabled it in wrong place. It does exit correctly when the process is forked, but not when it is running in the same JVM.
I suppose non-forked exit code would be an issue in SBT itself, not ZIO.

**Comment by adamgfraser** [comment]
@disordered We can't actually call `System.exit` in SBT when we are not forked because doing so would exit the user's SBT session. However, we should make sure to fail with the original error so it is properly reported. Just submitted a PR to do this.
