### ISSUE TITLE
ZStream Question: How to recover and continue? 

### ISSUE THREAD

**Issue by liewhite** [zio/zio#8123]
In the document, there are `catchxxx`s, but they all continue with new stream.

Is there a method to replace the bad element with new one and continue with current stream?

New Discovery: `either` can lift failure, but also terminate the stream.

**Comment by adamgfraser** [comment]
The contract of a stream is that it produces zero or more elements and then terminates with either an error or a done value with no meaningful information. So when a stream fails with an error there is nothing left to do. You can succeed with a new stream as `catchAll` does or succeed with that error as `either` does but there is nothing left to get out of the original stream.

**Comment by liewhite** [comment]
> The contract of a stream is that it produces zero or more elements and then terminates with either an error or a done value with no meaningful information. So when a stream fails with an error there is nothing left to do. You can succeed with a new stream as `catchAll` does or succeed with that error as `either` does but there is nothing left to get out of the original stream.

How about the ZStream.toPull and fromPull?  So we can recover failed pull effects in the pull processing.

**Comment by adamgfraser** [comment]
That doesn't change anything. Those operators are just giving you a different way to pull the values from a stream or construct a stream. Once a stream has failed there is nothing left to pull.
