### ISSUE TITLE
interop(s)

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#815]
The various `interop` right now are really bugging me :D

Would there be an issue with combining them all into one `zio-interop` module and using `Optional` dependencies (see https://blog.7mind.io/no-more-orphans.html)?

**Comment by kaishh** [comment]
That's similar to what we did before! (I actually got the `Optional` usage from zio). The big point of this trick is being able to stuff all instances into the companion object and have them always available without the `import scalaz.zio.interop.blah._` dance, but that would probably mean getting rid of even a big `zio-interop` module and just dump everything in core...

**Comment by ghostdogpr** [comment]
Closing this since we moved interop to separate repos
