### ISSUE TITLE
ZPipeline does not have contramap method 

### ISSUE THREAD

**Issue by Gregory-Berkman-Imprivata** [zio/zio#8152]
Is there any reason that the `ZPipeline` class does not have a `.contramap` method? it is in the [documentation](https://zio.dev/reference/stream/zpipeline#output-transformation-contramap).   

Or is there any way for me to perform a `ZPipeline.contramap(...)` with whatever current functions are available?

**Comment by adamgfraser** [comment]
I just submitted a PR to add this but you can just compose another pipeline that transforms the inputs with your pipeline.
