### ISSUE TITLE
makeSome & provideSome regression with compound types

### ISSUE THREAD

**Issue by narma** [zio/zio#8164]
makeSome and provideSome fails to compile with compound types.

Super minimal example for makeSome:
```scala
case class A(a: Int)
case class B(b: Int)
case class C(c: Int)

ZLayer.makeSome[A & B, C](ZLayer.fromZIO {
  for { 
    a <- ZIO.service[A]
    b <- ZIO.service[B]
  } yield C(a.a + b.b)
})
```
[compiles](https://scastie.scala-lang.org/narma/IjSSlNqvRwGtK3CAk9PTEQ/1) with 2.0.13 [but not](https://scastie.scala-lang.org/narma/IjSSlNqvRwGtK3CAk9PTEQ) with 2.0.14.

More complicated example with provideSome also https://scastie.scala-lang.org/narma/kIEO01clSmqfmiC3C5OjCg/2 fails with 2.0.14. (Minimal reproducer for our tests which stops compiles after upgrading to 2.0.14)

It's compiles and runs ok with 2.0.13 https://scastie.scala-lang.org/narma/kIEO01clSmqfmiC3C5OjCg/1

Same test but without compound types works ok with 2.0.14 https://scastie.scala-lang.org/eWLYpDXDRB6tisjkG40O7A

We are using only Scala 3.3.0.

**Comment by bilal-fazlani** [comment]
I was just about to report this myself.

Facing this issue. Had to go back to ZIO 2.0.13.

**Comment by narma** [comment]
Even more minimal reproducer for provideSome
```scala
import zio.*

case class A(a: Int)
case class B(b: Int)
case class C(c: Int)

def z: ZIO[A & B & C, Any, Unit] = for {
  a <- ZIO.service[A]
  b <- ZIO.service[B]
  c <- ZIO.service[C]
  _ <- ZIO.debug(a.a + b.b + c.c)
} yield ()

def layer: ZLayer[A & B, Any, C] = ZLayer.fromZIO {
  for {
    a <- ZIO.service[A]
    b <- ZIO.service[B]
  } yield C(a.a + b.b)
}

val io = z.provideSome[A & B](layer) // compilation failure

Unsafe.unsafe { implicit unsafe =>
  Runtime.default.unsafe.run(io.provide(ZLayer.succeed(A(1)) ++ ZLayer.succeed(B(2)))).getOrThrowFiberFailure()
}
```

https://scastie.scala-lang.org/AYo9PE0RQaOjI2EgwillWA

**Comment by bilal-fazlani** [comment]
Is it worth releasing a patch version for ZIO ?

**Comment by adamgfraser** [comment]
@bilal-fazlani Yes will do another release this weekend.
