### ISSUE TITLE
provide Coordinated-Shutdown mechanism

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8171]
In Akka, there's a coordinated shutdown feature that allows for integration into the shutdown process. Our existing 'acquireRelease' mechanism possesses some similar characteristics, but it doesn't fully meet this requirement. This concern has been reiterated several times, and a recent question in our Discord community underscores this need— for example, how to halt the Kafka consumer while allowing in-flight messages to finish processing, or how to unbind the HTTP server while ensuring currently processing requests are completed, etc.

Although there is a workaround, like waiting for a promise in the release section of 'acquireRelease', users appear to desire a more straightforward approach. A potential solution could be the introduction of a new method within ZIO or alternatively, a clear instructional guide in our documentation detailing how to implement this.

**Comment by adamgfraser** [comment]
Yeah I think this is just adding a finalizer so it is best addressed through documentation.

@khajavi Can you add an example of this?

**Comment by khajavi** [comment]
Will try to elaborate more on this!

**Comment by adamgfraser** [comment]
Thank you! 🙏
