### ISSUE TITLE
Hub probably incorrectly releases subscriptions

### ISSUE THREAD

**Issue by szlepermarcin** [zio/zio#8178]
`zio 2.0.15`

In some cases Hub incorrectly releases subscriptions, which causes resource leak and constantly growing internal subscribers list
```scala
    Hub.bounded[String](1024).flatMap { hub =>
      ZIO
        .scoped(
          hub.subscribe
            .flatMap { q =>
              for {
                f <- q.take.fork
                _ <- hub.publish("abcd").timed.map(_._1).debug
                _ <- f.join
              } yield ()
            }
        )
        .repeatN(1000_000)
    }
```
in this example  you can see the publishing time increases with the size of the subscriber list (which can be verified with debugger)

**Comment by szlepermarcin** [comment]
Hi, I have potential one more issue related to this topic - what about `releaseMap` in internal scope used by `Hub`? Each subscription registers finalizer in this scope and this finalizer should probably be removed after unsubscribing as well.

**Comment by adamgfraser** [comment]
Addressed in latest version.
