### ISSUE TITLE
java.lang.IllegalStateException: Not inside a request scope with JAXRS ResourceInfo

### ISSUE THREAD

**Issue by politrons** [zio/zio#819]
Hi all,

I´m having some issues interacting with `JAXRs ResourceInfo` inside a `ZIO`. 
When inside the ZIO I invoke this function

```
  def isCommand: ResourceInfo => Boolean = {
    resourceInfo =>
      val method = resourceInfo.getResourceMethod
      method.getAnnotation(classOf[POST]) != null || method.getAnnotation(classOf[PUT]) != null
  }
```

an exception it's throw `Die(java.lang.IllegalStateException: Not inside a request scope.)`

Any idea what's wrong?.

**Comment by kaishh** [comment]
It's likely that this API uses thread locals, so you'll need to issue all calls to it from one thread. Check if creating a `Executors.newFixedThreadPool` with size=1 and using it with `.on` helps.

**Comment by politrons** [comment]
Thanks for answer. Sounds logical what you mention, for now I just extract that computation to the main thread and just pass the variable into the ZIO. With that workaround works.

**Comment by adamgfraser** [comment]
@politrons Going to close for now given the age of this issue but if something is still not working please feel free to reopen and we will look into it.
