### ISSUE TITLE
Replace all unsafe usage of `reduce`

### ISSUE THREAD

**Issue by reibitto** [zio/zio#8190]
I can't get to creating a PR right now but this is an easy one that anyone can pick up quickly if they have time. Basically `reduce` on an empty `Seq` will result in a `java.lang.UnsupportedOperationException: empty.reduceLeft`. There's a few usages of this in the zio codebase. Most of them are in specs so replacing those probably aren't crucial but there's examples of it in actual non-test code too. For example we ran into this one which caused an exception:
https://github.com/zio/zio/blob/521b6fd548073f5343f9c71aa92568b056a55d5a/test/shared/src/main/scala/zio/test/TestArrow.scala#L46-L48

The fix is to use `fold`, `reduceOption`, or use a non-empty list where appropriate.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
