### ISSUE TITLE
zio-test unintentionally prints the failed tests multiple times

### ISSUE THREAD

**Issue by doohochang** [zio/zio#8214]
# Issue
zio-test seems to unintentionally print the failed test cases multiple times when using `def check(..)` with `Gen` instances.
It seems `failureDetails` in `zio.test.Summary` has duplicate contents somehow.

## Environment
sbt: 1.9.0
Scala: 3.3.0
zio-core, zio-test: 2.0.15

## Minimal Example
The following codes are written to reproduce a minimal example.
```scala
// A.scala
import zio.*
import zio.test.*

object A extends ZIOSpecDefault:
  def spec = suiteAll("A"):
    test("test"):
      assertTrue(1 + 1 == 3)

    test("test with check in A"):
      check(Gen.int): int =>
        assertTrue(1 + 1 == 2)
```

```scala
// B.scala
import zio.*
import zio.test.*

object B extends ZIOSpecDefault:
  def spec = suiteAll("B"):
    test("test with check in B"):
      check(Gen.int): int =>
        assertTrue(1 + 1 == 2)
```

## Test Result
```
sbt:zio-test-issue> test
+ A
  - test
    ✗ Result was false
    1 + 1 == 3
    at ~/playground/zio-test-issue/src/test/scala/A.scala:7

  + test with check in A
+ B
  + test with check in B
4 tests passed. 2 tests failed. 0 tests ignored.


  - A / test
    ✗ Result was false
    1 + 1 == 3
    at ~/playground/zio-test-issue/src/test/scala/A.scala:7


  - A / test
    ✗ Result was false
    1 + 1 == 3
    at ~/playground/zio-test-issue/src/test/scala/A.scala:7

Executed in 387 ms

[info] Completed tests
[error] Failed tests:
[error]         A
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Jun 22, 2023, 1:25:52 AM
```

**Comment by adamgfraser** [comment]
@swoogles Can you take a look?

**Comment by jamonkko** [comment]
Any update for this? It would be really nice to get a fix. Currently, with this issue, zio-test is unfortunately not a really good for real world use cases where there are more than one spec.
You can re-produce this also e.g. with https://github.com/softwaremill/realworld-tapir-zio by just breaking one test, which will lead to same error reported multiple times. 

Workaround could be to compose one Spec that adds all the suites from other spec files but then all failures will be reported under that aggregate Spec file. And it probably does not play well with JUnit integration either.
