### ISSUE TITLE
Rename `unleft` and co. and add 4 cases for either

### ISSUE THREAD

**Issue by decoursin** [zio/zio#8231]
In my opinion, the `right,` `left` `unleft`, `unright` methods don't exactly hit the mark - it's hard to remember which does what.

For example, `unleft` does this as copied from the documentation:
```scala
/**
 * Converts a `ZIO[R, Either[E, B], A]` into a `ZIO[R, E, Either[A, B]]`.
 * The inverse of `left`.
 */
```
Why does unleft make a `ZIO[R, E, Either[A, B]]` instead of a `ZIO[R, E, Either[B, A]]`? I would have expected it to do the later, because we're moving something from an error channel to an either on the success channel. The left of an either often signifies error itself, so it would have made sense to me to move something that was already on the error channel, namely type `B`, which implies it had some sort of relations to a failure, because it was on the error channel, then to the left of the either on the success channel, which as already stated is often correlated with error. But `unleft` moves it to the right side: `Either[A, B]`.

Also, in my opinion, although I think these methods are potentially very useful, because `either` is awesome and used so frequently, only some of the cases are implemented, four of them:

1. unleft: ```Converts a ZIO[R, Either[E, B], A] into a ZIO[R, E, Either[A, B]]```
2. unright: ```Converts a ZIO[R, Either[B, E], A] into a ZIO[R, E, Either[B, A]].```
3. left: ```Converts a ZIO[R, E, Either[B, A] into a ZIO[R, Either[E, A], B].```
4. right:  ```Converts a ZIO[R, E, Either[B, A] into a ZIO[R, Either[B, E], A].```

I actually had to really study the methods and type signatures to figure out the last two, because the docs weren't descriptive. The first two I just copied the docs verbatim.

It would seem like the names were meant to be short and "cute", instead of practical and logical. That's why they're confusing and hard to remember. And it's a pity that the other 4 cases aren't implemented.

In general, that's why I would propose the following 8 methods:

1. rightErrorToRightSuccess: ```Converts a ZIO[R, Either[J, K], A] into a ZIO[R, J, Either[A, K]]```
2. rightErrorToLeftSuccess: ```Converts a ZIO[R, Either[J, K], A] into a ZIO[R, J, Either[K, A]]```
3. leftErrorToLeftSuccess: ```Converts a ZIO[R, Either[J, K], A] into a ZIO[R, K, Either[J, A]]```
4. leftErrorToRightSuccess: ```Converts a ZIO[R, Either[J, K], A] into a ZIO[R, K, Either[A, K]]```
5. rightSuccessToRightError: ```Converts a ZIO[R, E, Either[B, C]] into a ZIO[R, Either[E, C], B]```
6. rightSuccessToLeftError: ```Converts a ZIO[R, E, Either[B, C]] into a ZIO[R, Either[C, E], B]```
7. leftSuccessToLeftError: ```Converts a ZIO[R, E, Either[B, C]] into a ZIO[R, Either[B, E], C]```
8. leftSuccessToRightError: ```Converts a ZIO[R, E, Either[B, C]] into a ZIO[R, Either[E, B], C]```

Thanks.

**Comment by fourth44** [comment]
Consider the current signatures as methods to 'zoom in' and 'zoom out' on values.
Given a `ZIO[R, E, Either[A, B]]`, if you want to do mappy and flatmappy things on the `Right` (`B`), you apply `.right` to bump the uninteresting part (the `Left`) to the error channel, but a `Left` must remain a `Left`, so the error channel becomes `Either[A, E]`. Then `.unright` is the reverse, bumping the Left error back to a Left 'success'. To me  `left` and `unleft` are admittedly less intuitive than `right`/`unright`, but they are consistent. Sometimes you might need to sprinkle some `.mapError(_.swap)` if you need to align with other code which had the order reversed on the error channel for some reason, but try to minimize those swapping operations through your code by choosing the most consistent (not per sé the most immediate obvious intuitive) order.

**Comment by decoursin** [comment]
No offense @fourth44, but to me, that explanation doesn't help anything.

Anyways, it's just my opinion, the maintainers are of course welcome to make their own decisions in this regard. Just trying to contribute ;)

**Comment by adamgfraser** [comment]
@decoursin The goal of these operators is not to have some generic method for converting any `Either` in either the error or success channels into an `Either` in the other. As you suggest that would require a total of eight different operators with very long method names, which would contribute to a proliferation of operators and hurt overall discoverability. If you want to arbitrarily move values between the error and success channels you can use `foldZIO` and do exactly the transformation you want.

As @fourth44 said, the goal of these operators is to satisfy one specific and common use case which is wanting to transform one of the values inside an `Either` in the success channel in an ergonomic way.

Imagine we have an api that returns a `ZIO[Any, Throwable, Either[DomainError, A]]`, where `DomainError` represents some "business errors" that may occur and and `Throwable` represents errors that may occur in network or file IO. We would like to transform the `A` value into a `B` value or possibly a workflow that produces a `B` value. As written to do that we have to do:

```scala
workflow.map(_.map(f))
```

Basically we need to map twice, once to get at the `Either` inside the `ZIO` and again to get at the `A` inside the `Either`. And this obviously gets worse if we want to do multiple transformations or use workflows.

These operators allow us to improve on this by "zooming in" to the value inside the `Either` and pushing the other possibility into the error channel. So we can do:

```scala
workflow.right.map(f).unright
```

Or even:

```scala
workflow.rightWith(_.map(f))
```

Which perhaps gives an intuition of `right` "zooming in" to the `A` case, `upright` "zooming out", and `rightWith` doing something while we are zoomed in. This also mirrors a variety of other ZIO operators such as `some` and `unsome` for zooming in to an optional values.

Anyway, there was significant discussion about this when ZIO 2.0 was being developed and we are not looking to make significant API changes at this point so going to close this but thanks for your feedback and hopefully this clarifies the usage of these operators.

**Comment by decoursin** [comment]
Ok, sorry about that, thanks for the explanation!

**Comment by adamgfraser** [comment]
Not at all! Thanks for the feedback and hope you're having a good experience using ZIO!

**Comment by decoursin** [comment]
I definitely am, I love it. I am pretty new to it. Switching from Cats Effect :), and I use Doobie still
