### ISSUE TITLE
ZLayer.derive fails when deriving services with no dependencies

### ISSUE THREAD

**Issue by hugoferreira** [zio/zio#8236]
From the [tests](https://github.com/zio/zio/blob/9845ae8598dbc3b82dd7d55779a41e5a81dbb920/core-tests/shared/src/test/scala-3/zio/ZLayerDerivationSpec.scala#L9):

```
case class OneDependency(d1: String)

val derivedOne = ZLayer.derive[OneDependency]

(for {
    d1 <- ZIO.service[OneDependency]
} yield d1 == OneDependency("one")).provide(
    derivedOne,
    ZLayer.succeed("one"),
)
```

But this doesn't work:

```
case class NoDependency()

val derivedZero = ZLayer.derive[NoDependency]

(for {
    d0 <- ZIO.service[OneDependency]
} yield d0 == NoDependency())
```

I wonder if this is (a) a bug, because the macro expansion is expecting at least one term, (b) on purpose, because case classes with zero arguments are frowned upon.

**Comment by adamgfraser** [comment]
Probably an oversight. Deriving a layer with no dependencies doesn't seem particularly useful but I don't see any reason why it shouldn't work.
