### ISSUE TITLE
Propagate Cause in tapBoth-method (tapBothCause)

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#8245]
Hello!

When we use `.tapBoth`, for example to log both success and error cases, it seems that we cannot log the original `Cause`, since it is not available to the function. The effective signature is like this(slightly reduced to de-clutter):
```scala
final def tapBoth(f: E => ZIO[R1, E1, Any], g: A => ZIO[R1, E1, Any]): ZIO[R1, E1, A] =
 ???
```

In this way, it is not possible to log a `Cause` with `.logErrorCause`.

Wondering if it is worth to add `.tapBothCause(...)`, so that for the error part we have: `f: Cause[E] => ZIO[R1, E1, Any]` ?

Otherwise the use of `.tapBoth` is not very convenient in these cases and we need to use `.tap` + `.tapErrorCause` instead.

Thank you!

**Comment by NavidJalali** [comment]
I can do this
