### ISSUE TITLE
New feature request: ZStream#interleaveWith

### ISSUE THREAD

**Issue by carlos-verdes** [zio/zio#8249]
I have next problem to solve:
"Having 2 streams of events sorted by date, generate a new stream with all events from both streams so all events of the new stream are also sorted by date"

When I read `ZStream#interleaveWith` I expected to have next signature:
```scala
  def interleaveWith[R1 <: R, E1 >: E, A1 >: A](
    that: => ZStream[R1, E1, A1]
  )(f: (left: A, right: A1)  =>  Boolean)(implicit trace: Trace): ZStream[R1, E1, A1] 
```

The idea is on each step to get the head of both streams, run function `f: (left: A, right: A1)  =>  Boolean` and pick the element of left stream if true (and right stream if false).

This signature would help me solve my current issue but I also think can bring lot of utility for other use cases (everything we work with event sourcing we will have similar problems to solve).

Example of how I would use:
```scala
case class Event(name: String, eventTime: Long, processingTime: Long)

val leftTrxs: Stream[Throwable, Event]
val rightTrxs: Stream[Throwable, Event]
val allTrx = leftTrxs.interleaveWith(rightTrxs)((left: Event, right: Event) => left.eventTime < right.eventTime)
```

I've done this before with collections and I can find an example I implemented using fs2 in the past if that can help.
I'll try to find a way to solve this and share my code if I'm successful.

**Comment by davidlar** [comment]
FYI. There is another method `ZStream#combine` that can be used to accomplish this. I just used it to do something similar...

**Comment by carlos-verdes** [comment]
I was reading and somehow I missed that, let me check

**Comment by carlos-verdes** [comment]
I found that method on the source code thanks, but I can't find on the documentation (it's late here so I'll double check tomorrow). You saved me lot of time!!

**Comment by davidlar** [comment]
I had the same problem and didn't find the method either but Adam helped me on discord as usual! :smiley:

**Comment by adamgfraser** [comment]
There is also `zipAllSortedByKey`.

**Comment by carlos-verdes** [comment]
I think I can close this issue and maybe request to update the documentation :)
