### ISSUE TITLE
Configurable unexpected error handler?

### ISSUE THREAD

**Issue by tim-2022** [zio/zio#8255]
I've noticed that sometimes ZIO apps silently die or misbehave in production in response to unexpected errors (e.g. null pointers, out-of-bounds, divide by zero, etc) -- unless one is flawless about "die"-level error handling (I'm not -- in my particular case, the error message implies I should have added error handling when running a seeming UStream) -- or unless one always runs services with debug-level logging turned on.

I tend to think an unexpected & unhandled error is more important than "Debug" (instead of being below "Info", even?) -- but perhaps a compromise could be: Java allows an unexpected exception handler to be installed.  Is it possible that we could maybe do something like this within ZIO?

Thank you very much for your consideration!

**Comment by adamgfraser** [comment]
It sounds like you are forking fibers but never joining them. You can configure the level that unhandled errors are logged at using `Runtime.setUnhandledErrorLogLevel`. However, generally the best solution is to join the fiber, which is how you specify that the failure of a forked fiber should be a failure of the application itself.
