### ISSUE TITLE
Optimize Zippable for Unit cases

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#8256]
Currently, Zippable has `implicit def` that construct new instances of `Zippable` when left or right are `Unit`. This is unnecessary, as we can reuse Zippable instances and cast them for the specified type parameter.

e.g.:

```scala
implicit def ZippableLeftIdentity[A]: Zippable.Out[Unit, A, A] =
    new Zippable[Unit, A] {
      type Out = A
      def zip(left: Unit, right: A) =
        right
    }
```

could be replaced by:

```scala
implicit def ZippableLeftIdentity[A]: Zippable.Out[Unit, A, A] = zippableLeftIdentity.asInstanceOf[Zippable.Out[Unit, A, A]]

private val zippableLeftIdentity: Zippable.Out[Unit, Any, Any] = 
    new Zippable[Unit, Any] {
      type Out = Any
      def zip(left: Unit, right: Any) =
        right
    }
```

etc.

In addition, some performance sensitive code could benefit from adding two methods to Zippable:

```scala
def discardsLeft: Boolean // returns true if zipping two values will discard the left one and pass the right one unmodified
def discardsRight: Boolean // returns true if ...
```

This can be used by downstream code to detect `Unit` cases and optimize appropriately through no-ops.

**Comment by adamgfraser** [comment]
I will do this.
