### ISSUE TITLE
Slow build times with Quill, can our approach be improved?

### ISSUE THREAD

**Issue by Aleks67B** [zio/zio#8271]
We have a project which uses Quill to interact with a PostgreSQL database and have found our compile times are becoming prohibitively slow, especially given the current size of our project and its expected growth.
​
At the time of writing, we have 32 database tables, and our code base contains 134 SELECTs of various complexities, 39 INSERTs, 25 DELETEs and 14 UPDATEs.  The schema is not going to get smaller as the project progresses.
​
At present, our project takes a little over two minutes to compile on a reasonable desktop computer, and between five and six minutes on our CI server (AWS t3.xlarge instance).  Of that compilation time, most of the time is taken by Quill.
​
Here is an example of a function containing a query that takes a little under two seconds to compile.  This timing was inferred by compiling using:
```
sbt compile | ts -i "%.S" | tee /tmp/compile.log
```
and looking at the times logged against each query emitted by Quill.
​
```scala
  private def fetchPageOfFamilies(pageOfIds: List[ProductFamilyId]): Task[List[ProductFamilyInfo]] = {
    if (pageOfIds.isEmpty) Task.pure(Nil) else {
      case class Row(family: ProductFamily, product: Product, supplierInternalId: SupplierInternalId,
                     category: Option[ProductCategory], status: Option[ProductFamilyStatusRecord])
      run(quote {
        for {
          family <- query[ProductFamily].filter(x => liftQuery(pageOfIds).contains(x.id))
          famMapping <- query[ProductFamilyRelationship].join(_.productFamilyId == family.id)
          product <- query[Product].join(_.id == famMapping.productId)
          supplierCode <- query[Supplier].join(_.id == product.supplierId).map(_.internalId)
          catMapping <- query[ProductCategoryProductRelationship].leftJoin(_.productId == product.id)
          category <- query[ProductCategory].leftJoin(x => catMapping.map(_.productCategoryId).contains(x.id))
          statusRecord <- currentStatus.leftJoin(_.productFamilyId == family.id)
        } yield Row(family, product, supplierCode, category, statusRecord)
      }).map { result: List[Row] =>
        val byProductFamily: Map[ProductFamily, List[Row]] = result.groupBy(_.family)
        byProductFamily.map { case (family, value) =>
          val products: Set[Product] = value.map(_.product).toSet
          val categories: Set[ProductCategory] = value.flatMap(_.category).toSet
          ProductFamilyInfo(family, products, categories, value.head.supplierInternalId, value.headOption.flatMap(_.status))
        }.toList.sortBy(_.productFamily.id.id)
      }
    }
  }
​
  private val currentStatus = quote(for {
    record <- query[ProductFamilyStatusRecord]
    if sql"SELECT MAX(id) FROM product_family_status_record GROUP BY product_family_id".as[Query[ProductFamilyStatusRecordId]].contains(record.id)
  } yield record)
```
​
Here are the definitions of the case classes that are mapped to database tables:
```scala
case class Product(id: ProductId, publicId: ProductPublicId, label: String, created: ZonedDateTime,
                   attributes: ProductAttributes, supplierId: SupplierId)
case class ProductCategory(id: ProductCategoryId, name: String, label: String, created: ZonedDateTime)
case class ProductCategoryProductRelationship(productId: ProductId,
                                              productCategoryId: ProductCategoryId,
                                              created: ZonedDateTime)
case class ProductFamily(id: ProductFamilyId, created: ZonedDateTime)
case class ProductFamilyRelationship(productId: ProductId, productFamilyId: ProductFamilyId, created: ZonedDateTime)
case class Supplier(id: SupplierId, internalId: SupplierInternalId, supplierName: Option[String],
                    clientSupplierCode: Option[ClientSupplierCode], created: ZonedDateTime)
```
​
The IDs are all strongly-typed wrappers around longs that we have explicitly-defined mappings for, e.g.
```scala
case class ProductId(id: Long)
​
implicit val productIdDecoder: MappedEncoding[Long, ProductId] = MappedEncoding(ProductId.apply)
implicit val productIdEncoder: MappedEncoding[ProductId, Long] = MappedEncoding(_.id)
```
​
We have some evidence that replacing the strongly-typed IDs with bare longs improves query compilation time, but
we are reluctant to do that because we appreciate the type-checking that Quill can do on JOIN conditions.  We
are mapping the IDs manually rather than doing `case class ProductId(id: Long) extends AnyVal` because `AnyVal`
IDs cause problems for us elsewhere; we don't know whether `AnyVal` IDs are more efficient from Quill's perspective.
​
Our `sbt` configuration for Quill and related things is:
```
  "io.getquill" % "quill-jdbc-monix_2.13" % "4.6.1",
  "org.postgresql" % "postgresql" % "42.5.4",
  evolutions,
  jdbc,
```
​
We are also doing:
```
  .settings(scalacOptions ++= Seq("-Xfatal-warnings", "-unchecked", "-deprecation", "-Ybackend-parallelism", "8"))
```
although the eight-thread parallelism seems not to make any difference to Quill.
​
We are open to suggestions about how our approach can be improved to reduce compile time.

**Comment by adamgfraser** [comment]
@Aleks67B Hi! I think you may get a better answer to this in the ZIO Quill repository. ZIO Quill uses macros to ensure that queries are valid at compile time. The trade off here is that this actually needs to be done at compile time which can increase compilation times. I think ZIO Quill maintainers and users would be in the best position to give you the best advice on how you can optimize this trade off. In any case this does not appear to be related to ZIO itself, which makes very limited use of compile time programming, and those usages do not appear to be relevant to this issue.
