### ISSUE TITLE
group operations on NonEmptyChunk/List

### ISSUE THREAD

**Issue by oker1** [zio/zio#8282]
Is there an underlying reason that the `groupBy` and `groupMap` operations are not implemented to keep the NonEmpty property of these collections or simply nobody needed them yet?

**Comment by adamgfraser** [comment]
Will take a look.

**Comment by adamgfraser** [comment]
/attempt #8282

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr561as1000hl30fbytbg25u/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
