### ISSUE TITLE
Prevent Accessing Covariant Data Types Containing Intersection Types From ZIO Environment

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#8283]
We currently prevent accessing intersection types from the environment by requiring a `Tag` when accessing the environment and only constructing a `Tag` when a type is known to not be an intersection type. This is important because a type like `ZIO[Int & String, Nothing, Unit]` is a workflow that requires an `Int` and a `String`, not a workflow that requires something that is both an `Int` and a `String`, which could not exist.

For example, the following code does not compile:

```scala
object Example extends ZIOAppDefault {

  val layerA: ZLayer[Any, Nothing, Int] =
    ZLayer.succeed(1)

  val layerB: ZLayer[Any, Nothing, String] =
    ZLayer.succeed("a")

  val layerC: ZLayer[Any, Nothing, Int & String] =
    layerA ++ layerB

  val run =
    ZIO.service[Int & String].provideLayer(layerC) // does not compile
}
```

In Scala 3 intersection types unify over covariant types, so the unification of `List[Int]` and `List[Double]` is `List[Int & Double]`. We need to extend our prohibition on intersection types to prevent covariant data types containing intersection types from being accessed from the environment as well. After this issue is closed, the following code also should not compile on Scala 3:

```scala
object Example extends ZIOAppDefault {

  val layerA: ZLayer[Any, Nothing, List[Int]] =
    ZLayer.succeed(List(1, 2, 3))

  val layerB: ZLayer[Any, Nothing, List[String]] =
    ZLayer.succeed(List("a", "b", "c"))

  val layerC: ZLayer[Any, Nothing, List[Int] & List[String]] =
    layerA ++ layerB

  val run =
    ZIO.service[List[Int & String]].provideLayer(layerC)
}
```

**Comment by joroKr21** [comment]
I'll take a crack at this bounty thing. Must feel pretty good getting paid for open source. And learn something new about dotty macros. Although I'm not sure we will like the result, variance is usually tricky to understand. But perhaps ZIO users should be comfortable with it.

**Comment by joroKr21** [comment]
/attempt #8283

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr560tnp000flb0fiopw9hsh/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by fourth44** [comment]
The problem is, this now prevents flattening ZLayers (when the inner ZLayer has an intersection of two services). I understand why this should not work for most covariant types, but I feel an exception should be made for known types which have valid 'ghost' intersection types (ZLayer and Environment?).
I can make it work if I supply a given of Tag[ZLayer[...]] using Tag.apply myself, but for me this feels like a regression of a valid use case.
See https://scastie.scala-lang.org/fourth44/SLZPUfU7RIOlLCsaLoxNOQ/1

Also note that the error message does not include the 'You must not use an intersection type' message, but just the 'Did you forget Tag, TagK, TagKKK...' message.

**Comment by joroKr21** [comment]
> The problem is, this now prevents flattening ZLayers (when the inner ZLayer has an intersection of two services). I understand why this should not work for most covariant types, but I feel an exception should be made for known types which have valid 'ghost' intersection types (ZLayer and Environment?).

I think flattening `ZLayer` should still be possible with `flatMap`. I'm not sure about these exceptions, perhaps it's possible but I'm not sure what would be the rule to allow that. I.e. is `ZLayer[A] & ZLayer[B]` really the same as `ZLayer[A & B]`?

> See https://scastie.scala-lang.org/fourth44/SLZPUfU7RIOlLCsaLoxNOQ/1

I wonder how you end up with `ZLayer` inside `UIO`? Perhaps there could be a `flatMap` missing somewhere earlier in the code.

> Also note that the error message does not include the 'You must not use an intersection type' message, but just the 'Did you forget Tag, TagK, TagKKK...' message.

Unfortunately it's not possible to provide a custom error message.
