### ISSUE TITLE
Add ZIO.readFile support for ScalaJS

### ISSUE THREAD

**Issue by DamianReeves** [zio/zio#8295]

**Comment by melsonic** [comment]
/attempt #8295

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr560a2w0004l30fxkogosp4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by admiralUrun** [comment]
Issue is solved, see  https://github.com/zio/zio/pull/8632
