### ISSUE TITLE
Add ZStream.readFile support for ScalaJS

### ISSUE THREAD

**Issue by DamianReeves** [zio/zio#8297]

**Comment by melsonic** [comment]
working on it
/attempt #8297

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr56068x000ck20fe9pt82m9/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by kaplan-shaked** [comment]
We can close this issue -
https://github.com/zio/zio/pull/8853
