### ISSUE TITLE
Memory Leak in recursive functions in Both ZIO 1 and ZIO 2

### ISSUE THREAD

**Issue by pwliwanow** [zio/zio#8316]
I've identified a possible memory leak when using recursive ZIO functions. This behavior has been observed in both ZIO 1 and ZIO 2 versions. The memory consumption grows progressively over time, and upon inspecting heap dumps, it's evident that certain objects related to the recursive calls aren't being garbage collected as expected (unless my understanding is incorrect and recurisive functions shouldn't not be used in run loops etc.).

Below is a sample program using ZIO 1 that illustrates the issue:
```scala
import zio._
import zio.clock.Clock
import zio.console.Console
import zio.duration._

object ProvideLeakyApp extends App {
  private val initialIterations = 10
  private val totalIterations = 1_000

  def run(args: List[String]): zio.URIO[zio.ZEnv, ExitCode] =
    (for {
      env <- ZIO.environment[Clock with Console]
      _ <- execute(0, env)
    } yield ()).exitCode

  private def execute(i: Int, env: Clock with Console): Task[Unit] = {
    val io = {
      if (i == initialIterations) {
        (for {
          _ <- console.putStrLn("Take a heap dump and press enter:")
          _ <- console.getStrLn
        } yield ()).provide(env)
      }
      else if (i == totalIterations) {
        (for {
          _ <- console.putStrLn("Take another heap dump and press enter:")
          _ <- console.getStrLn
        } yield ()).provide(env)
      }
      else ZIO.unit
    }
    io
      .zipRight {
        execute(i + 1, env)
          .delay(1.millisecond)
          .provide(env)
          .unless(i > totalIterations)
      }
  }
}
```

I've attached a screenshot from VisualVM that showcases the comparison between the two heap dumps.

It would be invaluable if the ZIO team could delve deeper into this issue, providing remediation for this observed memory leak or to clarify my misunderstandings in ZIO usage.

![image](https://github.com/zio/zio/assets/7759586/a40a218f-dd7e-4937-bf01-30ecbe6c4bba)

for completeness, here's similar ZIO 2 app:
```scala
import zio._

object ProvideLeakyApp extends ZIOAppDefault {
  private val initialIterations = 10
  private val totalIterations = 1_000

  override def run: ZIO[ZIOAppArgs with Scope, Any, Any] = {
    execute(0, DefaultServices.live)
  }

  private def execute(i: Int, env: ZEnvironment[Clock]): Task[Unit] = {
    val io = {
      if (i == initialIterations) zio.Console.readLine("Take a heap dump and press enter:").unit
      else if (i == totalIterations) zio.Console.readLine("Take another heap dump and press enter:").unit
      else ZIO.unit
    }
    io
      .zipRight {
        delay(execute(i + 1, env))(1.millisecond)
          .provideEnvironment(env)
          .unless(i > totalIterations)
          .unit
      }
  }

  private def delay[R, E, A](io: => ZIO[R, E, A])(duration: Duration): ZIO[R with Clock, E, A] = {
    ZIO
      .service[Clock]
      .flatMap { clock =>
        clock.sleep(duration) *> io
      }
  }
}
```

**Comment by adamgfraser** [comment]
@pwliwanow To operate in constant space recursive functions must be "effectually tail recursive", which means the recursive call must be the last call. Here you make a recursive call to `delay` but then after that you have three other calls to `provideEnvironment`, `unless`, and `unit`. The result is that the ZIO runtime must hold onto those operations to come back to them once the recursive call is done, building up a stack of those operations it needs to come back to with each recursive call.

**Comment by pwliwanow** [comment]
@adamgfraser I see, that makes sense. Thanks for the clarification!

**Comment by adamgfraser** [comment]
@pwliwanow No problem!
