### ISSUE TITLE
site docs: code snippets are too narrow

### ISSUE THREAD

**Issue by nafg** [zio/zio#8326]
At least for me, the horizontally scrollable section is a fraction of the box's width

On https://zio.dev/guides/tutorials/configurable-zio-application/:

[Screencast from 2023-08-16 20-42-42.webm](https://github.com/zio/zio/assets/98384/e9c14c4a-044b-49cb-bea1-9ea863b0f2a6)

(sorry the pointer didn't get recorded)

**Comment by nafg** [comment]
Seems to be due to a `max-width` on all `pre`s served in https://zio.dev/assets/css/styles.f376b300.css

**Comment by nafg** [comment]
I think it's from https://github.com/zio/zio/pull/8319

**Comment by adamgfraser** [comment]
@khajavi Can you take a look?

**Comment by khajavi** [comment]
@nafg Thank you for reporting. This is resolved via #8328
