### ISSUE TITLE
ZIO 2.0.16 ZLayer#zipWithPar causes memory leak

### ISSUE THREAD

**Issue by myazinn** [zio/zio#8353]
Just a simple app that takes two layers and provides them to a dummy effect forever
```scala
import zio.{ ULayer, ZIO, ZIOAppDefault, ZLayer }

object ZLayerMemoryLeak extends ZIOAppDefault {
  override def run: ZIO[Any, Any, Any] = {
    val int: ULayer[Int]       = ZLayer.succeed(1)
    val string: ULayer[String] = ZLayer.succeed("1")

    val effect = ZIO.service[Int] *> ZIO.service[String]

    effect.provideLayer(int ++ string).forever
    //    ZIO.service[Int].provide(int).forever // works fine
  }
}
```
Here's how it looks in VisualVM
<img width="1297" alt="image" src="https://github.com/zio/zio/assets/28982711/765cb01d-5473-48dd-9640-1cae2cf9ed68">
<img width="1296" alt="image" src="https://github.com/zio/zio/assets/28982711/475f89b2-08ba-49ad-a9c5-1d443da8f1a1">
For comparison, here's how it looks if I uncomment the last line
<img width="1296" alt="image" src="https://github.com/zio/zio/assets/28982711/e6141cb7-3720-4928-b6a6-5f08b4f97bfe">
Introduced here https://github.com/zio/zio/pull/8204.

**Comment by adamgfraser** [comment]
@myazinn Thanks for reporting! Will take a look.
