### ISSUE TITLE
Variadic assertTrue doesn't report which assertion failed

### ISSUE THREAD

**Issue by tjarvstrand** [zio/zio#8362]
The `assertTrue` macro is great, but unfortunately the variadic version will only report that an assertion failed on the opening line, not which condition failed, which can make it pretty inconvenient. E.g., the below code will only report that an assertion failed on the line of the `assertTrue`:

```
  ...
  assertTrue(
    someCondition,
    someOtherCondition,
  )
```

There's now an inspection in the Zio IntelliJ plugin that recommends collapsing sequential `assertTrue` into a single call to the variadic version, which I think compounds this problem. I switched over my code, because it reads nicer, and didn't realize/think about this until some tests started failing.

**Comment by adamgfraser** [comment]
I don't think I would make that an inspection.

**Comment by myazinn** [comment]
Hi @tjarvstrand 
Could you please give a bit more code / specify which ZIO version you are using? I was trying to reproduce it and it seems like it's working fine 🤔 
Here's the code that I use
```scala
import zio.test._

object AssertionRendererSpec extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("sweet")(
      test("combined test") {
        val someCondition      = "foo" == "foo"
        val someOtherCondition = "bar" == "buzz"
        assertTrue(someCondition, someOtherCondition)
      },
      test("separate test") {
        val someCondition      = "foo" == "foo"
        val someOtherCondition = "bar" == "buzz"
        assertTrue(someCondition) && assertTrue(someOtherCondition)
      }
    )
}

```
Tested on ZIO `2.0.10` and `2.0.15`, Scala `2.13.11` and `3.3.1`. On all versions, output is the same
```
+ sweet
  - separate test
    ✗ Result was false
    someOtherCondition
    at /some/path/IdeaProjects/Sandbox/main/src/test/scala/AssertionRendererSpec.scala:14

  - combined test
    ✗ Result was false
    someOtherCondition
    at /some/path/IdeaProjects/Sandbox/main/src/test/scala/AssertionRendererSpec.scala:9

```

**Comment by tjarvstrand** [comment]
Ah, perhaps it may be related to the fact that I'm using `check`. For me, this code reports the assertion failure on the line of the `assertTrue`:

```
     test("combined test") {
        check(int) { v =>
          assertTrue(
            v.isInstanceOf[Int],
            v.isInstanceOf[String],
          )
        }
      }
```

**Comment by myazinn** [comment]
Oh, now I see what you're talking about. My example was incorrect, here's a proper version
```scala
import zio.test._

object AssertionRendererSpec extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("sweet")(
      test("combined test") {
        val someCondition      = "foo" == "foo"
        val someOtherCondition = "bar" == "buzz"
        assertTrue(
          someCondition,
          someOtherCondition
        )
      },
      test("separate test") {
        val someCondition      = "foo" == "foo"
        val someOtherCondition = "bar" == "buzz"
        assertTrue(someCondition) &&
        assertTrue(someOtherCondition)
      }
    )
}
```
It will report that assertion failed on line 9, while it should've reported line 11

**Comment by vivasvan1** [comment]
/attempt #8362

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr55xmig0004jt0fhty7emim/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
