### ISSUE TITLE
ZScheduler is not shifting back to regular threadpool after blocking operation

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#8368]
After running a blocking operation (for example with `attemptBlocking`), the rest of the code from the same fiber is not shifted back to the regular threadpool and everything ends up on the blocking threadpool.

See this simple scastie: https://scastie.scala-lang.org/hFJFu9vETlW6JuXQD5YYpw

```scala
import zio._

val io = 
  for {
    _ <- ZIO.attempt(Thread.currentThread().getName()).debug
    _ <- ZIO.attemptBlocking(println("block!"))
    _ <- ZIO.attempt(Thread.currentThread().getName()).debug
  } yield ()

Unsafe.unsafe { implicit u =>
	Runtime.default.unsafe.run(io.fork.flatMap(_.join)).getOrThrowFiberFailure()
}
```

```
ZScheduler-Worker-0
block!
zio-default-blocking-1
```

The same with zio 1: https://scastie.scala-lang.org/u2xnVLUUTkCr9wvZjhjK8w
```
zio-default-async-1
block!
zio-default-async-2
```

Is that intended or is that a bug?
This behavior had disastrous effects on our application (just migrated from zio 1 to zio 2) since a huge part of our code ended up running on the blocking threadpool, which increased the number of threads and made everything quite inefficient.

**Comment by adamgfraser** [comment]
This is expected behavior. If a workflow is not specified to run on a certain executor but just happens to be running on that executor and then is shifted to a different executor, it will continue running on the other executor until a yield point.

So for example you can just yield to return to the original executor:

```scala
import zio._

object Example extends ZIOAppDefault {

  val run =
    for {
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug
      _ <- ZIO.attemptBlocking(println("block!"))
      _ <- ZIO.yieldNow
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug
    } yield ()
}
```

Or you can do enough operations to get to an automatic yield point:

```scala
import zio._

object Example extends ZIOAppDefault {

  val run =
    for {
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug
      _ <- ZIO.attemptBlocking(println("block!"))
      _ <- ZIO.unit.repeatN(5000)
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug
    } yield ()
}
```

Or if you specify that the work should be run on a particular executor it will be shifted back immediately:

```scala
import zio._

object Example extends ZIOAppDefault {

  val run =
    ZIO.onExecutor(Runtime.defaultExecutor) {
      for {
        _ <- ZIO.attempt(Thread.currentThread().getName()).debug
        _ <- ZIO.attemptBlocking(println("block!"))
        _ <- ZIO.attempt(Thread.currentThread().getName()).debug
      } yield ()
    }
}
```

**Comment by ghostdogpr** [comment]
Okay, that's why it got resolved when we decided to switch the default executor for other reasons which is basically equivalent to your second solution. 

While I don't necessarily agree with this default behavior, I think it should at least be mentioned in the migration guide (and probably the docs on blocking) because it can lead to terrible performance in some cases so better be aware about it.

**Comment by adamgfraser** [comment]
Not sure I understand. If the workflow forks any fiber those fibers will be run on the original thread pool:

```scala
import zio._

object Example extends ZIOAppDefault {

  val run =
    for {
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug
      _ <- ZIO.attemptBlocking(println("block!"))
      _ <- ZIO.attempt(Thread.currentThread().getName()).debug.fork
    } yield ()
}
```

Why should we do an additional thread pool submission when it has no benefit?

**Comment by ghostdogpr** [comment]
What we observed in production is that most of our business logic was running on the blocking threadpool because of this (our business logic is heavy and takes more than 50% of our CPU usage). That resulted in a high number of threads (instead of reusing a small number of threads for blocking I/O operations, they were all busy running business logic) leading to overall poor performance.

**Comment by adamgfraser** [comment]
I don't see how this could lead to that. If you do anything that creates a new thread pool submission, whether it is a yield or forking a new fiber, that work will be submitted to the original thread pool. The only difference is if we have the work that this specific fiber is doing should we trigger a thread pool submission earlier than we otherwise would for the work that is being done on the blocking thread we already created. There is no benefit to doing this.

**Comment by ghostdogpr** [comment]
We don't fork any fiber, it all happens in the same context:
```scala
for {
  state <- readFromDB // uses attemptBlocking
  res   <- runLogic(state)
} yield res
```
With ZIO 1, blocking threads were a small amount and used only for the blocking operations. What we observed was that because the business logic was running on it, the system had to create way more.
Note that our business logic uses `ZPure` so I guess it doesn't trigger enough IO loops to yield automatically.

**Comment by adamgfraser** [comment]
Okay but that is unrelated to the behavior here. The behavior here is just not triggering a thread pool submission when we have already created a blocking thread. It doesn't create any incremental blocking threads. If you want to limit the degree of parallelism for heavy compute work like that I would use a `Semaphore`.

**Comment by ghostdogpr** [comment]
Because it does not shift back it keeps the blocking threads busy for something they're not supposed to do, making need for more blocking threads when real blocking operations occur.

**Comment by adamgfraser** [comment]
Yeah if you want to shift back immediately you should specify that you want to run on that executor. We can definitely add something to the documentation about that. Copying @khajavi.

**Comment by khajavi** [comment]
Will do that!
