### ISSUE TITLE
`onExecutor` does not have any effect

### ISSUE THREAD

**Issue by mykytamykhailenko** [zio/zio#8388]
I'm trying to execute this piece of code:
```scala
      _ <- ZIO.onExecutor(Executor.fromExecutionContext(executor)) {
        Console.printLine(Thread.currentThread())
      }
```
However, this piece of code gets always executed on the blocking thread pool. What is the reason?
` Thread[zio-default-blocking-2,5,zio-default-blocking]`

The thread pool gets created in the following way:
```scala
ExecutionContext.fromExecutorService(Executors.newSingleThreadExecutor())
```

**Comment by adamgfraser** [comment]
Printing to the console is potentially blocking input / output so is run on the blocking executor.

**Comment by mykytamykhailenko** [comment]
Is there any way to override the blocking executor then? Or suppress the use of blocking executor in favour of plain executor?

**Comment by adamgfraser** [comment]
You can use `Runtime.setBlockingExecutor`. However I think the bigger point is you shouldn't care if printing to the console gets runs on the blocking executor.
