### ISSUE TITLE
sbt junit reports negative duration of tests

### ISSUE THREAD

**Issue by narma** [zio/zio#8396]
We have updated zio to 2.0.17 and our test reports shows negative time durations.

So here it looks like:
![telegram-cloud-photo-size-2-5203930960683455010-y](https://github.com/zio/zio/assets/91045/6a35795f-8225-4de0-aa1a-ad9352adeb45)

Our test reports are collected from default [sbt junit xml reporter](https://www.scala-sbt.org/1.x/docs/Testing.html#Test+Reports).
I've found that duration are collected from test event. This test event created at `TestExecutor` here https://github.com/zio/zio/blob/57d92a9264fbe71c9b6cf18a07d588809f096e4a/test/shared/src/main/scala/zio/test/TestExecutor.scala#L127.

And duration is calculated by default ZIO `.timed` operator https://github.com/zio/zio/blob/57d92a9264fbe71c9b6cf18a07d588809f096e4a/test/shared/src/main/scala/zio/test/TestExecutor.scala#L123

I made debug zio build, and it's really returning negative duration here.

I don't know why `.timed` returns negative value, which is the root cause of the original issue.

With git bisect I found first affected commit - merge commit of https://github.com/zio/zio/pull/8204/

That's the end of my investigation.

My original issue can'be resolved by replacing `.timed` in `TestExecutor` with manually calculating duration with `ClockLive` directly. But that did not fix the root cause.

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look.
