### ISSUE TITLE
Kryo Incompatibility with Various JDK Versions

### ISSUE THREAD

**Issue by jonathan-neufeld-asurion** [zio/zio#8431]
It is impossible to compile and build a project using Quill on more than one version of the Java JDK due to an incompatibility with a dependent library called _Kryo_ (by Esoteric Software):

This error occurs using JDK v17 but I have also experienced similar problems with Kryo on at least two other (older) JDK versions as well.

```
scalac: Error: Exception java.lang.RuntimeException: Could not obtain SerializedLambda or its methods via reflection [in thread "NGSession 5: 127.0.0.1: compile"]

```

**Quill Version**: 3.7.1 (via dooble-quill v0.13.4)

**Comment by adamgfraser** [comment]
It doesn't sound like this is an issue with ZIO.
