### ISSUE TITLE
TestClock does not adjust when running stream

### ISSUE THREAD

**Issue by solerf** [zio/zio#8469]
Hi, not sure if this is a bug or not but looking for guidance.

I have a service that watches a directory with `zio.nio.file.WatchService` and continuously streams new events:
```scala
watchService.stream
  .mapZIO(key => ZIO.scoped(key.pollEventsScoped))
  .flattenIterables
  .mapZIOPar(10)(transform)
  .runDrain
```

To ensure everything works, the following test:

```scala
test("listen new files in target path") {
  for {
    store <- ZIO.serviceWith[Settings](_.path)
    af <- ZIO.serviceWithZIO[FileWatcher](_.start()).forkDaemon // fork also tried

    wf <- Files.writeBytes(store / "filename.txt", Chunk.empty[Byte]).repeat(Schedule.spaced(2.seconds)).fork
    _ <- TestClock.adjust(2.seconds)
    _ <- wf.join
    _ <- af.interrupt
  } yield assertTrue(totalFiles == 2)
}
```

But in the logs I've got: `A test is advancing the test clock, but a fiber is not suspending` and only one file is created at the destination.

Now, I understand the clock will only advance when all fibers are `suspended` to make them run again, also removing the start step of the `FileWatcher` from the test make it works and output the two expected files. 
The `stream` from the `FileWatcher` does a `ZStream.repeatZIO` which repeats forever, my assumption is that this is blocking the `TestClock.adjust` hanging the test. If that is true how to overcome this?

I also tried running the `FileWatcher` which a `forkDaemon` to run it separated from the test fibers but no success.

**Comment by adamgfraser** [comment]
You are repeat writing every two seconds forever so your fiber never terminates and joining it suspends indefinitely.

**Comment by solerf** [comment]
ok, true indeed the join on the writer fiber is not needed but even removing it but keeping the `FileWatcher` it still hangs

**Comment by adamgfraser** [comment]
Not sure what the implementation is doing internally but if you have a fiber that never suspends then you need to use the live clock, which you can do with `TestAspect.withLiveClock`.

**Comment by solerf** [comment]
appreciated! that seems to work!

**Comment by adamgfraser** [comment]
Awesome!
