### ISSUE TITLE
ZEnvironment(...).prune[Any] doesn't prune anything

### ISSUE THREAD

**Issue by nigredo-tori** [zio/zio#8481]
I expect `.prune[A]` to only keep services mentioned in `A`, and discard everything else. This seems to hold, with one exception. `.prune[Any]` is a no-op! See [this Scastie](https://scastie.scala-lang.org/vOlOODUmSMGD2ywNn86F3w):
```scala
// ZEnvironment(String -> foo)
ZEnvironment(123, "foo").prune[String]
// ZEnvironment(Int -> 123, String -> foo)
ZEnvironment(123, "foo").prune[Any]
```

For some reason, the implementation has [this special case](https://github.com/zio/zio/blob/b9b3fd84a6fe90d3943b7167e48a7ecdea6e5840/core/shared/src/main/scala/zio/ZEnvironment.scala#L81). I'm not sure whether that is the expected behavior (in which case it should be mentioned in the ScalaDoc) or a bug caused by some attempt at optimization (in which case it should we should replace `self` with `ZEnvironment.empty`).

**Comment by adamgfraser** [comment]
This is expected behavior. The semantics of `prune[A]` are that it only keeps the services that are a subtype of `A` (or if `A` is an intersection type one of the types that makes up the intersection).

In your first example `String` is a subtype of `String` and `Int` is not a subtype of `String`. So the environment is pruned to contain only the `String` `"foo"`.

In your second second example `String` is a subtype of `Any` and `Int` is also a subtype of `Any`. So the environment is pruned to contain both the `String` `"foo"` and the `Int` `123`.

**Comment by nigredo-tori** [comment]
I see. I guess I just saw a non-intersection type as an intersection of one type (itself), and `Any` as an intersection of zero types, if that makes sense.

**UPD:** Actually, the ScalaDoc says:

> Prunes the environment to the **set of services statically known to be contained** within it.

If the type of the resulting value is `ZEnvironment[Any]`, then we don't statically know it to contain any services, so it **has** to be empty. But that's just based on documentation.

**Comment by nigredo-tori** [comment]
There are, then, other weird consequences of this choice. Consider:
```scala
val left: ZEnvironment[Int] = ZEnvironment(123)
val right: ZEnvironment[Any] = ZEnvironment(456)
// ZEnvironment(456)
left.union(right)
```
One might expect any `ZEnvironment[Any]` to behave the same way as `ZEnvironment.empty`, but that doesn't seem to be the case because of how `union` is [defined](https://github.com/zio/zio/blob/b9b3fd84a6fe90d3943b7167e48a7ecdea6e5840/core/shared/src/main/scala/zio/ZEnvironment.scala#L100-L101). I'd argue that a `ZEnvironment[Any]` bringing in **any** services is surprising.

**Comment by adamgfraser** [comment]
`Any` can be thought of that way but it is also a type itself.

And that consequence is not really related to `Any` but is a result of subtyping itself. Consider:

```scala
import zio._

object Example extends scala.App {

  trait Animal
  final case class Cat(name: String) extends Animal

  val cat1 = Cat("cat1")
  val cat2 = Cat("cat2")

  val left: ZEnvironment[Cat]     = ZEnvironment(cat1)
  val right: ZEnvironment[Animal] = ZEnvironment(cat2)

  val union = left.union(right)
  println(union) // ZEnvironment(Example::Cat -> Cat(cat2))
}
```

Here the right hand side is pruned to `Animal` but this allows any subtype of animal, which in this case is a cat but could bring in any animal in the world as you say above (imagine `Animal` is a class hierarchy representing the entire zoological classification of animals).

We can special case `Any` and say we want to treat that differently than all other types but generally that is not a good practice.
