### ISSUE TITLE
Random.nextIntBounded breaks when TestRandom.feedInt is used

### ISSUE THREAD

**Issue by vasiliy-bout** [zio/zio#8494]
I'm using `Random.nextIntBounded(62).replicateZIO(length)` in my code, and I expect that `nextIntBounded` call never returns values greater than 61.

In tests I want to generate 100 values (`length` is set to 100). I use `TestRandom.feedInts(Range(0, 100): _*)` so that the result is predictable. But the logic breaks because `nextIntBounded(62)` returns those integers passed to `feedInts` unchanged.

I could hardcode the knowledge about the upper bound 62 into my test, like this: `TestRandom.feedInts(Range(0, 100).map(_ % 62): _*)`, but in this case, if I accidentally break the logic and change the upper-bound to some invalid value, like `Random.nextIntBounded(620).replicateZIO(length)`, then I would expect my test to catch this error, but the test will not break, because the correct upper-bound in hardcoded there.

So I would expect that when I pass integer values to `TestRandom.feedInts`, then `Random.nextIntBounded(upperBound)` would do something like `Random.nextInt.map(_ % upperBound)` inside, so that the contract of `Random.nextIntBounded` method doesn't break.

**Comment by adamgfraser** [comment]
The contract of the feed methods is that the next time you generate a value of a type you get the value that was fed.

While I understand the desire to build in further logic like this, we found that it ultimately resulted in a less workable and usable model. In simple cases producing a value may just require a simple operation like modulo, but in others it may require generating additional random values, which then creates an unintuitive interface where the value returned is not the value fed and other fed values are consumed in a way that exposes an implementation detail of the algorithm used to generate particular random values.

Therefore, we stick with the much simpler model that you get back exactly what you put in. This gives you the full power to feed whatever values you want but also the responsibility to feed values that make sense. If you want to avoid this you can just not feed values at all and set a seed for deterministic testing. But the feed interface is always there if you want to specify exactly the values you want.
