### ISSUE TITLE
forkScoped from within pipeline is using wrong scope

### ISSUE THREAD

**Issue by axaluss** [zio/zio#8514]
dropping this quickly before I forget. 

My env has a `Scope` but it prefers to use a different scope when using `forkScoped` from within a pipeline. The forked fiber in the pipeline is terminated with the pipeline fiber, not with the fiber of the env- provided scope.

**Comment by adamgfraser** [comment]
It is not clear from this description whether there is any actual issue here. If you can create a minimized reproducer happy to take a look!
