### ISSUE TITLE
Add method to easily extract parallel errors from ZIO effect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#853]
When effects are combined in parallel, if they fail, then the errors are combined in parallel using `Cause`. However, it's not as easy as it could be to access the parallel errors.

This ticket describes a method that can expose _all_ parallel errors in a single call. The method will be called `parallelErrors and will be added to the `ZIO` trait inside `core` / ... / `ZIO.scala`.

```scala
trait ZIO[-R, +E, +A] { self =>
  ...
  def parallelErrors: ZIO[R, ::[E], A] = ???
  ...
}
```

The method can be implemented by calling `sandbox` on the `self` effect, and then looking at the `Cause` (perhaps using `foldM`) and pulling out all the errors (`E` values). If there is one or more, we can fail the effect returned from `parallelErrors` with `ZIO.fail`; otherwise, if there are no errors but the effect failed for other reasons, we can halt with `ZIO.halt`; and finally, if it did not fail, we can succeed with the success value using `ZIO.succeed`.

**Comment by softinio** [comment]
@jdegoes Happy to take this one. May need some extra guidance from you as this will be my first issue on ZIO itself and so will be new to its code base
