### ISSUE TITLE
zio-test: provide something like `assertAll(tests: Seq[TestResult])`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8531]
Hi, 

especially when migrating from other - fail-fast - testframeworks like ScalaTest, I find myself (and my colleagues) writing code like

```scala

for { 
... 
t1 = assertTrue(something)
 l = someList
 t2 = l.map { i => 
    assertTrue(i.id % 2 == 0) && 
    assertTrue(i.someBoolan) 
  } .foldLeft(assertTrue(true))(_ && _)
  ... 
  } yield t1 && t2
```

It would be great to clean this up somehow like 
```scala

for { 
... 
t1 = assertTrue(something)
 l = someList
 t2 = assertAll( l.map { i => 
    assertTrue(i.id % 2 == 0) && 
    assertTrue(i.someBoolan) 
  })
  ... 
  } yield t1 && t2
```

or 
```scala

for { 
... 
t1 = assertTrue(something)
 l = someList
 t2 = l.map { i => 
    assertTrue(i.id % 2 == 0) && 
    assertTrue(i.someBoolan) 
  }
  ... 
  } yield t1 && assertAll(t2)
```

I know I can easily make such helpers myself, however I think other users would benefit from this as well.

**Comment by adamgfraser** [comment]
@domdorn `TestResult.allSuccesses`

**Comment by domdorn** [comment]
`TestResult.allSuccesses` uses a varargs parameter which does not allow a `Seq[TestResult]` or `Option[TestResult]` to be passed. 
E.g. see screenshot here (still using zio 2.0.15):
![grafik](https://github.com/zio/zio/assets/100349/d2d0192b-a667-4b70-a231-f99d526419f5)

**Comment by domdorn** [comment]
Thanks!
