### ISSUE TITLE
No test found when an exception is raised in the construction of a provided layer

### ISSUE THREAD

**Issue by loicdescotte** [zio/zio#8565]
Problem found : "No test found in given " error is returned when running a zio-test test if an exception is raised in the construction of a provided layer.

Reproduction steps : 

Use ZIO 2.x and zio-test

Run this test :

```scala
import zio.test.Assertion.equalTo
import zio.test.junit.JUnitRunnableSpec
import zio.test.{Spec, TestEnvironment, assert}
import zio.{Scope, Task, ZIO, ZLayer}

trait Ops {
 def targetHost: String
}

object OpsTest extends Ops {
  override def targetHost: String = null
}

trait MyService {
  def readData : Task[List[String]]
}

class MyServiceTest(targetHostName: String) extends MyService {

  val url = s"https://${targetHostName.toLowerCase}/ws" // <- null pointer exception here

  override def readData: Task[List[String]] = {
    ZIO.succeed(List("a","b"))
  }
}

class NulTest extends JUnitRunnableSpec{
  override def spec: Spec[TestEnvironment with Scope, Any] = suite("nul test")(
    test("my test") {
      for {
        ms <- ZIO.service[MyService]
        result <- ms.readData
      }
      yield assert(result.size)(equalTo(2))
    }.provideLayer(ZLayer.succeed(new MyServiceTest(OpsTest.targetHost)))
  )
}
```

The test is running fine if you remove `.toLowerCase` (that causes the null pointer exception).

Error : 

```
Execution failed for task ':test'.
> No tests found for given includes: [NulTest](--tests filter)
```

This can be reproduced with any exception, for example if you change the code with 

```scala
object OpsTest extends Ops {
  override def targetHost: String = throw new Exception("boom")
}
```

**Comment by jdegoes** [comment]
/bounty $100

For a good, descriptive, and actionable error message as well as test failure.

**Comment by atulkrs** [comment]
can you assign this to me?

**Comment by cheikhsimsol** [comment]
/attempt #8565

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr4x8wpj0008jy0fwe92l230/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
