### ISSUE TITLE
TestClock manipulation doesn't seem to work right for shared environment

### ISSUE THREAD

**Issue by dimatkach** [zio/zio#8566]
If you fork an effect using Clock within a test, and fiddle with  TestClock in the same test, that works fine. But I am trying to have a single instance (of a heavy service) forked once, and then have all tests hit it. This seems faulty:

```
 case class TimerService(in: Queue[Int], out: Queue[Instant]) {
    def serve = ZStream.fromQueue(in)
      .takeWhile(_ > 0)
      .foreach { _ => Clock.instant.flatMap(out.offer _) }

    def ask(n: Int) = in.offer(n) *> out.take.map(_.toEpochMilli / 1000)
  }

  object TimerService {
    def fork = for {
      in <- Queue.bounded[Int](1)
      out <- Queue.bounded[Long](1)
      ts = TimerService(in, out)
      _ <- ts.serve.fork
    } yield ts
  }

  ...
  def spec: {
    suite("Shared Timer Service") ( 
     test("this does not work!") {
      for {
          ts <- ZIO.service[TimerService]
          answer <- TestClock.adjust(1.second) *> ts.ask(1)
      } yield assertTrue(answer == 1)
     }
    ).provideSomeLayerShared(ZLayer.fromZIO(TimerService.fork))
     .provideSomeLayer(ZLayer.fromZIO(TestClock.setTime(Instant.ofEpochMilli(0)))) +
    
   suit("Own timer service") (
    test("this does!") {
       for { 
         ts <- ZIO.service[TimerService]
         answer <- TestClock.adjust(1.second) *> ts.ask(1)
      } yield assertTrue(answer == 1)
    }
   ).provideSomeLayer(ZLayer.fromZIO(TimerService.fork))
    .provideSomeLayer(ZLayer.fromZIO(TestClock.setTime(Instant.ofEpochMilli(0))))
 }
 ```

So, `TimerService`  just reads commands from the `in` queue and writes what it thinks the current time is to the `out` queue. 
The test advances the clock by one second, and asks the service what time it is. First test fails (the response is 0 instead of 1), the second one works. The only difference between them is that in the first case the TimerService fork is `Shared` and in the second case it is not. 

I actually found a workaround for it: if I explicitly add `TestClock.default` to `provideSomeLayerShared` in the first test, _and_ replace `TestClock.adjust` with `ZIO.service[TestClock].adjust` then it works, but it seems ... weird (for the lack of a better word), and also I don't seem to be able to reset that clock back to zero anywhere outside of a test, which is obviously bad, so, I am just trying to understand, if this is a bug or just me doing something I am not supposed to?

**Comment by adamgfraser** [comment]
That is expected behavior. Each test is provided with a separate copy of the `TestClock` to prevent interference between tests. So when you adjust the `TestClock` in a test it is not the same one as is being used by your shared service. On the other hand when you provide `TestClock.default` you are now providing a specific implementation of the `TestClock` to your shared service and referencing the same one in your tests.

**Comment by dimatkach** [comment]
@adamgfraser ok, that makes sense ... I guess. But then why when I try something like this to the suite: 
```
TestAspect.before(ZIO.service[TestClock].flatMap(_.setTime(Instant.EPOCH)))
```
it doesn't seem to work? The tests see the clock as it was left by the previous one, not 0 ... 
Is there some way to work around this as well? I don't want to explicitly reset it in every test :(

**Comment by adamgfraser** [comment]
@dimatkach I think you may need to think more conceptually about what you are doing. Remember that tests are executed in parallel by default. So if you have multiple tests interacting with a shared clock both tests may set the clock to the initial value, then one test may set it, and then another test may read it. This is exactly why ZIO Test provides a separate copy of the test services to each test. You can do what you want with something like this:

```scala
import zio._
import zio.test._
import zio.test.TestAspect._

import java.time.Instant

object ExampleSpec extends ZIOSpecDefault {

  trait Shared {
    def set(instant: Instant): ZIO[Any, Nothing, Unit]
    def get: ZIO[Any, Nothing, Instant]
  }

  object Shared {

    val live: ZLayer[Any, Nothing, Shared] =
      ZLayer {
        for {
          clock <- testClock
        } yield new Shared {
          def set(instant: Instant): ZIO[Any, Nothing, Unit] =
            clock.setTime(instant)
          def get: ZIO[Any, Nothing, Instant] =
            clock.instant
        }
      }

    def get: ZIO[Shared, Nothing, Instant] =
      ZIO.serviceWithZIO(_.get)

    def set(instant: Instant): ZIO[Shared, Nothing, Unit] =
      ZIO.serviceWithZIO(_.set(instant))
  }

  def spec = (suite("ExampleSpec")(
    test("some test") {
      for {
        now   <- Live.live(Clock.instant)
        _     <- Shared.set(now)
        value <- Shared.get
      } yield assertTrue(value == now)
    },
    test("some other test") {
      for {
        value <- Shared.get
      } yield assertTrue(value == Instant.EPOCH)
    }
  ) @@ before(Shared.set(Instant.EPOCH)) @@ sequential).provideShared(Shared.live)
}
```

**Comment by dimatkach** [comment]
Yeah, I have to run them sequentually either way, they hitting the same database etc. ... Just trying to save on having to fork a new instance of the service for every test ...

**Comment by adamgfraser** [comment]
👍
