### ISSUE TITLE
zio-test + zio-prelude: Need way to "fuzzy compare" with Prelude

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8570]
In our services, we make heavy use of ZIO Prelude to wrap `Double`s into data types with a Unit, e.g. 
instead of just a `Double`, we have a `MW` (MegaWatts) like

```scala
  type MW = MW.Type
  object MW extends zio.prelude.Subtype[Double]
```

we now have case classes that assign values to a particular timestamp, e.g. 
```scala
case class PowerAtTime(t: Timestamp, v: MW)
```

in ZIO-Test we need to compare results of a calculation with expected values, 
e.g. 

```scala

test("compare values") { 

 val results: List[PowerAtTime] = computation()
 val expected = List( PowerAtTime(Timestamp(0), MW(3.4858273)), PowerAtTime(Timestamp(1), MW(5.3282774628)) )
 
 assertTrue( results == expected )
 }
 ```
 
 Now the computation is run (through a few layers) in an external process. This process gives slightly different results on Windows, Mac and Linux, e.g. the first Element of `expected` is not `PowerAtTime(Timestamp(0), MW(3.4858273))` but `PowerAtTime(Timestamp(0), MW(3.4858268))` on Mac ... so the last two decimal places differ. However, we're only interested in the first 4 decimal places, differences in the later places are not important. 
 
I need a way to model this, e.g. by providing a implicit `Comparator[MW]` which would be used for comparison in the macro that would only check the first 4 decimal places. I haven't found a way to do this. 
In ScalaTest, they provide stuff like 
```scala
implicit val doubleEquality = TolerantNumerics.tolerantDoubleEquality(0.01)
``` 
which is kind of what we want, but doesn't work with zio-test and also not on prelude types.

**Comment by domdorn** [comment]
could we maybe adjust the macro so that it sees if there's a implicit `zio.prelude.Equals[A]` or `scala.math.Equiv` available and use that in case its there?

**Comment by adamgfraser** [comment]
You need to use the `===` operator from ZIO Prelude if you want to compare two values for equality using ZIO Prelude's `Equal` abstraction rather than Scala;s `==` operator.
