### ISSUE TITLE
Trying to interrupt a fiber in test hangs forever? 

### ISSUE THREAD

**Issue by dimatkach** [zio/zio#8572]
I am trying to write some tests for a web service, that fork the service for a test, hit some endpoints, then kill it, but cannot figure out a way to do this that would actually work :( 

Here is an "emulated" service I wrote just to demonstrate the problem. Instead of serving web requests, it just reads strings from input queue and copies them to the output. The `Mgr`, which is also a client, keeps references to both queues, and provides an `ask` method, that simulates a client-side endpoint call. 

```
object EchoService {
  val nextId = new AtomicInteger(0)
  val manager = ZLayer.fromZIO(
    for {
      in <- Queue.bounded[String](10)
      out <- Queue.bounded[(Int, String)](10)
    } yield Mgr(in, out)
  )

  val forked = ZLayer.fromZIO(
    ZIO.acquireRelease(
      for {
        mgr <- ZIO.service[Mgr]
        f <- mgr.fork
      } yield f
    )(_.interrupt).withClock(ClockLive)
  )

  def ask(s: String) =
    ZIO.service[Mgr].flatMap(_.ask(s)).withClock(ClockLive)

  case class Mgr(in: Queue[String], out: Queue[(Int, String)]) {
    def ask(s: String) = in.offer(s) *> out.take.timeout(1.second)
    def fork = Svc(nextId.updateAndGet(_ + 1), in, out).serve.fork
  }

  case class Svc(id: Int, in: Queue[String], out: Queue[(Int, String)]) {
    val serve = ZStream.fromQueue(in)
      .takeWhile(_.nonEmpty)
      .foreach(s => out.offer(id -> s))
  }
}
```

This is how I test it: 

```
  def spec = suite("Tests")(
    suite("Forked service")(
      test("echo") { EchoService.ask("foo").map(x => assertTrue(x == Some(1, "foo"))).withClock(ClockLive) }
    ).provideSomeLayerShared(EchoService.manager >+> EchoService.forked)
```

This hangs forever ... The test completes sucessfully, and then it just hangs. 
Some debugging I have done indicates that .interrupt is invoked, but never returns.

There are two messages in the log, and I don't understand either of them: 

1. `Warning: A test is using time, but is not advancing the test clock, which may result in the test hanging. Use TestClock.adjust to manually advance the time.`
I don't get where this is using TestClock. I put `.withClock(ClockLive)` pretty much wherever I could. What else is missing? 
Is there a way to just _not_ use TestClock for the whole spec instead of having to override it everywhere explicitly? 

2. `Warning: ZIO Test is attempting to close the scope of suite Tests - Forked service in test_case_-665442250, but closing the scope has taken more than 60 seconds to complete. This may indicate a resource leak.`
Ok, so the question is _why_ this is happening. Does `.interrupt` not just kill the fiber, but behave more like java's `interrupt`, that justs politely asks the code to quit? If so, is there another method I can use to just _stop_ executing a fiber unconditionally? 

Interestingly, if instead of `provideSomeLayerShared` I use `provideSomeLayer`, the behavior changes: it still hangs but in a different way. The test does not complete (and doesn't seem to even start), and there is nothing at all in the log, except for this: 
`Test Tests - Forked service - echo has taken more than 1 m to execute. If this is not expected, consider using TestAspect.timeout to timeout runaway tests for faster diagnostics."` 

It looks like in this case it is trying to close the scope before even starting the test for some reason (and still hangs in the same place trying to call `interrupt`

I am sorry, maybe this is not really a bug, but I am pretty stuck here: documentation isn't helping, stackoverflow is silent, and chatgpt is blabbering incoherently. I am a n00b, and may be naively assuming how things "should" work based on my "common sense", so if I am doing something incorrectly here, I would appreciate any pointers to the right way to achieve what I am trying to do.

**Comment by adamgfraser** [comment]
There are multiple issues with your code:

1. The workflow that uses the `Clock` service is `ask` but you provide the `LiveClock` to practically every other workflow in your test but not that one. You can use `TestAspect.withLiveClock` to run your entire test with the live clock or `Live.live` or `Live.withLive` to run a particular part with the live clock. But if you want to use the more granular operators you need to actually use them on the part of your test that you want to use the live clock.
2. You are forking an uninterruptible fiber that never completes and then attempting to interrupt it which never completes. You fork a fiber in the `acquire` action of `ZIO.acquireRelease`. The `acquire` action is performed uninterruptibly and fibers inherit the interruptibility of their parents so the forked fiber is interruptible. You then attempt to interrupt that fiber in the `release` action but that can never complete because the fiber is uninterruptible. You can use the `interruptible` operator on the workflow you are forking to designate that it should be interruptible even though it is forked in an uninterruptible region.

See a corrected example below. We have numerous forums such as Discord where users can get help. Please use Github issues for things that are not working or feature requests, not questions about how to do something.

```scala
import zio._
import zio.stream._
import zio.test._
import zio.test.TestAspect._

import java.util.concurrent.atomic.AtomicInteger

object EchoService {
  val nextId = new AtomicInteger(0)
  val manager = ZLayer.fromZIO(
    for {
      in  <- Queue.bounded[String](10)
      out <- Queue.bounded[(Int, String)](10)
    } yield Mgr(in, out)
  )

  val forked = ZLayer.fromZIO(
    ZIO
      .acquireRelease(
        for {
          mgr <- ZIO.service[Mgr]
          f   <- mgr.fork
        } yield f
      )(_.interrupt)
  )

  def ask(s: String) =
    ZIO.service[Mgr].flatMap(_.ask(s))

  case class Mgr(in: Queue[String], out: Queue[(Int, String)]) {
    def ask(s: String) = in.offer(s) *> out.take.timeout(1.second)
    def fork           = Svc(nextId.updateAndGet(_ + 1), in, out).serve.interruptible.fork
  }

  case class Svc(id: Int, in: Queue[String], out: Queue[(Int, String)]) {
    val serve = ZStream
      .fromQueue(in)
      .takeWhile(_.nonEmpty)
      .foreach(s => out.offer(id -> s))
  }
}

object Tests extends ZIOSpecDefault {

  def spec = suite("Tests")(
    suite("Forked service")(
      test("echo") {
        for {
          x <- EchoService.ask("foo")
        } yield assertTrue(x == Some((1, "foo")))
      }
    ).provideSomeLayerShared(EchoService.manager >+> EchoService.forked) @@ withLiveClock
  )
}
```

**Comment by dimatkach** [comment]
> The workflow that uses the Clock service is ask but you provide the LiveClock to practically every other workflow in your test but not that one. 

Not sure what you mean by that. Is not providing live clock to ask? 
``` 
def ask(s: String) = ZIO.service[Mgr].flatMap(_.ask(s)).withClock(ClockLive)
```

>  The acquire action is performed uninterruptibly and fibers inherit the interruptibility of their parents so the forked fiber is interruptible. You then attempt to interrupt that fiber in the release action but that can never complete because the fiber is uninterruptible. You can use the interruptible operator on the workflow you are forking to designate that it should be interruptible even though it is forked in an uninterruptible region.

This is **pure gold**! Exactly what I was missing. Thank you so much!!!
