### ISSUE TITLE
Too big zio-test output when assertion failed on case class instances

### ISSUE THREAD

**Issue by evis** [zio/zio#8579]
When test failed, it's hard to understand why. Example: https://gist.github.com/evis/cd51be073b26c6a9f9ff45723d988e26

In this example, it's quite difficult to grasp the reason. Ideally, I'd like to see something like this:

```
receiptContent.payments(0).amount: expected 100, actual 10
receiptContent.rows(0).price: expected 100, actual 10
```

Or integrate something like https://diffx-scala.readthedocs.io/en/latest/index.html

**Comment by 987Nabil** [comment]
If you use intellij, the intellij zio plugin should now (or at least soon) show a diff link that will open the intellij diff view.

**Comment by jdegoes** [comment]
/bounty $500

For an implementation that properly "diffs" structured data, and reports only the actual differences, in as flattened a way as possible, rather than printing out the pretty-printed case class values.

**Comment by atulkrs** [comment]
can u assign this to me?

**Comment by urbit-pilled** [comment]
/attempt #8579

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr4x6rfe0004l80fdxhu3gq7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by joroKr21** [comment]
> If you use intellij, the intellij zio plugin should now (or at least soon) show a diff link that will open the intellij diff view.

I think I saw that recently, although we still use ZIO 1. I guess it will go away with the change?

**Comment by adamgfraser** [comment]
@joroKr21 That would be up to the maintainers of ZIO IntelliJ.
