### ISSUE TITLE
404 after clicking on the ZIO Newsletter button

### ISSUE THREAD

**Issue by visortelle** [zio/zio#8581]
<img width="1298" alt="Screenshot 2023-12-21 at 11 28 59 AM" src="https://github.com/zio/zio/assets/9302460/a59dfff6-b335-498a-af39-e341eaffe0dc">

<img width="866" alt="Screenshot 2023-12-21 at 11 29 09 AM" src="https://github.com/zio/zio/assets/9302460/770901f5-fcf5-41b4-a3c5-07c10076ddae">

**Comment by adamgfraser** [comment]
@khajavi Can you take a look?
