### ISSUE TITLE
Cannot replace a sequence config value with a shorter one

### ISSUE THREAD

**Issue by guersam** [zio/zio#8604]
#7700 [changed the semantic](https://github.com/zio/zio/pull/7700#discussion_r1070671785) of `ConfigProvider#orElse`  to merging all config values in left biased way.

It works with simple configuration formats, but there is a surprising case where trying to override a sequence with a shorter one.

Example: [Scastie](https://scastie.scala-lang.org/guersam/e7J2Et51Q5ezzfduSAjS1g/25)

```scala
ZIO.config(Config.chunkOf("permissions", Config.string))
  .withConfigProvider(
    fromHoconString("permissions = [admin]") orElse
    fromHoconString("permissions = [read, write]")
  )
  .map { ps =>
    assertTrue(ps == Chunk("admin")) // assertion fails: ps is Chunk("admin", "write")
  }    
```

It's reproducible with the simplest ConfigProvider such as `fromMap` when the sequence is expressed in bracket indexed format like `"foo[0]" -> "a"`.

**Comment by atulkrs** [comment]
can you assign this to me?

**Comment by atulkrs** [comment]
Plzz I will be great fit for this.

**Comment by 0xJoichiro** [comment]
/attempt #8604

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr4x472b0002l90fxo4tuecj/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by kyri-petrou** [comment]
/attempt #8604

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clr4x472b0002l90fxo4tuecj/cancel-attempt) |
