### ISSUE TITLE
Many pregenrated values via Gen

### ISSUE THREAD

**Issue by pribor** [zio/zio#8615]
Hello, I have noticed a strange behavior in `Gen`. It seems that if one generates more complex structures (simulated via `Gen.setOfN(10)(Gen.int(0, 10))`),  it generates many values even if only one is required. It seems that it is related to `forever` implementation in streams. (`rv.sample.forever.take(1)`). Is it possible to evaluate `gen` only as many times as the number of samples? 

```
    test("test") {
      def gen =
        for
          _ <- Gen.fromZIO(ZIO.debug("#### NEXT ITEM ####"))
          _ <- Gen.setOfN(10)(Gen.int(0, 10))
          _ <- Gen.fromZIO(ZIO.debug("#### FINISHED ####"))
        yield ()

      check(gen) { _ =>
        assertTrue(true)
      }
    } @@ samples(1) @@ shrinks(0)
```    

```
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
#### NEXT ITEM ####
.....
#### FINISHED ####

**Comment by adamgfraser** [comment]
There are no pre-generated values. `setOfN` needs to filter out duplicate elements to achieve the desired size which requires retrying the generator. If you use `setOf` or `ListOfN` for example you will not see this behavior.

**Comment by pribor** [comment]
Shouldn't it repeat only the generator passed in the parameters `Gen.int(0, 10)` ?

**Comment by adamgfraser** [comment]
No it needs to repeat the entire generator.
