### ISSUE TITLE
zio-test: assertTrue(someCollection.exists...) super slow

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8644]
please see attached sample test:

```scala

import zio.ZIO
import zio.test.{TestAspect, TestResult, ZIOSpecDefault, assertTrue}

object ExistsTestBug extends ZIOSpecDefault {

  case class ComplexObject(id: String,
                           name: String,
                           name2: String,
                           name3: String,
                           name4: String,
                           name5: String,
                           name6: String,
                           name7: String,
                           name8: String,
                           name9: String,
                           name10: String,
                           name11: String,
                          )
  object ComplexObject {
    def of(i: Int): ComplexObject = ComplexObject(
      id = i.toString,
      name = i.toString,
      name2 = i.toString,
      name3 = i.toString,
      name4 = i.toString,
      name5 = i.toString,
      name6 = i.toString,
      name7 = i.toString,
      name8 = i.toString,
      name9 = i.toString,
      name10 = i.toString,
      name11 = i.toString,
    )

  }
 def spec = suite("ExistsTestBug") {
   test("test") {
     for {
       _ <- ZIO.unit
       // sample of complex objects
       hugeList = (1 to 1000).map(i => ComplexObject.of(i)).toList

       shouldNotHave20 = assertTrue(!hugeList.exists(_.name3 == "20"))
       shouldNotHave510 = assertTrue(!hugeList.exists(_.name3 == "510"))
       shouldNotHave780 = assertTrue(!hugeList.exists(_.name3 == "780"))
       shouldNotHave999 = assertTrue(!hugeList.exists(_.name3 == "999"))
     } yield TestResult.allSuccesses(
       shouldNotHave20,
       shouldNotHave510,
       shouldNotHave780,
       shouldNotHave999,
     )
   }
 } @@ TestAspect.timed
}
```

The exists assertions take forever

zio version: 2.0.21
jdk: 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
os: mac os 14.2.1
cpu: apple silicon M3 max
ram: 64gb

**Comment by 987Nabil** [comment]
@domdorn since this might be macro related, the scala version might be helpful 🙂

**Comment by domdorn** [comment]
sure, 
```
ThisBuild / scalaVersion := "2.13.12"
```

**Comment by LeonardoBayona** [comment]
/attempt #8644

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clrxmsm35000ljx0frykorn7g/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by domdorn** [comment]
@LeonardoBayona thanks for your efforts! I looked at the diff of your pull request and don't see how this fixes the issue as its not touching any macro code, thus the above test will still be super slow?

**Comment by LeonardoBayona** [comment]
@domdorn I added 2 tests, `testOrig` with the same above test using `exists` and `testSlowFixed` using `existsFast`, the runtime was reduced by ~9 times. The other 2 tests in previous commit are basically the same, but with a larger size and more iterations, the runtime was reduced by ~16 times.

[Tests times in 2.13](https://github.com/zio/zio/actions/runs/7854194921/job/21434684440?pr=8666) :
```
+ ExistsTestSlowIssue
  + testSlowFixed - 5 ms
  + testOrig - 44 ms
  + testSlowExistsInListFixed - 132 ms
  + testSlowExistsInList - 2 s 148 ms
```

**Comment by CarlosEduR** [comment]
@domdorn @987Nabil would you guys be able to give more information about how we can be increasing the speed of this? I am willing to help on it, I created a new project and added the same test provided, and for me it takes 1s 37ms to execute.

**Comment by CarlosEduR** [comment]
@jdegoes would you know about it?

**Comment by jdegoes** [comment]
I think it's probably something silly like permutations over a list. Profiling is the way to know for sure.

I don't have time to look at this right now, but hopefully the bounty will encourage someone to start up the profiler!

**Comment by domdorn** [comment]
@andrzejressel could u please also create a test for a large sized list with complex objects (e.g. like above)?
cause simple exists with primitives is already faster. thanks.

**Comment by andrzejressel** [comment]
@domdorn I think it's not possible. Since the issue is not with comparison, but with pretty printing I would have to force zio-test to pretty print failure, but without actually failing. Not to mention the spam it would cause in logs.
