### ISSUE TITLE
zio-test: create `ZLayer#apply(TestAspect)`

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8654]
we have a `ZLayer#apply` for a `ZIO[R1 with R, E, A]` which given a `ZLayer[R1]` removes the `R1` from the ZIO. 
We should have the same for a `TestAspect[R1 with R, E, A]`, e.g. like this:
![grafik](https://github.com/zio/zio/assets/100349/717627dd-9cfc-4fd7-b844-28ab3da53e3f)

why do we need this? Cause currently I have to capture all the Environments needed by my spec when I just want to satisfy one dependency, e.g. 

![grafik](https://github.com/zio/zio/assets/100349/9ebea954-23c7-4df4-93cb-013e63858aae)

**Comment by adamgfraser** [comment]
You provide the environment to a `Spec` not to a `TestAspect` which you can do with the existing operators on `Spec`.
