### ISSUE TITLE
Running a test with a forked resource causes SBT to hang

### ISSUE THREAD

**Issue by atais** [zio/zio#8655]
It started with my SO question:
https://stackoverflow.com/questions/77906827/run-zio-http-server-during-zio-tests/77908225

But I am able to demo the issue:
https://github.com/atais/zio-http-e2e-test

Maybe I am creating the resource incorrectly, but well, I am quite lost already :-)
Is it a bug or my missconception?

Thanks!

**Comment by adamgfraser** [comment]
The easiest way to create a resource for a test is to use a layer. You can either use `provideLayer` if you want to create a separate resource for each test or `provideLayerShared` if you want to create a shared resource for all tests.

For example:

```scala
import zio._
import zio.test._

object ExampleSpec extends ZIOSpecDefault {

  val layer =
    ZLayer.scoped {
      for {
        promise <- Promise.make[Nothing, Unit]
        _       <- ZIO.debug("starting server")
        _       <- ZIO.addFinalizer(ZIO.debug("stopped server"))
        _       <- (promise.succeed(()) *> ZIO.never).interruptible.forkScoped
        _       <- promise.await
        _       <- ZIO.debug("started server")
        _       <- ZIO.addFinalizer(ZIO.debug("stopping server"))
      } yield ()
    }

  def spec = suite("ExampleSpec")(
    test("some test") {
      for {
        _ <- ZIO.debug("running test")
      } yield assertCompletes
    }
  ).provideLayerShared(layer)
}
```

**Comment by atais** [comment]
@adamgfraser ekhm, thanks for help, but where do I plug in the 

```
        Server
          .serve(Routes(Method.GET / "test" -> handler {
            Response.text("test")
          }).toHttpApp @@ Middleware.debug)
          .provide(Server.default)
```

?

Also how does the ZIO know the order of the finalizers? It does very little sense to me, why is "stopping server" showing before "stopped server"

I know it was your intention, but I don't understand why it works that way.

I'd really appreciate the clarification! Thanks


----

I randomly tried to adjust the example and managed to make it work with:

```
  val layer =
    ZLayer.scoped {
      for {
        _ <- ZIO.debug("starting server")
        _ <- ZIO.addFinalizer(ZIO.debug("stopped server"))
        _ <- Server
          .serve(Routes(Method.GET / "test" -> handler {
            Response.text("test")
          }).toHttpApp @@ Middleware.debug)
          .provide(Server.default)
          .forkScoped
        _ <- ZIO.debug("started server")
        _ <- ZIO.addFinalizer(ZIO.debug("stopping server"))
      } yield ()
    }
```

however I'd really wish to understand the finalizers better ;-)

**Comment by adamgfraser** [comment]
@atais Finalizers are run in reverse order of acquisition. Think about opening a connection to a remote server and then opening a file on the server. You want to close the file first because if you close the connection first you won't be able to close the file anymore.
