### ISSUE TITLE
Performance loss due to interface method invocation in ZIO's executor

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#8659]
I was looking at some benchmarking profiles for Caliban, and one thing that came to my attention is that there is a non-neglible time spent on `itable stub` on each invocation of the `runLoop` method. As you can see in the profiling screenshot at the end, **for a single invocation** of the `runLoop` method, the `itable stub` accounted for 1% of the total execution. In total, around ~10% of the total CPU time was spent on `itable stub` within `runLoop`, which is a lot given that the benchmark tests the full end-to-end performance of Caliban.

I managed to trace down the issue to [this line](https://github.com/zio/zio/blob/b316fcb00f5bfbe1f14480b9af3122154d889e88/core/shared/src/main/scala/zio/internal/FiberRuntime.scala#L853) (Note that the issue is also there for 2.0.x). Commenting out this line (for demonstration purposes only), improved the `BroadFlatMapBenchmark` throughput by 20%.

So what's the problem with this line? I don't think I can do half as a good job as [this issue](https://github.com/oracle/graal/issues/893) explaining this, but the TLDR version is that we need to avoid the interface method call in the executor's hot path.

AFAICT there is not a very straightforward way of avoiding that call. If we could somehow be a bit "smarter" on when that method is invoked (i.e., only when we need to extract the trace), that would make the executor considerably faster. Unfortunately, I don't know much about the internals of ZIO's Executor so I thought to open this issue just to bring this to your attention, and hopefully spark some ideas on how that call can be avoided.

PS: One other solution would be to call the method _after_ we've pattern matched on the concrete type, since then the call wouldn't be an interface call anymore. Having said that, I haven't tested it to know how performant that might be

<img width="1470" alt="image" src="https://github.com/zio/zio/assets/67301607/d03bb9ef-bfe6-4fa4-879c-6884dcf5e5a7">

**Comment by adamgfraser** [comment]
Thanks for reporting! Will take a look!
