### ISSUE TITLE
Docs mistake

### ISSUE THREAD

**Issue by waagnermann** [zio/zio#8667]
Hi!
In [this](https://zio.dev/reference/core/zio/#either-1) section the value of the second row in **Input Type** column probably should be `ZIO[R, Nothing, Either[E, A]]` (look at the explanation "We can submerge..." below, where this type now is already correctly represented)

**Comment by adamgfraser** [comment]
This is not correct. While it is fine if the error type is `Nothing`, the error type can also be `E` since as long as we have the same `E` in the error type and in the left side of the `Either` we can unify them.
