### ISSUE TITLE
ambiguity check break functionality

### ISSUE THREAD

**Issue by xlvp** [zio/zio#8670]
Hi! In version 2.0.21, an [ambiguity check](https://github.com/zio/zio/pull/8580) was added.
But in some cases we need to have multiple instances of the same interface.

For example in our case:

```scala
class SttpOauth2ClientCredentialsBackend[F[_], P] extends SttpBackend[F, P]

type BaseSttpBackend = SttpBackend[Task, Capabilities]
object BaseSttpBackend {
    val layer: TaskLayer[BaseSttpBackend] = ???
}

type CryptoSttpBackend = SttpOauth2ClientCredentialsBackend[Task, Capabilities]
object CryptoSttpBackend {
    val layer: TaskLayer[CryptoSttpBackend] = ???
}

(
  ZIO.serviceWith[BaseSttpBackend](_.send(???)) <*>
    ZIO.serviceWith[CryptoSttpBackend](_.send(???))
).provide(
  BaseSttpBackend.layer,
  CryptoSttpBackend.layer,
)
```

This code will fail with an error:

> [error] ──── ZLAYER ERROR ────────────────────────────────────────────────────
[error] 
[error]  Ambiguous layers! I cannot decide which to use.
[error]  You have provided more than one layer for the following type:
[error] 
[error]    sttp.client3.SttpBackend[zio.Task, Capabilities] is provided by:
[error]       1. BaseSttpBackend.layer
[error]       2. CryptoSttpBackend.live
[error] 
[error] ──────────────────────────────────────────────────────────────────────

But we need to have both layers.
Do you have any ideas what can be done about this?

**Comment by adamgfraser** [comment]
@zaxxel I would create a separate nominal type for each of these. For example:

```scala
final case class BaseSttpBackend(val value: SttpBackend[Task, Capabilities])
final case class CryptoSttpBackend(val value: SttpOauth2ClientCredentialsBackend[Task, Capabilities])

```

**Comment by xlvp** [comment]
Ok! Thank you! Apparently we used it incorrectly...
