### ISSUE TITLE
A priority queue implementation of Queue

### ISSUE THREAD

**Issue by ashwinbhaskar** [zio/zio#8673]
Current `zio.Queue` only gives an implementation of `LinkedQueue`. If you are looking for a Priority Queue you would have to use `scala.collection.mutable.PriorityQueue` but you would lose out on the nice out of the box integration with ZIO. For example you would not be able to use `ZStreams.fromQueue()`.

Is it feasible to add a Priority Queue implementation that can be accessed via, say something like, `Queue.boundedPriority[A: Ordering](..)`? 

PS: This is not for a hobby project (I see the need for this in my work)

**Comment by adamgfraser** [comment]
@ashwinbhaskar You can use `TPriorityQueue` for this.
