### ISSUE TITLE
`ZStream#takeWhileZIO` missing

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8674]
we have a `dropWhile`, a `dropWhileZIO` and a `takeWhile`, but we don't have a `takeWhileZIO` on `ZStream`. 

Current workaround for me is to write it as `takeUntilZIO` like

```scala
    consume <- Ref.make[Boolean](true)

...
.takeUntilZIO(_ => consume.get.map(!_))
``` 

ideally I could write

```scala

...
.takeWhileZIO(_ => consume.get)
```

**Comment by adamgfraser** [comment]
This was already implemented in #8623.
