### ISSUE TITLE
`mapZIOParUnordered` causes stream to skip elements when running with `runCount`

### ISSUE THREAD

**Issue by povder** [zio/zio#8683]
When running `runCount` or any method that does folding, such as `runFold`, on a stream that uses `mapZIOParUnordered`, sometimes the stream terminates before folding all elements. This happens non-deterministically.

**I can reproduce this on 2.0.20 version of zio-streams and I am unable to reproduce this anymore on 2.0.21. I went through the changelog and diff between 2.0.20 and I couldn't pinpoint a fix for this issue, so I'm reporting anyway just in case this can't be reproduced on 2.0.21 "by accident".**

This scala-cli-runnable script illustrates the issue:

```scala
//> using scala 3.4.0
//> using jvm 21
//> using dep dev.zio::zio-streams:2.0.20

import zio.{durationInt, ZIO, ZIOAppDefault}
import zio.stream.ZStream

object UnorderedTest extends ZIOAppDefault {
  val run = {
    ZStream.iterate(1)(_ + 1)
      .take(10)
      .mapZIOParUnordered(4)(a => zio.Random.nextIntBetween(100, 500).flatMap(ms => ZIO.sleep(ms.millis).as(a)))
      .debug("ELEM")
      .runCount
      .debug("COUNT")
      .tap(_ => ZIO.succeed(println("\n\n")))
      .repeatN(50)
  }
}

UnorderedTest.main(Array())
```

OS:  MacOS 14.3.1 arm64

The expected behaviour of the snippet is to print `COUNT: 10` for all repetitions.
The actual behaviour is that it prints `COUNT: 7` for some repetitions. (I think maybe I've seen a number other than 7, but I can only reproduce 7 now).

Example trimmed output:

```
ELEM: 4
ELEM: 3
ELEM: 2
ELEM: 1
ELEM: 7
ELEM: 8
ELEM: 6
ELEM: 5
ELEM: 10
ELEM: 9
COUNT: 10



ELEM: 3
ELEM: 4
ELEM: 1
ELEM: 2
ELEM: 5
ELEM: 6
ELEM: 8
COUNT: 7



ELEM: 4
ELEM: 3
ELEM: 2
ELEM: 1
ELEM: 5
ELEM: 9
ELEM: 8
COUNT: 7



ELEM: 3
ELEM: 5
ELEM: 4
ELEM: 2
ELEM: 1
ELEM: 7
ELEM: 6
ELEM: 8
ELEM: 9
ELEM: 10
COUNT: 10
```

**Comment by narma** [comment]
I think https://github.com/zio/zio/pull/8599 resolved this issue

**Comment by jdegoes** [comment]
Please re-open if not fixed.
