### ISSUE TITLE
ZStream#buffer doesn't preserve order of elements

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#8699]
Reproducer:
```scala
import zio.*
import zio.stream.*

object Test extends ZIOAppDefault {
  val expected = Chunk.fromIterable(0 until 100)
  val s        = ZStream.fromChunk(expected).buffer(16)

  def run = s.runCollect.map(_ == expected).debug.repeatWhile(identity)
}
```
It returns false after just a few iterations. If I remove `.buffer(16)`, it seems to work fine.

**Comment by ghostdogpr** [comment]
The issue is actually in `Queue` (`buffer` calls `runIntoQueueElementsScoped`).
```scala
import zio.*

object Test extends ZIOAppDefault {
  val expected = Chunk.fromIterable(0 until 100)

  def run =
    (for {
      queue         <- Queue.bounded[Int](16)
      _             <- queue.offerAll(expected).fork
      actual        <- queue.take.replicateZIO(100).map(Chunk.fromIterable)
      orderPreserved = actual == expected
      _             <- ZIO.when(!orderPreserved)(ZIO.fail(s"Order not preserved: $actual"))
    } yield ()).forever
}
```

**Comment by ghostdogpr** [comment]
Narrowed it down to this line: https://github.com/zio/zio/blob/4322d2b0d1641dbedca30a7043530b56da78b174/core/shared/src/main/scala/zio/Queue.scala#L372
When this is executed concurrently, you can end up inserting the element out of order.

**Comment by ghostdogpr** [comment]
Actually me from 2018 knew that the queue implementation was not 100% fair 😆 https://github.com/zio/zio/issues/447#issuecomment-445724577

When it comes to streams though, I think we expect the order to be maintained?

**Comment by eyalfa** [comment]
@ghostdogpr I'm currently attempting an optimization on `zio.stream.internal.ChannelExecutor#readUpstream` and experience one of the streams tests becoming flakey:
```
- ZStreamSpec / Combinators / tapSink / does not read ahead - 18 ms
        ✗ 1 was not equal to 6
        result == 6
        result = 1
        at /Users/efarago/dev/github/zio/streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala:3727
```
looking at `ZStream.tapSink` it seem like it (rightfully) relies on a bounded queue of size 1 to retain order when facing a single producer (very similar to `buffer`), I suspect something happened causing the sink fiber to see the end marker message before some of the emits. makes sense? 
I'm not 100% 'into' the queues implementation but I'd expect the single writer scenario to be valid.

* I added `@@ repeats(1000)` to the test once I understood it's flakey
* will try this on the 2.x branch as well just to make sure /i didn't introduce a regression in my WIP optimization (hope to share soon)
