### ISSUE TITLE
Infinite compile time when exceeded amount of parameters of class at ZLayer.fromFunction

### ISSUE THREAD

**Issue by Nojipiz** [zio/zio#8701]
When you include more parameters than necessary in an class instance creation within `ZLayer.fromFunction` in Scala, the compiler will continue compilation indefinitely, only halting when it reaches the Java Heap limit.

Here's an example illustrating the bug:

``` Scala
object Main extends ZIOAppDefault {
  trait ExampleTrait1
  trait ExampleTrait2
  class ExampleClass(traitOne: ExampleTrait1, traitTwo: ExampleTrait2)

  val layer: ZLayer[ExampleTrait1 & ExampleTrait2, Nothing, ExampleClass] = 
    ZLayer.fromFunction(new ExampleClass(_, _, _))

  def run = Console.printLine("Hello, World!")
}
```
Tested with: 
- Scala version = 3.3.3
- ZIO version = 2.0.21

**Comment by desavitsky** [comment]
Interesting, that in 3.4.1 it works as it should
It seems that it is a purely scala 3.3.3 bug
it fails with OOM in a such example as well:

```scala
 trait ExampleTrait1
  trait ExampleTrait2
  class ExampleClass(traitOne: ExampleTrait1, traitTwo: ExampleTrait2)

  def fun[In](a: In): Unit = println(42)

  fun(new ExampleClass(_, _, _))

```

I think, issue in scala3 repo should be created instead

**Comment by Nojipiz** [comment]
I just opened the issue at Scala: https://github.com/scala/scala3/issues/20134
