### ISSUE TITLE
2.11 JS/Native modes removed from izumi-reflect, is that ok?

### ISSUE THREAD

**Issue by pshirshov** [zio/zio#8715]
I've dropped removed Native/JS 2.11 support from izumi-reflect.

From what I can see, you've dropped 2.11 support in 2.0 branch, so could you confirm that my changes won't affect you?

**Comment by guizmaii** [comment]
I can confirm you that ZIO2 doesn't support Scala 2.11 for some time now.

See also https://github.com/zio/zio/pull/7896

**Comment by pshirshov** [comment]
I guess ZIO1 might just not update its dependency on I-R.
