### ISSUE TITLE
IO renames

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#872]
Inspired by discussion on #739, it's possible we may want to choose a more uniform naming convention for the `IO` type aliases. In particular, something like:

```scala
type IO[+A] = ZIO[Any, Throwable, A]
type RIO[-R, +A] = ZIO[R, Throwable, A]
type BIO[+E, +A] = ZIO[Any, E, A]
type UIO[+A] = ZIO[Any, Nothing, A]
type RUIO[-R, +A] = ZIO[R, Nothing, A]
```

Doing this all at once would break code, so the best strategy would be to introduce _new_ type aliases, and _new_ "companion objects":

```scala
val RIO = TaskR
val BIO = IO
...
```

Then mark the old incompatible ones as deprecated.

While in hindsight a more uniform naming convention would have been better, it's also possible that "the ship has sailed", and with more companies adopting ZIO prior to 1.0, it may be best to push off such changes to 2.0, if we want to do them.

/cc @nebtrx

**Comment by ioleo** [comment]
@jdegoes with #1154 merged, this can be closed?

**Comment by loicdescotte** [comment]
I like this proposal, and I think it should be done entirely before 1.0 as currently we a little inconstancy in names logic IMHO, as we  have IO[E,A] for something that can fail with a E and RIO[R,A] that looks like IO with an environment R but is instead an IO with the error type set as Throwable + an env.

IO[A] would fix this.

WDYT?

**Comment by ghostdogpr** [comment]
I agree with your point but I’m afraid of the confusion it would generate if we change this now, so I tend to agree with “the ship has sailed” on this.

**Comment by iravid** [comment]
Yes. No more renames, please!

**Comment by ioleo** [comment]
I'd also leave these "as is".

**Comment by adamgfraser** [comment]
Can we close? It feels like the ship has sailed on this one.
