### ISSUE TITLE
ZStream: merge and debounce are not compatible

### ISSUE THREAD

**Issue by artembakhanov** [zio/zio#8734]
I encountered an unexpected fiber interruption error when attempting  to `foreach` on two streams merged: one debounced and the other not.  Here is the min. reproducible code example (Scala 3):

```scala
import zio.*
import zio.stream.*

val stream1: UStream[Int | Unit] =
  (ZStream.succeed(0) ++ ZStream.fromZIO(ZIO.sleep(200.millis)))
    .debounce(100.millis)
val stream2: UStream[Nothing] = ZStream.empty

val effectAll = (stream1 merge stream2).runDrain

object Kek extends ZIOAppDefault:
  val run =
    for
      _ <- effectAll
        .catchAllDefect(ZIO.fail(_))
        .tapErrorCause(ZIO.logErrorCause("mmm sweet", _))
    yield ()
```
**Expected**: the application logs nothing

**Actual**: When I run this app, I get this in the logs: 

```
timestamp=2024-04-11T00:31:15.544135400Z level=ERROR thread=#zio-fiber-4 message="mmm sweet" cause="Exception in thread "zio-fiber-" java.lang.InterruptedException: Interrupted by thread "zio-fiber-6"
        Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-6"" location=<empty>.Kek.run file=IKILLEDHOURSLOL.scala line=16
```

However for some reason if you replace `100.millis` with `300.millis` it works just fine, ofc it is not the case with real applications.

I tried it on every possible zio version from 2.0.0 until 2.1-RC1 and it does not work.

**Comment by paulpdaniels** [comment]
/attempt #8734

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/paulpdaniels) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @paulpdaniels | 2 ZIO bounties | <div align="center">Scala, JavaScript, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvy4ntxw0006l309hguvm0uq/cancel-attempt) |
