### ISSUE TITLE
Add TestAspect.withLiveClock to the docs

### ISSUE THREAD

**Issue by visortelle** [zio/zio#8735]
Hi 👋

I spend the whole morning figuring out why `.retry(Schedule ...)` doesn't work in my tests.

I think `TestAspect.withLiveClock` should be mentioned in :

- Info admonition at the Installing ZIO Test page. https://zio.dev/reference/test/installation/
- At the test clock page: https://zio.dev/reference/test/services/clock/
- Probably somewhere at the TestAspects sub-page https://zio.dev/reference/test/aspects/

It would save hours for many people.

**Comment by khajavi** [comment]
@visortelle Thank you for reporting!

**Comment by jdegoes** [comment]
@visortelle Great ideas!

/bounty $50

**Comment by mobley-trent** [comment]
/attempt #8735

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mobley-trent) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mobley-trent | 2 bounties from 1 project | <div align="center">Python, Rust, <br />Jupyter Notebook</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvy4mkn2000bmk09ej6ojitg/cancel-attempt) |

**Comment by mobley-trent** [comment]
Hello @varshith257 I appreciate your interest in this issue but I am still very much interested in closing this issue.
