### ISSUE TITLE
ConfigProvider: Even when it's unnecessary, KebabCase&snakeCase parse the key to lowercase.

### ISSUE THREAD

**Issue by wi101** [zio/zio#8740]
For a configuration that uses kebabCase that has a map with keys that have hexadecimal digits separated by colons. There is a Missing data error while reading the configuration because the keys were converted to lowerCase even it was unnecessary.

Example:
```
example {
  keys {
    "01:23:45:67:89:AB": "tak"
  }
}
```

Error:
```
Missing data at example.keys.01:23:45:67:89:ab: Expected example.keys.01:23:45:67:89:ab to be set in properties.
`

**Comment by wi101** [comment]
I realised that the current implementation of kebab case is correct, it is expected to make the whole path lowercase, the issue is when the keys of a Map get changed, which supposed to be treated as constant values.

Example:
```
example {
 settings {
   "01:23:45:67:89:AB": "value1"
 }
}
```

```scala
  final case class ExampleConf(settings: Map[String, String])
```

**Comment by wi101** [comment]
@jdegoes Could you verify if this is a real issue or not?
https://github.com/zio/zio/issues/8740#issuecomment-2063693994
Sorry for the noise I wasn't sure who to ping

**Comment by jdegoes** [comment]
/bounty $100

@wi101 Looks like a real issue to me!
