### ISSUE TITLE
ZPipeline.fromFunction introduces a significant performance overhead

### ISSUE THREAD

**Issue by eyalfa** [zio/zio#8758]
ZPipeline.fromFunction was introduced by @adamgfraser in order to add ZPipeline support for some operations which are natively supported only for streams (i.e. merge and alike).

@oridag and myself were able to isolate a performance bottleneck related to this operator by introducing benchmarks which clearly show the additional overhead:

benchmark code:
```scala
  val chunkToConst : Chunk[Int] => Int = _ => 1
  val strmChunkToStrmConsts : ZStream[Any, Nothing, Chunk[Int]] => ZStream[Any, Nothing, Int] = _.map(chunkToConst)

  @Benchmark
  def zioChunkToConstDirect : Long = {
    val result =
      strmChunkToStrmConsts(ZStream
        .fromChunks(zioChunks: _*).chunks
      ).runCount

    unsafeRun(result)
  }

  @Benchmark
  def zioChunkToConstBaseline : Long = {
    val result = ZStream
      .fromChunks(zioChunks: _*)
      .chunks
      .via(ZPipeline.map(chunkToConst))
      .runCount

    unsafeRun(result)
  }

  @Benchmark
  def zioChunkToConstFromFunction : Long = {
    val result =ZStream
      .fromChunks(zioChunks: _*)
      .chunks
      .via(ZPipeline.fromFunction(strmChunkToStrmConsts))
      .runCount

    unsafeRun(result)
  }

  @Benchmark
  def zioChunkToConstFromFunction2 : Long = {
    val result =ZStream
      .fromChunks(zioChunks: _*)
      .chunks
      .via(ZPipeline.fromFunction2(strmChunkToStrmConsts))
      .runCount

    unsafeRun(result)
  }
```

benchmark results:
```
info] Benchmark                                      (chunkCount)  (chunkSize)   Mode  Cnt    Score    Error  Units
[info] StreamBenchmarks.zioChunkToConstBaseline              10000         5000  thrpt   15  158.237 ±  2.004  ops/s
[info] StreamBenchmarks.zioChunkToConstDirect                10000         5000  thrpt   15  247.806 ±  2.059  ops/s
[info] StreamBenchmarks.zioChunkToConstFromFunction          10000         5000  thrpt   15   12.009 ±  0.384  ops/s
[info] StreamBenchmarks.zioChunkToConstFromFunction2         10000         5000  thrpt   15  136.188 ± 11.971  ops/s
```

as shown in the results for `zioChunkToConstFromFunction` the overhead is over two orders of magnitude.

I suspect this is the result of the underlying implementation using `ZChannel.Bridge` which relies on some kind of a single slot buffer (with some additional synchronization and support for multiple consumers...), I was also able to come up with an alternative encoding and interpretation (which I believe can replace most usage of `ZChannel.Bridge`).
This can be seen in the results for benchmark `zioChunkToConstFromFunction2` which is comparable with the baseline.

* notice the baseline is not as fast as directly applying the function on the stream, I suspect this is due to some overhead relate to the `via` operator somewhat amplified by this specific benchmark.

I'd be happy to contribute a PR introducing the alternate `ZPipeline.fromFunction`.

**Comment by ghostdogpr** [comment]
Contribution would be welcome 👍🙏

**Comment by eyalfa** [comment]
> Contribution would be welcome 👍🙏

👍 do u happen to know if there's a way to run the benchmarks as part of the PR's CI?

**Comment by ghostdogpr** [comment]
They're not currently, just ran on a manual basis.

**Comment by eyalfa** [comment]
seems like ZChannel.Bridge is now only used by the ZChannel.mergeXXX family of functions, not really justified I might add.
these functions allow all merged channels to read from the same upstream, something similar to broadcast followed by merge, in fact most if not all stream operations involving merge operate on streams (one of the reason for introducing `ZPipeline.fromFunction`) so user's would have to work pretty hard to come up with code that utilizes the 'shared' upstream.

it's worth noting that the channel executor [identifies this and skips the bridge](https://github.com/zio/zio/blob/series/2.x/streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala#L135) in these scenarios.

so two questions here:
1. do we want to introduce the mergeXXX functions on ZPipeline as well?
2. can we completely deprecate the Bridge (I recall Adam stating on Discord he'd like to get rid of it), if so how do we replace and deprecate the ZChannel.mergeXXX family of functions which are currently public API

**Comment by ghostdogpr** [comment]
Closed by https://github.com/zio/zio/pull/8761

**Comment by ghostdogpr** [comment]
Since `Bridge` is private to zio, I think we could potentially delete if we replace its current usage by something else, but all public API need to remain.
