### ISSUE TITLE
featuring ZIO in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [zio/zio#878]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) 

This has the benefits of giving projects recognition and also lets the community and new users reference the creative ways of using Docusaurus!

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by jdegoes** [comment]
@nickbui729 That sounds great! You can find all logos [here](https://github.com/scalaz/scalaz-zio/tree/master/assets), in all sizes and formats. Thank you!

**Comment by NeQuissimus** [comment]
This should probably say ZIO, not Scalaz? :)

**Comment by softinio** [comment]
Be good if this is done after we move this repo to the new org

**Comment by nickbui729** [comment]
Sorry about the naming mistake I just fixed it! And thank you for the permission.
