### ISSUE TITLE
Cloning Zio-QuickStarts in Overview Guides Results in Fatal if User has Incorrect Rights

### ISSUE THREAD

**Issue by Yummy-Yums** [zio/zio#8782]
Hello , the link in [quickstart guide for restfule web service](https://zio.dev/guides/quickstarts/restful-webservice/#running-the-example) uses ssh login. it'll be easier to just clone via _Https_ ? Thanks

![image](https://github.com/zio/zio/assets/77977520/9c990029-ecc2-49d8-9cbb-9d0ca30655d4)

**Comment by khajavi** [comment]
@Yummy-Yums  Right! Are you interested in creating a pull request to fix the issue?

**Comment by Yummy-Yums** [comment]
Yeah, sure

**Comment by Yummy-Yums** [comment]
@khajavi I realized zio-quickstarts exists as a separate repo and is also contained in the main zio repo. do i change both? or main repo is enough.  Also, cloning via SSH is a common occurrence across the docs so i'd have to update that as well

**Comment by khajavi** [comment]
@Yummy-Yums We should update both.

**Comment by Yummy-Yums** [comment]
> @Yummy-Yums We should update both.

@khajavi  Secondly , i noticed some cli commands are wrapped in ```scala ``` , is it not supposed to be ```bash``` like below, is there a reason for this?

![image](https://github.com/zio/zio/assets/77977520/243977c6-4ffc-49e6-ad08-657df08fc80a)

**Comment by khajavi** [comment]
@Yummy-Yums  They are the mistake! Need to be fixed!
