### ISSUE TITLE
ZStream: Using `timeoutFail` logs an unhandled error

### ISSUE THREAD

**Issue by jasnross** [zio/zio#8783]
When I add `.timeoutFail` to a stream I always get an unhandled error log regardless of whether the stream timed out or not.

The log is at DEBUG level by default, but it seems like it could be misleading to see this if you have debug logs enabled.

**Example:**

```scala
import zio._
import zio.stream._

object StreamTimeoutExample extends ZIOAppDefault {
  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] =
    Runtime.setUnhandledErrorLogLevel(LogLevel.Info)

  val stream = ZStream
    .iterate(1)(_ + 1)
    .take(5)
    .schedule(Schedule.spaced(100.millis))
    .tap(n => Console.printLine(s"Received: $n"))
    .timeoutFail(new Exception("reached timeout"))(30.seconds)

  override def run = ZIO.logDebug("Start") *> stream.runDrain
}
```

**Expected:**

No unhandled error log is emitted since the stream completed successfully

**Actual:**

```
timestamp=2024-04-22T19:20:18.607412Z level=INFO thread=#zio-fiber-16 message="Fiber zio-fiber-16 did not handle an error" cause="Exception in thread "zio-fiber-16" scala.None$: None
```

**Comment by kpritam** [comment]
/attempt #8783

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kpritam) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kpritam | 1 ZIO bounty | <div align="center">Scala, Makefile, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvy4b1x80002l909723mra6g/cancel-attempt) |
