### ISSUE TITLE
Publish for Scala native 0.5

### ISSUE THREAD

**Issue by dejvid** [zio/zio#8786]
Are there plans to publish it there?

**Comment by ghostdogpr** [comment]
I believe it depends on this first https://github.com/zio/izumi-reflect/pull/459

Contributions welcome!

**Comment by kitlangton** [comment]
/attempt #8786

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kitlangton) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kitlangton | 1 ZIO bounty | <div align="center">Scala, Ruby, <br />Haskell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvy3chsa000jmi09plzmrjig/cancel-attempt) |

**Comment by kitlangton** [comment]
Cancelling for now as there are still a bunch of dependencies we need to wait on.
 https://github.com/cquiroz/scala-java-time/issues/504
