### ISSUE TITLE
Application doesn't await completion of uninterruptible fibers forked in global scope

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#8787]
It seems that the `ZIOAppDefault` runtime doesn't await for uninterruptible fibers to finish executing prior to exiting after it receives a SIGINT signal

To reproduce: Run the program below in IntelliJ and then Stop it 2-3 seconds later. The program will stop running immediately and print a `Process finished with exit code 130 (interrupted by signal 2:SIGINT)` 

```scala
object Foo extends ZIOAppDefault {
  val ef = ZIO.suspendSucceed(ZIO.sleep(10.seconds) *> ZIO.debug("FINISHED")).uninterruptible.forkDaemon

  def run = ef *> ZIO.never
}
```

**Comment by loathwine** [comment]
We also noticed this issue at my company. I think this has been an issue since ZIO 1.
I've created a workaround service as an alternative, but ideally there would be a better solution in ZIO.
[GracefulDaemon.scala](https://gist.github.com/loathwine/badd0c1f6c2ec1f0ddce65688dfd01d2)

**Comment by kyri-petrou** [comment]
@loathwine I went back quite a few versions trying to see where this bug originated from but it seems it's been present in most ZIO 2.x releases. Which I found a bit surprising because looking at the current code I believe it's meant to await for globally-scoped fiber completion 😨
