### ISSUE TITLE
Making Config Loader API Simpler

### ISSUE THREAD

**Issue by khajavi** [zio/zio#8789]
Let's say I have a config schema like below:

```scala
case class AppConfig(port: Int)

object DatabaseConfig {
  implicit val config: Config[AppConfig] = ???
}
```
Currently, when we need to load an `AppConfig` we need to write something like this:

```scala
ZIO.config(DatabaseConfig.config)   // reading this code feels somhow strange
```

But I think it is better to change the API using implicit arguments to have something like this:

```scala
ZIO.config[DatabaseConfig]  // simpler api
```

**Comment by jdegoes** [comment]
/bounty $75 for the fix and updates to documentation

**Comment by kpritam** [comment]
/attempt #8789

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvy3bynx0006mi09qbpaet6v/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
