### ISSUE TITLE
add conversion to `FiniteDuration` to zio.duration

### ISSUE THREAD

**Issue by domdorn** [zio/zio#8797]
Unfortunatelly we still have a lot of akka in our codebase.
akka always requires `scala.concurrent.duration.FiniteDuration` instances, however I always have `zio._` imported. 
There's already a `.asScala` conversion, however that one gives me just the supertype `scala.concurrent.duration.Duration` when I need the subtype. 

could we maybe have a `.asScalaFinite` or `.asScalaFiniteUnsafe` that would return a `FiniteDuration` for everything that is not infinity? 

https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/Duration.scala#L176-L181

Thanks!

**Comment by jdegoes** [comment]
I think `asScala` could be made to return FiniteDuration always, which might be the better fix.

**Comment by NavidJalali** [comment]
> I think `asScala` could be made to return FiniteDuration always, which might be the better fix.

Isnt that a regression? I mean what would it return for the infinite case?

**Comment by jdegoes** [comment]
@NavidJalali The thing is, there is no infinite case. It's faked. It used to exist back when we used Scala duration but `Duration.Inf` was ported over to mean "big finite" when we adopted `java.time` structures.

(Unless I'm missing something...)

**Comment by asr2003** [comment]
/attempt #8797

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvy3ajth0002jn09rgevfaa8/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
