### ISSUE TITLE
Documentation For Getting Started with ZIO

### ISSUE THREAD

**Issue by keylou** [zio/zio#8822]
Hello.

On this documentation page for zio 2.0.x https://zio.dev/overview/getting-started

the dependency zio version 0.0.0 is added

**Comment by khajavi** [comment]
Hello @keylou 
Thank you for reporting!
Here is the related file that needed to be fixed:
https://github.com/zio/zio/blob/series/2.x/docs/overview/index.md

**Comment by keylou** [comment]
Same problem on:

1. https://zio.dev/reference/stream/installation/
Related file: https://github.com/zio/zio/blob/series/2.x/docs/reference/stream/installation.md

2. https://zio.dev/reference/test/installation/ 
Related file: https://github.com/zio/zio/blob/series/2.x/docs/reference/test/installation.md

**Comment by keylou** [comment]
Checked case object BuildInfo in project.
It has no realisation in field version:

val version: _root_.scala.Predef.String = ???

Is this how it should be?

**Comment by khajavi** [comment]
@keylou 
If you would like to work on this, I would suggest using [site variables introduced by mdoc](https://scalameta.org/mdoc/docs/installation.html#configure-site-variables-like-version)

**Comment by khajavi** [comment]
Here is an example on zio-http project: https://github.com/zio/zio-http/blob/main/build.sbt#L331
