### ISSUE TITLE
ZIO chat on zio.dev is broken

### ISSUE THREAD

**Issue by swoogles** [zio/zio#8838]
ZIO chat pops up with its initial "How can I help?"-style greeting, but then does not respond to anything. Also prevents submitting any additional queries while the first one hangs.

<img width="937" alt="Screenshot 2024-05-10 at 9 54 26 AM" src="https://github.com/zio/zio/assets/2054940/e06b10ac-e0f4-4cca-a52e-0a395361addf">

Should either fix, if it's an easy token refresh or something, or disable/hide it.

**Comment by khajavi** [comment]
@swoogles Thanks for reporting! Fixed!
