### ISSUE TITLE
`.map` breaks fresh layers

### ISSUE THREAD

**Issue by hearnadam** [zio/zio#8858]
Minimized reproducer:
```
  class A
  class B
  val a = ZLayer {
    for {
      _ <- Console.printLine("A")
    } yield new A {}
  }
  val b = ZLayer {
    for {
      _ <- ZIO.service[A]
      _ <- Console.printLine("B")
    } yield new B {}
  }

  def run =
    {
      ZIO.service[A] *> ZIO.service[B]
    }.provide(a.fresh.map(identity), b)
```

Expectation:
- A layer maintains its 'freshness' regardless if an operator is invoked on it.
- Using operators such as `.debug` should not modify freshness of a layer

Console output:
```
A
B
```

Removing the `map`:
```
  def run =
    {
      ZIO.service[A] *> ZIO.service[B]
    }.provide(a.fresh, b)
```

Console output:
```
A
A
B
```

**Comment by jdegoes** [comment]
/bounty $100 for fix and regression test cases.

**Comment by kpritam** [comment]
/attempt #8858

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kpritam) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kpritam | 1 ZIO bounty | <div align="center">Scala, Makefile, <br />Kotlin & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clw829t2p0002l509zcbu9yaj/cancel-attempt) |
