### ISSUE TITLE
Scala 2.13 - cannot compare child class to parent class in assertTrue

### ISSUE THREAD

**Issue by andrzejressel** [zio/zio#8874]
Scala 2.13 only

https://scastie.scala-lang.org/rwgljZz2Q6m0aDTwkBDczA

```scala
import zio.test.assertTrue

class A
class B extends A
val a = new A()
val b = new B()
assertTrue(a == b)
assertTrue(b == a)
```

error:
```
type mismatch;
 found   : Playground.A
 required: Playground.B
not found: value location
```

Prepared test for `SmartAssertionSpec.scala`

```scala
    test("equalTo compiles when comparing different primitive types") {
      val a = 1
      val b = 1L
      assertTrue(a == b) && assertTrue(b == a)
    },
    test("equalTo compiles when comparing types that are direct descendants") {
      class A
      class B extends A
      val a = new A()
      val b = new B()
      assertTrue(a == b) && assertTrue(b == a)
    },
```

**Comment by andrzejressel** [comment]
~Now when I think about it - maybe it should work that way? I guess the issue is Scala 3 allowing that ...~

I was wrong (from equals Javadoc):

```
The equals method implements an equivalence relation on non-null object references:

It is symmetric: for any non-null reference values x and y, x. equals(y) should return true if and only if y. equals(x) returns true.
```

**Comment by andrzejressel** [comment]
I was wrong (from equals Javadoc):

```
The equals method implements an equivalence relation on non-null object references:

It is symmetric: for any non-null reference values x and y, x. equals(y) should return true if and only if y. equals(x) returns true.

**Comment by andrzejressel** [comment]
It seems like `c.inferImplicitValue` does not work for function `B` => `A` if they are descendants.

https://docs.scala-lang.org/overviews/quasiquotes/syntax-summary.html#types - `tq` in ZIO's case return Tree which returns null for `.tpe`

**Comment by kyri-petrou** [comment]
Hey @andrzejressel, I was going to link [this issue](https://github.com/zio/zio/issues/8754) on why I think this behaviour is correct for Scala 2 but not for Scala 3, but then I realised you were the one that opened it 😅 

Why do you think that in this case Scala 3's behaviour is correct but not Scala 2's?

**Comment by andrzejressel** [comment]
They are both a bit scuffed  - basically I believe that all directly related classes should be comparable in any order.

In Scala 2.13 it didn't work because of bug with implicit conversion finding, in Scala 3 it does not work because this conversion is not implemented for equals (only for `>` `>=` `<` `<=` comparisons).

EDIT: Even equals JavaDoc agrees with that - comparing parent to child should (must?) return the same as comparing child to parent.
