### ISSUE TITLE
`ZIO#someOrElse` does not work with covariant type constructors applied to `Nothing`

### ISSUE THREAD

**Issue by notxcain** [zio/zio#8890]
Hey there!

The following snippet does not compile.
```scala
ZIO.succeed(Option.empty[List[String]]).someOrElse(List.empty)
```

Unless I specify the type explicitly, which feels redundant and could be very noisy in a real codebase.
```scala
ZIO.succeed(Option.empty[List[String]]).someOrElse(List.empty[String])
```
I expect `someOrElse(a)` to be isomorphic to `map(_.getOrElse(a))`, e.g. the first snippet should behave like this
```scala
ZIO.succeed(Option.empty[List[String]]).map(_.getOrElse(List.empty))
```

This could be fixed by using one more subtype evidence as follows:
```scala
final def someOrElse[B, C](
    default: => C
  )(implicit ev: A IsSubtypeOfOutput Option[B], cb: C <:< B, trace: Trace): UIO[B] =
    map(a => ev(a).getOrElse(default))
```

However this change is certainly not binary compatible. 

Are there any workarounds? Is there anything we could do in 2.0?

**Comment by ghostdogpr** [comment]
I don't think there is much we can do in 2.x besides creating another variant but that would be quite dirty. Something to improve in zio 3.x?

**Comment by 987Nabil** [comment]
For Scala 3 users, extension methods are very cheap and could be used. In Scala 2 I would probably add the zio as a first param list to a custom method. I don't like the implicit way.

@ghostdogpr would it make sense to have a place to document zio 3 ideas? Or have a label for it?

**Comment by ghostdogpr** [comment]
Added the label

**Comment by jdegoes** [comment]
> Are there any workarounds? Is there anything we could do in 2.0?

There is a trick we can do: make the old method private, and then introduce the new method. 

New code will use the new method, and old code can continue to use the old method. 

Needs to be verified, of course.

/bounty $75

**Comment by notxcain** [comment]
/attempt #8890

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx1sitw20006m7094j6jl8kb/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
