### ISSUE TITLE
`TestArrow::withLocation` and `TestArrow::meta` cannot override a TestArrows location.

### ISSUE THREAD

**Issue by BalduinLandolt** [zio/zio#8893]
On `TestArrow` there is a method `withLocation` which takes a `SourceLocation` and which you would expect to return a new TestArrow with the updated location.
In practice, this returns an identical TestArrow, unless it is previously `None`.  
The same behaviour can be seen when calling the `meta` method on `TestArrow`, with the param `location` as `Some(string)` (which is how `withLocation` is implemented).

Reproducible example:

```scala
import zio.*
import zio.test.*

object sample extends ZIOSpecDefault {
  override def spec =
    suiteAll("sample") {
      val testResult: TestResult         = assertTrue(true)
      val arrow: TestArrow[Any, Boolean] = testResult.arrow
      val newArrow1                      = arrow.withLocation(SourceLocation("new location", 0))
      val newArrow2                      = arrow.meta(location = Some("new location:0"))
      test("test initial location") {
        arrow match
          case TestArrow.Meta(_, _, _, _, Some(locationString), _, _, _) =>
            assertTrue(locationString != "new location:0")
          case _ => throw new AssertionError(s"Unexpected")
      }
      test("test location after modification 1") {
        newArrow1 match
          case TestArrow.Meta(_, _, _, _, Some(locationString), _, _, _) =>
            assertTrue(locationString == "new location:0")
          case _ => throw new AssertionError(s"Unexpected")
      }
      test("test location after modification 2") {
        newArrow2 match
          case TestArrow.Meta(_, _, _, _, Some(locationString), _, _, _) =>
            assertTrue(locationString == "new location:0")
          case _ => throw new AssertionError(s"Unexpected")
      }
    }
}
```

This is due to the implementation of `meta`, which seems to be using the value of `self` for all fields (except code!) and only uses the passed params if it is None on self.

https://github.com/zio/zio/blob/3e502861a9ae7aba742ca2ad21b4c8364bdbd191/test/shared/src/main/scala/zio/test/TestArrow.scala#L121-L140

This would be pretty easy to change, but since I do not know why it is implemented like this, I'm not sure if this is as intended.

An easy workaround is to simply create a new TestArrow, but the behaviour seems strange, so I thought I'd report it after all.

**Comment by jdegoes** [comment]
/bounty $125

For:

1. Flipping around the order of `a.orElse(b)` to `b.orElse(c)` in `meta`, for all the fields, which will have the effect of PREFERRING the right-hand side (normal Scala idiom).
2. Verifying no existing tests pass, or fixing them if necessary.
3. Adding a new test to verify you can "set" things that were previously set.

**Comment by asr2003** [comment]
/attempt #8893

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx1sgmtq000fl309623jjalz/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
