### ISSUE TITLE
zio 2.1.2 issue with stuck tests

### ISSUE THREAD

**Issue by Ivoyaa** [zio/zio#8922]
Hi! I encountered a compatibility problem while trying to update my project from 2.0.15 to 2.1.2. 

I got a really simplified example of what I am trying to do: https://github.com/Ivoyaa/zio-2.1.2-example
The problem is that HappyPathSpec gets stuck on 2.1.X but actually completes test suite on 2.0.X. 

It might be that I just missed some really important messages in Release Notes. Anyway, would appreciate any help / advice.

**Comment by ghostdogpr** [comment]
It might be because you're blocking in your tests and we disabled auto-blocking detection. Try this test aspect: https://github.com/zio/zio/pull/8835

**Comment by Ivoyaa** [comment]
@ghostdogpr thanks for the tip!

I tried to do it like this but still it does not finish. The test passes but it looks like MyApp continues running.

```scala
import zio.test.TestAspect.blocking
import zio.test.{Spec, TestEnvironment, assertTrue}
import zio.{Scope, ZIO}

object HappyPathSpec extends MySpecBase {

  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("Happy path")(
      test("success") {
        for {
          _ <- ZIO.unit
        } yield assertTrue(true)
      }
    ) @@ blocking
}
```

**Comment by ghostdogpr** [comment]
Hmm I had a look and I think `ZIO.attempt(MyApp.main(Array()))` is not really appropriate because you're effectively blocking forever. `main` never completes and there is no way to interrupt it. It would be better if you run an actual IO (which is interruptible) rather than `main`.

**Comment by Ivoyaa** [comment]
I see. I know that the use case looks a bit obscure. We use this pattern for out e2e-tests. We provide all infra-dependencies with testcontainers, run our app through MyApp.main() to build actual app as is with all its endpoints, Kafka-processes, cron-processes, recurring jobs and then test out API. 

Probably we can factor out our main, bind it to Scope, run it with forkScoped without zipPar(ZIO.never). Do you think that would work and shutdown as expected? 🤔

**Comment by kyri-petrou** [comment]
@Ivoyaa can you changing [this line](https://github.com/Ivoyaa/zio-2.1.2-example/blob/0564e5983faf14fe6a25bc86563eeee8f12f11dc/src/test/scala/MySpecBase.scala#L7C3-L7C50) to this and let me know if it works?

```scala
override val bootstrap = testEnvironment ++ ApplicationForE2E.live
```

**Comment by Ivoyaa** [comment]
@kyri-petrou tried it, still gets stuck 👀

**Comment by kyri-petrou** [comment]
@Ivoyaa I think there is some weird interaction going on with the test environment/runner and the invocation of `ZIOApp#main` method.

As a quick workaround, you can change [this line](https://github.com/Ivoyaa/zio-2.1.2-example/blob/0564e5983faf14fe6a25bc86563eeee8f12f11dc/src/test/scala/ApplicationForE2E.scala#L12) to use the `invoke` method, which is the one that should be used for testing:

```scala
MyApp.invoke(Chunk()).forkDaemon
```

Just be wary, as per the documentation of the `invoke` method this is only meant for testing!

**Comment by Ivoyaa** [comment]
Oh, that helped in our project as well.

Great thanks for your work, guys!
