### ISSUE TITLE
ZIO Config Guide Invalid link

### ISSUE THREAD

**Issue by Yummy-Yums** [zio/zio#8926]
[ZIO -Config guide]( https://zio.dev/zio-config/) points incorrectly to itself instead of Dive into [Dive into ZIO config](https://zio.dev/zio-config/dive-into-zio-config) . 

i tried editing the page but link points to a not found

**Comment by varshith257** [comment]
/attempt #8926

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxrln4ph000rjt09mqg1arvr/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by guptadeepak8** [comment]
sry for inconvenience of previous PR
