### ISSUE TITLE
2.1.3 regression of mapZIOPar(Unordered) with Int.MaxValue level of parallelism

### ISSUE THREAD

**Issue by narma** [zio/zio#8935]
Regression (or breaking change) introduced https://github.com/zio/zio/pull/8908 here.
New implementation creates bounded queue with parallelism level of elements.

When using `mapZIOPar` or `mapZIOParUnordered` with `Int.MaxValue` of parallelism (or other big enough), which is suggested by official doc (https://github.com/zio/zio/blob/series/2.x/docs/reference/architecture/non-functional-requirements.md#5-high-throughput) leads to this failure
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
  | zio.internal.RingBuffer.<init>(RingBuffer.scala:158)
```

For example:
```scala
ZStream(1,2,3,4,5).mapZIOParUnordered(Int.MaxValue) { p =>
    ZIO.debug(p)
  }.runDrain
```

Currently our code which uses Int.MaxValue in several places has been changed to just use some high value here. But I'm wondering, should old behavior work as well? Also how much bigger in terms of memory usage is the new implementation?

**Comment by narma** [comment]
@eyalfa can you take a look please

**Comment by kyri-petrou** [comment]
While I agree that this is a regression and needs to be fixed, I think we should also change the docs and potentially have a variant of `mapZIOParUnordered` that doesn't require the users explicitly the parallelism level.

While the docs state that `Int.MaxValue` is for demonstration purposes only, they also imply that `Int.MaxValue` effectively means "unbounded parallelism", which is very wrong imho.

**Comment by kyri-petrou** [comment]
@eyalfa looking at the code, I'm wondering; does it even make sense for the parallelism queue to be bigger than the buffer? If I'm reading the code correctly, the parallelism will be `bufferSize + 1` at best no?

**Comment by narma** [comment]
@kyri-petrou about
> `Int.MaxValue` effectively means "unbounded parallelism" 

Just found an interesting line, exactly that meaning :D

https://github.com/zio/zio/blob/83f209184f055a651c8d02a541f22026ff2bd07c/streams/shared/src/main/scala/zio/stream/ZChannel.scala#L2299-L2303

**Comment by eyalfa** [comment]
@kyri-petrou I'll have a look, a bit surprised this pop since I recalled adding the line @narma pointed at.

**Comment by kyri-petrou** [comment]
@eyalfa I think you added it in a previous PR at a different part, but I think we need to do the same handling for `mapZIOPar` et.al.

**Comment by eyalfa** [comment]
@narma is it happening on the parallelism or bufferSize parameter?
if it's the parallelism param, it introduces two issues, seems like both the ordered and unordered versions are affected:
1. impossible to create a bounded queue of `Int.MaxValue`
2. the number of fibers won't be bound, unlike the old impl which used a fiber per element the new one uses a 'fibers pool'

#1 is easily fixable by using an unbound queue, #2 is harder as it requires some kind of mechanism to detect if some of the workers are available atm.

another option for #2 is to change the fibers such that when using unlimited parallelism, they'd poll the queue for the next work item and terminate if there's none. I suspect this may have bad influence on performance as many fibers will terminate after executing a single task, resulting with lots of child fibers related message to the parent fiber and weak references handling.

**Comment by eyalfa** [comment]
> @eyalfa I think you added it in a previous PR at a different part, but I think we need to do the same handling for `mapZIOPar` et.al.

yes I can now see this piece of code in `ZChannel.mergeAllWith` (the overload handling the back pressure strategy):
```
val offer = q0.offer(in)
              if (runningFibers == n)
                offer.as(n)
              else if (bounded)
                offer *> nestedStreamsProcessor.fork.as(runningFibers + 1)
              else {
                //when unbounded, we run the risk of spawning a fiber per channel,
                //even worse, each such fiber may end up processing one or less channels...
                //in any case these fibers are kept as long as this channel is running which may incur waste of resources.
                //this attempts to mitigate this by detecting scenarios where an idle worker was able to immediately pick the enqueued message, as a result we get a 'best effort' behavior of limiting the number of fibers.
                //the unbounded scenario is used by ZStream.groupBy and indeed it requires a fiber per sub-stream,
                //furthermore in most cases all sub streams 'survive' till processing ends so we're actually required to keep a fiber per stream in this case.
                offer *> nestedStreamsProcessor.fork.unlessZIO(q0.isEmpty).map {
                  case Some(_) => runningFibers + 1
                  case _       => runningFibers
                }
              }
```

once the queue is unbounded it's possible to make a best effort to limit the number of forked fibers, is this good enough for the mapZioXXX cases as well?

**Comment by kyri-petrou** [comment]
> @eyalfa looking at the code, I'm wondering; does it even make sense for the parallelism queue to be bigger than the buffer? If I'm reading the code correctly, the parallelism will be `bufferSize + 1` at best no?

@eyalfa what do you think about this by the way

**Comment by kyri-petrou** [comment]
Actually I'm even wondering if this is an issue with the current implementation, I think the previous one didn't have this limitation

**Comment by eyalfa** [comment]
> > @eyalfa looking at the code, I'm wondering; does it even make sense for the parallelism queue to be bigger than the buffer? If I'm reading the code correctly, the parallelism will be `bufferSize + 1` at best no?
> 
> @eyalfa what do you think about this by the way

out of the top of my mind (this requires some thorough thinking): just like any thread pool, the queue is there just to mitigate bursts, what actually matters is the number of threads (fibers in this case). so my hunch is: the queue can be bounded at any finite size, assuming the buffer size is also finite this should work.

notice that the queue size doesn't limit parallelism, especially when the parallelism parameter is unbounded: there will always be a fiber to grab the next message.

when parallelism is bounded, even if the tasks are length and the queue is a single element queue, soon enough there will be `n` fibers running, so parallelism is totally separated from bufferSize.

**Comment by eyalfa** [comment]
@kyri-petrou , took another look at the code,
your statement is correct in regard to the ordered version due to the fact upstream enqueues to both queues so the smaller queue effectively limits parallelism.

another issue with the ordered version, most call sites ton't specify the `bufferSize` which is then assigned the value of `n`, meaning if one is unbounded so with the other be.

I hope I can find some time to work on this next week, I guess first step would be introducing test cases...

**Comment by kyri-petrou** [comment]
@eyalfa it seems that parallelism is correctly respected afterall (see tests in https://github.com/zio/zio/pull/8940).

We just need a fix for the bounded queue now. I think we can use something semantically very large as a limit on parallelism for now (we can do go for 4096 or something) and cap it there as a temporary patch

**Comment by kyri-petrou** [comment]
@eyalfa I spoke too soon 😢 It seems the test uses `mapZIOParUnordered`, but if I change it to `mapZIOPar` then the 2nd test fails

**Comment by kyri-petrou** [comment]
@eyalfa good news, we have tests now thanks to @narma to test for parallelism: https://github.com/zio/zio/pull/8940

You'll need to remove the `ignore` aspect from the test though first

**Comment by eyalfa** [comment]
@kyri-petrou I don't see tests introducing unbounded par operators in #8940 
what I do see is a scenario where bufferSize is smaller than parallelism, effectively causing mapZIOPar to deadlock, a simple fix for the finite case is transforming bufferSize using `bufferSize max n`. this basically means: if you permit parallelism of `n` you effectively agree to hold up to `n` elements in memory. 
notice that the two queues implementation effectively protects us from buffering `n + bufferSize` elements since it enqueues to both queues before pulling the next element, hence one full queue is enough to block the process limiting in-flight elements to `n + 1` (or 'bufferSize + 1' when it's larger than n).

this makes me think what's the meaning of the bufferSize parameter here, seems it's only useful when larger than parallelism, in this case it compensates for a slow downstream.

**Comment by narma** [comment]
Resolved by https://github.com/zio/zio/pull/8954
