### ISSUE TITLE
.provide triggers WartRemover ExplicitImplicitTypes error in ZIO 2.1.3

### ISSUE THREAD

**Issue by thijsnissen** [zio/zio#8936]
At work we are expected to use [WartRemover](https://www.wartremover.org/). We use Scala `2.13.14`. The minimized example below compiles with ZIO `2.1.2`. Since `2.1.3`, WartRemover throws the following error (the same error occurs when using .make and .provideSome):

```
[error] [wartremover:ExplicitImplicitTypes] implicit definitions must have an explicit type ascription
[error]       .provide(ZLayer.succeed(new Foo("baz")))
[error]               ^
```
Minimized example (using scala-cli):

```
//> using scala "2.13.14"
//> using dep "dev.zio::zio:2.1.3"
//> using plugin "org.wartremover::wartremover:3.1.6"
//> using options "-P:wartremover:traverser:org.wartremover.warts.ExplicitImplicitTypes"

import zio._

case class Foo(bar: String)

object Main extends ZIOAppDefault {
  val run: UIO[ExitCode] =
    ZIO.service[Foo]
      .provide(ZLayer.succeed(Foo("baz")))
      .exitCode
}
```
Is this something that could be fixed? How should we handle this?

**Comment by lemony312** [comment]
I am getting the error `local val trace$macro$6 in value deps`
val deps = ZIO....
                     .provide(???)
