### ISSUE TITLE
Unintuitive behaviour of `checkAll`

### ISSUE THREAD

**Issue by imRentable** [zio/zio#8949]
Hello,

I am really fond of the property-based testing toolkit that ZIO test provides. However, I am struggling with the implicit differences in the behaviour of deterministic and non-deterministic generators in conjunction with their respective helper functions `check` and `checkAll`. The main complexity is caused by the hidden contract that there are (finite) determinstic and non-deterministic generators in the first place. For instance, I have to read the documentation of a generator to know what kind of the aforementioned ones it is. `check` and `checkAll` will gladly accept either of them. Unfortunately, this causes some unintuitive behaviour that introduces the risk of silently introducing false-positive test cases. 

Please see the following example suite:

```scala
import zio.{Scope, ZIO}
import zio.test.TestAspect.shrinks
import zio.test._

// ZIO Version: 2.1.2
object CheckAllSpec extends ZIOSpecDefault {
  override def spec: Spec[TestEnvironment with Scope, Any] = suite("Filtered Generators")(
    // expectation: test hangs
    test("non-deterministic with filter succeeds without value") {
      checkAll(Gen.int(1, 1000).filter(_ == 0)) { int =>
        ZIO.debug(int) *> assertTrue(int == 0)
      }
    },
    // expectation: I don't know but producing only one value seems odd. Perhaps default to `check()` behaviour?
    test("non-deterministic without filter produces only one value") {
      checkAll(Gen.int(1, 1000)) { int =>
        ZIO.debug(int) *> assertTrue(int == 0)
      }
    },
    // expectation: Fail or at least warn that no value could be produced.
    test("deterministic with filter succeeds without value") {
      val iterable = 1 to 1000
      checkAll(Gen.fromIterable(iterable).filter(_ == 0)) { int =>
        ZIO.debug(int) *> assertTrue(int == 0)
      }
    }
  ) @@ shrinks(0)
}
```
- **Test 1**: A filtered non-deterministic (infinite) generator that will never produce a value is used with `checkAll` which could be caused by a mere typo. Instead of hanging, which I would expect, it simply succeeds.
- **Test 2:** A non-deterministic (infinite) generator is used with `checkAll` which could be caused by a mere typo. It produces just one value which I find odd. That being said, I don't know what the best solution here would be. Perhaps defaulting to `check`? 
- **Test 3**: A filtered deterministic (infinite) generator that will never produce a value is used with `checkAll`. This test succeeds directly as well. Of course, this reflects the behaviour of a an all-quantifier that will yield true for an empty set but this can also be caused by a typo, resulting in an undesired false-positive. 

It would be great if it would be harder to shoot oneself in the foot by accidentally stumbling into the aforementioned scenarios. Reflecting the kind of generator in the type system could make sense. This should ensure that one does not use an unsuitable generator for their use case.

**Comment by jdegoes** [comment]
I am not sure what to do with this one, because any change here would break backward compatibility. While it's true there's a DX issue here, caused by lack of type safety, it would only be encountered during test development.

Maybe there are modest changes we could make that don't affect backward compatibility, such as warning with empty generators, etc.

**Comment by imRentable** [comment]
I see... well, a warning would already be useful. Currently, I find myself adding printlns to sanity-check whether my gens are actually generating multiple or any values at all.

**Comment by jdegoes** [comment]
/bounty $150 for warnings being generated and printed to guide the user to fix the issues.

**Comment by kyri-petrou** [comment]
/attempt #8949

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;22 ZIO bounties <br/> + 2 bounties from 1 project | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center">﹟8983</div> | [Cancel attempt](https://console.algora.io/api/bounties/clz89pruk0004l409adlt9dwa/cancel-attempt) |
