### ISSUE TITLE
Type inference of the E type breaks down when using ZIO.retry in conjunction with ZIO.provide

### ISSUE THREAD

**Issue by CatsDogsAndOther** [zio/zio#895]
import java.util.concurrent.TimeUnit

import scalaz.zio.clock.Clock
import scalaz.zio.duration.Duration
import scalaz.zio.{IO, Schedule, ZIO}

import scala.concurrent.Future

class Example {

  // what I have to do
  def fetchRemoteData1(): IO[RemoteClientException, RemoteData] = {
    val keys: List[String] = List("key1", "key2")

    val io: ZIO[Clock, RemoteClientException, RemoteData] =
      ZIO
        .fromFuture{ implicit ec => remoteCall(keys) }
        .timed
        .mapError { e: Throwable => RemoteCallFailedException(e) }
        .map { case (d, x: RemoteData) => x }
        .timeoutFail(RemoteCallTimeoutException())(Duration(100, TimeUnit.MILLISECONDS))
        .retry(Schedule.recurs(2))

    io.provide(Clock.Live)
  }

  // what I have want to do
  def fetchRemoteData2(): IO[RemoteClientException, RemoteData] = {
    val keys: List[String] = List("key1", "key2")

    ZIO
      .fromFuture{ implicit ec => remoteCall(keys) }
      .timed
      .mapError { e: Throwable => RemoteCallFailedException(e) }
      .map { case (d, x: RemoteData) => x }
      .timeoutFail(RemoteCallTimeoutException())(Duration(100, TimeUnit.MILLISECONDS))
      .retry(Schedule.recurs(2))
      .provide(Clock.Live)
  }

  // what also breaks
  def fetchRemoteData3(): IO[RemoteClientException, RemoteData] = {
    val keys: List[String] = List("key1", "key2")

    val io =
      ZIO
        .fromFuture{ implicit ec => remoteCall(keys) }
        .timed
        .mapError { e: Throwable => RemoteCallFailedException(e) }
        .map { case (d, x: RemoteData) => x }
        .timeoutFail(RemoteCallTimeoutException())(Duration(100, TimeUnit.MILLISECONDS))
        .retry(Schedule.recurs(2))

    io.provide(Clock.Live)
  }

  // the retry seems to contribute to the issue as this compiles fine
  def fetchRemoteData4(): IO[RemoteClientException, RemoteData] = {
    val keys: List[String] = List("key1", "key2")

    ZIO
      .fromFuture{ implicit ec => remoteCall(keys) }
      .timed
      .mapError { e: Throwable => RemoteCallFailedException(e) }
      .map { case (d, x: RemoteData) => x }
      .timeoutFail(RemoteCallTimeoutException())(Duration(100, TimeUnit.MILLISECONDS))
      .provide(Clock.Live)
  }

  // this compiles fine as well.
  def fetchRemoteData7(): ZIO[Clock, RemoteClientException, RemoteData] = {
    val keys: List[String] = List("key1", "key2")

    ZIO
      .fromFuture{ implicit ec => remoteCall(keys) }
      .timed
      .mapError { e: Throwable => RemoteCallFailedException(e) }
      .map { case (d, x: RemoteData) => x }
      .timeoutFail(RemoteCallTimeoutException())(Duration(100, TimeUnit.MILLISECONDS))
      .retry(Schedule.recurs(2))
  }

  final def remoteCall(keys: Iterable[String]): Future[RemoteData] = ???

  sealed trait RemoteClientException extends RuntimeException

  case class RemoteCallFailedException(e: Throwable) extends RemoteClientException

  case class RemoteCallTimeoutException() extends RemoteClientException

  case class RemoteData(data: List[Int])
}

This is the compilation error 2 and 3 cause
>Error:(40, 15) type mismatch;
 found   : scalaz.zio.IO[Any,Example.this.RemoteData]
    (which expands to)  scalaz.zio.ZIO[Any,Any,Example.this.RemoteData]
 required: scalaz.zio.IO[Example.this.RemoteClientException,Example.this.RemoteData]
    (which expands to)  scalaz.zio.ZIO[Any,Example.this.RemoteClientException,Example.this.RemoteData]
      .provide(Clock.Live)

**Comment by jdegoes** [comment]
I've seen this before, and I think we should be able to fix this. Thank you for reporting!

**Comment by ghostdogpr** [comment]
I believe this is fixed in RC12.
@CatsDogsAndOther please reopen if you find it still happens.
