### ISSUE TITLE
Using STM is much slower than using a single Ref even with contention

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#8983]
Here's the result of `SingleRefBenchmark`:
```
[info] Benchmark                     (fibers)  (ops)   Mode  Cnt     Score     Error  Units
[info] STMBenchmarks.refContention         10   1000  thrpt    5  4854.440 ± 300.593  ops/s
[info] STMBenchmarks.trefContention        10   1000  thrpt    5   440.238 ±   5.423  ops/s
```
Also if I add a single ref case to `TMapContentionBenchmarks`:
```
[info] Benchmark                      Mode  Cnt    Score   Error  Units
[info] STMBenchmarks.contentionRef   thrpt    5  204.426 ± 2.632  ops/s
[info] STMBenchmarks.contentionTMap  thrpt    5   29.248 ± 1.729  ops/s
[info] STMBenchmarks.contentionTRef  thrpt    5   33.547 ± 1.804  ops/s
```
In both cases, using a single `Ref` is an order of magnitude faster than STM even in a contention case, which makes STM loses its appeal.

**Comment by jdegoes** [comment]
STM gradually regressed in performance over time as various fixes and improvements were incorporated.

/bounty $2500 for broad-based optimization of STM sufficient to come close to or surpass performance of Ref in the above benchmarks.

**Comment by kyri-petrou** [comment]
I'll give this a go

/attempt #8983

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;21 ZIO bounties <br/> + 1 bounty from 1 project | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz89nwh30002jo09gfy9debg/cancel-attempt) |
