### ISSUE TITLE
Clarify documentation on initialization of test bootstrap layers

### ISSUE THREAD

**Issue by tjarvstrand** [zio/zio#8993]
At the moment, it's not entirely clear from the [documentation](https://zio.dev/reference/test/sharing-layers-between-multiple-files/) that layers of the same type that are shared between different test suites will be re-initialized unless they are actually the same reference.

For example, having a common super class for database tests that defines a connection layer at the class level will create one connection (or connection pool) for each test suite, and not close them until after all suites have finished, potentially exhausting the database connection allowance.

It would be useful, I think to document that it is necessary to define such layers in a central place, such as the companion object.

**Comment by varshith257** [comment]
/attempt #8993 

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 4 bounties from 2 projects | <div align="center">TypeScript, Scala, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz89lyw1000ijy096ape0iiv/cancel-attempt) |
