### ISSUE TITLE
Flaky Stream test

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#900]
There is a flaky Stream test that tests zipWith:

```
[error]     x zipWith prioritizes failure
[error]  TIMEOUT: 60 seconds (file:1)
```

/cc @iravid

**Comment by jdegoes** [comment]
Ignore, it's a legit failure. 😄

**Comment by iravid** [comment]
Oh yeah? I'm rewriting this operator and trying to track down a similar failure. What was the issue?

**Comment by jdegoes** [comment]
Maybe I spoke too soon, but I know I'm getting 100% failures right now in my local branch (#897). So whatever problem it had is being greatly exacerbated.

**Comment by jdegoes** [comment]
I haven't diagnosed it, btw.

**Comment by iravid** [comment]
Just comment it out in your branch for now I suppose. I'll figure it out as part of the ZManaged rewrite.

**Comment by jdegoes** [comment]
Ok, will spend 10 more minutes on it because I want to make sure I didn't break `raceWith` in any way, then I'll comment it out for now.

**Comment by iravid** [comment]
I've not seen this in a while after the ZManaged rewrite. Shall we close?

**Comment by iravid** [comment]
Closing this out as it seems to be well-behaved now
