### ISSUE TITLE
ZSink.collectAllToMap{N} should have value extraction function

### ISSUE THREAD

**Issue by vladvershinin** [zio/zio#9028]
I think, it would be nice to have an option to build map `Map[K, B]` from `ZStream[_, _, In]` in one operation.

Presently, `ZSink.collectAllToMap[In, K]` that makes a `Map[K, In]` is present.

## Problem example

I found this pattern very common
```
case class Person(name: String, age: Int)

val stream: ZStream[_, _, Person] = ???
// and then you need
val map: Map[String, Int] = ???
```
So, instead of 
```
mapA <- stream.run(ZSink.collectAllToMap(_.name)((_, b) => b))
mapFinal = mapA.view.mapValues(_.age)
```
this could be
```
mapFinal <- stream.run(ZSink.collectAllMap(_.name)(_.age)((_, b) => b))
```

## Please, share your thoughts.

Your feedback and suggestions are highly appreciated.

---

## Part 2. Naming and compatibility problems

If you find this idea useful, naming and compatibility questions arise.

Doing this in vacuum, I'd put value projection function as the second parameter group.
```
  def collectAllToMap[In, K, V](
    key: In => K
  )(
    value: In => V
  )(f: (In, In) => In)(implicit trace: Trace): ZSink[Any, Nothing, In, Nothing, Map[K, V]] =
```
But this breaks backwards compatibility.

So as this option because of implicit Trace still present and should be in the last argument.
```
  def collectAllToMap[In, K, V](
    key: In => K
  )(
    f: (In, In) => In
  )(
    value: In => V = identity[In]
  )(implicit trace: Trace): ZSink[Any, Nothing, In, Nothing, Map[K, V]] =
```

## Questions

Then is seems it should be a new method with a new name?
`collectAllToMapValue`? Sounds bad. I am lack of good ideas.

I have no experience in such problems.
Is it really impossible to add a parameter into a method that has any implicit arguments in the end without breaking backwards compatibility?

**Comment by jdegoes** [comment]
/bounty $75 for `collectAllToMapValue` and test cases (it's not a bad name, just long 😄 ).

**Comment by Petter-K** [comment]
/attempt #9028

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz89e0jt0002mh090wxq8q6u/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
