### ISSUE TITLE
Support child scope

### ISSUE THREAD

**Issue by domdorn** [zio/zio#9043]
Hi, 

we prototyped this code to create a "child" scope, e.g. we are already in a code path that has a wider `Scope` but want some effect to have a smaller scope:

```scala

  def childScope[R, E, A](effect: => ZIO[R with Scope, E, A])(implicit trace: Trace): ZIO[R with Scope, E, A] = 
    ZIO.scope.flatMap(scope => scope.fork.flatMap(childScope => childScope.use[R](effect)))

```

use case: 
we have a long running effect PARENT (e.g. multiple hours) that is run in a scope and creates a bunch of resources using acquire-release. 
this long running process has some effects (CHILD1, CHILD2, CHILD3) that each do a bunch of acquire-release, e.g. create temporary files, run an external program, process the data of the temporary files and cleans them up . 
We want the child effects to have a smaller scope (that is still connected to the bigger scope), so they trigger their cleanup operations when they are finished, not when the long running process is finally complete. 

The code above is our naive approach in doing that.. we're not sure if this interferes with some mechanics in zio.

**Comment by kyri-petrou** [comment]
Hey @domdorn. Assuming that you want the child scope to still be governed by the parent scope, this is the correct way of doing it. Is there anything that's not working well for you with this approach?

**Comment by kyri-petrou** [comment]
Another approach in case you also want to fork the effect via the method:

```scala
  def forkAsChild[R, E, A](effect: => ZIO[R with Scope, E, A])(implicit trace: Trace): ZIO[R with Scope, Nothing, Fiber.Runtime[E, A]] =
    ZIO.scope.flatMap(scope => scope.fork.flatMap(childScope => effect.forkIn(childScope)))
```

**Comment by jdegoes** [comment]
@domdorn By "connected to the parent scope", you mean that if the parent scope is closed, the child scopes are all closed? 

Or do you mean something else?

**Comment by domdorn** [comment]
> @domdorn By "connected to the parent scope", you mean that if the parent scope is closed, the child scopes are all closed?
> 
> Or do you mean something else?

Yes, if the parent scope gets closed or the fiber that created the child scope gets interrupted/cleaned up.

**Comment by jdegoes** [comment]
Can you look into `ZIO.transplant`?

**Comment by guizmaii** [comment]
@domdorn Seems like John provided you the solution. Closing. Feel free to ask me to re-open if needed
