### ISSUE TITLE
Allow running some effect before / after a single sample of check

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio#9046]
# What
This is similar to what was asked for in https://github.com/zio/zio/issues/5285 and https://github.com/zio/zio/issues/4007.

Goal would be to have some mechanism to run an effect before/after a single sample of check. This is different to the existing TestAspect.{before,after,around} as these run effects around the _entire test_ which includes the entire test block.

# Why

Sometimes it is useful to test side-effecting programs using property based testing. An example would be specs for a database, where you want to generate the data to insert into the database and assert against later. This can be useful to detect issues that otherwise. One exampe for this is the mismatch between precision for timestamps in postgres (up to micriseconds) and java.time.Instant (up to nanoseconds). Issues such as this are much easier to find using property-based-testing.

An alternative that can be used is to have a custom function that sets up the database, and is also what I'm currently using, something like:
```scala
test("insert and get user") {
  check(GenUser) { user => 
    withPreparedDb {
      for {
        userRepository <- ZIO.service[UserRepository]
        _ <- userRepository.insert(user)
        retrieved <- userRepository.get(user.id)
      } yield assert(retrieved)(equalTo(user))
    }
  }
}
```
The problem with this is that it plays very badly with reusing the tests / running them against multiple targets. For example, if you have a fake implementation of the UserRepository that you want to use for other tests, it is very nice to be able to run the same tests against that one as well. This works great with the existing aspects / provide, but doesn't work at all with setup functions like above without additional machinery.

# How

I think that best UX for this would be additonal aspects that only run code before / after / around a single sample. Somthing like TestAspect.beforeCheck. I.e. the above would become:
```scala
test("insert and get user") {
  check(GenUser) { user => 
    for {
      userRepository <- ZIO.service[UserRepository]
      _ <- userRepository.insert(user)
      retrieved <- userRepository.get(user.id)
    } yield assert(retrieved)(equalTo(user))
  }
} @@ TestAspect.aroundCheck(preparedDb)
```

This could be implemented using a fiber ref. We are already passing data into tests using fiber refs into the tests with the TestConfig, so it also would not be a big departure from what we already have.
We could add a new FiberRef or add a new field to TestConfig, using it to pass an `UIO[Unit]` or `Option[URIO[Scope, Unit]]` into the test. Inside of the checkStream function that actually runs the property based test, this fiberRef would be retrieved and the embedded effect applied to the test code.

---

If you are happy with the above proposal I'm happy to work on this, so just give me a short 👍 / 👎 to let me know.

**Comment by kyri-petrou** [comment]
I think this is OK, although I'm slightly concerned with not ending up adding too many methods to `TestAspect` to improve UX for every possible use-case.

Just thinking out loud, but what do you think about adding just a single `TestAspect.fromZIOAspect` (open to suggestions for the name) which takes a `ZIOAspect` and specify in the scaladoc that unlike `before`/`after`/`around` this aspect will be applied to each individual iteration of `check`? This aspect then can be used for standard tests as well as property-based tests

**Comment by kyri-petrou** [comment]
Actually I think it might be too complicated to set it up like this. What about adding an aspect that wraps an existing aspect in order to apply it to each iteration of `check`? Then it can be used as:

```scala
TestAspect.checks(TestAspect.before(???)))
```
Is that something's that's doable you recon?

**Comment by mschuwalow** [comment]
I don't think all of the TestAspects make sense when applied to checks. For example annotate, exceptX, parallel don't really make sense.

I do think having at least the around version of such an aspect is valuable though as it's something that cannot be done with current aspect api, as they cannot look into individual test cases.

I understand your concern regarding api surface of test aspect though.

I guess we do have at least one additional option:
We could expand samples produced by check into new independent tests, as was discussed in the linked issues. This would make all aspects work seamlessly with check, but would break backwards compatibility unless we introduce this behavior as new api while keeping the old.
Perhaps we could have something like checkSuite which expands a generator + test code into a suite of tests without generators.

**Comment by jdegoes** [comment]
/bounty $150 for @kyri-petrou's spec for `TestAspect.checks` and associated tests.

**Comment by mschuwalow** [comment]
/attempt #9046

~~I still believe that not all Aspects make sense for individual checks. I plan to split TestAspect into two groups of aspects:~~
~~1. Ones that operate on a zio effect and don't really care about it being a spec. These include before, after, ... and will works with the new TestAspect.checks~~
~~2. Ones that only really have well defined semantics when applied to a spec, such as ignore.~~

~~Idea would be to introduce a subtype of TestAspect to encode this split. Something like `abstract class EffectAspect[+LowerR, -UpperR, +LowerE, -UpperE] extends TestAspect[LowerR, UpperR, LowerE, UpperE]`.~~
~~Would that work for you?~~

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz88nq5d0002mi09ku82m5gs/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
