### ISSUE TITLE
ZStream scoped doesn't release the resource

### ISSUE THREAD

**Issue by pribor** [zio/zio#9052]
zio: 2.1.6
scala: 3.3.0 and 3.4.2

Hello, It seems that `ZStream.scoped` doesn't release the resource in some cases. I'm not able to fully isolate the problem as it starts working when I use more deterministic operators.

```
object MyApp extends ZIOAppDefault:

  def resource = ZIO.acquireRelease(ZIO.debug("acquire"))(_ => ZIO.debug("resource released"))

  val stream = ZStream.succeed(1)
    .repeat(Schedule.spaced(1.second))
    .flatMap(_ => ZStream.scoped(resource))
    .schedule(Schedule.spaced(1.second))


  override def run =
    for
      s <- stream.runDrain.fork
      _ <- ZIO.sleep(2.second)
      _ <- s.interrupt
    yield ()
```

prints only `acquire`

**Comment by kyri-petrou** [comment]
Hmm this is really bizarre. For some reason it seems that the finalizers are deferred to the end of the stream, but even more weirdly it seems they're not run once the stream finalizes. Changing the last  `.schedule` to `500.millis` "solves" the issue, but of course that's not a proper solution.

Thanks for reporting, I'll take a look

**Comment by jdegoes** [comment]
/bounty $250 for a reproducing test case and proper fix.
