### ISSUE TITLE
Enable multithreading for ZIO Native support

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#9056]
This will require ditching the versions of many structures copy/pasted from Scala.js and using true multi-threaded implementations, potentially from the JDK if they have Scala Native analogues.

**Comment by jdegoes** [comment]
/bounty $1500 for enabling Scala native multithreading in all tests and fixing all issues this identifies, such that the tests are green.

**Comment by asr2003** [comment]
I will give it a try

/attempt #9056

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/asr2003) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @asr2003 | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 1 bounty from 1 project | <div align="center">JavaScript, Go, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz89s15b000hl4094bl7l00j/cancel-attempt) |

**Comment by varshith257** [comment]
After following up with @asr2003 to support multithreading in native, got a feasible solution. Collaborating with @asr2003 to solve this issue. Finally overcame the issue encountered `SIGSEGV` (code 11) error with `nativeConfig ~= {_.withMultithreading(true)}`  after ditching copy-pasted scala.js structures.

Need a couple of adjustments in native tests to support multithreading env. With this,

/attempt #9056



<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 5 bounties from 3 projects | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz89s15b000hl4094bl7l00j/cancel-attempt) |

**Comment by sideeffffect** [comment]
It's lovely to see progress on this guys @varshith257 @asr2003  :tada: 
Be careful about how to interact with Algora , so that you can properly split the bounty between yourselves if you want. I think there's something like `/split` command?
