### ISSUE TITLE
Examples for Providing Partial Dependencies

### ISSUE THREAD

**Issue by ashkan-leo** [zio/zio#908]
I am trying to partially provide dependencies to a `z: ZIO[R, E, A]` object. I can't figure out how to do this. I don't find any example on how to use `provideSome` and `provideSomeM` functions either.
It'd be great if someone could write some examples on how this can be done.

**Comment by politrons** [comment]
@ashkan-leo maybe this example it might help you https://github.com/politrons/reactiveScala/blob/master/zio/src/main/scala/com/features/zio/ZIOLayer.scala#L216

**Comment by kitlangton** [comment]
Addressed by new docs
