### ISSUE TITLE
Consider rewriting recursive ZIO methods to iterate instead

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#9082]
I'm opening this as an issue so that we can track it (and so that I don't forget about it 😅)

While working on #9081 I realised that we have a fair amount of `ZIO` methods that use recursion when it can be avoided. e.g., the current implementation of `forever`:

```scala
  final def forever(implicit trace: Trace): ZIO[R, E, Nothing] = {
    lazy val loop: ZIO[R, E, Nothing] = self *> ZIO.yieldNow *> loop

    loop
  }
```

Can be rewritten to:

```scala
  final def forever(implicit trace: Trace): ZIO[R, E, Nothing] =
    ZIO.whileLoop(true)(self)(_ => ()).asInstanceOf[ZIO[R, E, Nothing]]
```

This is much more performant as it doesn't require yielding in order to avoid iterating deeper into the `FiberRuntime` stack.

Interestingly, we already do adopt this approach in some methods (e.g., [iterate](https://github.com/zio/zio/blob/e85906a7e4cc817df778fe6f0df513c9ff63686e/core/shared/src/main/scala/zio/ZIO.scala#L3971-L3980)) so it might be good to adopt it wherever possible

**Comment by jdegoes** [comment]
This may require iterate be changed to yield every n iterations.

/bounty $450

**Comment by yanisoln** [comment]
/attempt #9082

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/yanisoln) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @yanisoln | 1 bounty from 1 project | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0mmyjyo0002l403x5rsw0tz/cancel-attempt) |

**Comment by 987Nabil** [comment]
@yanisoln fyi: There is already an open PR
