### ISSUE TITLE
`ZStream.interruptWhen(promise)` changes behavior of another stream

### ISSUE THREAD

**Issue by nedsociety** [zio/zio#9091]
With certain setup, a stream seems to block for no reason by just adding `interruptWhen(promise)` with a completely unrelated `promise` to another blocking stream, when those two streams were intertwined within `ZStream.unwrap()`. See the reproducer below.

### Reproducer
```scala
//> using dep dev.zio::zio:2.1.7
//> using dep dev.zio::zio-streams:2.1.7

import zio.*
import zio.stream.*

object Main extends ZIOAppDefault {
  def run = for {
    requestQueue            <- Queue.unbounded[String]
    totallyUnrelatedPromise <- Promise.make[Throwable, Unit]
    _                       <- ZStream
                                 .unwrap(
                                   ZStream
                                     .fromQueue(requestQueue)
                                     .runForeach(msg => ZIO.debug(s"message received: $msg"))
                                     .fork
                                     .as(ZStream.succeed("") ++ ZStream.never)
                                 )
                                 // commenting and uncommenting the line below changes the behavior
                                 .interruptWhen(totallyUnrelatedPromise)
                                 .runDrain
                                 .fork
    _                       <- requestQueue.offer("some message").delay(250.millis).forever
  } yield ()
}
```

```bash
@ scala-cli run repro.scala                # When `.interruptWhen(...)` is commented out: works as intended
message received: some message
message received: some message
message received: some message
message received: some message
message received: some message
...
^C

@ scala-cli run repro.scala                # When `.interruptWhen(...)` is NOT commented out: blocks indefinitely
^C
```

Related issues:
- https://github.com/devsisters/shardcake/issues/133 (original report)
- #7460 (seemingly similar symptom)

**Comment by nedsociety** [comment]
cc. @ghostdogpr

**Comment by kyri-petrou** [comment]
This looks like a legitimate bug, but the part that I find very weird is that it's only present when `fork` is used in the inner effect.

If you use `forkScoped` / `forkIn(scope)` it works as expected:

```scala
import zio.*
import zio.stream.*

object Main extends ZIOAppDefault {
  def run = for {
    requestQueue            <- Queue.unbounded[String]
    totallyUnrelatedPromise <- Promise.make[Throwable, Unit]
    _ <- ZStream
      .unwrapScoped(
        ZStream
          .fromQueue(requestQueue)
          .runForeach(msg => ZIO.debug(s"message received: $msg"))
          .forkScoped
          .as(ZStream.succeed("") ++ ZStream.never)
      )
      // commenting and uncommenting the line below changes the behavior
      .interruptWhen(totallyUnrelatedPromise)
      .runDrain
      .fork
    _ <- requestQueue.offer("some message").delay(250.millis).forever
  } yield ()
}
```

Note that it also works with `unwrap` and `forkDaemon`.

PS: You don't need to use a promise to reproduce it, you can simply use `interruptWhen(ZIO.never)`

**Comment by kyri-petrou** [comment]
PS: You don't need to use `totallyUnrelatedPromise` to reproduce it, you can simply use `ZIO.never`

**Comment by kyri-petrou** [comment]
/attempt #9091

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;32 ZIO bounties <br/> + 2 bounties from 1 project | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center">﹟9093</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0mle6k0001kjy03rerwnnwe/cancel-attempt) |
