### ISSUE TITLE
Add `ignore` method

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#910]
For any data type that has a notion of failure and mapping, we should add an `ignore` method, e.g.:

```scala
trait ZIO[R, E, A] {
   def ignore: ZIO[R, Nothing, Unit] = self.either.unit
}
```

The meaning of ignore is: _ignore any failures and give me back unit_. It's equivalent to "either" followed by "unit". It can be defined, for sure, on `ZIO` and `STM`, and possibly stream abstractions.

**Comment by NeQuissimus** [comment]
Yes!

**Comment by ghostdogpr** [comment]
Done in #1083
