### ISSUE TITLE
Expose the size of the queu waiting for a semaphore

### ISSUE THREAD

**Issue by tmccombs** [zio/zio#9102]
Please add a method to `Semaphore` that allows observing how many tasks are currently in the queue waiting for available permits. This is useful for monitoring if a semaphore is heavily contended.

This could be implemented with something like:

```scala

def queueSize(implicit trace: Trace): UIO[Long] = ref.get.map {
  case Left(queue) => queue.size
  case Right(_) => 0L
}
```

**Comment by caeus** [comment]
https://github.com/zio/zio/pull/9122
