### ISSUE TITLE
Add a new module to read application parameters from command line

### ISSUE THREAD

**Issue by geazi-anc** [zio/zio#9118]
Passing parameters via command line to an application is a convenient way to turn it highly flexible and configurable, without using environment variables or system properties. It is ideal for data pipelines, for instance, which are run on a serverless tool or on an environment where defining these variables is not possible.

However, ZIO currently lacks an easy way to achieve this. A solution, therefore, would be to add a new module to read these parameters from the command line and parse them into a key-value structure. This proposed functionality is inspired by Apache Flink's [Parameter Tool](https://nightlies.apache.org/flink/flink-docs-stable/api/java/org/apache/flink/api/java/utils/ParameterTool.html).

Here's how it would work:

```scala
// using scala 3 syntax
import zio.*

object MyApp extends ZIOAppDefault:
  val params: ZIOAppParam = ZIOAppParam.fromArgs(ZIOAppArgs.getArgs())
  val run = for
    host <- params.get("host")
    port <- params.get("port")
    _ <- Console.printLine(s"Application started with host = $host and port = $port")
  yield ()
```

You can run the application with the --host and --port parameters using the Scala CLI:

```Bash
$ scala-cli MyApp.scala -- --host example.com --port 8080
Compiling project (Scala 3.4.2, JVM (21)) - Scala compiler output
Compiled project (Scala 3.4.2, JVM (21)) - Scala compiler output
Application started with host = example.com and port = 8080
```

What do you think about this proposed functionality? I'd like to implement it in ZIO core. This would be my first contribution to an open-source project.

Thanks in advance!

**Comment by ghostdogpr** [comment]
Are you aware of https://zio.dev/reference/core/zioapp/#accessing-command-line-arguments ?

It returns a Chunk of String but then you can use zio-config `ConfigSource.fromCommandLineArgs` to parse it

**Comment by kyri-petrou** [comment]
> but then you can use zio-config  `ConfigSource.fromCommandLineArgs` to parse it

Interestingly, this method isn't available anymore in `zio-config` v4.x (it was in 3.x). I wonder why was it removed 🤔. Perhaps it's been pushed to https://github.com/zio/zio-cli instead?

**Comment by ghostdogpr** [comment]
Whoops, we're using it in Caliban.

**Comment by geazi-anc** [comment]
> Are you aware of https://zio.dev/reference/core/zioapp/#accessing-command-line-arguments ?
> 
> It returns a Chunk of String but then you can use zio-config `ConfigSource.fromCommandLineArgs` to parse it

Thank you so much for your answer. In deed, I wasn't aware of this functionality in zio-config. I'll search more about, or use zio-cli to have the same result.

Thank you again!
