### ISSUE TITLE
Introduce super polymorphic version of Ref called 'ZRef'

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#913]
We need a version of `Ref` that is highly polymorphic called `ZRef`. The existing `Ref` can be implemented atop this, as a type alias, and pseudo-companion object.

The new `ZRef` will have the following type parameters:

```scala
abstract class ZRef[-A, +EA, +B, +EB] {
  final def get: IO[EB, B] = ???
  final def set(a: A): IO[EA, Unit] = ???
  final def setAsync(a: A): IO[EA, Unit] = ???
  final def update[E, A1 <: A](f: A => A1)(implicit ev1: EA <:< E, ev2: EB <:< E): IO[E, A1] = ???
  final def modify[B, A1 <: A](f: A => (B, A1))(implicit ev1: EA <:< E, ev2: EB <:< E): IO[E,B] = ???
  // etc.
}
```

etc. I don't know if this type encoding will work for errors, it remains to be investigated.

The old `Ref` will be implemented as:

```scala
type Ref[A] = ZRef[A, Nothing, A, Nothing]
val Ref = ZRef
```

to avoid breaking any code and to provide a simpler version for common cases.

Not (necessarily) part of this ticket, this polymorphic version will allow introducing `map`, `const`, `unit`, `mapError`, `zip`, `filter`, and numerous other methods.

Most excitingly, there is a connection between this formulation of `ZRef` and optics. 😱 💃

**Comment by iravid** [comment]
<3 "ZIO - Profunctors for Scala" <3

**Comment by regiskuckaertz** [comment]
I'll pick this one 💪

**Comment by regiskuckaertz** [comment]
I'm struggling to write `contramap` because of the `update*` and `modify*` methods. Variance aside, it seems impossible to provide an `A => A` when you have a `C => C` and a `C => A`:
```scala
def contramap[C](g: C => A) = new ZRef[EA, EB, C, B] {
  def update(f: C => C): IO[EB, B] = // cannot call self.update: (A => A) => IO[EB, B]
}
```
It suggest to me the update mechanism needs to be abstract somehow. `ZSink` comes close with
```scala
  final def update(state: Step[State, Nothing]): ZSink[R, E, A0, A, B] =
    new ZSink[R, E, A0, A, B] {
      type State = self.State
      val initial: ZIO[R, E, Step[State, Nothing]]             = IO.succeed(state)
      def step(state: State, a: A): ZIO[R, E, Step[State, A0]] = self.step(state, a)
      def extract(state: State): ZIO[R, E, B]                  = self.extract(state)
    }
```
I assume we can employ the same kind of trick, with the goal to keep being able to write simple expressions like `Ref.make(0).update(_ + 1)`. Before putting more time into this, do you agree? If you have any advice on how to model that, by all means 😇

**Comment by iravid** [comment]
Isn't it possible for `update` to be `g . f $ state`?

**Comment by iravid** [comment]
ah yeah ok. you need a `type State = A`, is that what you're asking?

**Comment by regiskuckaertz** [comment]
> Isn't it possible for update to be g . f $ state?

`g . f :: c -> a`, not `a -> a` 😞 

> ah yeah ok. you need a type State = A, is that what you're asking?

Yes. If I understand correctly, this is why you came up with `Step[]` and `State`, right?

**Comment by iravid** [comment]
Oh but that still won't solve the issue if you need to return `IO[E, C]`. Update has to return `IO[E, B]` no?

**Comment by iravid** [comment]
The current version of `update` returns the result of applying `f` to the internal state. So I don't see why this shouldn't return a `B` (as `get` does)

**Comment by regiskuckaertz** [comment]
yeah that's right! so in essence, `ZRef` is a black box for a mutable variable:
```
     +---------+
A >--|  State  |--> B
     +---------+
```

In the case of `Ref`, `State = A`, it makes sense that `update :: (a -> a) -> b`

```
     +---------+
A >--|    A    |--> B
     +---------+
```

Does it mean that we can change `ZRef` to

```
abstract class ZRef[EA, EB, A, B] {
  type State

  def update(f: State => State): IO[EB, B]
  def modify[X](f: State => (State, X)): IO[EB, X]
}
```

**Comment by iravid** [comment]
Hmm I don’t think those signatures are useful if you forget what State is. But I had to leave my computer, will  be back later today

**Comment by regiskuckaertz** [comment]
What if there's an additional abstract method
```scala
def extract(state: State): IO[EB, B]
```
same as in `ZSink`? Sure thing, thanks for your help so far, it's helpful to have someone to brainstorm with :-)

**Comment by jdegoes** [comment]
I think both `update` and `modify` have to be done on a syntax class inside companion of `ZRef`, which will assume that `A =:= B`.

I think this will be the simplest and leas confusing encoding.

**Comment by regiskuckaertz** [comment]
oh I see what you mean, so they're not in `ZRef` by default. works for me 👍

**Comment by iravid** [comment]
Ah that makes sense re modify and update.

**Comment by dsebban** [comment]
Hey can I pick this one up? @regiskuckaertz I would totally understand if you want to give it another chance , would love to give a try though, thnks

**Comment by regiskuckaertz** [comment]
@dsebban Hello 👋 Thanks a lot for asking, please go ahead as I won't have time to focus on zio for a while 😞

**Comment by jdegoes** [comment]
@dsebban I would do a generic update / modify:

e.g.:

```scala
def updateUnify[C](ea: C => A, eb: B => C)(f: C => C): ZRef[EA, EB, C, C] = ???
```

then add syntax for ordinary `update` in terms of this one, in the case that `A =:= B`:

```scala
object ZRef {
  implicit class ZRefUnifiedValueSyntax[EA, EB, A](ref: ZRef[EA, EB, A, A]) {
    def update(f: A => A): ZRef[EA, EB, A, A] = ???
  }
```

Then for performance reasons, I'd take it a step deeper, and add private `unsafeUpdate` / `unsafeModify` functions, which assumes (_cast_) `A =:= B`, and are called in the syntax classes.

**Comment by dsebban** [comment]
Thanks, I will try your suggestion next, I left some comments on my commit where I am stuck

**Comment by jdegoes** [comment]
@dsebban 

OK, so here's what we need to do:

 - Make `unsafe` functions return `Option` of their result types.
 - If a ref is created through `ZRef.make`, then return the unsafe functions wrapped in `Some`
 - In all other cases, do not use the unsafe functions, rather, delegate to type safe ways of accomplishing the same functionality.

This means that all methods will have "safe" implementations. It's only as a shortcut that refs created _but not transformed_ will end up getting access to the unsafe methods.

Does this change make sense? Unlike our previous sketch, this one should be type sound.
