### ISSUE TITLE
ZPool leaks resources when acquisition is interrupted

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#9152]
I've been debugging a [CI failure in ZIO HTTP](https://github.com/zio/zio-http/actions/runs/10610450982/job/29407956295#step:9:4911) involving a flaky test, and I managed to trace this issue down to ZPool not releasing resources on scoped workflows when the resource acquisition is interrupted. Reproducer:

```scala
import zio.*

object Foo extends ZIOAppDefault {
  val counter = Ref.unsafe.make(0)(Unsafe)

  val incCounter = ZIO.acquireRelease(counter.update(_ + 1))(_ => counter.update(_ - 1))

  def run = ZIO.scoped(
    for {
      pool <- ZPool.make(incCounter *> ZIO.sleep(2.seconds), 0 to 100, 10.seconds)
      f    <- ZIO.scoped(pool.get).fork
      _    <- ZIO.sleep(1.second)
      _    <- f.interrupt
      _    <- f.await.ignore
    } yield ()
  ) *> counter.get.debug("count")
}
```

I expect `count: 0` to be printed in the console, however `count: 1` is printed instead.

Note that this is causing connections to be leaked in ZIO HTTP's Client in cases that the request is interrupted while we're acquiring a connection to the server.

cc @987Nabil

EDIT: This seems worse than I thought; if the acquisition fails, then the resource does not even become part of the pool, which means it'll stay alive totally unmanaged

**Comment by jdegoes** [comment]
@kyri-petrou Added a bounty!
