### ISSUE TITLE
Could not resolve view on Ident(map)

### ISSUE THREAD

**Issue by felix-hedenstrom** [zio/zio#9153]
When using a `Map` with `.view` in a `assertTrue` in scala 3 you get a `Could not resolve view` error. This error is not present in scala 2. 

It happens in the case of 
```
val map = Map(1 -> 2)
assertTrue(map.view.mapValues(_ + 1).toMap == Map(1 -> 2))
```
and can easily be avoided by rewriting it as 
```
val map = Map(1 -> 2).view.mapValues(_ + 1).toMap
assertTrue(map == Map(1 -> 2))
```

https://scastie.scala-lang.org/XdewBxIPRdSF1Y0ELkv7Hg

**Comment by jdegoes** [comment]
/bounty $125 for fix and test demonstrating fix.

**Comment by varshith257** [comment]
/attempt #9153

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 7 bounties from 4 projects | <div align="center">TypeScript, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0minz6x0002jp03hoq4gvin/cancel-attempt) |

**Comment by dheerajsingh89** [comment]
/attempt #9153

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/itsdheerajdp) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @itsdheerajdp | 4 bounties from 2 projects | <div align="center">HTML, JavaScript, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0minz6x0002jp03hoq4gvin/cancel-attempt) |

**Comment by varshith257** [comment]
@itsdheerajdp FYI, I am on a way to completing it

**Comment by varshith257** [comment]
@jdegoes This issue is dependent on this. I think first we need to support Scala-3 compatibility for SmartAssertionMacros. Opened a separate ticket to track it

- https://github.com/zio/zio/issues/9178
