### ISSUE TITLE
Tracing: think of a replacement for ZIOFn

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#916]
Some starting points in thread: https://github.com/scalaz/scalaz-zio/pull/849#discussion_r287895254

`ZIOFn` is both a maintainability and a performance concern, however a different approach that can support the same patterns for passing user lambdas down to the tracer is hard to come by... Some specific hard cases - `mapError`, `bracket`

Some starting work on @jdegoes's 2nd suggestion has been started [here](https://github.com/7mind/scalaz-zio/compare/feature/zio-stacktraces...feature/remove-ziofn), however no performance gain has yet been observed

**Comment by adamgfraser** [comment]
I think this has been superseded by the new approach to execution tracing in ZIO 2.
