### ISSUE TITLE
Website: Upgrade Docusaurus to the Latest Version (3.x)

### ISSUE THREAD

**Issue by khajavi** [zio/zio#9162]
The zio.dev website is based on docusaurus version 2.2.0. We need to update the site with the latest stable version.

**Comment by neo773** [comment]
/attempt #9162

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 134 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0mlda0k000kky03e5rd7cd2/cancel-attempt) |

**Comment by emmz3230** [comment]
is this bounty still available
