### ISSUE TITLE
Scope is not propagated from layer to specs in test suites.

### ISSUE THREAD

**Issue by fredDJSonos** [zio/zio#9175]
For various historical reasons (migration from a ZIO1 project), I need all my tests to run with `ClockLive` and `RandomLive`.  This is surprisingly hard to do in ZIO2.  Ideally, a layer like this:

```scala
  def realClock: ULayer[Unit] = ZLayer.scoped {
    for {
      _ <- ZIO.withClockScoped(Clock.ClockLive)
      _ <- ZIO.withRandomScoped(RandomLive)
    } yield ()
  }
```
Should be enough to override the default choice of the test environment.  Let’s put that in practice:

```scala
object RealClockSpec extends ZIOSpec[Unit] {
  val spec = suite("full")(single, singleWithoutProvide, aSuite) @@ sequential

  // this DOES work with a single test!
  def single =
    oneTest("single").provideLayerShared(realClock)

  // This does not work with a suite
  def aSuite = suite("foo")(
    oneTest("1"),
    oneTest("2")
  ).provideSomeLayerShared(realClock) @@ sequential

  // this does not work (scope not inherited from the bootstrap)
  def singleWithoutProvide = oneTest("singleWithoutProvide")

  // the scope of the layer does not propagate to the specs
  override val bootstrap: ULayer[Unit] = realClock

  def oneTest(s: String): Spec[Any, Nothing] = test(s) {
    ZIO.scoped {
      for {
        // TestRandom.deterministic produces  -1295463240
        x   <- Random.nextInt
        now <- Clock.localDateTime 
        // now will be 1970 under the TestClock
        _   <- ZIO.logInfo(s"id is $x $now")
      } yield assertTrue(x != -1295463240)
    }
  }

  def realClock: ULayer[Unit] = ZLayer.scoped {
    for {
      _ <- ZIO.withClockScoped(Clock.ClockLive)
      _ <- ZIO.withRandomScoped(RandomLive)
    } yield ()
  }
}
```

It’s a bit hard to swallow that `provideLayerShared` has a different semantic when it applies to a suite or to a single test.  So we have at least one  bug, don’t we ?  

The environment computed by layers is correctly propagated, of course.  Otherwise the bug would be much more visible.   But the `Scope` defined by the `realClock` layer does not appear  to propagate properly, except in the trivial `SpecCase::TestCase`

The code [here](https://github.com/zio/zio/blob/e41d9c5fd46d724ec1b435d10d68903a74932acb/test/shared/src/main/scala/zio/test/Spec.scala#L343) looks ok.  We observe the environment computed once, and provided to the list of specs.  There is an attempt to define a common Scope for all the specs. So maybe the issue is in the runner ?

## Related issue
There is a slightly related behaviour that presumably has the same root cause.  I don’t know if it deserves a different ticket.  Maybe it’s even consider a correct behavior, after all.

We certainly have some anti-pattern in our test suites.  Among the things we do, is having sequential dependant specs like
```scala
   val spec = suite(
      writeSomethingToDB(),
      writeSomethingElseToDB(),
      testSomethingInDB()
    ). provideSomeLayerShared(dbLayer) @@ sequential
```
I don’t know if it’s good or bad practice, but we have tons of tests like that.  The `TestRandom.deterministic` state is reset before each spec and that does not feel right, does it? The consequence is that  we generate the same ID for the DB writes and cause spurious insertion failures.  
This is not a surprising behaviour given that the state of the `TestRandom.deterministic` is kept in the current scope and the scope is lost, as previously observed.

In fact, I could live with `TestRandom.deterministic` if it would not reset between individual specs.  But I can understand that this is the expected behavior.

**Comment by kyri-petrou** [comment]
Hi @fredDJSonos, have you tried using the `withLiveRandom` and `withLiveClock` aspects? You can have them applied globally (to all tests in the spec) as:

```scala
import zio.Chunk
import zio.test.*
import zio.test.TestAspect.*

object FooSpec extends ZIOSpecDefault {

  override def aspects: Chunk[TestAspectAtLeastR[TestEnvironment]] =
    super.aspects ++ Chunk(withLiveClock, withLiveRandom)

  override def spec = ???
}
```

If you want to avoid defining the `override def aspects = ???` in every file, you could also add that in an abstract class and have your suites extend it

**Comment by fredDJSonos** [comment]
Thanks a lot, this solves my problem.  At least I have a workaround.  I should have read the doc better.  

But this scope issue is real bug, right ?

**Comment by fredDJSonos** [comment]
Looking at the machinery of the `TestAspect`, I realize that the only difference with my code is:
  * `TestAspect.withLiveClock` does a `spec.provideSomeLayer(realClock)`
  *  I’m doing `spec.provideLayerShared(realClock)`

This is the _Shared_ part that matters here.  This is with the `*Shared` variant that the problem happens.

**Comment by kyri-petrou** [comment]
Hmm this might be a legitimate bug, I'll need to look deeper into it to see what might be causing it

**Comment by jdegoes** [comment]
/bounty $250 to fix the scope bug.

**Comment by clarzte** [comment]
/attempt #9175

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm392libn0002l703spawswmw/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
