### ISSUE TITLE
 Add Scala 3 Compatibility for `SmartAssertionMacros`  in ZIO Test

### ISSUE THREAD

**Issue by varshith257** [zio/zio#9178]
Currently, SmartAssertionMacros are built using Scala 2 macro system, which isn't directly compatible with Scala 3. Scala 3 introduces a new macro system that relies on `inline` and `quoted` constructs, replacing the previous `blackbox` macros.  We need to rewrite SmartAssertionMacros using Scala 3's macro API to support both versions effectively.

References:
https://docs.scala-lang.org/scala3/guides/macros/
https://virtuslab.com/blog/technology/metaprogramming-in-scala-2-3/
https://docs.scala-lang.org/scala3/guides/migration/tutorial-macro-mixing.html

**Comment by kyri-petrou** [comment]
The SmartAssertionMacros are already implemented for Scala 3 (see [here](https://github.com/zio/zio/blob/series/2.x/test/shared/src/main/scala-3/zio/test/Macros.scala)). Closing this issue, feel free to reopen if you think that there is something specific missing
