### ISSUE TITLE
Consider deprecating `ZIO#onDone`

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#9191]
I was debugging a nasty bug at $WORK, and to my surprise I found out that `ZIO#onDone` forks the effect and "discards" the fiber, running the success/error callbacks on exit (see [here](https://github.com/zio/zio/blob/cf4a2fc691247a5a60efcd48de9efb44945ae496/core/shared/src/main/scala/zio/ZIO.scala#L1046-L1060))

I think this behaviour is quite dangerous because its behaviour is _very_ different than other `onX` methods (e.g., `onExit`). As a user (or in my case, when I reviewed the PR that caused the bug), I won't know that the method forks the effect and doesn't await on its completion unless I take a look at the source code.

In order to guard against incorrect usage of this method, we should consider deprecating it (`onDoneCause` as well). If we find out that users do use this method in the correct way and need it, we can introduce it under a more accurate name (`forkDaemonExit` or something)

**Comment by jdegoes** [comment]
I think it was designed to copy Future semantics, and maybe in that age, it made sense. In the age of effect systems, less so.

**Comment by jdegoes** [comment]
/bounty $100 for making `onDone` / `onDoneCause` the same as other `onX` methods (i.e. NOT fork).

Why?

We can argue existing bug is a behavior and document it in release notes.

**Comment by asr2003** [comment]
/attempt #9191

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/asr2003) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @asr2003 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 5 bounties from 3 projects | <div align="center">Rust, Scala, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm392d1b3002tmh03xoo1tmix/cancel-attempt) |
