### ISSUE TITLE
Inconsistency Between the Input Signature of `ZIO#catchAllDefect` and `ZIO#tapDefect` Methods

### ISSUE THREAD

**Issue by khajavi** [zio/zio#9194]
I'm surprised that there is no "ZIO#catchAllDefect*" variant, (such as `ZIO#catchAllDefectCause`?!), that would give me access to the cause of the defect. However, when I want to use "ZIO#tapDefect," I can access the cause of the defect. This shows inconsistency between APIs: one gives me a `Throwable` and the other gives `Cause`. Any thoughts on this?

P.S. I found we have `ZIO#tapError` and `ZIO#tapErrorCause`, but not the same for `ZIO#tapDefect`.

**Comment by jdegoes** [comment]
There is no cause of defect. Rather, if you want the full cause of the failure, it will include any defects. So you would just use `catchAllCause` and look for the defect in there.

We could have `tapDefect`, that makes sense, but it should only give you `Throwable`, not cause. If you want the full cause, you would use `tapErrorCause`.

Make sense? Please open a new ticket if the goal is to add `tapDefect`.
