### ISSUE TITLE
STM transaction retry loop (regression in 2.1.8)

### ISSUE THREAD

**Issue by dilation** [zio/zio#9215]
### Steps to reproduce:

```
git clone https://github.com/nokia/stm-benchmark.git
cd stm-benchmark
```

#### With version 2.1.7:

```
git checkout b25cc70  # uses 2.1.7
sbt zstm/test
```

Finishes in about 2-3 seconds, and after some debugging output, it prints:

```
...
com.nokia.stmbenchmark.zstm.ZstmSolverSpec:
  + minimal.txt 0.756s
  + testBoard.txt 0.962s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 3 s, completed Sep 23, 2024, 4:24:49 PM
```

#### With version 2.1.8:

```
git checkout 97d9bed  # uses 2.1.8
sbt zstm/test
```

It doesn't complete, and after some successful transactions, it continually seems to retry the same 2 transactions:

```
...
Trying to commit Route(Point(28,26),Point(64,29))
Trying to commit Route(Point(38,66),Point(47,36))
Trying to commit Route(Point(28,26),Point(64,29))
Trying to commit Route(Point(38,66),Point(47,36))
...
```

### Additional information:

I also tried it with version 2.1.9, it has the same problem.

Based on some debugging, it seems to me, that 2 threads are taking turns continuously retrying the same 2 transactions, which never seem to be able to commit. (I've let it run for more than a few minutes without the debug `println`s, and it spins the CPU, but doesn't seem to finish.)

**Comment by kyri-petrou** [comment]
Thanks for reporting this issue @dilation. I'll take a look, I have a feeling I know what might be causing it
