### ISSUE TITLE
ZIO Test Should Report a Failed Test With the Most Accurate Label

### ISSUE THREAD

**Issue by khajavi** [zio/zio#9227]
If I have a test like this: 

```scala
object LabelingAssertions extends ZIOSpecDefault {
  def spec =
    test("when an inner assertion fails") {
      assert(Some(0)) {
        isSome(
          equalTo(42).label("equality check")
        ).label("structural check")
      }.label("assertion label")
    }
}
```
It reports like this:
![image](https://github.com/user-attachments/assets/b2ad5e67-1ff4-4eff-836d-17d46bc6e71e)

In the above test, when the "equalTo" assertion fails, I expect its corresponding label, the "equality check" will appear on the test report, not the outer label "assertion label"

**Comment by varshith257** [comment]
/attempt #9227

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;6 ZIO bounties <br/> + 15 bounties from 9 projects | <div align="center">Rust, Scala, <br />Go & more</div> | <div align="center">﹟9352</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm42xa6nl0004kz030yjk8nii/cancel-attempt) |
