### ISSUE TITLE
ZStream.fromHubScoped shutdown question

### ISSUE THREAD

**Issue by tim-smart** [zio/zio#9236]
Looking at the implementation of .fromHubScoped, I am wondering why `fromQueueWithShutdown` is used? I thought the Scope is responsible for shutting down the queue?

```scala
  def fromHubScoped[A](
    hub: => Hub[A],
    maxChunkSize: => Int = DefaultChunkSize
  )(implicit trace: Trace): ZIO[Scope, Nothing, ZStream[Any, Nothing, A]] =
    ZIO.suspendSucceed(hub.subscribe.map(queue => fromQueueWithShutdown(queue, maxChunkSize)))
```

**Comment by ghostdogpr** [comment]
The `Scope` might have a lifecycle that is different from the stream, so using `fromQueueWithShutdown` ensures the queue is shutdown when the stream ends, regardless of the scope. They're both controlling the queue shutdown, whichever happens first.

**Comment by tim-smart** [comment]
But the stream could be consumed more than once?

**Comment by ghostdogpr** [comment]
No just once, since it shuts down the queue, and there is only one queue created by `subscribe`.

**Comment by kyri-petrou** [comment]
Going to close this issue, feel free to reopen if you need more clarification (or alternatively, you can always ask on the ZIO Discord channel 🙂)
