### ISSUE TITLE
No way of deterministically testing timeouts

### ISSUE THREAD

**Issue by freskog** [zio/zio#925]
At the moment there doesn't seem to be any way of deterministically testing timeouts in ZIO.

My goto strategy for other similar problems has been to use the Test* implementations made available via scalaz-zio-testkit. Unfortunately, the way that the TestClock is implemented is at odds with testing timeouts.

If I understand it correctly a timeout in ZIO is just implemented as two racing fibers, one that performs the desired action and the other one is waits for a the duration of the timeout. The TestClock implementation doesn't actually sleep, but rather just records the fact that a sleep was performed, and thus it's not unlikely that the timeout fiber is the winner no matter what it's delay is set to.

I can't think of any better workarounds than to use the Clock.Live implementation for those tests that require testing timeouts at the moment, but this comes with a world of pain when trying to set a reasonable amount of time to wait...

**Comment by jdegoes** [comment]
I think this is closed by #1360. @freskog, can you confirm? /cc @adamgfraser

**Comment by freskog** [comment]
@jdegoes, yes that looks awesome!
