### ISSUE TITLE
[ZIO 1.x] Unused implicit tag in ZLayer concat (++) method

### ISSUE THREAD

**Issue by joroKr21** [zio/zio#9262]
```scala
final def ++[E1 >: E, RIn2, ROut1 >: ROut, ROut2](
  that: ZLayer[RIn2, E1, ROut2]
)(implicit ev: Has.Union[ROut1, ROut2], tag: Tag[ROut2]): ZLayer[RIn with RIn2, E1, ROut1 with ROut2] =
  self.zipWithPar(that)(ev.union)

implicit def HasHasUnion[R <: Has[_], R1 <: Has[_]: Tag]: Union[R, R1] =
  new Union[R, R1] {
    def union(r: R, r1: R1): R with R1 =
      r.union[R1](r1)
  }
```

That implicit `Tag` in `++` is not used and it can generate a lot of garbage esp. when using `zio-magic`.

**Comment by asr2003** [comment]
/attempt #9262

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/asr2003) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @asr2003 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 5 bounties from 3 projects | <div align="center">Rust, Go, <br />Scala & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm38x3e600004mk03zy4gc2uh/cancel-attempt) |

**Comment by kyri-petrou** [comment]
Fixed by https://github.com/zio/zio/pull/9297
