### ISSUE TITLE
New microsite does not deploy as part of release

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#927]
Microsite is built now using Docusaurus, the task appears to complete in Travis, but I did not investigate beyond that.

**Comment by jdegoes** [comment]
<https://travis-ci.org/scalaz/scalaz-zio/jobs/539881502>

**Comment by ghostdogpr** [comment]
The error is `Missing git user. Did you forget to export the 'GIT_USER' environment variable?`
According to the documentation here https://docusaurus.io/docs/en/publishing.html#using-travis-ci, we need to add `GIT_USER="..." ` in .travis.yml.
There's also `echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc` that we don't have but I'm not sure it's necessary. @NeQuissimus any idea on this?

**Comment by NeQuissimus** [comment]
Pretty sure that netrc line is the only thing missing. The yarn invokation probably looks for this file.

**Comment by ghostdogpr** [comment]
@NeQuissimus so we need a token from a user with write permissions (https://docusaurus.io/docs/en/publishing.html#using-travis-ci). Do you want to do it, since the rest uses your account? Otherwise I can try it.

@jdegoes since the RC5 is already released, I could build locally and make a PR with the new website for manually merging into the gh-pages branch. Unless there is another way that doesn't involve making a new RC?

**Comment by ghostdogpr** [comment]
OK, ignore my previous message since we're going to use Netlify instead. Here are the instructions: https://docusaurus.io/docs/en/publishing#hosting-on-netlify

**Comment by NeQuissimus** [comment]
I made a Circle CI context called "Website", which gives environment variables
- `GH_TOKEN`
- `GH_NAME`
- `GH_EMAIL`

Can you publish the RC5 website by hand for now?

I think I'll use my time at LambdaConf to tackle the migration of the build onto Circle CI.

**Comment by ghostdogpr** [comment]
@NeQuissimus Yep, I'm trying to upload it manually + configuring netlify to point to the gh-pages branch, and I'll let you fix the build for future releases.

**Comment by ghostdogpr** [comment]
Done: https://zio.dev/ (it's the RC5)

**Comment by jdegoes** [comment]
@ghostdogpr Superb. Thank you! 🙏

**Comment by softinio** [comment]
Working on this as part of #931. 

@NeQuissimus have you set `GH_NAME` to GitHub username I assume? Ty

**Comment by NeQuissimus** [comment]
I have indeed
