### ISSUE TITLE
Add operator to ZLayer which returns an effect that produces application and allows running an effect

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#9272]
Considering to add a new function `runWith` (name TBD) that is on `ZLayer`, and which allows you to specify all of the dependencies of the layer. The layer must succeed with `Unit` and represents the main function of the application.

This operator would allow a style of application wireup that is layer-focused:

```scala
val run = 
  TodoApp.layer.runWith(TodoRepo.testLayer, TodoConfig.defaultLayer, EmailService.testLayer)
```

where:

```scala
TodoApp.layer: ZLayer[TodoRepo & TodoConfig & EmailService, Nothing, Unit]
```

**Comment by ekhov** [comment]
/attempt #9272

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ekhov) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ekhov | 3 ZIO bounties | <div align="center">Python, Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm2yz76jc0002l20381aizzff/cancel-attempt) |

**Comment by varshith257** [comment]
/attempt #9272

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;5 ZIO bounties <br/> + 13 bounties from 9 projects | <div align="center">Rust, Go, <br />Scala & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm2yz76jc0002l20381aizzff/cancel-attempt) |

**Comment by nehaaprasad** [comment]
/attempt #9272


I think, Use `ZLayer.make[R](layers: _*)` to safely combine the provided layers and ensure they match the required environment type. Then, provide the composed layer to the application using `ZIO.unit.provideLayer(composedLayer >>> layer)`.


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm2yz76jc0002l20381aizzff/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
