### ISSUE TITLE
Use a Virtual Thread-based Executor (when available) for the Default Blocking Executor

### ISSUE THREAD

**Issue by AugustNagro** [zio/zio#9276]
The current blocking executor uses a ThreadPoolExecutor.

Using a virtual thread-based executor can greatly reduce the number of platform threads created.

One example of this is with JDBC. Assume you're using Hikari CP with a DB connection pool size of 10. If your ZIO app attempts to run 100 concurrent queries, 100 threads will be created. 90 of them will be waiting for `DataSource::getConnection` to return and thus wasting resources.

By using virtual threads, we can let Java manage this blocking automatically on a fixed number of platform threads with Executors.newVirtualThreadPerTaskExecutor()

https://github.com/zio/zio/blob/series/2.x/core/jvm/src/main/scala/zio/internal/LoomSupport.scala

https://github.com/zio/zio/blob/series/2.x/core/jvm-native/src/main/scala/zio/internal/Blocking.scala

https://github.com/zio/zio-jdbc/issues/24

**Comment by kyri-petrou** [comment]
There are a few "gotchas" with virtual threads at the moment which makes me a bit reluctant to use them as a default for blocking operations.

The most prominent one is that the use of `synchronized` blocks causes pinning of the carrier thread, effectively hard-blocking the main thread. AFAIK there is currently work being done to avoid pinning of the carrier thread in `synchronized` blocks, but until then we can't really consider it as the default implementation for the blocking threadpool.

**Comment by AugustNagro** [comment]
Hopefully the pinning fix lands in JDK 24.

https://openjdk.org/jeps/491

The most popular Java libraries have migrated to juc.locks at this point.

https://jdbc.postgresql.org/changelogs/2023-03-17-42.6.0-release/

**Comment by kyri-petrou** [comment]
@AugustNagro I agree that a lot of Java libraries have migrated to locks to make them Loom-friendlier, but I think there are more issues / edge-cases besides `synchronized` blocks. e.g., in the past I had issues with using GraalVM's polyglot API with Virtual Threads as they were not supported yet. In either way, I'm reluctant on making changes of such magnitude to be the new default behaviour as it's almost guaranteed to affect some users in a negative way.

Just trying to understand your suggestion / use-case a little bit better, what is the reason that you would like ZIO to use Virtual Threads for blocking effects by default? Is it any of the reasons below or do you have another reason in mind?
1. At the moment there is too much boilerplate involved in changing the blocking executor to use virtual threads
2. You want to use the same loom-based executor instance for both the default and blocking operations to minimize context switching
3. You have no control over the JDK that the application is run on, and want to use virtual threads for blocking ops whenever they're available

**Comment by jdegoes** [comment]
I think we can make it easy to use loom threads for blocking executor, but that we should not tamper with the default right now. 

Example of how to make it easy: have a `Runtime.<xyz>` layer to make this change, so it's a 1-liner; and document this in a Loom-only section on the website.

Perhaps we can refocus the ticket on this goal, instead??

**Comment by AugustNagro** [comment]
> Perhaps we can refocus the ticket on this goal, instead??

Sounds good!

**Comment by digy** [comment]
@jdegoes Can't find nothing in the docs that could be called Loom-only section. Maybe you can point me to the section ?

**Comment by khajavi** [comment]
@digy We don't have this section yet!

**Comment by digy** [comment]
/attempt #9276

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm425qjmo0004l1037cwu6pe9/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ghostdogpr** [comment]
Closed by https://github.com/zio/zio/pull/9355
