### ISSUE TITLE
Calling `System.env` and related methods do not work on Scala.js

### ISSUE THREAD

**Issue by mhriemers** [zio/zio#9279]
When using ZIO in a Scala.js project, the `zio.System.env` method and related environment variable access functions do not retrieve environment variables as expected. This issue occurs even when environment variables are correctly set in the Node.js environment using `jsEnv` configurations in `build.sbt`.

### Steps to Reproduce:

1. **Set Up a Scala.js Project with ZIO Dependencies**

   Include ZIO in your `build.sbt`:

   ```scala
   libraryDependencies += "dev.zio" %%% "zio" % "2.1.11"
   ```

2. **Configure `jsEnv` to Pass Environment Variables to Node.js**

   ```scala
   jsEnv := new NodeJSEnv(
     NodeJSEnv.Config().withEnv(Map("FOO" -> "hello", "BAR" -> "world"))
   )
   ```

3. **Attempt to Access Environment Variables Using `zio.System.env`**

   ```scala
   package com.example

   import zio.{ZIO, ZLayer, System}

   case class Config(
     foo: String,
     bar: String
   )

   object Config {
     val live: ZLayer[Any, Exception, Config] = ZLayer(
       for {
         foo <- System.env("FOO").someOrFail(new Exception("FOO not set"))
         bar <- System.env("BAR").someOrFail(new Exception("BAR not set"))
       } yield Config(foo, bar)
     )
   }
   ```

4. **Run the Scala.js Application**

   Execute the application and observe the behavior.

**Expected Behavior:**

- The application should retrieve the `FOO` and `BAR` environment variables.
- No exceptions related to missing environment variables should be thrown.

**Actual Behavior:**

- The application fails to retrieve the environment variables.
- Exceptions are thrown indicating that `FOO` and `BAR` are not set.

### Analysis:

The issue appears because `zio.System.env` relies on the underlying platform's standard library to access environment variables. In Scala.js, `System.getenv` is not available due to JavaScript limitations. Therefore, `zio.System.env` does not function correctly in a Scala.js environment.

**Suggested Solution:**

To address this issue, it would be beneficial for ZIO to provide a Scala.js-specific implementation of `zio.System`, similar to how `ClockPlatformSpecific` is used to handle platform-specific clock functionalities. By creating a `SystemPlatformSpecific` trait for Scala.js, ZIO can directly interact with the Node.js `process.env` object to access environment variables when running under Node.js.

**Proposed Implementation:**

1. **Create a `SystemPlatformSpecific` Trait for Scala.js**

   In the `zio` package, create a new file `SystemPlatformSpecific.scala` specifically for Scala.js:

   ```scala
   // zio/SystemPlatformSpecific.scala (Scala.js version)

   package zio

   import scala.scalajs.js
   import scala.scalajs.js.Dynamic.global

   private[zio] trait SystemPlatformSpecific { self: System.type =>

     def env(variable: => String)(implicit trace: Trace): IO[SecurityException, Option[String]] =
       ZIO.attempt {
         val env = global.process.env.asInstanceOf[js.Dictionary[String]]
         env.get(variable)
       }.refineToOrDie[SecurityException]

     // Implement other methods as needed, such as system properties or line separators
   }
   ```

   This trait provides a Scala.js-specific implementation of `env` by accessing `global.process.env`, which is available when running under Node.js.

2. **Modify the `System` Object to Extend `SystemPlatformSpecific`**

   Ensure that the `System` object extends `SystemPlatformSpecific`, so that the platform-specific implementation is included:

   ```scala
   // zio/System.scala

   package zio

   object System extends SystemPlatformSpecific {
     // Existing code...
   }
   ```

3. **Handle Non-Node.js Environments**

   In cases where Scala.js is not running under Node.js (e.g., in a browser), the implementation should gracefully handle the absence of `process.env`:

   ```scala
   // zio/SystemPlatformSpecific.scala (updated)

   private[zio] trait SystemPlatformSpecific { self: System.type =>

     def env(variable: => String)(implicit trace: Trace): IO[SecurityException, Option[String]] =
       ZIO.attempt {
         if (js.typeOf(global.process) != "undefined" && js.typeOf(global.process.env) != "undefined") {
           val env = global.process.env.asInstanceOf[js.Dictionary[String]]
           env.get(variable)
         } else {
           None
         }
       }.refineToOrDie[SecurityException]
   }
   ```

**Workaround:**

As a temporary workaround, users can define their own method to access environment variables in Scala.js:

```scala
def getEnv(key: String): Option[String] = {
  val env = global.process.env.asInstanceOf[js.Dictionary[String]]
  env.get(variable)
}
```

**Environment:**

- **ZIO Version:** 2.1.11
- **Scala.js Version:** 1.17.0
- **Node.js Version:** 22.11.0
- **Build Tool:** sbt 1.10.5

**Comment by kyri-petrou** [comment]
I'm kind of conflicted here. While I think the change on ZIO's side to enable this is rather small, I also get the feeling that this is perhaps that should be supported by ScalaJS instead?

**Comment by mhriemers** [comment]
I tried but since `process` is not part of ECMAScript, [the changes were not accepted by the Scala.js contributors](https://github.com/scala-js/scala-js/pull/5067). FWIW, [cats-effect](https://github.com/armanbilge/cats-effect/blob/series/3.x/std/js/src/main/scala/cats/effect/std/EnvCompanionPlatform.scala) has something similar.
