### ISSUE TITLE
ZStream#mapZIOPar performance drop between 2.1.6 and 2.1.12

### ISSUE THREAD

**Issue by gkfabs** [zio/zio#9308]
I notice an important drop of performance between 2.1.6 and 2.1.12 when I am running this piece of code:

```scala
import zio._
import zio.stream._

object Main extends ZIOAppDefault {

  final def run =
    ZStream
      .fromIterable(Range(0, 150_000).toList)
       .mapZIOPar(java.lang.Runtime.getRuntime.availableProcessors * 16)(i => ZIO.succeed(i + 1).delay(10.millis))
      .run(ZSink.collectAll.timed)
      .flatMap(test => ZIO.debug(test._2.toString))
      .exitCode
}
```

On 2.1.6 it takes 5s, when on 2.1.12 it takes 1min25s.

I was wondering what could be the cause.

**Comment by regiskuckaertz** [comment]
2.1.3 had an implementation that was extremely fast but had to be rolled back due to a memory leak (https://github.com/zio/zio/releases/tag/v2.1.7)

**Comment by kyri-petrou** [comment]
How many processors does your machine have?

Also, can you also check what's the total time required when using `v2.1.11`?

**Comment by regiskuckaertz** [comment]
```scala
% scala-cli run stream.scala
Compiling project (Scala 3.5.0, JVM (21))
Compiled project (Scala 3.5.0, JVM (21))
[hint] ./stream.scala:1:15
[hint] "zio-streams is outdated, update to 2.1.12"
[hint]      zio-streams 2.1.6 -> dev.zio::zio-streams:2.1.12
[hint] //> using dep dev.zio::zio-streams:2.1.6
[hint]               ^^^^^^^^^^^^^^^^^^^^^^^^^^
PT9.285469484S
% time scala-cli run stream.scala
Downloading 2 dependencies
Compiling project (Scala 3.5.0, JVM (21))
Compiled project (Scala 3.5.0, JVM (21))
[hint] ./stream.scala:1:15
[hint] "zio-streams is outdated, update to 2.1.12"
[hint]      zio-streams 2.1.11 -> dev.zio::zio-streams:2.1.12
[hint] //> using dep dev.zio::zio-streams:2.1.11
[hint]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
PT1M47.825304188S
% time scala-cli run stream.scala
Compiling project (Scala 3.5.0, JVM (21))
Compiled project (Scala 3.5.0, JVM (21))
PT1M39.596419131S
```

**Comment by kyri-petrou** [comment]
After looking a bit into it, it seems that the main issue here is that parallelism is effectively capped / bounded by the buffer size. AFAICT reason that you're observing a better performance with v2.1.6 is that the implementation used in that version used the value of the `n` parallel argument as the default buffer size. However, we had to revert that change as users were using `Int.MaxValue` as the parallelism level which was causing OOM issues when sizing the internal buffer queues.

This should give you a performance similar to v2.1.6

```scala
import zio._
import zio.stream._

object Main extends ZIOAppDefault {

  // NOTE: For `bufferSize`, it's better for this to be a power of 2 but leaving as is for demo purposes
  val n = java.lang.Runtime.getRuntime.availableProcessors * 16

  final def run =
    ZStream
      .fromIterable(Range(0, 150_000).toList)
      // Note `(n, n)`
      .mapZIOPar(n, n)(i => ZIO.succeed(i + 1).delay(10.millis))
      .run(ZSink.collectAll.timed)
      .flatMap(test => ZIO.debug(test._2.toString))
      .exitCode
}
```

**Comment by kyri-petrou** [comment]
Going to close this issue, but feel free to reopen if you think that the solution I proposed above doesn't match your needs. I will open a separate issue to improve the default buffer size for finite parallelism levels when using `mapZIOPar`
