### ISSUE TITLE
Fix microsite to use new organization

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio#932]
I did a couple changes manually in the published microsite but they need to be done in the source (`website` folder) for future releases:
- change gitter chatroom to ZIO/Core
- change github URL and stargazers URL to point to the new repo https://github.com/zio/zio
- change siteConfig.js:
```
title: 'ZIO', // Title for your website.
url: 'https://zio.dev',
baseUrl: '/',
projectName: 'zio',
organizationName: 'zio',
```

**Comment by softinio** [comment]
Resolved by #933
