### ISSUE TITLE
.provideSome triggers WartRemover ExplicitImplicitTypes error in ZIO 2.1.13

### ISSUE THREAD

**Issue by thijsnissen** [zio/zio#9320]
A slightly modified version of #8936 . This time it only affects the use of `.provideSome`.

At work we are expected to use [WartRemover](https://www.wartremover.org/). We use Scala `2.13.15`. The minimized example below compiles with ZIO `2.1.12`. Since `2.1.13`, WartRemover throws the following error:

```
[error] [wartremover:ExplicitImplicitTypes] implicit definitions must have an explicit type ascription
[error]     ZLayer.make[Foo with Bar](fooLayer, barLayer)
[error]                              ^
[error] 
[error] [wartremover:ExplicitImplicitTypes] implicit definitions must have an explicit type ascription
[error]       .provideSome[Bar](fooLayer)
[error]                        ^
```
Minimized example (using scala-cli):

```
//> using scala "2.13.15"
//> using dep "dev.zio::zio:2.1.13"
//> using plugin "org.wartremover::wartremover:3.2.4"
//> using options "-P:wartremover:traverser:org.wartremover.warts.ExplicitImplicitTypes"

import zio._

case class Foo(bar: Bar)
case class Bar(baz: String)

object Main extends ZIOAppDefault {
  val fooLayer: URLayer[Bar, Foo] = 
    ZLayer.fromFunction(Foo(_))

  val barLayer: ULayer[Bar] = 
    ZLayer.succeed(Bar(""))

  val fooBarLayer: ULayer[Foo with Bar] = 
    ZLayer.make[Foo with Bar](fooLayer, barLayer)

  val program: URIO[Bar, ExitCode] =
    ZIO
      .service[Foo]
      .provideSome[Bar](fooLayer)
      .exitCode

  val run: UIO[ExitCode] =
    program.provide(barLayer)
}
```

**Update:**
- `Zlayer.make` also seems affected. I updated the error message and example code.
- Some of our projects also fail on just `.provide`, although I cannot replicate that in this minimized example.

**Comment by joroKr21** [comment]
That sounds like an issue with WartRemover though, because the type is provided

**Comment by kyri-petrou** [comment]
@joroKr21 I just remembered why I used explicit instead of implicit vals in the macros. The problem is [here](https://github.com/zio/zio/pull/9281/files#diff-3687b3214db43cb906810b783c4a4c42e26b43fb65fb7430778483b02c5fdabdR83). The macros infer the type of the implicit `Trace` as `Object`, and wartremover doesn't like this. Since wartremover is a commonly used linting tool, we have to fix this.

Could you please revert the implementation back to using explicit values?

**Comment by joroKr21** [comment]
> The macros infer the type of the implicit Trace as Object

That doesn't sound right, why do you think that's the case?
```scala
type Trace = Tracer.instance.Type with Tracer.Traced
```

> and wartremover doesn't like this

That sounds like a but in Wartremover. Why should `Object` be treated specially? It doesn't mean there was no type ascription provided.

**Comment by kyri-petrou** [comment]
@joroKr21 we can try and get this resolved at wartremover, but this is going to take time (assuming it's even possible to fix) and our change is preventing users from updating to the latest ZIO version(s).

In short: we should followup with the wartremover team but also revert the change on our side to unblock users

**Comment by joroKr21** [comment]
I think you should definitely submit an issue to Wartremover @thijsnissen 
Because as it is right now it's actually making us introduce warts in our code to work around the false positive.
@kyri-petrou can't we add a comment to disable this wart check?

**Comment by thijsnissen** [comment]
Thank you for addressing this issue. As suggested I have reported the issue to Wartremover as well under [#1155](https://github.com/wartremover/wartremover/issues/1155).
