### ISSUE TITLE
In documentation of ref, warning about immutable data have a mistake.

### ISSUE THREAD

**Issue by pocorall** [zio/zio#9350]
https://zio.dev/reference/concurrency/ref/

In the page above, there is a warning about use of immutable data:

```
// Compiles but don't work properly
var init = 0
val counterRef = Ref.make(init)
// To correct this, we should change the init to be immutable:
val init = 0
val counterRef = Ref.make(init)
```

However, that example seems flawed. In JVM, primitive typed variables (`init` in this case) are copied when it is passed as a function parameter. So, the two examples above are basically the same program. The scala keyword `val` and `var` are about (im)mutability of a reference, not the data. As a proper revision of the text, I propose the change as below:

```
// Compiles but don't work properly
val init = collection.mutable.Seq(1,3,5)
val counterRef = Ref.make(init)
// To correct this, we should change the init to be immutable:
val init = Seq(1,3,5)
val counterRef = Ref.make(init)
```

**Comment by khajavi** [comment]
@pocorall 
That makes sense. Could you please create a pull request, if you don’t mind?

**Comment by varshith257** [comment]
/attempt #9350

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;6 ZIO bounties <br/> + 15 bounties from 9 projects | <div align="center">Rust, Scala, <br />Go & more</div> | <div align="center">﹟9352</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm424y3on000fl103yr0lwrj4/cancel-attempt) |
