### ISSUE TITLE
Ambiguous implicit value for zio.Trace with ZIO 2.1.13

### ISSUE THREAD

**Issue by cipriandrei10** [zio/zio#9352]
```scala
import zio._

object Dummy {
  trait Dep

  def call[R: Tag](implicit trace: Trace): URIO[R, Unit] =
    ZIO
      .serviceWithZIO[Dep](_ => ZIO.service[R].unit)
      .provideSome[R](ZLayer.succeed(new Dep {}))
}
```
This snippet fails with:
```bash
ambiguous implicit values:
[error]  both value trace of type zio.Trace
[error]  and value trace$macro$4 of type zio.Trace
[error]  match expected type zio.Trace
```
`scala: 2.13.15`
`zio: 2.1.13`
Previous versions do not have this problem, [scastie link](https://scastie.scala-lang.org/cipriansofronia/4eMtdcFkSieKOik3K1nxWA/6).

**Comment by varshith257** [comment]
/attempt #9352

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;6 ZIO bounties <br/> + 15 bounties from 9 projects | <div align="center">Rust, Scala, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm424twam0002l103fq8s3g4a/cancel-attempt) |

**Comment by varshith257** [comment]
The issue occurs due to introducing of given trace in `LayerMacroUtils`. The compiler getting struggle to determine the trace which implicitly given.

I am thinking of using `summonFrom`

**Comment by joroKr21** [comment]
This is my fault, I didn't consider anyone would be passing the trace implictly (explicitly)
