### ISSUE TITLE
Tracer. instance does regex pattern match for filtered out logs 

### ISSUE THREAD

**Issue by plokhotnyuk** [zio/zio#9412]
Currently `Tracer.instance.unapply` is called for each `ZIO.log` expression before checking of logging level and has too much overhead (see flame graphs for allocations and CPU cycles below) due to [pattern matching with regex](https://github.com/zio/zio/blob/349c3c65049ce311d720a024e410217dd5af5628/stacktracer/src/main/scala-3/zio/internal/stacktracer/Tracer.scala#L27)

### Allocations

![image](https://github.com/user-attachments/assets/67231a14-d561-42d9-b79b-c3bec7319101)

### CPU cycles

![image](https://github.com/user-attachments/assets/b2129e38-b153-4461-b4b0-26dfe086c9ea)

### Steps to reproduce

1. Create `trace_logback.scala` with the following code:
```scala
//> using resourceDir .
//> using dep "dev.zio::zio:2.1.13"
//> using dep "dev.zio::zio-logging:2.4.0"
//> using dep "dev.zio::zio-logging-slf4j2:2.4.0"
//> using dep "org.slf4j:slf4j-api:2.0.16"
//> using dep "ch.qos.logback:logback-classic:1.5.12"

import zio.*
import zio.logging.backend.SLF4J

object TestApp extends ZIOAppDefault {
  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] = Runtime.removeDefaultLoggers >>> SLF4J.slf4j

  val run: ZIO[Any, Nothing, Unit] = ZIO.whileLoop(true)(ZIO.log("xxx"))(_ => ())
}
```
2. In the same directory create `logback.xml` with the following settings:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%d{HH:mm:ss.SSS} [%thread] [%kvp] %-5level %logger{36} %msg%n</Pattern>
        </layout>
    </appender>
    <root level="error">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```
3. Run with [scala-cli](https://scala-cli.virtuslab.org/install/):
```sh
scala-cli tracer_logback.scala
```
4. Get a process ID of the running `TestApp`:
```sh
jps | grep TestApp
```
5. Run [async-profiler](https://github.com/async-profiler/async-profiler/releases/tag/nightly) with the following options:
```sh
./asprof -d 30 -e cycles -i 100000 -f cycles_logback_error.html <TestApp_process_ID>
```

**Comment by guizmaii** [comment]
@plokhotnyuk Thanks for this very detailed report! 🙂
Could you please retry your measurements with these changes https://github.com/zio/zio/pull/9414, please?

(Hopefully, my code is correct 😅)

**Comment by plokhotnyuk** [comment]
It seems that both old and new implementations of `unapply` can throw exception in `toInt` call for the invalid input.

But the main question is: why these calls of `Tracer.instance#unapply` are happening before checking of the log priority?

**Comment by guizmaii** [comment]
> It seems that both old and new implementations of unapply can throw exception in toInt call for the invalid input.

It can probably never happen, so that's a non-issue, I think.

> why these calls of Tracer.instance#unapply are happening before checking of the log priority?

Looking at the code, adding these traces information to the logs doesn't seem to be correlated to the log priority.
Not sure to understand your question 🤔

**Comment by plokhotnyuk** [comment]
Probably the main question should be addressed to zio-logging.

In the `logback.xml` I set `<root level="error">` that means all info level messages should be skipped, so no need for tracing data to be reparsed from the stringified representation.

**Comment by plokhotnyuk** [comment]
@guizmaii I've made `sbt +publishLocal` for your branch and tested your improvements with the following changes in the script:
```scala
//> using repositories ivy2Local
//> using dep "dev.zio::zio:2.1.13+75-e6a57916+20241215-0916-SNAPSHOT"
```
Instead of:
```scala
//> using dep "dev.zio::zio:2.1.13"
```
Results are much better, here is how the flame graph for CPU cycles looks now:

![image](https://github.com/user-attachments/assets/1ad9fbca-f01c-4c8e-b204-407f4e022def)

**Comment by guizmaii** [comment]
@plokhotnyuk Thank you for that :)

It is interesting to see how `parseInt` is expensive

BTW, if you wanna try, I'm making another set of optimisations here: https://github.com/zio/zio/pull/9416

**Comment by plokhotnyuk** [comment]
@guizmaii Before testing both approaches I would replace string instantiation and number parsing by the following code:
```scala
      val closingParentesisIdx = length - 1
      idx = colonIdx + 1
      var line = 0
      while (idx < closingParentesisIdx) {
        val c = trace.charAt(idx)
        idx += 1
        if (c < '0' || c > '9' || line > 214748364 || {
          line = line * 10 + (c - '0')
          line <= 0
        }) return null
      }
      ParsedTrace(location, file, line)
```
It makes parsing pure with less allocations and CPU overhead.

Also, I think that usage of `String` for traces is for the reason to avoid allocations and CPU overhead on each `ZIO` operator with `Trace` parameter until it need to be logged.

**Comment by guizmaii** [comment]
@plokhotnyuk What is `214748364` in `line > 214748364`? 🤔

**Comment by plokhotnyuk** [comment]
It is for checking of `Int` overflow before multiplication on 10: `214748364 == Int.MaxValue / 10`.

[A similar check you can spot in jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala/blob/8f6c06d1f4db830fb9e302bc96da969d1bd8e27b/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L2090-L2093), but it is done using negative `Int` value to simplify handling a case with `Int.MinValue`.

**Comment by guizmaii** [comment]
Re-opened because we can go further in the optimisation. See https://github.com/zio/zio/issues/9412#issuecomment-2544726681

**Comment by guizmaii** [comment]
@plokhotnyuk Could you maybe submit a PR with this optimisation, please?

**Comment by plokhotnyuk** [comment]
@guizmaii I've proposed a PR with improvements for line number parsing and clean up for implementation of other steps: https://github.com/zio/zio/pull/9433

EDIT: 
Below is a flame graph for CPU cycles that shows more efficiency for `Tracer$.unapply` with this PR 
![image](https://github.com/user-attachments/assets/a43b2688-33b6-4ace-8ad7-dc41f41e3393)

Also, I propose to follow up with _possible_ improvements for `zio.logging.backend.SLF4J$Slf4jLogger.apply` and `zio.logging.LoggerNameExtractor$FnExtractor.apply` (in the related repo) to don't parse traces for lower level messages that are filtered out by logger and to don't parse a whole trace just to extract partial location accordingly.

I thought that as a workaround I can use `loggerName` annotations to avoid logger name extractions and trace parsing under the hood.

Below is a flame graph for the reproducing code with added `package logging` and the log operator annotation, like here: `ZIO.log("xxx") @@ zio.logging.loggerName("logging.TestApp")`.

It shows that with logger name annotations there is another overhead with `ZIO$LogAnnotate.apply`:
![image](https://github.com/user-attachments/assets/fae88ea6-6ed9-4517-ba2c-939dec0f9b0d)

**Comment by guizmaii** [comment]
@plokhotnyuk Can you open another issue for these following optimisations, please?
