### ISSUE TITLE
Support Scala 2.11?

### ISSUE THREAD

**Issue by denisgarci** [zio/zio#963]
Hi,
I noticed that after the change from TravisCI to CircleCI the support for Scala 2.11 has been dropped. I'm not sure if that's intentional. Should it be enable again?

**Comment by iravid** [comment]
Ouch, that definitely sounds like an oversight. cc @softinio

**Comment by softinio** [comment]
Thanks for reporting this will have a PR to correct this within 24 hours probably tonight.

**Comment by denisgarci** [comment]
@softinio Thank you!
