### ISSUE TITLE
Add user provided canceler to effectBlocking

### ISSUE THREAD

**Issue by freskog** [zio/zio#966]
Some blocking effects can not be canceled by performing a Thread.interrupt, but there are other ways of ensuring the effect is canceled. 

One example is 
```scala
Task.effect(new ServerSocket(9000)).flatMap(
      l => effectBlocking(l.accept())
 )
```
This can not be interrupted using the normal interruption mechanism of ZIO. If we added a parameter to effectBlocking letting the user specify how to cancel a blocking effect we could have something like:

```scala
Task.effect(new ServerSocket(9000)).flatMap(
      l => effectBlocking(l.accept())(Task.effect(l.close().orDie)
)
```

Right now the user is forced to hack around this (essentially linking an interrupt of a parent fiber to calling l.close)

**Comment by iravid** [comment]
Interesting. Definitely a usecase we should address!

I think that the main property of `effectBlocking` is that it uses `Thread.interrupt`, and calls it repeatedly until the thread dies using short sleeps.

I don't think that sort of behavior is general enough to make `effectBlocking` use a user defined canceller. But maybe you could use `effectAsyncInterrupt` to run the effect inside `blocking` and return the user's canceller? If that works we could package that into a combinator in the blocking package.

**Comment by iravid** [comment]
Something like this: https://github.com/zio/zio-kafka/blob/master/src/main/scala/zio/kafka/client/Consumer.scala#L38

**Comment by freskog** [comment]
@iravid yeah, that's a really neat way to do it. Will have a stab at this.

**Comment by freskog** [comment]
@iravid 

I tried using the approach suggested above,

```scala
    def effectBlockingCancelable[A](effect: => A)(cancel: UIO[Unit]): ZIO[R, Throwable, A] =
      ZIO.effectAsyncInterrupt { cb =>
        cb(effectBlocking(effect))
        Left(cancel)
      }
```

However, my testing indicates that this doesn't work. 

```scala
  def blocking = {
    val released = new AtomicBoolean(false)
    (() => while(!released.get()) {
      try {
        Thread.sleep(10L)
      } catch {
        case _:InterruptedException => Thread.interrupted()
    }
    }, UIO.effectTotal(released.set(true)))
  }

  def e4 = {
    val (block, cancel) = blocking
    val res = unsafeRun(effectBlockingCancelable(block())(cancel).timeout(Duration.Zero))
    res must beNone
  }
```

This just hangs forever, but if I try the approach of forking of the effect into it's own fiber and set the canceler on the parent fiber it works as expected:

```scala
    def effectBlockingCancelable[A](effect: => A)(cancel: UIO[Unit]): ZIO[R, Throwable, A] =
      blocking(ZIO.effect(effect)).interruptChildren.fork.flatMap(_.join).onInterrupt(cancel)
```

Is there a reason to not use the second approach, or did I misunderstand your suggestion around using effectAsyncInterrupt?

**Comment by freskog** [comment]
And naturally, as soon as I wrote that I realized that this is also an option

```scala
    def effectBlockingCancelable[A](effect: => A)(cancel: UIO[Unit]): ZIO[R, Throwable, A] =
      ZIO.effectAsyncInterrupt { cb =>
        cb(blocking(ZIO.effect(effect).fork.flatMap(_.join)))
        Left(cancel)
      }
```

I'm not sure which option is best here.
