### ISSUE TITLE
Flaky ZManagedSpec

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio#996]
This happens sometimes: 

```
[info] ZManagedSpec
[info]   ZManaged.make
[info]     + Invokes cleanups in reverse order of acquisition.
[error]     x Properly performs parallel acquire and release.
[error]  2 != 1 (ZManagedSpec.scala:146)
[info]     + Constructs an uninterruptible 
```

**Comment by spf3000** [comment]
I played around a little with this - I couldn't reproduce the error - I tried upgrading to a property based test - see above commit. Still I couldn't reproduce it so it's still open.

**Comment by iravid** [comment]
@spf3000 can you try using `nonFlaky` from `RTSSpec`? Usually helps to flush these out

**Comment by spf3000** [comment]
@iravid thanks for the suggestion - I tried above with nonflaky - even upped the retries to 1000. Still passed. Although I had to remove the unsafeRun to make it compile - perhaps by doing that I may have inadvertently fixed the issue. What would you suggest?

**Comment by iravid** [comment]
This is beyond me 🤷🏽‍♂️We've been having issues related to fiber supervision and garbage collected, so I'm tempted to suggest trying with a smaller heap size. Though that runs the risk of just running out of memory.

**Comment by ghostdogpr** [comment]
I suspect this has been fixed somehow because I haven't seen it in months. Let's reopen if it comes again.
